### ISSUE TITLE
Before posting an issue.... / Bevor man ein Issue erstellt....

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS22_AutoDrive#1]
Bevor du ein Issue meldest:
- schau nach, ob du die aktuellste Version von AutoDrive nutzt und falls nicht, dann erst aktualisieren und prüfe anschließend, ob der Fehler/das Problem noch besteht
- überprüfe dein Log auf "Error" und "Warning" und falls welche vorhanden sind, dann versuche sie erstmal zu beheben
- wenn das Log ohne (kritische) Fehler ist, dann versuche das Problem auf einer Standardkarte ohne zusätzliche Mods und nur mit aktiviertem AD nachzustellen
- taucht der Fehler dort nicht auf, dann versuche nach und nach andere Mods zu aktivieren, ob der Fehler dann auftaucht
- zu einigen Problemen und Fragen findet man auf Youtube etliche Kanäle und Videos, welche man sich anschauen sollte

Sollte das alles nicht helfen, dann erst erstelle ein Issue, in welches du bitte alle Infos reinpostet. Je mehr Infos wir bekommen, desto einfacher kann ein Problem nachvollzogen und dir schneller geholfen werden. Dazu gehören z.Bsp. welche Map, welche Fahrzeuge, genaue Beschreibung der Situation und das Log.

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

Before you report an issue:
- check if you are using the latest version of AutoDrive and if not, update first and then check if the bug/problem still exists
- check your log for "Error" and "Warning" and if there are any, try to fix them first
- if the log is without (critical) errors, then try to recreate the problem on a standard map without additional mods and only with AD enabled
- if the error does not appear there, try to activate other mods bit by bit, if the error appears
- to some problems and questions you can find several channels and videos on Youtube, which you should watch

If all this doesn't help, please create an issue and post all informations in it. The more information we get, the easier it is to understand the problem and so we can help you faster. This includes e.g. which map, which vehicles, exact description of the situation and the log.

**Comment by bennarbed** [comment]
Bonjour,
depuis la maj 1.4 "autodrive " ne fonctionne pas correctement.
En effet cela se passe sur l'utilisation de plusieurs véhicules.
il y a des missions qui changent( silo A, passe champ 10)
pouvez vous m'aider?!
Cordialement
