### ISSUE TITLE
No option for "continue when full"

### ISSUE THREAD

**Issue by SunkenL** [Stephan-S/FS22_AutoDrive#10]
Hello and thank you for this great mod!!

When i make a route to fill my row of greenhouses with water, the tractor stops at the first one and waits.
I know the setting "drive on when empty" but also "drive on when full" would be nice in this situation(maybe with a timer setting also).

Eager to see what you think of this?

**Comment by Iwan1803** [comment]
Could you paste your and a screenshot of the situation in here?

**Comment by ArtV-Nef** [comment]
there is the same problem
![2021-12-19_23-24-04](https://user-images.githubusercontent.com/59769343/146689764-6a4856ba-8046-4088-90fa-136972abc347.jpg)

**Comment by SunkenL** [comment]
Exactly this ArtV-Nef shows!

**Comment by Iwan1803** [comment]
You are not using distributed offloading as there is only 1 destination point on the route. Only by using the distributed mode it will continue automatically if a trigger is full.

**Comment by Iwan1803** [comment]
Yes, that should help.

**Comment by Gariot** [comment]
This is basically #171 
AD wont continue because the greenhouse technically is never full for longer than one second. The greenhouse will use about 1-2 Liter almost instantly and AD fills that up at the same time. Thats the reason AD wont continue and stops there at the first greenhouse even if cycle unload is enabled.

**Comment by Axel32019** [comment]
You may check if it is working with the dev version: https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
