### ISSUE TITLE
Siliermittel tanken geht nicht

### ISSUE THREAD

**Issue by Bliro** [Stephan-S/FS22_AutoDrive#100]
Halole,
Wenn ich die 2.0.0.2 im MP auf einem Dedi-Server aktiv habe, kann ich mit meinem Hexler Claas Jaguar 960 und dem Ladewagen Schuitemaker Rapide 580V kein Siliermittel auffüllen.

Ich fahre mit den Geräten an die entsprechende Ladeseite und bekomme keinen Trigger zum beladen. Automatisch tanken und reparieren habe ich deaktiviert. In den Spieleinstellungen ist das automatische Einkaufen auch deaktiviert

**Comment by Axel32019** [comment]
Hallo @Bliro ,
Soll AD oder möchtest Du selbst von Hand laden ?

**Comment by Bliro** [comment]
Wir haben AD gerade neu auf den Server gemacht und können das aktuell nicht mehr reproduzieren.
Manchmal ist der LS22 wohl etwas zickig.

Es ist passiert als ich manuell an die Palette, an den gewöhnlichen "Ladepunkt" für Siliermittel heran gefahren bin. 

Aber bis jetzt "Problem Solved bzw nicht rekonstruierbar"

Danke für die Mühe und die Arbeit am AD :)
