### ISSUE TITLE
"Drescher" mit Rückfahrfunktion

### ISSUE THREAD

**Issue by JuniorKDK** [Stephan-S/FS22_AutoDrive#1001]
Wenn man den Anbaufeldhäcksler von Lacotec beispielsweise wie ich hier am Xerion nutzt und dann die Kabine dreht um damit zu häckseln, wollen die Abfahrer den Xerion trotzdem in der eigentlichen Fahrtrichtung anfahren. Ein nebenher fahren ist so natürlich nicht möglich.
![Farming Simulator 22 Screenshot 2023 10 01 - 12 09 18 47](https://github.com/Stephan-S/FS22_AutoDrive/assets/101211331/8870095f-fe1f-4041-9d13-e2e33191c504)

**Comment by Axel32019** [comment]
duplicate #690
