### ISSUE TITLE
Open combine pipe only when the combine got a valid unloader.

### ISSUE THREAD

**Issue by Tensuko** [Stephan-S/FS22_AutoDrive#1002]
It happens too often that the combine extend the pipe without any reason, when driving with CP.
If ppl are willed to have the AD unloader to unloaded the CP combine, they both need the same WP Target anyway and you can use that check to decide if the pipe opening should be done or not.

For me I just removed this.
```
function AutoDrive:combineIsCallingDriver(combine)	--only for CoursePlay
	local openPipe,_ = ADHarvestManager.getOpenPipePercent(combine)
	return openPipe or ADHarvestManager.doesHarvesterNeedUnloading(combine, true)
end
```
That do the trick for me becouse I don't use the AD Unloader.
But you could add in a check for valid unloader connection (that same WP thingy, not sure how you call it).
That way it should only happen if the combine got an AD Unloader.

Opened Issue due to another request or comment on our side.
https://github.com/Courseplay/Courseplay_FS22/issues/2825

**Comment by marcelmmx** [comment]
Removing the said function stops the pipe from unfolding, but also the driver from unloading the combine. The only option then is to unload manually or using CP, which has a load of other issues. If possible, please fix this behaviour in AD and tie the trigger to something else - not openPipe.

**Comment by Tensuko** [comment]
Did I say remove that option?
I said "But you could add in a check for valid unloader connection" and "That way it should only happen if the combine got an AD Unloader."

**Comment by BippyMiester** [comment]
> For me I just removed this.

So yes, @Tensuko you did.

**Comment by Tensuko** [comment]
Omg.... for ME I did that becouse I don't use the AD unloader - I did NOT say dev from AD should remove it....

Read it correctly!

**Comment by Axel32019** [comment]
> It happens too often that the combine extend the pipe without any reason, when driving with CP. If ppl are willed to have the AD unloader to unloaded the CP combine, they both need the same WP Targetanyway and you can use that check to decide if the pipe opening should be done or not.
> 
> For me I just removed this.
> 
> ```
> function AutoDrive:combineIsCallingDriver(combine)	--only for CoursePlay
> 	local openPipe,_ = ADHarvestManager.getOpenPipePercent(combine)
> 	return openPipe or ADHarvestManager.doesHarvesterNeedUnloading(combine, true)
> end
> ```
> 
> That do the trick for me becouse I don't use the AD Unloader. But you could add in a check for valid unloader connection (that same WP thingy, not sure how you call it). That way it should only happen if the combine got an AD Unloader.
> 
> Opened Issue due to another request or comment on our side. [Courseplay/Courseplay_FS22#2825](https://github.com/Courseplay/Courseplay_FS22/issues/2825)

That is one small part of the complete unloader topic, which need some update in future, but is complex spread over several functions, tasks,  etc., not done in some minutes!

**Comment by Axel32019** [comment]
will improve with [https://github.com/Stephan-S/FS22_AutoDrive/commit/8b92562af00d91a19d8e15271c27a747226b5b5d](url)

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.8
