### ISSUE TITLE
All Issues Should Be Submitted In English, If At All Possible

### ISSUE THREAD

**Issue by BippyMiester** [Stephan-S/FS22_AutoDrive#1003]
English is considered by most to be a [lingua franca](https://en.wikipedia.org/wiki/English_as_a_lingua_franca) for the developer community. Obviously I think that this project should want to be as inclusive as possible, but deciphering the (often vague) issues from someone who is new or old to software development or the open-source community is difficult enough already, without the language barrier.

Most of the time (but not always), a non-English-speaking developer will run their text through Google Translate before posting. However this does little more beyond saving the developer a click, as they still have to attempt to decipher the machine translation. In fact this is not always successful, and usually their response is to say something like "sorry, I do not understand what you are trying to say", or worse off, the issue doesn't get solved at all.

Now I get it, Open-source maintenance is often volunteer work. I understand the desire to be welcoming to everyone. To some degree that is certainly possible, but this approach doesn't scale. It is reasonable to expect that people who bring their problems to a community do their share of the work and present the problem in a manner that can be answered effectively. There needs to be a balance of two forces: limited capacity by experts who are interested and able to answer these problems, and a reputation of helpfulness in the wider community. Considering that all the accompanying wiki articles, README, and documentation is written in English, I think that asking for comprehensible English in this projects issues, is a reasonable requirement.

This problem will only solve itself if the project becomes so popular that national/language-specific communities appear with their own help resources. While there are people who want to contribute to help, but don't understand the German language, its impossible to find an **_accurate and timely_** solution to the problem if a language barrier exists.

As stated in my first paragraph, English is a [lingua franca](https://en.wikipedia.org/wiki/English_as_a_lingua_franca) and most if not all programming languages use English as their primary language. I think the same should be extended to this projects GitHub Issues, as the project has taken a huge surge in English primary countries. Those who do not write or speak English would obviously be exempt here, but should not expect a timely response.

**Comment by Tensuko** [comment]
- There are ppl who don't speak english
- Leave this to the dev of this project how to handle this

**Comment by BippyMiester** [comment]
> * There are ppl who don't speak english

I literally said:
> Those who do not write or speak English would obviously be exempt here, but should not expect a timely response.

Clearly you didn't take the time to read my post. Its ok. Not a problem.

> * Leave this to the dev of this project how to handle this

Thats literally why I made this issue to bring attention to it. Without the issue being raised, nobody would know about the issue, or the challenges that arise from issues being brought forth by users, as clearly outlined in initial post. The dev team of the project can do as they please. However, my statement still stands, and I put a ton of effort into writing my issue. I don't know an accurate or effective solution to this issue, and thats why I wanted feedback.

However, your negativity isn't appreciated nor is it constructive. As stated previously, clearly you didn't read my post or else you wouldn't have missed the last line. So, unless you have something constructive to contribute to the conversation, like coming up with an actual solution to the issue, its probably best to stay out of it and wait for the dev team to respond before replying. This is for the sake of reducing spam, confusion, and frustration.

**Comment by ThomasMatern** [comment]
The entire dev team speaks German as their first language, yet, somehow puts up all the effort to deal with people who don't speak German. <sarcasm> It would be a lot easier for the dev team if all issues were submitted in German only </sarcasm>
You are raising an issue that simply isn't one. Forcing someone to report issues in a language they are not really comfortable in, will result in low-quality bug reports - or no reports at all. 

>  Obviously I think that this project should want to be as inclusive as possible [...]
Exactly. Hence, German and English are accepted here.

> It is reasonable to expect that people who bring their problems to a community do their share of the work and present the problem in a manner that can be answered effectively.
Exactly. Hence, German and English are accepted here.

> Considering that all the accompanying wiki articles, README, and documentation is written in English, I think that asking for comprehensible English in this projects [sic] issues , is a reasonable requirement.
Nope, it just shows how much effort was put into this to make this project accessible to a wide user base. 

Also, telling off the main contributor of CoursePlay doesn't earn you any brownie points here.

**Comment by TobiHH78** [comment]
> However, your negativity isn't appreciated nor is it constructive. As stated previously, clearly you didn't read my post or else you wouldn't have missed the last line. So, unless you have something constructive to contribute to the conversation, like coming up with an actual solution to the issue, its probably best to stay out of it and wait for the dev team to respond before replying. This is for the sake of reducing spam, confusion, and frustration.

That`s funny, as Tensuko is one of the Devs...

**Comment by Tensuko** [comment]
> That`s funny, as Tensuko is one of the Devs...

Well, at least for Courseplay, AutoDrive isn't my part but ofc we have a cooperation at some points :)

**Comment by Axel32019** [comment]
German or English is OK - see #1 -> no bug -> closed
