### ISSUE TITLE
Slurry Barrel always activates during Autodrive

### ISSUE THREAD

**Issue by Friendlyx** [Stephan-S/FS22_AutoDrive#1004]
Moin,

I have the issue that the slurry barrel always activates during normal drives. It only happens to the ones with an implement attacher and attached implement for example the bomech boom. Its only the Barrel which activates and not the implement.
This prevents the driver from going fast.

**Comment by andreasthu** [comment]
de:
Ich habe das selbe mit dem Holmer TV585, dem Zunhammer Tv585-Fass und dem Bomech TrackPack Ausleger.
auf der Strasse bei der Fahrt zum Füllen oder zum Feld wird das Fass eingeschaltet und somit ist die Beschleunigung und Endgeschwindigkeit bescheiden und die Fahrt dauert dementsprechend viel länger.
Wäre schön wenn das behoben werden könnte.

google-übersetzer:
I have the same thing with the Holmer TV585, the Zunhammer Tv585 barrel and the Bomech TrackPack boom.
On the road when driving to fill or to the field, the barrel is switched on and therefore the acceleration and final speed are modest and the journey takes much longer.
It would be nice if that could be fixed.

lg
andreas

**Comment by MacedonskyAlex** [comment]
RU:
Проблема с сеялками и сажалками, у которых есть бак для удобрений. А именно, если в меню игры установлено, что наймит пополняет удобрения, то при переждвижении на автодрайве расходуются деньги (в финансах видно, что покупаются удобрения)

Google Translite:
The problem is with seeders and planters that have a fertilizer tank. Namely, if it is set in the game menu that the hirer replenishes fertilizers, then when you wait on the autodrive, money is spent (in finance you can see that fertilizers are being purchased)

**Comment by Axel32019** [comment]
Giant's bugs - see #719, #662 -> closed

**Comment by andreasthu** [comment]
also ok,
hab mir #719 und #662 durchgelesen
habe beim \FS22_holmerPack\zunhammer\tv585.xml bei <turnOnVehicle> das <activatableFillUnit index="1" /> deaktiviert.
sieht in der xml jetzt so aus:
```
    <turnOnVehicle>
        <activatableFillUnits>
            <!-- <activatableFillUnit index="1" /> -->
        </activatableFillUnits>

        <sounds>
            <work template="SLURRY_03">
                <pitch indoor="0.75" outdoor="1.2" />
            </work>
        </sounds>
    </turnOnVehicle>
```
nun fährt der Holmer mit Fass ausgeschaltet zum Feld und cP schaltet dann alles ein:
![fsScreen_2023_10_18_08_03_28](https://github.com/Stephan-S/FS22_AutoDrive/assets/24860501/6a02817f-abf2-4f57-b94d-67f49e72adf5)
![fsScreen_2023_10_18_08_03_45](https://github.com/Stephan-S/FS22_AutoDrive/assets/24860501/c48df792-9d84-4b4a-83b8-cead450b05fc)
![fsScreen_2023_10_18_08_04_10](https://github.com/Stephan-S/FS22_AutoDrive/assets/24860501/2ccd1654-2178-43ad-ae5b-e3f392c1d690)
funktioniert im moment so gut.
werd aber noch beobachten obs durchs deaktivieren irgendwelche anderen Probleme gibt.
lg
andreas
