### ISSUE TITLE
Autodrive doesnt avoid fruit

### ISSUE THREAD

**Issue by dgonyou** [Stephan-S/FS22_AutoDrive#1010]
Autodrive while using a grain cart for unloading a harvester doesn't avoid fruit. It will say finding route, then cut across the field and crop to the harvester. I have avoid fruit active.

**Comment by Axel32019** [comment]
Large field? -> increase setting Pathfinder factor
To less headlands -> make more
Still not avoid fruit -> this is a fallback if no route could be found -> no bug
