### ISSUE TITLE
Unloader

### ISSUE THREAD

**Issue by MeCtiv770** [Stephan-S/FS22_AutoDrive#1011]
My unloader only drives behind the harvester
Avoid Fruit is off pls help

**Comment by bdbssb** [comment]
Yes please an answer to what I’m doing wrong. Same problem. Forage harvester gets hit in the rear and shoved all over. I even tried setting the forage pipe to lock in position. I did see somewhere that there is a call button?  Going to look in to this and check back.

**Comment by rohne83** [comment]
Which unloader, which harvester? Screenshots to depict situation. Otherwise noone will be able to help

**Comment by Axel32019** [comment]
no feedback -> closed
