### ISSUE TITLE
Combine Modus: Abladepunkt ändert sich zufällig

### ISSUE THREAD

**Issue by davemaul** [Stephan-S/FS22_AutoDrive#1014]
Moin!

Autodrive ändert beim Drescher abfahren bei bestimmten Events (z. B. nachdem ein Hänger abgeladen wurde / man den Play Button drückt) den Abladepunkt (bspw. auf der NF Marsch von Bahnhof zu EDEKA, etc.). Wichtig zu erwähnen ist, dass wir mit Better Contracts auf einem Dedi Server spielen und im Extremfall 10 Ernteaufträge mit eigenen Dreschern und Abfahrern parallel machen. Es war leider nicht wirklich ersichtlich, wann AD das Ziel zufallsbasiert anpasst. Kommt die Mod mit so vielen parallelen Aufträgen nicht klar?

Danke!

**Comment by JDTiger** [comment]
Du hast vmtl. das durchwechseln der Zielpunkte aktiviert.
Dies ist gedacht um Silage gleichmaessig ueber verschienene Bahnen in nem Silo zu verteilen.

**Comment by davemaul** [comment]
Oh Mann, Schicht 8. :D Das wird es gewesen sein. Wir hatten "nur entladen" an. Mir war nicht bewusst, dass AD dann die Ziele aus einem Ordner durchwechselt. It's not a bug, it's feature. 🤣

Besten Dank 👍
