### ISSUE TITLE
Arbeitslicht beim Be, -  Entladen geht immer an, egal ob "Ja" oder "Nein" in den Einstellungen ausgewählt wird.

### ISSUE THREAD

**Issue by CeberusOne** [Stephan-S/FS22_AutoDrive#1020]
Hallo, 

mir ist Folgender Fehler bzw. Problem aufgefallen.

Bei der Einstellung Arbeitslicht beim Be,- Entladen ist es scheinbar egal ob man "Ja" oder "Nein" auswählt, sobald der AD-Fahrer auf ein Feld kommt gehen sofort Alle Arbeitslichter an , auch wenn diese Einstellung auf " Nein" steht.

Ich habe es sowohl mit als auch ohne Mods getestet, Erlengrad + AD , sonst nichts und nur Vanilla-Fahzeuge , macht keinen Unterschied. 

Vielleicht sollte da mal drüber geschaut werden.  

mfg  Loki

**Comment by Axel32019** [comment]
Hallo, AD aktiviert auf dem Feld immer das Arbeitslicht wenn gemäß Spiel/Karte Nacht ist, so wie ein Giants-Helfer es auch tut:
https://gdn.giants-software.com/documentation_scripting_fs22.php?version=script&category=48&class=466#updateAILights6315
Die anderen Fälle lassen sich per Einstellung de-/aktivieren.
