### ISSUE TITLE
Collision detection "FS19" setting makes no sense

### ISSUE THREAD

**Issue by ThomasMatern** [Stephan-S/FS22_AutoDrive#1022]
I guess the FS19 setting does /something/ but from looking at the code, it does not make much sense.
Picking this option uses a bunch of FS19 collision bit definitions and uses them in FS22.
Looking through the list, subtracting 1 (because that's what FS19 did), we use the following collision detection bits in FS19 mode:

- mask_Non_Pushable_1 -> becomes bit-0, which is not used/"default" in FS22
- mask_Non_Pushable_2  -> becomes bit-1, STATIC_WORLD in FS22, good
- mask_static_world_1 -> becomes bit-2, which is deprecated in FS22 and marked as 'do not use'
- mask_static_world_2 -> becomes bit-3, STATIC_OBJECTS in FS22, good
- mask_tractors -> becomes bit-5, AI_BLOCKING in FS22, good
- mask_combines -> becomes bit-6, also deprecated and marked as 'do not use'
- mask_trailers -> becomes bit-7, also deprecated and marked as 'do not use'

If we want to have a FS19 mode, we should use the FS22 bits that are closest to the old FS19 behaviour.
The old bit definitions should be removed.

This is not a bug but rather a cleanup task.

**Comment by Axel32019** [comment]
FULL STOP!!!
This topic has a long and special history + background -> let's discuss in DC!
