### ISSUE TITLE
Verbesserungsvorschlag/Wunsch: Angabe Liefermenge

### ISSUE THREAD

**Issue by Akita83** [Stephan-S/FS22_AutoDrive#1023]
Es geht darum das man ja bei AD sagen kann hol zb Weizen aus dem Silo und bringe es zu Produktion x allerdings macht er dann den Anhänger voll es wäre super wenn da noch eine option rein kommen würde , die erlaubt ein zu geben ob voll oder das man selbst eintragen kann wie viel er holen soll und dann es weg bringt. LG

**Comment by Iwan1803** [comment]
Doppelt zu #973

**Comment by Iwan1803** [comment]
No further feedback -> closed!
