### ISSUE TITLE
Auto Drive keine Funktion mit Field-Creator

### ISSUE THREAD

**Issue by Woodpecker001** [Stephan-S/FS22_AutoDrive#1026]
Hallo zusammen ...schöne mod.. Aber hat schon jemand versucht ein Feld zu erstellen? ich schon ..leider ging es erst nicht. Nachdem ich Auto Drive deaktiviert hatte ging es. aber meine eingefahrenen Kurse waren nicht mehr da...von Auto Drive die Dateien wieder ersetzt ( vorher Sicherung gemacht ) siehe da die Kurse waren wieder da aber das Feld was ich erstellt hatte war wieder im normalen Zustand .Hat jemand eine LÖSUNG? danke schon mal im voraus. Udo

**Comment by Axel32019** [comment]
Hallo, Feld erstellen mit AD? Kenne ich nicht, nur mit CP. Ein paar Screenshots von dem was Du da machst / willst wären hilfreich.
Ich kann es mir gerade nicht vorstellen.

**Comment by Axel32019** [comment]
no update -> closed
