### ISSUE TITLE
error: running lua method 'update'.

### ISSUE THREAD

**Issue by Olliver05** [Stephan-S/FS22_AutoDrive#1029]
Hello!

I have this problem that when I load into a savegame it just load up to 50% then its just stand there would be nice if you guys can help what it is?
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/13398123/log.txt)

**Comment by daniloqz** [comment]
This is the same problem that I have been facing and I made a post previously, the developer asked for the log but I had resolved it by redoing the routes, but the problem persisted again, this error simply occurs and to stop it it needs to stop all the bots that are running . Furthermore, I noticed this only occurs in this new version. I will also leave my log.txt on my server with several moments with this error ("2023-11-17 21:52 Error: Running LUA method 'update'.
dataS/scripts/player/Player.lua(3110) : attempt to perform arithmetic on local 'inputValue' (a nil value)"

However, I don't have the problem logging into the server, it usually occurs randomly at some point when there is an AD bot doing some work.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/13398583/log.txt)

**Comment by regs1980** [comment]
@Olliver05 
You don't even use AD, why should AD be the problem.
Your problem is a mod problem.
Check every single mod for function.  

@daniloqz 
Your problem is a mod problem.
Check every single mod for function.
![2023-11-18 07_10_54-C__Users_Administrator_Desktop_log txt - Notepad++  Administrator](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/ad14478a-f2c2-49d8-b259-333e723b6f50)

**Comment by Olliver05** [comment]
> @Olliver05 You don't even use AD, why should AD be the problem? Your problem is a Mod problem. Check every single Mod for function.
> 
> @daniloqz Your problem is a Mod problem. Check every single Mod for function. ![2023-11-18 07_10_54-C__Users_Administrator_Desktop_log txt - Notepad++ Administrator](https://user-images.githubusercontent.com/13314443/283979781-ad14478a-f2c2-49d8-b259-333e723b6f50.jpg)

Yea I know it is a mod problem but I have checked all mods that I have played with erlyer but it wont work so I wonder if you can check exactly what mods it is that makes this error so I can unload that mod?

**Comment by Olliver05** [comment]
What can it be then because I have mail with giants and them sad that it seems to be a mod that make thees errors but what do you think it can be?

**Comment by regs1980** [comment]
@Olliver05 
Giants has replied to your mail that it is AutoDrive, although you do not have AutoDrive in your mod folder and do not use it.

**Comment by Olliver05** [comment]
@regs1980 
Whats meen with that?

**Comment by regs1980** [comment]
@Olliver05 
You are on the AutoDrive issue page.
If you have problems with AD then you are in the right place.
You are not using AD, your error comes from another mod in the folder.
Check all mods in your folder and contact the creator who created it. 
If you have found the error mod.

**Comment by Olliver05** [comment]
@regs1980 
okey I fixed the problem to come in to a savegame but now when I comes in it dosent exists any tractors in the shop the hole shop is empty but trying to fix it on my own right now (sorry for bad english because im a swedish boy haha)

**Comment by Axel32019** [comment]
no AD issue -> closed
