### ISSUE TITLE
unable to move points

### ISSUE THREAD

**Issue by tafferjim** [Stephan-S/FS22_AutoDrive#103]
Hello.  I searched the issues page as well as I could.  I'm not sure if this has been mentioned as I don't read French.  I have tried several times to move a point and have not had success.  I tried with right mouse button, left mouse button and even the middle mouse button, but none of them allow me to adjust the location of the points.

**Comment by Bobster82** [comment]
I use my middle mouse for moving points, no problems with at... maybe key assignments?

**Comment by MoslessNeo** [comment]
If you are using CTS (Click to Siwitch), disable the mod and test.

**Comment by tafferjim** [comment]
It was the CTS, thank you.
