### ISSUE TITLE
Autodrive dumps out baler while driving

### ISSUE THREAD

**Issue by AutumnGamer** [Stephan-S/FS22_AutoDrive#1030]
I wanted AD to drive my full baler to another location, but as soon as I enable autodrive it starts opening the baler hatch mid-drive and dumping out the full bale on the road before driving off. I had auto-unload disabled for a purpose, is this intentional or is this a bug?

**Comment by regs1980** [comment]
This is not a mistake.
The Giants helper does the same thing, only he doesn't close the press.
