### ISSUE TITLE
Auto Drive Conflict

### ISSUE THREAD

**Issue by BTECPotato** [Stephan-S/FS22_AutoDrive#1031]
Auto Drive seems to break the game when using a trailer or any trailer that attaches a forklift, I believe it still recognised the forklift as an individual vehicle, it breaks the game as soon as you attach the forklift to the trailer removing the vehicle hud and also unable to press E to enter or exit the vehicle. I have tested with just auto drive enabled in mod menu just to make sure it was no other mod creating the conflict but still happened when auto drive is turned off in mod menu and isn’t loaded in game there is no issues with the trailer

![IMG_0789](https://github.com/Stephan-S/FS22_AutoDrive/assets/151441630/b989934e-5bc7-485d-b1e9-03bceedd49bb)
![IMG_0788](https://github.com/Stephan-S/FS22_AutoDrive/assets/151441630/1481dbf2-315e-40ba-b3e4-92f781f21592)
![IMG_0787](https://github.com/Stephan-S/FS22_AutoDrive/assets/151441630/5afb33f2-59e9-4c16-ad43-c3e1c9930e57)
![IMG_0786](https://github.com/Stephan-S/FS22_AutoDrive/assets/151441630/de09a120-a972-4aad-83fe-cb4970f44278)

**Comment by Axel32019** [comment]
Attach the following files: log.txt, AutoDrive_config.xml, AutoDrive_config.xml, vehicles.xml
