### ISSUE TITLE
Abfahrer fährt Ernter aus Premium Expansion auf der falschen Seite an

### ISSUE THREAD

**Issue by Steini619** [Stephan-S/FS22_AutoDrive#1034]
Der Abfahrer fährt den Dewulf aus dem Premium Expansion auf der falschen Seite ab also nicht wo das Entladerohr ist. Wen mir wer helfen kann wäre es echt super.

**Comment by NeverHere** [comment]
I am having the same issue. It appears that autodrive is detecting the harvester as a chopper. I was able to sort of fix this by using spiral field and running the pipe towards the outside of the field.

**Comment by Iwan1803** [comment]
Wir arbeiten bereits an einer Lösung / we are working on a problem solution 😉
