### ISSUE TITLE
AD no pass for trigger (Zielonka)

### ISSUE THREAD

**Issue by Vanquish081** [Stephan-S/FS22_AutoDrive#1035]
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/12070061/44cae75e-6230-4cd3-8040-87d9a7825ac7)

It doesn't go through the Farmers Market trigger, I needed to create a new route (green) to continue.

**Comment by Iwan1803** [comment]
Collision set to "FS 19"?

**Comment by Vanquish081** [comment]
> Collision set to "FS 19"?

Is set "FS22"

**Comment by Iwan1803** [comment]
Then set it to "FS 19".

**Comment by Vanquish081** [comment]
In FS 19 work fine, doesn't stop here.
