### ISSUE TITLE
Grain Cart Not Catching Up With Combine

### ISSUE THREAD

**Issue by mdrollins1983** [Stephan-S/FS22_AutoDrive#1038]
It seems since the latest GIANTS update, Catching up with combine Planning path is stuck and will not catch the combine. See attached debug and log txt. I'm not sure what the issue is.

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/94983108/269f90b7-c651-4b74-98d9-f1000d5c4fad)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/13467605/log.txt)

**Comment by rohne83** [comment]
your log has more errors than anything else, and nothing to AD. The debug screen shows that no combine is assigned to the unloader. Cannot tell why. But since you're using CP for your combine anyway, you're better off using CP also for the grain cart.
