### ISSUE TITLE
Possiblity to save presets of AD settings

### ISSUE THREAD

**Issue by lordbanastor** [Stephan-S/FS22_AutoDrive#1039]
I was wondering about the possibility to have presets saved of settings. Let me explain: Sometimes I need a tractor with a trailer to go from point A to point B in the "Unload Combine" mode, like when harvesting some of my own fields. This happens every year and I usually unload the harvest in my own silos, so is always the same settings: wait combine in point A and unload in point B. Next I want to sell some of this harvest into a given place, so I select the "Pickup and Deliver" mode from my silo to the destiny. I think it would be a nice help to be able to select this presets instead of having to set everything from the start, specially because I have a lot of checkpoints in my map. Not that its not good the way it is now, there are a folders mode already to sort my points that way, but I think this could be some addition to this already great mod. So, this is a suggestion, an enhancement, not an issue.

**Comment by Iwan1803** [comment]
See #963 and also the older #580.
