### ISSUE TITLE
Request to improve the deletion of a point

### ISSUE THREAD

**Issue by Markus33-ITA** [Stephan-S/FS22_AutoDrive#104]
I would like to propose an improvement for the elimination of a point. At the moment you have to click on the hud to delete. If possible, create a function to be enabled, again on the hud, which allows, with the click of the mouse, to delete any point (without being selected by the vehicle with the red line) within a predefined maximum radius (to be set with a setting global) away from the vehicle.
A thousand thanks.
Merry Christmas

**Comment by Bobster82** [comment]
If you hold the LALT key then you can click on a point to delete it ;)

**Comment by Markus33-ITA** [comment]
I not knew. Thankssss Bobster82
