### ISSUE TITLE
can't find path on same field

### ISSUE THREAD

**Issue by Commissar0617** [Stephan-S/FS22_AutoDrive#1047]
![20231214205619_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/5993529/843d5ae6-5636-48f4-b58a-b7451ff868d3)
![20231214205623_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/5993529/c8e5d47e-899e-46ec-a9e8-6112e72b45df)
![20231214205626_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/5993529/d3e30c27-872f-488a-a9a3-2eb7c5c3c62d)

**Comment by regs1980** [comment]
@Commissar0617 What do you want to tell us with these pictures?

**Comment by Axel32019** [comment]
no description -> will be closed

**Comment by Iwan1803** [comment]
No further feedback -> closed!
