### ISSUE TITLE
Question for axel or stephan

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS22_AutoDrive#105]
Hey guys,
When you park a vehicle, do you set any variable or fire any event? Why I am asking is, In my mod I can set vehicles at park state, but if I can subscribe to your event, it would go automatically. (There is a message event fired when parked, but dont know if I can use that or you have something else.

Thanks in advance ;)

**Comment by Iwan1803** [comment]
I think parking is like driving to a normal target, but Stephan and/or Axel can give more informations.

**Comment by Stephan-S** [comment]
Hey, I think we can add an event for that. We let you know here, when it is done :-)

**Comment by Stephan-S** [comment]
The event will be in the next release and called "onAutoDriveParked"

**Comment by Bobster82** [comment]
Sorry for my late comment, had some busy days ;)
Thank you for this.
