### ISSUE TITLE
Red dots suddenly missing Auto Drive

### ISSUE THREAD

**Issue by Dimitri010101** [Stephan-S/FS22_AutoDrive#1050]
Hello everyone,

Im quite new to this forum i searched this before i opened this Issue so correct me if it already exist.
Playing for 1year farming simulator 22 with autodrive worked always great till suddenly the red dots disapeared.

Tried:
-Re install Autodrive
-New map with only auto drive
-dots are placed above vehicle 
-Re singed the key for show dots

The strange this is i can see way-point and the lines in the menu map but not in the game (fotos below as example)
![Map autodrive](https://github.com/Stephan-S/FS22_AutoDrive/assets/153950277/2c293933-0900-4f25-bb18-f4dfa5bcad9c)
![3d](https://github.com/Stephan-S/FS22_AutoDrive/assets/153950277/8be26fae-5c10-4272-baee-30219e98294e)

**Comment by Axel32019** [comment]
Hello, Please add log.txt, AutoDrive_config.xml, AutoDrive_config.xml, vehicles.xml ->.zip here.

**Comment by Dimitri010101** [comment]
I also tried  just few moments ago this method but game is lagging and menu screens are not showing.
But red dots  fromautodrive are back.



Since no one has posted the solution yet, I'll do so, even if this is an old question:

Look for game.xml within you personal Documents folder, subfolder "My Games\FarmingSimulator2022".
Edit file with notepad, notepad++ or any other "dumb" plain-text editor. Do not use Word or something similar.
Find this line:

<renderer>D3D_12</renderer>

and change to

<renderer>D3D_11</renderer>

and save your changes. Done! You may start / restart FS22.

I'm on D3D_11 also, on Nvidia RTX 2080 SUPER. D3D_12 causes crashes.

**Comment by Dimitri010101** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/13695546/log.txt)
 
The other files are not supported to add here. 
How i resolve this?

**Comment by Dimitri010101** [comment]
Here are my logs.

[logs.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/13697145/logs.zip)

**Comment by Axel32019** [comment]
~500 mods, multiple maps and this is working? If so, respect !!!
Your last comment is not so clear to me - change to D3D_11 solved the issue?
You are running a GTX 1080, right?

**Comment by Dimitri010101** [comment]
In mean while i got it fixed,
First i changed the game.xml to D3D_11 and this was laggy so i undo it, then i restart computer and tried it again this time with succes the game is working properly and ad line are back. 
I wanne thank everybody for helping.
(in this game only 10 mods where active)
Yes i have a GTX 180.
