### ISSUE TITLE
AD bringt Server zum Absturz

### ISSUE THREAD

**Issue by LSMT-elMatador** [Stephan-S/FS22_AutoDrive#1051]
Hallo, beim Einfahren einer Map hat AD plötzlich einen LUA Call Stack verursacht!

Server Log anbei
[log (1).txt](https://github.com/Stephan-S/FS22_AutoDrive/files/13693900/log.1.txt)

Spiellog

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/13693902/log.txt)

**Comment by Axel32019** [comment]
Hallo, Wenn ihr Änderungen am mod vornehmt geschieht das auf Euer eignenes Risiko!!!
`Available mod: (Hash: d6fb9326b3dc2f754c146694892f7b69) (Version: 2.0.1.4.03) FS22_AutoDrive`


`2023-12-16 21:15 Error: Running LUA method 'draw'.`
`E:/LS Mods/LS 22/0-Mods AD Fahren/FS22_AutoDrive/scripts/Specialization.lua:807: attempt to index local 'wp' (a nil value)`

Kein Fehler in AD -> closed

**Comment by LSMT-elMatador** [comment]
Hallo Axel,
Hier wurden lediglich die Zielpunkt Bilder getauscht. Also an dem Programm wurde so nichts geändert!
