### ISSUE TITLE
Exit Field problem

### ISSUE THREAD

**Issue by TinMen6** [Stephan-S/FS22_AutoDrive#1052]
So i am using AD with CP to unload my combine. So lets say that i make two AD routes to the field for two tractors to unload my combine so one point will be A and other point will be B. So when i first use the points everything goes normal the tractor exits the field at the same point as they come in. But if i later switch tractor that at first came in the field at point A to come in now at point B the exit for that tractor remains the same as it did before that is point A. It happened on different maps to me not sure if this is the CP or AD problem tbh.

Edit. Even deleting the old point A does nothing the tractor is still going to the old point A and goes to empty the trailer from there.

**Comment by regs1980** [comment]
Screenshots and videos of the problem would help more.

**Comment by TinMen6** [comment]
https://medal.tv/games/farming-simulator-22/clips/1K1h7dbQZjS6Rx/d1337j3oGPOv?invite=cr-MSwxWm0sMjA5Nzg4Mzk0LA

Where the tractor exits the field is where my old point A was before i did some changes tand then when it gets back it goes to the point B which you can see in the AD menu on the right.  Sorry if the video is bad i am not much of an editor :)

**Comment by regs1980** [comment]
@TinMen6 
You have set a destination point with the CP driver.
CP first drives to this point before handing over to AD.
If CP is to hand over to AD immediately, the target point must be set more than 20 meters from the edge of the field.

**Comment by TinMen6** [comment]
@regs1980 ok i got it to kind work thanks a lot. Is this a new thining? I have been playing for years and i don't remember ever setting the "Target Position", i just set the field position and that was it

**Comment by regs1980** [comment]
@TinMen6 
The target position is set automatically when activating CP, unless you set it manually.

**Comment by Axel32019** [comment]
no AD issue -> closed
