### ISSUE TITLE
Autodrive won't drive

### ISSUE THREAD

**Issue by mooleshacat** [Stephan-S/FS22_AutoDrive#1053]
There is a problem with Autodrive and the cotton harvesters.

As we all know none of the cotton harvesters can unload partial bales. Some claim the Case can, but I have a 15% bale stuck in my harvester as we speak.

The issue is when I finish a field and a bale is stuck inside, if I tell it to drive to field 9, it just sits there and does nothing presumably because it is trying to "fold" itself which it can't because of the stuck bale.

This forces me to drive to every job manually, because when does the harvester NOT have a bale stuck inside it?

**Comment by mooleshacat** [comment]
Update, I found to unload partial bale is press Y.

Googling around no one ever tells what the keybind is, they just say to unload the bale which is not helpful at all.

This still will be an issue with the JD. Maybe for the cotton harvesters it should skip folding because it will never be able to fold and therefore will always prevent autodrive from driving.

**Comment by Axel32019** [comment]
@mooleshacat Is the Giants-Helper able to drive the not-empty harvesters to a destination -> NO!
Is AD able to drive -> YES, if you disable fold implements in "Experimental Features Settings".

**Comment by Iwan1803** [comment]
No further feedback -> closed!
