### ISSUE TITLE
Sunglasses Setting option missing

### ISSUE THREAD

**Issue by venominc831** [Stephan-S/FS22_AutoDrive#1055]
I was looking for debug options and discovered that I've been missing a setting category with the sunglasses. I updated to the latest version, and still cannot see it. I have tried on a single player game as well as a multiplayer server. 
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/154626651/ffed90a1-0297-4f3a-a736-de87fc15055b)

**Comment by Axel32019** [comment]
see #720

**Comment by venominc831** [comment]
My console is enabled
