### ISSUE TITLE
Force chaser to unload forage harvester only left/right

### ISSUE THREAD

**Issue by Timmeey86** [Stephan-S/FS22_AutoDrive#1057]
Is there a way to force tractors with the HAWE forage auger to chase a forage harvester on their left/right side?
Mine always tries to catch the rear side, which causes too much distance to be between the forage harvester and the trailer:

![grafik](https://github.com/Stephan-S/FS22_AutoDrive/assets/10223149/c7a9c60c-9a01-4735-8a30-ec2508ec8935)

All vehicles are base game; the forage harvester has the long pipe configuration

**Comment by regs1980** [comment]
Show AD setting from driver.

**Comment by Timmeey86** [comment]
I'm not near my PC until next Saturday, but the driver was in courseplay with "Field 15 (Grass)" selected in the AutoDrive window, but AutoDrive deactivated of course

**Comment by Timmeey86** [comment]
I switched to the John Deere forage harvester with a long pipe which doesn't have the issue
