### ISSUE TITLE
 'currentDischargeNode' (a nil value)

### ISSUE THREAD

**Issue by JORDANdu29** [Stephan-S/FS22_AutoDrive#1061]
Good morning,

During a multiplayer game, I have this problem. I can't get the autodrive to empty automatically. I have this error appearing:
FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:623: attempt to index local 'currentDischargeNode' (a nil value).

Any solutions to this problem?
Good day

**Comment by Axel32019** [comment]
Hello, Please add the following files in a .zip file: log.txt, AutoDrive_config.xml, AutoDrive_config.xml, vehicles.xml

**Comment by JORDANdu29** [comment]
First of all, thank you for your help.
In the .zip you will find the requested files 
[AD JORDANdu29.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/13851264/AD.JORDANdu29.zip)

I added the video of the problem:
https://www.youtube.com/watch?v=jT6P7cbW3HI&ab_channel=NadroNoread

Thanks again

**Comment by JORDANdu29** [comment]
Thank you, when do you expect a new version?
Good luck
