### ISSUE TITLE
I have a memory problem in the LS22.

### ISSUE THREAD

**Issue by Kuehe-Schubbser** [Stephan-S/FS22_AutoDrive#1063]
I have a memory problem in the LS22.
 
Save -> Quit game -> Main menu (rare)
Save -> Quit game -> Giants Engine is finished (most of the time)
Save -> Quit game -> Error message (common)

I also have D:\ references in my log, even though I don't have another disk connected.

Then I was informed that the error was in Autodrive.
Error: D:\auto_builder\cache\svn\0fe094cb2d0ec4b784b781920968bc31\src\engine\app\ReflectionAndScriptBinding.cpp (8354)2024-01-13 14:01 : 2024-01-13 14:01 !MathUtil::isNaN(pArgs- >arg[1].f)
2024-01-13 14:01 LUA call stack:
[Log_Datei.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/13928295/Log_Datei.txt)

**Comment by Axel32019** [comment]
No AutoDrive related issue -> closed

**Comment by Kuehe-Schubbser** [comment]
It would have been nice if you had given me a hint as to WHERE the error was.
This is almost similar problem and was AD error!!
https://github.com/Stephan-S/FS22_AutoDrive/issues/41
