### ISSUE TITLE
What is this triangle after using LCtrl + LMB?

### ISSUE THREAD

**Issue by Igi-PL** [Stephan-S/FS22_AutoDrive#1064]
According to the help and hint LCtrl + LMB should add a point. This time it worked, but the new point is in a completely different place, and there are also a lot of points in the shape of a triangle.
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/9589570/a67776b7-f841-46b8-a553-1841531a4977)

**Comment by Axel32019** [comment]
See: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#new-color-assignment-for-users-with-different-color-perception
