### ISSUE TITLE
IDEA - Have exit points as well as start points

### ISSUE THREAD

**Issue by coatsy35** [Stephan-S/FS22_AutoDrive#1065]
When using lots of trailers in the same field it often becomes a bottleneck of a trailer returning to the field ending up at the same point as one trying to exit. (I know you can create multiple start points, but you often end up with a crash somewhere).

Could we have a third option on each of the functions so that a start point is set and and an exit point if required (could just be set to the same if people wanted it to act as it does now). This would be really useful for fields with multiple entrances so a circular route could be created or other large areas. Would make the whole system more slick.

What does everyone think?

**Comment by Iwan1803** [comment]
We should program a function to solve a problem which can be fixed by yourself with a network correction or an other field exist strategy?

**Comment by coatsy35** [comment]
> We should program a function to solve a problem which can be fixed by yourself with a network correction or an other field exist strategy?

How do you get a load and deliver to enter one entrance of a field and wait for the combine to call and then exit via another then?

**Comment by Iwan1803** [comment]
With a catch line around the field and the field exit strategy "nearest" 😉

**Comment by coatsy35** [comment]
Ah yes. But still often they end up using the start position as the nearest and crash or just get stuck there. Would be neater and a useful addition IMO if you could force them to always exit where the user wants.

**Comment by rohne83** [comment]
or you use a normal green line at the field edge and choose exit strategy 'behind start'. This as well as nearest will avoid collisions with other waiting unloaders. Problem solved.
