### ISSUE TITLE
Question Hit center of exactFillRootNode

### ISSUE THREAD

**Issue by Martin-L45** [Stephan-S/FS22_AutoDrive#1068]
I have a mod where the exactFillRootNode is pretty small. this causes autodrive to overshoot when trying to fill from silo or augerwagon. If i extend the exactFillRootNode i works but it does not look right. 
Is there anyway to make autodrive aim for the center of the exactFillRootNode?

**Comment by Axel32019** [comment]
Have a look at the ingame trailers: exactFillRootNode is a invisible transform, so need to cover the loading area somehow.
AD is only aiming for exactFillRootNode while catch a harvester unload position, for loading from silo just make the route through the silo pipe/trigger.

**Comment by Martin-L45** [comment]
Ok Thanks for your reply. I will make some visual changes to make it look right. 
Looking forward to your next release.
