### ISSUE TITLE
Weird Issue with Continue in 2.0.1.4

### ISSUE THREAD

**Issue by thelapisfox** [Stephan-S/FS22_AutoDrive#1069]
For some reason, whenever I hit the Continue button on the AD UI, it randomly replaces the destination. It even does this when it reaches a destination. For example; I had it set on Pickup & Unload. I had it picking up from my Farm Silo and Dropping it off at the Feed Store on the Elk Mountain V2 map. Once it picked up the sunflowers from the silo, it began its next stop but the drop-off field got switched to We Buy Hay. So, I stopped it, reset the destination, hit the On button, and then hit Continue. As soon as I do, the drop-off changes again, this time to Bakery Unload, then to Gold Smelter Load/Unload, and then to my Farms wait point for unloaders. This just keeps happening over and over again. I have tried to restart but that doesn't fix it. Any clue what might be causing it?

**Comment by Axel32019** [comment]
add a screenshot!

**Comment by Friendlyx** [comment]
I had that as well some time ago in Multiplayer. I think it was a courseplay connected error. please try the newest cp version on github.

**Comment by thelapisfox** [comment]
As far as Pickup And Deliver, I wasn't sure what that did so I never touched it. Also, since I don't see an option to search for the best-selling station, I assume that's part of the expert options, which I do not currently have active.

Regarding the screenshots, here are the huds, and the options for both AD and CP.

![fsScreen_2024_01_23_10_52_43](https://github.com/Stephan-S/FS22_AutoDrive/assets/899111/a55b5cde-3940-4819-84ca-333e24375ffe)
![fsScreen_2024_01_23_10_52_58](https://github.com/Stephan-S/FS22_AutoDrive/assets/899111/8087fe16-23e1-4fe0-9099-cbf60d5bba5c)
![fsScreen_2024_01_23_10_53_03](https://github.com/Stephan-S/FS22_AutoDrive/assets/899111/2ba604de-d2ed-412e-8cfe-2a7b9fc02756)
![fsScreen_2024_01_23_10_54_04](https://github.com/Stephan-S/FS22_AutoDrive/assets/899111/e8ae1255-bfe9-4a56-b288-d541e6b357e1)
![fsScreen_2024_01_23_10_54_06](https://github.com/Stephan-S/FS22_AutoDrive/assets/899111/ead6c3f2-c6e5-49ae-9e17-7b688676925a)
![fsScreen_2024_01_23_10_54_09](https://github.com/Stephan-S/FS22_AutoDrive/assets/899111/d36639d6-6e4e-488c-b0a8-4a94057751ac)
![fsScreen_2024_01_23_10_54_11](https://github.com/Stephan-S/FS22_AutoDrive/assets/899111/d592e1d7-bcb6-4ac9-8ab1-9e93b1b8b2f2)

**Comment by Axel32019** [comment]
no feedback -> closed
