### ISSUE TITLE
Start CP am Ziel noch nicht "eingebaut"?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS22_AutoDrive#107]
Hallo,
ich kann CP nicht auswählen, nur AIVE für den Automatischen Start der Feldarbeit.
Hab AIVE rausgenommen, da erscheint das CP-Logo aber auch nicht.
Hattet ihr das noch nicht vorgesehen? Ich nahm an, das wusstet ihr, das CP in den Startlöchern steht und nun zur Verfügung steht.

**Comment by ct177mak** [comment]
Vllt ist dir aufgefallen, das der CP Baum mal grade heute öffentlich wurde und niemand wird da in ein paar Stunden irgend was einbauen ,lass den Leuten eibfach die Zeit die sie brauchen ,wenn AD zusammen mit CP funktioniert wird das auch dann hier drin stehen.

**Comment by Iwan1803** [comment]
Am 22. November kam LS22 raus, am 17.12. die erste AD-Version und nun sind wir schon 2 Versionen weiter.
Coden, testen, korrigieren, erneut testen, usw. und das ohne eine vernünftige Skript-Doku seitens Giants.
Nun ist CP gerade mal ein paar Stunden raus und da darf man wohl nicht erwarten, das wir sofort springen, um die Verbindung wiederherzustellen. Lasst sie erst mal Erfahrungen sammeln, Bugs fixen, Verbesserungen sichten und ggfs. einbauen und dann werden wir uns auch sicherlich an die Verbindung AD<>CP machen.
Mal davon abgesehen und manchen mögen es kaum glauben: tatsächlich haben auch wir ein reales Leben abseits von AD und Familien, mit den wir Weihnachten feiern 😉

**Comment by haamic** [comment]
Alles gut, es war ja auch nur eine Frage.  Ein "Nein, noch nicht," hätte als Antwort vollkommen gereicht.

@Iwan1803 
in deinem letzten Releasevideo bei 10:23 
[https://youtu.be/nu8RwMndl_U?t=623](url)
hatte ich für mich zumindest rausgehört oder hören wollen 😉, das evtl. zu Weihnachten etwas veröffentlicht wird. Dabei konnte es sich eigentlich nur um CP handeln.
Da ihr ja mit CP in Kontakt steht, nahm ich fälschlicherweise an, das in AD bereits eine Vorbereitung für CP statt fand. 

Geniesst die Weihnachtszeit. Das habt ihr Euch verdient, denn ihr habt Grosses geleistet, in der Vergangenheit und auch schon in der kurzen Zeit mit LS22. Dankeschön

**Comment by Iwan1803** [comment]
Es war eine Vermutung oder eher Hoffnung, das CP zu Weihnachten noch kommen wird 😉
Wir werden uns CP natürlich ansehen und dann auch schauen, das wir wieder mit CP und auch CP mit AD kommunizieren kann.

**Comment by UnknwnArtst** [comment]
Guten Abend, gibt es bezüglich Courseplay Integration schon was neues?

**Comment by Iwan1803** [comment]
Wir sind dran und ganz wichtig: it's done when it's done 😎

**Comment by Axel32019** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases
In Release 2.0.0.4 enthalten
