### ISSUE TITLE
Suw 5000 cannot unload in trailer

### ISSUE THREAD

**Issue by Melchior174** [Stephan-S/FS22_AutoDrive#1074]
Suw 5000 cannot unload in trailer

have tried the following

- let automatic tip off and selected it must use auger
- have a sample and it is because it could only from one side

I use autodrive with courseplay

autodrive has in this case and empty the grass collector that drives on the field and drive over and throw it in the truck

it worked 2 times and then no more

Hope you can help

otherwise it runs perfectly

**Comment by Axel32019** [comment]
Please add a screenshot showing SUW 5000 with the AD destinations visible.

**Comment by Melchior174** [comment]
i have done som testing offline where i workes

but on the server it worked 2 times and then stopped

**Comment by regs1980** [comment]
@Melchior174 Deactivate the automatic unloading side and set to pipe mode manually.

**Comment by Melchior174** [comment]
i have try that. still donst work

**Comment by Axel32019** [comment]
tested and is working for me
is the pipe opening before reaching the trailer?

**Comment by Axel32019** [comment]
no feedback -> closed
