### ISSUE TITLE
Trailer Mod Creation Compatibility Help - Automatic Tip Side.

### ISSUE THREAD

**Issue by Sam-D03** [Stephan-S/FS22_AutoDrive#1076]
Howdy!

I'm currently working on creating a mod trailer with 3x fill volumes, selectable by 3x different tip sides. Could you give any hints as to how AutoDrive works with the Automatic Tip Side Unload feature? I cannot get this feature to work with my trailer when one of the 3 discharge nodes hit an unload trigger, Autodrive doesn't change tip sides, like it does with every other multiple fill volume trailer! I cannot see any differences in vehicle XML on my trailer to other mod trailers that work fine.

Any hints to how this system works would really be appreciated to get compatibility in please!

**Comment by Axel32019** [comment]
Hello,
The tipside is selected which first hit an tip trigger with a raycast of the related discharge node, Y direction.
You may look here: https://github.com/Stephan-S/FS22_AutoDrive/blob/1eb6f653982328d850be3bec0718c3a48fadde13/scripts/Utils/TrailerUtil.lua#L650

**Comment by Sam-D03** [comment]
Perfect! I hadn't added effect nodes to my dischargers, and I didn't think that would be required for Autodrive to see all 3 discharge nodes. Added effect nodes and now works - thanks so much for the quick help @Axel32019!

**Comment by Axel32019** [comment]
Fine that my small hints could help - close here
