### ISSUE TITLE
Wegpunkte unterschiedlich hoch

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#1077]
Hallo Leute
mir ist grade vorhin aufgefallen, das AD die Wegpunkte unterschiedlich hoch setzt, je nachdem ob sie eingefahren werden, manuell gesetzt oder verschoben werden.
ich habe hier einen kurs mit dem HN T7 eingefahren, daneben einen Kurs manuell zickzack daneben/gekreuzt gezeichnet:
![fsScreen_2024_01_28_09_00_48](https://github.com/Stephan-S/FS22_AutoDrive/assets/24860501/f83951b6-49be-44a8-8178-2ccf29a4c89e)

und hier von der Seite sieht man die unterschiedlichen Höhen:
![fsScreen_2024_01_28_09_00_55](https://github.com/Stephan-S/FS22_AutoDrive/assets/24860501/41281216-ae1b-4e57-9442-d3395c3baf0c)

und zieht man einen (hohen) Wegpunkt aus einer eingefahrenen Linie, wird er auch tiefer gesetzt:
![fsScreen_2024_01_28_09_04_51](https://github.com/Stephan-S/FS22_AutoDrive/assets/24860501/ccf0125d-c084-4640-9973-e13357ef8a88)
![fsScreen_2024_01_28_09_04_59](https://github.com/Stephan-S/FS22_AutoDrive/assets/24860501/1c7d0368-2b20-427a-a9a0-8db8d8b0a93f)

gibts da eine Möglichkeit das man die Wegpunkte (nachträglich) auf die gleiche Höhe setzt?
kann es sein das es auf das Fahrzeug ankommt, beim großen NH T7 oder ähnlichen sind sie hoch, beim Lindner Unitrac z.b. tief.

lg
andreas

**Comment by Axel32019** [comment]
Hallo @andreasthu,
Wir nutzen verschiedene Höhen für die Wegpunkte, je nach Situation:

1. Aufzeichnung mit Fahrzeug
Hier wird der Fahrzeug-Ursprung verwendet um z.B. auf Brücken die Wegpunkte nicht auf den Boden darunter zu setzen.
Das 2. könnte zu Kollisionen mit Fahrzeug-Teilen führen und Punkte irgendwo im Fahrzeug entstehen lassen, wer was in mods so drin ist...

2. Erzeugen / Verschieben mit Maus
Hier wird mit einem raycast auf ein statisches Objekt geschaut um auch Landscape-Änderungen mitzubekommen:
https://gdn.giants-software.com/thread.php?categoryId=3&threadId=8381

Nachträglich alles auf den gleichen Abstand zum Boden zu bekommen würde einiges an Überarbeitungen notwendig machen.
Im Moment sehe ich das nicht als notwendig an - never change a ...

**Comment by andreasthu** [comment]
Ja ok, danke.
Mir ist es jetzt erst eigentlich beim NH T7 aufgefallen.
Ich hatte eine kurve eingefahren (d.h. punkte knapp nebeneinander) und dann einen punkt etwas verschoben wegen einer abzweigung.
Und da die kurvenpunkte sehr hoch waren und der eine verschobene recht tief,  sah der kurs von der seite recht eckig aus, von oben drauf  war er aber eh geschmeidig. Es ist für mich ja eigentlich nur eine optische sache, deshalb hab ich nur mal nachgefragt ob das so sein soll.
Alles gut bei mir, wichtig ist das es sauber läuft und das tut es.
Lg
Andreas

**Comment by Axel32019** [comment]
Na dann ist ja gut!
