### ISSUE TITLE
Tractor with supersteer does to many micro corrections 

### ISSUE THREAD

**Issue by m4ttyofficial** [Stephan-S/FS22_AutoDrive#1082]
The tractor 70 series, mod made by smety which is present on mod hub, the version with supersteer when autodrive is engaged spend too much time micro correcting the steering and not accelerating. Idk what could be the problem

**Comment by Iwan1803** [comment]
If the modder has built in something "special" that doesn't correspond to the Giants standard, then that's honestly not our problem. We will not customize AD for every "special" mod.
