### ISSUE TITLE
Bale Unload not working

### ISSUE THREAD

**Issue by PirateAE** [Stephan-S/FS22_AutoDrive#1086]
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/b18bc51c-38cf-4c9f-8868-e2269b137629)
Title. I tried moving the Sale point way ahead of the trigger... just stops here and wont progress further. Sale point is a placed one. Map is Hobows Hollow 4x

Edit for further tests
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/629f1631-0e4b-49e5-b953-8a5b0f90b822)
Made a New reverse course, stopped here, not even on the reverse part yet.

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/0ec67be7-7ced-48c0-b523-d7c7fea6dc68)
Kicked the weight off (as its a mod, the rest is base game) stoped here. Maybe terrain?

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/6eda8a41-5374-46c2-933a-f7b9fab93916)
Nope Not Terrain, 

And on a Random Whim a Built in sale point, no terrain 
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/f63a6846-7571-4575-b8ec-2d4d6274d9c2)

Im stumped

Edit Two, just trying to set it back to the Bio Heater, it wont go though the sale point.
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/e51ccc77-1db4-4f93-b6d3-89f6708f7828)

**Comment by PirateAE** [comment]
third and Final try at something, Back at the OG sell point. Entire new course, Forward part made so it misses the sale point entirely so its just the the rear end seeing it first on the reverse, still refusing to go though the sale point.

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/d69596dc-6d3d-46af-8ea7-cd4afa42670f)

**Comment by Axel32019** [comment]
set collision to FS19 or OFF
no reverse drive unloading

**Comment by PirateAE** [comment]
fs19 collision worked.... more or less... it did unload at the unload point.... just not the sale trigger itself. ill reposition my point and see if it works again
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/1755415/e777abfe-c970-45df-806b-c86aeb3b25a6)
