### ISSUE TITLE
How to disable the "should autodrive generate a route" popup at the start of the game?

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS22_AutoDrive#1087]
Every time I enter the game, I get this popup:
![image](https://github.com/Courseplay/Courseplay_FS22/assets/11199752/ed247983-e57e-406c-8617-12692b03ae93)
How to disable it?

**Comment by Axel32019** [comment]
It seems you are not using AutoDrive, so simply delete the mod from your mods folder.

**Comment by rogeriodec** [comment]
Not true, I'm using it, but I don't want to automatically generate routes when I enter the game

**Comment by coatsy35** [comment]
Simple. Just press no then. It only pops up once on a new save game

**Comment by rogeriodec** [comment]
> Simple. Just press no then. It only pops up once on a new save game

This is my question. I'm asking if I can disable this popup that appears every time I enter the game.
