### ISSUE TITLE
AD continues to show shortcut keys in the help window, even when the option is disabled

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS22_AutoDrive#1088]
Here the current configuration:

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/11199752/ec597086-f173-4c3d-8de3-d4c64adac1f5)

But the keys are still appearing on F1:

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/11199752/2b687735-9103-4b43-bb57-7675b4ca4325)

**Comment by Axel32019** [comment]
same as #980 - fixed in next release
