### ISSUE TITLE
AD erstellt zusätzlichen Punkt

### ISSUE THREAD

**Issue by Burschi-Ingo** [Stephan-S/FS22_AutoDrive#109]
Hallo zusammen. Ich habe ein Problem. Ich habe einen kleinen Rundkurs gelegt wo ich von einem kleinen Multifruit Silo (Neuero)  Gras in ein größeres Multi fahren lassen möchte mit AD. Habe ihm den Ladepunkt gesetzt und den Entladepunkt gesetzt. Die erste Runde macht er auch gut, aber nach dem Abladen beim großen Silo, setzt er einfach einen neuen Punkt mit der Bezeichnung: NL 16-22 - 6000 Multifruit, ohne das ich das je eingestellt habe oder so einen Punkt gesetzt hätte. Woran kann das liegen? Das war vor dem Update von AD schon so und jetzt immer noch. Und wir haben es auch ausprobiert, das ich einem Mitspieler Stroh liefere. Also von meinem Silo in seins aber er erstellt immer wieder einen Punkt vor meinem gesetzten Punkt. Sogar ab und zu bei ihm auf dem Hof. Wir spielen übrigens die Papenburg Map. Kann mir da jemand helfen?

![AD Strecke vom kleinen Silo zum Mitspieler](https://user-images.githubusercontent.com/96613261/147372939-ba6f78e6-0357-4af0-9fb5-cbc7c114f003.jpg)
![AD Strecke vom kleinen zum großen Silo-3](https://user-images.githubusercontent.com/96613261/147372948-84cf231d-e60d-46f3-a9db-902cd7e1730b.jpg)
![AD Strecke vom kleinen zum großen Silo 1](https://user-images.githubusercontent.com/96613261/147372953-018259d4-a009-401b-808d-b1ed8ac6a2ef.jpg)

**Comment by Iwan1803** [comment]
Wenn der Anhänger vorne grüne ist, dann sucht er für das Laden den Ladepunkt mit dem günstigsten Einkaufspreis und für das Entladen den Trigger, wo am meisten Geld für die Ware bezahlt (außer Zugstationen).
Klick die Anhänger im HUD mal bitte an, das sie nicht mehr grün sind und versuch es erneut.

**Comment by Burschi-Ingo** [comment]
Aber das hat doch nix mit Verkauf oder Einkauf zu tun, wenn ich etwas von meinem Silo zu einem Kollegen auf seinem Hot in sein Silo bringen lassen möchte. Und am Siloabstand hab ich nichts geändert.  Ich probiere das morgen nochmal wegen der grünen Anhänger die im Bild zu sehen sind. Und das er einfach einen Punkt an einem Multifruit Silo setzt was definitiv keine Kauf- oder Verkaufsstelle ist, ist ja mein Problem. Ich habe ja ein Punkt gesetzt und zwar den vor meinem Silo (Kleines Silo Ingo) so das er an dem Silo aufladen kann. Und wenn ich im die Strecke angebe und auf Start drücke, macht er sofort den Punkt: NL16-22 2000 Multifruit. Obwohl er definitive Abfahr und Endpunkte hat. Naja wie gesagt, ich probiere es morgen nochmal.

**Comment by Iwan1803** [comment]
Bei einem grünen Anhänger im HUD geht AD von Ein- und/oder Verkauf aus und nur dann werden fehlende Zielpunkt erstellt.

Davon abgesehen könnte dein Zielpunkt "Kleines Hofsilo" zu nah am Trigger sein, denn so wird möglicherweise der Zielpunkt erreicht, bevor der Anhänger überhaupt im Trigger ist. Als Faustregel kann man sagen: kann man manuell be-/entladen, sollte man noch eine Fahrzeuglänge vorfahren und dort den Zielpunkt setzen.

**Comment by Burschi-Ingo** [comment]
Okay danke. Werde ich gleich morgen/nachher ausprobieren. Es liegt aber nicht zufällig daran, das 2 Leute im Editor sind und bei der großen Map gleichzeitig Kurse einfahren? Okay sage mal Gute Nacht und vielen Dank fürs erste. Melde mich wenn es trotz Deiner Tipps nicht hin haut :)

**Comment by Iwan1803** [comment]
Theoretisch sollte es keine Probleme machen, wenn mehrere Strecken einfahren, aber empfehlen würde ich es nicht. Schließlich müssen die ganzen Änderungen zwischen allen Spielern synchronisiert werden.
