### ISSUE TITLE
AD driving in snow

### ISSUE THREAD

**Issue by Misamangame** [Stephan-S/FS22_AutoDrive#1095]
Hello,
When you have deep snow on the ground and you driving a vehicle it is sinking into it and leave track behind itself. Some specially road vehicles with normal/thin tires can get stuck. But when AD drives on same amount of snow it just ignores it and driving normally with worse breaking/turning performance but it does not sinking into it or leave track behind. Is it something what can be fixed or is it Giants thing that helper simply doesn't have same weight/mass preferences?  Btw CP have it same but as I'm using it on fields it is not so obvious doing almost 0 work during winter anyway.

**Comment by Iwan1803** [comment]
Use the Giants helper and it will have the same effect. So this is not an AD issue or problem.

**Comment by Misamangame** [comment]
Yes I thought it will be Giants,  thx for answer
