### ISSUE TITLE
Parkplatz wird nicht zugewisen

### ISSUE THREAD

**Issue by JonasFovea** [Stephan-S/FS22_AutoDrive#1098]
Hallo, ich habe Probleme beim Zuweisen von Parkplätzen.

Durch Klicken auf das P Symbol mit der Rechten Maustaste, auch unter der verwendug von Strg, Shift, etc., passiert leider nichts.
Auch habe ich schon Keybindings für den entsprechenden Befehl hinzu gefügt, aber das bringt ebenfalls nichts.

Ich benutze die AD Version 2.0.0.7

Hat da jemand noch eine Idee?

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-Tastenkombinationen#parken
Zum Zuweisen muss der Editor-Modus aktiv sein.
Hat es einen Grund, warum du noch eine ältere Version verwendest?

**Comment by JonasFovea** [comment]
Ah danke, das ergibt Sinn!

Die alte Version läuft aufm Server und das ist immer so anstrengend, wenn alle ständig mods updaten müssen. Und die Version lief ja auch immer gut.

Ich werde jetzt aber mal updaten.

**Comment by JonasFovea** [comment]
Ich hab jetzt heute deinen Tip ausprobieren können, aber das hat leider nicht geholfen 🤔 .
Sogar mit der aktuellen AD Version 2.0.1.6.

Auch kein Unterschied besteht zwischen Single- und Multiplayer.

Probiert habe ich im Editor-Modus den Lstrg-Rechtsklick, als auch per zugewiesenem Hotkey.

Kann das noch andere Gründe haben?

**Comment by Iwan1803** [comment]
Du solltest mal schauen, ob diese Tastenkombi noch irgendwo hinterlegt ist.

**Comment by JonasFovea** [comment]
Das ist nicht der Fall, habe auch (neben anderen Versuchen) mal was ungewöhnliches verwendet: LSTRG-LSHIFT-ß

**Comment by JonasFovea** [comment]
Kann ich evtl das Setzen durch Mausklick wieder wie im LS19 auf nur die rechte Maustaste ändern? Da hat das für mich immer Funktioniert.
Ich hatte irgendwann bei anderen Mods nämlich auch schon mal Probleme mit der LSTRG-Taste

**Comment by Axel32019** [comment]
Hallo @JonasFovea ,
Probiers mal mit Tastatureinstellung "AD: 1. Ziel als Parkplatz setzen"

**Comment by Axel32019** [comment]
no update -> closed
