### ISSUE TITLE
Request for information on changing the chinese language file

### ISSUE THREAD

**Issue by aini1123** [Stephan-S/FS22_AutoDrive#11]
I need Chinese translation, can you help me, thank you!

**Comment by Iwan1803** [comment]
Do you want to do the translations?

Here are instructions in case you want to do the pull request:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

If not, we are happy to just copy the file and add it ourself. Though that means that you will not be the official "creator" of those translations in Github and will not be listed as contributor 😁
