### ISSUE TITLE
Abholen und Liefern, Es geht leider nur 1 Anhänger, der 2 oder 3 wird nicht befüllt..

### ISSUE THREAD

**Issue by BANO72** [Stephan-S/FS22_AutoDrive#110]
Erstmal vielen Dank an euch , der wichtgiste MOD überhaupt.......

Problem ist, das beim abholen und liefern nur der 1 erste Anhänger befüllt wird, der 2 oder 3 Anhänger wird ignoriert und es wird losgefahren und abgeladen.

**Comment by Axel32019** [comment]
Hallo @BANO72 ,
Ein Screenshot der Ladestelle mit aktivem Edit-Mode -> button 7. https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description würde helfen.
Vermutung: Zielpunkt nicht weit genug hinter dem Ladepunkt.

**Comment by BANO72** [comment]
ja, das war's
Dachte nicht das ich den Zielpunkt so weit nach vorne legen muss ....
Vielen Dank für den Tip .
