### ISSUE TITLE
Hide waypoints on mapview?

### ISSUE THREAD

**Issue by dxwarlock** [Stephan-S/FS22_AutoDrive#1102]
Sorry if this is a feature and I cannot find the option.

I am attempting to setup parking points for our 30 tractors. Only issue is when in mapview there is 40+ waypoints all crammed into one area (30 parking + dropoff/silo/etc on farm), making the map a mess to try to click on anything to select it to reset or see a vehicle as it just keeps picking waypoints.

Is there a way to disable to visual pin on the map view?

**Comment by Axel32019** [comment]
Disable "Show markers" in your personal settings.

**Comment by Axel32019** [comment]
no feedback -> closed
