### ISSUE TITLE
Aktives Abfahren - verkehrt herum?

### ISSUE THREAD

**Issue by Niceaux** [Stephan-S/FS22_AutoDrive#1103]
Moin..

in der aktuellen Autodrive version hab ich folgende Feststellung gemacht:

Ist beim Drescher das "aktive Abfahren" auf Ja, bleibt der Drescher beim abtanken stehen.
Steht es auf "Nein", ist aktives Abfahren möglich.

Scheint so, als wäre die Option verkehrt herum ;)

**Comment by Axel32019** [comment]
Moin, Diese Einstellung beeinflusst den Drescher nicht. 
Bitte Screenshots und log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml anfügen.

**Comment by Axel32019** [comment]
no feedback -> closed
