### ISSUE TITLE
Disable shadows

### ISSUE THREAD

**Issue by rogeriodec** [Stephan-S/FS22_AutoDrive#1104]
At times, the shadows of the waypoints get in the way, as in the case of planting trees.
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/11199752/b73f51d2-b2aa-430b-b3d8-b7bb271cfe1e)

Is it possible to disable waypoint shadows and still keep them visible?

**Comment by Axel32019** [comment]
This are no AD waypoints! -> CP
closed.
