### ISSUE TITLE
Driver stuck/stopped message

### ISSUE THREAD

**Issue by Bovrinox** [Stephan-S/FS22_AutoDrive#1105]
Could we have an on screen message telling us when a vehicle is stuck, or not moving for an extended period of time? It is so frustrating setting a vehicle off on its task, thinking it is happily selling all your milk, just to discover it has gone slightly off route somewhere and got stuck, even though its done the same route hundreds of other times just fine! 
A simple message saying vehicle such-and-such hasn't moved in x number of seconds or something would be really helpful!

**Comment by norfolkfarmer** [comment]
I always use this mod to keep an eye on all my workers.

https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=235001&title=fs2022

**Comment by Bovrinox** [comment]
Well that would work, but to be honest there is already too much clutter on
the ui for me, adding more isn't the way to go, especially with production
info displayed in the same way from other mods. A small pop up message for
a stuck driver like courseplay does would be much cleaner, in my opinion

**Comment by ThomasMatern** [comment]
Duplicate. #156 #399
