### ISSUE TITLE
Unloading Issues! Getting Worse

### ISSUE THREAD

**Issue by Dopescustoms** [Stephan-S/FS22_AutoDrive#1106]
I posted this on steam and that lead me to here.
I have tried using different buildings.(What happened to being able to raise and lower items?) I have noticed that some occasions i can change the vehicle, but now that is starting to not work either. Call me crazy, but it feels like a ongoing degrading issue. Gets worse with time. Over the last two weeks I have had 4 vehicles stop working with unloading, loading works fine with any of them, just not unloading.  Any help would be greatly appreciated. Thanks 

PS. I does not matter what I'm hauling in any of these events. I have spent a "bit" of time trying to incrementally move the unload points ahead and behind and different vehicles. Thanks 
Please let me know if you need more information.

**Comment by Dopescustoms** [comment]
Something new, after the vehicle stops at the marker for unload, if i grab the marker and move it backwards the unit will then start to unload. But when it tries it again on its own, nothing, Unless i grab the marker again and move it, then it starts to unload.

**Comment by regs1980** [comment]
Screenshots of the AD settings and the problem itself, as well as log.txt with activated AD debug, are very helpful.

**Comment by Axel32019** [comment]
no update -> closed
