### ISSUE TITLE
Drive from CP to Unload with 5kph

### ISSUE THREAD

**Issue by MartinR80** [Stephan-S/FS22_AutoDrive#1107]
Hi.
I have a Traktor pulling a Foragewagon collecting mown grass with Courseplay.
If it gets full it sucessfuly pulls out to Autodrive but it does not go faster than 5kph.
Doesnt matter if it is going from the field to the AD route or if it travels along the AD route.
Any idea what could cause this?

Thanks for any Help!
![AD](https://github.com/Stephan-S/FS22_AutoDrive/assets/46870042/cae701ed-f8cf-47c4-bd64-c967e1d4b024)

**Comment by regs1980** [comment]
First update CP and upload the log.txt of the game, it may well be that other mods are still involved.
https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.4.1.0

**Comment by MartinR80** [comment]
I updated all Mods and here is a log. Thanks.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/14730950/log.txt)

**Comment by regs1980** [comment]
CP is still on the Modhub version, update to the version from the link.
Make a video of the problem.

**Comment by MartinR80** [comment]
Oh. I must have clicked update in game and it downgraded again?.
Its is now 7.4.1.0. But nothing changed.
[Link to Video](https://youtu.be/w-fgSCfWXqI)

**Comment by regs1980** [comment]
It looks like cruise control because it can go backwards 11 km/h.
Remove all other mods except CP and AD from the mod folder and see if the problem still exists.

**Comment by MartinR80** [comment]
Removed all Mods except the official DLCs still the same...

**Comment by MartinR80** [comment]
Ok i reset all AutoDrive options to default and now its working again. Not sure what i had set that has caused this.
Sorry for the inconvenience and thanks for trying to help!

**Comment by regs1980** [comment]
The Max Silo distance was definitely set to 200 meters.
