### ISSUE TITLE
In game HUD not opening

### ISSUE THREAD

**Issue by SolarFarms** [Stephan-S/FS22_AutoDrive#1108]
Ingame HUD is not opening. Ive tried multiple versions and changing the keybinds. Not sure what the cause is im quite new to FS22 modding. Any help would be greatly appreciated?

**Comment by Iwan1803** [comment]
Left ALT + Numpad 0 is the default keybinding. If this doesn't work then check your keybindings because another mod is probably using the same combination.

**Comment by asundrus** [comment]
Remember, you need to be in a vehicle first.

**Comment by Axel32019** [comment]
no update -> closed
