### ISSUE TITLE
Different trailers or attachments can no longer be detached or removed from version 2.0.0.2.

### ISSUE THREAD

**Issue by OldMan52** [Stephan-S/FS22_AutoDrive#111]
Various trailers or attachments can no longer be unhooked or dismounted as of version 2.0.0.2. In version 2.0.0.1 I have no problems with this. I get the following error message in the game: '' Unhooking while the implement is up/down is not allowed ''. I have attached the log.xml as an attachment.

Greetings OldMan52
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7775682/log.txt)

**Comment by Williwillswisse** [comment]
Take a look at #131
