### ISSUE TITLE
LUA error 

### ISSUE THREAD

**Issue by envikowaty** [Stephan-S/FS22_AutoDrive#1113]
Good day,

Please see attached errors plus added my whole log file:

`2024-03-30 17:08 Game saved successfully.
2024-03-30 17:09 Error: Running LUA method 'mouseEvent'.
C:/Users/Grzegorz/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/CollisionDetectionUtils.lua:281: attempt to index field 'ad' (a nil value)
2024-03-30 17:09 Error: Running LUA method 'update'.
C:/Users/Grzegorz/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/CollisionDetectionUtils.lua:281: attempt to index field 'ad' (a nil value)
2024-03-30 17:09 Error: Running LUA method 'mouseEvent'.
C:/Users/Grzegorz/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/CollisionDetectionUtils.lua:281: attempt to index field 'ad' (a nil value)
2024-03-30 17:09 Error: Running LUA method 'update'.
C:/Users/Grzegorz/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/CollisionDetectionUtils.lua:281: attempt to index field 'ad' (a nil value)
2024-03-30 17:10 dataS/character/animals/wild/deer/deerAdult.i3d (43.65 ms)`

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/14812628/log.txt)

**Comment by ThomasMatern** [comment]
Can you please supply more information? 
- when does this happen: after loading a specific savegame, after loading any savegame?
- what happens afterwards? Does the game just work or does it freeze?
- you have a *lot* of mods, have you tried disabling all mods except AD?
- have you tried starting a new map with only AD enabled?

**Comment by envikowaty** [comment]
> Can you please supply more information? 
> 
> - when does this happen: after loading a specific savegame, after loading any savegame?
> 
The only way to access the tractor or harvester is by using TAB button, no chance to access to standing next to it, to respire this problem game restart required 


> - what happens afterwards? Does the game just work or does it freeze?
> 
Impossible to access the tractors by standing next to them 


> - you have a *lot* of mods, have you tried disabling all mods except AD?
> 
I've deleted a lot of mods which are not from mod hub to find the problem, still looking for the trouble conflict mod


> - have you tried starting a new map with only AD enabled?

Ye I did, looks like some mod conflict

**Comment by Axel32019** [comment]
Hello,
Please use the following AD Version.
If you observe the issue add these files in one zip-file: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml
[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/14897615/FS22_AutoDrive.zip)

**Comment by envikowaty** [comment]
I will ran some tests tonight and see if the problem appears again

**Comment by ThomasMatern** [comment]
@envikowaty any update?

**Comment by envikowaty** [comment]
It's definitely a conflict with some mods be because of new save there is no problem, I'm still trying to find with what mod is the problem. 

At the moment I'm trying to figure out how suddenly some obstruction appeared and I can't ran AD. Where  couple days before there was no problem

**Comment by Axel32019** [comment]
no update -> closed
