### ISSUE TITLE
Routenmanager

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS22_AutoDrive#1114]
Hallo! Habe folgendes Problem:
Wenn ich eine Route ändere und ich Fehler mache, möchte ich die gespeicherte Route neu laden.
Beim neue laden stürzt mir das LS Spiel aber ab!
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/14816955/log.txt)
Video
https://youtu.be/z51ojc2Dnfg

**Comment by ThomasMatern** [comment]
Hi, ich kann das nicht direkt reproduzieren. Kannst du bitte die Route anhaengen?

Du findest die im FS22 Ordner (wo auch deine Spielstaende gespeichert sind), unter "modSettings\FS22_AutoDrive\routesManager". 
Oeffne "routes.xml", finde deine Route und den korrspondierenden, kryptischen "filename". Im Ordner "routes" findest du eine entprechende XML Datei mit diesem Namen - das ist deine Route.

**Comment by KarlGutenberg** [comment]
Gewünschte Route Dieses Programm nimmt keine XML
Habe die XML in PDF umbenannt
[95CG0ZNTYNwC0TLR.PDF](https://github.com/Stephan-S/FS22_AutoDrive/files/14820828/95CG0ZNTYNwC0TLR.PDF)
Auch auf andere Maps funktioniert das nicht!

**Comment by ThomasMatern** [comment]
Ich kann das Problem leider nicht reproduzieren. Kannst du bitte mal alle anderen mods deaktivieren und es erneut versuchen?

**Comment by KarlGutenberg** [comment]
Habe ich schon gemacht!
Auch habe ich den Ordner modSetting gelöscht,
ohne erfolg!

Thomas Matern ***@***.***> schrieb am Mi. 3. Apr. 2024 um
09:38:

**Comment by KarlGutenberg** [comment]
Habe es gefunden!
Es lag an der gespeicherten Route! Irgendwas muss da defekt gewesen sein!
Kann geschlossen werden!
Danke für Deine Mühe Thomas

**Comment by Iwan1803** [comment]
Ganz wichtig: vor dem Speichern per Routenmanager unbedingt AD_Debug ausmachen!

**Comment by KarlGutenberg** [comment]
Das kann mein Fehler gewesen sein!!

Iwan1803 ***@***.***> schrieb am Mi. 3. Apr. 2024 um 16:19:
