### ISSUE TITLE
Wiederholungen Zählfehler

### ISSUE THREAD

**Issue by Ghost265** [Stephan-S/FS22_AutoDrive#1115]
Mahlzeit, mir ist aufgefallen wenn ich z.b. Abholen und Liefern mache dann z.b. 40 Wiederholungen mache, fährt er ganz normal und alles gut aber im Hud steht dann nachdem er paar mal gefahren ist wieder die 40 drinn und er zählt von vorne. meistens passiert das wenn man kurz aufm Fahrzeug raus geht und später wieder rein geht. Kann auch mit dem Händler zusammen hängen. Zuletzt bin ich aus dem Fahrzeug raus dann war der bei 17/40 wiederholungen, habe dann was im Händler gemacht, also kurz ein Display aufgestellt bin dann wieder in den Trecker rein und er war wieder bei 40/40

**Comment by rohne83** [comment]
Na wenn du im Shop was im Fahrzeug umkonfigurierst und danach AD wieder neu startest ist das doch auch ein komplett neuer Job. Wäre schlimm wenn da einfach vom letzten Stand aus weitergezählt würde anstatt wieder von vorne zu beginnen.

**Comment by Ghost265** [comment]
nein das hast du falsch verstanden. ich lasse den AD weiter fahren, steige aus und gehe in den shop. Baue dann iwas oder gucke nur was nach und steige danach wieder in das fahrzeug ein, dann ist der zähler wieder auf anfang

**Comment by Axel32019** [comment]
Kommt vor wenn repariert, getankt, geparkt wird - fixed: https://github.com/Stephan-S/FS22_AutoDrive/commit/1fce136e54d9cc68299b6453ebcb37e5a0c804c0

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.8
