### ISSUE TITLE
Autodrive course creation

### ISSUE THREAD

**Issue by dakotatech199gmail** [Stephan-S/FS22_AutoDrive#1119]
Using the scroll wheel to create an arc when connecting to the next node not working. I have to manually add nodes to make a curved path. Isa there a fix for this?

**Comment by Iwan1803** [comment]
You need at least 2 connected waypoints at each site.

**Comment by dakotatech199gmail** [comment]
I do and the scroll still doesn't work

**Comment by ThomasMatern** [comment]
@dakotatech199gmail please attach a screenshot of the exact situation when the scroll is not working, with both sides of the network being visible.

**Comment by dakotatech199gmail** [comment]
I am doing what the instructions say but my scroll wheel does not create an arc like all the videos show. I have to drive it or manually set nodes. I checked my mouse settings and can't find anything to fix the problem.
________________________________

**Comment by ThomasMatern** [comment]
@dakotatech199gmail I can't help if you don't show me what you are doing. Sorry.

**Comment by dakotatech199gmail** [comment]
What's to know, I click on one node then hover over the next dot and turn
the scroll wheel like described in many videos and my line does not curve,
it stays straight!

**Comment by dakotatech199gmail** [comment]
Photo attached
________________________________

**Comment by ThomasMatern** [comment]
I can't see a photo.
Does the first node you click on have a connection to another node?
Does the second node you click on have a connection to another node?
For this to work, you need at least 4 nodes: S1, S2, E1, E2. Nodes S1 and S2 have to be connected already, and nodes E1 and E2 as well. Only then will you get an arc after clicking on S1 and hovering/scrolling over E1.

**Comment by Axel32019** [comment]
no update -> closed
