### ISSUE TITLE
Loader stops right in front of pallet pickup

### ISSUE THREAD

**Issue by Pachoracing** [Stephan-S/FS22_AutoDrive#1120]
Hi,

I have done a pickup and delivery route to transport wool from the sheep farm to the spinnery.
Now it works great when I start, the truck waits to fill and then goes to the spinnery and auto unloads, but when it returns to the loading it stops in front of the pallets, if I stop the AD move a bit forward and start it again it drives to the spot and picks it up like it should...but why is it stopping? and more importantly how can I stop it from doing so?

**Comment by Axel32019** [comment]
Hi,
Please add:
- screenshots with Game collision enabled -> F5, AD debug -> Sensors
- a zip-file with following files: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by Axel32019** [comment]
no update -> closed
