### ISSUE TITLE
Issue in unloading Dewulf ZKIVSE

### ISSUE THREAD

**Issue by dynilath** [Stephan-S/FS22_AutoDrive#1121]
Looks like the tractor is trying to go to a position that's too early for unload.

https://github.com/Stephan-S/FS22_AutoDrive/assets/3864313/d3dbfab8-43ae-411f-83ab-9448b19cfe30

The pipe offset setting only works in X-axis, this seems like a miss in Z-axis so I can do nothing with it

**Comment by Axel32019** [comment]
Please add a zip-file with following files: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by dynilath** [comment]
I found that there is a high probability that this problem can be solved directly by restarting the game. Reproduction may take some time.

**Comment by Axel32019** [comment]
no update -> closed
