### ISSUE TITLE
Problem mit Acimobil FS22_TrafficLight_Prefab

### ISSUE THREAD

**Issue by Taylor1684** [Stephan-S/FS22_AutoDrive#1123]
Mit der neusten Version 2.0.1.6 funktioniert die Kollisionserkennung "LS19" mit den FS22_TrafficLight_Prefab von Achimobil nicht mehr. Mit 2.0.1.4 hat es noch funktioniert und mit alle anderen Versionen davor auch.

**Comment by regs1980** [comment]
Die Aussage ist falsch, AD in der v2.0.1.6 erkennt AI-Blocker auf einer Map.
Die Map Insel Basern hat das FS22_TrafficLight_Prefab Skript in jeder Ampel eingebaut und sämtliche AD Fahrzeuge erkennen das.
![2024-05-08 10_47_44-Greenshot](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/f9040516-c56d-46d4-9780-ff4f8a900dec)
![2024-05-08 10_50_59-Greenshot](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/f067b70c-0804-40ba-b37b-92acb5b90b9e)
![2024-05-08 10_53_19-Greenshot](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/a0b52efa-29c9-4638-ade1-2d9e1bf6f28a)

Jetzt kommt es darauf an, was du für eine Kollisionshöhe eingestellt hast, in der v2.0.1.6 reicht 1 m.

**Comment by Taylor1684** [comment]
Danke für die info und hilfe . 
Bis zu 2m Kollissionshöhe geht es aufjedenfall. Es war nur komisch, hatte nichts geändert an der Kollisionshöhe zwischen den Versionen die waren immer bei 2.25m und es ging halt bei den Versionen davor ohne Probleme

**Comment by regs1980** [comment]
@Taylor1684 
Die Kollisionssensoren wurden überarbeitet, stand als Drittes in der Release-Info.

![2024-05-08 12_28_54-Release Notes für AutoDrive deutsch · Stephan-S_FS22_AutoDrive Wiki – Mozilla Fi](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/4b986381-068d-4896-8ce3-95778e94ca97)
