### ISSUE TITLE
Allradlenkung

### ISSUE THREAD

**Issue by agestar69** [Stephan-S/FS22_AutoDrive#1124]
Frage: Habe mehrere Fahrzeuge mit Allradlenkung
Ich schalte die vor AD immer aus, da die Fahrzeuge mit AD zu 90% immer im Graben oder vor dem Baum landen, aber AD schalltet die Allradlenkung spätestens nach dem Abladen wieder ein
Wie kann ich das deaktivieren?

**Comment by Axel32019** [comment]
AD ändert keinen Lenkmodus. Wurde von CP an AD übergeben?

**Comment by agestar69** [comment]
Er kam vom Feld, also Ja
Also muss ich schauen warum CP das umstellt?

**Comment by Axel32019** [comment]
So kenne ich das auch, ist schon länger der Fall -> CP anfragen.
Hier -> closed.
