### ISSUE TITLE
Kein Hub bei AD

### ISSUE THREAD

**Issue by Carsten36** [Stephan-S/FS22_AutoDrive#1125]
Über den HUD von AD bekam ich eine blaue Meldung seitdem öffnet der Hud nicht mehr, habe FS22 neu runtergeladen, AD neu installiert, im Mod Ordner nur AD und CP drinnen, Hud macht nicht auf, trotz richtiger Tastenkombination, aber das Menü von AD macht auf, es geht nur um den Hud, kann mir da einer weiterhelfen?

**Comment by andremeyer123** [comment]
Biste auch im Fahrzeug ?

**Comment by Carsten36** [comment]
ja das bin ich

**Comment by andremeyer123** [comment]
Nicht einfach closed was wars jetzt ?

**Comment by Carsten36** [comment]
Ne geht immer noch nicht

**Comment by regs1980** [comment]
C:\Users\...\Documents\My Games\FarmingSimulator2022 die Datei inputBinding.xml löschen, FS22 braucht man weder deinstallieren, geschweige neu herunterladen, wenn was ist, immer den C:\Users\...\Documents\My Games\FarmingSimulator2022 löschen vorher alles Wichtige speichern.

**Comment by Carsten36** [comment]
Danke für die Info regs

**Comment by Axel32019** [comment]
no update -> closed
