### ISSUE TITLE
AD Follow Combine - Keep driving throught fruit

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS22_AutoDrive#1127]
Since 1 or 2 last version, AD Driver keep running into crops while following combine.
i remember before the 2.0.1.x it was ok, but sinc 2.0.1.x, it's getting worse
i'm using version 2.0.1.6
here's another example : 
![fsScreen_2024_05_20_09_26_55](https://github.com/Stephan-S/FS22_AutoDrive/assets/58886243/da73f066-6523-4b19-97d1-32dece1895d4)

as you can see, drivers is running in the middle of crops to get close to the combine

Here's my log
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/15374046/log.txt)

please fix, it's getting worse and pretty annoying

**Comment by Axel32019** [comment]
Increase Pathfinder factor in global settings.

**Comment by Axel32019** [comment]
no update -> closed
