### ISSUE TITLE
Parkplätze verstellen sich

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS22_AutoDrive#1128]
Hallo zusammen,

bei uns ist immer wieder mal das Problem, dass sich zugewiesene Parkplätze verändern oder gar löschen.
Verändert wurde während der Zeit nichts.

Gruß Marc

**Comment by Kitekater** [comment]
Traktor hat zB P-01 zugewiesen, wohin er auch immer zielgenau fährt, wenn man auf "P" drückt. Eines Tages hat er entweder einen anderen Parkplatz zugewiesen, zB P -02 oder es ist garkeiner mehr hinterlegt

**Comment by regs1980** [comment]
Wie viel Leute haben Berechtigungen?

**Comment by Kitekater** [comment]
Nur ich.

**Comment by regs1980** [comment]
Eher unwahrscheinlich, dass es von AD kommt, sonst würden schon mehr das Problem schildern in fast 3 Jahren.
Ich selber spiele seit FS19 mit AD und CP auf einem Server und bis jetzt ist sowas noch nie vorgekommen.
Entweder können andere User auf deine Geräte zu greifen und jemand macht sich ein Spaß draus das zu ändern oder du hast ein Mod Problem mit anderen Mods.

**Comment by Axel32019** [comment]
Hallo @Kitekater,
Bitte sichere einmal folgende Dateien aktuell und einmal nach dem Auftreten, evtl. kann man dann was finden...
log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by Kitekater** [comment]
Hi Axel. 

Alles klar, werde ich machen.
Wollte morgen sowieso mal rausfinden, in welcher Datei der Parkplatz zugewiesen wird und das dann mit Savegames vergleichen, die ich regelmäßig sichere. Vielleicht finde ich ja was

**Comment by Axel32019** [comment]
Die Parkplätze stehen bei den Fahrzeugen in vehicles.xml.

**Comment by Kitekater** [comment]
Bin grad bis Mittwoch unterwegs. Dann schaue ich sofort
