### ISSUE TITLE
AutoDrive and Courseplay

### ISSUE THREAD

**Issue by DickTimmerman** [Stephan-S/FS22_AutoDrive#1129]
I have seen AutoDrive and CoursePlay working together in some user YT. I managed to have Guidance steering visible in AD but never had CP visible in AutoDrive. Is there anything that I have overseen or done wrong with installing Autodrive?

Also in post [ [m0dbot](https://github.com/m0dbot)](https://github.com/Stephan-S/FS22_AutoDrive/issues/1081) his post you can see the CP icon in the AD menu.

**Comment by DickTimmerman** [comment]
And exactly that button will not appear with me.
I use AD versio 2.0.0.3 and CoursePlay 7.4.1.2
Also, extra setting "On".

**Comment by regs1980** [comment]
CP was supported from version 2.0.0.4. 

![2024-05-24 21_18_39-Releases · Stephan-S_FS22_AutoDrive – Mozilla Firefox](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/0b7f2f0b-c530-4892-8239-1a3193a7fe5a)

**Comment by Axel32019** [comment]
@DickTimmerman Are you able to work with CP?
Please attach log.txt within a zip-file.

**Comment by DickTimmerman** [comment]
[log.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/15467969/log.zip)
No, CP is still not showing up. Probably my setting will be a problem but if you can help.

**Comment by Axel32019** [comment]
Available mod: (Hash: 2c609d019ed1600d507b524b22d2faed) (Version: 7.4.1.2) FS22_Courseplay
Available mod: (Hash: 1f1e642e77ff75d69f8cf63a699219bd) (Version: 2.0.0.3) FS22_AutoDrive
1. AD 2003 is not supporting CP!
2. Update AD to latest version: https://github.com/Stephan-S/FS22_AutoDrive/releases/latest/download/FS22_AutoDrive.zip

**Comment by DickTimmerman** [comment]
Many thx for support, the version i have downloaded now is showing the CP button. Now I will figure out how to use.
