### ISSUE TITLE
Using CP combine did not unload since 99%

### ISSUE THREAD

**Issue by bibifr** [Stephan-S/FS22_AutoDrive#113]
Hello dear, 

Since cp is out, i Got a smallest error today. When CP driving Combine and reach 99% cp stop but AD did not unload Combine since it's not 100% for call while in fruit.

Pipe in fruit not error in log 

Best regard

Edit: I forgot something important ... 

Merry chrismas everyone ;)

**Comment by rohne83** [comment]
if you want to have AD unloading the combine, you have to set a lower fill percentage than 100% in the combine's AD settings. AD will then get called at this fill level.

**Comment by bibifr** [comment]
hi 
it's set to 30% But nothing to do they sometime up more than 30 and do not unload untill they full
