### ISSUE TITLE
Log Error fillFreeCapacity

### ISSUE THREAD

**Issue by Lorsch1409** [Stephan-S/FS22_AutoDrive#1135]
Ich bekomme mit einem Autoloader (Achimobil) folgenden Fehler in der Log. Das Spiel friert ein.

Autodrive steht auf abladen. Geladen sind Standard 125er Rundballen. 

C:/Users/jensv/OneDrive/Dokumente Jens/My Games/FarmingSimulator2022/mods Deutschland/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: attempt to perform arithmetic on local 'fillFreeCapacity' (a nil value)
2024-06-11 08:48 Error: Running LUA method 'update'.

[log.txt](https://github.com/user-attachments/files/15783441/log.txt)

**Comment by Axel32019** [comment]
AD ist nicht kompatibel mit FS22_FillLevelLimiter. Das führt zu diesem Fehler.

**Comment by Lorsch1409** [comment]
Danke für das sehr schnelle Feedback. Ich deaktiviere dann mal den Fill Level Limiter und gebe Bescheid, ob der Fehler verschwunden ist.
