### ISSUE TITLE
forks for big-bag

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Stephan-S/FS22_AutoDrive#114]
With these forks for big-bag, there was a problem before updating the game. In Version 1.2, it was corrected, but now there are problems with AutoDrive.

2021-12-25 20:44 Error: Running LUA method 'update'.
E:/FARMING_SIMULATOR/mods_FS22/FS22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:345: attempt to call method 'getAttachedImplements' (a nil value)

2021-12-25 20:45 Error: Running LUA method 'update'.
E:/FARMING_SIMULATOR/mods_FS22/FS22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:301: attempt to call method 'getAttachedImplements' (a nil value)

![fsScreen_2021_12_25_20_48_42](https://user-images.githubusercontent.com/8200153/147391622-9dfa7459-5240-4db8-b3d3-87fe483691be.png)

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/issues/137
