### ISSUE TITLE
Höhe der Streckenpunkte - Definition

### ISSUE THREAD

**Issue by Ulanawius** [Stephan-S/FS22_AutoDrive#1145]
Vielen Dank für die tolle Arbeit an AD.

Bei einigen Schleppern (aus FS19 konvertiert) habe ich das Problem, dass beim Einfahren der Strecken die Streckenpunkte unterhalb der Straße/Felder erzeugt werden (bei Anzeige auf Bodenhöhe). Wie wird die Höhe der Punkte definiert, bzw. von welchen Werten im Mod wird diese übernommen? Hängt dies an einem Koordinatensystem im Mod?

Vielen Dank,
Christoph

**Comment by Axel32019** [comment]
Hallo @Ulanawius , siehe #1077.

**Comment by Ulanawius** [comment]
Vielen Dank!
