### ISSUE TITLE
How to autodrive horses?

### ISSUE THREAD

**Issue by michael-ts** [Stephan-S/FS22_AutoDrive#1146]
I am trying to set up a course for my horse to follow.   However, I can't get AutoDrive to enable when I'm riding a horse.

**Comment by Axel32019** [comment]
Horses are not supported by AutoDrive!

**Comment by michael-ts** [comment]
Yes, obviously.  But I would like to gauge the difficulty in implementing this support.  Currently tabbing through my vehicles brings up the horse I was last riding suggesting that in some respects at least it is considered similar to a vehicle.
