### ISSUE TITLE
Can’t use the mouse wheel to set curved waypoints.

### ISSUE THREAD

**Issue by Alleniienx** [Stephan-S/FS22_AutoDrive#1148]
When I move to the target waypoint and scroll the mouse wheel, nothing happens, even though my mouse wheel is working fine.I also couldn’t find any related settings in the keyboard controls. Could you tell me what to do? Thanks a lot!

![20240706021952-convert](https://github.com/Stephan-S/FS22_AutoDrive/assets/171823181/abedcb3d-045d-4b7c-b88c-71f098dc65fd)

**Comment by andreasthu** [comment]
Each point must have a connection to another point, so that AD can calculate a start and a end angle 

Lg
Andreas

**Comment by Axel32019** [comment]
no issue -> closed
