### ISSUE TITLE
Haut Beleron / Volksleron Probleme

### ISSUE THREAD

**Issue by bitbuster1963** [Stephan-S/FS22_AutoDrive#115]
Moin, unterhalb der Großen Brückenansätze bei den genannten Maps ergeben sich wie auf den Bildern zu sehen massive Probleme beim anlegen bzw. editieren des Streckennetzes. Immer wieder werden diese tiefen Punkte gesetzt und der Kurs funktioniert
![screenshot_hth_09](https://user-images.githubusercontent.com/9318300/147394861-44678bfb-1bfa-4cad-8b80-99ea30db3901.jpg)
![screenshot_hth_10](https://user-images.githubusercontent.com/9318300/147394863-3477d2b8-d013-4373-b7d5-07114038895d.jpg)
![screenshot_hth_11](https://user-images.githubusercontent.com/9318300/147394864-a62ed8c3-be4c-4c28-a9e1-d7aaa15c51f7.jpg)
 natürlich nicht.

**Comment by KarlGutenberg** [comment]
Schau dir mal das Video von https://www.youtube.com/c/Iwan1803 an
Der erklährt dir wie das geht!

**Comment by bitbuster1963** [comment]
Nochmal zum besseren Verständnis. Ich klicke mit der rechten Maustaste auf einen Wegpunkt und der Wegpunkt verschwindet nach unten ins Nirwana. Weder L-Shift noch anderes hilft. Lösche ich nun den tiefliegenden Wegpunkt und verbinde erneut bleibt der Schlepper am ersten Wegpunkt der neuen Linie stehen und rührt sich nicht mehr.

**Comment by Williwillswisse** [comment]
Da brauchst du etwas Fingerspitzengefühl und Übung. Beim Markieren des Wegpunktes mit der rechten Maustaste darfst du nicht wackeln bevor du LSHIFT drückst.
Aber als kleiner Trick:
Bei deinem ersten Bild ist rechts oben eine Grasfläche. Den unterirdischen Wegpunkt dort hinziehen und er ist wieder auf Straßenniveau. Dann mit gedrückter LSHIFT an die gewünschte Stelle ziehen.
