### ISSUE TITLE
Vehicle Unusable After Drive Complete

### ISSUE THREAD

**Issue by KaosFarms94** [Stephan-S/FS22_AutoDrive#1150]
I have the Lastest Version of the Mod And it works Pretty Well but i do have issue where vehicle keeps driving forward or backwards after reaching destination, and some times the vehicle with either be come unusable where i can get in the vehicle but cant change gears or even shut the engine off until i exit and reload the game. Also idk if i over looked but is there a way to make vehicle shut itself off once it reaches the parking spot?

**Comment by Axel32019** [comment]
Add the following files in one .zip file here:
log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by Axel32019** [comment]
no update -> closed
