### ISSUE TITLE
Autodrive loop

### ISSUE THREAD

**Issue by UncleHaze** [Stephan-S/FS22_AutoDrive#1151]
Im trying to loop drivig to a point. Unsure if possible at current time? Otherwise suggestion for future function. 

Context: over 15 greenhouses just want it to drive past them to autoload then drive over the automatic unloqd point. 

Yes i tried multiple pickup locations which works fine but is too slow with the slowing down etc. 1 loadig point also doesnt work since it enables autoload too late. If increasing range for trigger it also is too far away still or the tractor slows down too much.

**Comment by Axel32019** [comment]
Screenshot?

**Comment by Axel32019** [comment]
no update -> closed
