### ISSUE TITLE
AD Conflicts with Click to Switch mod

### ISSUE THREAD

**Issue by pixelinkmedia** [Stephan-S/FS22_AutoDrive#1152]
Click to Switch is a mod that allows you (while in a vehicle) to right-click on the screen and then click on another vehicle to switch to that vehicle. It works great as long as I don't install and use AD.

However, when I install and use right click, it doesn't allow me to enter another vehicle.

I have done a lot of tests trying to figure out why AD and Click to Switch conflicts
There are no key-bindings that are the same.

It seems to me the issue may have something to do with both mods sharing the same right-click (or Middle mouse button) thread of the game. But, I am only gestimating.

I like AD, but because of Neuropathy in my hands from a stroke, I really need Click to Switch to save me on so many tabs while trying to get to a vehicle.

That's why I am also interested in AD. To save me some pain in my hands of having to drive everywhere.

Anything you need, just let me know.

Thanks

**Comment by pixelinkmedia** [comment]
Update.
After uninstalling AD, then deleting ALL mod setting folder/files....
I re-installed AD and I was able to go to another vehicle after pressing the middle mouse button.

So, right ow it works.
I will test again after I build another AD route/track and see if that may be the issue.

Thanks

**Comment by pixelinkmedia** [comment]
Update:
Well, after building a route.
I middle-click mouse button to go into clicking mod, and clicking on another vehicle does not work.

So, it seems that when a route/track is built that it conflicts with Click to Switch, which no longer works after building route.

Thanks

**Comment by pixelinkmedia** [comment]
Well, after some more research it seems that Click to Switch had a bug update to address this issue.
It has a more convoluted key short cut to get CTS to work.
So, now I installed AD and it works.

**Comment by pixelinkmedia** [comment]
All set

**Comment by Axel32019** [comment]
so no issue -> closed
