### ISSUE TITLE
Autodrive issue - vehicles don't stop at destination

### ISSUE THREAD

**Issue by xSpanky** [Stephan-S/FS22_AutoDrive#1153]
Hi, got a problem with AD, my drivers don't stop after reaching destination, instead they keep driving forward or run in circles around their destination point. Also a tractor with trailer won't stop under combine's pipe for unloading, goes straight and then loops instead. Anyone had that kind of issuea and managed to solve it somehow? The map's Szpakowo and I'm using AD route made for it by FinnishFarmer.

**Comment by KaosFarms94** [comment]
Im having same issue on Upper Miss River Valley Map. Also have had few times when vehicles would complete their job they would become unusable. I could enter them but couldnt turn them on or off or even put them into gear.

**Comment by KaosFarms94** [comment]
If your using Real Vehicle Breakdowns. Get rid of it. This Fixed My Issue

**Comment by xSpanky** [comment]
Confirmed, Real Vehicle Breakdowns was causing the problem. I've updated the mod to the newest version and now it works just fine, didn't have to remove it ;)
