### ISSUE TITLE
Verbesserungsvorschlag skalierbare Zielpunktnamen

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS22_AutoDrive#1154]
Hallo,

wäre es möglich eine Skalierung der Zielpunktnamen einzubauen? Also die, die im bearbeitungsmodus über der Strecke schweben. Leider ist es mir nicht möglich diese zulesen, da sie für mich zu klein sind.

LG

**Comment by Axel32019** [comment]
Hallo @Onkel2000 ,
Mal wieder....
![MarkerText](https://github.com/user-attachments/assets/fcfb65c4-053c-46ed-8e4f-15988e93014b)

Würde das schon reichen oder noch größer?
Wenn die zu groß werden passen sie nicht mehr auf den Bildschirm.

**Comment by Onkel2000** [comment]
> Hallo @Onkel2000 , Mal wieder.... ![MarkerText](https://private-user-images.githubusercontent.com/52026009/350154329-fcfb65c4-053c-46ed-8e4f-15988e93014b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNDgwMjQsIm5iZiI6MTcyMTM0NzcyNCwicGF0aCI6Ii81MjAyNjAwOS8zNTAxNTQzMjktZmNmYjY1YzQtMDUzYy00NmVkLThlNGYtMTU5ODhlOTMwMTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAwMDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2Y2M3MmI0OWUwNzdjOGZlMDY4ZGUwODM5N2RlMzRhMGFjZDAzYjc3YWVlY2VlNWU4YzViNjVkNGVlZDBhZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S8I_L61dKNDIagX6lgRU_HZmWqLpkqtAMyTS0O16h1Q)
> 
> Würde das schon reichen oder noch größer? Wenn die zu groß werden passen sie nicht mehr auf den Bildschirm.

Ja,ich mal wieder ;)
Danke dir, für deine schnelle antwort und anscheinend schnelle anpassung. Tatsächlich muss es warscheinlich gar nicht ganz so groß, etwas kleiner und mir wäre schon sehr geholfen da es jetzt echt winzig ist.

**Comment by Axel32019** [comment]
Probier das bitte mal aus und gib Bescheid ob OK oder nicht.
[FS22_AutoDrive.zip](https://github.com/user-attachments/files/16315193/FS22_AutoDrive.zip)

**Comment by Onkel2000** [comment]
> Probier das bitte mal aus und gib Bescheid ob OK oder nicht. [FS22_AutoDrive.zip](https://github.com/user-attachments/files/16315193/FS22_AutoDrive.zip)

Das ist großartig, das ist schon sehr viel besser. Vielen Dank dafür.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.8
