### ISSUE TITLE
selbstständiges tanken/reparieren

### ISSUE THREAD

**Issue by OpiGunnar** [Stephan-S/FS22_AutoDrive#1155]
hallo,die funktion des selbst reparierens und tanken muss ich bei jedem start auf dem server neu abschalten.
auch als admin und mit festlegung als standart schaltet sich das immer wieder auf  "**an**" ,warum?

lg Opi

**Comment by Axel32019** [comment]
Hallo, Bitte folgende Dateien von Client und Server in einem .zip hier einfügen:
log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by OpiGunnar** [comment]
hallo axel,denke das das nicht mehr nötig ist.
mir wurde erklärt daß das immer fahrzeug bezogen und nicht global
eingestellt werden muss. was ich nicht wusste.
hab die einstellungen in jedem meiner fahrzeuge gemacht und nu passt das.
sorry das ich da stress gemacht hab.
nobody is perfekt. muss mir dringend angewöhnen mehr zu lesen

lg
Opi

Am Sa., 27. Juli 2024 um 22:14 Uhr schrieb Axel32019 <
***@***.***>:
