### ISSUE TITLE
AI Breaks Working With Courseplay

### ISSUE THREAD

**Issue by RyZAus** [Stephan-S/FS22_AutoDrive#1156]
When it happens:
- When taking over for autodrive by stopping the task.

Problem:
- Tracktor locks up and sometimes drives in random direction.

Cause:
- If you stop the 'start courseplay at destination' connection prior to stopping autodrive?
- If you have auto repair or auto refuel enabled with no connection to a place to do it?

Conditions:
- On multiplayer.

Additional Notes:
- It's very hit or miss. Found it to be super inconsistent but usually can semi often replicate it by the server being on for multiple days.

**Comment by Axel32019** [comment]
Please add the following files from client and server in one .zip file here:
log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by Axel32019** [comment]
no update -> closed
