### ISSUE TITLE
"Navigation only" mode (Enhancement)

### ISSUE THREAD

**Issue by vertigoogle** [Stephan-S/FS22_AutoDrive#1157]
EN:

There might be those players who want to drive on their own but still want the advantage of the autodrive pathfinder to reach their destinations.
I suggest a mode on which autdrive still shows the next path, but does not drive on it's own.
I know, it would then be not "auto"drive anymore but I cannot imagine another mod similar enough to achieve this. And maybe it's not this bunch of a work...

Thanks for reading and discussing this.
Yours

---

DE (übersetzt):
Es gibt möglicherweise Spieler, die selbst fahren möchten, aber trotzdem den Vorteil des Autodrive-Pathfinders nutzen wollen, um ihre Ziele zu erreichen.
Ich schlage einen Modus vor, bei dem Autodrive weiterhin den nächsten Weg anzeigt, aber nicht von selbst fährt.
Ich weiß, es wäre dann kein "Auto"drive mehr, aber ich kann mir keinen anderen Mod vorstellen, der dem ähnlich genug ist, um dies zu erreichen. Und vielleicht ist das nicht so viel Arbeit...

Danke fürs Lesen und Diskutieren.
Viele Grüße

**Comment by regs1980** [comment]
Den Vorschlag gab es schon mal .

https://github.com/Stephan-S/FS22_AutoDrive/issues/761#issue-1472682831

**Comment by Iwan1803** [comment]
Nette Idee aber dafür ist AD nun mal nicht gedacht und ausgelegt.
