### ISSUE TITLE
Abfahrer bleibt bei 90% stehen und setzt zurück

### ISSUE THREAD

**Issue by 0scarZulu** [Stephan-S/FS22_AutoDrive#1158]
Hallo, 

mir ist heute seit langem mal folgendes Problem aufgefallen was auch reproduzierbar ist. Wenn mein Drescher oder Roder unter 90% FillLevel hat kommt der Abfahrer an und bunkert ab. Sobald ab das FillLevel die 90% erreicht und überschreitet bleibt der ABfahrer stehen und setzt zurück. Diesen Vorgang wiederholt der Abfahrer solange bis man zum Stillstand kommt. Ein fliegendes Abbunkern ist dann nicht mehr möglich über 90%, ist das so gewollt bzw. vorgesehen? 

Cheers

**Comment by rohne83** [comment]
dürfte Duplikat sein zu #929

**Comment by Axel32019** [comment]
Ist so beabsichtigt.
