### ISSUE TITLE
Request call driver intervals every 30 seconds

### ISSUE THREAD

**Issue by Beedog743** [Stephan-S/FS22_AutoDrive#116]
So at its current state you can set a pre-call fill level for combines and their perspective unloaded. However. If your unloader is full and is off driving to the destination point for the harvest and the combine hits its pre call fill level before the tractor reaches its field position the tractor will not go to the combine and the combine will not call the driver until its full. I'm requesting an enhancement for the combine once reaching its precall fill level to send out a "call driver" command every 30 seconds or so until it receives a response. Or even every % after the precall level would help immensely.

**Comment by Stephan-S** [comment]
The driver will always be called. There is no need for that. It will however not answer the pre call if the combine is almost full (85% or so) since this could result in the driver being too close to the combine when it actually reaches 100% and will not be able to pathfind properly to the pipe
