### ISSUE TITLE
Discovered that the loading truck does not automatically unload straw when delivering it

### ISSUE THREAD

**Issue by Simba76** [Stephan-S/FS22_AutoDrive#1160]
Discovered that the loading truck does not automatically unload straw when delivering it

**Comment by Axel32019** [comment]
Please add the following files from client and server in one .zip file here:
log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml
Screenshots!

**Comment by Axel32019** [comment]
no feedback -> closed
