### ISSUE TITLE
Game Freezes When Starting a Route with Autodrive Until the Vehicle Reaches Its Destination

### ISSUE THREAD

**Issue by charlotte507** [Stephan-S/FS22_AutoDrive#1161]
I am trying to use Autodrive in the game Farming Simulator 22. I downloaded and installed the map routes that I am playing on. When I get into a vehicle and set it to start driving to another point, I can't get out of the vehicle and move around. The camera freezes, and although the game keeps running, my character is frozen until the vehicle reaches its destination. Once it arrives, I can move again, get out of the car, and continue playing, but in the meantime, it's as if the game freezes while Autodrive is functioning.

I tried with simpler routes and created a route from scratch that was just a straight line, and the same thing happened.

**Comment by Axel32019** [comment]
Please add the following files from client and server in one .zip file here:
log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by Axel32019** [comment]
no feedback -> closed

**Comment by charlotte507** [comment]
[autodrive.zip](https://github.com/user-attachments/files/17347390/autodrive.zip)

please help me
