### ISSUE TITLE
Vorschlag Motorstart 

### ISSUE THREAD

**Issue by Waldmeister52** [Stephan-S/FS22_AutoDrive#1164]
Hallöchen zusammen :)

Hätte einen Vorschlag ob man das mit den Wartezeiten so regeln könnte wie bei courseplay ob der Fahrer bei Wartezeiten den Motor abstellen soll. Bei courseplay gibt es ja die Option mit Kraftstoff Sparen, wäre nice wenn man das in Autodrive auch so umsetzten könnte. 

Beste grüße

**Comment by Axel32019** [comment]
no feedback -> closed
