### ISSUE TITLE
Intersections are created automatically. They don't In V2.0.0.2 and 2.0.0.1 but it works in 2.0.0.0

### ISSUE THREAD

**Issue by ChrisTheDevL** [Stephan-S/FS22_AutoDrive#117]
intersections are created automatically. V2.0.0.1 and 2.0.0.2 have this issue as shown in the pics. 

These pics are V2.0.0.1
![Farming Simulator 22 12_26_2021 4_14_46 AM](https://user-images.githubusercontent.com/82164557/147403875-f43e8c8f-f575-46b1-b195-daad145077d9.png)
![Farming Simulator 22 12_26_2021 4_14_16 AM](https://user-images.githubusercontent.com/82164557/147403876-c7225663-8cbb-488e-923a-d1573a6c9525.png)
![Farming Simulator 22 12_26_2021 4_13_33 AM](https://user-images.githubusercontent.com/82164557/147403878-fd1ed019-488a-488a-90b7-5e0d6d7e706c.png)

These pics are V2.0.0.2
![Farming Simulator 22 12_26_2021 4_20_25 AM](https://user-images.githubusercontent.com/82164557/147404004-b0c86ae9-b69b-4f51-a0dd-b82a14167a86.png)
![Farming Simulator 22 12_26_2021 4_21_20 AM](https://user-images.githubusercontent.com/82164557/147404007-17b328fa-76a9-4b14-9e0b-dec67c6882ca.png)
![Farming Simulator 22 12_26_2021 4_19_42 AM](https://user-images.githubusercontent.com/82164557/147404011-98634a4a-3053-4a49-b348-79d319af108d.png)

And this is not a big thing but it really helps out.

**Comment by ph1go** [comment]
There were problems with the automatic creation when it came to intersections so they were disabled in v2.0.0.1. The roads are all added but intersections aren't.

https://github.com/Stephan-S/FS22_AutoDrive/issues/4

**Comment by Laku83** [comment]
I think I have the same problem but with version v2.0.0.2 in Haut Beyleron where points are created but not connected in the intersections. I'm updating them manually in the editor by @KillBait. Here is a video in case you need it to solve the problem.
[https://user-images.githubusercontent.com/3968257/147572181-9a832d17-1096-4597-990b-91b06d91582f.mp4](url)
