### ISSUE TITLE
Game Freezes When Starting a Route with Autodrive Until the Vehicle Reaches Its Destination

### ISSUE THREAD

**Issue by charlotte507** [Stephan-S/FS22_AutoDrive#1171]
I am trying to use Autodrive in the game Farming Simulator 22. I downloaded and installed the map routes that I am playing on. When I get into a vehicle and set it to start driving to another point, I can't get out of the vehicle and move around. The camera freezes, and although the game keeps running, my character is frozen until the vehicle reaches its destination. Once it arrives, I can move again, get out of the car, and continue playing, but in the meantime, it's as if the game freezes while Autodrive is functioning.

I tried with simpler routes and created a route from scratch that was just a straight line, and the same thing happened.

add the following files from client and server in one .zip file here:
log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml
[autodrive.zip](https://github.com/user-attachments/files/17355630/autodrive.zip)

**Comment by Axel32019** [comment]
log.txt is missing. Without it we cannot investigate - please add this!

**Comment by charlotte507** [comment]
[autodrive.zip](https://github.com/user-attachments/files/17358271/autodrive.zip)

**Comment by Axel32019** [comment]
No errors seen from AD.
Many errors seen from other mods, i.e. 1991DodgeRamW250.
Try the following:
Remove all mods causing "error", "LUA call stack" etc. physical from your mods folder.
