### ISSUE TITLE
Reverse driving

### ISSUE THREAD

**Issue by BoxerHUN** [Stephan-S/FS22_AutoDrive#1172]
Can AutoDrive also be expected to handle reversing multi-pivot trailers? He currently manages only one. Trailers with rotating stools "stiffen" when reversing. CoursePlay v6.5 (FS19) handled it perfectly.

The essence of the error is that it is impossible to reverse to certain places because of this.

Even in such a small area, the CP reverses without fail.
https://www.youtube.com/live/gPJqo0z_crc?si=cAblTUa0BYv5xEvb&t=340

**Comment by Iwan1803** [comment]
AD can handle 1 trailer and there is no plan to handle more.
