### ISSUE TITLE
FS25_AutoDrive

### ISSUE THREAD

**Issue by Tritura2** [Stephan-S/FS22_AutoDrive#1183]
I just want to know, if you guys are working on a FS25 Version?

**Comment by asundrus** [comment]
> I just want to know, if you guys are working on a FS25 Version?

https://github.com/Stephan-S/FS22_AutoDrive/issues/1177

**Comment by k4talin** [comment]
He answered.. maybe yes maybe now. What kind of arrogant answer LOL

**Comment by Iwan1803** [comment]
> He answered.. maybe yes maybe now. What kind of arrogant answer LOL

No comment on this... 🙄

Check #1184

**Comment by Tritura2** [comment]
> Check #1184

Thank you very much for your response and for providing us with an insight into the current status. 😃

**Comment by CrazyCarrot911** [comment]
instead of complaining, help in a way that you can. I donated a coffee, I am no programmer and can'
t help that way but I can give a coffee to support moral.
CP had given me a total of 2500h in FS22, well worth the 5$ imho.

Thank you !

**Comment by Mike1977** [comment]
> instead of complaining, help in a way that you can. I donated a coffee, I am no programmer and can' t help that way but I can give a coffee to support moral. CP had given me a total of 2500h in FS22, well worth the 5$ imho.
> 
> Thank you !

This is not CP. This is AD.

**Comment by TrainzmanUK** [comment]
Cannot wait. it it does get updated to 25, as our AutoDrive Guy YouTube is yearning for more material using this brillent addon for Farming Simulator that makes a huge difference to FS gameplay and loved my so many players.
Keep up the great work your doing for us and hope you all well and are taking a well deserved break for the Holidays.

**Comment by fudoido** [comment]
well, can only hope it is coming soon. i see latest update from courseplay mentions interactions with AD, so......
Come one guys, dont leave us in so much suspense, give us a small breadcrumb :p
