### ISSUE TITLE
AutoDrive for FS25?

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS22_AutoDrive#1184]
Discord-News vom 22.11.2024:

Der LS25 ist erst seit ein paar Tagen raus und Giants hat doch einige Änderungen im Hintergrund vorgenommen. Leider gibt es darüber (aktuell) noch keine Dokumentation, so das alle Modder (und bes. Skriptmodder) im Try&Error-Verfahren versuchen, ihre Mods wieder ans Laufen zu bekommen. Hiervon ist AD natürlich nicht ausgenommen und aktuell versuchen wir im Team zu ermitteln, was diese Änderung sind, was sie für AD bedeuten und ob wir die Probleme und Fehler überhaupt lösen können. Daher können wir aktuell keine Aussage machen, ob und wann es AD für den LS25 geben wird. Das verschiedene Aktionen aber noch funktionieren, macht uns Hoffnung.

_FS25 was released some days ago and Giants has made some changes in the background. Unfortunately there is (currently) no documentation on this, so all modders (and especially script modders) are trying to get their mods back working by trial and error. Of course, AD is not exempt from this and we are currently trying to find out what these changes are, what they mean for AD and whether we can solve the problems and errors at all. We are therefore currently unable to say whether and when AD will be available for the FS25. However, the fact that various actions are still working gives us hope._

**Comment by huseyinsayar** [comment]
Ich habe in einigen Videos gesehen, dass Autodrive 3.0.0.0 für FS25 getestet wurde. Was können wir tun, um Tester zu werden?

**Comment by Iwan1803** [comment]
Gar nichts, denn wenn dann suchen wir uns Tester 😉

**Comment by hjnkberlinart** [comment]
Iwan 1803, arbeitet in Ruhe, und lasst euch nicht Treiben. Nur wenn Ihr es möchtet, kann ich mittesten, dies jedoch nur wenn Ihr es möchtet.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS25_AutoDrive/releases
