### ISSUE TITLE
fyi: I will continue NL(dutch) translation

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS22_AutoDrive#12]
Hey guys, again nice work on FS22 version!
I need to work something out on my own mod (need to figure out how I get the ingame menu) before I can continue on the NL (dutch) translation. But I will shortly work on it (I think this week) ;)

**Comment by Iwan1803** [comment]
Thank you for that.
Here are instructions in case you want to do the pull request:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

If not, we are happy to just copy the file and add it ourself. Though that means that you will not be the official "creator" of those translations in Github and will not be listed as contributor 😁
