### ISSUE TITLE
Autodrive kills game and 2GB of my Ram

### ISSUE THREAD

**Issue by Terrabey** [Stephan-S/FS22_AutoDrive#120]
Hello I want to report an Issiue which is that when I play with Autodrive it freeze the game and need 2/3 GB of my Ram which is not good

**Comment by Axel32019** [comment]
Hello @Terrabey ,
How should we investigate without any further information than what you mentioned?
Please attach at least a log file.

**Comment by Terrabey** [comment]
So I was found that out by using every mod at once to check which mod kills the game and by using Autodrive my RAM has 1% Free space which means that it uses 2GB of my 2x 8 GB Cards.

**Comment by Terrabey** [comment]
I cant show you pictures because my Laptop crashes 5 seconds after seeing the Stats of usage.

**Comment by Axel32019** [comment]
Please attach at least a log file.

**Comment by Axel32019** [comment]
no update - closed
