### ISSUE TITLE
Doppelte Zielpunkte möglich

### ISSUE THREAD

**Issue by SaschaLie** [Stephan-S/FS22_AutoDrive#121]
Hallo
Habe festgestellt, daß es möglich ist, mehrere Zielpunkte gleich zu benennen. Wird da AD nicht Probleme machen?
Grüße, Sascha
![doppel](https://user-images.githubusercontent.com/96572157/147415900-5f6c60b8-2277-430e-b2ff-44cdfa9790e8.jpg)

**Comment by Axel32019** [comment]
Hallo @SaschaLie ,
AD hat damit kein Problem -  nur wie willst Du wissen welcher der vielen mit gleichem Namen wo hingehört?
Empfehlung: Keine gleichen Namen verwenden.

**Comment by SaschaLie** [comment]
Hatte mich mal verschrieben, da war der Trecker zum falschen Feld gefahren. Hatte mich dann gewundert, wo der hin will.
