### ISSUE TITLE
Default truck trailers work very poorly on combine unload

### ISSUE THREAD

**Issue by caracarn3** [Stephan-S/FS22_AutoDrive#122]
All three of the trailers that come with the game (and therefore those likely to be used by many people) all have multiple hoppers.   AD had a very hard time when emptying to sense and pull forward (see image).   I have to stop the harvester and wait 5 minutes for the truck to circle around a few times (see my other reported issue on turning radius for unload combine too short) to finally hit the back hopper of this trailer.   The other trailers have more hoppers and AD does not work with them at all (3 hopper trailer) or struggles to drive with the trailer (two trailer Wilson config with 80K capacity).

![image](https://user-images.githubusercontent.com/24917927/147416370-f5efe6eb-7e80-44a6-a454-360601c34d52.png)

**Comment by MoslessNeo** [comment]
This is an old issue, dating back to FS19.
Now maybe based on the game's AI it's possible to extract something. (_I also haven't tested whether the game AI can unload these trailers_)
What we can do is report what happened to the developer to try to adjust it.
They have 2 unloading locations and you must select one or the other. That's the big problem.

**Comment by Axel32019** [comment]
There will be an improvement in the next release. Please check it out.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
