### ISSUE TITLE
Turning radius on unload combine for trucks too tight

### ISSUE THREAD

**Issue by caracarn3** [Stephan-S/FS22_AutoDrive#123]
AD still uses a type of figure 8 track when unloading.   The truck comes from in front then loops out a bit and then turns around behind the harvester.   The truck begins that turn around far too fast and the trailer is not straight when it get back to the harvester.   This results in waiting for the truck to try multiple times or doing it manually which means then AD is not working in a way that makes it useful.  Here is the best it does.

![image](https://user-images.githubusercontent.com/24917927/147417183-7ccd4168-a0f0-472d-be9e-b28ebd9c4582.png)

**Comment by Stephan-S** [comment]
So we basically need to increase the straightening section. Not necessarily increase the turning radius.

**Comment by Axel32019** [comment]
There will be an improvement in the next release. Please check it out.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
