### ISSUE TITLE
Games freezes sometimes

### ISSUE THREAD

**Issue by StefanBraun2001** [Stephan-S/FS22_AutoDrive#125]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7777594/log.txt)
At first, here is my log. I don't know if it is helpful, but i post it here anyways.
I did forage harvesting (i drive the harvester myself) and i want to get the chaff to the U shaped Driving silo at the Elmcreek BGA (every Driving Silo has 5 lanes to make sure it is filled properly and evenly) When a unloader truck is full or done unloading at t he BGA, the game freezes for about a minute. It also happens if i exit the forage harvester. If i click too much, Windows say "Giants Engine 9.0.0 is not responding anymore" and it is impossible to get the current game unstuck again.
Any idea what it could be? There are a lot of course points at the bga (since every lane has a reverse course to the back wall and a course out of the driving silo and, of course there is a course to straighten tractor and trailer and a entrance and an exit from the bga premises), there is nothing i can do. Also, the unloading works perfectly fine (Helper drives back as far as possible and then unloads the chaff) and the driving out afterwards is working fine also

**Comment by Axel32019** [comment]
Hallo @StefanBraun2001 ,
Aus dem log geht nichts AD spezifisches hervor. Wenn möglich bitte mal ohne Coursplay im mod-Ordner weiter testen.

**Comment by StefanBraun2001** [comment]
Das werde ich bei Gelegenheit mal testen und berichten. Ist es eigtl. ok in Deutsch zu schreiben? Dann muss ich hier niemanden mit meinem Schrott-Englisch quälen.

**Comment by StefanBraun2001** [comment]
Passiert leider immer noch. Log vom Maishäckseln mit 2 Abfahrern ohne CP im Mod-Ordner und nur AD aktiv ist angehängt. Im übrigen passiert das manchmal auch, wenn man den Abfahrer einschaltet und er zu einem Ziel fahren soll.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7785957/log.txt)
Dieses mal hat sich das Spiel auch nach knapp 10 Minuten nicht wieder gefangen, so dass ich dann Task-Kill gemacht habe.

**Comment by Stephan-S** [comment]
Bist du sicher, dass das Log korrekt ist? Oder hast du den LS nach dem Absturz nochmal gestartet? Dort ist leider kein einziger Error drinnen

**Comment by StefanBraun2001** [comment]
Ich habe den LS nicht erneut gestartet. Bin zwar kein Programmierer, aber solche Basis weiß ich (und ich weiß auch, das das nicht böse gemeint ist). Soll ich ggf. mal ein Video der Situation aufnehmen und verlinken?

**Comment by Stephan-S** [comment]
Du könntest mal die Konsole im LS aktivieren, damit du Zugriff auf die Debug Einstellungen im AD Einstellungsmenü hast und dann dort auf jeden Fall mal die für das Fahrzeug aktivieren. Vlt noch Pathfinder und Streckennetz und wenn du es damit aushältst etwas zu spielen bis der Fehler kommt steht dort vielleicht etwas nützliches

**Comment by StefanBraun2001** [comment]
Habe das mal gemacht. Der Modus Streckennetz hat einige Sackgassen/tote Punkte auf der Map aufgezeigt. Die habe ich mal entfernt (bis auf die auf der Map-Ausfahrt, da kommt man nicht ganz hin). Ich habe das Streckennetz ja noch mit 2.0.0 aufgezeichnet (zum größten Teil) Da gab es natürlich einige tote Punkte, die ich nicht gesehen habe und ich habe das Streckennetz auch noch nicht auf Herz und Nieren getestet. Die toten Punkte haben zum Teil zu geringen Umwegen geführt
Zurück zum Thema:
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7786349/log.txt)
Ich hab die gewünschten Debug Modes mal angemacht und wieder gehäckselt. Leider tritt das Problem immer noch auf. Ich weiß nicht, warum. Eingefahren sind die Kurse alle und die Verbindungen sind hergestellt.

**Comment by Kitekater** [comment]
Hallo, ich kann mich hier mal spontan mit einklinken.
Habe leider gerade keine Log parat, ist auch bei Auftreten des Fehlers nichts drin zu sehen.
Bei uns auf dem Server steht das komplette Spiel, wenn eine Strecke berechnet werden soll, bei der er dann kein Ziel findet.
Nicht immer aber einige Male. Steht aber dann für alle Spieler auf dem Dedi-Server.
Auch ruckelt es, wenn man einstellt, dass er mehrere Ziele anfahren soll. (Ordner-Option)
Beispiel:
Wassertrigger der Gewächshäuser soll angefahren werden, und zwischen den Punkten rucket die Fahrt, so als ob er den Trigger sucht, und dann steht auch das Spiel wieder für 10-30 Sekunden.

**Comment by Nomat50** [comment]
Hello dear developers, when playing FS22, I encountered a bug that I didn't understand, when I pressed Lev.Ctrl and the left mouse button of the left triangle of the waypoints of blue color is displayed. it is unclear what it is. I'm applying a screen. tell me how to get rid of it. Thank you in advance.
![fsScreen_2021_12_30_22_36_27](https://user-images.githubusercontent.com/95122983/147784070-2b2f718e-a4a7-47cf-8085-6dbfd4cbcb4c.png)

**Comment by Stummerl** [comment]
Hallo zusammen,
ich möchte mich bei dem Thema auch einklinken. Ich habe das gleiche Problem wie der Thredersteller. 
Sobald ich den Kurs Starten will friert LS ein und auch das InfoHub vom LS verschwindet in der Zeit. Dauer ist unterschiedlich, aber in der Regel so ca. 15-20 sec wo nichts geht. Habe dazu auch die CPU Auslastung beobachtet. Hier wir überwiegend nur 1 Kern der verfügbaren 16 genutzt und bei diesem bricht die Auslastung komplett ein in der Zeit. Auch bei der GPU verhällt es sich ähnlich. Habe die OriginalKarte Haut-Beyleron ohne Mods und die Kurse die Willi eingefahren hat. Übrigens vielen Dank dafür.
Die Kurse von Willi habe ich leicht für meine Bedürfnisse abgeändert.

Wenn der Abfahrer mit AutoDrive unterwegs ist und berechnet dann eine neue Route weil er zum Silo fährt oder ähnliches, dann friert auch wieder alles ein. Sprich jedesmal wenn eine Routenberechnung erfolgt dann steht das Spiel. 
Verwende die Version 2.0.0.2 schon länger. Dies tritt aber erst sein kurzem auf. Ich kann es aber nicht nachvollziehen ob dies mit dem Update von Giants gekommen ist.
LOG und AutodriveConfig im Anhang.
LOG-File sieht für mich sauber aus, aber ihr seid die Spezialisten.

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7809826/log.txt)

[AutoDrive_config.xml.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7809829/AutoDrive_config.xml.txt)

An dieser Stelle nochmals vielen Dank an das ganze Team für die tolle Arbeit die ihr hier Leistet.

**Comment by StefanBraun2001** [comment]
[AD-Backup Elmcreek.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7832747/AD-Backup.Elmcreek.txt)
Ich habe hier auch mal meine Kurse eingefügt. Ich möchte ehrlich gesagt das ungern nochmals komplett neu einfahren und ich möchte eigtl. schon meine eigenen Kurse verwenden (ich weiß, die sind teilw. echt komisch eingefahren)
Ich kann AD mittlerweile nicht mal mehr vernünftig zum Drescher abfahren verwenden, nach dem Abladen am Zielpunkt friert das Spiel immer dauerhaft ein (hab es einmal 2 Stunden laufen lassen ohne was am PC zu machen, nix passiert)
Ich werde jetzt wohl mal ein neues Savegame machen und nur ein paar Basic-Kurse für 2-3 Testfelder und für die BGA einfahren und berichten.

**Comment by Stummerl** [comment]
Was ich festgestellt habe, reicht es wenn du die AutoDriveConfig.xml aus dem Savegame entfernst und diese neu anlegst. Alternativ sind als Grundlage auch die wirklich guten Kurse von Willi geeignet. Findest du bei Hot-HQ.

**Comment by StefanBraun2001** [comment]
Ist ein guter Vorschlag. Allerdings möchte ich meine eigenen Kurse, ich bin da leider ein bisschen zu perfektionistisch. Die Kurse neu einzufahren dürfte sowieso eine gute Idee sein, da ich die Kurse größtenteils mit 2.0.0 eingefahren habe und ich da noch Anfänger war. Sollte es nach vollständigem einfahren wieder auftreten, melde ich das nochmal, ansonsten mache ich das Issue zu.

**Comment by StefanBraun2001** [comment]
So, Kurse neu eingefahren. Jetzt ist es deutlich besser. Das Spiel friert zwar immer noch ein, aber wirklich nur recht kurz für 5-10 Sekunden. War auch recht lustig, als ich 3 Häckslerabfahrer gleichzeitig losgeschickt habe und die sich im Weg standen. Die haben allen Ernstes sich selber befreit und nochnichtmal den Drescher gerammt. Beindruckend, was so ein Mod alles kann...

**Comment by StefanBraun2001** [comment]
Mit Version 2.0.0.3 hat sich das ganze jetzt nochmals verbessert. Auch diese kurzen Einfrierer von 5-10 Sekunden kommen jetzt nicht mehr vor, jegliche Kommandos werden nun nahezu instantan ausgeführt. Sehr gut!

**Comment by Kitekater** [comment]
Kann ich bestätigen
