### ISSUE TITLE
Truck follows when it can get to pipe to unload

### ISSUE THREAD

**Issue by caracarn3** [Stephan-S/FS22_AutoDrive#126]
Another unload problem, is that trucks do not approach the open pipe they just keep following.   The only way I have gotten it to work is to stop and wait 5 minutes for truck to finally manuver over.

![image](https://user-images.githubusercontent.com/24917927/147421407-61b4349a-589a-4532-9aea-a8afdf9a45b8.png)

**Comment by Stephan-S** [comment]
Could you enbable the Sensor Debug option in the AD Settings please and post a picture of that situation again? Thank you.
You have to enable the console in FS to access the AD Debug settings

**Comment by caracarn3** [comment]
Map maker released new version of the map that needs a new save to use, so when I get back to it will see if I can figure this out.   I'm not great with FS debug etc. so hope I can figure this out

**Comment by CyrilMaeko** [comment]
Bonjour , j'ai le même problème , je trouve les véhicules contrôlé par l'I.A. un peu lent pour rejoindre la batteuse a décharger

**Comment by Axel32019** [comment]
no update -> closed
