### ISSUE TITLE
Poor Backing up with Trailers

### ISSUE THREAD

**Issue by Resandise** [Stephan-S/FS22_AutoDrive#129]
When set to unload forage harvester, at the end of each row, the unloader backs up, but if the trailer is not straight, which it rarely is, it backs up and jack knifes, and the trailer "Pulls the tractor" into a un-necessary turn, and requires it to re-calculate a path back to the harvester, often times doing multiple circles around the harvester though the crops, and catching the harvester and pulling it off path.  Also, the pathfinder appears to be very poorly, and finds and very round about way to get to the harvester, often straight though fruit, even when avoid fruit is turned on
![fsScreen_2021_12_26_20_24_15](https://user-images.githubusercontent.com/96673100/147428063-cdd75b19-a21d-45f2-b5b3-937965336e09.png)

**Comment by alexanderweide** [comment]
I confirm this issue , had it today myself. It also dosent matter what trailer you use. At each row it does reverse piroettes. 
![Bildschirmfoto vom 2022-01-05 02-20-07](https://user-images.githubusercontent.com/7734241/148145942-ff021f3f-3ca9-426f-be56-f758e9ab2be4.png)

![Bildschirmfoto vom 2022-01-05 02-20-01](https://user-images.githubusercontent.com/7734241/148145933-fc7f7f22-d775-4458-82ff-6d32549b1f6b.png)
