### ISSUE TITLE
Kollisionserkennung stoppt vorm Bach auf der Elmcreek

### ISSUE THREAD

**Issue by Malfed** [Stephan-S/FS22_AutoDrive#13]
Hey,

wenn man unter den Einstellungen die Kollisionserkennung aktiviert, dann erkennt AutoDrive den Bach auf dem Hof bei Feld 46 auf der Elmcreek als Hindernis und fährt nicht hindurch. 

![Kollision0](https://user-images.githubusercontent.com/24369031/146644986-e9f18665-14f2-4bf7-8100-5e9f40e1399e.png)

Manche Fahrzeuge sind etwas entspannter und rollen langsam durch, andere nicht. Der Fendt 930 Vario stoppt z.B. vor dem Bach. 

![Kollision1](https://user-images.githubusercontent.com/24369031/146644987-9663e9f2-1a70-449f-89ed-d0a0510b0cf4.png)
![Kollision2](https://user-images.githubusercontent.com/24369031/146644991-c145cc81-6630-4327-ab0e-0ea773b53bbc.png)

Auch ein Übermalen mit einer anderen Textur und ein Löschen der Pflanzen hilft nicht. 

![Kollision3](https://user-images.githubusercontent.com/24369031/146644992-4d434006-7829-43ca-b4ff-1b10845afc51.png)

Lediglich ein sehr starkes Anheben des Geländes führt wohl dazu, dass das Hindernis nicht mehr erkannt wird. Vielleicht gibt es irgendwie die Möglichkeit zu erkennen, ob das Wasser durchfahren werden kann?

![image](https://user-images.githubusercontent.com/24369031/146645032-a5af27de-82b3-49b0-b02b-bca93392333c.png)

Ein einfacher Workaround ist ansonsten das Deaktivieren der Kollisionserkennung, aber vielleicht lässt sich das Problem ja auch lösen. Zum Test hatte ich außer AutoDrive keinen weiteren Mod geladen und habe auch einen neuen Spielstand gestartet.

Danke euch für den tollen Mod und die Konvertierung in den 22er! :)

**Comment by ct177mak** [comment]
versuch mal die Kollisionserhöhung über Grund auf 2,50m zu stellen ,im Screen steht die auf 1,25m ,vllt bissl zu tief für meinen Geschmack.

lg

**Comment by Malfed** [comment]
Gute Idee, damit funktioniert es und er fährt ohne Probleme durch den Bach. Ich hatte die Einstellung auch schon gesehen und auch im Tooltip gelesen, dass der Standardwert 2 ist und mich gewundert, warum es auf 1,25 steht - ich habe den Wert aber eigentlich nicht verstellt. Wenn ich einen neuen Spielstand starte, dann steht der Wert direkt auf 1,25 und nicht auf 2 oder 2,5.

Da sich mein ursprüngliches Problem aber durch eine Einstellung lösen lässt schließe ich den Issue mal.

Danke nochmal! :)
