### ISSUE TITLE
Kursfarbe Nebenstrecke beidseitig manchmal schlecht zu erkennen

### ISSUE THREAD

**Issue by ChrisBS91** [Stephan-S/FS22_AutoDrive#130]
![Kurs AD](https://user-images.githubusercontent.com/88283062/147446561-dfb75168-b2f3-411a-bfec-8197ebd5ed9a.png)

HI 
Könntet Ihr die Streckenfarbe von Nebenstrecke beidseitig vielleicht noch einmal überarbeiten?? 

Gerade auf Feldwegen, kann man sie manchmal echt schlecht erkennen. Siehe Tracktor und ein Feld davor

**Comment by 60erjonny** [comment]
Hallo

Das kann man doch selber.
https://www.youtube.com/watch?v=RP1USIKGxMc&list=PL5cOkXj5isconfMMPvBVCkAMh0AepBvey&index=23
Hier beschreibt Ivan1803 ( ca. ab Minute 12 ), wie das in der Version vom AD im LS 19 geht.
Diese Funktion ist auch in der AD im LS22....-)

**Comment by ChrisBS91** [comment]
AAAh, das wusste ich nich :-) 

THX, werde es gleich mal probieren
