### ISSUE TITLE
experimental Feature "Fold Implements",  fertilizer spreaders can no longer be uncoupled after AD drive - Düngestreuer können nach AD-Fahrt nicht mehr abgekoppelt werden

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS22_AutoDrive#131]
latest version 2.0.0.2

Hello,
If the experimental feature "**Fold Implements**" is activated, it is no longer possible to disconnect fertilizer spreaders.
As soon as a drive with fertilizer spreader has been made by AD, it is no longer possible to uncouple the devices.
Start+stop AD is enough, the vehicle does not even have to move.
When trying to disconnect with "Q", the following message appears 
**"Unhitching while the equipment is folding/unfolding is not allowed!"**. (see pictures)
However, the tested fertilizer spreaders can not open or close, because they do not have this function.
So far, I have only been able to determine this behavior with the fertilizer spreaders. 
On occasion please have a look. It has no priority, you can avoid the error by deselecting the feature.
Nothing appears in the log.
Greetings Micha
+++++++++++++++++++++++++++++++++++++++++

aktuelleste Version 2.0.0.2

Hallo,
ist das experimentelle Feature "**Fold Implements**" aktiviert, lassen sich keine Düngerstreuer mehr abkoppeln.
Sobald per AD eine Fahrt mit Düngerstreuer gemacht wurde, kann man die Geräte nicht mehr abkoppeln.
AD starten+stoppen reicht schon, das Fahrzeug muss sich nicht mal bewegen.
Es erscheint beim Abkoppelversuch mit "Q" die Meldung 
**"Abhängen während das Gerät auf-/zuklappt ist nicht erlaubt!"**. (siehe Bilder)
Die getesteten Düngerstreuer können aber nicht auf- oder zuklappen, da sie diese Funktion nicht haben.
Das Verhalten konnte ich bisher nur bei den Düngerstreuern feststellen. 
Bei Gelegenheit bitte mal anschauen. Es hat keine Prio, man kann ja durch Abwahl des Features den Fehler umgehen.
Im log taucht nichts auf.
Gruss Micha

![d1](https://user-images.githubusercontent.com/28841989/147436277-6aa024ab-f83a-4419-880f-c9086c0a5a9d.jpg)
![d2](https://user-images.githubusercontent.com/28841989/147436294-1478c993-5f57-43ae-bff3-24deef17d011.jpg)

**Comment by haamic** [comment]
Sorry, you must first sell/return the fertilizer spreader and couple the new one without the selected feature.
Then the uncoupling also works.
Thought it was enough just to deselect the feature, but unfortunately that still does not work.
++++++++++++++++++++++++++++++++++++++++++++++++++++
Sorry, man muss den Düngerstreuer erst verkaufen/zurückgeben und den neuen ohne das ausgewählte Feature ankoppeln.
Dann klappt auch das Abkoppeln.
Dachte es reicht nur das Feature abzuwählen, aber leider geht das trotzdem nicht.

**Comment by Axel32019** [comment]
This is still in development, so feedback is needed. Please deactivate and modify the vehicles.xml as following:
Look for <foldable foldAnimTime="0.001000"/>
If the value is 0.00100, 0.00200, 0.00300.... change to 0.00000, but 1.0000 is OK and not to be changed.

**Comment by haamic** [comment]
Hallo Axel,
du schriebst, "**Bitte deaktiviere und modifiziere die vehicles.xml wie folgt:.....**".
in der **vehicles.xml** im Savegame? finde da nichts.

Welche Werte genau, nach denen ich schauen soll?  Versteh leider nicht, was die vehicles.xml  mit dem experimentellen Feature zu tun haben könnte. Oder gibts noch irgendwo eine xml die genauso heißt?

die Daten des Düngerstreuers darin sehen so aus:

` <vehicle filename="data/vehicles/amazone/zats3200/zats3200.xml" id="21" isAbsolute="true" age="0.000000" price="25000.000000" farmId="1" propertyState="2" operatingTime="2738.603760" selectedObjectIndex="1" subSelectedObjectIndex="1">
        <component index="1" position="175.98321533203 85.382461547852 162.50883483887" rotation="171.27256687243 81.770205120692 172.14330670858"/>
        <configuration name="cover" id="1"/>
        <configuration name="fillUnit" id="1"/>
        <configuration name="fillVolume" id="1"/>
        <boughtConfiguration name="cover" id="1"/>
        <boughtConfiguration name="fillUnit" id="1"/>
        <boughtConfiguration name="fillVolume" id="1"/>
        <washable>
            <dirtNode amount="0.161853"/>
        </washable>
        <wearable damage="0.035325">
            <wearNode amount="0.032340"/>
        </wearable>
        <wheels lastWheelConfiguration="1"/>
        <attacherJoints comboDirection="-1"/>
        <foldable foldAnimTime="0.000000"/>
        <variableWorkWidth leftSide="6" rightSide="6"/>
        <fillUnit>
            <unit index="1" fillType="FERTILIZER" fillLevel="2638.975342"/>
        </fillUnit>
        <cover state="0"/>
        <workMode state="1"/>
        <actionController lastDirection="-1" numActions="1">
            <action name="turnOn" identifier="data/vehicles/amazone/zats3200/zats3200.xml" lastDirection="-1"/>
        </actionController>
    </vehicle>`

**Comment by Axel32019** [comment]
Hallo @haamic , Sorry da ging in der Formatierung was unter - korrigiert.
Suche nach `<foldable foldAnimTime="0.001000"/>`

**Comment by haamic** [comment]
Okay , da fehlte wohl wirklich etwas.
Wie du oben aber sehen kannst, steht bei mir ja schon 

foldable foldAnimTime="0.000000"

Wahrscheinlich, weil ein düngerstreuer nicht zum ausklappen gedacht ist.

**Comment by Axel32019** [comment]
Hat der Traktor ein Gewicht o.ä. vorne dran? Wenn ja dieses prüfen.

**Comment by mulei2507** [comment]
Das Problem hab ich beim Zusatztank aber ich löse das Problem mit frisch Einlogen auf dem Server

**Comment by haamic** [comment]
> Hat der Traktor ein Gewicht o.ä. vorne dran? Wenn ja dieses prüfen.

nein hat kein Gewicht dran

**Comment by mertchri** [comment]
Hallo zusammen, ich habe gerade das gleiche Problem wie haamic beschrieben hat. Ich habe das ganze im Vanilla Game ohne Mods (außer Autodrive) getestet, und wenn die Funktion "Fold Implements" aktiv geschaltet wird und Autodrive anschließend aktiviert wird (Fahrt zum Zielpunkt) und man danach den Anhänger abkuppeln möchte, kommt die oben genannte Fehlermeldung. Setzt man dann alle betroffenen Fahrzeuge zurück und deaktiviert vor dem Ankuppeln der Geräte den Punkt "Fold Implements", dann funktioniert alles wieder normal. 
Ich habe das Ganze auch mit einem Frontgewicht probiert, es lassen sich dann weder das Gewicht noch der Anhänger abkuppeln und man kann das Problem nur mit dem Zurücksetzen der betroffenen Fahrzeuge lösen. Ich habe auch mal Screenshots gemacht und hänge meine LOG hier an.

**Comment by mertchri** [comment]
![fsScreen_2021_12_28_17_02_42](https://user-images.githubusercontent.com/48655908/147587706-249c20a9-27e1-4372-ab79-ed83525dc922.jpg)
![fsScreen_2021_12_28_17_22_53](https://user-images.githubusercontent.com/48655908/147587712-93b76c99-1d26-4900-bd0e-bc50afff4c72.jpg)
![fsScreen_2021_12_28_17_25_03](https://user-images.githubusercontent.com/48655908/147587716-8082686f-7103-454f-afe6-d2a5d17cab40.jpg)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7785619/log.txt)
