### ISSUE TITLE
AutoDrive gui/logo

### ISSUE THREAD

**Issue by daensky** [Stephan-S/FS22_AutoDrive#132]
Not really an issue, here is something I've made to make it more FS22 oriented:
(btw, @Stephan-S , did you get my mail?)

new textures preview:
![preview](https://user-images.githubusercontent.com/95402697/147451895-9d024814-7c43-498d-bd16-9c173effe399.jpg)

new logo:
![logo](https://user-images.githubusercontent.com/95402697/147451969-0a46dcb2-89fe-4d6d-84b3-40127c04f741.png)

the files:
[FS22_AutoDrive_textures.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7779268/FS22_AutoDrive_textures.zip)

Some icons are left unchanged since I didn't see them used. (need feedback on this)
I will update this, some icons I've made need improvement.

**Comment by regs1980** [comment]
Nice HUD, I think the trailer symbols are very good

this is my variant
https://github.com/Stephan-S/FS22_AutoDrive/issues/27

**Comment by Stephan-S** [comment]
@regs1980 and @daensky This is currently voted at by all Discord members in case you haven't seen that yet :-)
Thank you for both of your contributions! This is really appreciated

**Comment by Axel32019** [comment]
Das hat sich mit dem DC voting erledigt.
