### ISSUE TITLE
Amazone UX11200

### ISSUE THREAD

**Issue by 60erjonny** [Stephan-S/FS22_AutoDrive#133]
Hallo
Wenn man ein Fahrzeug, mit dieser Spritze ( Mod ) mit AD los fahren lassen will, klappt sich immer gleich die Amazone UX11200 auseinander. Somit wird eine Überführung zum Feld unmöglich.
Mit den Giants-Helfer ( freie Fahrt ) ist das aber, ohne Probleme möglich.
https://www.modding-welt.com/mods/file/2713-amazone-ux11200/
Nun ist eben die Frage: Liegt es am Mod oder an AD...???
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7779579/log.txt)
![fsScreen_2021_12_27_10_45_49](https://user-images.githubusercontent.com/63659182/147459144-c6ba4393-0779-48d1-8d38-1eebc69c088d.png)

**Comment by regs1980** [comment]
Liegt am MOD mit den Standard Spritzen klappt es wunderbar.

<img width="1220" alt="2021-12-27 11_21_08-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147462806-d5b276f6-7bbb-418d-aaea-cac2f936a32d.png">

<img width="1145" alt="2021-12-27 11_19_24-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147462791-c7145752-8650-4515-b918-4fbd86a81171.png">

<img width="1279" alt="2021-12-27 11_20_18-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147462797-81985955-98b0-435e-b2f3-b344a2600fde.png">

**Comment by 60erjonny** [comment]
Hallo
Ah, habe hier auch schon danach gefragt:
https://www.modding-welt.com/mods/file/2713-amazone-ux11200/#comments

**Comment by Stephan-S** [comment]
Das war ein AD Fehler. Liegt an der experimentellen Einstellung zum Zusammenklappen der Geräte beim Start.
Ist behoben im nächsten Fix
