### ISSUE TITLE
Drescher wird nicht im Netzwerk registriert [Multiplayer]

### ISSUE THREAD

**Issue by MerryDev** [Stephan-S/FS22_AutoDrive#134]
Mir ist aufgefallen, dass der Drescher (Lexion 8900 + Convio 1380) nicht im Netzwerk registriert wird, sobald ein Non-Admin die Karre fährt. Sobald der Admin im Drescher sitzt erkennt der ÜLW-Fahrer (1050 + Bergmann ULW 4000 + 3000kg Fendt Gewicht) den Lexion problemlos und fährt auch hin (vorausgesetzt das Rohr ist ausgefahren).

**Comment by Stephan-S** [comment]
Hey, danke für die Meldung. Ich denke das Problem ist identifiziert und behoben. Der Test im MP steht noch aus
