### ISSUE TITLE
AD Mapmarker ?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#135]
Hallo Leute
im LS19-AD hatte man auf der Map immer so schöne weiße "pümpel", 
im LS22 gibt es diese nun nurmehr im ESC-Menü:
![fsScreen_2021_12_27_14_33_15](https://user-images.githubusercontent.com/24860501/147476800-42531916-79a4-4b31-b43e-f6809c9276b3.png)

in der Map ingame werden diese zu blauen Rauten:
![fsScreen_2021_12_27_14_33_24](https://user-images.githubusercontent.com/24860501/147476850-658f9d7c-9e9d-42bf-873d-073ce0024345.png)

soll das so sein?
fand diese weißen pümpel (inLS19) in der ingame-map immer besser und sie wären auch einfacher als AD icons zu erkennen.
lg
andreas

**Comment by Axel32019** [comment]
Hallo @andreasthu , 
Schick mal ein Dankeschön an Giants für die fehlende Script-Doku. 
Hier mussten wir uns bei bekannten Placeable-Hotspots bedienen, das einzige was derzeit so überhaupt funktioniert. Wenn es in Zukunft was besseres gibt machen wir was draus, im Moment nicht möglich.

**Comment by andreasthu** [comment]
danke für die info
lg
andreas
