### ISSUE TITLE
Problem beim joinen des Servers

### ISSUE THREAD

**Issue by EveryDayPIZZAA** [Stephan-S/FS22_AutoDrive#136]
Hey, ich und mein freund haben im Multiplayer folgendes Problem: Ich schicke ihn die autodrive zip datei zu, er zieht sie im mod ordner rein der mod wird auch im spiel erkannt aber wenn er im Multiplayer meinen Server Joinen will kommt dann das der mod nicht verfügbar ist.

**Comment by Iwan1803** [comment]
Ersetzt dein Freund auch die vorhandene Datei oder hat er sie mehrfach drin?

**Comment by EveryDayPIZZAA** [comment]
ja er ersetzt die datei auch

**Comment by Iwan1803** [comment]
Keine Ahnung, was da auf dem Weg vom hoch- zum runterladen passiert, aber ladet doch einfach beide mal die ZIP von hierunter und ersetzt die vorhandene Datei.

**Comment by EveryDayPIZZAA** [comment]
haben wir auch schon gemacht
