### ISSUE TITLE
Lua-Fehler nach dem Aussteigen bei Traktoren mit Freontlader, BigBagLifter (Dual) und angehängten Big Bags

### ISSUE THREAD

**Issue by SchorschiBW** [Stephan-S/FS22_AutoDrive#137]
Folgenden Fehler bekomme ich, wenn ich einen Traktor mit Frontlader und einem BigBag-Lifter nehme und bei angehängten BigBags aussteige:

2021-12-27 17:17 Error: Running LUA method 'update'.
E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:301: attempt to call method 'getAttachedImplements' (a nil value)

Der entsprechende Traktor ist danach nicht mehr zu gebrauchen, auch nach Neustart des Profils nicht mehr
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7780940/log.txt)

**Comment by Iwan1803** [comment]
Doppelt und daher geschlossen: https://github.com/Stephan-S/FS22_AutoDrive/issues/114
