### ISSUE TITLE
AD network goes 'underground' 

### ISSUE THREAD

**Issue by Strodey123** [Stephan-S/FS22_AutoDrive#14]
The network points are dropping below the road (only tested on French map) in certain places when they are moved. Both with the autogenerated network and user drawn.
![AD](https://user-images.githubusercontent.com/96347610/146648199-354c02aa-43d4-4378-b171-15b8c2383a48.png)

**Comment by Iwan1803** [comment]
For moving waypoints to keep the altitude on f.e. a bridge:
1. grab waypoint with right mouse button and hold it
2. press and hold left shift key
3. move the waypoint to its new location
4. there first release the right mouse button and then the left shift key

**Comment by Iwan1803** [comment]
And btw. it's duplicated: https://github.com/Stephan-S/FS22_AutoDrive/issues/5
