### ISSUE TITLE
Grimme Ventor 4150

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#141]
Wäre es möglich mehrere Arbeitsprofile erstellen zu können wegen dem Rohr? Damit man nicht immer die Abstände ändern muss?

Achso, und warum bleibt hier der Abfahrer nicht von der Grimme weg bis Sie abtanken soll? ER schiebt mich regelrecht auf der Map von hinten oder so wie gerade eben kommt er von vorne an und behindert mich... :-(

**Comment by BigBlackBahamut** [comment]
![20211227213220_1](https://user-images.githubusercontent.com/59480223/147505409-fc806db5-9251-4e8e-9443-d8c3a05fd044.jpg)
Hier nochmal. Der Abfahrer fährt die ganze Zeit hinter mir her. Was habe ich falsch eingestellt? Wenn ich mich dann drehe steht dieser mir im Weg. Klar fährt er weg, aber erstmal stehe ich....

**Comment by BigBlackBahamut** [comment]
Und jedes mal kurz bevor ich dann voll bin haut der Abfahrer ab!!

**Comment by RealNeo80** [comment]
weiteres Problem: wenn er hinterherfährt fährt er nicht früh genug in den Versatz sondern fährt ran, bleibt stehen, und muss dann zum abbunkern zurücksetzen Versatz vom Rohr ist auf 3.5m eingestellt
![vektor abtanken](https://user-images.githubusercontent.com/8066324/147668428-18bbe6fa-d40a-4bb8-9459-ee4355df7f91.png)

**Comment by RealNeo80** [comment]
OT: @BigBlackBahamut  was nutzt du für einen Mod um die Füllstände anzuzeigen?

**Comment by BigBlackBahamut** [comment]
Das ist der VehicleInspector 1.75. Gefunden bei ls-portal.eu

**Comment by BigBlackBahamut** [comment]
So, noch einmal was neues. Sowohl Grimme Rüben als auch Grimme Kartoffeln. Sobald ich mit den großen Erntern unterwegs bin fährt der Abfahrer immer sofort los. Er wartet nicht bis ich voll bin. Somit blockiert und schubst dieser mich.

Getestet auf MP.

**Comment by Axel32019** [comment]
@BigBlackBahamut Du kannst den Abfahrer durch Rohr ein- / ausklappen fernsteuern. Steht er im Weg wie im ersten Bild einfach in min. 20..30 m Abstand mit Rohr aus oder Taste "Abfahrer rufen" hinter den Ernter rufen, dann fährt er aus dem Weg.

**Comment by Axel32019** [comment]
@RealNeo80 Der Ernter fährt mit CP?
Aktuell kann AD wegen noch fehlender Infos von CP nicht so mit Erntern arbeiten wie das in LS19 war - bitte um Geduld!

**Comment by BigBlackBahamut** [comment]
> @BigBlackBahamut Du kannst den Abfahrer durch Rohr ein- / ausklappen fernsteuern. Steht er im Weg wie im ersten Bild einfach in min. 20..30 m Abstand mit Rohr aus oder Taste "Abfahrer rufen" hinter den Ernter rufen, dann fährt er aus dem Weg.

Wie man sieht (auf dem ersten Bild) ist das Rohr eingefahren. Sobald ich den AD aktiviere als Abfahrer (egal ob Kartoffel oder Zuckerrüben) fährt der Abfahrer los, und zwar dann so das er mit entweder von vorne kommt oder von hinten. Er bleibt nicht am Platz und wartet auf den Einsatz.

**Comment by cwattyeso** [comment]
An issue I'm experiencing with Autodrive trying to unload from these Potato and Sugar Beet Harvesters is that if the Trailer Driver is correctly able to drive in the correct lane beside the Harvester, they will nearly always drive ahead of the harvester so that the pipe is not able to unload into their trailer if they have a short/small trailer as the Autodrive Worker drives too far ahead of the harvester. It's almost as if they are expecting the Harvester to be a Combine or other such Vehicle where the Pipe is located in the centre or toward the front of the Harvester. The problem with these Potato and Beet Harvesters is that the pipe is located right at the rear.

**Comment by Axel32019** [comment]
> An issue I'm experiencing with Autodrive trying to unload from these Potato and Sugar Beet Harvesters is that if the Trailer Driver is correctly able to drive in the correct lane beside the Harvester, they will nearly always drive ahead of the harvester so that the pipe is not able to unload into their trailer if they have a short/small trailer as the Autodrive Worker drives too far ahead of the harvester. It's almost as if they are expecting the Harvester to be a Combine or other such Vehicle where the Pipe is located in the centre or toward the front of the Harvester. The problem with these Potato and Beet Harvesters is that the pipe is located right at the rear.

This is known and already fixed (not yet in release).
Workarounds: disable unload on the fly or use longer trailer(s)

**Comment by cwattyeso** [comment]
I did try disabling the unload on the move option, however the trailers would still drive and park past the pipe on the harvester preventing them unloading. I sadly didn't have the option of using a bigger or longer trailer, as was doing a harvesting contract at the time and had no control over the equipment given to me. Though I did try taking my own farm's tractor and trailer to the field and also attempting to use that to unload, but that combination of tractor and trailer, just kept wanting to drive into the harvester and no matter what I tried changing in the Autodrive options could not get it to recognise and drive the correct offset.
![fsScreen_2022_01_11_13_13_09](https://user-images.githubusercontent.com/13921716/149407719-ad4722f4-5eee-452c-b273-e6d4da03ac6f.jpg)

**Comment by Vanquish081** [comment]
This is solved?¿

No work fine with DEWULF ZKIVSE :(
