### ISSUE TITLE
Wenn Drescher sich eine Tasche gedroschen hat steht der AD Fahrer so 2 m vorne im Weg kann man das nicht AD sagen das er so 5m rückwärts fährt?

### ISSUE THREAD

**Issue by Brombee42** [Stephan-S/FS22_AutoDrive#142]
Also der AD Fahrer steht immer leicht im Weg wenn der Curseplay Drescher aus seiner Tasche wieder fährt und startet.Er schiebt den AD Traktor zwar weg, aber wenn das ein kl Drescher ist nicht.Dann wird der Curseplay Fahrer Blockiert.
![InkedfsScreen_2021_12_27_06_08_35_LI](https://user-images.githubusercontent.com/30389219/147512489-7e09c3a7-c271-4b5d-965f-b01ad61ba5b3.jpg)

**Comment by Stephan-S** [comment]
Die Lösung wäre also noch ein Stück weiter zurück zu setzen, korrekt? Oder hat er gar nicht zurückgesetzt nach dem Abladen?

**Comment by Brombee42** [comment]
Ja die Lösung wäre ein Stück zurückzusetzen denn er bleibt stehen .Der AD  fährt nicht zurück wenn Drescher übergeladen hat.

**Comment by Sacred-Shadow** [comment]
Kann da keine Probleme nachvollziehen ... CP macht bei mir ganz normal weiter, selbst wenn der Abfahrer sich kein Stück weiter bewegt. Aber es hängt halt wirklich davon ab, wie der Abfahrer an den Drescher ranfährt. 

Also können 1-2m gerade zurückfahren da wirklich wunder wirken.

**Comment by Axel32019** [comment]
Auch hier: Das liegt an der noch nicht vollständigen Kooperation mit CP - Hier ist Geduld gefragt da in beiden mods Anpassungen notwendig sind.
