### ISSUE TITLE
lost of connection

### ISSUE THREAD

**Issue by frabonk** [Stephan-S/FS22_AutoDrive#144]
can you tell me I have completed an autoroute in elmcreek, but the issue I have is when i make a new game in farm manager and putting the file in the config file into the brand new game and up load it to the server it always comes up with losted connection after maybe 10 seconds can anyone help thanks frank.

**Comment by Stephan-S** [comment]
Most likely an issue that was fixed in version 2.0.0.2.
Though you have to create a new AutoDrive network from scratch to use it on the server. The file could be corrupted if generated with the previous AD releases. Please reopen if the issue persists
