### ISSUE TITLE
sind gekreuzte Wege böse? / Edit: er scheint zwischen 2 punkten zu kleben

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#146]
Ich habe hier einen Weg auf dem sich 2 Linien kreuzen, und mein Abfahrer mag hier absolut nicht weiterfahren ...
![Abfahren](https://user-images.githubusercontent.com/8066324/147565363-d782b3e7-6ac7-45ff-b8a1-ebce39d631cf.png)

hab gerade die strecke nochmal mit dem Schlepper eingelesen da ich das vorher mit dem Mahindra gemacht hatte, hat aber nix geändert, nur die punkte sind jetzt etwas anders, es scheint aber dass er hier zwischen 2 punkten kleben bleibt. Das ist aber eine ganze strecke auf diesem Feldweg so, ab dem Bahntunnel bis ca. mitte 68/69 dann wird es besser, er bremst aber jeden punkt auf 5km ein

![Kleben](https://user-images.githubusercontent.com/8066324/147572765-f1b33d18-49d8-4a26-a1f6-2dd0776fadf2.png)

**Comment by Stephan-S** [comment]
Sieht mir eher nach der Kollisionserkennung aus. Stell die mal in den Einstellungen höhe oder komplett aus.
Wenn du Zeit und Lust hast, dann mache auch gerne mal in dem Zustand die DebugEinstellungen von AD zu den Sensoren an und mache dann mal einen Screenshot wie es vor dem Traktor aussieht

**Comment by RealNeo80** [comment]
ja das wars anscheinend, ich habe die Kollision von 1m auf 1,5gestellt. was komisch is dass damit anscheinend nur der Maxxum CVX 145 ein Problem hatte, der Große T7.315HD nicht. Mit Kollission 1,5m funktionieren beide. Sie bremsen zwar beide an fast der ganzen strecke jeden punkt ein, auch mit 1,5 aber sie fahren das ab. wenn ich später mal zeit hab kann ich dir die Debug noch machen

**Comment by Axel32019** [comment]
@RealNeo80 Siehe hier: https://www.youtube.com/watch?v=AjeZ-scB0Vk

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
