### ISSUE TITLE
Autodrive harmonization with Autoload and Pallets

### ISSUE THREAD

**Issue by Gillios** [Stephan-S/FS22_AutoDrive#148]
It would be great if you could send Autodrive out with an Autoload trailer to load pallets. (Wool / cheese / etc)

I think this went in LS19 so I would be very pleased if it would also come in LS22.

Many Thanks :)

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
