### ISSUE TITLE
constant forage harvesting deadlocks / detect grass as fruit

### ISSUE THREAD

**Issue by benjamint444** [Stephan-S/FS22_AutoDrive#149]
i am trying to let autodrive control my forage harvester and chaser tractor at the same time to harvest my grass field.

**what happens:**
whenever the tractor chases the harvester it picks a chase position to the left or the right. i.e. in the previous lane where the harvester has already been, or in the next lane where the harvester will go on his next pass when he turns around. if the tractor is in the future lane, 100% of the time when the harvester gets to the end and turns around crashes directly into the tractor and they sit there for a few minutes or forever locked in a deadlock.

**expected behaviour:**
chaser tractors prefer a rear-position rather than a side chase position when following a non-buffering harvester OR it just always picks the side where the grass has already been harvested.

 does "avoid fruits" not work for grass? (i think this is the problem, because it only seems to happen with grass and not corn...)

**Comment by benjamint444** [comment]
as a short term solution i think i will just edit the lua script to let me increase the pipe offset by more than 5m

i think if i can offset the chaser by like 9 meters he will be close enough to catch the silage but far enough away that he wont get crashed into

**Comment by Iwan1803** [comment]
AD is driving the harvester or did i misunderstood it?
As in FS19, we recommend to use a forage harvester with a long pipe so that the unloader can keep an appropriate distance.
Also "grass" was in FS19 a problem and we will take a look on it.

**Comment by benjamint444** [comment]
Yep AD is driving both the Harvester and the chaser. 

I already installed the longest pipe and increased the offset setting to +5m to try and get the chaser as far as away from the Harvester as possible but +5m wasn't enough.

**Comment by benjamint444** [comment]
Just in case it's important, It's the John Deere Harvester with longest pipe + Krone mower Header, on field 26 of Haut Beyleron.

 I don't think those variables make a difference but ... Who knows 😃

**Comment by Axel32019** [comment]
No AD use case - closed.

**Comment by benjamint444** [comment]
i see that it was marked as "no use case" and i just want to clarify that so i dont make any more issues that are wrong.


is it forage harvesters + grass that is not an AD use case, or that AD is controlling both the harvester and the chaser wagon that is not a use case?

**Comment by Iwan1803** [comment]
If you use AD for fieldwork, we won't support it because AD wasn't made for that.
