### ISSUE TITLE
Automatische Kurse für Felder / Automatic courses for fields

### ISSUE THREAD

**Issue by Rumspringa90** [Stephan-S/FS22_AutoDrive#15]
Moin,
als Ergänzung für das automatische Generieren des Streckennetzes wäre es noch cool, wenn auch die Feldrandkurse mit generiert werden.

as a supplement to the automatic generation of the route network, it would be cool if the field edge courses were also generated.

Grüße Rumspringa

**Comment by mlewelt** [comment]
Wofür soll das gut sein? Das hier ist nicht Courseplay.

**Comment by Rumspringa90** [comment]
Für den Abfahrer vom Drescher um den nächstgelegenen Punkt besser zu finden da nicht an jedem feldrand eine Straße ist

**Comment by Mike1977** [comment]
Die Kurse der Straße werden mithilfe der Splines generiert die auf der Map für den KI verkehr und den neuen total sinnlosen Helfer verbaut sind. Die Feldränder zu erkennen und dann mit Kursen zu versehen wäre so einfach wahrscheinlich garnich möglich...

**Comment by Iwan1803** [comment]
-> #839
