### ISSUE TITLE
Missing debug menu

### ISSUE THREAD

**Issue by pierrehicks** [Stephan-S/FS22_AutoDrive#151]
I was wondering if there is supposed to be a debug menu like there was in FS19 or if I need to activate it somehow

**Comment by Iwan1803** [comment]
For the debug menu you need to activate the console in LS22.
In the game.xml at the bottom change the marked lines:
![image](https://user-images.githubusercontent.com/47528836/147638877-60bb683b-09cf-4eeb-9cde-30d2b0cb76b8.png)

**Comment by pierrehicks** [comment]
Thank you

**Comment by RealNeo80** [comment]
@Iwan1803 and how could i open the debug menu, or do something with it? is there a description somewhere?
