### ISSUE TITLE
Jaguar TT

### ISSUE THREAD

**Issue by prehnj112** [Stephan-S/FS22_AutoDrive#153]
Hallo,
Wir haben auf dem Server fest gestellt, das der Jaguar TT Probleme mit den abfahrer hat. Der neue Krone z.b. hat überhaupt keine Probleme mit den Abfahrern.
Bei dem TT ist das lange Rohr ausgewählt.

**Comment by rohne83** [comment]
Eine präzisere Beschreibung der Art deiner "Probleme" wäre sicherlich hilfreich. Screenshots sind auch erlaubt.

**Comment by prehnj112** [comment]
Achso ja 
Bilder kann ich erst später zulegen.
Also der abfahrer fährt neben den Häcksler und nach ner Zeit bleibt der Häcksler einfach stehen und nimmt den abfahrer nicht mehr wahr. Der abfahrer fährt dann immer vor und zurück aber der Häcksler nimmt den abfahrer nicht mehr an.

**Comment by Iwan1803** [comment]
Ist der Jaguar ein Mod- oder Vanilla-Fahrzeug? Was ist mit dem Abfahrer und bes. dem Anhänger?
Wer fährt den Häcksler denn? Gibt es Meldungen dazu im Log-File? Screenshots?

**Comment by prehnj112** [comment]
Alles originale Fahrzeuge und Anhänger aus dem Spiel. Log kann ich gerade nicht sagen da sich der Server täglich neu startet. 
Die anderen Häcksler funktionieren aber wie sie sollen.
Soweit ich das noch weiß hatte Autodrive im 19er aber auch schon Probleme gehabt mit den Häcksler vom Dlc.

**Comment by Iwan1803** [comment]
Was in LS19 war, interessiert eigentlich nicht mehr 😉
Ich sitze gerade im Jaguar TT und konnte soweit keine Probleme feststellen. Meine 2 Abfahrer haben den Vanilla-Anhänger Strautmann Aperion 3401.
Das einzige war, das ich einmal das Schneidwerk aus- & wieder einschalten musste, da der Häcksler nicht mehr häckseln wollte sondern den Mais einfach runtergedrückt hat. Ob das nun aber mit AD in Verbindung steht, kann ich nicht sagen.

**Comment by Axel32019** [comment]
Mit diesen Angaben sehe ich nichts zu ändern -> closed
