### ISSUE TITLE
Diesel empty, AD still drives, just like Giants helper - Dieseltank leer, AD fährt trotzdem noch, genau wie Giants Helfer

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS22_AutoDrive#154]
Hello,
the Giants helper still drives, even if the diesel is used up.
Manually, however, no more driving is possible, not even the engine can be switched on.
AD behaves the same way and drives despite empty diesel to the gas station, you have set automatic refueling, or just where you send it. AD then creeps there with 6km/h without engine.
Is it the internal helper that AD also behaves this way, or could you make AD not want to drive anymore?
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
der Giants-Helfer fährt trotzdem noch, auch wenn der Diesel verbraucht ist.
Händisch ist aber keine Fahrt mehr möglich, nicht mal der Motor ist anschaltbar.
AD verhält sich genauso und fährt trotz leerem Diesel zur Tankstelle, man automatisches Tanken eingestellt hat, oder eben dahin wo man es schickt. AD schleicht dann mit 6km/h ohne Motor dort hin.
Liegt es am internen Helfer, das sich AD auch so verhält, oder könntet ihr AD dazu bringen, auch nicht mehr fahren zu wollen?

**Comment by Iwan1803** [comment]
Wenn der Giants-Helfer fahren kann, warum sollte AD das dann nicht auch können?
Ich finde das eigentlich ganz gut von Giants gelöst: entweder schleicht das Fahrzeug halt zur nächsten Tanke oder man benutzt halt doch den "Anhänger der Schande" 😉

**Comment by haamic** [comment]
Na realistisch ist das nicht, dann hätte Giants auch das manuelle fahren oder schleichen noch erlauben können, trotz leerem Tank. AD brauch demzufolge auch nicht automatisch tanken fahren, wenn's trotzdem funktioniert, auch ohne Diesel.   
Spart man sich das Tankgeld und ihr hättet die Funktion nicht einbauen müssen. Aber das habt ihr, eben weil es realistisch sein soll. Daher meine Frage, ob AD sich dann auch real verhalten kann, und nicht wie es Giants falsch vormacht.

**Comment by Iwan1803** [comment]
Wir haben die Tank-, Reparatur- und sonstige Funktionen nicht eingebaut, damit das Spiel "realistischer" wird, sondern weil es Vorschläge aus der Community waren und wir sie als sinnvoll (und mit vertretbarem Aufwand umsetzbar) bewertet haben. Das nur mal so zur Info...

Du darfst dich gerne bei Giants beschweren, wenn dir das Fahren mit (angeblich) leerem Tank nicht passt und das Spiel somit (angeblich) nicht realistisch genug ist. Ich glaube aber mal, das Giants keinen Anspruch auf 100% Realismus hat, denn dafür würden noch so etliche Features fehlen (Einsinken im Schlamm bei Regen, Deaktivieren von "Jahreszeiten" nicht möglich, u.v.m.).
Btw. ist es durchaus realistisch, das ein Fahrzeug mit (lt. Anzeige) leerem Tank dennoch fahren kann. Dies ist mir in jungen Jahren schon das eine andere mal passiert 🙄
