### ISSUE TITLE
[QUESTION] mehrere Abfahrer auf einem Feld Kollidieren am Zielpunkt

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#158]
wenn ich die Abfahrer  aufs Feld schicke, versucht der 2. immer den ersten zu umfahren um an den Zielpunkt zu kommen. Wenn einer bereits am Drescher ist, dann funktioniert das weil der 2. ja am Zielpunkt wartet. Gibt es ne Möglichkeit dem zu sagen dass er weiter hinten warten soll?

**Comment by Iwan1803** [comment]
Welche Einstellungen haben denn deine Abfahrer? Vermutlich ist nur eine Einstellung falsch.
Ein Screenshot vom Feld, wo sie stehen, könnte auch hilfreich sein.

**Comment by Axel32019** [comment]
Keine Rückmeldung -> closed
