### ISSUE TITLE
[Bug?] Einstellige Wegpunktbezeichnungen

### ISSUE THREAD

**Issue by Sacred-Shadow** [Stephan-S/FS22_AutoDrive#16]
Bin mir nicht sicher obs nen Bug ist oder gewollt ... aber ich kann keine einstellige Wegpunktbezeichnungen machen. 
Gibt keine Meldung in der normalen Log, wird einfach nur nicht gespeichert. 

Ist halt blöd für Feld 1-9 ... oder ich muss mehr schreiben als die Zahl alleine. 

Bug oder gewollt?

**Comment by Iwan1803** [comment]
ich würde die Nummern <10 immer mit einer Führungsnull beginnen, also 01, 02, etc.

**Comment by Sacred-Shadow** [comment]
Ich unterteile in Ordner ... 1-9 in einen ... 10-19 in nen anderen .. und soweiter. 
Aber joar könnte man schon so machen.

Nur sollte dann irgendwie was angezeigt werden, wenn AD das so nicht "mag". 
Oder ne führende 0 davor gesetzt werden?

Wobei du dann aber auch bei a-z das Problem hättest. 
Der Name muss halt aktuell zweistellig sein.

**Comment by Iwan1803** [comment]
Eigentlich sehe ich immer Ordner, welche 10 Felder beinhalten. Also 01-10, 11-20, etc.
In "Felder 01-10" packst du dann 01, 02, 03,....,10 rein. Dann bist du 2-stellig und das wird auch sauber geordnet angezeigt.

**Comment by Sacred-Shadow** [comment]
Ändert halt weiterhin nichts daran, dass AD so tut als würde es bei einstelligen Bezeichnungen speichern, es dann aber nicht macht.

**Comment by Stephan-S** [comment]
Ich würde mal sagen es ist ein Bug. Es wird aktuell auf Länge des Namens > 1 geprüft, wenn > 0 bzw >= 1 völlig ausreichen sollte.
Wird angepasst
