### ISSUE TITLE
Debug Menü

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#160]
Wie kann ich euch mit mehr Daten versorgen?

Console ist an, aber wie kann ich das Debug Zeugs einschalten?

**Comment by Iwan1803** [comment]
In den AD-Einstellungen findest du mit aktiviert Konsole die Brille, wo verschiedene Debug-Einstellungen vorhanden sind:
![image](https://user-images.githubusercontent.com/47528836/147818790-c0625b57-74d9-45ef-a55d-f694d22e9ee0.png)

**Comment by RealNeo80** [comment]
so einfach wenn mans weiß :p

**Comment by Iwan1803** [comment]
Dann mach ich hier mal zu 😉

**Comment by RealNeo80** [comment]
kann man das anpinnen? bin bestimmt net nur ich ders sucht ;)Von meinem/meiner Galaxy gesendet<div>
</div><div>
</div><div>-------- Ursprüngliche Nachricht --------</div><div>Von: Iwan1803 ***@***.***> </div><div>Datum: 31.12.21  16:14  (GMT+01:00) </div><div>An: Stephan-S/FS22_AutoDrive ***@***.***> </div><div>Cc: RealNeo80 ***@***.***>, Author ***@***.***> </div><div>Betreff: Re: [Stephan-S/FS22_AutoDrive] Debug Menü (Issue #160) </div><div>
</div>

-------- Original Message --------
Subject: Re: [Stephan-S/FS22_AutoDrive] Debug Menü (Issue #160)
From:    Iwan1803 ***@***.***>
To:      RealNeo80 ***@***.***>

Dann mach ich hier mal zu 😉

**Comment by Iwan1803** [comment]
Wenn die Leute die Suche benutzen, werden sie es auch finden. Ansonsten müssten wir dutzende Issues anpinnen 😉

**Comment by duokanduoxue** [comment]
没有调试菜单选项
![QQ图片20220102200931](https://user-images.githubusercontent.com/50108417/147875261-147308f7-c042-4e9c-92ec-758f295a8b5c.png)

**Comment by duokanduoxue** [comment]
> In den AD-Einstellungen findest du mit aktivierter Konsole die Brille, wo verschiedene Debug-Einstellungen vorhanden sind: ![image](https://user-images.githubusercontent.com/47528836/147818790-c0625b57-74d9-45ef-a55d-f694d22e9ee0.png)

> 
![QQ图片20220102200931](https://user-images.githubusercontent.com/50108417/147875278-bc5e2222-b414-4386-95fc-4c1c7995792b.png)

**Comment by Iwan1803** [comment]
You need to activate the console in FS22 to see the debug menu.
