### ISSUE TITLE
Pfadfindung über Flüsse und Gräben?

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#161]
das war einfach der nächste Punkt, das ist korrekt ... aber doch nicht durch den Graben :P .... gibts net möglichkeit ausser an den Gräben entlagen eine einbahnstraße zu ziehen auf die er fahren muss?

![Screenshot_4](https://user-images.githubusercontent.com/8066324/147760791-c62dc265-9e06-470a-b069-a06be8999aee.png)

**Comment by Iwan1803** [comment]
Man zieht eine Fanglinie rund ums Feld und stellt die Feldausfahrtstrategie auf "Nächstgelegen" um.
https://youtu.be/9soMdjVEpt0

**Comment by dominiczeth** [comment]
Autodrive kontrolliert höchstens auf collis, nicht aber auf Berge, Täler oder Gräben
