### ISSUE TITLE
Autodrivekurse löschen sich nach Zeit aus Savegame

### ISSUE THREAD

**Issue by Jakky911** [Stephan-S/FS22_AutoDrive#163]
Ich habe das Problem, das nach einer halben Stunde spielen mit vielen Kursen das Spiel abstürzt und die AutoDrive_config Datei im Savegame gelöscht wird.
VG

**Comment by skjatala** [comment]
> I have the problem that after half an hour of playing with many courses the game crashes and the AutoDrive_config file in the savegame is deleted. VG
Read this Topic
https://github.com/Stephan-S/FS22_AutoDrive/issues/55#event-5805565092

**Comment by Iwan1803** [comment]
Single- oder Multiplayer oder Dedi-Server? Immer nach einer halben Stunde? Vielleicht sogar immer bei einer bestimmten Aktion?
Bitte nach dem nächsten Crash das Logfile sofort hier hochgeladen.

**Comment by Axel32019** [comment]
Kein Update -> closed
