### ISSUE TITLE
is it possible to modify a roads without being in a vehicle?

### ISSUE THREAD

**Issue by Nos510** [Stephan-S/FS22_AutoDrive#164]
It will be very interesting if we could modify a roads without having to be in a tractor it will be a very interesting mechanism to develop

**Comment by Iwan1803** [comment]
Ingame: no.
You can try the external editor: https://github.com/KillBait/AutoDrive_Course_Editor

**Comment by dominiczeth** [comment]
Could it be possible to implement that in the building mode from the game?

**Comment by Iwan1803** [comment]
How should it work? Do you want to be able to walk across the map and then create and move waypoints?
You can't get zoom enough into the map to be able to do anything sensible there.
I don't understand why using a vehicle for route editing is a problem for you.

**Comment by Flatts3000** [comment]
The main use I see is when I want to send a worker along a route while my character stays and fine tunes the nodes. Not sure its worth the effort but I've found myself wanting to do it several times.

**Comment by Ashtoruin** [comment]
> The main use I see is when I want to send a worker along a route while my character stays and fine tunes the nodes. Not sure its worth the effort but I've found myself wanting to do it several times.

Same. I *could* go get a truck or gator, but I want the AI to keep going and I'm already there. Could be a handheld GPS or something.

**Comment by Axel32019** [comment]
See: https://github.com/Stephan-S/FS22_AutoDrive/wiki/Release-Notes-for-AutoDrive-english
Release 2.0.0.1 (22.12.2021):
New functions:

    AD can be controlled in the helper HUD #9
