### ISSUE TITLE
AD verweigert Abtanken

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#165]
Er schafft es einfach nicht dass er unter den Drescher kommt

![Drescher](https://user-images.githubusercontent.com/8066324/147836600-6d2b0bc9-48cd-434d-8aa4-381adc8e99e7.png)
[log_AD.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7796916/log_AD.txt)

EDIT:
jetzt das kuriose, nach speichern und neu laden, gehts
![Screenshot_5](https://user-images.githubusercontent.com/8066324/147836824-7c907b3a-21b5-4293-985f-2c4ffa84239e.png)
[restlog.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7796920/restlog.txt)

**Comment by RealNeo80** [comment]
Edit habs gefunden, das war die 4m kollissionshöhe ... dafür ruckelt er jetzt wieder an manchen wegpunkten :P aber irgendeinen Tod muss man sterben oder wie war das ^^

**Comment by 60erjonny** [comment]
Hi
Welche Wert hast du jetzt, eigentlich gewählt?
...empfohlener Standart wäre ja 2 m...ich habe 1,75 m eingestellt...

**Comment by RealNeo80** [comment]
jetz hab ich 2m, er bremst aber manche punkte extrem ein, gerade wenns durch tunnels oder über brücken geht

**Comment by Axel32019** [comment]
Ursache gefunden -> closed
