### ISSUE TITLE
Streckennetz nicht Sichtbar

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS22_AutoDrive#167]
HI, hab seit gestern mit der 2003 RC und dem neuen Design das Problem, ich kann mit der rechten Maus die Linien nicht mehr einschalten. Es geht nur noch die linke Maus zum Editieren. Gibt keine log Fehler.

LG Timmi

**Comment by Axel32019** [comment]
Kann ich nicht bestätigen - @Iwan1803 wie sieht es bei Dir aus?

**Comment by dominiczeth** [comment]
Ich habe die 2.0.0.3 RC ebenfalls getestet. Ich habe damit keine Probleme.

**Comment by timmi4026** [comment]
Wenn ich mit der linke Maus auf das Dreieck klicke kann ich Strecken Editieren und so. Nehme ich die rechte Maustaste kann ich mir ja die Strecken anzeigen lassen ohne den Editiermodus, und genau das geht nicht mehr. Bei der 2002 geht es noch, und das Hud setzt sich immer an den rechten Bildschirm Rand zurück. Ach so hab vllt vergessen zusagen das ich auf Server spiele.

**Comment by Iwan1803** [comment]
@Axel32019  ich habe es gerade getestet und im SP funktioniert die RC einwandfrei.
Auf dem Dedi hingegen klappt der Rechtsklick nicht und auch die Position des HUD wird nicht mehr korrekt gespeichert. Es wird nach dem Serverbeitritt wieder an die Default-Stelle zurückgesetzt.

**Comment by Kitekater** [comment]
Vielleicht passt das auch dazu.
Jedesmal wenn ich den Server betrete (SP weiss ich nicht) ist der Editiermodus aktiv. Auch wenn ich ohne Edit Modus das Spiel verlasse.

**Comment by ChrisBS91** [comment]
Das Neue Design sieht super aus :-) 
Könnt Ihr schon sagen wann es für alle kommt??

**Comment by Axel32019** [comment]
@Kitekater Ich kann das nicht nachvollziehen. Mit welcher Version hast Du das festgestellt?
Kannst Du mal mit der Entwicklungsversion dev_stephan testen?

**Comment by Iwan1803** [comment]
@Axel32019 den Bug gab es in LS19 schon.
Hier wurden nicht die User-Settings genommen sondern die Einstellungen aus der AD-Config selber.
Hat man im SP z.Bsp. das Anzeigen der Linien aktiviert (kein Edit-Modus) und die Config dann auf den Server geladen, hatten alle diese Einstellung.
Ob das zwischenzeitlich gefixt worden ist, kann ich aktuell nicht sagen, aber bei Bedarf nachher mal testen.

**Comment by Kitekater** [comment]
@Axel32019 
Ich nutze die 2.0.0.2
Spielen auf einem Server und nur ich habe es beim Starten.
Werde spaßeshalber mal ein SP starten und es dann ausschalten, mal sehen was dann passiert
