### ISSUE TITLE
Cycle Unload - Start and stop

### ISSUE THREAD

**Issue by Petromotion** [Stephan-S/FS22_AutoDrive#171]
When using the cycle unload for greenhouses if the unload areas are in a loop it starts and stops the trailer. It triggers for the 1L of water and does a small fill until the trailer moves out of the fill trigger. 

Is it possible to only fill that stop one time and move to the next or only fill if under 98%?

**Comment by Philj030** [comment]
Agree having the same issue if i have 4 greenhouses would be nice to just do a loop past all 4 water triggers and have it only  top up #1  by 5% when it is at 95%  and 2 another 10 % (its at 90%) and skip 3  (100%) and then fill 4

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
