### ISSUE TITLE
Warning Meldung im Log Text AutoDrive_init_config.xml

### ISSUE THREAD

**Issue by Ralf1806** [Stephan-S/FS22_AutoDrive#172]
Hallo AD Team, ich habe eine Frage, wenn ich ein neues Savegame starte, erscheint folgende Warning Meldung :    
 **Warning: [AutoDrive] Can't load init config from C:/Users/ralf/Documents/My Games/FarmingSimulator2022/mods/Mod_Map_Alpine/AutoDrive_init_config.xml**
Wäre echt klasse, wenn man mir erklären könnte woran das liegt, bzw. selbst ob ich den Fehler selbst beheben kann.
Übrigens ich nutze bereits das Release AutoDrive 2.0.0.2
Vielen Dank im Voraus

**Comment by Axel32019** [comment]
Hallo @Ralf1806 , Das ist nur ein Hinweis, kannst Du ignorieren.

**Comment by dominiczeth** [comment]
Kurze Frage: wofür ist diese Datei denn? Kann man fertige ad Kurse mit der Modmap zusammen ausliefern?

**Comment by Stephan-S** [comment]
Ja genau. Wir hatten mal eingebaut, dass das möglich wäre.
