### ISSUE TITLE
Detach problem 

### ISSUE THREAD

**Issue by Albatrozs112** [Stephan-S/FS22_AutoDrive#174]
Hello 
After i turn off AutoDrive i can detach.
All time show this on regular trailer 
"Detach while folding is not allowed!" warning hint.
Just help reset all,and lose goods in it. :(

**Comment by Woogielicious** [comment]
Same problem here since we have installed the latest AD version. After Server restart if its fine, but if you started any AD course after that nothing can be detached from the tractor anymore.

**Comment by dominiczeth** [comment]
Try it with "Strg+X", does that work?

**Comment by Iwan1803** [comment]
Please set this option to "No" and try again:
![image](https://user-images.githubusercontent.com/47528836/147937920-d635d253-69bf-4eb6-9c12-8dfb776c842c.png)

**Comment by Woogielicious** [comment]
> Please set this option to "No" and try again: ![image](https://user-images.githubusercontent.com/47528836/147937920-d635d253-69bf-4eb6-9c12-8dfb776c842c.png)

Yes after that it worked again.

**Comment by Iwan1803** [comment]
@Axel32019 da solltest du noch mal einen Blick drauf werfen, da ähnliche Meldungen auch immer wieder in DC auftauchen 😉

**Comment by Axel32019** [comment]
see #131

**Comment by Albatrozs112** [comment]
@Iwan1803 @Woogielicious @Axel32019  
I don't understand german language.
And this why i can't read many issus :(

**Comment by Woogielicious** [comment]
That is why we write in english. :D the german part is not nessesary for you.

**Comment by Dzi4d3k** [comment]
@Albatrozs112 just put particular issue link into translate.google.com, and choose preferred destination language, and open in new windows with marked icon: 

![obraz](https://user-images.githubusercontent.com/12050055/148066569-5bb023e9-2c5e-4378-a8c3-55169b92c2d1.png)
