### ISSUE TITLE
Change of target while unloading combine

### ISSUE THREAD

**Issue by norges** [Stephan-S/FS22_AutoDrive#175]
I use autodrive to unload a combine and to deliver the crops to the silo on my farm. Unfortunately after it unloads the target changes to another one for the next unload. Since that position can't unload crops the driver drives circles with the full trailer. 

In case more info is needed I will give that.

**Comment by rohne83** [comment]
Seems you have activated the 'Use Folders' and 'Cycle Pickup and Deliver' options. Deactivate at least the latter, and it will always drive to the same targets again.

**Comment by norges** [comment]
I had the option activated right, I did not read the tooltip and thought it meant keep going between the points.  Sorry and thanks for the very fast help.
