### ISSUE TITLE
Kollisionserkennung an Bahnübergängen

### ISSUE THREAD

**Issue by MatzeB62** [Stephan-S/FS22_AutoDrive#176]
ist es möglich, Autodrive beizubringen, an geschlossenen Bahnübergängen anzuhalten?

**Comment by norges** [comment]
Das wäre eine super Verbesserung 

Ich hatte auf der erlengrad Mappe heute mehrfach meinen Traktor samt Hänger neben der Straße liegen weil er gegen die geschlossene Schranke fährt und dann dich diese hochgehoben und umgekippt wird.

**Comment by Iwan1803** [comment]
Auf der französischen Map hab ich keine Probleme damit.
Die Kollisionshöhe habe ich auf 2m eingestellt.
Bitte prüft das mal bei euch.

**Comment by SaschaLie** [comment]
Ich habe die Probleme auf der Haut auch. Schranke zu, Zug kommt, der vom Traktor erkannt wird und er bleibt stehen. Sobald der Zug weg ist, fährt der Traktor los und will durch die Schranken. Kolli auf 2m.

**Comment by Sacred-Shadow** [comment]
Das war halt leider schon immer nen Problem von AD .. egal auf welcher Map.
Mal funktioniert es gut ... Fahrzeug hält sauber an ... manchmal aber auch nicht .... aber spätestens wenn der Zug weg ist und die Schranke auf gehen wird, fliegen die Fahrzeuge einmal durch die Lust (weil se an der Schranke hängen).

Lösungsidee wäre evtl. für Bahnübergänge ne eigene Punktart (evtl. Wartepunkt?) anlegen zu können. 
An denen AD die Fahrzeuge nach Aufhebung der Kollisionserkennung (was bestenfalls von der Schranke oder im schlimmsten Fall vom Zug ausgelöst wird) einige Sekunden (einstellbar) warten lässt. 

Wenn das Anhalten funktioniert, müsste es so funktionieren, dass das Fahrzeug erst bei offener Schranke wieder losfahren wird.

**Comment by norges** [comment]
> Auf der französischen Map hab ich keine Probleme damit.
> 
> Die Kollisionshöhe habe ich auf 2m eingestellt.
> 
> Bitte prüft das mal bei euch.

Die kolissionshöhe steht bei mir auf 2m und kollisionserkennung ist an

**Comment by Axel32019** [comment]
Stellt mal bitte die Kollisionshöhe auf 1,5 m, dann werden die Schranken erkannt und das Fahrzeug hält davor an.
Empfehlung ist weiterhin eine leichte Schlangenlinie davor zu erzeugen damit die Fahrzeuge nicht mit >100 km/h darauf zu fahren, ein Bremsen ist dann nicht mehr möglich.

**Comment by SaschaLie** [comment]
Klappt: Kolli an, 1,75m. Habe vor und nach dem Bahnübergang diese "Zacken" eingebaut. Traktor fährt schön langsam & erkennt die Schranken
![BU](https://user-images.githubusercontent.com/96572157/148161940-022c8266-d330-48e9-867c-f8af1fa85704.jpg)

**Comment by RealNeo80** [comment]
aufgespießt :p
![image](https://user-images.githubusercontent.com/8066324/149675170-8ccfdbd0-ed05-4b49-a200-3ba3806628ea.png)

**Comment by Iwan1803** [comment]
Ja, toll, und? Was soll uns das jetzt sagen und vor allem wann genau ist es passiert?
Hat du die empfohlene Kollisionshöhe eingestellt? Die Zacken zum Abbremsen sehe ich zumindest nicht.

**Comment by Axel32019** [comment]
@RealNeo80 Wie's geht zeigt @SaschaLie - closed
