### ISSUE TITLE
Frame enhancement in default position

### ISSUE THREAD

**Issue by Markus33-ITA** [Stephan-S/FS22_AutoDrive#18]
Hi Stephan-S. Not that it's a problem, I would like to ask if possible a better frame positioning because it is superimposed. With the displacement it resolves. I like to leave it in the default positions.

[https://i.imgur.com/8DYe5to.png](https://i.imgur.com/8DYe5to.png)
[https://i.imgur.com/U4mrkOn.png](https://i.imgur.com/U4mrkOn.png)

**Comment by Iwan1803** [comment]
You can move the HUD to any position you like. I don't know if there is a possibillity to check if the HUD is over other ones or outside the screen.

**Comment by Stephan-S** [comment]
But those are all other Mods using the same space as the AD HUD. I don't really see a need to adjust our default postion.
Like Iwan said, you only have to move the HUD once and this position will be stored for you. So, that should be fine, right?

**Comment by Markus33-ITA** [comment]
It's not a problem for me to move it. I just have to be careful and stay as close to the right edge as possible.
