### ISSUE TITLE
Wegpunkte auf Brücken werden ausgewählt

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#181]
wenn er automatisch unter der Brücke durchfahren soll, crasht er jedesmal in den Brückenpfeiler, da er die Wegpunkte von oben nimmt

![image](https://user-images.githubusercontent.com/8066324/148235611-454c12df-6233-4758-a7b1-eb27f73106b6.png)

**Comment by Axel32019** [comment]
Wie die rote Linie schon zeigt sind die oberen Wegpunkte die nächstliegenden und werden auch für die Wegfindung berücksichtigt. Da hilft nur etwas zurück fahren und neu starten.

**Comment by RealNeo80** [comment]
is mir schon logisch, dass der die oberen auswählt, hab ich ja geschrieben, hast ja nen Feature Request draus gemacht, dann passt das. sollte ja normalerweise nicht sein

**Comment by 60erjonny** [comment]
Wie hoch hast du, die "Distanz Vorausschauen ( Lenkung )" eingestellt...?
Dumme Idee von mir -->versuche zusätzlich mehrere Punkte in der Route unter der Brücke zu erstellen, dann müssten die ja immer näher sein...!?!

**Comment by 60erjonny** [comment]
Konntest du das Problem lösen...? Würde mich noch interessieren...Danke...
