### ISSUE TITLE
cant disconect implements

### ISSUE THREAD

**Issue by Thebiginn** [Stephan-S/FS22_AutoDrive#182]
Hi first of all what an amazing mod! thank you for doing the great work!

I found a bug where I can't disconnect implements from my tractor, after activating the tractor on a job. it says that i can't disconnect because you are unable to,  during unfolding. but it isn't unfolded or anything. The only thing I can do then, is reset it back to the shop. However, when I'm using that same setup again and activate it, it is stuck once again.

**Comment by Philj030** [comment]
Agree I am having the same issue with combines - it says i cant detach when folding - but the combine is folded  :(

**Comment by Axel32019** [comment]
see #131
