### ISSUE TITLE
Probleme mit Autodrive

### ISSUE THREAD

**Issue by CosmoDJ** [Stephan-S/FS22_AutoDrive#183]
Folgendes Problem. 
Ich habe im Rabatt Shop 2x den gleichen Traktor gekauft. Fastrac 4420.
Habe eine Einzelkorn Hinten Angehängt. Azurit 9 (Geliehen)
Vorne: 
Frontlader Q7M
Big Bag Lifter - Dual
2x Big Bag Saatgut 
Aktuelle Nutzung nur Autodrive / GPS 
Maschinen sind keine Mods (Vanila)

Die Saatgut wird als Zuckerrüben Erkannt. (Saatmaschiene auf Zuckerrüben eingestellt)
Kurze zeit später Kein Tacho Hud, kann nicht Fahren / Lenken.  
Beim Aussteigen mit Tap. ( Anders geht's nicht ) Sehe mein Char im Traktor. 
Beim Zurücksetzen wird Nummernschild gelöscht. Kann aber wieder Fahren. Autodrive Versagt total. keine Reaktion. 

Bitte daher um Hilfe.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7817051/log.txt)
![unknown](https://user-images.githubusercontent.com/97190195/148270922-586248cc-173c-407f-8d7a-a3d4767cb6c3.png)
![unknown1](https://user-images.githubusercontent.com/97190195/148270928-fb2ec76f-080a-4476-9ad3-ef1eb998fa06.png)
![unknown2](https://user-images.githubusercontent.com/97190195/148271064-26f8e602-fda3-48b6-a98d-9aa50a7a41e4.png)

**Comment by Axel32019** [comment]
Gleiche Ursache wie hier #114

**Comment by CosmoDJ** [comment]
@Axel32019  vielen lieben dank für die sehr schnelle hilfe. ich wünsche dir alles gute.
