### ISSUE TITLE
Fruchtumfahrung, wieso fährt der Abfahrer mitten durch?

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#184]
der hätte eigentlich aussenrum 2 Vorgewende schon platz

![image](https://user-images.githubusercontent.com/8066324/148294359-214d43c1-3b03-444c-8087-0d44cac42f7e.png)

**Comment by Iwan1803** [comment]
Poste mal einen Screenshot von den Abfahrer-Einstellungen.

**Comment by RealNeo80** [comment]
![image](https://user-images.githubusercontent.com/8066324/148586282-be82e666-f408-42d9-8d70-282c1bc4c6b0.png)

**Comment by Axel32019** [comment]
@RealNeo80 Wie ist die Einstellung Pfadfindungs-Faktor ? Welche Map, Feld?

**Comment by RealNeo80** [comment]
Faktor 0,5, Elmcreek Feld 31. Ich hab das aber schon bei anderen Feldern auch beobachtet. 

Interessant ist, dass er auch wenn er vor dem Drescher ist (gleiche FR wie der Drescher) dass er dann rechts rum durch die Frucht wendet um abzutanken obwohl links rum Vorgewende ohne Frucht frei wäre. Scheint als ob er lieber rechts rum wendet, egal ob Frucht dabei zerstört wird

**Comment by RealNeo80** [comment]
![image](https://user-images.githubusercontent.com/8066324/148680474-01a3d53e-1ab9-4270-8f84-c547e62dc6e8.png)

Grade beim Ventor Feld 25 Elmcreek

**Comment by Axel32019** [comment]
Stell bitte mal den Pfadfindungs-Faktor auf 1 oder 1.5, dann mal schauen ob das reicht.

**Comment by Axel32019** [comment]
@RealNeo80 Hat das was gebracht?

**Comment by RealNeo80** [comment]
nein hatte nix gebracht, ich wills aber grad mit dem 2.0.0.4.RC nochmal testen, ja der Wartepunkt war beim ersten mal auf dem Grünstreifen, beim 2. mal war er aber im Feld. Ich meinte gesehen zu haben, dass der Abfahrer es 1x probiert hatte, der Ernter dann weitergefahren ist (kann feldende gewesen sein, nciht sicher), als er wieder angesetzt hat war ihm die Frucht egal und er is einfach quer durch.

wie gesagt ich wills mir aber nochmal genauer anschauen

**Comment by Axel32019** [comment]
@RealNeo80 Habs glaub gefunden, liegt am neuen LS22 Gras. Brauchste nicht weiter suchen.

**Comment by RealNeo80** [comment]
super, dann schaun wir mal obs dran liegt
