### ISSUE TITLE
Abfahrer fährt Drescher nicht an

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#185]
Der Weg wird berechnet, er fährt aber einfach nicht los, im HDU vom Abfahrer kommt fallback:false

![image](https://user-images.githubusercontent.com/8066324/148299606-8cc3f41a-9b7b-4938-813e-a8105c88bd58.png)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7818186/log.txt)

**Comment by Axel32019** [comment]
Die Anzeige fallback ist bei aktivem Debug-Kanal normal. Im log sehe ich momentan keinen Fehler.
Bitte die Tasten-Kombi AD: Entwickler Aktion zuweisen und in dieser Situation betätigen bis im log keine Meldungen mehr ausgegeben werden, dann bitte log hier posten.

**Comment by RealNeo80** [comment]
er schein auch hier nen überlauf zu produzieren
![image](https://user-images.githubusercontent.com/8066324/148361370-0275e0e0-fd13-4811-a9de-81e42f3e936f.png)
Entwickleraktion ging nicht mehr, da isser mir abgeschmiert
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7820840/log.txt)
hier is das log mit entwickler,

**Comment by Axel32019** [comment]
Die log enthält nur die Entwickler-Aktion vom Ernter, die hilft nicht da hier nicht die Pfadfindung des Abfahrers enthalten ist:
Wenn benötigen wir die vom Abfahrer.
