### ISSUE TITLE
Drescher abtanken

### ISSUE THREAD

**Issue by masuti** [Stephan-S/FS22_AutoDrive#186]
Hallo Ihr fleißiger AD Erbauer,
wenn der Drescher zum abtanken eine Tasche fährt läßt der Abfahre nach dem abtanken keinen Platz damit der Drescher seine Arbeit wieder aufnehme kann. Es kommt dann immer zu Verkeilungen.
Euch ein schönes und gesundes neues Jahr.
Manfred Zoppa

**Comment by Axel32019** [comment]
Hallo @masuti , Das liegt an der noch nicht vollständigen Kooperation mit CP - Hier ist Geduld gefragt da in beiden mods Anpassungen notwendig sind.

**Comment by XPiRiJenZ** [comment]
#142 beschreibt wohl dasselbe Problem...
