### ISSUE TITLE
"Fahrzeug fährt tanken", bleibt aber am AiO Silo stehen

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS22_AutoDrive#188]
Hallo,

ich habe das Problem, dass, sobald die Meldung zum Tanken fahren erscheint, entsprechendes Fahrzeug unser AiO Silo auf dem Hof anfährt, (Dort gibt es aber keinen Sprit), anstatt zur Tanke zu fahren. 
Dort stoppt und startet AD immer wieder, so dass die Tanken Meldung fast dauerhaft erscheint, und alle Fahrzeuge in der Kartenübersicht im Rhythmus der Meldung blinken.

Viele Grüße

**Comment by Iwan1803** [comment]
Das ist das Problem mit diesen Multisilos, aus welchem ich Diesel zumindest rausnehmen würde.

@Axel32019 
kann man die Tankroutine so erweitern, das er in diesem Fall einen anderen Tankpunkt sucht?

**Comment by Axel32019** [comment]
Hallo @Kitekater , Würdest Du bitte mitteilen welches "AiO Silo" das ist?
@Iwan1803 Für die Suche ist entscheidend ob das "Füllgut" vorhanden ist, d.h. Füllstand >0. Kann sein das hier das Silo und/oder die Definition der Filltypes in der Map das verursachen -> dann wird es allerdings kompliziert das richtige zu finden.
Daher ist jetzt erstmal wichtig was das für ein Silo ist...

**Comment by Kitekater** [comment]
@Axel32019 
Das ist die "Multifruit Buying Station" von 82Studuo. Version 1.0.1

Ich habe jetzt mal alle Fahrzeugflüssigkeiten/Gase/Strom rausgenommen, denn anscheinend wurden dort alle Filltypes, die es gibt, mit eingefügt. Schnee und Wolle bekomme ich da auch. 😉 

Werde es nochmal testen und dann berichten

**Comment by 60erjonny** [comment]
Habe das mit diesem Mod: MTLModdingTeam_UniversalKaufsilo, auch schon beobachten können...

**Comment by Axel32019** [comment]
@Kitekater , @60erjonny An beiden Silos ist nicht einmal ein manuelles Diesel tanken möglich.
Daher ist es auch für AD nicht möglich da zu tanken.
Es lassen sich nur Anhänger beladen.
Wenn ihr diese mods verwenden wollt, entfernt, wenn vorhanden, diese Filltypes: DIESEL DEF ELECTRICCHARGE METHANE 
Aus den mods sehe ich keine Möglichkeit dies in AD zu lösen. @Iwan1803
