### ISSUE TITLE
LS22 stürzt mit AD ab

### ISSUE THREAD

**Issue by taylorfx** [Stephan-S/FS22_AutoDrive#189]
Hallo,
ich bin noch AD-Anfänger, Strecken einfahren funktioniert, aber nach den ersten 2 oder 3 Stunden üben, stürzt mein LS22 ab, was sich wie folgt äußert. Der Traktor den ich selbst fahre, bleibt nach hin und her switchen mit anderen Fahrzeugen plötzlich stumm und ich kann Ihn nicht mehr bewegen, ich kann noch rausspringen und andere Fahrzeuge fahren, aber diesen Traktor nicht mehr, wenn ich Ihn zurücksetze funktioniert er wieder eine Weile, dann passiert es wieder, ich habe ganz wenige andere Mods drin VCA, ein Stroh-Mod und eben AD. Die Log enthält mehre Meldungen mit AD und lua-Problemen. zb: S22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:345: attempt to call method 'getAttachedImplements' (a nil value)

**Comment by Iwan1803** [comment]
Lass mich raten: Bigbags?

**Comment by Iwan1803** [comment]
Im DC geklärt, es liegt an den Bigbags -> #114
