### ISSUE TITLE
Zielpunkte doppelt nutzen/kopieren

### ISSUE THREAD

**Issue by ChrisBS91** [Stephan-S/FS22_AutoDrive#190]
Hi 
Vielleicht wäre es eine Idee für Leute die mit den AD Ordnern arbeiten. 

Wäre es möglich die Zielpunkte doppelt zu nutzen? ...Also ich habe zum Beispiel verschiedene Höfe und dementsprechend verschiedene Ordner. Jetzt habe ich zum Beispiel einen Parkplatz Grubber erstellt. Möchte dort einen Tracktor hinschicken. Jetzt muss ich alle Ordner öffnen um zu gucken wo der P Grubber drin ist. 
Wäre cool, wenn ich mir einen Ordner Parkplätze erstellen könnte und die Parkplätze Zielpunkte sowohl im dazugehörigen "Hofordner" als auch im Parkplatzordner verwenden könnte

**Comment by Iwan1803** [comment]
Schon mal dran gedacht, die Suche (per Lupe) in der offenen Zielpunkt-Liste zu benutzen? 😉
