### ISSUE TITLE
Error: Running LUA method 'draw

### ISSUE THREAD

**Issue by Momo13092022** [Stephan-S/FS22_AutoDrive#191]
Hallo, wir bekommen neuerdings folgende Error Meldung und dann hängt sich AD auf.
Error: Running LUA method 'draw'.
C:/Users/mauri/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Hud/PullDownList.lua:601: attempt to index a nil value

**Comment by Iwan1803** [comment]
Wann genau an welcher Stelle? SP, MP oder Server? Welche Map? Ein paar mehr Infos + Logs + AD-Config wären schon schön....

**Comment by BeastyBass** [comment]
Ich hatte auch eine Fehlermeldung von Autodrive (Error: Running LUA method 'update'). Wenn ich im Multiplayer auf Elmscreek nach dem Neueinstieg mich bewegt hatte, war die Taste dauerhaft an. Auch im Menü ging dann nix mehr bis ich nur noch ALT-F4 drücken könnte.
Dies stand in der Log drin:
FarmingSimulator2022/mods/FS22_AutoDrive/scripts/TelemetryExport.lua:34: attempt to perform arithmetic on field 'timeSinceLastTelemetryOutput' (a nil value)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7833203/log.txt)

**Comment by Axel32019** [comment]
Hallo @Momo13092022 , Bitte log von client und wenn MP vom Server anhängen.

**Comment by Axel32019** [comment]
@BeastyBass Bitte experimentelles Feature telemetryOutput deaktiveren. Hat derzeit keine Funktion.

**Comment by BeastyBass** [comment]
> @BeastyBass Bitte experimentelles Feature telemetryOutput deaktiveren. Hat derzeit keine Funktion.

Wusste gar nicht das ich das angemacht hatte. Danke schön!!!

**Comment by Momo13092022** [comment]
> Hallo @Momo13092022 , Bitte log von client und wenn MP vom Server anhängen.

Gerne, hier sind beide ....
[logClient.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7833295/logClient.txt)
[logServer.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7833296/logServer.txt)

**Comment by Axel32019** [comment]
@Momo13092022 Hast Du auch noch die folgenden Dateien?
vehicles.xml items.xml

**Comment by Momo13092022** [comment]
> @Momo13092022 Hast Du auch noch die folgenden Dateien? vehicles.xml items.xml

Klar..
[vehicles.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7833815/vehicles.txt)
[items.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7833816/items.txt)

**Comment by Axel32019** [comment]
Verwendest Du eine Tastenkombi zur Auswahl des  Ladegutes?

**Comment by Axel32019** [comment]
Tip: Wenn Ballen, Paletten im Shop auftauchen diese in der items.xml löschen:
<item ... position="-0.00079348991857842 -99.570175170898 0.00044890071148984"
