### ISSUE TITLE
AD erkennt den turn vom Häcksler nicht

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS22_AutoDrive#192]
Hallo,

Habe eine Fehler entdeckt, scheint eine Komibination von AD + CP zu sein, habe dazu auch schon im CP-Forum eine Antwort bekommen. (es gibt noch keine Schnittstelle).

Das CP Team fixt das Pickup-heben, könntet ich darüber nicht den turn erkennen? (Pickup geht nach oben = Häcksler wendet + Abfahrer setzt ein paar Meter zurück)
Bin aber verwundert da es beim Mais häckseln doch ganz gut funktoniert.

Auch beim Drescher abtanken streift das Schneidwerk von Drescher den Abfahrer weil dieser am Ende des Abtankvorgangs in einer "Tasche" nicht ein paar Meter zurücksetzt.

Weiters ist mir aufgefallen, dass dem Abfahrer beim zurückschieben den Anhänger nicht schieben kann. Passiert auch beim Drescher so:

https://youtu.be/AbxWo694feo 

an die log hab ich auch bei AD leider nicht gedacht...

könnte es aber in ein paar Tagen nachstellen...

Danke für eure großartige Arbeit ;-)

LG
Eric

**Comment by 60erjonny** [comment]
mein Hächsler überspringt immer eine Reihe bei CP-Kurs-->
AD-Kollisionserkennung an-->
blaue Fanglinie um das Fend gezogen--->
Abfahrer dann, bei Feldausfahrt auf Nächstgelegenen stellen--->
Kollisionshöhe über Grund habe ich auf 2m --->
100 % gibt es nicht, aber bei mir geht es so einiger massen...

**Comment by Axel32019** [comment]
Hallo @eric4072 , Das liegt an der noch nicht vollständigen Kooperation mit CP - Hier ist Geduld gefragt da in beiden mods Anpassungen notwendig sind.

**Comment by eric4072** [comment]
bitte video ansehen... habe die selben Einstellungen bis auf die blauen Linie, welche ja bei geschickt angelegtem Kurs und der Funktion "hinterm Start" nicht benötigt wird.

rechtsturns wenn der Abfahrer links fährt, sind kein Problem... links wie im Video

**Comment by eric4072** [comment]
@Axel32019  ok, alles klar 👍
