### ISSUE TITLE
Fehler bzw. Einfrieren beim BigBag auf der gabel

### ISSUE THREAD

**Issue by ProdaxCH** [Stephan-S/FS22_AutoDrive#193]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7829956/log.txt)
Hallo Liebes AD Team
Letztens ist mir aufgefallen das sobald der AD Mod im Ordner ist und man einen BigBag auf dem Frontlader hat, dabei aus dem Fahrzeug steigt entsteht Lua Fehler siehe LOG, danach kann man oft nicht mehr zurück ins Fahrzeug steigen bis der BigBag Lifter Verkauft wurde. Erst meinte ich es liegt an einem Mod, nun habe ich neues Save Game mit nur AD genommen und keine Kurse sind eingefahren. Simuliert wurde es im SP. bei weiteren Infos kann auch per DC beim Iwan Kontaktiert werden. 
Besten Dank und Schönes Wochenende
ProdaxCH

**Comment by Axel32019** [comment]
Hallo @ProdaxCH , Den kennen wir schon - Fix im nächsten Release -> #114
