### ISSUE TITLE
drive-through silo  / Durchfahrsilo problem

### ISSUE THREAD

**Issue by nimanox** [Stephan-S/FS22_AutoDrive#194]
habe das problem das  der Abfahrer beim Anfang stehen bleibt abkippt und dann erst losfährt . dadurch ensteht am anfang von silo ein hügel  wodurch der nächste abfahrer sich auf der bahn fest fährt mit dem anhänger .

das nächste was ich sehe ist das er nicht gleichmässig durch das Silo fährt am Anfang fährt er 16 km/h und zum ende hin nur noch 8km/h wodurch die schwad größer wird und nicht bis 
zum ende des Silos abkippt

habe es auch mit verschiedenen Anhänger und Traktoren kombis getestet  das Ergebnis bleibt gleich

![Download](https://user-images.githubusercontent.com/61834018/148584244-f93db8a4-9190-4077-b77e-d1d945eaa456.jpeg)

**Comment by Iwan1803** [comment]
Ich habe das gerade mit dem letzten RC getestet und kann es bestätigen:
- der Abfahrer fährt ins Silo rein und bleibt stehen, sobald das gesamte Gespann drin ist
- er öffnet dann die Klappe und sobald er anfängt abzuladen, fährt er erst wieder los
Die Geschwindigkeitsreduzierung gegen Ende scheint normal zu sein und fällt höher aus, wenn der Zielpunkt zu nah am Ende des Durchfahrsilos ist.

**Comment by SaschaLie** [comment]
Hallo. Bei mir klappt zwar die Durchfahrt (Durchgehend 8km/h) und das Abladen (Fendt1050&Aperion3401) ordentlich, aber ich muss die Kollisionserkennung (Höhe 2,0m) aus machen. Sobald die erste Schwad liegt, fährt der Traktor nicht mehr durchs Silo. Könnte man die "Fruchtgüter" nicht irgendwie "Unsichtbar machen" für die Kollisionsabfrage?
![Silo](https://user-images.githubusercontent.com/96572157/148918694-3c316273-0687-4fa0-b8d6-bcc1d311780a.jpg)

**Comment by nimanox** [comment]
problem besteht leider auch mit der version 2.0.0.4 bei mir das er am anfang stehn bleibt und anfängt abzukippen und dan erst weiter fährt. im singleplayer sowie im multiplayer mit mehreren kombination getestet

**Comment by Axel32019** [comment]
wenn jemand zeit hat

**Comment by Axel32019** [comment]
@nimanox Nach ca. 20 Std. ist eine Verbesserung möglich, jedoch blockieren diverse Animationen, Effekte, Sounds das Abladen und lassen sich derzeit nicht umgehen.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5

**Comment by nimanox** [comment]
vielen dank für das update  und es funktioniert jetzt viel besser als vorher  gute arbeit  

ist das auch für das ende der abkippens möglich das er am ende nicht stehn bleibt nach ein paar tests stell ich fest das er am ende langsamer wird obwohl die zielpunkte anderthalb fahrzeuglängen hinter dem silo sind
