### ISSUE TITLE
Kollissionsbox Ventor buggy?

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#196]
wieso hängt die beim Einlenken so weit rechts?

![image](https://user-images.githubusercontent.com/8066324/148654115-6cfdff05-355e-4926-a057-9b48a34f9a1b.png)

**Comment by Axel32019** [comment]
Weil die "der Lenkung folgt" und vor das Fahrzeug gehängt wird.
