### ISSUE TITLE
[enhancement] 2. Abholpunkt einfügen

### ISSUE THREAD

**Issue by Gillios** [Stephan-S/FS22_AutoDrive#197]
Meine Idee wäre das man im Modus Abholen und Abliefern eine weitere Möglichkeit bekommt um zu laden.

Denn mir gerade zb aufgefallen, ich schicke meinen LKW mit Gülle bei den Kühen laden, schicke ihn dann los zur BGA dann nochmal das gleiche spiel mit den Schweinen. Somit wäre meine Idee im sagen zu können, Du lädst bei den Kühen, danach bei den Schweinen und fährst dann bei der BGA abladen und das alles in einem Abwasch, ohne mehrere Touren machen zu müssen.

Vielleicht macht dies ja auch für noch ein Paar mehr Leute sinn. 

LG Danke für eure Arbeit.

**Comment by Stephan-S** [comment]
Du meinst so was wie "Rotierend Beladen"?
Schau mal in den AD Einstellungen des Fahrzeugs nach ;-)

**Comment by Gillios** [comment]
Aber dafür müssten ich diese beiden Punkte in einen einzelnen Ordner packen, Sonst fährt er ja auch alle anderen Punkte an die ich dort mit drin habe oder nicht?
![20220108204317_1](https://user-images.githubusercontent.com/88940738/148657638-5b6f5a3b-2109-42e5-8fac-cf70f4efd108.jpg)
 
fährt in diesem fall jetzt nicht jeden Punkt in diesem Ordner an und versucht sich da zu beladen?

**Comment by Stephan-S** [comment]
Genau. Aber Ordner sind ja auch schnell erstellt/gelöscht und Punkte verschoben. Ich denke die Option ist mir lieber als das HUD dafür extra um mehrere Abladepunkte zu vergrößern

**Comment by Gillios** [comment]
Okay, Danke für die schnelle Antwort, war ja wie gesagt auch nur eine Idee :D Trz danke für die Arbeit die ihr da rein steckt :)
