### ISSUE TITLE
Abfahrer beim häckseln findet keinen Weg vom Feld

### ISSUE THREAD

**Issue by daserthomas** [Stephan-S/FS22_AutoDrive#199]
Steps to reproduce
Häckseln mit verschiedenen Abfahren.
Der Abfahrer kann keinen Pfad vom Feld runter berechnen berechnen.

Actual behavior
Nachdem der Anhänger voll ist kommt die Meldung "Der Fahrer von 1050 konnte keinen Pfad zum Ziel berechnen" und der Abfahrer bleibt stehen

Expected behavior
Der Abfahrer sollte das Feld verlassen und zum abladen im Keilsilo fahren

Screenshots

Courseplay version
7.0.0.16
Autodrive version
2.0.0.2

Log

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7834702/log.txt)

Map
Standart Elmcreek

Vehicles/ implements involved
kein Mod. Standart 1050 und Fendt Katana

Relevant script mods
AD, CP, und VCA an

**Comment by 60erjonny** [comment]
Hallo
Prüfe die Einstellung von den Abfahreren der Feldausfahrt in AD und den bei dir angelegten Streckennetz entsprechent einstellen...
Teste dabei mal, ob die Abfahrer auch ein anders Ziel ( Trigger ) anfahren könnten...
Kontrolliere die Streckenteile am Keilsilo, ob sich hier Fehler eingeschlichen haben...

**Comment by RealNeo80** [comment]
@daserthomas liegt meistens dran dass Streckenpunkte nicht sauber verbunden sind, Fahr die Strecke mal ab, ansonsten bitte bei AD posten. .. bist du die Strecke abgefahren wie drüben gesagt?

**Comment by daserthomas** [comment]
Das Streckennetz ist sauber verbunden inkl. Strecke ums Feld
Wenn ich den Abfahrer dann manuell auf die Strecke fahre lädt er auch einwandfrei im Silo ab und fährt zurück
Ich habe auch diverse Einstellung im AD ausprobiert leider ohne Erfolg

**Comment by daserthomas** [comment]
Vielen Dank für die schnelle Hilfe 
Tatsächlich war an einer Stelle die Strecke nicht verbunden was ich bei 100 mal kontrollieren nicht gesehen habe,
Also mein Fehler
