### ISSUE TITLE
Thanks Stephan and team.

### ISSUE THREAD

**Issue by huseyinsayar** [Stephan-S/FS22_AutoDrive#2]
I couldn't enjoy / gratify the game without Autodrive... I hope it gives the old taste. I'm so glad you edited it for fs22. I hope to see you in CP soon.
Also, thank you for including my translation.

**Comment by 60erjonny** [comment]
Vielen Dank...!
Ich werde wieder viel testen...!

**Comment by Bandesss** [comment]
Ja auch von mir vielen dank, vor allem das es so schnell ging.
Hammer geil Danke

**Comment by fudoido** [comment]
wasnt expecting it so fast. well done guys. here comes lots of entertaining hours in a new farm :)

**Comment by skjatala** [comment]
I also wasnt expecting it so fast. well done guys. here comes lots of entertaining hours in a new farm. I'm so glad you have done it for fs22.
Thank You Very much .

**Comment by Torfrockjunge33** [comment]
Ich bedanke mich für den tollen Mod, und ein ganz ganz ganz dickes Lob das es so schnell geklappt hat.

**Comment by jeffersondarsy** [comment]
Vielen lieben Dank! Erst jetzt wird der LS22 wieder zum Leben erweckt und das nur Dank euch und eurer Hilfe.

**Comment by Bobster82** [comment]
Thanks guys for the release! Pretty awesome! Going to download it and dive into it :D

**Comment by mikindwa** [comment]
You guys are awesome, thank you so much for making the FS series of games so much for like a real sim.  I couldnt imagine playing without AD
