### ISSUE TITLE
Maus geht nicht mehr

### ISSUE THREAD

**Issue by Wolle1976** [Stephan-S/FS22_AutoDrive#20]
Hallo, ich habe ein Sreckennetz im SP Erstellt und auf das Savegame des DEDI-Server´s hochgeladen. Nach des ersten streckennetz- nacharbeit verschwand der Mauszeiger und öässt sich auch nicht mehr zurückholen.
Kennt jemand das Problem und was kann ich dagegen machen??

**Comment by Wolle1976** [comment]
[server.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7740043/server.txt)

**Comment by Axel32019** [comment]
Hallo @Wolle1976 , Im Server-log kann ich keinen Fehler von AD sehen. Hast Du noch die Client-log?
Könnte das gleiche Problem wie hier sein #4

**Comment by Wolle1976** [comment]
Mit dem neuen Streckennetz ist das Problem verschwunden
Danke
