### ISSUE TITLE
[Feature Request] Kollissionskontrolle beim Parken

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#200]
Ich würde mir wünschen, das die Kollission beim Parken anders ist als im Normalen Fahren, da es ja doch in den Hallen enger ist, und die Normale Kontrolle ständig aneckt. Vielleicht fällt euch ja was ein, wie man das machen kann.

Ggf die Box einfach verkleinern je näher der Parkplatz ist oder sowas ;)

**Comment by Axel32019** [comment]
Was meinst Du? Vorwärts, rückwärts oder beides fahren?
Ein Screenshot der konkreten Situation macht das verständlicher :-)

**Comment by RealNeo80** [comment]
vorwärts und rückwärts fahren, sorry hatte da keinen Screen weil ich das erst hinterher geschrieben habe :P wenns das nächste mal passiert post ich ihn dir

**Comment by Axel32019** [comment]
@RealNeo80 Schon mal mit 2.0.0.5 probiert?

**Comment by RealNeo80** [comment]
mal schaun ob ich am WE dazu komm. Bin arbeitstechnisch grad arg eingespannt so dass ich LS schon lang nicht mehr offen hatte

**Comment by Axel32019** [comment]
@RealNeo80  Bitte mal mit 2006 probieren, siehe Release-Notes

**Comment by RealNeo80** [comment]
2006 läuft grad, scheint besser zu sein, hab aber noch net alle trailer getestetVon meinem/meiner Galaxy gesendet<div>
</div><div>
</div><div>-------- Ursprüngliche Nachricht --------</div><div>Von: Axel32019 ***@***.***> </div><div>Datum: 01.06.22  19:21  (GMT+01:00) </div><div>An: Stephan-S/FS22_AutoDrive ***@***.***> </div><div>Cc: RealNeo80 ***@***.***>, Mention ***@***.***> </div><div>Betreff: Re: [Stephan-S/FS22_AutoDrive] [Feature Request] Kollissionskontrolle beim Parken (Issue #200) </div><div>
</div>

-------- Original Message --------
Subject: Re: [Stephan-S/FS22_AutoDrive] [Feature Request] Kollissionskontrolle beim Parken (Issue #200)
From:    Axel32019 ***@***.***>
To:      RealNeo80 ***@***.***>

@RealNeo80  Bitte mal mit 2006 probieren, siehe Release-Notes
