### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by Elite82pt** [Stephan-S/FS22_AutoDrive#201]
I would really like to see a feature added...secondary roads. Like roads that are only used to go to a specific waypoint in that road...or maybe a type of road that the AI only goes if there's a waypoint in it.

**Comment by 60erjonny** [comment]
Hi
That's where there is already ... to read here ... 
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Release-Notes-for-AutoDrive-english

**Comment by Iwan1803** [comment]
See also: https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-key-combinations
As this allready exists -> closed.
