### ISSUE TITLE
Autorive erkennt die Ai Splines nicht an

### ISSUE THREAD

**Issue by TommyGFX** [Stephan-S/FS22_AutoDrive#205]
Hat man in einer Map nur AI Splines, erstellt Autodrive kein Streckennetz.

Legt man die gleichen Splines auch beim trafficSystem rein, wird ein Streckennetz erstellt.

Ist das so gewollt ?

**Comment by TommyGFX** [comment]
Und gibt es eine Möglichkeit, wenn man im Debug Menü das Streckennetz aktiviert, die dort aufgelisteten Punkte zu speichern mit Koordinaten ? So dann man später im Ge schauen kann wo die Sackgassen sind ?

**Comment by Axel32019** [comment]
> Hat man in einer Map nur AI Splines, erstellt Autodrive kein Streckennetz.
> 
> Legt man die gleichen Splines auch beim trafficSystem rein, wird ein Streckennetz erstellt.
> 
> Ist das so gewollt ?

Ist das eine mod-Map?

**Comment by Axel32019** [comment]
> Und gibt es eine Möglichkeit, wenn man im Debug Menü das Streckennetz aktiviert, die dort aufgelisteten Punkte zu speichern mit Koordinaten ? So dann man später im Ge schauen kann wo die Sackgassen sind ?

Das ist nicht vorgesehen. Du kannst die Punkte über die Map anspringen, dann zeigt die Minimap die Koordinaten.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
