### ISSUE TITLE
[Feature] Maximum speed from cruise control

### ISSUE THREAD

**Issue by JustDen1234** [Stephan-S/FS22_AutoDrive#206]
It would be nice if the vehicles maximum speed will be the speed set for the cruise control. 

I know about the max speed in the AD UI, creating this feature whould make this obsolete...

**Comment by Iwan1803** [comment]
During field work i set the max. speed for cruise control to 20km/h. If AD then should drive to another place, it should also use this 20km/h?
For me it sounds better to use independent settings.

**Comment by Mobius104** [comment]
I agree with Iwan1803, leaving the two settings separate is more useful.

**Comment by JustDen1234** [comment]
Totally agree with you both. Using AD for a long time now, never used the max speed controls of AD. But 2 days ago I thought I wanted to use this. Did not think of the AD opties, in the future I will think twice before adding a feature request :-D
