### ISSUE TITLE
Abfahrer manuell rufen

### ISSUE THREAD

**Issue by Cola7777** [Stephan-S/FS22_AutoDrive#208]
Es wäre toll wenn man im Drescher (sofern ein Abfahrer gemeldet ist) manuell den Abfahrer rufen könnte - in dem Fall werden die eingestellten Rufen % ignoriert.

Wäre ideal bei halbautomatischem Betrieb (wenn man selbst den Drescher fährt und lieber sofort abtanken möchte da danach evtl. eine kritische Stelle kommt) und vor allem am Ende der Feldarbeit wenn der Drescher noch Körner im Tank hat aber durch die % Einstellungen nicht ruft.

Danke

**Comment by Iwan1803** [comment]
Du kannst den Abfahrer rufen, indem du eine Tastenkombi dafür in LS22 in den Tastenbelegungen einträgst.
Ansonsten kannst du auch das aktive Abfahren im Drescher aktivieren und dann kommt der Abfahrer, wenn du das Rohr ausfährst.

**Comment by Cola7777** [comment]
Super, danke dir.

**Comment by Iwan1803** [comment]
Gerne 😉
