### ISSUE TITLE
Fehlermeldung: abhängen während das gerät auf-zuklappt ist nicht erlaubt

### ISSUE THREAD

**Issue by hipf81** [Stephan-S/FS22_AutoDrive#209]
Dieses Problem entstand durch die Option in den Konfig "fold implements = true", dadurch werden in der vehicles.xml folgende Werte für alle Anbaugeräte oder Anhänger von Fahrzeugen gesetzt, die mit AD bewegt werden (siehe Bild). Der Wert von 0.000100 reicht, damit man nicht mehr abkoppeln kann.

Ich habe alle Foren vorher durchsucht und auch bei Giants einen Issue aufgemacht, bin heute Nacht selber drauf gekommen. Nachdem der Wert auf "false" in der Konfig geändert wurde, bestand der Fehler nicht mehr. Das trifft alle Anbauten, die nicht "foldable" sind, zB Gewichte, Transportwagen für Mähwerke, Anhänger, etc
![Vergleich vehicles xml nach Fehler](https://user-images.githubusercontent.com/73005104/148703074-571b8826-1397-46d2-a199-c7a3ed816800.jpg)
.

**Comment by Iwan1803** [comment]
Hast du schon auf 2.0.0.3 aktualisiert und besteht da das Problem noch?

**Comment by hipf81** [comment]
Hi
War gestern nicht verfügbar. Ich werde es bei Gelegenheit nochmal testen.
LG Wolfgang

Iwan1803 ***@***.***> schrieb am Mo., 10. Jän. 2022, 00:26:

**Comment by Halfiga** [comment]
Hi,

Also ich habe genau dieselben Meldungen in der Vorgängerversion als auch in der 2.0.0.3

LG
Halfiga

**Comment by hipf81** [comment]
Hi
Die Option "fold implement" deaktivieren hat bei mir geholfen.
LG Wolfgang


Halfiga ***@***.***> schrieb am Mo., 10. Jän. 2022, 14:58:

**Comment by Halfiga** [comment]
Das hat das Problem erstmal nicht behoben... Ich habe das im Savegame geändert ich hoffe das ich da richtig war...
Werde morgen mal ausprobieren alle Geräte und Hänger zu verkaufen und neu kaufen und dann schauen ob dann das Problem gelöst ist um die alten Gerätschaften zu löschen und neu schreiben zu lassen

**Comment by Halfiga** [comment]
Hi,

mit V 2.0.0.3 und nachdem ich alle Geräte mit denen ich den Fehler hatte ausgetauscht habe und nach nun mehreren Stunden testen scheint das Problem behoben zu sein.

LG
Halfiga
