### ISSUE TITLE
Warning for messageBackground.dds

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS22_AutoDrive#210]
Folgende Warnung erscheint im Log:
`2022-01-09 19:41 Warning (performance): Width or height doesn't equal 2^n of mip-mapped texture D:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/textures/messageBackground.dds.`

**Comment by Dzi4d3k** [comment]
It's caused by the fact that messageBackground.dds has 512 on 60 pixel, where height should be 64 (2^6).
To not to interfere with @daensky copyrights I suggest 2 pixel at top and the same on bottom, and will be good without notice.

**Comment by daensky** [comment]
Sorry for that, I could have sworn that I did not change the resolution of that.
@Dzi4d3k Yes, this seems indeed to fix the problem.

Here is the attached file:
[messageBackground.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7838728/messageBackground.zip)

Please let me know if you've noticed any other problems with the icons/textures.

**Comment by Dzi4d3k** [comment]
Only this one hasn't dimensions adhering 2^n principle.
However I wonder if it would be possible to reduce dimensions of gui_debug_Icons_BC7.dds, as lot of file is unused, but it will probably need icons positions re-mappging
