### ISSUE TITLE
Abfahrer fährt neben Häcksler nicht richtig

### ISSUE THREAD

**Issue by Naiszen** [Stephan-S/FS22_AutoDrive#213]
Seit dem neuen Update 2.0.0.3 fährt der Abfahrer viel zu dicht am Hächsler, und auch viel zu weit vorne und somit bleibt CP stehen. siehe Foto.
![2022-01-10 (8) kopie](https://user-images.githubusercontent.com/96670511/148709769-8d8c0a5b-810d-4b2a-abb8-a575ec3899db.jpg)

um Überhaupt etwas zu nutzen, hab ich den Wert: "Abstand Rohr" auf 4.0m gestellt, aber er fährt immer noch viel zu weit vorne, als ob er einem Drescher folgen würde....   dies führt wieder zu dem nächsten problem in den Kurven, wo dann der Abfahrer im Weg steht... Siehe Foto
![2022-01-10 (8) kopie](https://user-images.githubusercontent.com/96670511/148710077-6201957d-956f-4647-a4cf-6c217dd663a3.jpg)

bei der Version 2.0.0.2 war das deutlich angenehmer ;)

**Comment by Naiszen** [comment]
und jetzt hatte ich noch mehrmals das er beim Reihenwechsel, wenn er rechts neben den Häcksler fährt, das der Häcksler dann in den Fahrer fährt und dann alles stehen bleibt.. vorm Update lief dieses viel besser
![2022-01-10 (9)](https://user-images.githubusercontent.com/96670511/148710532-c25d0b04-6317-4237-bfbb-8f1bc12a20c5.jpg)

**Comment by Iwan1803** [comment]
Ist das mit dem falschen Abstand nur am Feldrand oder überall auf dem Feld?
Das konnte ich so nämlich bisher beim Häckseln nicht beobachten (Vanilla-Fahrzeuge, keine Mods).

**Comment by SaschaLie** [comment]
Ich habe schwer Probleme im Vorgewende "scharf". Der Häcksler (auch Drescher) fährt immer am Ende so eine Tasche und setzt dann zurück bis zum Feldrand. Bis dahin klappt das mit dem Abfahrer, der schön hinterher fährt. Sobald der Häcksler in die Tasche fährt, setzt sich der Abfahrer daneben. Das ist zwar eher ein Courseplay Problem, aber vielleicht wäre da im AD auch was machbar.

I have severe problems in the "sharp" headland. The forage harvester always drives such a bag at the end and then moves back to the edge of the field. Until then, it will work with the downhill rider, who follows nicely. As soon as the chopper goes into the pocket, the driver sits next to it. This is more of a course play problem, but maybe something could be done in AD.
![H1](https://user-images.githubusercontent.com/96572157/149067370-a75ad419-4cb8-496b-85d3-ecfa2ad7e335.jpg)
Hier setzt der Häcksler zurück
![H2](https://user-images.githubusercontent.com/96572157/149067371-ae1cca0d-d2cd-4a49-afbd-42bc5698afce.jpg)
Hier habe ich den Abfahrer ausgeschaltet und von Hand zurückgefahren
![H3](https://user-images.githubusercontent.com/96572157/149067373-8bf76ba9-017e-40a5-b4d2-883b7e2bc27d.jpg)

**Comment by Osram1981** [comment]
Das gleiche Problem hab ich auch aber was noch fehlt ist wen der Häcksler sein Wendemanöver im Vorgewende abgeschlossen hatt bleibt oftmals der abfahren stehen und Rechnet ewig und findet kein Weg zum Häcksler ne er ruft dan auch oft den 2den abfahren.

**Comment by rohne83** [comment]
Das mit der Wende in scharfen Vorgewendeecken dürfte daran liegen, dass es derzeit noch keine richtige Schnittstelle zwischen AD und CP gibt. AD weiß daher ja nicht ob der Häcksler sich gerade diese Tasche zum Wenden drischt und vollzieht daher wie sonst auch einfach stumpf sämtliche Bewegungen des Häckslers nach. Was in dem Fall halt kontraproduktiv ist.
Da bleibt nur Abwarten bis die Kommunikation zwischne den beiden Mods ausgebaut wurde.

**Comment by SaschaLie** [comment]
Ja, das dachte ich mir. Es wird sich langsam alles einspielen, denke ich. Ist schon Klasse, was bisher alles schon Möglich ist
