### ISSUE TITLE
unsharp Autodrive Onscreen Menu / Unscharfes Autodrive Menü

### ISSUE THREAD

**Issue by alexanderweide** [Stephan-S/FS22_AutoDrive#214]
Hey 

i have uploaded  this report since Update 2.003 the menü is unscharp. 

![Bildschirmfoto vom 2022-01-10 09-39-32](https://user-images.githubusercontent.com/7734241/148738032-22cbea66-9626-458f-b736-b25ffe1b6bec.png)

**Comment by alexanderweide** [comment]
It seems that the error appear on default scaling mode. Its to small for default. Default in my case should be 80% ....

**Comment by Axel32019** [comment]
Bitte mal die log.txt anfügen.

**Comment by Axel32019** [comment]
Kein Update -> closed
