### ISSUE TITLE
LS22 stürzt ab unter Verwendung von AD

### ISSUE THREAD

**Issue by DarthYoda92** [Stephan-S/FS22_AutoDrive#216]
Sobald ich einen Kurs abfahren lasse oder einen neu eingefahrenen abfahren lasse stürzt LS nach gewisser Zeit ab.
Gespielt wird auf der Map Haut-Beyleron. Selbst ohne andere Mods tritt der Faheler weiterhin auf.
LOG wird angehangen.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7838890/log.txt)

**Comment by Sacred-Shadow** [comment]
Also ich hab jetzt mehrere Stundne mit der aktuellen AD Version probiert ... da crasht nix.

**Comment by RealNeo80** [comment]
ich auch, und die log is auch net aussagekräftig, da scheint eher CP gestartet zu werden

**Comment by DarthYoda92** [comment]
Also könnte der Fehler an CP liegen?
Dann nehme ich CP mal raus und teste erneut.
Ohne CP kam der Fehler aber auch auf meinem alten Spielstand.

**Comment by RealNeo80** [comment]
mach mal die debugs von AD mit an. so sieht man gar nixbei mir läuft AD 2.0.0.3 und CP 7.0.0.17 reibungslosVon meinem/meiner Galaxy gesendet<div>
</div><div>
</div><div>-------- Ursprüngliche Nachricht --------</div><div>Von: DarthYoda92 ***@***.***> </div><div>Datum: 10.01.22  23:35  (GMT+01:00) </div><div>An: Stephan-S/FS22_AutoDrive ***@***.***> </div><div>Cc: RealNeo80 ***@***.***>, Comment ***@***.***> </div><div>Betreff: Re: [Stephan-S/FS22_AutoDrive] LS22 stürzt ab unter Verwendung von AD (Issue #216) </div><div>
</div>

-------- Original Message --------
Subject: Re: [Stephan-S/FS22_AutoDrive] LS22 stürzt ab unter Verwendung von AD (Issue #216)
From:    DarthYoda92 ***@***.***>
To:      RealNeo80 ***@***.***>

Also könnte der Fehler an CP liegen?

Dann nehme ich CP mal raus und teste erneut.

Ohne CP kam der Fehler aber auch auf meinem alten Spielstand.

**Comment by DarthYoda92** [comment]
Wie genau schalte ich die Debugs an?

**Comment by DarthYoda92** [comment]
Ohne CP gibt es keine Abstürze mehr.
Dann hat sich das hier wohl erledigt.
Danke
