### ISSUE TITLE
[Feature Request] Parken mehrerer Komponenten

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS22_AutoDrive#217]
Hallo zusammen,

erstmal danke für die tolle Arbeit, die ihr macht. Macht echt jedes Mal mehr Spass AD zu benutzen.

Ich habe da eine Sache, die mir manchmal schon beim Spielen aufgefallen ist, dass es "cool" wäre, wenn verfügbar.
Und nach dem letzten Release-Video wo der Kommentar "Event-Schnittstelle für andere Mods nach dem Parken", dachte ich mir, jetzt schreib ich es.

Es ist ja möglich Parkplätze je Gerät zu vergeben, also aktiver Hänger, auf P, wird der Hänger geparkt.
Wie wäre die Erweiterung, dass ich, in welcher Form auch immer, auswählen kann, dass er nachdem er den Hänger geparkt hat, die Zugmaschine auch auf die programmierte Parkposition bringt.
Das wäre eine große Erleichterung beim Geräte aufräumen, bzw. kurz vor Feierabend.

Viele Grüße

Marc

**Comment by RealNeo80** [comment]
Doublette von #162 mehr oder weniger ;)

**Comment by Axel32019** [comment]
Betrachten wir mal, wie genannt, als Doublette - daher hier closed.
