### ISSUE TITLE
Feature Request - Überbrückungssschalter Autodrive Check Gerät an/aus. 

### ISSUE THREAD

**Issue by alexanderweide** [Stephan-S/FS22_AutoDrive#219]
Hey Developers,

Wäre es möglich das man einen Optionsbutton einfügt der eine Funktion ausschaltet? 

In FS19 war ich es gewöhnt Autodrive zu nutzen um die Feldränder zum beispiel beim Spritzen automatisch mit einem aufgezeichneten Kurs zu fahren. In FS 22 Autodrive funktioniert dies leider nicht mehr, da Autodrive jedes Anbaugerät zuklappt bevor es los fährt. Alternativ kann man es zurück klappen und anschalten, nur leider fährt Autodrive dann nicht los. 
Ich finde die Idee mit den Nebenstrecken extrem genial und zweckdienlich für solch ein Vorhaben. Einzig und allein fehlt die Möglichkeit mit einem Überbrückungsschalter das Einfahren oder Kontrollieren des Arbeitszustands auszuschalten. 

Ich hoffe das ich mich richtig ausgedrückt habe?:-)

So kurz gesagt: Ich wünsche mir eine Funktion / button, der Ausschaltet das autodrive nicht started solange das angehängte Gerät aktiviert oder ausgeklappt ist...

MFG

Alex

**Comment by rohne83** [comment]
Sprich, du willst AD nutzen um Vorgewende zu bearbeiten? Da ist CP und sogar AIVE aber deutlich besser für geeignet, AD ist dafür überhaupt nicht vorgesehen...

**Comment by alexanderweide** [comment]
> Sprich, du willst AD nutzen um Vorgewende zu bearbeiten? Da ist CP und sogar AIVE aber deutlich besser für geeignet, AD ist dafür überhaupt nicht vorgesehen...

Im Prinzip Ja, und ja das weiß ich. Courseplay ist A leider noch nicht fertig für Multiplayer und wird es auch in absehbarer Zeit wahrscheinlich nicht und auf der anderen Seite nutze ich in Courseplay trotzdem nur die Outline. Beim Fahren mit der Spritze ist es goldwert eine Outline zu haben wenn man nur aus dem Cockpit heraus fährt. Den rest kann man ja sowieso ohne Probleme mit VCA und dem Spurassistent/Auto Vorgewende machen. Warum soll ich Courseplay haben mit all den nutzlosen Fähigkeiten wenn ich nur Hilfe beim Outline fahren brauch. ;-)

**Comment by Iwan1803** [comment]
Du kannst in den AD-Einstellungen unter Experimental Features deaktivieren, das beim Start Anbaugeräte zugeklappt werden (folding attachments).
Dennoch ist es nicht vorgesehen (und auch nicht geplant), das AD Feldarbeit erledigt, da es hierfür andere Spezialisten gibt, auch wenn die noch etwas Zeit brauchen, bis alles funktioniert (siehe CP).

**Comment by alexanderweide** [comment]
ahhh dankeschön für den hinweis... über die experimental features..
