### ISSUE TITLE
Bug: All Courses get lost sometimes

### ISSUE THREAD

**Issue by StefanBraun2001** [Stephan-S/FS22_AutoDrive#22]
Hello!

I spent 2-3 hours creating and optimizing the courses of Elmcreek Map. Suddenly, the tachometer was gone and the course points were not visible too, even it the warning trianagle was in red. When i restarted the game next time, all courses and waypoints were gone. This issue has hapened more than one time and i shut off auto-save. Even when using a backup, it didn't work. For my other savegame i still have the courses and waypoints (only the automatic created ones, there are also 2 Auto Drive Text files which are not existent in the other savegame but they were existent before the incident)
I will post a log file if the error occurs again.

Edit: It happened again. So i post the logfile here.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7740581/log.txt)

**Comment by Stephan-S** [comment]
Thanks for the report and the log. The issue is found and fixed and a bugfix release will be out soon

**Comment by prometheus247** [comment]
Same here. 
Was running to plot and course. 
The bug happened when I tried to connect 2 panels.

My log is full of:

`2021-12-20 21:43 Error: Running LUA method 'draw'.`
[...]
```
E:/-/Documents/my games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Hud.lua:802: attempt to perform arithmetic on field 'y' (a nil value)
2021-12-20 21:43 Error: Running LUA method 'draw'.
```
[...]
```
2021-12-20 21:44 Error: Running LUA method 'draw'.
E:/-/Documents/my games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:198: attempt to perform arithmetic on field 'y' (a nil value)
```
