### ISSUE TITLE
[Feature Request] Abfahrer von vorne Anfahren

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#220]
gibt es eigentlich einen Grund warum der Abfahrer immer von hinten anfährt? manchmal müsste er nur 20m vorwärts fahren, aber er will 100m Kurven fahren um von hinten abzutanken

**Comment by 60erjonny** [comment]
Nun, ein abtanken bei einem fahrenden Drescher ( wenn das so gewollt eingestellt ) ist das wohl sinnig nicht anders möglich...
Bei einen stehenden Abtanken, würde das evtl. gehen...

**Comment by Iwan1803** [comment]
Die Routinen, damit Abfahrer den Drescher und vor allem das Rohrende finden können, sind schon sehr komplex. Dies um weitere zu ergänzen, um Drescher von vorne abzutanken, halte ich für wenig zielführend und sehr zeitaufwändig.
Hier müssten haufenweise Abfragen ergänzt werden: wer fährt den Drescher (da sich Helfer anders verhalten), wo steht er und macht Abtanken von vorne oder hinten Sinn, steht der Abfahrer dem Drescher dann im Weg, etc.

**Comment by Axel32019** [comment]
@RealNeo80  @Iwan1803 hat es schon gut zusammengefasst: viel Aufwand für diesen einen Fall
