### ISSUE TITLE
2 Abfahrer an einem Feld, der volle fährt nicht weg, weil der leere ihn blockiert

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#223]
wie könnte man das lösen?
der volle versucht über den Zielpunkt abzufahren obwohl dort noch der andere steht

![image](https://user-images.githubusercontent.com/8066324/149018497-ac246b97-dbf7-4477-bbbb-0f457a9462d7.png)

**Comment by 60erjonny** [comment]
Hier hat Iwan1803 ein gutes LS19-Howto darüber verfasst. Dürfte für LS22 auch noch alles gelten...https://www.youtube.com/watch?v=FiKmXgiJCGs&list=PL5cOkXj5isconfMMPvBVCkAMh0AepBvey&index=10

**Comment by RealNeo80** [comment]
hmm ok, ich schaus mir an. das is manchmal so zäh sich die informationen zu AD zusammenzusuchen
