### ISSUE TITLE
Combine Mode issue

### ISSUE THREAD

**Issue by Philj030** [Stephan-S/FS22_AutoDrive#224]
Is anyone else having an issue with the combine not being called unless you are physically in the combine ?

**Comment by Iwan1803** [comment]
If a helper is driving the combine, the unloader will be called at the set fill level.
If you are driving it:
- the unloader is automatically called when the harvester is stopped and the pipe is extended
- if you've activated the active unloader option, the unloader will drive to the combine if the pipe is extended
- if you left the vehicle, the unloader will stop
