### ISSUE TITLE
Unimog U400 mit wechselrahmen

### ISSUE THREAD

**Issue by Osram1981** [Stephan-S/FS22_AutoDrive#225]
Benutze den Unimog und AD erkennt die Ladefläche beim Abladen nicht richtig er lädt ihn bloß ab wen der Anhänger und der Unimog gleichzeitig auf den trigger Stehen auch wen der Unimog allein fährt kommt er oft mit voller Ladefläche zurück. Hab den mod von FBM geladen, wen man das was machen könnte währe toll der bleibt nämlich in Abholen und Liefern Modus immer am verkaufspunkt stehen und fährt nicht weiter denke er erkennt das er nicht komplett abgeladen hatt.

**Comment by Osram1981** [comment]
Noch dazu benutze die 2.0.0.3 
Hab das heute nochmal getestet sobald du 2 Anhänger dran hast ist das gleiche Problem der abfahren lädt zuerst den hinteren Anhänger ab und bei vordere bleibt dan voll und er bleibt dan am abladepunkt stehen weil er nicht leer ist.
Desweideren ist mir aufgefallen das wen du mehrere laufen hast bleibt irgendwann mal der ein oder andere an ner Kreuzung stehen, oder wen ich ein zum Beispiel einen grupper zu anderen Feld schicke dan muss ich erst ein Stück fahren bis AD das macht.

Benutze die Kurse vom Willi und spiel auf der Frankreich Karte

**Comment by rohne83** [comment]
Der Unimog hat derzeit noch jede Menge Fehler. Würde mal vermuten, dass es zur Zeit erstmal noch ein Mod-Problem ist.

**Comment by Osram1981** [comment]
Ok alles klar danke für die info
