### ISSUE TITLE
If Silo empty wait enhancement (or bug fix?)

### ISSUE THREAD

**Issue by Mobius104** [Stephan-S/FS22_AutoDrive#226]
Using 2..0.0.3 I am trying to set up 
  grain carts offload into motherbin
  --> motherbin offloads into semi trucks
  --> semis take grain to silo.  or sale point.

The problem is with multi-bin trailers.  If the motherbin doesn't have enough grain to completely fill the truck, the loop breaks and the truck sits there forever.   The truck pulls forward regardless until it is full or it hits the waypoint.  When the motherbin can't fill it as it passes through, it ends up reaching the waypoint without a full load in the first bin(s).  When the final bin fills it sits because the front bins aren't full.  With an actual silo the truck will wait with the first bin under the fill pipe.  With augers the truck waits at the defined waypoint rather than with the first bin under the auger trigger point.

edited for clarity

**Comment by Axel32019** [comment]
Please add some screenshots with destinations shown.

**Comment by Mobius104** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7866388/log.txt)

This is my FS22 log file.  Please let me know if there's another I should be posting, couldn't find one.

**Comment by Mobius104** [comment]
Front trailer partially full, truck has pulled forward to waypoint
![Screenshot 2022-01-13 143653](https://user-images.githubusercontent.com/96738051/149419904-4e941942-c650-4619-b885-7a1cc5b4dcda.jpg)
![Screenshot 2022-01-13 143610](https://user-images.githubusercontent.com/96738051/149419910-ae0b992a-f701-4895-94cc-419132361a11.jpg)
.

**Comment by Mobius104** [comment]
![Screenshot 2022-01-13 154511](https://user-images.githubusercontent.com/96738051/149426350-b2fe6bef-1418-4956-b4f0-e1e4caaeda31.jpg)

Rear bin is now full.  Truck does not progress to silo, loop stops.

**Comment by Axel32019** [comment]
This could not be solved without breaking the complete system of loading with other augers, just to solve this single situatation.
Suggestions:
1. Use a unloader with only 1 fillUnit
2. Make the route of unloader the oposite way, target for 2nd fillUnit, set unload level to 40% - the unloaders might not be filled complete but will always continue.
