### ISSUE TITLE
Grain Carts no longer offload combine on the move *

### ISSUE THREAD

**Issue by Mobius104** [Stephan-S/FS22_AutoDrive#227]
In 2.0.0.2 I had no issues with combine offload on the move into grain carts (specifically Kinze 1051).  In 2.0.0.3 the tractor attempts to offload on the move, but positions himself with the front of the grain cart just behind the auger of the combine, so the combine doesn't offload and they traverse the field like that.  Tractor needs to be a couple meters at least farther forward.

Edit:  Combine being used is stock FS22 Class Lexion 8900.  Fendt 942 and JCB 8330 used to pull grain carts, both with  Kinze 1051 specifically now fails to offload on the move where before it did.  Stock FS22 Elmer Haulmaster is able to offload on the move, but the auger pipe is just about past the front of the cart.

**Comment by Mobius104** [comment]
I haven't had any pathfinding issues.  I do make it easy for the AD graincarts by having the combine(s) traverse the field left<->right (horizontally) as viewed from the offload point, rather than up/down, and have the harvested rows moving progressively farther away so that there's empty field between the cart and the offload point.  I find this keeps my having to untangle grain carts from combines much less often.   If it's a very large field or one with very long rows I will subdivide it so that the combine always has the capacity to do the row when the auger is on the unharvested side and have enough capacity left when starting the next row for the cart to get into position and offload on the move.  You still get occasions when the combine fills with the auger on the unharvested side and they have to stop and unload, but most of the time everything keeps running.

**Comment by Hanslimaa** [comment]
I have the same issue. I took a screenshot. 
![20220125193624_1](https://user-images.githubusercontent.com/66185982/151048394-e04b74f7-845f-4e13-aa4b-1ca8ea40d3e5.jpg)

**Comment by bojanh66** [comment]
I also have problem with pathfinding issue, tractor with trailer have hard time following auger pipe of combine and tractor also needs to be few meters in front, at least 2-3 meters minimum.
Back to 2.0.0.2 until this issue/bug is fixed.
