### ISSUE TITLE
Automatische Kurvenverbindung letztes Segment

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#23]
Hallo Stefan 
Erstmal Danke das du AD für LS22 gemacht hast.
Bin schon fleissig am einfahren in o-belron.
Auch die neue automatische Kurvenverbindung hilft viel.
Dabei ist mir aufgefallen das es dabei meist so aussieht wie wenn am ende der verbindung ein eckpunkt mehr sein könnte.
Die letzte verbindungslinie ist doppelt solange wie die anderen und die knickwinkel größer.
Stell dir später noch einen screenshot davon rein.
Kann gerade nichr auf den spiele pc zugreifen.
Lg
Andreas

**Comment by andreasthu** [comment]
Hier noch die Bilder vom Kurven erzeugen:
![fsScreen_2021_12_19_14_42_03](https://user-images.githubusercontent.com/24860501/146741865-a6a1513d-6c82-4696-8521-e40df6541387.png)
![fsScreen_2021_12_19_14_42_08](https://user-images.githubusercontent.com/24860501/146741875-3b4f2513-d397-40c1-b145-f4ad3c214342.png)
die Kurve wird mit 4 segmenten erzeugt (die ersten drei sind kurz, das letzte doppelt solange und "mehr geknickt"
da könnten mMn ruhig 5 gleichkurze segmente sein mit gleichem knickwinkel.
lg
andreas

**Comment by Rumspringa90** [comment]
Meiner Meinung nach müssten da eher nur 3 Segmente erzeugt werden. Weil dann würde er nicht mehr versuchen mit zu viel Geschwindigkeit in die kurve zu fahren und dann schlagartig abbremsen wenn der Lenkeinschlag voll erreicht ist und er quasi schon über den Punkt hinaus geschossen ist, sondern konstant mit 12km/h in und durch die kurve fahren.

Alternativ müsste man nicht nur ein Winkel für die Berechnung benutzen sondern diese aufaddieren und dann zu gucken welche Geschwindigkeit ich brauche. Gegebenenfalls noch mit einer Länge gekoppelt, da man in langezogenereren Kuven schneller fahren kann als in engen Kurven.

**Comment by regs1980** [comment]
> die Kurve wird mit 4 segmenten erzeugt (die ersten drei sind kurz, das letzte doppelt solange und "mehr geknickt"
> da könnten mMn ruhig 5 gleichkurze segmente sein mit gleichem knickwinkel.

Anfangs und Endpunkt der Kurve mehr auseinander schon wird die Kurve glatter, wenn das lange Segment direkt auf der Linie liegt und die Kurve mindestens 6 Punkte hat fahren die Fahrzeuge am besten.

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
