### ISSUE TITLE
v2.0.0.3 collision detection improperly detects some silos

### ISSUE THREAD

**Issue by Mobius104** [Stephan-S/FS22_AutoDrive#230]
Vehicles detect the edge of the concrete load/unload area and stop.  The Neuro and Neuro multifruit silos, and the Grainquid silos (all three sizes) were what I tested.

It seems to be the raised lip of the concrete area that is triggering the collision detection.  I was able to do terrain modification to make the Neuro silos work with collision detection on, but  was unsuccessful with the Grainquid silos.  Rapid angle of approach terrain changes also trigger collision detection when the vehicle is perfectly capable of navigating said terrain.

This was tested at default detection height settings.  I'm not sure if I should classify this as a bug, or an enhancement request for collision detection.

**Comment by Axel32019** [comment]
Please provide a screenshot with F5 debug to the violett collisions.

**Comment by Mobius104** [comment]
Only mods present are AutoDrive, Power Tools, Player Speed, and the Grainquid silos.  On perfectly flat ground the Farma 400+Obi1000 poses no issues.  However if there is some slope and the building placement auto-levels the ground, collision detection can trigger.  This is on Field 33 on Elm Creek:
![Screenshot 2022-01-14 123800](https://user-images.githubusercontent.com/96738051/149582505-bc80b96f-4766-4b97-83be-dc1fad9d1656.jpg)
![Screenshot 2022-01-14 124113](https://user-images.githubusercontent.com/96738051/149582516-7ccce08a-ef3a-405e-bc41-1db827bf6ec4.jpg)


The grainquid silos fail always, their small ramp for the load/unload area always triggers collision detction regardless of original terrain slope:



![Screenshot 2022-01-14 123042](https://user-images.githubusercontent.com/96738051/149582660-618109d1-eb40-4220-b9ca-854a28afa552.jpg)
![Screenshot 2022-01-14 123925](https://user-images.githubusercontent.com/96738051/149582694-d6c90395-0d86-4e57-9a64-5395759233ec.jpg)

**Comment by Axel32019** [comment]
Increase the collision height step by step, this should help.

**Comment by Mobius104** [comment]
Sorry, F5 on:

![Screenshot 2022-01-14 151106](https://user-images.githubusercontent.com/96738051/149597393-f01ee308-9e10-4534-9ebb-004b2dcf1bf7.jpg)

![Screenshot 2022-01-14 151710](https://user-images.githubusercontent.com/96738051/149597407-792f7ba8-03be-4cd4-8162-423ee098a0f2.jpg)

![Screenshot 2022-01-14 151742](https://user-images.githubusercontent.com/96738051/149597413-3b554912-03e6-493c-84d5-62938a473fd9.jpg)

**Comment by Axel32019** [comment]
Increase the collision height to 2.5m.
If it still stuck please press F5 multiple times until the violett rectangles appear on ground, objects etc. and post the screenshot.

**Comment by Mobius104** [comment]
2.5m was better, successfully navigated the Farma 400, still stopped at the Grainquid silos, even the one put down on flat terrain:

![Screenshot 2022-01-15 074210](https://user-images.githubusercontent.com/96738051/149627947-bf276ac7-0dbb-4aba-a1dd-a10e851339cc.jpg)
![Screenshot 2022-01-15 074314](https://user-images.githubusercontent.com/96738051/149627949-5bdcf481-2aa7-46c9-9cda-3240ee83d124.jpg)
![Screenshot 2022-01-15 074433](https://user-images.githubusercontent.com/96738051/149627954-cbee15d7-383f-4aae-afbe-2a5bed2926ec.jpg)
![Screenshot 2022-01-15 074837](https://user-images.githubusercontent.com/96738051/149628063-22c9175c-adb0-436b-9e2d-170349e2684f.jpg)
![Screenshot 2022-01-15 074913](https://user-images.githubusercontent.com/96738051/149628064-13a8d7c1-6520-4350-bd97-fb663031e77c.jpg)

**Comment by Axel32019** [comment]
The second last picture shows the outline of the bale trigger of that mod. It has the same collision like solid objects, so AD could not drive through. At the moment I do not see any option to solve this in AD, only to use an other mod.
If you are able, you might change the bale trigger collision mask or remove it complete.

**Comment by Mobius104** [comment]
I have notified the Grainquid mod author.
