### ISSUE TITLE
Diesel not available as fill selection on tankers with multiple filltypes

### ISSUE THREAD

**Issue by FusionSimulations** [Stephan-S/FS22_AutoDrive#233]
Using a MAN TGS (base game) and TGX (modded) tanker that accepts multiple liquids (diesel, slurry, digestate, etc), I am unable to select Diesel as a fill option for load/deliver
![no_diesel](https://user-images.githubusercontent.com/97692656/149377265-9a1793df-c493-414b-8033-ee1df2d59cc6.png)

However, if I use the base game field tanker - the Thundercreek fuel trailer - then I am able to select diesel to fill and deliver.

**Comment by Axel32019** [comment]
Please provide a link to the modded TGX

**Comment by Iwan1803** [comment]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=227429&title=fs2022
![image](https://user-images.githubusercontent.com/47528836/149588252-f49f508b-8ac9-4480-81f4-424211b3685c.png)

**Comment by Iwan1803** [comment]
@Axel32019 ich lass den hier mal als Reminder offen, da es aktuell ja noch nicht gefixt ist.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
