### ISSUE TITLE
GUI Auflösungs-Problem - GUI Resolution problem (2.0.0.3)

### ISSUE THREAD

**Issue by LarsCSA** [Stephan-S/FS22_AutoDrive#234]
Habe seit 2.0.0.3 das Problem, dass die Icons extrem schlecht aufgelöst sind. Das ist bei mir erst zu erkennen nachdem man das GUI auf ca. 125% macht. Ab 145% wird eine bessere, ich behaupte richtige, Auflösung angezeigt. (Neu Installation von AutoDrive, hat nicht geholfen). Da kam ich auf die Idee, das Spiele UI größer zu machen, was dazu führte, dass ich selbst nach zurückstellen der Vergrößerung, AutoDrive gar nicht mehr skalieren konnte.  Das Problem trat in dem Singleplayer sowie Multiplayer (Dedizierter-Server) auf. (Spiele das Spiel auf Full HD).  (Neu Installation von AutoDrive, hat nicht geholfen).

Since 2.0.0.3 I have the problem that the icons are extremely poorly resolved. This can only be seen after you make the GUI to about 125%. From 145% a better, I claim correct, resolution is displayed. (Reinstalling AutoDrive didn't help). That's when I came up with the idea of ​​making the game UI bigger, which meant that even after resetting the magnification, I couldn't scale AutoDrive anymore. (Play the game on Full HD). The problem occurred in single player and multiplayer (dedicated server).  (Reinstalling AutoDrive didn't help).

**Comment by Axel32019** [comment]
@LarsCSA Wenn möglich bitte Screenshots mit den verschiedenen Auflösungen und zugehörige logs anfügen.

**Comment by LarsCSA** [comment]
Hat sich mit dem neuen Update anscheinend geregelt (hatte es zuletzt nicht mehr) LG
