### ISSUE TITLE
Pathfinding Problem im "Abholen" Modus

### ISSUE THREAD

**Issue by TheDivine07** [Stephan-S/FS22_AutoDrive#235]
Ich habe einen merkwürdigen Fehler/Unterschied im Pathfinding zwischen dem normalen Fahrmodus und dem Abholmodus festgestellt. Das Video sollte das Problem eigentlich eindeutig zeigen. 

https://www.youtube.com/watch?v=u3k5XxEaIhQ

**Comment by Iwan1803** [comment]
Erwartetes Verhalten: er berechnet den gesamten Weg zum Parkplatz.
Tatsächliches Verhalten: er berechnet erstmal den Weg zum Ladepunkt und nach dem Erreichen des Zielpunktes erst er den Weg zum Parkplatz.
Leider kann man aufgrund der Nebenstrecke nicht erkennen, welche Streckenabschnitte er da anvisiert (die Linien leuchten leicht).
Wäre die Strecke hinter dem Zielpunkt ein paar Meter länger und hätte noch 1-2 Wegpunkte mehr, würde es klappen - außer das Fahrzeug will direkt auf die Rückwärtsstrecke.

**Comment by TheDivine07** [comment]
Hab das ganze gerade mal ausprobiert und zwei weitere Wegpunkte zwischen dem Zielpunkt und dem erste Rückwärtsfahrpunkt erstellt und das ganze funktioniert direkt. Ich kam zwar auf die Idee die Abstände zwischen den Punkten mal zu vergrößern, an mehr Punkte hab ich leider nicht gedacht..

**Comment by Iwan1803** [comment]
Freut mich, das es nun klappt und danke für die Rückmeldung 👍
