### ISSUE TITLE
Fahrzeug blinkt bei Rückwärtsstrecke

### ISSUE THREAD

**Issue by Opa-Andre** [Stephan-S/FS22_AutoDrive#236]
Wenn man in den AD 2.0.0.3 Optionen (und auch den Vorgängerversionen) das Blinklicht (turn light) bei Richtugswechsel aktiviert (habe ich bei mir auf 60° gestellt) funktioniert dies soweit sehr gut. Gibt es jedoch einen Kurs mit Rückwärts-Fahrstrecke, dann wird unabhängig  vom Winkel dort kurz vor und während der gesamten Rückwärtsfahrt das Blinklicht der letzten Kurve aktiviert. Also z. Bsp. bei einer leichten Rechtskurve vor der Rückwärtsstrecke, wo normalerweise kein Blinklicht aktiviert wird, wird das rechte Blinklicht aktiviert und bleibt eingeschaltet, bis die Rückwärtsfahrt beendet ist. 

Die Idee wäre, entweder optional oder generell während einer Rückwärtsfahrstrecke beide Blinklichter links und rechts, d.h. die Warnblinkanlage (hazard light) zu aktivieren - wird ja im "richtigen Leben" auch oft so zur Warnung gemacht...

**Comment by AlexStephenLytton** [comment]
Genau der selbe Vorschlag ist mir vor 3 Tagen in den Sinn gekommen.... Ich schließe mich Andre an :)

**Comment by Iwan1803** [comment]
@Axel32019 vermutlich mal wieder ein Dedi-Server Problem:
nach dem Rückwärts einparken, bleibt der Warnblinker an, aber man muss 2x Numpad-2 drücken, damit er wieder ausgeht.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
