### ISSUE TITLE
Emergency Garbage Dedi Server crash issue

### ISSUE THREAD

**Issue by alexanderweide** [Stephan-S/FS22_AutoDrive#237]
Hallo ab und zu wenn wir Autodrive los schicken crasht der Server:

mit dieser Fehlermeldung: 

2022-01-13 22:01 Warning: Performing emergency garbage collection pass - memory went from 357751 KB to 716151 KB in less than one frame
2022-01-13 22:01 Usage is now 357751 KB; full GC took 806.391100ms 

Es ist ein reproduzierbares Problem.

Wie kann man diesen Fehler beheben?

**Comment by alexanderweide** [comment]
mittlerweile sehe ich einen möglichen Zusammenhang zwischen dem neuen Interface und Autodrive. : wenn ich in gleicher Konstellation Autodrive über das Interface und den Start Stop button drücke, stürzt der Server mit besagter Fehlermeldung ab. Wenn ich Autodrive aber via Hotkey starte dann scheinbar seltener.

**Comment by Iwan1803** [comment]
Bitte Log vom Server und vom Client posten, danke!

**Comment by alexanderweide** [comment]
Problem gelöst:

Infos zum Server / Game:

16 Fach Map Swedisch Landscape
128GB RAM Server mit 5 Spielern.
Nebenstrecken ist das Problemkind das gefixt werden muss.
Die Karte hat keine Traffic Splines oder ähnliches. 

im ersten Bild sieht man was den Crash verursacht hat und zwar wenn der Traktor auf einem Nebenstrecken Kurs steht der nicht mit dem Zielpunkt/Hauptnetz verbunden ist. 

![Bildschirmfoto vom 2022-01-15 00-38-09](https://user-images.githubusercontent.com/7734241/149598606-7d3446ec-47db-4bf7-a73d-fbcf2bb8da90.png)

Wenn man dann beidseitige Verbindungen schafft. NICHT nur einseitige - wie im folgenden BIld... ist das Crash Problem gefixt.
Die Feldrandkurse sind zum sprühen ohne Courseplay da.

-> Programmiertechnisch sollte auf jedenfall eine maximal Itteration eingestellt werden für nebenstrecken, damit der Server sich nicht bis zur Erschöpfung den Weg sucht. ggf sollte es eine connection abfrage geben und wenn keine Connection gefunden wird sollte die Abfrage eine Fehlermeldung erzeugen und einfach stoppen. 

Ich habe das auf unserer 16 Fach Map Schwedish Landscape auch an anderer Stelle probiert ->

Wenn die Nebenstrecke nicht mit der Zielstrecke/Grünen Strecke verbunden ist, crasht das Spiel/Server vollständig. Nur ein total Restart hilft dann noch. 128gb Ram des Servers werden geflushed.

Lösung ist aktuell alle Strecken und vorallem alle Nebenstrecken zu verbinden mit dem Hauptnetz.

**Comment by Iwan1803** [comment]
Nur noch mal zur Erinnerung: AD ist NICHT für die Feldarbeit ausgelegt und wir werden das auch nicht supporten.
Wenn es knallt, weil ihr Nebenstrecken nicht mit dem Hauptnetz verbindet, aber der AD-Fahrer auf das Hauptnetz drauf fahren soll, ist das erstmal in meinen Augen kein wirkliches AD-Problem.
Vielleicht wird einer der Entwickler aber noch mal einen Blick auf die Streckenberechnung bzgl. "Nebenstrecken" werfen. Daher lasse ich das hier erstmal offen.

**Comment by alexanderweide** [comment]
> Nur noch mal zur Erinnerung: AD ist NICHT für die Feldarbeit ausgelegt und wir werden das auch nicht supporten. Wenn es knallt, weil ihr Nebenstrecken nicht mit dem Hauptnetz verbindet, aber der AD-Fahrer auf das Hauptnetz drauf fahren soll, ist das erstmal in meinen Augen kein wirkliches AD-Problem. Vielleicht wird einer der Entwickler aber noch mal einen Blick auf die Streckenberechnung bzgl. "Nebenstrecken" werfen. Daher lasse ich das hier erstmal offen.


weiteren Bug gefunden: Die Abstürze entstehen auch, wenn AD mit Grünen Lines nicht verbunden ist. Also von Grün zu Grün. Das kann durch Fehler mal passieren, es darf nicht zum Absturz führen.  Denn Fehler machen ist menschlich. 

das mag alles sein. Ich finde es ein wenig Frech so zu schreiben, da es hier um Verbesserungen geht. Seit doch froh wenn Leute eure Mod so nutzen wie man AD schon in LS 19 am Anfang genutzt hat als es noch kein Courseplay gab. 

Abgesehen davon. Es muss möglich sein das Nebenstrecken NICHT angeschlossen sind an das Hauptnetz. Zum Beispiel bei Produktionsstraßen und Automatisierter Produktionskreisläufe. Ich und ich glaube ich kann für viele Spieler sprechen, streben eine Voll-Automatisierung von Produktionen an. Und meist findet das alles auf einem Gelände statt wo sonst keiner hin kommt. Wenn dann der Server abstürzt ist das nicht nur ärgerlich, das sollte funktionieren, abgesehen von Nebenstrecken war das auch schon in FS 19 möglich. 

Nichts für ungut. Danke trotzdem für die Arbeit und den Mod. Ich wollte nur helfen.

**Comment by Dzi4d3k** [comment]
If I correctly understood translation, the main issue lay in existence of two separate networks, not AD used for field work.
IMHO that's not uncommon configuration to have separated networks and I would totally agree with @alexanderweide on his point of view.

**Comment by Iwan1803** [comment]
However, the only reason for a 2nd road network in this case is that it is used for field work, for which AD is not intended.
As written above: maybe one of the developers will take a look at the route calculation regarding "secondary routes". Therefore I leave this open for now.
So I don't understand why somebody has to react so childishly.

**Comment by alexanderweide** [comment]
> However, the only reason for a 2nd road network in this case is that it is used for field work, for which AD is not intended. As written above: maybe one of the developers will take a look at the route calculation regarding "secondary routes". Therefore I leave this open for now. So I don't understand why somebody has to react so childishly.
hasnothas nothing to do with childish. Your reaction is selfcentered. I never said that you have to make fieldwork possible. But its quite insane to say reply that there are in no way Situations where you would not want to have multiple disconnected networks. In fact i have 5 servers with multiple players kinda public if you will. And there are many players who dont trust each other or even have different knowledge about the game so. Everyone build there own networks in order to not get influenced by annother player... many gamers only playing together on a server to have this feeling of a community but in fact most of them are single players.. its beyond my mind why you comment like this.. only for a request or idea to improve the code also because it dosent was a problem back in fs19.. so when it was working in fs19 it should work in fs22 too. Without respect i know fs22 is a troublesome problematic release.. but its just code..

**Comment by alexanderweide** [comment]
> If I correctly understood translation, the main issue lay in existence of two separate networks, not AD used for field work. IMHO that's not uncommon configuration to have separated networks and I would totally agree with @alexanderweide on his point of view.

Totally agree it should be possible to have different networks... the question is if this calculation between main networks and side networks are need to calculate a priority like now

**Comment by Iwan1803** [comment]
> And there are many players who dont trust each other or even have different knowledge about the game so. Everyone build there own networks in order to not get influenced by annother player...

And that is a reason for several road networks, which are not connected to each other? 🙄
Sounds a little bit like "kill him, he's driving on my road", isn't it? Playing together on a server should be not like "i play only for myself". It should be more like "hey, you need straw? no problem, i'll sell mine to you" or do you really only have egoists playing on the servers, maybe creating several AD networks on the same streets? Wouldn't it be better to introduce the players to AD and teach him? Then no one would have to be afraid that someone foreign comes near to or on their own farm.
But it's ok for me as everyone may play the way he wants to. Just my 2 cents...

I offered you that maybe one of the developers will take a look at the route calculation for this "strange" problem, but it seems that this is still not enough for you. You want it to work.
May I remind you that we do all this in our spare time? Acting like a defiant child here and shouting "I want" will certainly not help you.

And now let's all calm down and wait to see what the developers have to say about it.

**Comment by alexanderweide** [comment]
First of all iam calmed down. Dont tell me how i should feel. Secondly stop reading my text like you want. I never said you have too. I only made aware that it should work. And yes i totally agree that playing together is better. But keep in mind many people arent collective. Not everyone is looking for actrue participation espacially not on a public server. And yes production networks are seperated. You also dont talk to every neighbour espacially not in a big city.

**Comment by Dzi4d3k** [comment]
Well I didn't wanted to introduce any nervousness into discussion and would agree with both point of views. And conclusion could be like with many different software problems.
We have to options:
1. Workaround - at this point not use bug leading network configuration.
2. Solution - try to fix code (wait for developers).

But direction is indeed up to decision for developers if they find it so critical to fix and find time to fix it. With either way chosen, we should still be graceful for all work in this brilliant mod 😃
