### ISSUE TITLE
AD auto changes delivery destination

### ISSUE THREAD

**Issue by Resandise** [Stephan-S/FS22_AutoDrive#239]
When using AD to pick up and delivery, or just delivery, When I set it to one location, and click go, the destination changes to somewhere else that I don't want it to go.

**Comment by RealNeo80** [comment]
Its not a bug, its a feature .... somewhere i read that AD is searching for best price for product

**Comment by Resandise** [comment]
Um, Its a bug when I want it delivered to my Silo and not SOLD.

**Comment by 60erjonny** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Release-Notes-for-AutoDrive-english

Zitat: Added automatic unload target selection (based on sell price)

Just click with the mouse ... 

Funktion aktiviert...
![fsScreen_2022_01_14_19_27_56](https://user-images.githubusercontent.com/63659182/149566808-4e0cb74a-4dbd-49d3-9050-f5f9c42b812e.png)

Fuktion deaktiviert...
![fsScreen_2022_01_14_19_28_03](https://user-images.githubusercontent.com/63659182/149566920-42713607-7c8c-4543-bd79-a42af8a3b867.png)

**Comment by 60erjonny** [comment]
> Um, Its a bug when I want it delivered to my Silo and not SOLD.

What is the Ad-Hud from you ...?
Is this Function on or off?
Did you possibly be a rotation?

**Comment by Chico0008** [comment]
The thing is : when you activate auto-dest in delivery mode, it stay active for other mod (unload only or combine)
so if you set your vehicule to combine, having the auto-dest activate, it will go to unload to the best price, even if you whoose your silo first.

you can only activate/deactivate this option in delivery mode, 
an update that could be made, is the ability to deactivate the auto-dest for un load when your are not in delivery mode

If the trail is bleu, auto-dest is activate, if white, it's not.
just have in mind you have to deactivate auto-dest before changing mode :)

**Comment by 60erjonny** [comment]
@Chico0008 
In my eyes, it does not matter which mode is used.
Either I would like to sell it at the best price, or set a specific destination
So you only have to go on or off ...

**Comment by Resandise** [comment]
Appearently, I had it on Auto Dest, and didn't know that was even a thing, My bad.

**Comment by Roby1164** [comment]
Problem reappeared, my solution no longer works, as written in my post https://github.com/Stephan-S/FS22_AutoDrive/issues/305
