### ISSUE TITLE
Lua error on startup

### ISSUE THREAD

**Issue by mrPassion78** [Stephan-S/FS22_AutoDrive#24]
i started a savegame on erlengrad, and on a mon map, no mans land, and on both a got a LUA error. i have no idea what it is, but thought to report it here.
i tied to add my log file here, but some how it does not accept it so i put in a screenshot of the LUA errors. no mods active just AD, and map is loaded, and thats when the screenshot is taken. 
![LUA error FS22](https://user-images.githubusercontent.com/40406761/146671527-51aa528d-c587-4f1b-befa-7829d0fe07d8.jpg)

**Comment by Iwan1803** [comment]
Looks like here: https://github.com/Stephan-S/FS22_AutoDrive/issues/4

**Comment by Stephan-S** [comment]
Yeah, known issue. Already fixed and bugfix release coming soon!
