### ISSUE TITLE
destination not reachable from one node to another

### ISSUE THREAD

**Issue by sschiebrel** [Stephan-S/FS22_AutoDrive#241]
trying to get the farmers market on elm creek... all my nodes have green connection lines and are going in the right direction.
i'm at an intersection (not sure it that's relevant.. but I am).   I have a waypoint at the farmers market.   if I tell the tractor to goto that waypoint on a node before the intersection, i get "can't reach" but if I move the tractor one node farther along, it can reach it fine.   i've tried deleting the points and recreating them, deleting a bunch of points connecting them manually, recording a route across the intersection...  nothing seems to matter.

**Comment by RealNeo80** [comment]
if you took the standard lines, there are some dead ends in, Activate the Dev console, there you can let u show the dead ends
im pretty sure thats the problem

![image](https://user-images.githubusercontent.com/8066324/149587405-a4d7d3bd-1947-4224-92e3-b8891c1bbe69.png)

**Comment by Gnrnr** [comment]
Might not be a dead end, it might be a node point is slightly behind the previous node point.  If the angle is too sharp between nodes, the path cannot be found.  This is usually near where you start a new track from an existing one.

**Comment by RealNeo80** [comment]
he haven´t replied for 3 days, so i think it can be closed anyway

**Comment by sschiebrel** [comment]
I fixed it by deleting about 20 nodes either way of (before and after) the intersection.   the nodes were not behind others (no abrupt change of direction) or were they dead ends.   I think maybe when the system used the existing AI traffic system and converted those to nodes, it had a little issue converting those or something.    removing 20 or so nodes seemed to fix the issue.   i've had issues connecting the converted nodes to recorded ones anyway.  i'm to the point where I'll just use recorded paths everywhere..
