### ISSUE TITLE
Gras Mähen mit Cours außerhalb von Feldern

### ISSUE THREAD

**Issue by audiklaus** [Stephan-S/FS22_AutoDrive#242]
Hallo wie ist es möglich Gras außerhalb von Feldern mit einen Cours zu Mähen?
Also wenn ich einen Cours mit einen Traktor u. Mähwerk und Ladewagen erstellt habe über Feldrändern und Feldern, so wird nur auf dem Feld gemäht NICHT aber der RAND sobald Autodrive aktiv ist.
Was kann ich einstellen das ich auch das Gras an den Rändern mähen kann so wie früher?
Für mich ist das leider ein riesen Problem.
Ich bedanke mich für Ihre Antworten.

Danke audiklaus

**Comment by RealNeo80** [comment]
Bist du sicher dass du nicht courseplay meinst? du bist hier im Autodrive ;) Aber du könntest mal die 7.0.0.19 von CP probieren, da hast du jetzt die möglichkeit die feldgrenzen zu erweitern Field Margin im Minus vergrößert das Feld. einfach mal Probieren. bei Fragen aber dann bei CP ein Issue posten!

**Comment by audiklaus** [comment]
Ja nee ganz so verwirrt bin ich auch nicht, ich bin auch schon sehr lange dabei.
Feldgrenzen erweitern, bringt mich nicht weiter, weil es bei courseplay NUR eine automatischen Coursgenerator gibt.  
Ich sollte hier ein Foto posten?

**Comment by Iwan1803** [comment]
Wenn du ein CoursePlay-Problem oder eine Frage zu CoursePlay hast, dann mach das bitte auf dem github von CoursePlay und nicht bei uns hier von AutoDrive: https://github.com/Courseplay/Courseplay_FS22/issues

**Comment by audiklaus** [comment]
Entschuldigung wenn ich mich einfach unklar ausgedrückt habe.
Hier die Bilder:
<a href="https://imagetwist.com/rk3ovowg6ru3/fsScreen_2022_01_14_22_30_40.png" target="_blank"><img src="https://img119.imagetwist.com/th/45811/rk3ovowg6ru3.jpg" border="0"></a>
SO sieht es leider aus.

<a href="https://imagetwist.com/7ha107kwa9q7/fsScreen_2022_01_14_22_30_54.png" target="_blank"><img src="https://img119.imagetwist.com/th/45811/7ha107kwa9q7.jpg" border="0"></a>
So sollte es aussehen.

<a href="https://imagetwist.com/7ytu1evoxtvy/fsScreen_2022_01_14_22_59_06.png" target="_blank"><img src="https://img33.imagetwist.com/th/45811/7ytu1evoxtvy.jpg" border="0"></a>
Der Kurs im AutoDrive.

Nochmals:
Was kann ich machen das er auch die Ränder mäht? Denn wenn das nur manuell geht mmmm.

**Comment by Iwan1803** [comment]
AutoDrive ist nicht für die Feldarbeit gedacht, sondern für Fahrtätigkeiten und richtig: Gras mähen ist eine Feldarbeit.
Wenn du das Gras abseits eines Feldes mähen möchtest, musst du das entweder per Hand machen oder die Felder entsprechend vergrößern.
