### ISSUE TITLE
Ränder Mähen wird von AutoDrive blockiert

### ISSUE THREAD

**Issue by audiklaus** [Stephan-S/FS22_AutoDrive#243]
Hallo wie ist es möglich auch an Rändern mit einen Kurs Gras zu mähen?
Problem: Das Mähwerk mäht NUR auf den Feld sobald der AutoDrive Kurs gefahren wird.
![fsScreen_2022_01_14_22_30_40](https://user-images.githubusercontent.com/95242079/149593238-364f0004-cbaf-4972-bb0d-c88c69f34c93.png)
Der AutoDrive Kurs sieht So aus:
![fsScreen_2022_01_14_22_59_06](https://user-images.githubusercontent.com/95242079/149593347-5270ecab-7890-4d8f-b6d6-85d1897733c6.png)

Und so sollte es eigentlich sein: (wie es auch in LS19 ging):
![fsScreen_2022_01_14_22_30_54](https://user-images.githubusercontent.com/95242079/149593456-5bd30993-6a6b-4fd8-91b8-33e0cc28b3c4.png)

Was muss ich tun damit das ganze Gras gemäht wird? Leider wird mit AutoDrive das Mähwerk irgendwie auf dem Feldrand deaktiviert. (nicht Ausgeschaltet wie zu sehen ist). Für mich ist das leider ein sehr großes Problem, da man so natürlich keine Grasflächen mehr mähen kann außerhalb von Feldern.
Wie kann man diese Deaktivierung aufheben?

mfg audiklaus

**Comment by Iwan1803** [comment]
Warum machst du einfach ein neues Issue auf, obwohl ich dir alles in dem anderen bereits erklärt habe?

**Comment by audiklaus** [comment]
Danke für deine Erklärung.
Früher ging es.
