### ISSUE TITLE
Cannot find harvester when using Combine unload mode

### ISSUE THREAD

**Issue by AyakawaSakura** [Stephan-S/FS22_AutoDrive#244]
**Version:** 2.0.0.3

**What happened:**
I have a harvester(leased Axion-flow 7150 with 3020 TerraFlex 25FT header) working on field 71 on the Elmcreek map, and I have a Fendt 1050 with Bergmann HTW 65 trailer to coop with the harvester. However, When I assign the trailer to "Unload combine" mode and let the build-in helper to operate the harvester, the trailer shows "No harvester with same target found".
This problem persists for built-in helper and course-play helper.

**Map:** Elmcreek with AD course from: https://www.modhub.us/farming-simulator-22-mods/autodrive-elmcreek-by-elmatador-v1000

**Log:**
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7874349/log.txt)

**Screenshot:**
![Screenshot 2022-01-15 135626](https://user-images.githubusercontent.com/30264706/149611173-0740af58-29b2-4434-93db-fa356bff04bb.jpg)
When the harvester is full....

![Screenshot 2022-01-15 135646](https://user-images.githubusercontent.com/30264706/149611190-10154d8a-b6c1-44d8-92e6-9b99f1451abb.jpg)
 The trailer is hot helping.

**Comment by mfehr94** [comment]
The communication between CP and AD is not implemented properly yet. Please be patient with the developers

**Comment by AyakawaSakura** [comment]
> The communication between CP and AD is not implemented properly yet. Please be patient with the developers

I am aware that cross-mod communication is not available. But this cannot explain this problem when using built-in helper. Especially I used this function serveral days before with forage harvester and it worked fine.

**Comment by Axel32019** [comment]
As the red message tells: Harvester and Unloader 1st targets do not match to work together.
You have to set the same target in the harvester, this case "Field-71".

**Comment by AyakawaSakura** [comment]
> As the red message tells: Harvester and Unloader 1st targets do not match to work together. You have to set the same target in the harvester, this case "Field-71".

Thanks for replying. I set the harvester to combine unload mode and the first parameter to field 71. And the problem solved. I am closing this issue for this is my problem.
