### ISSUE TITLE
Color spectrum of dots when trying to add a new waypoint 

### ISSUE THREAD

**Issue by WildBill-Massive** [Stephan-S/FS22_AutoDrive#245]
When holding LCRTL and clicking RMB I get a triangle shaped color spectrum of dots.

![fsScreen_2022_01_15_12_34_01](https://user-images.githubusercontent.com/97803803/149633809-38823662-58ec-4acd-a968-12d1fbf53514.png)

**Comment by Axel32019** [comment]
Please have a look at this: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#new-color-assignment-for-users-with-different-color-perception

**Comment by WildBill-Massive** [comment]
Thank you for the assistance. The solution worked.
