### ISSUE TITLE
Dual hopper trailers don't fully unload

### ISSUE THREAD

**Issue by JDTiger** [Stephan-S/FS22_AutoDrive#246]
Hey,

When using a trailer with multiple hoppers, autodrive does not unload both of them, the truck will continue with one hopper still loaded.

kind regards,
JDTiger

**Comment by Petromotion** [comment]
Seems to work for me. Make sure your waypoint is far enough ahead of the trigger for both dumps to work. 

What trailer are you using?

**Comment by JDTiger** [comment]
I am usingf the Wilso PaceSetter, and it only emptys the rear Hopper, so not a problem with too little space.

**Comment by MoslessNeo** [comment]
The truck arrives at the unloading point, unloads the first compartment, and then stops.
[https://1drv.ms/u/s!AteKuv2uUj5JgZWoCfXRAJY0C81F6rE?e=KkieoG](url)

**Comment by rohne83** [comment]
> The truck arrives at the unloading point, unloads the first compartment, and then stops. https://1drv.ms/u/s!AteKuv2uUj5JgZWoCfXRAJY0C81F6rE?e=duzgHa

In this case your point is much too near to the silo. Place it far enough that all hoppers went over the silo trigger before the truck reaches the point.
