### ISSUE TITLE
[BUG] on a dedi server the turn signals doesn't turn on

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS22_AutoDrive#247]
Auf einem Dedi-Server funktionieren die Blinker nicht. Ich habe die Blinkereinstellung mit 30, 60 und 80 gestestet, aber selbst bei Kurven mit weit über 120° werden sie nicht eingeschaltet.
Nutze ich das savegame vom Server lokal im SP funktionieren sie hingegen problemlos.

**Comment by Axel32019** [comment]
@timmi4026 , @Iwan1803 Wenn ich das live richtig gesehen habe ist das ein generelles Problem mit dem Licht-System von Giants. Sehe momentan keinen Ansatzpunkt für AD, wir machen nur Licht an oder aus, nix spezielleres.
