### ISSUE TITLE
[BUG] Abfahrer fährt von AIVE-Ernter weg ohne vollständig entladen zu haben

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS22_AutoDrive#248]
AIVE ist bei mir eingestellt, das der Drescher zum Abtanken anhalten soll.
Er ruft bei den eingestellten 60% den Abfahrer, welcher dann auch kommt. Erreicht er den Drescher, fährt dieser das Rohr aus und bleibt stehen. Der Abfahrer fährt darunter, lädt auch einen Teil ab, aber fährt dann nach einer gewissen Zeit rückwärts, wo er dann stehen bleibt. Der Drescher setzt dann seine Fahrt fährt.
Der Abfahrer hat auch noch nicht den eingestellten Füllstand erreicht.
Ich bin mir nicht ganz sicher, wer hier in dem Fall der "Schuldige" ist.

**Comment by RealNeo80** [comment]
ich würde auf AD tippen, habe das jetzt auch ein paar mal mit CP beobachtet

**Comment by WotanTGH** [comment]
Habe das gleiche Problem. 
Drescher steht. AD Abfahrer fährt unter das Rohr, Abtanken startet. 
Nach einigen Sekunden beginnt der AD Abfahrer langsam rückwärts zu fahren und wechselt in "Zurücksetzten von Drescher" ohne das dieser fertig abgetankt war. Damit ist der Abtankvorgang beendet. 
Habe es mit verschiendenen Zugfahrzeugen und verschiedenen Anhängern getestet.
Tritt nur auf, wenn der Drescher noch nicht bei 95% Füllstand war und quasi durch das Heranfahren des AD Abfahrers gestoppt wurde.

**Comment by Axel32019** [comment]
@Iwan1803 Bitte log.txt mit Debug Drescher und Pfadfinding anfügen.

**Comment by Iwan1803** [comment]
@Axel32019 bitte schön und bei Bedarf kann ich dir auch ein Video schicken.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7898411/log.txt)

**Comment by Axel32019** [comment]
@Iwan1803 
Kein Bug, funktioniert wie es soll - der "Schuldige" sitzt vor dem Monitor:
Ernter ist eingestellt für "Aktives Abfahren", richtig?
s.o. AIVE ist bei mir eingestellt, das der Drescher zum Abtanken anhalten soll.
Bleibt der Ernter und damit auch der Abfahrer stehen, wird dies nach spätestens 60s, wahrscheinlicher nach 15s als Blockade erkannt - log: got stuck - reversing now
Der Abfahrer fährt jetzt rückwärts aus der Blockade heraus.
Lösungen:
1. Ernter nicht zum Abtanken anhalten lassen oder
2. "Aktives Abfahren" aus

Beides aktiv geht nicht!

**Comment by Axel32019** [comment]
> Habe das gleiche Problem. Drescher (per CP gesteuert) fährt Rohr aus (noch während der Fahrt). AD Abfahrer fährt unter das Rohr. Drescher hält an. Abtanken startet. Nach einigen Sekunden beginnt der AD Abfahrer langsam rückwärts zu fahren und wechselt in "Zurücksetzten von Drescher" ohne das dieser fertig abgetankt war. Damit ist der Abtankvorgang beendet. Habe es mit verschiendenen Zugfahrzeugen und verschiedenen Anhängern getestet. Tritt nur auf, wenn der Drescher noch nicht bei 95% Füllstand war und quasi durch das Heranfahren des AD Abfahrers gestoppt wurde.

Siehe vorheriger Kommentar - gilt auch für CP u.ä. Helfer mit solchen Einstell-Kombinationen

**Comment by Iwan1803** [comment]
@Axel32019 wäre es dann nicht besser, bei Helfern das "Aktive Abfahren" zu ignorieren?

**Comment by Axel32019** [comment]
@Iwan1803 "Sonderbehandlungen" sind nicht hilfreich, gleiches Verhalten für alle ist das Ziel.

**Comment by rohne83** [comment]
Blockadeerkennung nach 15 Sekunden? Könnte evtl bei CP zu Problemen führen, wenn das Ende einer Feldreihe erreicht ist. Wenn das Entladen nämlich vorher schon begonnen hat, hält CP den Drescher/Roder dann ca 2Meter vor dem Ende der Bahn an, um den Tank komplett abzuladen - ist soweit auch das einzig sinnvolle Vorgehen in der Situation. Würde aber bedeuten, dass AD auch dann wieder fälschlicherweise eine Blockade vermutet, es sei denn ihr bekommt da noch eine passende Funktion für in die Schnittstelle mit eingebaut.

**Comment by RealNeo80** [comment]
ich hab heute das beim Panther mal bewusst ohne aktives abfahren eingestellt. da ist das ganze aber auch zu beobachten, Panther bleibt stehen, leert ca. 30-40% azsm Abfahrer fährt Rückwärts und der Panther fährt weiter obwohl er net leer ist

**Comment by Daywalker885** [comment]
So ich hänge mich hier mal mit rein, nachdem mich der @Iwan1803  darum gebeten hat mal meine situation zu schildern auch wenn es hierbei eher um AIVE geht. So folgendes hab ich :-------->  Doch habe ich probleme mit meinen abfahrern, wenn ich am dreschen bin (Häckseln war noch nicht dran) Wenn ich ihn über das rohr rufe, natürlich früh genug, bevor ich quasi zum vorgewände komme, natürlich auch früh genug bevor der tank voll ist. Fährt der immer erst zu dem punkt wo er das rohr erkennt bzw. den ruf. Dann kommt er schon nicht mehr hinter her und bleibt auch manchmal dann einfach auf der bahn stehen. Wenn ich ihn selbst rufe und mal glück habe, das er den weg zu mir schafft und ich kurz vorher das rohr ausfahre, hab ich manchmal glück und er fährt auch brav neben mir her. Meistens ist es allerdings so das er nicht schnell genug bei mir ist oder auch mal in mich rein fährt, wenn er mir entgegen kommt. Und wenn ich dann voll bin und natürlich stehen bleiben muss und mir dann auch sage okay ich mach mein tank leer und der abfahrer ist dann wenigstens voll, fährt der oft während ich stehe einfach mal zurück.


Das ist der kommentar, aus youtube von mir, wollte jetzt nicht nochmal alles schreiben, ich kann es mir fast nicht vorstellen, das es an cp oder aive liegt, denn ich fahre den drescher immer selbst und da ich das spiel auf einem dedi server spiele mit freunden, cp ist noch nicht multiplayer fähig, daher habe ich das erst gar nicht und AIVE macht im multiplayer nicht immer das was er soll, egal wie ich es einstelle ob aktives abfahren oder nicht, der fährt einfach zurück, egal ob voll oder ich sage okay jetzt darf ich erst mal wieder anhalten, weil ich sonst zu nah am feldrand bin und der abfahrer da wieder nicht weiter fährt.


Hoffe das wir das schnell irgendwie hin bekommen, denn ich spiele aktuell noch auf der elmcreek (auf schwer) ich habe mittlerweile schon den dritten spielstand angefangen der erste war zum testen waren ca. 80 stunden der zweite, als wir dann auch schon mit AD angefangen haben waren dann 300 stunden under aktuelle 3 stand sind auch schon 270 stunden. Es ist natürlich erstaunlich wie schnell AD am start war nach dem release und das nicht alles sofort funktioniert ist ja völlig verständlich. Nur wenn dann die richtig großen maps kommen, wäre es schade, wenn dort einieges so wie das abfahren nicht richtig geht, denn dann verliert man auch sehr viel zeit und ich denke das dadurch die langzeitmotivation auch verloren geht. 

Es soll hier keine kritik oder sonstiges sein, möchte nur gern meine erfahrungen mitteilen und versuchen zu verstehen warum in diesem fall, der abfahrer so arbeitet

**Comment by RealNeo80** [comment]
@Axel32019 
ich hatte das ganze jetzt wieder mit der 2.0.0.4, log anbei. Das Problem ist das der Abfahrer meint er steckt fest, und fängt dann an Rückwärts zu fahren. Diesmal wars aber der ganz normale Drescher

`2022-01-30 20:24   Info: [AD] 89280 CH7.70: getIsCPTurning getIsCpHarvesterWaitingForUnload false
2022-01-30 20:24   Info: [AD] 89280 CH7.70: getIsCPTurning getIsCpHarvesterWaitingForUnloadInPocket false
2022-01-30 20:24   Info: [AD] 89280 CH7.70: getIsCPTurning getIsCpHarvesterWaitingForUnloadAfterPulledBack false
2022-01-30 20:24   Info: [AD] 89280 CH7.70: getIsCPTurning getIsCpHarvesterManeuvering false
2022-01-30 20:24   Info: [AD] 89307 Scheduler update self.actual_fps 30.0 averagefps 28.8 self.stepsPerFrame 8
**2022-01-30 20:24   Info: [AD] 89340 T7.315 HD: got stuck - reversing now**
2022-01-30 20:24   Info: [AD] 89341 T7.315 HD: ADSpecialDrivingModule:checkWayPointReached start self.currentWayPointIndex 0 
2022-01-30 20:24   Info: [AD] 89341 T7.315 HD: ADSpecialDrivingModule:checkWayPointReached distanceToTarget 91.590045012969 minDistance 4.5 angleToPoint 1.9305432781643 self.currentWayPointIndex 0 
2022-01-30 20:24   Info: [AD] 89341 T7.315 HD: ADSpecialDrivingModule:checkWayPointReached end self.currentWayPointIndex 0 `

Zeile 7974
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7966751/log.txt)

**Comment by RealNeo80** [comment]
@Axel32019 
das ist in der 2.0.0.5-RC noch genauso

**Comment by Axel32019** [comment]
> @Axel32019 das ist in der 2.0.0.5-RC noch genauso

Wie Du weißt: Kein Support für Dev-Versionen!

**Comment by RealNeo80** [comment]
ja, ich wollte dir ja nur Bescheid geben, falls du schon was geändert hast ;)

**Comment by Iwan1803** [comment]
Da ich kein AIVE mehr nutze und sonst weiter keine Problem mehr hatte -> geschlossen!
