### ISSUE TITLE
(FRAGE) Trion während der fahrt abtanken

### ISSUE THREAD

**Issue by Puschl1989** [Stephan-S/FS22_AutoDrive#249]
Hallo zusammen, ich habe da mal eine kleine frage und zwar ist mir aufgefallen das wenn ich versuche meinen Trion während der fahrt abzubunkern das er das Rohr konstant zwischen Schlepper und Anhänger hält. Ich habe schon ein paar Einstellungen versucht, komme aber zu dem Schluss das nichts wirklich geholfen hat ich bin mir auch nicht ganz sicher ob es nicht daran liegt das der Trion das Rohr sehr weit nachvorne schwenkt. Daher meine frage habe ich was übersehen oder gibt es irgendwo noch eine Einstellung mit der man spielen könnte? So wie auf dem Bild zusehen ist fährt er dann die ganze Reihe neben mir her. Ps zusätzlich ist mir auch aufgefallen er fährt auch nur ganz knapp unter das Rohr wenn stehen bleibe passt auch nur gerade so.
LG Puschl
![fsScreen_2022_01_17_01_00_13](https://user-images.githubusercontent.com/97857619/149720990-0885fca1-284f-4b43-a20b-01388a36a2bc.png)

**Comment by ole1510** [comment]
Ich habe das selbe mit dem festgestellt. mit einem anderen Mähdrescher hat es geklappt. wenn du die debug box einschaltest siehst du, dass die box vom Hänger bis zu der Anhänger Kupplung geht. Liegt es evtl. daran, dass er noch in der box ist und davon ausgeht, dass es passt ?

**Comment by Puschl1989** [comment]
@ole1510 Ja inzwischen habe ich auch mal mit den Debugs rumgespielt und ja bei mir sieht es ähnlich auch wie bei dir. Im stand klappt es mit dem Überladen wenn auch nur knapp während der fahrt hält er das Rohr immer zwischen Hänger und Schlepper. Vielleicht wäre eine Option das man Manuell regeln könnte wie weit er vor fährt?

**Comment by MarcDo74** [comment]
Gleiches Problem mit dem Trion. Hoffe es wird gefixt
