### ISSUE TITLE
8RT Turn Radius

### ISSUE THREAD

**Issue by Petromotion** [Stephan-S/FS22_AutoDrive#251]
The turn radius is too tight with a trailer. The worst is the Demco Auger. It will try a 90 degree turn and not have power to turn it. Then time out and stop working. 

![16424076898664310646344758423434](https://user-images.githubusercontent.com/46306268/149733451-f2f1c434-8cfd-4024-9428-9dc95c2556e9.jpg)

**Comment by dozerjz** [comment]
Is there a way to adjust the turn radius on machines?

**Comment by Axel32019** [comment]
You may adjust the vehicle/trailer xml:
look for <ai> and add:
<turningRadiusLimitation radius="10"/>

**Comment by dozerjz** [comment]
Thank you!  I will take a look at this tonight!

**Comment by Axel32019** [comment]
This was improved in Release 2.0.0.5
