### ISSUE TITLE
[BUG] Unload position for Ventor Potato harvester

### ISSUE THREAD

**Issue by Gnrnr** [Stephan-S/FS22_AutoDrive#252]
When using autodrive to unload the Ventor 4150 potato harvester, the tractor pulls up too close to the side of the harvester for the unload position.  The harvester unloads on the right hand side and the tractor tries to be close enough to the harvester that even if it didn't crash into the side, the potatoes would be missing the right hand side of the trailer.

I have tried altering the pipe distance setting for the harvester, but am unsure if this is doing anything at this stage.

**Comment by Gnrnr** [comment]
Ok.  i have played a bit more with it now.  Pipe offset appears to be working as intended.  If I have the harvester set to stopwhile unloading , the tractor with trailer will drive past the harvester and stop about 6-10m forward of where it needs to stop.  If i then drive the harvester up to it, the autodrive tractor will drive away again.

**Comment by Bovrinox** [comment]
I too have found this issue. An easy fix would be to provide a front to back pipe offset as well as a left right offset. Is that something that could be implemented? 
Courseplay had something similar on FS19 I think.
