### ISSUE TITLE
Modded truck headlights

### ISSUE THREAD

**Issue by dozerjz** [Stephan-S/FS22_AutoDrive#253]
Good Morning, I was looking to see if anyone knew what I could do about using modded semi's and the headlights not working at night.  The vehicles only use the running lights.  In fs19, i adjusted the lights to work by changing what items were in option 1 on the modded vehicle, just did not know if there was a way to change this without editing the truck.  Thank you for all you do!

**Comment by Iwan1803** [comment]
Maybe somebody can help you in our Discord: https://discord.gg/9D4B5hX
As this not AD-related -> closed.
