### ISSUE TITLE
Kverneland Optima RS - rückwärts fahren geht nicht / reverse way not working

### ISSUE THREAD

**Issue by theMompfdie** [Stephan-S/FS22_AutoDrive#255]
Liebes AD Team,
ich hab die Tage versucht unsere Maschinenhalle am DediServer mittels Einparkkursen zu machen, damit der Sauhaufen endlich ein Ende hat. Bei der **Kverneland Optima RS** ist jedoch folgendes Problem aufgetreten, welches in den Moment wo der Traktor das Ding Rückwärts reinschieben sollte seine Aufgabe sofort beendet und nur sagt das der Punkt erreicht wurde.
Wenn ich den gleichen Punkt mit einem anderen Gerät ansteuere, wie z.b. der **Lemke Solitare 12** dann wird genau wie der Kurs ist, rückwärts eingeparkt.

Ist das jetzt ein Bug von AD oder ein Problem von Giants? Da es sich um ein Geräte handelt, welches beim Transport wo anderes angehängt wird, als bei der Feldarbeit.

------
Dear AD Team,
these days I worked with AD to reorganize the machine hall with reverse courses. With **Kverneland Optima RS** we have found and issue.
Now if the tractor will switch to reverse way, the message pops up with AD point reached. with other devices like **Lemke Solitare 12** it works fine. 

Maybe the problem with this device is, that the transport connection is different to the field work connection?
AD problem or from Giants?

------
Hier das Foto falls sich jetzt jemand mit der Bezeichung nicht gerade ein Bild machen konnte:
Picture from the device with issue:
![fs19-kverneland-vicon-equipment-pack-v1-0-3 1](https://user-images.githubusercontent.com/61227831/149893409-96f03138-9645-42f9-9cee-af093f8b0f82.jpg)

**Comment by Axel32019** [comment]
Hallo @theMompfdie Das Gerät ist leider nicht so einfach in den Griff zu bekommen - dafür brauchen wir einige Zeit.
Der Bezugspunkt fürs Rückwärtsfahren kann mit der derzeitigen Funktion nicht bestimmt werden.

**Comment by theMompfdie** [comment]
Ok, alles klar. Jetzt löse ich es mal bis aufweiteres mit einem anderen Spot der nur mit Vorwärts fahren erreichbar ist. Sollte es sich ausgehen das ihr das einbaut/fixed wäre es für den Perfektionisten super.
