### ISSUE TITLE
Abfahrer im Erntermodus

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#256]
Hi, irgendwie habe ich nur Probleme mit AD wo es bei anderen alles funzelt.... :-( 

Meine Felder sind alle Richtig eingefahren, sobald der Abfahrer den Ernter abgetankt hat heißt es das der Abfahrer keinen Weg zum Abfahrer Platz findet. Gehe ich allerdings (dort wo der Abfahrer im Feld steht) vom Erntermodus auf direkten Fahrmodus erkennt er einen Weg zu dem Abfahrer Platz wo er im Erntermodus keinen Weg gefunden hat. SP im übrigen.

**Comment by Natsu83** [comment]
Ja. Das Problem habe ich auch seit der 2.0.0.3. Die 2.0.0.2 funktioniert das noch. Deswegen nutze ich noch die 2.0.0.2

**Comment by BigBlackBahamut** [comment]
Ah, okay. Und ich zweifelte schon an mir :-) Dann hoffe ich mal das es schnell behoben wird. Danke für die schnelle Antwort @Natsu83

**Comment by Axel32019** [comment]
Hallo @BigBlackBahamut , Bitte mal folgende Dateien anfügen: AutoDrive_config.xml, vehicles.xml, log.txt - .xml in .txt umbenennen oder .zip
Auf welchem Feld tritt das auf?

**Comment by BigBlackBahamut** [comment]
[AD_config_vehicle_log.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7891299/AD_config_vehicle_log.zip)
Ich habe mal gerade ein Savegame BackUp genommen. Habe also das gleiche Feld gerade noch einmal versucht wie heute Morgen. Ich hatte es da auf jeden Feld von 1-4 und habe sogar meinen Drescher wieder getauscht von Mod auf Original weil ich dachte das es daran lag, war es aber nicht. 

Anbei die gewünschten Daten

**Comment by Obsiana2019** [comment]
Ich muss mich mal hier auch mal zu Wort melden, habe auch schon gedacht ich bin am verzweifeln das gleiche Problem tritt bei mir auch auf. Egal welche Map. Derzeit auf der Niemandsland mit selbst erstellten Feld.  Abfahrer fährt zum Drescher tankt ab und findet den Weg nicht mehr zum Parken. 

Mit der Version davor gerade getestet, funktioniert es Fehlerfrei.

**Comment by BigBlackBahamut** [comment]
@Stephan-S  @Axel32019 

Hier noch eine komische Sache:

Wenn ich das Rohr ausgefahren habe kommt der Abfahrer an -> Tankt ab. Wenn ich jetzt das Rohr einfahre und weiter dresche bleibt der Abfahrer Regungslos stehen obwohl das Parken im Feld untersagt ist. Fahre ich das Rohr wieder aus kommt der Abfahrer angefahren.

Wenn ich nun aber das Rohr ausgefahren lasse und weiter dresche kommt auch die Meldung das der Helfer keinen Weg findet. 

Also: Rohr raus und nach dem abtanken schnell wieder einfahren = Abfahrer bleibt regungslos stehen und wartet auf den Ruf!

Wenn ich den Abfahrer im Feld nun die Arbeite entnehme mit dem AD und wieder aktiviere (Natürlich Erntermodus) bleibt der Abfahrer auch im Feld stehen und wartet auf dem Ruf. Er fährt einfach nicht vom Feld weil er den Ruf des Dreschers abwartet. War das nicht so das beim neu anwählen der Arbeit der Helfer immer wieder erst zum Sammelpunkt des Feldes fährt?

Es ist so auf eigentlich jedem Feld seit dem letzten Update. Ich habe mal dieses "Fold Implements" deaktiviert weil wegen neu und so, aber da tut sich auch auch nichts.

**Comment by rohne83** [comment]
Das war schon immer so, dass der Abfahrer an Ort und Stelle auf den Ruf wartet, wenn man ihn innerhalb der Feldgrenzen einstellt. Ist ja auch sinnvoll so.
Wobei ich aber nicht weiß, ob das bei deaktiviertem Parken im Feld ebenfalls zutrifft, weil ich das nie so nutzen musste.

**Comment by BigBlackBahamut** [comment]
@rohne83 Bisher war es immer so das er nach dem abtanken vom Feld gefahren ist da es dem Abfahrer versagt worden war im Feld zu Parken. Das habe ich immer bisher so gemacht damit der Abfahrer nicht im Weg steht falls dieser nicht Richtig Platz macht.

Ich werde mal die Feldbegrenzung deaktivieren und schauen ob es mit dem "nicht Parken m Feld" bzw. mit dem Ausfahren funktioniert. Oder mir fällt gerade noch was ein. Ich Teste mal gerade was.

**Comment by BigBlackBahamut** [comment]
Also mal ehrlich, hier auf meine Map geschieht gerade etwas komisches. Der Abfahrer fuhr diesmal vom Drescher weg aber nur weil er die Grenze zum Abladen erreicht hat. Aber er fuhr am Rand des Feldes zu Hälfte ab und dann fuhr der Abfahrer quer über das Feld auf das Andere Feld und dort dann am Feldrand zur Ausfahrt um abladen zu fahren.... Man bekommt das Gefühl das mit dem letzten Update die Fahrstrecken und Abgrenzungen der Felder nicht mehr wirklich erkannt werden.

**Comment by Obsiana2019** [comment]
Ich stelle das bei mir heute nach der Arbeit mal mit der 03er Version nach mit Logfile und gleich danach mit der 2er version und Logfile und hänge das hier mal dran. Scheint wohl nicht so häufig zu sein der Fehler (oder Bedienungsfehler) denn können die Jungs evtl mal drüber schauen.

**Comment by BigBlackBahamut** [comment]
[AD_config_vehicle_log.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7896356/AD_config_vehicle_log.zip)
Mit dem geraden geschriebenen von mir vorgefallenen Fehlverhalten des AD-Fahrers hier noch einmal die frischen Daten.

**Comment by BigBlackBahamut** [comment]
So, ich habe auf Elmcreek gerade noch mal neu angefangen. Die Einstellungen von AD sind die gleichen. Meine Vermutung bestätigt mich (wobei ich betonen möchte das ich nur ein Spieler bin und mit der Materie von AD nicht wirklich was weiß, es ist nur meine Vermutung!): 

Wie weiter oben schon geschrieben hatte ich die Vermutung das mit dem neuen Update von AD die alten Streckendaten nicht verarbeiten kann. Ich werde hier noch einmal die jetzigen Daten bereitstellen. 
[AD_config_vehicle_log Elmcreek neue Karte.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7896776/AD_config_vehicle_log.Elmcreek.neue.Karte.zip)

**Comment by DHempelmann** [comment]
Ich habe das Gleiche Problem. Und zwar habe ich meine Abfahrer auf "Nächstgelegen" eingestellt, um Staus am Anfahrpunkt zu vermeiden. Das ganze Feld ist brav mit einer AD-Strecke umgeben, damit er auch bestimmt was ordentliches findet.
Seit der 3er Version tankt er den Drescher (in meinem Fall Rüben) ab, wartet dann auf Platz und wenn der Rübenernter weit genug weg ist, kommt "hat keinen Weg zu Fxx" gefunden. Obwohl er ja eigentlich gar nicht zu Fxx fahren sollte, sondern zum Abladeplatz. Drücke ich denn einfach auf den AD Startbutton, sucht er sich auch eine Strecke zum Silo und fährt gleich los.

Stelle ich auf "Standard", dann kommt die Fehlermeldung nicht. Dann fährt er Fxx brav an.

**Comment by BigBlackBahamut** [comment]
Okay, ich bin raus. Ich werde zwar weiterhin AD benutzen werde hier aber keine Sachen mehr melden. 6 Tage mit mehreren Meldungen aber keine Antwort nach weiteren 6 Tagen... Privates Leben ist OK, aber eine kleine Antwort wäre nett gewesen.

**Comment by Axel32019** [comment]
Ist in Arbeit....
