### ISSUE TITLE
Kartoffelroder abtanken funktioniert bei mir nicht

### ISSUE THREAD

**Issue by SaschaLie** [Stephan-S/FS22_AutoDrive#258]
Hallo
AD-Vers.2.0.0.3
Roder: Ventor 4150
Tracktor: Fastrac
Anhänger: Fliegl TMK 273
Alles Vanilla

Problem: Der Abfahrer fährt nicht richtig unter das "Rohr" und dann durch.
CP beim Roder; Beim Abtanken stehenbleiben ist bei beiden eingestellt.
Bild1 die Einstellungen zu dem Abfahrer. Abstand zum Rohr bei 3.25m.
Bild2, der Abfahrer kommt, der Roder fängt an abzubunkern.
Bild3, hier fährt der Abfahrer durch.
Bild4, hier mal mit Abstand zum Rohr auf 3,0m. Da bleibt der Abfahrer hängen. Es ist auch so, in Mitte des Feldes, nicht nur hier in der Kurve. Der Abfahrer holt weit genug aus
Hab immer wieder mal alles neu gestartet, Problem bleibt.

Hier die Log zu dem letzten Versuch nach Neustart:
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7896788/log.txt)

![Einst](https://user-images.githubusercontent.com/96572157/150123384-0deefa66-d900-4a5b-bab5-075338af5d65.jpg)
![1](https://user-images.githubusercontent.com/96572157/150123392-9a08eea9-60ea-4ca7-877e-b61dc8f7557f.jpg)
![2](https://user-images.githubusercontent.com/96572157/150123402-2c938218-747a-4e2e-871c-a4e29e0fef48.jpg)
![3](https://user-images.githubusercontent.com/96572157/150123410-303e5216-ba0c-4af6-a7cf-c81fc3416887.jpg)

**Comment by 60erjonny** [comment]
Meine Einstellungen dazu...damit geht es recht gut...
![fsScreen_2022_01_19_17_06_23](https://user-images.githubusercontent.com/63659182/150169466-b38dbd3f-8671-40b2-98b8-dd9a4ea0d020.png)

**Comment by SaschaLie** [comment]
Danke dafür, klappt aber leider nicht. Da will er dann auf die andere Seite fahren. Wieder umgestellt auf +3,0m trifft er mal das Rohr, bleibt aber nicht stehen. Dann trifft er das Rohr wieder nicht.
![4](https://user-images.githubusercontent.com/96572157/150214316-1137935f-521e-4257-a4a1-95b2665dff2b.jpg)

**Comment by Dzi4d3k** [comment]
Am I missing something or is it not possible to start potato harvester in opposite direction to have unloading pipe directed to edge of field not center?

**Comment by SaschaLie** [comment]
The result is the same. I had already tested
![5](https://user-images.githubusercontent.com/96572157/150218722-0ba85711-5dd7-4250-97e8-6a8966e2b69f.jpg)

**Comment by 60erjonny** [comment]
Den Abfahrer auf dem Feld langsamer anfahren lassen...

**Comment by SaschaLie** [comment]
Nichts zu machen. Der Abfahrer hält einfach nicht an. Bei 3m trifft er mal das Rohr richtig, mal zu nah am Roder. Aber er hält nicht an. Selbst mit 10km/h fährt er weiter

**Comment by SaschaLie** [comment]
Gerade noch andere Tracktoren getestet, den Standarthelfer getestet und auch den Roder selbst gefahren. Nichts hilft. Der Abfahrer fährt einfach unterm Rohr durch und weiter.

**Comment by VatriXxX** [comment]
Bei mir funktioniert es ebenfalls nicht, bei mir fährt der Traktor einfach weiter und fährt erneuert an den Kartoffelroder und das immer und immer wieder... https://i.imgur.com/IqSlAP2.mp4
Im Video ist das im Debug Modus zu sehen, denke das könnte weiterhelfen.

**Comment by nimanox** [comment]
bei uns aufn dedi server mit giants helfer funktioniert es auch nicht und hab schon einige einstelung versucht

**Comment by Karre55** [comment]
> Hallo AD-Vers.2.0.0.3 Roder: Ventor 4150 Tracktor: Fastrac Anhänger: Fliegl TMK 273 Alles Vanilla
> 
> Problem: Der Abfahrer fährt nicht richtig unter das "Rohr" und dann durch. CP beim Röder; Beim Abtanken stehenbleiben ist bei beiden eingestellt. Bild1 die Einstellungen zu dem Abfahrer. Abstand zum Rohr bei 3,25m. Bild2, der Abfahrer kommt, der Roder fängt an abzubunkern. Bild3, hier fährt der Abfahrer durch. Bild4, hier mal mit Abstand zum Rohr auf 3,0m. Da bleibt der Abfahrer hängen. Es ist auch so, in Mitte des Feldes, nicht nur hier in der Kurve. Der Abfahrer holt weit genug aus Hab immer wieder mal alles neu gestartet, Problem bleibt.
> 
> Hier sterben Log zu dem letzten Versuch nach Neustart: [log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7896788/log.txt)
> 
> ![Einst](https://user-images.githubusercontent.com/96572157/150123384-0deefa66-d900-4a5b-bab5-075338af5d65.jpg) ![1](https://user-images.githubusercontent.com/96572157/150123392-9a08eea9-60ea-4ca7-877e-b61dc8f7557f.jpg) ![2](https://user-images.githubusercontent.com/96572157/150123402-2c938218-747a-4e2e-871c-a4e29e0fef48.jpg) ![3](https://user-images.githubusercontent.com/96572157/150123410-303e5216-ba0c-4af6-a7cf-c81fc3416887.jpg)

Liegt wohl an der Version 03. hab Stundenlag probiert,-nix.
zum entladen des Kartoffelroders lade ich extra die Version 02, da funktioniert es noch.

**Comment by Karre55** [comment]
Liegt wohl an der Version 03. hab Stundenlag probiert,-nix.
zum entladen des Kartoffelroders lade ich extra die Version 02, da funktioniert es noch.

**Comment by SchwarzschildX** [comment]
Selbes Problem bei mir. Beim ersten mal fährt er gut an aber dann einfach weiter, daraufhin fährt er hinten in den Roder rein und bleibt stecken.
