### ISSUE TITLE
Streckennetz Debug

### ISSUE THREAD

**Issue by Ralf-B** [Stephan-S/FS22_AutoDrive#259]
Hallo AutoDrive Team,
wäre es möglich auch die Enden von Beidseitig befahrbaren Strecken mit in das Streckennetz Debug aufzunehmen, damit solche Stellen leichter zu finden sind.
![Screenshot (2)](https://user-images.githubusercontent.com/54984457/150166441-7e63271d-5c4d-4a3a-af83-89337647ef76.png)
Eine weitere Problemstelle deren anzeige im Streckennetz Debug nützlich wäre, sind Winkel spitzer 90° 
![Screenshot (3)](https://user-images.githubusercontent.com/54984457/150168444-6a913f10-ae72-488b-a522-b905232a090e.png)

AutoDrive Version 2.0.0.3

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
