### ISSUE TITLE
Ballensammelwagen enladen im LS22 

### ISSUE THREAD

**Issue by regs1980** [Stephan-S/FS22_AutoDrive#26]
Wird es dieses mal vielleicht die Option geben oder ist das wieder zu intensive das umzusetzen?

**Comment by Tensuko** [comment]
Da könnte man dann schauen wenn wir den Ballensammelmodus in CP reinbringen, dass man zusammen das Abladen von Ballensammelwagen in AD bringt.

**Comment by regs1980** [comment]
Das wäre das beste was ihr machen könnt, so bleibt CP auf dem Feld und AD auf der Straße, außerdem bräuchten die Leute von CP sich keinen Kopf zu machen, alles was mit Straße zu tun hat und können sich somit mehr auf die Feldarbeit fixieren und auch Zeitersparnis.

**Comment by Stummerl** [comment]
Schließe mich dem an. Wäre Super wenn ihr das mit dem Ballensammelwagen in AD integrieren könntet. Bis zum Entladepunkt würde es ja schon funktionieren
![fsScreen_2022_01_06_16_47_30 (Large)](https://user-images.githubusercontent.com/97124563/148418894-9feb76d5-e743-466d-9ee1-61b06b3850e1.png)
.

**Comment by Carpantus** [comment]
Wenn das ginge währe das super.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
