### ISSUE TITLE
Abfahrer kommt nicht bei eingestelltem Prozentsatz, wenn ich den Drescher selber fahre

### ISSUE THREAD

**Issue by domijo98** [Stephan-S/FS22_AutoDrive#260]
Hallo, bei mir kommt der Abfahrer nicht ab dem eingestellten Prozentsatz, wenn ich den Drescher selber fahre. Wenn der Helfer fährt ist das kein Problem bitte um Rückmeldung
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7899243/log.txt)

**Comment by Iwan1803** [comment]
Das ist normal. Wenn man selber fährt:
- man hält an, fährt das Rohr aus und der Abfahrer kommt
- man aktiviert im Drescher "Aktives Abfahren" und fährt dann das Rohr aus, um den Abfahrer zu rufen
Der voreingestellte Prozentsatz zählt nur für Helfer.

**Comment by domijo98** [comment]
Ok danke für die Rückmeldung. Warum ist das nicht mehr möglich, im 19er ging das noch. Warum ,,sollte'' das nur beim Helfer funktionieren? Ist eine super Hilfe, die man somit nicht nutzen kann :/.

**Comment by Iwan1803** [comment]
Oh, eine Möglichkeit habe ich noch vergessen: du kannst den Abfahrer per frei belegbarer Tastenkombi rufen.
Und ja, man mag es zwar kaum glauben, aber das ist tatsächlich schon in LS19 geändert worden:
https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#megatweak-chopper-and-harvester-unloader-routine-complete-rework

**Comment by domijo98** [comment]
Ja ich weiß, genauso wie es auch übers Rohr funktioniert, aber warum hat man das abgestellt?

**Comment by domijo98** [comment]
Oha dass das schon im 19er geändert wurde bekam ich nicht mit, da es bei mir ja so einigermaßen funktionierte.

**Comment by domijo98** [comment]
Hallo, ich würde gerne wissen warum das oben genannte Feature nur beim Helfer funktioniert und nicht mehr, wenn man selber fährt

**Comment by Iwan1803** [comment]
Wir führen keine Historie, warum wieso weshalb etwas geändert oder hinzugefügt oder rausgenommen worden ist.
In meinen Augen macht es aber absolut Sinn, das ich als Fahrer einer Erntemaschine selber entscheiden kann, wann der Abfahrer kommen soll. Je nachdem, wie ich meine Bahnen fahre, steht er mir sonst möglicherweise im Weg oder fährt durch die Frucht.
Die Möglichkeiten, wie man den Abfahrer rufen kann, wurden ja genannt und daher mache ich hier erstmal zu.

**Comment by domijo98** [comment]
Alles klar danke, wollte das nur wissen 👍
