### ISSUE TITLE
Collision detection on train crossing barriers

### ISSUE THREAD

**Issue by rossc85** [Stephan-S/FS22_AutoDrive#263]
Drivers keep crashing into train barriers and sometimes climb over them resulting in either train hitting them or thy get stuck on barrier when it raises, would be nice if collision detection could be added some point in the future. 
Or even if it could be possible that if train was X distance away and getting closer, they would stop before the barrier so that barrier would not come down ontop of vehicle/load

**Comment by Iwan1803** [comment]
Take a look in here: https://github.com/Stephan-S/FS22_AutoDrive/issues/222
