### ISSUE TITLE
Extra Spur für große Gespanne

### ISSUE THREAD

**Issue by SliderRyder** [Stephan-S/FS22_AutoDrive#264]
Neues Feature?!
Viele LS Spieler kennen es: Autodrive Kurse sind perfekt eingefahren. Die Schlepper fahren perfekt auf der Straße.
Dann kommt ein Mähdrescher und reißt rechts und links alles nieder.

Mein Vorschlag:  So wie es Nebenstrecken, ZweibahnStrecken ,Etc gibt, könnte es doch eine EXTRA BREIT / EXTRA Lang - Strecke geben.
Das würde heißen: 
An Engstelllen, Kurven, Kreuzungen, wo große Fahrzeuge weiter ausholen müssen als Standard Traktoren, könnte man eine ,,EXTRA Breit " Strecke einfahren und im betreffenden Fahrzeug ( eventuell in den Einstellungen)  aktivieren, sodass auch große Gespanne immer zuverlässig am Ziel ankommen.

**Comment by 60erjonny** [comment]
An solchen Stellen würde ich es mal, mit blauen Linien mittig auf der Straße versuchen. Diese dürfen dann von beiden Seiten, nur von einem Fahrzeug befahren werden...und gut ist es ...

**Comment by TobiHH78** [comment]
Sag das mal der KI...

**Comment by 60erjonny** [comment]
Nun und du glaubst, das Zitat: "EXTRA BREIT / EXTRA Lang - Strecke" den KI-Verkehr kümmert...?
Man kann wohl nicht alles haben...schalte den Verkehr aus und du hast Ruhe...:-)

**Comment by Iwan1803** [comment]
Dann kommt der nächste um die Ecke, der noch "EXTRA HOCH / EXTRA SCHWER" und wer weiß was noch möchte...
Und ja, es soll tatsächlich Maps geben, welche einfach nicht für "EXTRA BREIT / GROß / LANG" etc. gemacht sind.
Selbst mit den vorhandenen 2 Streckentypen sind einige schon überfordert und wenn wir da noch mehr einbauen würden, wäre das Chaos perfekt. Davon abgesehen würde sich Wegberechnung enorm verlängern, weil alle Streckentypen ja berücksichtigt werden müssen.
Daher denke ich, das sowas nicht kommen wird.

Btw. wie können Kurse "perfekt" sein, wenn normale Drescher da nicht mal lang kommen?
Wenn möglich, fahre ich Kurse mit GPS und 4,50m Arbeitsbreite ein und selbst da kann es mal passieren, das sich 2 Drescher begegnen und stehen bleiben, um sich nicht die Spiegel abzufahren 😉

**Comment by SliderRyder** [comment]
Ok also baue Linien ja. Die nutze ich auch, sind aber ja nicht die Lösung für mein  beschriebenes Problem. Es geht ja darum, dass ein traktor nicht so weit ausholt wie ein Drescher beispielsweise.
Und ein drescher schert ja auch ,,anders " aus wegen der Hinterachs lenkung.

Und klar der KI Verkehr juckt gar nix das ist mir  bewusst. Den schalte ich sowieso ab, sobald ich autodrive aktiv habe.

Es war ja nur ein Vorschlag mit der extra Spur. Mehr nicht.

**Comment by Iwan1803** [comment]
Es gibt ja ein paar Lösungen und es wird immer wieder auch Map-bedingte "Probleme" geben, aber es kann halt einfach nicht sein, das wir AD ständig um irgendwas erweitern sollen, um sowas zu lösen.
Wir helfen immer gerne und schauen uns auch alles an, aber es gibt halt auch Sachen, wo wir einfach nein sagen müssen.
