### ISSUE TITLE
Double Trailer Getting Stuck with Combine Unload

### ISSUE THREAD

**Issue by hockeyfan2815** [Stephan-S/FS22_AutoDrive#267]
I noticed that when using a double trailer, specifically the Lode King Distinction Super B, and it goes to turn around to line up with the combine to unload it will frequently take such a tight turn that it ties itself in a knot and gets itself stuck.

Thank you though other than that it has been working great for me.

**Comment by dominiczeth** [comment]
This trailer isn't really suitable for unloading on the field. 

Anyway it should use a minimum turn radius for pathfinding on the Field. Just like courseplay, which calculates turns based on turn Radius.

**Comment by Axel32019** [comment]
There will be an improvement in the next release. Please check it out.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
