### ISSUE TITLE
Feature request - Ability to lock AD route creation in multiplayer

### ISSUE THREAD

**Issue by Ginks-dk** [Stephan-S/FS22_AutoDrive#268]
Hello
Would it be possible to add the feature, so it's only Server admins, that can allow route creation on a multiplayer server.

**Comment by Dzi4d3k** [comment]
Please look on:
https://github.com/Stephan-S/FS22_AutoDrive/issues/187
hopefully it will be introduced in future versions.

**Comment by Ginks-dk** [comment]
Thank you, must have missed that, was looking thru the issues channel.
