### ISSUE TITLE
HUD Farben ändern?

### ISSUE THREAD

**Issue by regs1980** [Stephan-S/FS22_AutoDrive#27]
Wie kann man die HUD Farben ändern bezogen auf Symbole und Hintergrund, in welcher Datei kann ich das ändern, so das es eher zum LS22 HUD passt?

**Comment by Stephan-S** [comment]
Die dds Dateien liegen alle im textures Ordner. 
Tob dich gerne damit aus und wenn du etwas feriges teilen möchtest, immer her damit :-)

**Comment by regs1980** [comment]
Bin schon dabei, kein Problem mache ich gern.

**Comment by regs1980** [comment]
Nach ein paar Stunden Arbeit ist dieses Raus gekommen, etwas Farbenfroher und stark angelehnt am HUD vom LS22.

<img width="426" alt="2021-12-19 18_44_20-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/146685245-4b63925b-d1f2-491b-b388-9ef1adebc082.png">


<img width="412" alt="2021-12-19 18_45_35-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/146685249-f34d8803-9287-4989-8784-cb9462779158.png">

<img width="1172" alt="2021-12-19 18_30_57-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/146685254-5229dcfe-a068-4c71-8661-701a32260f9a.png">


[textures.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7741272/textures.zip)

**Comment by Stephan-S** [comment]
Hui, das ging ja richtig schnell! Klasse.
Ich finde es super, dass du die Rahmen und Farben auf das fs22 Blau gebracht hast.
Für mich persönlich ist es etwas zu bunt geworden.
Wenn du mir persönlich einen riesen Gefallen tun möchtest, dann würde ich mir eine Version mit wenig rot/grün wünschen. Ausnahmen wären aktive Prozesse/Einstellungen wie der Editor Modus.

Dann würde ich gerne beide Optionen verbauen und per User setting umschaltbar machen

**Comment by regs1980** [comment]
> Wenn du mir persönlich einen riesen Gefallen tun möchtest, dann würde ich mir eine Version mit wenig rot/grün wünschen

Kein Problem

**Comment by Stephan-S** [comment]
Ah und die Icons sollten alle im BC3 / DXT5 For,mat gespeichert werden, damit es reibungslos läuft und keine Fehlermeldungen dazu gibt.

**Comment by regs1980** [comment]
Perfekt, das wollte ich dich eh noch fragen mit dem Format.

**Comment by Stephan-S** [comment]
Klasse, danke. Wir machen dann damit ne Umfrage im Discord welches wir als Standard nutzen werden. Wenn es sehr uneindeutig wird, werde ich dann sobald ich Zeit habe mal eine  Auswahlmöglichkeit einbauen. Aber das hat noch nicht die höchste Prio aktuell. Erstmal nutzen wir dann ein neues Set von dir :-)
Vielen Dank schon mal!

**Comment by regs1980** [comment]
> Aber das hat noch nicht die höchste Prio aktuell.

Nur mal eine kleine Vorschau, der rec button hat auch schon eine neue Veränderung und die Traktor Symbole sind auch schon mit was neuerem bestückt.

<img width="786" alt="2021-12-22 19_25_59-LS22 Mods" src="https://user-images.githubusercontent.com/13314443/147139655-d1681c42-c7fc-4500-b219-4873da5b2ee6.png">

**Comment by regs1980** [comment]
Finale Version, ich hoffe die ist für jeden akzeptabel.

<img width="787" alt="2021-12-26 00_13_27-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147395602-ab240ab1-316a-4139-9fff-794e2a5db7a0.png">
<img width="725" alt="2021-12-26 00_14_01-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147395603-e70f4825-fba5-457d-becc-cdc8f9aae927.png">
<img width="764" alt="2021-12-26 00_14_27-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147395604-312da3aa-6f7d-47a8-9b58-7625c08f7481.png">
<img width="989" alt="2021-12-26 00_15_06-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147395605-e72209d7-8f43-44e2-9bdd-3640afcaf36f.png">
<img width="922" alt="2021-12-26 00_15_27-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147395607-a32eb5d8-f709-49a5-9afd-6e345eff6093.png">
<img width="959" alt="2021-12-26 00_16_07-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147395608-b75b7968-480b-41d4-b4a7-76f41abbac21.png">

[textures weiß - blau.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7776377/textures.weiss.-.blau.zip)

**Comment by Axel32019** [comment]
Das hat sich mit dem DC voting erledigt.
