### ISSUE TITLE
Line Colour

### ISSUE THREAD

**Issue by Bovrinox** [Stephan-S/FS22_AutoDrive#270]
Hey there, first off top work, this mod is far better than i imagined. Never used it because it seemed to duplicate courseplays function in FS19, but its so much more
I am having a bit of bother just now however, for some reason all routes are showing as a blue line, even the one way routes which should be green. It was working correctly to start with, and I've no idea what caused it to bug out. It may of been something to do with trying to manually place a way point by clicking (cant remember the exact combination to do it).
All it did was give me a big triangle of different coloured blobs, rather than create a waypoint, and i couldnt work out what it was for. After closing the edit mode on the autodrive GUI it caused the game to hang for about 10 seconds, and shortly after that I noticed all lines had changed to blue. 
Any ideas why, and how to revert it back to colour coding the route types? 
Thanks in advance
Bov

**Comment by Dzi4d3k** [comment]
Hi, that might better work to do this offline (off-game) in companion app AD Course Editor:
https://github.com/KillBait/AutoDrive_Course_Editor

**Comment by Axel32019** [comment]
Hello, Please also have a look here: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#new-color-assignment-for-users-with-different-color-perception

**Comment by Bovrinox** [comment]
Im not sure what you are telling me to do here. Ive tried toggling the colour assignment mode option but it still just displays all lines as blue, regardless of it being one or two way. The reverse lines are a different colour, but thats all.

**Comment by Axel32019** [comment]
This: "Reset": restores the original AD color for the selected item (regardless of the selected color waypoint)

**Comment by bojanh66** [comment]
Hello, last time i used Autodrive in FS19 was probably at least 1 year ago.
So today i was trying to record some route in FS22 and suddenly i discovered orange and brown lines ??
Then i read Wiki and i understood correctly:
- green line = orange line
- blue line = brown line
So, orange and brown lines are same as green/blue, just different color for people with eye issue ? They have same function?

**Comment by Bovrinox** [comment]
> This: "Reset": restores the original AD color for the selected item (regardless of the selected color waypoint)

there we go, thanks a lot I've sussed it out now. Took me an embarrassingly long time to realise that if i click on one of the blobs in the triangle it comes up with a list of things, then there's a reset button at the bottom!
Thanks for your help, and your patience!
Bov

PS: Ive also now worked out how to manually add points with the mouse :D

**Comment by Bovrinox** [comment]
> Hello, last time i used Autodrive in FS19 was probably at least 1 year ago. So today i was trying to record some route in FS22 and suddenly i discovered orange and brown lines ?? Then i read Wiki and if i understood correctly:
> 
> * green line = orange line
> * blue line = brown line
>   Correct?
>   So, orange and brown lines are same as green/blue, just different color for people with eye issue ? They have same function?

I think it is something to do with side roads, the orange and brown is counted as a side road and will only be used if it is significantly faster than any main route

**Comment by mfehr94** [comment]
As the wiki said: "Color assignment for users with different color perception"

**Comment by Axel32019** [comment]
From my understanding issue is clarified - closed
