### ISSUE TITLE
Video Autodrive Howto 09 - Fanglinie Feldrand

### ISSUE THREAD

**Issue by TripleX1978** [Stephan-S/FS22_AutoDrive#271]
Hallo Iwan,
Du hast in dem Video den Feldrand mit einer blauen Linie abgesteckt und die Ausfahrten in grün.
Könnte man nicht auch den Feldrand als beidseitig befahrbare Nebenstrecke einfahren um zu verhindern dass die Fahrer über das Feld abkürzen oder könnte das zu Problemen führen wenn Abfahrer das Feld verlassen wollen?

**Comment by Iwan1803** [comment]
Ich habe in dem Video doch erklärt, warum da grüne Linien vom Feld runterführen und warum die Fanglinie blau (=beidseitig befahrbar) ist.
Durch die grünen Linien kann doch keiner drauf fahren und somit muss ich da auch keine Nebenstrecke draus machen.

**Comment by TobiHH78** [comment]
Na ja, man könnte auch die Frage beantworten...Also nein, es führt zu keinen Problemen.
Ich nutze seit jeher beidseitig befahrbare Nebenstrecken als Fanglinie, und das funktioniert einwandfrei.

Halte ich auch für die bessere Variante, weil man die Feldzufahrten dann auch beidseitig befahrbar machen kann. Hat den Vorteil, mehr Möglichkeiten für den Wartepunkt des Abfahrers zu haben.  Mein Wartepunkt geht häufig von der Fanglinie ab, und so hat der Abfahrer mehr Möglichkeiten von jeder Seite des Feldes diesen Punkt auch wieder anzufahren.

Andere Fahrzeuge nutzen diese Strecken wegen der Nebenstrecke nicht, es wird also auch nicht falsch abgekürzt.

Man kann es so oder so machen, aber Probleme machen Nebenstrecken als Fanglinie nicht.

**Comment by TripleX1978** [comment]
Danke für die Antwort @TobiHH78 .

Den Gedanken hatte ich auch verfolgt.

**Comment by Iwan1803** [comment]
In der Frage steht aber nichts von "ich habe den Zielpunkt auf der Fanglinie" 😉
Die Fanglinie soll dazu dienen, das die Fahrzeuge eine koordinierte Abfahrt vom Feld haben. Es wäre eher ungünstig, wenn da ein Abfahrer auf dieser Linie steht, weil da ein Zielpunkt ist und andere Fahrzeuge deshalb da nicht wegkommen.
Was ich mir aber vorstellen könnte, das auf der Fanglinie ein Zielpunkt ist, wo ein Überladewagen dann auf den am Feldzielpunkt wartenden Abfahrer überladt, aber dann braucht man am Überladepunkt einseitige Linien. Schließlich können die ÜLW nur auf einer Seite abladen.

**Comment by TobiHH78** [comment]
Das steht auch in meiner Antwort nicht. Ich bin nur im Gegensatz zu dir auf die ursprüngliche Frage eingegangen.

Die ursprüngliche Frage ob eine  Nebenstrecke als Fanglinie Probleme bereitet, kann man schlicht und ergreifend mit nein beantworten. Sie macht exakt das gleiche wie die blaue Linie. Der Abfahrer sucht sich den nächsten Punkt und fährt dann über die Nebenstrecke vom Feld.
Die Nebenstrecke bietet aber je nach Situation und Map zusätzliche Vorteile.
Ich habe nicht geschrieben, dass der Haltepunkt auf der Fanglinie liegt, sondern **von der Fanglinie** abgeht. Natürlich liegt der Punkt nicht darauf, das wäre in der Tat ungünstig.
Auf großen Feldern bei 4x oder 16x-Karten kann es z.B. sinnvoll sein, auch Haltepunkte auf dem Feld zu haben. Dazu muss der Abfahrer aber natürlich auch auf das Feld auffahren können. Geht bei deinem Szenario nicht.
Fängst du bei einem 80 oder 100 Hektar großen Feld im Westen an, und hast den Haltepunkt des Abfahrers links vom Feld, muss er mit fortschreitender Ernte immer weiter quer über das abgeerntete Feld zum Drescher fahren. Hast du auch Wartepunkte mittig im Feld, kann man, wenn weit genug gedroschen wurde dem Abfahrer den neuen Haltepunkt zuweisen. Erspart viel unnötige Leerfahrten.

**Comment by Iwan1803** [comment]
Schön, das du mehr in den ursprünglichen Post reininterpretierst als dort wirklich steht, denn ich lese nix davon, das auch die grünen Linien durch beidseitig befahrbare ersetzt werden sollen 😉
Das es etliche Möglichkeiten gibt, wie man die Fanglinie auch anderes nutzen und erweitern kann, wurde ja nun ausreichend erörtert.
