### ISSUE TITLE
stoppt AD das funktionieren der Pfeiltasten im CP MiniHuD?

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#278]
Im [CP Github](https://github.com/Courseplay/Courseplay_FS22/issues/489) sind wir draufgekommen, dass unter Umständen die Pfeiltasten links rechts zum bedienen im MiniHud von CP nicht mehr funktionieren.

was reproduzierbar war ist das Ctrl+Alt+UP den Fehler auslöst. Ich bin mir aber sicher dass ich die Tastenkombi nie benutzt habe. 
vielleicht fällt euch ja ein an was das liegen kann.

Das ganze nur als low priority Frage und Querverweis zu sehen, wenn jemand danach sucht

**Comment by Axel32019** [comment]
Diese Tastenkombi scheint in der Engine besonders behandelt zu werden - wird erstmal gelöscht.
