### ISSUE TITLE
Ajuda com CP e AD

### ISSUE THREAD

**Issue by erksartori** [Stephan-S/FS22_AutoDrive#280]
Estou tendo problemas, para reabastecer meus implementos. Tenho rota para o local para reabastecer com sementes, calcário e fertilizantes. porem se o implemento esta no campo Plantando, passando calcário ou passando fertilizante utilizando o CP, assim que acaba , ele para e não vai reabastecer (AD).

Alguém poderia me ajudar a configurar. pois no FS19, a gente colocava no CP para utilizar o AD em conjunto, mas aqui não achei essa opção.

Agradeço desde já a ajuda.

I'm having trouble refueling my implements. I have a route to the site to refuel with seeds, limestone and fertilizer. but if the implement is in the field Planting, passing limestone or passing fertilizer using the CP, so it ends, it stop and will not refuel (AD).

Could someone help me set up. because in FS19, we put in the PC to use the AD together, but here I did not find this option.

I appreciate your help.

**Comment by 60erjonny** [comment]
...so weit sind CP und AD noch nicht...

**Comment by Iwan1803** [comment]
We are working on the communication between AD & CP, but it will take some time.
