### ISSUE TITLE
Anfang

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS22_AutoDrive#282]
Ihr habt stark angefangen, aber genauso schnell nachgelassen!
Ihr: 2.0.0.3 
CP: 7.0.0.21
Früher LS19 gab es mal eine Testversion heute nur noch Release?

Macht weiter so!
Danke

**Comment by Iwan1803** [comment]
Ja, wir machen weiter so wie bisher und wir werden uns auch nicht durch irgendwem hier hetzen lassen. Mit so dummen Sprüchen kannst du uns auch nicht gerade ermutigen.
Schon vergessen? Wir haben hier alle tatsächlich auch noch ein richtiges Leben und machen hier alles in unserer Freizeit.
Du darfst uns aber gerne entsprechend hohe Gehälter zahlen und dann können wir das hier in Vollzeit machen, wenn es dir nicht schnell genug geht 😉
