### ISSUE TITLE
Game Menus stop working

### ISSUE THREAD

**Issue by Bovrinox** [Stephan-S/FS22_AutoDrive#284]
Hi there, 
I have noticed that whilst using autodrive to unload combines (controlled by courseplay) it messes up the game menus. The shop and esc menu stop responding to controller inputs, and sometimes the esc menu seems to open twice, with a slightly offset second one. Unfortunately this breaks the game, as neither of the two duplicate menus can be closed. 
Will try to replicate and provide screen shots

**Comment by Axel32019** [comment]
Hi, Did you start AD with default key cobination CTRL ALT cursor up?
If so, please assign an other key combination.

**Comment by Bovrinox** [comment]
I will have started AD by clicking the little button on the menu that appears when pressing alt 0. Not tested the issue without courseplay, ill play about with it a bit later on this evening and see what happens.

**Comment by Bovrinox** [comment]
slight update, at this point AD just completely breaks the game. If i load with the mod active, it asks me to auto generate routes, but then it wont open the GUI using the alt 0 combination, and also causes the normal game interface to stop working correctly. The mouse cursor disappears. It still highlights things in the keybind screen, but it wont let me actually click on things;

**Comment by Axel32019** [comment]
Please add you log.txt file(s).

**Comment by Bovrinox** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7946444/log.txt)
Is that this one? I could only find one log.txt file, hope it helps!

**Comment by Axel32019** [comment]
Is this log from the issue? I could not see an issue related to AD, but:
- there is/are maps in the mods folder, but you load the FR map <-> FS22_Calmsden -> more than 1 map may cause issues, difficult to find!
Could you give a try to only have AD in mods folder an start your game?

**Comment by Bovrinox** [comment]
the only map i have downloaded is the calmsden one, it doesnt appear in the mod list when loading games not on that map, so it shouldnt be loading more than one. I realise i do have a lot of mods installed, so i will try it with no other mods in the folder rather than just all deactivated and see what happens.
Thanks for your patience

**Comment by Bovrinox** [comment]
as a side note, AD seems to mess with refill triggers for machinery when near refill bags, like seeders, and also for trailers under silo fill points. Have to exit the vehicle and get back in it to activate them. 
It also messes with autoload trailer mods, it just completely removes the functionality of them
. Not sure if it is connected or not.

**Comment by Axel32019** [comment]
What do you mean with "as a side note, AD seems to mess with refill triggers for machinery when near refill bags" - try to refill from big bags?
For "and also for trailers under silo fill points" please add a screenshot, welcome with AD targets visible.
"It also messes with autoload trailer mods" - this is not supported (yet) as it was possible in FS19!

**Comment by Bovrinox** [comment]
Hi there, I will do that now.
Yes, I mean it wont load from big bags, and it wont fill trailers until I park under the pipe, get out the vehicle and get back in. Same for seeders, fertilisers etc when parking near big bags/pallets. Have to leave the vehicle and re0enter it to activate the fill trigger.
![image](https://user-images.githubusercontent.com/63093402/151661074-15070c0f-32b1-4f8b-8262-18813925033c.png)

As for autoload trailers not working - didnt realise it was a known issue, sorry about that, that's fine can work around that no problem.

**Comment by Axel32019** [comment]
This looks like you do not know the basic functions of AD - please consult Youtube!
Here is not the right place to do so.

**Comment by Bovrinox** [comment]
What do you mean? you can clearly see in the top left that fill trailer is not available. I thought it was obvious from my description what is happening. I cannot fill my trailer. I have to get out of the tractor, as in get out and walk about, then get back in it, and it will let me fill the trailer from the silo, without moving the tractor. I would provide a video of this, but I don't know how to. This IS NOT repeat, NOT about getting AD to fill the trailer. It is about doing it MYSELF, which DOES NOT WORK with the AD mod active.
