### ISSUE TITLE
Vehicle specific routes (new feature).

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS22_AutoDrive#285]
Hello autodrive team.
Today came to my head an idea that i wish to know if it would be possible to be done on autodrive, at a late stage of the mod when things are more stable for fs22.....
Considering the amount of maps being now released with some unique features, i was having the idea of making autodrive get a new connection type between nodes that would make that connection vehicle dependant.....
My thought is, the current connection system for all vehicles, then add a connection type for smaller equipment only, excluding trucks, combines and larger tractors, and maybe a 3rd connection but to forbid combines only, due to combines being wider than (most) all other equipment and needing "shortcuts" sometimes

By having this new connection type, and using it on a autodrive network, we players could limit the number of times we get some vehicles stuck, as autodrive, with this feature implemented, could send a warning when we  try to start the course saying that the equipment is not recommended or allowed for the destination point (because the destination is accessed through a "small vehicle network" only, or a combine cant reach a point because that point is accessed by a "forbidden combines network" only). Adding to this concept, it would help also to create some shortcut networks for smaller equipment through buildings and other tight places, maybe even through some farm gates, while bigger equipment could still be allowed into main roads.

Would this be something possible to do? Is it worth to give it some moments of thought?
What you guys think of the idea, before going into the technical thinking of it? :p
thanks in advance, and keep going the great work.

**Comment by Iwan1803** [comment]
There have been similar requests a few times.
It makes AD unnecessarily more complicated and would slow down the route calculation a lot.
