### ISSUE TITLE
Abfahrer beim häckseln

### ISSUE THREAD

**Issue by Holzotte** [Stephan-S/FS22_AutoDrive#288]
Hallo an die Modder,

erstmal Danke für eure Arbeit die ihr in Autodrive investiert das wir User  unseren Spaß mit dem Spiel haben. 👍🏻👍🏻👍🏻

Mir ist eine Kleinigkeit beim spielen aufgefallen, ich weiß nicht ob es ein Bug ist oder ob es an meinen Einstellungen für den Abfahrer liegt. Und zwar ist es so das ja immer der Abfahrer  als erstes gewählt wird der dem Ernter am nächsten ist. Beim mir ist es so das das nicht funktioniert, sobald ich eine 90 Grand wende fahre, fährt der Abfahrer rückwärts vom Feld und bleibt da stehen. Nach einiger Zeit fährt dann der Abfahrer los der am Startpunkt steht obwohl dieser weiter weg ist als der andere Abfahrer.

Ich hoffe ihr könnt mir da weiterhelfen.

Danke im vorraus

**Comment by Speedyls19** [comment]
Das Problem hab ich leider auch konnte es aber bisher noch nicht lösen mit anderen einstellungen

**Comment by Klaus-Willy** [comment]
Ich auch habe das gleiche Problem - auch bei der 180 wende wechselt ständig der Abfahrer und es dauert sehr lange bis es weiter geht.
Ansonsten mega Arbeit die ihr leistet!

**Comment by Joko-Ger** [comment]
Hallo zusammen,
ich habe das gleiche Problem. Sobald der Häcksler am Ende des Feldes eine 180°-Wende macht, bleibt der eigentliche Abfahrer stehen (Statusmeldung: Warten auf Ruf), obwohl er noch nicht voll ist, und es wird ein neuer Abfahrer gerufen, der am Wartepunkt am komplett anderen Ende des Feldes steht.
Kann es sein, dass es hier eine Einstellung im LS19 gab, dass der Häcksler der nähesten Abfahrer rufen soll?

Ansonsten macht AD das Spiel so ungemein besser, vielen Dank dafür!

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
