### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS22_AutoDrive#289]
ich kann bei AD im Editormodus kein Wegpung verschinen so wie ich das von ls 19 kenne ich benuze die Version 2.0.0.4.RC
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7944673/log.txt)

**Comment by RealNeo80** [comment]
rechte maustaste und verschieben ... geht bei mir

**Comment by Natsu83** [comment]
Falls du die aktuelle Vesion von CP nutzt: Ändere mal die Mausbelegung für CP. Hier beißt sich derzeit CP mit AD, die beide die rechte Maustaste belegen.

**Comment by Tensuko** [comment]
Normale Belegung für AD ist mittlere Maustaste.
Wer beides auf die gleiche Taste legt muss sich nicht wundern.
AD mittlere, CP rechte Maustaste.
Mit beiden Mauszeigern lassen sich die beiden HUDs komplett bedienen, was die Wegpunkt von AD an geht, habe ich nicht probiert, hier muss offenbar die AD Maus benutzt werden.
Getestet mit CP 7.0.0.23 und AD 2.0.0.3

**Comment by Natsu83** [comment]
Warum auch immer: Bei mir lag CP auf der rechten Maustaste in der aktuellen Version, ohne dass ich zuvor was an der Bindung was verändert habe. Aber mir ist eben aufgefallen, dass auf einmal mehrere Sachen doppelt belegt waren und gebissen haben. Möglich, dass da irgend ein anderes Mod reingehauen hat.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
