### ISSUE TITLE
Bale unloading plans? 

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS22_AutoDrive#290]
Hey guys. Seems CP is bringing option for bale collect/wrap in fieldwork operations.
I know integration between 2 mods is not yet functional, but would it be possible to make the tractor able to unload the trailers with a normal "deliver" course?
I think both Anderson and arcus in bale trailers use the Y key to unload them, once to put it on unload position, and a second time to actually unload the bales, then a 3rd time to set it back to transport position.
Once the integration is implemented, would be nice to set it as pickup and deliver mode, but instead of selecting a loading point, we would select a marker next to the field, and once vehicle arrives at it, would pass operations to CP so it would resume the fieldwork operations until it gets the trailer full, then CP would pass operations again for AD to let it drive to unload bale trailer.
Hope I'm making sense of the suggestion.
Thanks in advance for help :)

**Comment by rohne83** [comment]
Pickup&deliver would be the correct mode for this, as this basically exactly the same scenario as for a loading wagon. Most of it is working already now. Only thing missing for that to work completely without babysitting is that AD recognizes the bale fill level and the bale trigger at the unloading station.

**Comment by Tensuko** [comment]
For unloading stacks in reverse, a bale detection is needed so the unload will be moved forward.
Should not be to hard with a raycast.

**Comment by fudoido** [comment]
> Pickup&deliver would be the correct mode for this, as this basically exactly the same scenario as for a loading wagon. Most of it is working already now. Only thing missing for that to work completely without babysitting is that AD recognizes the bale fill level and the bale trigger at the unloading station.

yes i also think it would be the best mode. apart from what you said, it will also need a new function keypress, since the bale wagons unload feature is with key Y and is a 3 step process (unloading position, unloading process and transport position), opposite to normal trailer where it is a 2 step process with I key Once to unload, once to close/lower trailer for transport). dont think that will be the major issue, the harder part might be detecting the fill levels.

> For unloading stacks in reverse, a bale detection is needed so the unload will be moved forward. Should not be to hard with a raycast.

i been playing now on county lane map and fortunately the map has a straight pass unload trigger. issue here will be to make the trailer dump the bales in the exact spot, but dont think it is hard if normal trailers usually stop the end of the trailer right where the trigger marker is.

**Comment by Axel32019** [comment]
@rohne83 @Tensuko If it is so easy, PR welcome!

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
