### ISSUE TITLE
AutoDrive beim Tanken blockiert alle Fahrzeuge

### ISSUE THREAD

**Issue by kroddn** [Stephan-S/FS22_AutoDrive#291]
[log-2022-01-27.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7948561/log-2022-01-27.txt)

Moin zusammen. 

Wir haben heute zum zweiten Mal nen Bug auf unsere Dedicated Server, wo wir AutoDrive als Verursacher vermuten.
* Wir haben ein Dieselfass platziert und einen Wegpunkt dort rein gesetzt. 
* Wenn man nun ein Fahrzeug zum Tanken schickt (ich hab mir das mit STRG+ALT+T belegt), dann fährt das Fahrzeug los, bleibt 10 Meter vorm Dieselfass stehen. 
* Danach lassen sich **KEINE Fahrzeuge mehr bewegen**. 
* Wenn man das Fahrzeug vorm Tank resettet, dann wird das Fahrzeug am Shop geklont. Der Bug bleibt.
* Abhilfe scheint nur Server Restart zu bringen. Neues Verbinden zum Server reicht nicht.

Das Log zeigt (keine Ahnung ob's von AD kommt):
```
2022-01-27 08:42 Error: Running LUA method 'update'.
dataS/scripts/objects/LoadingStation.lua(257) : bad argument #1 to 'min' (number expected, got nil)
```

**Comment by kroddn** [comment]
We used the Diesel Tank from https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=157276

**Comment by Axel32019** [comment]
Moin,
Danke @kroddn für's rauskopieren aus dem log, da wunder ich mich schon das das Spiel überhaupt noch zuckt bei den vielen Fehlermeldungen.
Der genannte Tank ist ein 19er, aber wir kennen den Fehler schon: #262
Daher mach ich hier zu.
