### ISSUE TITLE
[Feature request] AD Menu mit Controller Steuerbar

### ISSUE THREAD

**Issue by BeckerCodeing** [Stephan-S/FS22_AutoDrive#292]
Hallo zusammen,

erstmal vielen dank für diese geniale Mod.

Da ich hin und wieder gerne per Steam Link per Controller auf dem TV spiele, was auch gut funktioniert wenn die wege bereits eingefahren sind, ist mir aufgefallen, dass man das Menu von AD (nicht das schnellmenu) nicht mit dem Controller bedienen kann. Mann kann nicht durch die Optionen innerhalb des Menus springen, da default mäßig kein Menupunkt ausgewählt ist (aufleuchtet).

Wäre es möglich, das AD Menu mit dem Controller bedienbar zu machen?

Mit freundlichen Grüßen,

Marcel

**Comment by BeckerCodeing** [comment]
Es lässt sich auch mit der Tastatur nachstellen. Das Standard menu lässt sich auch mit den pfeiltasten bedienen, das der Mod leider nicht, weil es keine makierung im menu gibt wenn man in das menu kommt.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
