### ISSUE TITLE
Abfahrer abtanken 

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#295]
Hallo
Was muss ich einstellen damit der Abfahrer beim Abtanken schneller fährt, weil wie auf den Bild zu sehen kann er leider nicht abtanken
![Abfahrer](https://user-images.githubusercontent.com/47453761/151592383-f599b041-d87c-4d92-a8aa-ca46b8eaa0be.png)

**Comment by Natsu83** [comment]
Dürfte nichts mit der Geschwindigkeit zu tun haben, sondern weil CP und AD noch nicht auf einaner optimiert sind. Mal funktioniert das Abtanken beim Fahren, mal nicht. Soweit ich das sehe, liegt das daran, dass die Abfrage der Rohrposition bei AD in Verbindung mit CP noch nicht sauber läuft. Die Optimierung wird gerade nach und nach implementiert. Da solltest du etwas Geduld haben.

**Comment by RealNeo80** [comment]
ich sage dem drescher im moment immer dass er stehen bleiben soll, dann funktioniert das abtanken normal reibungslos.
@Natsu83 das will ich auch testen, ich glaub aber das nur starten und stoppen von CP grad integriert ist

**Comment by Natsu83** [comment]
Also in der Dev funktioniert das Abtanken während der fahrt. Er positioniert sich in der tat mittiger, so dass auch kurzzeitige Geschwindigkeitsunterschiede ausgeglichen werden können.
