### ISSUE TITLE
Automatische Shopauswahl lässt sich in "Abladen" nicht de- und aktivieren

### ISSUE THREAD

**Issue by Clouseau219** [Stephan-S/FS22_AutoDrive#297]
Hi,

habe festgestellt dass sich die automatische Shop Auswahl im "Abladen" nicht de- und aktivieren lässt, geht nur über "Abholen und Abliefern" und wenn dort aktiviert ist es aber auch im Abladen aktiviert.  Wenn man es im Abladen de- oder aktivieren will muss man erst wieder ins andere Menü wechseln und dann wieder zurück.
Ist das so gewollt?

Grüße,
Clou

**Comment by Axel32019** [comment]
Hi @Clouseau219 , Ist nicht so sinnvoll, wird geändert.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
