### ISSUE TITLE
Server Warnungen 

### ISSUE THREAD

**Issue by andremeyer123** [Stephan-S/FS22_AutoDrive#3]
Top Mod  3 Warnungen auf einem Server 
Unknown file type '.vscode/settings.json'
Unknown file type 'README.md'
File count per store item too high. 330 found (max. 128)

**Comment by Bandesss** [comment]
Lösche doch die Readme, dann hast nur noch 2 Fehler 
Wobei die Storeanzahl kannst vergessen, das ist kein Fehler einfach nur ein Hinweis :)

**Comment by andremeyer123** [comment]
Ist nur als Hinweis gedacht, dass diese Sachen nix machen weiss ich selbst . :D

**Comment by Iwan1803** [comment]
Da sind dem guten @Stephan-S wohl 2 Dateien mit in die Zip reingerutscht, welche da nicht drin sein sollten 😉
Wie schon gesagt wurde, sind das Hinweise aber keine wirklichen Fehlermeldungen und daher zu vernachlässigen.
Aber danke für den Hinweis, wir werden da beim nächsten Release besser drauf achten.

**Comment by andremeyer123** [comment]
File count per store item too high. 330 found (max. 128) 
diesen Hinweis gibt es noch

**Comment by Iwan1803** [comment]
Ja und den wird es auch noch länger geben und er hat immer noch keinerlei Auswirkungen.

**Comment by andremeyer123** [comment]
ja und was ist das für eine art zu antworten habe niemals gesagt das dieser Hinweis etwas auslöst oder  ?
ich berichte nur was noch zusehen ist .

**Comment by Iwan1803** [comment]
Wir können und werden die Anzahl an Dateien nicht mal eben schrumpfen, nur damit dieser Hinweis auf Servern nicht mehr angezeigt wird.
Daher stelle ich mir einfach die Frage, was du mit der erneuten Meldung bezwecken möchtest, vor allem wenn dir bekannt ist, das es kein Fehler ist.

**Comment by andremeyer123** [comment]
Man möchte nach einem Update euch nur sagen es ist noch einer da wenn ihr nichts haben möchtet einfach löschen und gut ist.
