### ISSUE TITLE
Filltrigger Kollision 

### ISSUE THREAD

**Issue by MADxHAWK** [Stephan-S/FS22_AutoDrive#30]
Autodrive kann keine Förderschnecke (Meridian TL 12-39) als Ladepunkt anfahren.
Autodrive scheint den Ladetrigger der Förderschnecke als Kollisionsobjekt zu erkennen und stoppt vor dem Förderband, obwohl genügend Platz ist, sowohl seitlich als auch unter der Förderschnecke. 
Genutzt wird ein standar John Deere 6250R und die Standard Förderschnecke aus dem Spiel

**Comment by Axel32019** [comment]
Irgendwie ist hier wohl meine Erklärung nicht gespeichert worden:
Da existiert eine Kolli die von der Engine generiert wird - derzeit keine Möglichkeit dies zu vermeiden.
Diese Kolli  führt dazu das Förderbänder nicht durchfahren werden können, sowohl von AD als auch vom AI-Helfer, manuell aber schon.
