### ISSUE TITLE
Frage zum Abfahren

### ISSUE THREAD

**Issue by Zwoxlol** [Stephan-S/FS22_AutoDrive#300]
Kann mir jemand sagen was ich falsch mache?

https://streamable.com/h1iif6  (Video ist leider zu groß)

Ich will das er an der Seite stehen bleibt, bis die Erntemaschine 100% voll ist in dem fall. (habs auch it 95% versucht aber klappt nix)

**Comment by Iwan1803** [comment]
Mach mal ein Update auf 2.0.0.4, da einiges bzgl. Roder & Co. verbessert worden ist.

**Comment by Zwoxlol** [comment]
> Mach mal ein Update auf 2.0.0.4, da einiges bzgl. Roder & Co. verbessert worden ist.

Oh wow ich hab gar nicht gesehen das heut ein neues update kam. Werds gleich probieren

**Comment by Natsu83** [comment]
Sieht so aus, als würde die Maschiene Courseplay nutzen. Die Einstellungen für das Abfahren der Erntemaschiene müssen in der Erntemaschiene vorgenommen werden. In der Erntemaschiene die AutoDrive-Einstellungen öffnen und auf das Dreschersymbol klicken. Dort dann den gewünschten Wert einstellen. Auf keinen Fall auf über 90% gehen, da CP sich ab 95% zum Abtanken hin stellt und nicht mehr weiter fährt. 99% ist der maximale Füllstand, den Courseplay zulässt. Also musst du auf 90% stellen. Und du solltest in den Dreschersetting bei Autodrive auch das "Aktives Abfahren" deaktivieren. 
Um Sicher zu gehen, dass er dann wirklich nur abtankt, wenn er steht, musst du im Drescher bei den Coursplay dan "Beim entladen stehen bleiben" aktivieren.

**Comment by Zwoxlol** [comment]
> 

Danke! Hab nicht gesehen das es eigenständige Drescher settings gibt. Hab mich die ganze zeit gewundert warum der bei 50% auf dem Feld rum fährt

**Comment by Natsu83** [comment]
Ja. Ist ein bischen verwirrend. Das Reguläre "Abladen ab Level" bezieht sich nur auf reine Bunkerfahrzeuge, Überladewagen und Anhänger. Bei Erntemaschienen muss dies über die Dreschereinstellungen vorgenommen werden, da dieses Setting eben für die Kommikation zwischen AD und CP verantwortlich ist. Über dieses Setting erfolgt der Ruf zum Abtanken.
