### ISSUE TITLE
CP Zeichen taucht nicht auf  

### ISSUE THREAD

**Issue by stefan10921** [Stephan-S/FS22_AutoDrive#302]
hallo ich suche und suche ich finde das CP zeichen nicht habe von allem das neuste eiso Von CP und AD die neuste version 

In meinem video zeige ich es https://youtu.be/B5Nf4KmYBnQ 

Danke im Voraus

**Comment by RealNeo80** [comment]
das ist autodrive 2.0.0.3 --- CP gibt es erst ab 2.0.0.4

**Comment by Axel32019** [comment]
Frage beantwortet -> closed
