### ISSUE TITLE
Streckennetz anzeigen auf Karte im Editor Modus

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS22_AutoDrive#303]
Die Idee mit dem Streckennetz anzeigen ist ja nice, aaaaber könnt ihr das auf die rechtsklick Funktion legen (Strecke zeigen ohne Editor) und nicht auf den Editor Modus, (links klick) ich hatte es heute eingeschaltet und die karte mit linker Maus hin und her gezogen, dabei hab ich irgendwo was angeklickt auf der AD Strecke hinter dem Map Bild , quasi einen Bubble aktiviert, ich schließ mal nicht aus das man den auch verschieben kann beim Map anschauen

LG TImmi

**Comment by SaschaLie** [comment]
Habe das auch bemerkt. Beim Karte verschieben habe ich mehrere Punkt-Anklick-Sounds bemerkt und unfreiwillig eine neue Punktverbindung geschaffen.

Gruß, Sascha

**Comment by Axel32019** [comment]
Hallo @timmi4026 , Ich schätze Du kannst die Änderung selbst mal einbauen oder die dev Version probieren :-)
