### ISSUE TITLE
Kollisionserkennung mit geschlossenem Bahnübergang

### ISSUE THREAD

**Issue by lutzemai** [Stephan-S/FS22_AutoDrive#304]
Hey,
ich habe aktuell kein offenes Thema zu dem Punkt gefunden. Aber AutoDrive hat wohl aktuell keine Kollisionserkennung mit einem geschlossenen Bahnübergang. Er fährt einfach drüber -> Ergebnis siehe nachfolgende Abbildungen

Grüße

![20220131073356_1](https://user-images.githubusercontent.com/98731693/151749858-1675ae5e-85a5-4f47-a6d4-3fe096ec162c.jpg)
![20220131073407_1](https://user-images.githubusercontent.com/98731693/151749861-4da4fc12-9b91-4f8e-be1d-b09f5127292d.jpg)

**Comment by lutzemai** [comment]
Hey,

noch etwas zur Info. Ich habe im Bereich des Bahnüberganges einen einzelnen in beide Richtungen befahrbaren Hauptweg erstellt, um Kollisionen mit anderen Fahrzeugen oder breitem Gerät zu vermeiden. Das immer nur 1 Fahrzeug über den Bahnübergang fahren kann. 
Dieser verläuft mittig auf der Straße. Kann es eventuell daran liegen, dass er dann vielleicht geschlossende Schranken nicht richtig erkennt?

Grüße Vorab & ein dickes Lob an die Modersteller für die super Arbeit.. :-)

**Comment by RealNeo80** [comment]
#176

**Comment by lutzemai** [comment]
Danke @RealNeo80 . Hab die kollisionswarnung aktiviert und auf 1,5m gestellt. Jetzt funktioniert es
