### ISSUE TITLE
Small problem destination points

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS22_AutoDrive#305]
After updating to the latest release, perhaps also because I had used test versions to download manually, double destination points were automatically waxed or referred to the positionable, for example, the loading point at the sugar factory, I created it double a few points later, in the path, as in other cases, and it took place when the "load and deliver" started.
I discovered and had to delete all the files and folders, present in the "Autodrive" folder present in the mygames / famrmingsimulator22 folder. in doing so, everything was settled.
I hope it is a random problem, it happened to me, but in case I hope it can be useful to others who have the same or similar problems.

**Comment by Axel32019** [comment]
see #239

**Comment by Iwan1803** [comment]
Seems like you didn't read the linked issue complete...
If the color of the trailor in front of the target point is blue, AD will select the best target itself (best price for selling/buying).
A click on the trailor icon will change the color to white and AD will drive then to the selected target.
So please check the color of the trailor icons.

**Comment by Axel32019** [comment]
no feedback -> closed
