### ISSUE TITLE
CP wird gestoppt wenn in AD das Ziel geändert wird, warum?

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#306]
mit welchen Hintergrund wird der Aktive CP Job beendet, wenn ich das Ziel ändere?

bei mir passiert es immer wieder dass ich beim drescher vergesse das ziel umzustellen und den CP job schon gestartet hab. wenn ich Nun das Ziel ändere schmeißt mir AD den CP job raus

2022-01-31 12:38   Info: [AD] 533351 CH7.70: AutoDrive:StopCP...
2022-01-31 12:38   Info: [AD] 533351 CH7.70: AutoDrive:StopCP - cpStartStopDriver

**Comment by hermannbrauer** [comment]
Hey,
@Iwan1803 hat das ausführlich erklärt ;)
https://youtu.be/jz1u4Weg2XY?t=561
Gruß

**Comment by Iwan1803** [comment]
Weil AD an der Stelle davon ausgeht, das der CP-Job erledigt ist, wenn man das obere Ziel ändert.
Schick mal einen Grubber per AD und aktiviertem CP zum Feld und schau dann mal am Ende nach dem CP-Button.
Richtig: der ist immer noch aktiv und wird automatisch deaktiviert, wenn du das AD-Ziel änderst.

**Comment by RealNeo80** [comment]
ja du darfst ja den CP button deaktieren, das is wurscht, aber du sollst mir den Job nicht abbrechen, den ich nicht mal über AD gestartet hab. Das eine hat nix mit den anderen zu tun, Wenn ich das Ziel ändere darfst du gerne Starten mit CP ausschalten, aber nicht den CP Job der gerade aktiv ist

**Comment by Iwan1803** [comment]
Wenn du AD nicht zum Starten von CP genutzt hast, warum hast du den Button dann überhaupt deaktiviert? 🙄

**Comment by RealNeo80** [comment]
nein der button ist nicht aktiv, er stoppt mir aber den CP Job

**Comment by Iwan1803** [comment]
@Axel32019 bitte mal prüfen, denn er dürfte CP ja nur stoppen, wenn der CP-Button auch aktiv ist.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
