### ISSUE TITLE
Loading and delivery. the driver pours grain into the silo 

### ISSUE THREAD

**Issue by azbest1992** [Stephan-S/FS22_AutoDrive#307]
Sorry for my bad English.
When I set up a job for transporting grain from the silo to the chicken house, the driver fills the trailer, then drives forward a bit and unload the grain back into the silo. Next he drive to chicken house and wait some time there with empty trailer and back to silo, load grain and unload. This happens in all silos that have a loading pipe above the chute. So both are default from the game (Unia and Neueron). I did not notice this problem when transporting grain from the silo to the collection point.

**Comment by RealNeo80** [comment]
have you load and unload correct? can you show a screen?

**Comment by azbest1992** [comment]
He load grain to full there. 
![Load](https://user-images.githubusercontent.com/74253047/151803045-6cadcc99-fcc7-43fb-83f2-2031e6fe2c71.jpg)
Next worker go forward, stop, and unload grain.
![Unload](https://user-images.githubusercontent.com/74253047/151803057-a70c9ecb-a964-4d4d-888c-2310857d9dbd.jpg)
In FS19 i don't have problem like that. Could this be because the marker is slightly offset and when the worker moves forward, the rear of the trailer hits the chute?

**Comment by Axel32019** [comment]
Could you please move the point "Silos zaladunek" ~ 5 ... 10 m forward.
Check the setting max trigger distance, this seems to be to high. The driver think he is already at unload position.
Try 10 or 25

**Comment by azbest1992** [comment]
> Could you please move the point "Silos zaladunek" ~ 5 ... 10 m forward. Check the setting max trigger distance, this seems to be to high. The driver think he is already at unload position. Try 10 or 25

Oh my God... Thanks you. Max trigger distance was problem. I use 50m. Now i have 10m and work great.
