### ISSUE TITLE
[BUG_SP] Rotierendes Entladen benutzt nur den ersten eingestellten Entladepunkt

### ISSUE THREAD

**Issue by bmsbwd** [Stephan-S/FS22_AutoDrive#308]
Beim Gras abfahren in Kombination mit CoursePlay wird vom AD-Abfahrer immer nur an der ersten Stelle im Silo entladen. Also in dem unten bebilderten Fall nur auf "BGA - Silo li -1".

![Einstellung](https://user-images.githubusercontent.com/10153289/151816127-7eea1483-c4f5-45b3-8bb0-35b38f7ca525.jpg)

![Entladepunkte](https://user-images.githubusercontent.com/10153289/151816132-816a332d-16e7-4c4d-8e7e-4e97502f60b7.jpg)

![Silo](https://user-images.githubusercontent.com/10153289/151816134-b75e0d22-19be-4061-9033-c65811a306e0.jpg)

Sorry, sehr großes Log. Dafür vollständig. ;)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7971702/log.txt)

**Comment by bmsbwd** [comment]
Huh?! Jetzt hab ich nen zusätzlichen 2. Fahrer auf den gleichen Auftrag geschickt mit Entladepunkt 4 als Startpunkt und nun machen sie was sie sollen.
Ist rotierend Entladen nur mit mehreren Abfahrern möglich? Dann hab ich da das Prinzip nicht verstanden und das issue kann geschlossen werden. Sorry.

**Comment by Axel32019** [comment]
Rotierend entladen funktioniert auch mit 1 Fahrzeug. Bitte mal log mit Debug Pfadfindung aktiv anfügen.

**Comment by bmsbwd** [comment]
Ich kann den fehler leider nicht mehr reproduzieren. Also entweder hab ich mich irgendwo vertan oder AD hat sich nur verschluckt. Sorry.
