### ISSUE TITLE
Feld verwechsellung

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#309]
Moin
Ich fahre auf der Elmcreek (Erweiterung auf große Fläche) mit Autodrive 2.0.3
Ich habe den Abfahrer auf Feld 12 eingestellt er fährt aber zu Feld 3 und bleibt dort stehen
Wo dran liegt das
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7973439/log.txt)

**Comment by Axel32019** [comment]
Hallo @Hendirk ,
Hinweis: FS22_AutoRepair-master ist eine falsche zip-Datei.
FS22_Calmsden ist eine Map - Du verwendest jedoch die Elmcreek, diese daher aus dem mods Ordner entfernen! Mehrere Maps verursachen Fehler die sehr schwer zu finden sind!
FS22_NF_Marsch_oG was ist das denn? Siehe vorher!
Irgendwas stimmt hier ganz und gar nicht, geladen wird noch eine ganz andere Map:
2022-01-31 19:19   Info: [AD] Map title: CreekHawk-Farm
2022-01-31 19:19   Info: [AD] Parsed map title: CreekHawk-Farm
Das kann so also nicht funktionieren, aufräumen ist angesagt!

**Comment by Hendirk** [comment]
So ich hab nochmal aufgeräumt
Bei der Ceparsten Karte CreekHawk Farm sind mehrere Felder zu ein paar großen Feld zusammen gelegt, und da dachte ich das die eingefahren Kurse von der standard Creekhawk Farm passen würden
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7973739/log.txt)

**Comment by Axel32019** [comment]
Wenn ich das jetzt richtig verstanden habe, verwendest Du ein Streckennetz für eine originale Map mit einer veränderten und wunderst Dich das die Zielpunkte nicht passen?
Das Streckennetz muss schon zur Karte passen, AD passt da nichts an!
Das ist kein AD Bug.
