### ISSUE TITLE
Automatic course generator

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS22_AutoDrive#31]
It took me a while to figure it out, but on small streets the automatic course generator overlaps two one way lines (green) on the exact same spot, instead of generating one two way line (purple). I think you already know that, but since it isn't mentioned here, i just wanted to put it into the record.

Oh, and btw, thank you for your great work with this project.

**Comment by Pcab59** [comment]
Bonjour, 
Le générateur automatique duplique plein de lignes aux carrefours. plusieurs points non connectés.
Se déclenche au lancement d'une partie solo, pas en multi.

**Comment by Iwan1803** [comment]
Bitte 2.0.0.1 ausprobieren und sollte der Fehler wieder auftauchen, dann bitte ein neues Issue aufmachen:
*Please try 2.0.0.1 and if the error reappears, please open a new issue:*
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.1
