### ISSUE TITLE
Mehrfaches  Ein/Ausschalten bis Start

### ISSUE THREAD

**Issue by Voodooman1968** [Stephan-S/FS22_AutoDrive#311]
Hallo und erstmal Danke denn mit der 2.0.0.4 läuft erstmal viel worauf ich gewartet habe.Es fällt mir aber auf das ich nach einer Weile beim Aktivieren der Fahrzeuge diese nicht starten.Erst nach meist 3x Ein/Auschalten von AD fährt das Fahrzeug auf den geplanten Kurs los. Optisch gibts da auch eine Auffälligkeit denn im Schlepper z.B. sitze ich und wenn er dann startet sitzt ein Helfer drin und er fährt los.
Vielleicht gibts da ja eine Lösung  Danke Gruß Voodooman

**Comment by Iwan1803** [comment]
Bitte ein vollständiges Logfile anhängen, wenn dies wieder passiert, danke!

**Comment by Voodooman1968** [comment]
Herzlichen Dank für die Zeit und Antwort.Ich habe mal so einiges bereinigt fast alle Mods ausgeschaltet ,brachte aber nix und danach wieder angeschaltet.Doch habe ich eine Auffälligkeit. Immer wenn es passiert kommt "Error running LUA method "MouseEvent" .Hab natürlich gegooglt aber meist nur ältere Kommentare gefunden die keine Lösung brachten.Ich sende erstmal ein Sreenshot mit (werde auf alle Fälle noch ein Logfile posten) Wollte schon mal die Eckdaten posten:
Karte Haute Beyleron AD Version 2.0.0.4 CP Version 7.0.0.25.   Fehler ist nicht Fahrzeugspezifisch kommt immer mal sporadisch.
Bis auf den Grimme Varitron 470-Terra Trac (Kartoffelernter) da geht nix mehr also Ruf der Abfahrer geht nicht usw. Habe den aber gegen den anderen Grimme ausgetauscht der läuft einwandfrei.Vermutlich hängt das mit ausfahren des Rohres zusammen, was der 470er nicht hat.........Naja ich bin geduldig und werde nochmal ein Log machen denke der Fehler liegt irgendwo bei mir. Danke fürs Lesen Grüße Voodooman 
![Lua-01 02 22](https://user-images.githubusercontent.com/98675207/151985039-744ad642-2f3f-419c-bf5e-1d5251704e22.png)

**Comment by Axel32019** [comment]
Hallo @Voodooman1968 , Der 470er hat nur einen Entladestatus "unloading="1"". Das ist nicht so gängig, aber ich hab eine potentielle Verbesserung gefunden.

**Comment by Voodooman1968** [comment]
Das hört sich ja schon mal gut an. Der Ventor 4150 hat das große 30er Feld in HB komplett mit 2 Unimogs 1600 geerntet und abgefahren ohne einen Fehler. Mit dem 470er war das erst als AD 2.0.0.4 aktiv war. Vorher ging das, ist aber nicht weiter tragisch. An der Mouse Event Sache bin ich noch dran. Ich will das noch genauer lokalisieren.

Danke und Grüße Voodooman

**Comment by Voodooman1968** [comment]
Hallo nochmal ,habe gerade nochmal etwas experimentiert.Wenn ich zur Werkstatt fahre (ich weiß sehr viele Fahrzeuge nur zum Test) und ich in die Nähe des Einstiegstriggers komme kann ich nicht mehr ins Fahrzeug einsteigen. die Maussteuerung dreht total durch und ich drehe mich um die eigene Achse. Nur ein Tab bzw ESC hilft. Laufe ich wieder hin geht es von vorn los.
Rote Meldung anbei. zu dem Fehler mit dem Mouse Event kann ich noch sagen das wenn ich AD zum Fahren aktiviere, geht der Helper nicht in Betrieb erst nach 2-3x an und ausschalten. Sollte ein Log helfen bitte benachrichtigen Danke Euch vielmals Grüße Voodooman
![Lua-2](https://user-images.githubusercontent.com/98675207/152250055-c9937585-e509-4c3b-ae9b-81bd3709c780.png)
.
