### ISSUE TITLE
INFO: AD lines not visible, only on helper HUD

### ISSUE THREAD

**Issue by nfd4611** [Stephan-S/FS22_AutoDrive#312]
Not sure what has happened, but suddenly I can no longer see the route lines in edit mode in world as seen in this screenshot
![fsScreen_2022_02_01_01_33_01](https://user-images.githubusercontent.com/98712616/151929866-f29f2110-892c-4e9b-bb5a-bc82f74f0f94.png)
 but can clearly see the generated course lines in the map...
![fsScreen_2022_02_01_01_34_46](https://user-images.githubusercontent.com/98712616/151929974-9cb26340-41dc-46bc-a9ce-90bf25ab2153.png)
the only mods active in this save are AD and CP, any ideas?
Here's my log
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7976683/log.txt)

**Comment by nfd4611** [comment]
map is Elm Creek, but have this issue in all maps.

**Comment by hermannbrauer** [comment]
versuch mal die rechte STRG Taste damit kannst du Punkte ausblenden mit der ALT GR ging auch etwas, nur das habe ich jetzt nicht im Kopf und kann auch nicht testen

**Comment by Iwan1803** [comment]
@nfd4611 did you change something in the graphic settings or added new mods?

**Comment by Darkfaer666** [comment]
Ich habe das gleiche Problem, vor dem update auf 2.0.0.4 lief alles super,

**Comment by nfd4611** [comment]
I@Iwan1803 this is a fresh save, no waypoints set. no new mods added. only mods active are the latest versions of AD and CP

**Comment by Iwan1803** [comment]
A fresh savegame? Did you run the autogenerator to create a road network or maybe copied a config to the savegame?

**Comment by nfd4611** [comment]
ran the autogenerator, that's the lines on the map, but still can't see them in world

**Comment by hbgaming** [comment]
> Not sure what has happened, but suddenly I can no longer see the route lines in edit mode in world as seen in this screenshot ![fsScreen_2022_02_01_01_33_01](https://user-images.githubusercontent.com/98712616/151929866-f29f2110-892c-4e9b-bb5a-bc82f74f0f94.png) but can clearly see the generated course lines in the map... ![fsScreen_2022_02_01_01_34_46](https://user-images.githubusercontent.com/98712616/151929974-9cb26340-41dc-46bc-a9ce-90bf25ab2153.png) the only mods active in this save are AD and CP, any ideas? Here's my log [log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7976683/log.txt)

**Comment by hbgaming** [comment]
I'm have the same  issue

**Comment by Darkfaer666** [comment]
hier mal die screens  aus der console

![image](https://user-images.githubusercontent.com/12968078/152024840-e8dc3b50-50a3-47aa-8d66-c6bd0f784b96.png)
![image](https://user-images.githubusercontent.com/12968078/152024911-3ca8805f-7a1c-480b-a9d7-fff25a145778.png)

**Comment by Darkfaer666** [comment]
okay, meinerseits ist der Fehler behoben, ich weiss nicht ob es anderen auch hilft, aber wenn ihr über Steam spielt, dann deaktiviert bitte unter Startoptionen wenn eingetragen   -disableShaderCompiler.

dann läufts. (zumindest bei mir) 
![image](https://user-images.githubusercontent.com/12968078/152111367-165f7712-fb72-44e7-b15e-abccd1717bb1.png)
![image](https://user-images.githubusercontent.com/12968078/152111420-720f8298-6953-4b9d-93cf-4c56b3879614.png)

**Comment by nfd4611** [comment]
well, glad someone found a solution, but doesn't help me. I don't have anything entered in the start options of Steam, I'm not that advanced in using commands so I don't mess with those settings.

**Comment by Iwan1803** [comment]
Start the game, load your savegame, wait 2 minutes, close the game complete and then upload the log here.

**Comment by nfd4611** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7987809/log.txt)
here's my log

**Comment by Axel32019** [comment]
> [log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7987809/log.txt) here's my log

Hint: - at least 2 Maps in mods folder: FS22_Calmsden, FS22_Frankenmuth_Map

With so many mods it is hard to say what happen. Please try an empty save game only with AD!

**Comment by nfd4611** [comment]
Heading out to work, so won't be able to try this until tomorrow.

**Comment by nfd4611** [comment]
Just got home. Removed all mods except AD and CP, started a fresh save and ran the autogenerator. Same results, can't see the autogenerated tracks in world but they are present on the map view.

Here is the log
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7994173/log.txt)

**Comment by nfd4611** [comment]
Just to add, I imported in a  route network into my save and AD drives the routes perfectly, I just can't see the route network in game while in edit mode.

**Comment by Axel32019** [comment]
@nfd4611 I tried to reproduce with the same steps. My log look nearly the same and everthing is find, except some graphics settings, status messages are different. May be this cause the issue.
Please try some different graphic resolutions, game profiles i.e. Medium, low etc.

**Comment by nfd4611** [comment]
fixed it... did some searching and apparently there are some issues with the latest NVIDIA drivers and FS22, reverted to an earlier version of the drivers and had to change the renderer from DirectX12 to DirectX11 and that fixed the issue. Thanks for the help.

**Comment by Iwan1803** [comment]
Really? It's a driver problem and also one of DirectX?

**Comment by nfd4611** [comment]
it would appear so

**Comment by Dzi4d3k** [comment]
@Iwan1803 
Can you change issue name to something more meaningful, as it is pinned now.

**Comment by LuxVsNox** [comment]
Ich habe dasselbe Problem.  Die habe schon andere Graka Treiber installiert, aber immer noch keine Besserung. Wie kann ich auf DirectX11 wechseln? 
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10067846/log.txt)

**Comment by mas1701** [comment]
> Ich habe dasselbe Problem. Die habe schon andere Graka Treiber installiert, aber immer noch keine Besserung. Wie kann ich auf DirectX11 wechseln? [log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10067846/log.txt)

Since no one has posted the solution yet, I'll do so, even if this is an old question:

Look for game.xml within you personal Documents folder, subfolder "My Games\FarmingSimulator2022".
Edit file with notepad, notepad++ or any other "dumb" plain-text editor. Do not use Word or something similar.
Find this line:

`<renderer>D3D_12</renderer>`

and change to

`<renderer>D3D_11</renderer>`

and save your changes. Done! You may start / restart FS22.

I'm on D3D_11 also, on Nvidia RTX 2080 SUPER. D3D_12 causes crashes.

--

Da noch niemand eine Antwort gegeben hat, mache ich das mal, auch wenn es eine alte Frage ist:

Schaue nach der game.xml in Deinem persönlichen Dokumenteordner, Unterordner "My Games\FarmingSimulator2022".
Bearbeite die Datei mit Notepad, notepad++ oder einem anderen "dummen" nur-Text Editor. Kein Word o.ä. benutzen.

Schaue nach dieser Zeile:

`<renderer>D3D_12</renderer>`

und ändere sie wie folgt

`<renderer>D3D_11</renderer>`

und speichere Deine Änderung. Fertig! Du kannst LS22 wieder starten / neustarten.

Ich nutzte auch D3D_11, mit einer Nvidia RTX 2080 SUPER. D3D_12 crasht dauernd.
