### ISSUE TITLE
AD-Abfahrer setzt nach Abtanken nicht zurück

### ISSUE THREAD

**Issue by McBenzer** [Stephan-S/FS22_AutoDrive#315]
Abfahrer fährt setzt nicht zurück nach beenden des Abtankens:

![image](https://user-images.githubusercontent.com/96957355/151966580-e87d3675-4140-4076-9734-4bf749785f96.png)

Vorheriges Abtanken, Abfahrer setzt zurück:

![image](https://user-images.githubusercontent.com/96957355/151966830-d0d9676f-878a-458f-8ce6-43ef733613ce.png)

**Comment by McBenzer** [comment]
[log_01_02_22.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7978352/log_01_02_22.txt)

**Comment by Axel32019** [comment]
Für oberes Bild bitte Abtanken lassen, dann Screenshot anfügen.

**Comment by McBenzer** [comment]
Ist nach dem Abtanken, die Animation läuft anscheinend länger. 

Abtanken läuft:
![image](https://user-images.githubusercontent.com/96957355/152035294-ac18d0f8-70ca-4a70-9b02-6a01ce3f87ed.png)

Abtanken ende:
![image](https://user-images.githubusercontent.com/96957355/152036027-5c3ef6d5-830e-4076-b7a7-a8f106d0b04a.png)

Und das obere Bild im Startpost ist direkt im Anschluss und es ändert sich nichts mehr, bis der Drescher los fährt.

**Comment by FarmerMario** [comment]
Hallo,
Bei mir war die Situation,der Drescher wird kurz vor Ende eine Bahn abgetankt.Der Abfahrer steht in der Frucht.
Bleibt stehen und wartet auf Platz. Der Drescher wendet und es kommt zur Kollision oder es bleibt alles stehen.
Also, das wäre besser,daß der Abfahrer zurück setzt, um sich selber Platz zu schaffen und dann kann er die Frucht verlassen.

mfg Farmer Mario

**Comment by Axel32019** [comment]
Ist der Drescher beim weiter arbeiten mit dem Abfahrer kollidiert?

**Comment by Axel32019** [comment]
> Hallo, Bei mir war die Situation,der Drescher wird kurz vor Ende eine Bahn abgetankt.Der Abfahrer steht in der Frucht. Bleibt stehen und wartet auf Platz. Der Drescher wendet und es kommt zur Kollision oder es bleibt alles stehen. Also, das wäre besser,daß der Abfahrer zurück setzt, um sich selber Platz zu schaffen und dann kann er die Frucht verlassen.
> 
> mfg Farmer Mario

Das ist ein anderes Thema - bitte wenn notwendig separaten issue aufmachen!

**Comment by FarmerMario** [comment]
Hallo Stephan,Axel,

 

Ja,er arbeitet weiter.Entweder fährt er weiter und schiebt den Abfahrer vor sich her, bis dieser sich dann ausschaltet.

Oder, der Abfahrer hat vermeintlich Platz gefunden,fahrt am Drescher vorbei.Dieser fahrt weiter und verhakt sich dann mit dem Schneidwerk im Hänger.

 

Ich werde versuchen die Situationen wieder hervorzurufen und Screenshots im Github posten.

 

mfg FarmerMario

 
 

Gesendet: Mittwoch, 02. Februar 2022 um 18:20 Uhr
Von: "Axel32019" ***@***.***>
An: "Stephan-S/FS22_AutoDrive" ***@***.***>
Cc: "FarmerMario" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [Stephan-S/FS22_AutoDrive] AD-Abfahrer setzt nach Abtanken nicht zurück (Issue #315)


 

Ist der Drescher beim weiter arbeiten mit dem Abfahrer kollidiert?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by McBenzer** [comment]
> Ist der Drescher beim weiter arbeiten mit dem Abfahrer kollidiert?

Das ist so korrekt. Hatte das gestern extra getestet, von ich glaube 7 mal Abtanken im 1. Vorgewende ist der Drescher 3 mal in den Abfahrer gefahren, weil dieser stehen geblieben ist und 4 mal hatte der Abfahrer zurückgesetzt.

**Comment by Axel32019** [comment]
@McBenzer Bitte mal Debug Externe Schnittstelle aktivieren und log anfügen.

**Comment by FarmerMario** [comment]
Ja,das war auf den Feldbahen.Drescher wurde abgetankt,wartet bis Drescher gewendet hat und wurde von diesem

vor sich hergeschoben oder gerammt.

 

 

Gesendet: Mittwoch, 02. Februar 2022 um 22:52 Uhr
Von: "McBenzer" ***@***.***>
An: "Stephan-S/FS22_AutoDrive" ***@***.***>
Cc: "FarmerMario" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [Stephan-S/FS22_AutoDrive] AD-Abfahrer setzt nach Abtanken nicht zurück (Issue #315)


 


Ist der Drescher beim weiter arbeiten mit dem Abfahrer kollidiert?


Das ist so korrekt. Hatte das gestern extra getestet, von ich glaube 7 mal Abtanken im 1. Vorgewende ist der Drescher 3 mal in den Abfahrer gefahren, weil dieser stehen geblieben ist und 4 mal hatte der Abfahrer zurückgesetzt.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FarmerMario** [comment]
Zitat:"Bitte mal Debug Externe Schnittstelle aktivieren und log anfügen."

 

Weiß nicht wie oder was damit gemeint ist. :(

 
 

Gesendet: Mittwoch, 02. Februar 2022 um 23:05 Uhr
Von: "Axel32019" ***@***.***>
An: "Stephan-S/FS22_AutoDrive" ***@***.***>
Cc: "FarmerMario" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [Stephan-S/FS22_AutoDrive] AD-Abfahrer setzt nach Abtanken nicht zurück (Issue #315)


 

@McBenzer Bitte mal Debug Externe Schnittstelle aktivieren und log anfügen.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Axel32019** [comment]
> Zitat:"Bitte mal Debug Externe Schnittstelle aktivieren und log anfügen."   Weiß nicht wie oder was damit gemeint ist. :(     Gesendet: Mittwoch, 02. Februar 2022 um 23:05 Uhr Von: "Axel32019" ***@***.***> An: "Stephan-S/FS22_AutoDrive" ***@***.***> Cc: "FarmerMario" ***@***.***>, "Comment" ***@***.***> Betreff: Re: [Stephan-S/FS22_AutoDrive] AD-Abfahrer setzt nach Abtanken nicht zurück (Issue #315)   @McBenzer Bitte mal Debug Externe Schnittstelle aktivieren und log anfügen. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

@FarmerMario siehe hier: https://www.youtube.com/watch?v=AjeZ-scB0Vk

**Comment by Axel32019** [comment]
Das hat jetzt aber geklappt, oder?

**Comment by McBenzer** [comment]
Nein, der Drescher ist in den Abfahrer gefahren, weil der Abfahrer sich nicht bewegt hat, erst nach dem der CP Helfer wegen Blockierung die Arbeit eingestellt hat.

**Comment by Axel32019** [comment]
Vermutlich hab ich's gefunden, muß noch getestet werden...

**Comment by McBenzer** [comment]
Okay, danke. Ich teste es im neuen Releas noch mal.

**Comment by Gariot** [comment]
Passiert immer noch mit Tandem Anhaengern. Wenn der AD Abfahrer in den zweiten Anhaenger laed faehrt er danach nicht mehr rueckwaerts und der Drescher faehrt ihm natuerlich dann rein.
