### ISSUE TITLE
Target not selectable any more

### ISSUE THREAD

**Issue by kroddn** [Stephan-S/FS22_AutoDrive#316]
We are using AD on a Multiplayer game.

Steps to reproduce
* Delete a waypoint that containts a target
* Add a new waypoint "McCain Abladen"
* Try to select "McCain Abladen" out of the liste => dropdown stays empty
* Add another waypoint "Test 2"
* Try to select "Test 2" out of the list => dropdown stays empty
* Try to select "McCain Abladen" out of the list => now works
* Try to start AutoDrive with "McCain Abladen" selected => tries to drive to "Test 2"!

When restarting the server, the game does **NOT start:**
```
2022-02-01 21:42 Error: Running LUA method 'packetReceived'.
C://gameservers//s1436926//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Manager/GraphManager.lua:432: attempt to index a nil value

```
[AutoDrive_config.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7981879/AutoDrive_config.zip)

![image](https://user-images.githubusercontent.com/63540443/152049280-9d49268a-67dc-4d4f-84b1-21fe6603a593.png)

![image](https://user-images.githubusercontent.com/63540443/152049622-492606f4-6517-4dfe-870c-197c9092213d.png)

**Comment by Axel32019** [comment]
Hallo @kroddn , Unser MP Server läuft leider im Moment nicht. Würdest Du bitte mal mit Version 2004 testen ob das Problem noch da ist, wir hatten da was geändert.

**Comment by kroddn** [comment]
Wir haben auf 2004 upgraded, haben aber weiter Probleme. Der letzte AD gesetze Wegpunkt funktioniert nicht. Am WE schau ich mir alles noch mal genauer an.

**Comment by kroddn** [comment]
Zum thema MP Server: wir haben nen Experimental Server laufen. Das savegame ist grad auf unseren prod Server umgezogen. Ich kann euch Zugang zum Server geben. 

PM im Discord?

**Comment by kroddn** [comment]
Noch eine weitere Erkenntnis: heute hatte ich ein ähnliches Problem, dass ich ein Ziel ausgewählt habe (F117) und in der Fehlermeldung allerdings "Kein Weg zu 3_1 gefunden" angezeigt wurde. Deaktivieren der Debug-Wegpunkte hat in dem Fall Abhilfe geschafft.

**Comment by Iwan1803** [comment]
Ist das Problem mit der aktuellsten Version präsent?
Ich konnte das gerade auf meinem Dedi nicht nachstellen.
