### ISSUE TITLE
Augerwagon spec not recognized as a load trigger

### ISSUE THREAD

**Issue by jobyrns72** [Stephan-S/FS22_AutoDrive#318]
Hi there I wanted to bring attention that the augerwagon trailers dont get treated as a trigger again. For example a seed tender to fill a seeder. The seeder slows down and drives underneath the auger it starts to load but doesnt stop and keeps going to the load point.
Heres and example of the auger wagon
[https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=230224&title=fs2022](url
![fsScreen_2022_02_01_19_45_23](https://user-images.githubusercontent.com/4283225/152082029-5613198e-1169-4e04-9583-e2edc01096f0.png)
)

**Comment by Axel32019** [comment]
Hi @jobyrns72 , Could you please provide a link to the seeder - it does not look like standard ingame, right?

**Comment by jobyrns72** [comment]
You are correct it is not. I'll get you a link tonight and will also try a standard seeder as well but I believe it will be the same problem. This seeder stop fine at a buy seed trigger perfectly fine.

**Comment by Axel32019** [comment]
In such case(s) the trigger size(s) do matter very much, also fill speed, drive speed etc.
Thats why we need the details of the machines to look deep inside...

**Comment by jobyrns72** [comment]
Just Tested with the ingame Kuhn Venta 4030 seeder and the same result. Tractor slows down and opens lid and drives under augerwagon. The Augerwagon starts to dump into seeder but tractors just drives on to target point

**Comment by Axel32019** [comment]
Here is no bug with AD, more a mod issue:
- the augerwagon need power to fill something, i.e. a tractor running on it is required -> new in FS22
- the fill has to be selected at the augerwagon - AD could not select the required fill for the seeder
- the animation, start of filling is to late so AD could not detect it - the seeder already passed before filling started

We can not reduce the speed in AD as it is already often claimed AD drives to slow to find loading point.
At the moment we are not able to solve this scenario, may be in future.

**Comment by jobyrns72** [comment]
Understandable I have a work around til then I'll just have the fertilizer trailer in front at one dump point and have the auger wagon running on a course that stops at a point where the spout will be over the seeder when the seeder reaches his point
