### ISSUE TITLE
AutoDrive funktioniert nicht

### ISSUE THREAD

**Issue by RudiBergfeld** [Stephan-S/FS22_AutoDrive#319]
Hallo,
ich habe ei Video von Mario Hirschfeld gesehen das CP und AD im 22 Schon wieder zusammenarbeiten wie so geht das bei mir nicht ?
Ach so ich benutze die neusten Versinonen von AD und CP die auf Github zu haben sin
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7987922/log.txt)
d

**Comment by hermannbrauer** [comment]
sicher das dein AD geladen wird???

"Error: Invalid mod name 'FS22_AutoDrive2.0.0.4'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit"

**Comment by Iwan1803** [comment]
Warum benennt man Mods um? Man sollte eh immer nur eine Version im mods-Ordner haben.
Lösch die ganzen AutoDrive-ZIPs aus deinem mods-Ordner raus und dann lad die hier runter, ohne sie irgendwie umzubenennen: https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.4/FS22_AutoDrive.zip
