### ISSUE TITLE
Just a Question: How to add target in directory

### ISSUE THREAD

**Issue by MrsJessica92** [Stephan-S/FS22_AutoDrive#32]
Hey,
erstmal danke für den echt guten Mod. Ich hab den schon im LS19 geliebt.

Ich wollte mir gerade meine Zielpunkte erstellen, nach dem generieren. Ich hab in den Settings gesehen man kann jetzt ordner machen und habe mir auch einen mit dem Namen "Felder" angelegt - jetzt ist es ja so, dass neue Zielpunkte im Standard erstellt werden.

Meine Frage wäre jetzt: WIe kann ich die, in den Ordner schieben bzw. erstellen? Oder geht das Ingame gar nicht?

**Comment by bjt3833** [comment]
when in the autodrive edit mode in game, you can click and drag the targets from the default folder to another folder while the target list is open.

**Comment by Iwan1803** [comment]
Wie schon gesagt:
im Editor-Modus den Zielpunkt mit der linken Maustaste greifen und dann einfach auf den Ordnernamen ziehen.
Dieser wird dann bläulich markiert und der Zielpunkt dort einsortiert, wenn man die linke Maustaste loslässt.

**Comment by MrsJessica92** [comment]
Danke :3
