### ISSUE TITLE
automatisches Nachfüllen von Saatgut ohne Dünger nachzufüllen Amazone Citan

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#320]
Hallo Zusammen,

gibt es die Möglichkeit dass ihr auswertet ob in der Sämaschine in CP die Düngefunktion eingeschaltet ist oder nicht?
Ich habe gerade mit der Amazon Citan gesät, und da hat er mir beim Auffüllen vom Saatgut auch den Düngertank vollgemacht, was ja grundsätzlich ok ist, wenn die Düngefunktion eingeschaltet ist. Bei ausgeschaltetem Dünger sollte er sich aber nur aufs Saatgut beschränken beim auffüllen

**Comment by Axel32019** [comment]
Hallo, Ich nenn das mal "Luxusproblem" - Du verlierst ja nichts.

**Comment by RealNeo80** [comment]
würde ich auch als "Luxusproblem" behandeln

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
