### ISSUE TITLE
AutoDrive und Dedi

### ISSUE THREAD

**Issue by EnMBlacky** [Stephan-S/FS22_AutoDrive#321]
Hallöle,

kann mir jemand sagen, wie wir es hinbekommen das erstellte Routen usw. auf dem Dedi mit ALLEN Spielern Synchronisiert werden ? oder ist das (noch) nicht möglich ?

Grüße & einen schönen Abend

**Comment by EnMBlacky** [comment]
Hmm das tut Sie aber mein Zocker Kollege sieht in seinem AD Fenster nur ein Route, sonst aber nichts.

**Comment by Iwan1803** [comment]
Wie nur eine Route?

**Comment by EnMBlacky** [comment]
Okay hat sich soeben erledigt, mein zocker Kollege hat mich falsch verstanden. Aber wenn wir schon dabei sind, ich habe heute Mittag LS22 gespielt, gespeichert und Offline gegangen, vor einer Stunde habe ich meinem Kollegen die neue AD 2.0.0.4 eingespielt, er hat sich als erstes auf dem Server eingeloggt und danach ich (ich hatte die neue Version seit gestern) und alle erstellten Routen waren, ich musste erst auf ein altes Savegame (Backup) zurückgreifen um damit alles wieder beim alten war. Kann sich das jemand erklären wie das zustande kommt ?

**Comment by Iwan1803** [comment]
Das wird es vermutlich aufgrund des Serverneustarts nicht mehr geben.

**Comment by EnMBlacky** [comment]
Nach den logs schau ich später, sollte nichts mehr vorhanden sein und der Fehler nochmal vorkommen, werde ich die Logs umgehend hier Posten bevor ich irgendwas anderes mache 😀

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
