### ISSUE TITLE
Error LUA 

### ISSUE THREAD

**Issue by vSoRx** [Stephan-S/FS22_AutoDrive#322]
Hallo, ich habe einen LUA gefunden. 

Und zwar wenn ich einen Miststreuer und/oder Güllefass am Trecker habe und ich AD zum Feld fahren lasse und AD soll dann an CP weiter geben um zu düngen, dann macht er das alles wunderbar. Wenn der Miststreuer/Güllefass leer ist und er zum Aufladepunkt fährt dann haut mir AD oder CP das weiß ich nicht wer das genau macht von den beiden einen LUA Error in die log die wie folgt aussieht "Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/AIJobVehicle.lua(480) : attempt to index local 'currentHelper' (a nil value)" die kommt aber NUR wenn die Einstellung von AD "wenn Silo leer" "warten" eingestellt ist und ich an der Gerätschaft vorbei laufe und/oder per taste TAB auf das Gespann wechsle. Ansonsten läuft alles wunderbar :) 
(habe auch bis jetzt nur diesen Fehler gefunden ^^ )

Mods die ich benutzt habe: AD 2.0.0.4 , CP 7.0.0.25 und PowerTools aus dem modhub um das ganze ein bisschen zu beschleunigen. 

Fahrzeuge die ich benutzt habe: Vanilla 

Mfg 

vSoRx 

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7989295/log.txt)
 
Edit: habe festgestellt das es nicht nur beim warten ist sondern beim allgemein befüllen mit AD und Säen oder Düngen mit CP selber. Der Fehler kommt auch nur wenn ich direkt an der Befüllstation stehe und der Helfer das gerät auffüllen möchte.

**Comment by Axel32019** [comment]
Versuchen das Problem zu finden, jedoch fehlt die Doku im SDK.
