### ISSUE TITLE
Spiel lädt nicht weiter als 85%

### ISSUE THREAD

**Issue by Kjeldar01** [Stephan-S/FS22_AutoDrive#323]
Hallo,
ich habe nur AD im Modordner und mein Spiel hängt sich bei 85% während des ladens auf.

Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/Nutzer/Documents/my games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Specialization.lua:216: attempt to compare number with nil
,sagt das Log.

**Comment by RealNeo80** [comment]
ich kenn das problem von CP, hast du gerade upgedated? https://github.com/Courseplay/Courseplay_FS22/issues/710
schau mal ob das hilft, deaktiveren und aktivieren von Autodrive. Speicher dir aber deine Autodrive_config und AutoDriveUsersData aus deinem Savegame. die hat er bei mir das letzte mal verloren als ich AD deaktiviert hatte

**Comment by Kjeldar01** [comment]
Alles schon versucht. Ohne AD läuft alles. CP, Mods etc. . Sobald AD aktiviert ist hängt es sich auf.

**Comment by Axel32019** [comment]
Hallo @Kjeldar01 , Das komplette log bitte hier anfügen, Auszüge helfen uns nicht!

**Comment by Iwan1803** [comment]
Mal CP auf .25 aktualisieren, in der es angeblich gefixt ist: https://github.com/Courseplay/Courseplay_FS22/releases/download/7.0.0.25/FS22_Courseplay.zip
Falls das nicht hilft, brauchen wir das komplette Log.

**Comment by Kjeldar01** [comment]
Vergesst alles. 
Habe komplett neu angefangen (ohne vorher CP drin zu haben) und es läuft.
