### ISSUE TITLE
Create a AD task similar to Combine unload

### ISSUE THREAD

**Issue by schwyl** [Stephan-S/FS22_AutoDrive#324]
Hi There,

Right now I have a course built through CP. I have a route built to my field through AD with a waypoint on the field thats close to the first waypoint of the CP course. 

Would it be possible to modify the combine unload task and turn it in to a drive to and execute task.?

For Instance have the waypoint Call Field 1 Start. Have that selected as the target. Once the worker arrives there it executes the CP course assigned to that machine. Upon completion it executes the deliver to task?

**Comment by Axel32019** [comment]
Hi, 
No, I see no real chance to implement something like this:
How many variations of AD modes are possible? We will not implement something for 1 special scenario, makes no sense.

**Comment by schwyl** [comment]
But it wouldn't be for one scenario.

**Comment by Iwan1803** [comment]
Since no further feedback -> closed!
