### ISSUE TITLE
Editormodus, Punkte verschieben bei Linienhöhe über Fahrzeug

### ISSUE THREAD

**Issue by MudgeO** [Stephan-S/FS22_AutoDrive#325]
Ich bin mir nicht 100% sicher, aber ich meine in der FS19 Version war es möglich, das wenn man Punkte über Fahrzeug anzeigen lässt, diese mittels rechter Maustaste verschieben konnte auch wenn man den unteren "Anfasspunkt" benutzt. Fand/Fände ich sehr hilfreich gerade beim Ausrichten unter Hallen oder Bäumen ...

**Comment by Axel32019** [comment]
Wenn Punkte über Fahrzeug eingeschaltet, sind nur diese verschiebbar, nicht mehr die unteren. Das war schon immer so, da sonst das "Greifen" eines Punktes zu frickelig wird.
