### ISSUE TITLE
Abfahrer wartet CP Turn nicht ab

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#326]
leider keine logs von der Externen Schnittstelle, da ich es erst gesehen habe wies schon fast zu spät war.

Das Problem ist das der Abfahrer schon angefangen hat zu fahren als der Drescher noch auf der langen Seite war,
wie der Drescher dann gewendet hat sind die genau zusammengetroffen

das ist leider der 2. screen, da hatte ich die schon auseinandergefummelt

![image](https://user-images.githubusercontent.com/8066324/152341996-cd1dff78-9e30-49a1-88cd-c3cbfa3b04a0.png)

**Comment by Iwan1803** [comment]
Es wird immer mal Situationen geben, wo sie sich begegnen werden und ganz besonders in den ersten 1-2 Vorgewendebahnen, wo nun mal wenig Platz ist. Irgendwo muss der Abfahrer (je nach Einstellungen) ja nun mal lang fahren, um zum Ernter zu kommen.
Davon abgesehen steht der bei dir ja nun auch in einer echt "bescheidenen" Position 😉

**Comment by RealNeo80** [comment]
nein, der stand da nicht und kam von rechts und wollte abgetankt werden. Dann hat er gedreht und der Abfahrer wollte vorne vorbei weil er ja auf die Rechte Bahn zum Abtanken wollte

Ihr kriegt doch normal von CP die Info das der gerade dreht. kann man da nicht schauen dass der Abfahrer weit genug weg ist? bei mir passiert es in 5 von 10 Fällen dass der Abfahrer beim Anfahren in den Drescher kracht weil der nicht mehr an der Position ist wo der Abfahrer zum abtanken hinwill. 

Normal müsste der doch dynamisch seinen Standpunkt melden und der Abfahrer drauf reagieren. So in der Art einen Abfangkurs generieren

**Comment by Zwoxlol** [comment]
> Es wird immer mal Situationen geben, wo sie sich begegnen werden und ganz besonders in den ersten 1-2 Vorgewendebahnen, wo nun mal wenig Platz ist. Irgendwo muss der Abfahrer (je nach Einstellungen) ja nun mal lang fahren, um zum Ernter zu kommen. Davon abgesehen steht der bei dir ja nun auch in einer echt "bescheidenen" Position und möchte dazu auch noch abgetankt werden (Rohr ist draussen) 😉

ist bei mir bei mir nach den vorgewendebahnen passiert

**Comment by RealNeo80** [comment]
das passiert bei mir überall, ob vorgewende, oder bahnen, wenn der Drescher wendet, bevor der Abfahrer ihn erreicht hat gibts 80% nen crash

**Comment by RealNeo80** [comment]
scheint mit 2.0.0.5 RC wirklich besser zu sein, ich teste das mal weiter

**Comment by RealNeo80** [comment]
@Axel32019 

ich denke das das eher hier dazu passt wie im anderen Thread:

Ich habe eben gesehen wie das zustande kommt. Ursache war das der Drescher über der Frucht abtanken wollte. Sprich er hat das Rohr über der Frucht ausgefahren und der Abfahrer hat wieder den Zielpunkt in der Frucht berechnet. Da ist er dann auch hingefahren. Währenddessen hat der Drescher gewendet - Abfahrer ging in den Modus "Drescher wenden lassen" und ist in der Frucht stehengeblieben, der Drescher natürlich frontal reingeknallt
![image](https://user-images.githubusercontent.com/8066324/153643807-5bf51688-415c-47ea-98c0-6ef55c2b83a1.png)

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
