### ISSUE TITLE
Feld spritzen

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#327]
Moin
Was muss ich einstellen wenn ich ein Feld spritzen möchte, ich habe jetzt z.B. Feld 8, Füllung Flüssigdünger, Ort der Auffüllung: Düngertank eingestellt. Welcher Modus muss eingestellt werden ?

**Comment by Iwan1803** [comment]
Du brauchst dafür den Abholen-Modus, denn er soll er bei Bedarf Dünger "abholen" und zum Feld bringen.
Oberes Ziel ist das Feld, darunter der Abholort und darunter natürlich, was abgeholt werden soll.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
