### ISSUE TITLE
Unable to set Park 

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS22_AutoDrive#328]
Hi
I'm using AD 2.0.0.4 and CP 7.0.0.25

i can't set a park destination for my vehicule
i can right click on any button on autodrive pannel (edit, record, etc), except the PARK button, nothing happen when i right click on it (left click just tell me no PARK is set)

CP mini hud is hidden, and i deactivate the right click button in CP.

any idea why ?

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7997819/log.txt)

**Comment by isakovp** [comment]
Hi, I have the same issue

**Comment by MudgeO** [comment]
Same here ...

**Comment by Iwan1803** [comment]
Set and delete parking destination was changed with 1.1.0.8 (28.02.2021) in FS19.
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-key-combinations#parking

**Comment by Chico0008** [comment]
Didn' know the key comb was changed >_<
ok to set park with CTRL + LMB

**Comment by Iwan1803** [comment]
assign P: LCTRL + **R**MB on P
