### ISSUE TITLE
Pickup & Deliver with Autoload

### ISSUE THREAD

**Issue by flug8** [Stephan-S/FS22_AutoDrive#33]
Wie kann ich Paletten automatisch aufladen, transportieren und wieder abladen, zum Beispiel mit einem Anhänger der mit Autoload modifiziert wurde (bei mir Strautmann SEK 802 Autoload)?

**Comment by mikindwa** [comment]
It would be awesome if we could (if possible) in this situation add additional pick up points prior to delivery.  And even more awesome if we could add another 'task' to the que.  This would probably only be applicable to load and deliver mode.  Load from point A and point B etc, then deliver to -----
Or
Load from farm, deliver to other side of map. Load on other side of map and deliver on way back, then load from there and deliver to another place.  Especially for pallets, we could deliver to factory, collect finished goods and deliver to sell point on return trip.
Being able to 'add' a task to this mode we could plan the days workload for our worker and let them go for it.  Would also work for multiple grain types.  I understand if we cannot select which type of pallet (grape juice or raisins etc) as autoload just loads everything, but the return trip would be more realistic to real life.
Thank you for another amazing version of this must have mod, you guys really help make the game.

**Comment by Iwan1803** [comment]
@flug8 
in LS19 gab es das EasyAutoload-Skript, welches AD ansprechen konnte. Fahrzeuge, welche das Skript nutzten, konnten Paletten auf- und abladen. Da dieses noch nicht für LS22 erschienen ist und es entsprechend auch noch keine Fahrzeuge dazu gibt, kann AD aktuell nicht mit Paletten umgehen.
An einigen Triggern werden Paletten aber automatisch "entladen" und man kann zumindest AD dort hinschicken.

@mikindwa 
What does the palette question have to do with your desire for a qeue that you just attach this one? Create an issue for that as it will get lost in here.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
