### ISSUE TITLE
Abholen und Abliefern erstellt automatisch neues Ziel (oder wählt ein anderes als eingestellt)

### ISSUE THREAD

**Issue by alexx2104** [Stephan-S/FS22_AutoDrive#330]
Hallo zusammen,

das hier ist mein erstes Problem, dass ich auf Github für Autodrive erstelle. Solltet ihr weitere Infos oder Logs benötigen, lasst es mich wissen :)
Zu meinem Problem: Ich nutze die Funktion Abholen und Abliefern in Verbindung mit Courseplay, jeweils die neuesten offiziellen Versionen. An "Feld-71 Alternativ" soll abgeholt werden, am "Silo [Beladepunkt]" (also das Silo beladen :D ) soll abgeladen werden. Wenn ich allerdings Autodrive starte, wird immer wieder "Viehhandel" als Abladepunkt eingestellt. Zuvor wurde auch immer wieder ein neuer Punkt "Multisilo 6 Mio" angelegt und angesteuert, obwohl ich diesen nicht mal selbst erstellt habe. Er wurde teils in der Nähe des Multisilos angelegt, teils an irgendwelchen Kreuzungen auf der Elmcreek Karte. Rotierendes Be- und entladen ist übrigens ausgeschaltet.

Könnt ihr mir weiterhelfen?

Viele Grüße
Alex
![2022-02-04 12_51_09-Farming Simulator 22](https://user-images.githubusercontent.com/96819380/152524562-87e63335-605d-45cf-afd9-7f78056eefca.png)
![2022-02-04 12_51_33-Farming Simulator 22](https://user-images.githubusercontent.com/96819380/152524564-a0a94d40-02c4-4109-a165-3b2099076acc.png)

**Comment by RealNeo80** [comment]
da gab es doch ne Funktion dass er den besten Preis nimmt, finds aber grad nirgends wo man das an und abschalten kann

**Comment by TimoR1014** [comment]
klick mal auf das blaue Abladesymbol. dadurch sucht er sich die Verkaufsstelle mit dem besten Preis. da dein Silo nichts bezahlt, fährt er nicht dorthin sondern zum Viehhandel. AD erstellt dann auch schon mal nen neuen Wegpunkt, wenn ne Strecke über nen "guten" Trigger führt. 
gleiches würde auch für das obere Symbol gelten. wenn blau, dann bestes Ziel, wenn weiß, dann eingestelltes Ziel.

**Comment by alexx2104** [comment]
Jau das wars. Danke euch zwei :) Die Funktion kannte ich auch noch nicht. Wie sucht er sich die passenden Abladepunkte bzw. wie werden sie verbunden? Einfach indem man dem Abladepunkt den gleichen Namen der Verkaufsstelle gibt?

Was ich noch nicht verstehe: wieso wurde immer wieder dieser Punkt "Multisilo 6 Mio" angelegt? Kann es gerade leider nicht mehr reproduzieren 👎

**Comment by Axel32019** [comment]
Der Abladepunkt bekommt den Namen der An-/Verkaufsstelle mit dem niedrigsten/höchsten Preis und wird so platziert das das aktuelle Gespann auch abladen kann, wenn kein Ziel passt.
