### ISSUE TITLE
Fahrzeuge fahren bei eingeschalteter Kollisonserkennung teilweise nicht

### ISSUE THREAD

**Issue by RubberDuck3011** [Stephan-S/FS22_AutoDrive#332]
Hallöchen,

ich habe ein Problem mit der Kollisonserkennung von AD. aber seht selbst anhand der Bilder.

Bei ein paar Fahrzeugen ist der Sensor sogar teilweiße im Boden.

MFG und vielen Dank
![20220204_192153](https://user-images.githubusercontent.com/99044628/152588368-585efec5-4e34-442d-94f4-2747390b05ba.jpg)
![20220204_192830](https://user-images.githubusercontent.com/99044628/152588892-4e68925e-765a-4395-bb4f-81b38d0a4cf5.jpg)

**Comment by Axel32019** [comment]
Hallo, Kollisionshöhe ist viel zu niedrig eingestellt - 1.5 bis 2 m einstellen

**Comment by RubberDuck3011** [comment]
Wie kann ich die Kollisonshöhe einstellen?

**Comment by RubberDuck3011** [comment]
Funktionier danke schön
