### ISSUE TITLE
Frage: Drescher und Abfahrer Kollision 

### ISSUE THREAD

**Issue by Zwoxlol** [Stephan-S/FS22_AutoDrive#333]
Gibt es eine Möglichkeit sowas zu verhindern? Ist nicht das erste mal passiert

![image](https://user-images.githubusercontent.com/65707907/152602065-0cbe35cf-31e1-40cb-b609-790017278079.png)

**Comment by RealNeo80** [comment]
#326 das ist auch das was ich hier beschrieben habe

**Comment by Zwoxlol** [comment]
![image](https://user-images.githubusercontent.com/65707907/152603658-31edd0d2-3469-4c4a-aaff-85a1e26de6a5.png)

Das sollte man ausschalten können. Er sollte direkt vom Rohr wegfahren nach rechts oder links.

**Comment by Axel32019** [comment]
Ursache ist #184

**Comment by rohne83** [comment]
Kann es sein, dass der Drescher kurz zuvor am Ende der vorherigen Bahn in den Abfahrer abgetankt hat, mit Rohr (und Abfahrer) in der Frucht?
Dann ists doch kein Wunder, dass sowas passiert. Man bunkert einfach nicht über der Frucht ab.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
