### ISSUE TITLE
Q: How does "Park" work in Pickup and Deliver?

### ISSUE THREAD

**Issue by AgroWillem** [Stephan-S/FS22_AutoDrive#334]
1st of all: great thanks for developing this nice mod again for FS22.

When i make a Pickup and Deliver route it keeps saying that i must mark a "Parkpoint" with a right mouse-click.
This does not help.
Clicking the "P" in the menu gives the same message.
I assigned CRTL+ALT+P keys to "parking" but gives the same message.
The Pickup and Deliver does not work good now, it keeps choosing random destinations.

I read https://github.com/Stephan-S/FS22_AutoDrive/issues/330#issue-1124119371 but either Blue or White Symbol, it keeps choosing other destinations then i want. I do not understand. 

Thx ahead mates.

**Comment by Iwan1803** [comment]
If the message comes up that no parking point was assigned, then you didn't assigned a parking point for the selected vehicle or attachment.
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-key-combinations#parking

If the targets are changing, you've activated the distributed load/unload for that vehicle.

**Comment by AgroWillem** [comment]
Maybe a dull question but how do i assign LCTRL + RMB to "P".
When i try it only says CTRL under Keys1 OR under "Mouse" it only says "RIGHT".

**Comment by Iwan1803** [comment]
You do not need to assign this key combination - you just have to press it.

**Comment by Iwan1803** [comment]
Since no further feedback -> closed!
