### ISSUE TITLE
Error: Running LUA method 'packetReceived

### ISSUE THREAD

**Issue by Papa-Scherzkeks** [Stephan-S/FS22_AutoDrive#336]
hoffe die Server log hilft.

[NF_Marsch_4fach_oG. 06.02.2022 log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8010264/NF_Marsch_4fach_oG.06.02.2022.log.txt)
[NF_Marsch_4fach_oG. 06.02.2022 log 2.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8010270/NF_Marsch_4fach_oG.06.02.2022.log.2.txt)

**Comment by Iwan1803** [comment]
Hilfreich wäre eine Beschreibung, wann was wie wo mit welchen Fahrzeugen und Einstellungen etwas passiert.
