### ISSUE TITLE
AD 2.0.0.4 REC funtion makes the game "Freeze"

### ISSUE THREAD

**Issue by Ginks-dk** [Stephan-S/FS22_AutoDrive#337]
When ever we activate the REC function on our MP server, No one can drive their vehicles.
Lights, door and all other stuff works. And you can exit the vehicle and walk around.
As soon as you take off the REC, everything works again

**Comment by Iwan1803** [comment]
Log from server and client could help us....

**Comment by Bjoern-B** [comment]
Hey we have the same freezing problem but it happened not while recording but just randomly i'll attach the Server and the 2 logs from the connected clients
[Server_log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8081255/Server_log.txt)
[Player1_log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8081257/Player1_log.txt)
[Player2_log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8081258/Player2_log.txt)

**Comment by Axel32019** [comment]
> When ever we activate the REC function on our MP server, No one can drive their vehicles. Lights, door and all other stuff works. And you can exit the vehicle and walk around. As soon as you take off the REC, everything works again

Please provide the complete log files from server and client(s).

**Comment by Bjoern-B** [comment]
> 

Mag auch nen fehler sein aber wie du an der länge des logs siehst läuft der server noch ca 2 stunden weiter bevor das problem auftrat ich würde auf alles aber zeile 51627 tippen


2022-02-16 16:37 Warning (script): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2022-02-16 16:37   D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\base\scripting\lua\LuaScriptSystem.cpp (890): expectedType == Value::VoidType || expectedType == Value::ClassType
2022-02-16 16:37 LUA call stack:
  dataS/scripts/triggers/LoadTriggerSetIsLoadingEvent.lua (40) : streamWriteUInt8
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/network/Server.lua (549) : sendEvent
  dataS/scripts/triggers/LoadTriggerSetIsLoadingEvent.lua (57) : broadcastEvent
  dataS/scripts/triggers/LoadTrigger.lua (440) : sendEvent
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Utils/UtilFuncs.lua (1001) : setIsLoading
  dataS/scripts/utils/Utils.lua (436) : newFunc
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Tasks/RefuelTask.lua (126) : onFillTypeSelection
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Tasks/RefuelTask.lua (67) : startRefueling
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Modules/TaskModule.lua (87) : update
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Specialization.lua (395) : update
  dataS/scripts/specialization/SpecializationUtil.lua (19)
  dataS/scripts/vehicles/Vehicle.lua (1877) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (112) : update
  dataS/scripts/network/Server.lua (59) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1180) : update
  dataS/scripts/FSBaseMission.lua (2006) : update
  dataS/scripts/missions/mission00.lua (582) : update
  dataS/scripts/main.lua (1323) : update
2022-02-16 16:37 Warning (script): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2022-02-16 16:37   D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\base\scripting\lua\LuaScriptSystem.cpp (890): expectedType == Value::VoidType || expectedType == Value::ClassType
2022-02-16 16:37 LUA call stack:
  dataS/scripts/triggers/LoadTriggerSetIsLoadingEvent.lua (40) : streamWriteUInt8
  dataS/scripts/network/Connection.lua (88) : writeStream
  dataS/scripts/network/Server.lua (549) : sendEvent
  dataS/scripts/triggers/LoadTriggerSetIsLoadingEvent.lua (57) : broadcastEvent
  dataS/scripts/triggers/LoadTrigger.lua (440) : sendEvent
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Utils/UtilFuncs.lua (1001) : setIsLoading
  dataS/scripts/utils/Utils.lua (436) : newFunc
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Tasks/RefuelTask.lua (126) : onFillTypeSelection
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Tasks/RefuelTask.lua (67) : startRefueling
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Modules/TaskModule.lua (87) : update
  =C://gameservers//s1437393//ls2022//gameProfile/mods/FS22_AutoDrive/scripts/Specialization.lua (395) : update
  dataS/scripts/specialization/SpecializationUtil.lua (19)
  dataS/scripts/vehicles/Vehicle.lua (1877) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (112) : update
  dataS/scripts/network/Server.lua (59) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1180) : update
  dataS/scripts/FSBaseMission.lua (2006) : update
  dataS/scripts/missions/mission00.lua (582) : update
  dataS/scripts/main.lua (1323) : update

**Comment by Axel32019** [comment]
@Bjoern-B  Das sieht nach einem Trigger aus der zwar ein Objekt, jedoch keine FillUnit hat - was so vom Grundspiel nie angenommen würde.
Leider kann ich nicht die ganzen mods analysieren - hier hilft nur Stück für Stück testen oder evtl. nach einem Script in den mods suchen welches die Funktion onFillTypeSelection überschreibt.
Als workaround nehm ich einen nil-check mit auf und eine log-Ausgabe wenn sowas auftritt.

**Comment by Bjoern-B** [comment]
@Axel32019 Wir vermuten es könnte https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=224316&title=fs2022
mit dem mod zusammenhängen, da AutoDrive versucht an der Multifrucht-Einkaufsstation zu tanken, jedoch man Diesel nur mit einem Anhänger aus der Multifrucht-Einkaufsstation bekommt.

**Comment by Axel32019** [comment]
@Bjoern-B Welches Fahrzeug versucht da zu tanken?

**Comment by Bjoern-B** [comment]
@Axel32019 Naja alle, also wenn der tankstand niedrig ist und autodrive sagt es fährt tanken und die Multifrucht-Einkaufsstation am nächsten ist fährt das fahrzeug zu dieser und versucht da zu tanken

**Comment by Axel32019** [comment]
> @Axel32019 Naja alle, also wenn der tankstand niedrig ist und autodrive sagt es fährt tanken und die Multifrucht-Einkaufsstation am nächsten ist fährt das fahrzeug zu dieser und versucht da zu tanken

@Bjoern-B Jetzt hab ich's wiedergefunden: #188

**Comment by Axel32019** [comment]
> When ever we activate the REC function on our MP server, No one can drive their vehicles. Lights, door and all other stuff works. And you can exit the vehicle and walk around. As soon as you take off the REC, everything works again

@Ginks-dk Will you be able to provide logs?

**Comment by Bjoern-B** [comment]
> > @Axel32019 Naja alle, also wenn der tankstand niedrig ist und autodrive sagt es fährt tanken und die Multifrucht-Einkaufsstation am nächsten ist fährt das fahrzeug zu dieser und versucht da zu tanken
> 
> @Bjoern-B Jetzt hab ich's wiedergefunden: #188

Jo alles klar den fix haben wir auch schon gemacht alles uns die Idee kam das es daran liegen könnte seitdem hatten wir den freeze auch nicht mehr
