### ISSUE TITLE
Mehrere Missionen

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#338]
Hallo
Es ist kein Problem sondern eine Frage: Können Autodrive und Courseplay mehrere Aufträge nach einander arbeiten, also wenn z.B. Feld 1,2, und 3 gespritzt werden soll das er die nach einander abfährt

**Comment by hermannbrauer** [comment]
Hallo Hendrik, 
nein, das ist so nicht vorgesehen und wird vermutlich auch nicht implementiert. 
Da es sich beim LS22 um einen Landwirtschafts simulator handelt mit dem Schwerpunkt auf die landwirtschaftlichen Tätigkeiten Feldwirtschaft und Tierhaltung, das was du möchtest ist eine Manager Simulation das kann so nicht umgesetzt werden.

**Comment by RealNeo80** [comment]
Das Problem wäre hier auch die Koordination da das 2 verschiedene Mods sind. Du musst ja je im AD und CP die entsprechenden Ziele und Kurse vorgeben. 

Das was du wärst wäre eigentlich ein 3. Mod der auf die Ziele von AD und die Kurse von CP zugreift, du die in ner liste entsprechend zusammenfügst und dann sagst Liste abarbeiten.

@Iwan1803 hat AD eigentlich die Möglichkeit sich extern starten zu lassen so wie CP?

**Comment by RealNeo80** [comment]
ähm ja, wenn ich so drüber nachdenk, blöde Frage

**Comment by Axel32019** [comment]
@Iwan1803 @RealNeo80 Nicht ganz: AD reagiert auf definierte Events von CP. Um AD von anderen mods zu starten ist etwas mehr notwendig :-)
