### ISSUE TITLE
Silly Driver

### ISSUE THREAD

**Issue by Terrabey** [Stephan-S/FS22_AutoDrive#339]
Hello!
I want to report an Issue by unload an Harvester.
The Issiue is that the planing need to long and he drive to slow.
This is not good for good profit

**Comment by ChndlrBng** [comment]
I have no idea why this would be a reportable issue. The things you described can be different for different PCs or AD-Settings. Add your used settings and measure the times, maybe add short Clip of your Issue. If i were the developer of this Mod i would ignore and close this Issue immediately.

**Comment by Iwan1803** [comment]
Issue means a problem or error, but i just do not understand what you want to report now.

**Comment by Terrabey** [comment]
For Example. When I have 2 Harvester and 3 Unloader then they do nothing. They just stay there and play a Card Game. My second example is that when he want to unload a field with 1 harvester he goes to it but the Harvester drives away and the Unloader exit the field goes back on it calculate the course again goes to the full Harvester. Doesn't go with the Harvester...

**Comment by Iwan1803** [comment]
We love it when we are asked to guess what the problem might be...
Log? Screenshots of the situations? Settings for the harvester and the unloader?

**Comment by Axel32019** [comment]
As @Terrabey seem to not like to post required information, see #120, closed!
