### ISSUE TITLE
Lua Callstack V2.0.0.1 RC1

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS22_AutoDrive#34]
Moin, hab einen Fehler bekommen nach folgenden Einstellungen:
Traktor eingestellt auf Hof Silo Hafer abholen, soll bringen nach Getreidemühle, Fruchtsorte Hafer. Einmalige Fahrt.
Habe ihn losgeschickt, es kam ein Hinweis das ich keinen Parkplatz zugewiesen habe und während er auf dem Weg war zum Hofsilo habe ich die Fahrt abgebrochen. Danach hatte ich die Lua Meldung im log.

Hoffe es hilft Dir. 
LG TImmi
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7743474/log.txt)

**Comment by Iwan1803** [comment]
Gerade im Stream verifiziert:
- die Option "am Ende parken" ist aktiviert
- ist kein P zugewiesen, kommt die LUA-Meldung beim Start (Abholen&Abliefern)
- ist ein P zugewiesen, kommt keine Meldung
