### ISSUE TITLE
Latest release 2.0.0.4 is not using updated translations files

### ISSUE THREAD

**Issue by Lactic68** [Stephan-S/FS22_AutoDrive#341]
Hi,
I have noticed that the recent release version 2.0.0.4 is not using the updated translations files. That is for example the case with [French (FR)](https://github.com/Stephan-S/FS22_AutoDrive/blob/main/translations/translation_fr.xml). 

Might be useful to include them in next release.

**Comment by Iwan1803** [comment]
All open requests were included. If there is something wrong, then you can edit it and open a new request 😉
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
