### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by ducky75** [Stephan-S/FS22_AutoDrive#343]
Hallo,
erstmal vielen Dank für eure Super Arbeit an diesem Mod!!
Hätte da mal ne Frage, vielleicht könnt bzw dürft ihr das ja verraten???
Wo nimmt sich AD den Punkt am Fahrzeug zur Streckenverfolgung?? Und könnte ich den dann am Fahrzeug anpassen???
Weil der bei manchen MOD Fahrzeugen  gerne ziemlich weit hinten sitzt, und das Fahrzeug dann an Kreuzungen oder engen Kurven zb sehr weit ausholt  und schlussendlich hängen bleibt!
Im vorraus schonmal Danke!
Grüße Ducky

**Comment by ChndlrBng** [comment]
Guten Morgen,
ohne es 100% zu Wissen, aber ich vermute es ist der Punkt über deinem Fahrzeug zwischen dem die Rote Linie zum naheliegendsten Wegpunkt gezogen wird.
VG

**Comment by ducky75** [comment]
Hallo,
 ja genau um den geht es mir!
 Der ist ja bestimmt vom Fahrzeug her vorgegeben?
Schwerpunkt, Kamara posi oder sowas?

**Comment by ducky75** [comment]
Habe jetzt mehrere Stunden mit meinem freundlichen Suchanbieter nach Hilfe für den Schwerpunkt gesucht!
Das einzigste was ich gefunden habe ist wie ich in der XML den "centerofmass" verstellen kann!
Das zu verändern ändert aber nichts an dem Punkt der Abnahme (rote Linie)!
Wie oder wo im Giants Editor kann ich den Schwerpunkt bearbeiten? Finde dazu leider überhaupt nichts im Netz :-(

**Comment by Axel32019** [comment]
Hallo @ducky75 , Der Punkt ist der (keine Ahnung wie das richtig heißt!) Definitions-Punkt der ersten Komponente eines Fahrzeuges, nicht der Schwerpunkt. Im GE die erste Komponente anklicken, dann ist es das Fadenkreuz.
Sorrry, bin mit den GE etc. Begrifflichkeiten nicht fit!

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen.
