### ISSUE TITLE
AD Bleibt immer in der frucht Stehen

### ISSUE THREAD

**Issue by Osram1981** [Stephan-S/FS22_AutoDrive#344]
![fsScreen_2022_02_08_18_46_30](https://user-images.githubusercontent.com/89778771/153048389-3b4e3623-77ba-4787-afbe-d0c2bf1f7b58.png)
Hallo AD Bleibt wen ich Gras mit dem Hecksler Ernte immer in der frucht stehen trotz Fruchumfahrung,
auch wen ich abfahrer zb auf feld begrenze fährt er nicht wie bei Mais Hinterher auf der ersten sonder fährt in der frucht neben hecksler her.
er fährt immer links vom hecksler und bei jeder 2den  bahn wechselt der abfahrer keine ahnung warum und der andere steht dan in der bahn wo der Hecksler nehmen möchte und sie kolidieren.

ps bei mais Funktioniert alles soweit

**Comment by Iwan1803** [comment]
Ähnliches Problem wie in #345 : Gras... 🙄

**Comment by Axel32019** [comment]
Grundproblem ist #184.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
