### ISSUE TITLE
Probleme Grashäckseln mit Abfahrer und Häcksler

### ISSUE THREAD

**Issue by VJH01** [Stephan-S/FS22_AutoDrive#345]
Hallo AD-Team,
mir sind zwei Sachen beim Grashäckseln (Häcksler mit CP) und Abfahren (AD) aufgefallen:
![Bug_AD](https://user-images.githubusercontent.com/96574322/153072369-5cfca917-dc78-46fa-ac93-3672d80f339c.png)
:
1. Der Abfahrer (gelbe Linie) fährt zwischen dem Schwad und Häcksler (grüne Linie). Das Verhalten macht das Wendemanöver unnötig kompliziert. Es wäre sinnvoller wenn er erst rechts vom Häcksler gefahren wäre und nach dem Wenden links vom Häcksler. Ansonsten passiert gern mal Punkt 2 bei mir.
2. Der Abfahrer crasht mehrfach den Häcksler nach dessen Wendemanöver (rote Linie), er fährt immer nur stur vor und zurück. Sinnvoller wäre etwas auszuholen und wieder seitlich an den Häcksler (blaue Linie).

Vielen Dank für die tolle Arbeit bisher!

**Comment by Rosencrafter** [comment]
Also ich habe ein ähnliches Problem mit einem Mais Häcksler und auch beim Dreschen ab und zu wieder das Problem.
cast:
Der Abfahrer läd einen Drescher ab. Der Drescher ist leer, fährt sein Rohr ein und startet nach einer kurzen Zeit weiter auf seinem Kurs. Der AD abfahrer jedoch hat die kurze zeit genutz, weil er voll ist und abladen möchte, und hat sich einen pfad gesucht. leider versucht er immer zuerst nach rechts zu wenden also in den Drescher hinein. (besser wäre hier erst nach links zu fahren oder ein stück zurück zu setzen).
Das Gleiche Problem wie oben im Issue beschrieben hatte ich auch beim Mais Häckseln, hab jetzt aber leider kein bild mehr davon. ebenfalls das Problem: AD und der Helfer (CP) "sprechen sich nicht ab" wer jetzt in welche richtung wendet und wer zuerst fahren darf.

**Comment by ct177mak** [comment]
@Rosencrafter vllt lädst du dir mal den Mainbranch runter von Autodrive ,ich für meinen Teil habe kein Problem das der Abfahrer auch ein Stück zurück setzt und nicht in den Drescher vorne fährt .

**Comment by Iwan1803** [comment]
Was soll am "Mainbranch" anders sein als am Release selber? Richtig, gar nichts 😉

**Comment by Rosencrafter** [comment]
Keine Ahnung auf welche versionen du dich irgendwo beziehst... Ich behaupte einfachmal das alle Issues sich nur und ausschließlich auf die latest release Version beziehen, und so ist des bei mir auch. Eine andere Version werd ich mir auch nicht in mein Savegame ziehen, denn meistens hat es einen grund warum ein neues feature noch nicht im release ist.

nun inhaltlich: 

> @Rosencrafter vllt lädst du dir mal den Mainbranch runter von Autodrive ,ich für meinen Teil habe kein Problem das der Abfahrer auch ein Stück zurück setzt und nicht in den Drescher vorne fährt .

Ja, macht er, aber nicht wenn er voll ist und zum abladepunkt fahren will, sondern nur wenn er zwischendurch einmal den drescher abgeladen hat. Und in meinem fall auch nicht immer.

**Comment by Axel32019** [comment]
Kommen Verbesserungen in die nächste Version.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
