### ISSUE TITLE
FS 22 Autodrive & Multiple Trailers

### ISSUE THREAD

**Issue by caseguy15** [Stephan-S/FS22_AutoDrive#346]
I am running two gravity wagons with autodrive that unload a combine just fine.  When they go to the bin (silo) only the first wagon will unload and the tractor and wagons will just sit there.
Auto drive version 2.0.0.3

**Comment by dominiczeth** [comment]
First thing: try newest version 2.0.0.4

**Comment by Redster999** [comment]
And move the stopping point further away. Minimum 1,5x the length of the full vehicles with trailer

**Comment by caseguy15** [comment]
I kept the same version and moved the stopping point farther ahead.  That seems to have worked.  Thanks.
