### ISSUE TITLE
Can't offloading back way with Maximun Trigger Distance 10m

### ISSUE THREAD

**Issue by yann-mrt** [Stephan-S/FS22_AutoDrive#347]
Good day,
When I try to make a offloading with a back way route and AD Maximum Trigger Distance setting at 10m, the tractor go back until the way point, don't detect the trigger and don't offload. If the setting is at 25 m their is not problem offload is done normally.
This happen in all offloading I try to do in back way.
I didn't find this problem was already reported, if it was, sorry for the double.
![image](https://user-images.githubusercontent.com/74056604/153097920-ec1e4a00-a1e2-4f73-85dc-0fb4a7b6929c.png)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8028421/log.txt)

**Comment by Axel32019** [comment]
Hello @yann-mrt , Could you please enable the trigger display with F5. This would help to see the trigger.

**Comment by yann-mrt** [comment]
Here it is 
![image](https://user-images.githubusercontent.com/74056604/153684737-90454ff5-8cb1-4daf-9486-6eb21c4bd958.png)
Same for this one 
![image](https://user-images.githubusercontent.com/74056604/153685178-3fb2fec8-f686-4736-a2be-e3828b8902dc.png)
and all back way offload I try to do with 10m setting even with other map.

**Comment by Axel32019** [comment]
Could you please drive to unload with debug trailer enabled.

**Comment by yann-mrt** [comment]
Good day,

Here is the log file with debug trailer enable
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8069032/log.txt)

**Comment by Axel32019** [comment]
Hello @yann-mrt , In the log I can see that the trigger is not recognize, due to:
- triggers are "searched" only in the trigger distance, but if the unload point of the trailer has already moved out of trigger area it will not be recognized as the distance is taken from the tractor center -> move the target closer to trigger area
- Do you activated automatic unload position in settings?

**Comment by yann-mrt** [comment]
I try the following with the same trailer and other one (not molded) in case.
I try with unload point closer and on the border of the trigger, with and without automatic tip side and all test are the same, still doesn't unload with 10m maximum trigger distance back way.

**Comment by yann-mrt** [comment]
@Axel32019 did you had chance to look at this ?

**Comment by Axel32019** [comment]
@yann-mrt Was busy with other topics, but looks like I found a possible solution.

**Comment by yann-mrt** [comment]
It is working great !! 
Thanks for your, and other ones from the dev team, times.
I guess I would not play to FS without AD and CP.
