### ISSUE TITLE
Mehrere Abfahrer in einer Reihe warten nicht wenn der Motor des ersten Fahrzeugs ausgeschalten ist

### ISSUE THREAD

**Issue by DagiBeeast** [Stephan-S/FS22_AutoDrive#349]
Hey,

Situation:

Ich hab ein Fahrzeug welches einen Kipper beladen soll.
Der Traktor mit Kipper soll rückwärts (!) an dieses Fahrzeug heranfahren, beladen werden, und wieder losfahren zum Abkippen.
Es sind mehrere Fahrzeuge in der "Runde" beschäftigt. Sobald der erste Kipper rückwärts am belade Punkt angehalten hat, wird nach ein paar Sekunden der Motor ab geschalten (Er steht unter keinem Silo sondern wird manuell durch ein Spieler z.B Radlader beladen)

Das Problem ist nun folgendes:
Der zweite Abfahrer hat derweil mit viel Abstand gewartet bis der erste Abfahrer rückwärts an den belade Punkt gefahren ist. Sobald allerdings der erste den Motor beim beladen abstellt, fährt der zweite los und knallt ihm quasi rückwärts vorne drauf.

 Nun wäre mein Vorschlag eine Option einzubauen, welche festlegt, wie lange der Motor an sein soll bzw. wann die Strecke freigegeben wird. Evt. das auch bei Motor aus die Strecke vom AD Fahrzeug belegt wird.

Grüße

**Comment by Axel32019** [comment]
Hallo @DagiBeeast , Screeshots mit sichtbaren Zielen würde uns sehr helfen das zu verstehen und vielleicht haben wir auch eine Lösung...

**Comment by DagiBeeast** [comment]
Hallo @Axel32019

https://prnt.sc/26ubdvj
https://prnt.sc/26ubelt
https://prnt.sc/26ubesk

Sobald der erste Abfahrer (Massey Ferguson) sein Beladeziel erreicht hat, geht er quasi auf Standby und der zweite Abfahrer (Fendt) wird losgeschickt und fährt ihm somit vorne drauf.

**Comment by Axel32019** [comment]
Für diesen Fall extra eine Option einzubauen halte ich nicht für sinnvoll/nötig, das hat zu viele Auswirkungen auf anderes.
Wie ich das lösen würde: Eine Schleife vorwärts um das braune Haus https://prnt.sc/26ubelt , dann können die Abfahrer hintereinander bei "bst1" warten.

**Comment by DagiBeeast** [comment]
Ja ein Kreisverkehr geht natürlich , allerdings ist das nicht immer ganz so Praktikabel... Schade das es nicht möglich ist, die Abfahrer warten zu lassen.

**Comment by Axel32019** [comment]
Solange ein Fahrzeug auf der blauen Strecke aktiv / fährt, gilt diese als belegt und die folgenden warten. Der laufende Motor zeigt an das das Fahrzeug noch aktiv ist.
In Deinem Fall müsste man die Strecke solange blockieren wie ein Fahrzeug darauf fährt, steht, ent-, lädt usw.
