### ISSUE TITLE
Verbesserungsvorschlag Reparatur und Tanken

### ISSUE THREAD

**Issue by Pehusa** [Stephan-S/FS22_AutoDrive#351]
Wenn ich automatische Reparatur und automatisch Auftanken eingestellt habe, wäre es super, wenn der Helfer die Notwendigkeit früher erkennen würde.
Bei mir kommt es oft vor, dass der Helfer im "Drescher abladen" Modus z.B. im Hofsilo ablädt, dann zum Feld fährt und erst dort erkennt, dass eine Reparatur ansteht. Dann fährt der Helfer in die Werkstatt, lässt reparieren und fährt wieder zurück zum Feld.
Sollte jetzt zufällig tanken notwendig sein, fährt der Helfer wieder los zum tanken.
Dadurch ist der Helfer sehr lange unterwegs und fährt unnötige Strecken leer. Gerade auf größeren Karten dauert das ewig.

Prima wäre es, wenn der Helfer bereits vor Anfahrt Feld auf Notwendigkeit prüft, und dann ggf beides direkt hintereinander erledigt.

**Comment by RealNeo80** [comment]
das Problem ist wie du sagst der Schwellenwert, da selbst beim prüfen vom Starten von AD dieser unterschritten ist bei Ankunft am Feld aber fällig.

was helfen würde, bei Ankunft am Feld nicht zu prüfen ob er in die Werkstatt muss sondern das nur beim Starten und beim Verlassen des Feldes prüfen. 
Bei erfolgter Reparatur auch prüfen ob er Tanken muss, oder ihn ggf ab 50% nach einer Reparatur  immer zum Tanken zu schicken

**Comment by Pehusa** [comment]
Ja, wie von theMompfdie beschrieben, wäre es der Idealweg:
Abladen (oder generell Starten) -> Werkstatt -> Tanken -> Zielpunkt -> Drescher abfahren
Wenn ich AD zum Auffüllen der Sähmaschine, des Düngerstreuers oder der Spritze in Kombination mit CP nutze, ist das auch der Fall:
Gerät ist leer --> Feld verlassen --> Gerät am Silo auffüllen --> Feld --> Werkstatt --> Feld --> tanken --> Feld --> Wiederaufnahme der Arbeit

Kann AD den Zustand Tanken und Werkstatt bei Start nicht vorausberechnen? AD wirft mir ja auch die Zeit bis Ankunft aus.
Wenn der eingestellte Schwellenwert bei Ankunft unterschritten werden würde, dann geht es erst zu Werkstatt und Tanken.
Die Prüfung am Feld könnte dann entfallen.

Ich kenne mich aber technisch nicht aus, daher entschuldigt bitte, falls der Vorschlag nicht umsetzbar ist.

Es wäre nur eine super Erleichterung, da auf einer großen Karte u. U. gut und gerne mal 10 Minuten Umweg durch das pendeln zwischen Feld und Werkstatt/Tankstelle dazu kommt.

**Comment by RealNeo80** [comment]
ja aber wieso vorausberechnen? die Feld(Ziel)Prüfung einfach weglassen und Tanken nach der Werkstatt grundsätzlich wenn <50% Tank. Weil der Schlepper stirbt ja net weil er noch die Feldarbeit machen muss. Beim Tanken müssten man überlegen ob man dann beim Starten net einen höheren Tanklevel prüfen muss, damit aufm Feld der Sprit net ausgeht

**Comment by theMompfdie** [comment]
Technisch betrachtet  ist sicher am einfachsten, wenn das eine Event fertig ist, startet automatisch die Prüfung ob die Bedingung für das andere Event auch erfüllt wird. Dies würde sicher keine größere Rechenleistung benötigen. 

Andereseits will man ja vielleicht das die AD Fahrer viel auf der Karte herum _crusen_ und die Arbeit erledigen, deswegen einen die Zeit dann auch nicht so wichtig ist. :)

**Comment by Daywalker885** [comment]
also muss auch sagen es ist recht nervig, wenn man AD als abfahrer für das feld hat und ihn zu sich rufen will und er auf einmal auf die idee kommt ach ich muss tanken oder in die werkstatt, vielleicht kann man eine art tolleranz darin einbauen. Das wenn er zum beispiel als abfahrer gerufen wird, er erst abbunkert und dann tanken fährt oder in die werkstatt also das er die priorität dann anders setzt. So das er das tanken einfach mit in den aktuellen auftrag mit einbindet, ist ja nu nicht so das der auf einmal kaputt geht oder kein sprit mehr hat. Des weiteren wäre es auch nice, wenn man AD einstellen könnte, wann er reparieren und tanken fährt

**Comment by BigBlackBahamut** [comment]
So, nun ist es mir gerade passiert. Mein Traktor ist in Zusammenarbeit mit CP auf dem Feld mangels Sprit verreckt....

Kann es sein das dass Tanken im Bereich "CP" nicht funktioniert? somit wäre die Möglichkeit AD selbst Tanken fahren zu lassen ja mehr oder weniger hinfällig was den Bereich CP angeht. 

Daher wäre es auf jeden Fall besser auch unteranderem den Stand des Diesels fürs "Selbsttanken" anzuheben.

**Comment by Axel32019** [comment]
Eine vorausschauende Prüfung ob Tanken,Reparieren notwendig ist sehe ich als nicht kalkulierbar an.
AD überprüft nach jeder abgeschlossenen Aktion, z.B. Laden, Entladen, Fahren etc., ob Tanken,Reparieren notwendig ist und führt dies durch.
Zudem wird im nächsten Release die Zusammenarbeit mit CP für Tanken,Reparieren,Parken enthalten sein - könnt ihr gerne mit der dev-Version schon mal probieren: https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
