### ISSUE TITLE
Kann es sein, dass die Parkplatz ID´s nach dem löschen von Zielpunkten nicht mehr stimmen?

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#352]
Ich habe meine Parkplätze und Ziele umgestellt, und dabei auch einige gelöscht, jetzt hab ich festgestellt, dass bei einigen Fahrzeugen die Parkplätze nicht mehr stimmen.

Kann es sein, dass die ID´s nicht fix sind, sondern diese stur von A_Z in die Tabelle eingelesen werden? wenn zwischendrin welche fehlen
stimmt dann natürlich der index von der Tabelle nicht mehr mit dem Zielpunkt überein.

kann ich mir gerade nicht anders erklären

**Comment by Axel32019** [comment]
SP oder Server?

**Comment by RealNeo80** [comment]
SPVon meinem/meiner Galaxy gesendet<div>
</div><div>
</div><div>-------- Ursprüngliche Nachricht --------</div><div>Von: Axel32019 ***@***.***> </div><div>Datum: 11.02.22  22:30  (GMT+01:00) </div><div>An: Stephan-S/FS22_AutoDrive ***@***.***> </div><div>Cc: RealNeo80 ***@***.***>, Author ***@***.***> </div><div>Betreff: Re: [Stephan-S/FS22_AutoDrive] Kann es sein, dass die Parkplatz ID´s nach dem löschen von Zi </div><div>
</div>

-------- Original Message --------
Subject: Re: [Stephan-S/FS22_AutoDrive] Kann es sein, dass die Parkplatz ID´s nach dem löschen von Zi
From:    Axel32019 ***@***.***>
To:      RealNeo80 ***@***.***>

SP oder Server?

**Comment by Axel32019** [comment]
Also ich krieg das nicht hin. Wenn Du das wieder mal hast, bitte AutoDrive_config.xml und vehicles.xml anfügen.

**Comment by SchorschiBW** [comment]
Ich hatte eben das gleiche (oder ein ähnliches???) Phänomen:

Hatte gestern an meinem Streckennetz ein paar Kleinigkeiten geändert (zusätzliche Punkte für neue Parkplätze, Fahrsilo ans Netz usw.) und als ich heute morgen mein Spiel startete, stimmten alle, aber auch wirklich alle zugeteilten Parkplätze nicht mehr, sprich, die Geräten hatten allesamt andere Zuweisungen

**Comment by RealNeo80** [comment]
@Axel32019 
ich hatte das ganze wieder, und weiß glaub ich auch woran das liegt. Ich habe das Streckennetz mit dem externen Editor bearbeitet und dabei Punkte gelöscht, imho macht der die ID vergabe anders als AD intern. Sollte das eher ins GIT vom Editor oder hier? Oder gibts keine Lösung und is einfach so, dann muss man halt aufpassen.

**Comment by Axel32019** [comment]
@RealNeo80 Bitte beim Editor melden wenn noch nicht geschehen
