### ISSUE TITLE
Kurs Berechnung Streckennetz Nutzung

### ISSUE THREAD

**Issue by Pioner912** [Stephan-S/FS22_AutoDrive#353]
Hallo zusammen, 

Ich habe heute eine Düngemission angenommen und AD und CP zum Auftrag geschickt und das hat auch geklappt aber irgendwie will der Traktor nicht das Streckennetz nutzen siehe Bilder! 

![20220211101425_1](https://user-images.githubusercontent.com/65849562/153566226-5b47812e-bbef-4918-8858-1c9142e85c09.jpg)
![20220211101438_1](https://user-images.githubusercontent.com/65849562/153566234-f208fd1a-2e6e-46e8-9173-c988520cfa94.jpg)

Gibt es irgendetwas was man beachten sollte, der Traktor stand vorher auf einem Feld mit CP Auftrag und AD Zielpunkt (Feld 21 NF Marsch).

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8047395/log.txt)

**Comment by Axel32019** [comment]
Hallo @Pioner912 , Das sieht danach aus als ob Du den neuen Job mitten im Feld 11 oder 36 gestartet hast. Dann wird mittels Pathfinder der Weg zum Startpunkt F 44 gesucht - geht dann quer über die Map :-).
Bitte mal prüfen ob Feldausfahrt auf nächstgelegen steht und das Netz von Holger stammt. Wenn ja sollte er die Feldlinie nehmen und über die Straßen zum Ziel fahren.
