### ISSUE TITLE
Abfahrer bleibt trotz Platz stehen

### ISSUE THREAD

**Issue by Pr3d4t0r71** [Stephan-S/FS22_AutoDrive#356]
Hey Leute,

habe die neuste Version von Autodrive (2.0.0.4) und habe das Problem, dass die Abfahrer nicht aneinander vorbeifahren, obwohl genug Platz zwischen ihnen ist. Muss dann immer einen manuell zur Seite fahren damit es weitergeht. 

Vllt hat ja jemand von euch einen Tipp um das zu lösen.

![fsScreen_2022_02_11_17_32_54](https://user-images.githubusercontent.com/99498862/153635738-5b1e390c-e42c-4e35-ba7f-b52e29aee1e7.png)

**Comment by RealNeo80** [comment]
ich denk dass da die kollissionsboxen aneinanderknallen, schalt mal die sensoren in der Debug ein. Ich glaub da is einfach zu wenig platz

**Comment by Axel32019** [comment]
Hallo @Pr3d4t0r71 , @RealNeo80 Hat's schon erkannt: in LS22 sind die Kollis die Fahrzeuge etwas "gewachsen" - zieh mal die Wegpunkte ein klein wenig zum Straßenrand, dann sollte es funktionieren.

**Comment by Pr3d4t0r71** [comment]
@Axel32019 @RealNeo80  Danke für eure Antworten, werde mir das dann morgen oder übermorgen nochmal anschauen.

Dann werden wohl alle Routen angepasst werden müssen 😣

**Comment by Pr3d4t0r71** [comment]
Anhänger sind alles die standardmäßigen Bergmann Häckselwagen
Links: Originaler Fendt 900er
Mitte: Mod 900er (https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=225936&title=fs2022)
Rechts: Originaler Claas 900er

Traktoren und Anhänger sind alle mit normalen Reifen, also keine Breitreifen
![fsScreen_2022_02_12_21_56_11](https://user-images.githubusercontent.com/99498862/153728132-4d464de1-0bb0-4026-9c10-76504c7c1861.png)

**Comment by Axel32019** [comment]
Das sind die Abmessungen der Fahrzeuge in deren xml. Real sind sie kleiner, z.b. der Anhänger in der xml 3,8m breit, laut GE ca. 2,6m. Wir verwenden für alles in AD die xml Werte - ein "Scannen" der realen Abmessungen wäre viel zu aufwändig.
Daher bleibt Dir nur die Engstellen zu weiten oder mit blauen Strecken eine Vorrang-Lösung einzubauen.

**Comment by Pr3d4t0r71** [comment]
Könnte man ansonsten auch die Werte in der XML anpassen? Oder meinst du das wäre zu aufwändig, bzw würde Giants da mit Updates immer reinfuschen?

**Comment by rohne83** [comment]
am besten aus dem Fahrzeug nen Mod machen, und dann nur in deinem Mod die xml anpassen. Wenn du die Originaldateien änderst, geht kein Multiplayer mehr, und deine Änderungen sind mit jedem LS-Update gefährdet rückgängig gemacht zu werden.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
