### ISSUE TITLE
Tractor is waiting in the planted area

### ISSUE THREAD

**Issue by MoslessNeo** [Stephan-S/FS22_AutoDrive#358]
I'd like to report a problem I'm having - I searched here but couldn't find it. If there is a similar report, close it.
The problem is that when the tractor in overloader mode is doing its job of going to the combine (this works very well), after the combine is finished unloading the auger wagon it goes to the planted area.
This causes a lot of trouble because the harvester soon comes back and collides with him.
It is activated for him to avoid planting, but even so, he insists on going in the field not yet harvested.

![20220211132338_1](https://user-images.githubusercontent.com/6533809/153664771-d782e40d-c345-4587-869f-0b9759e42b36.jpg)

![20220211132314_1](https://user-images.githubusercontent.com/6533809/153664833-7e27a826-0907-4596-b6a1-43abd1a92b6b.jpg)

![20220210082157_1 2](https://user-images.githubusercontent.com/6533809/153664861-e78dd898-7468-4c69-b627-76689212076a.jpg)

**Comment by RealNeo80** [comment]
#344 #345 #326
