### ISSUE TITLE
Debug Infos für Anfangspunkte

### ISSUE THREAD

**Issue by Clouseau219** [Stephan-S/FS22_AutoDrive#36]
Hi,
erst mal vielen Dank für eure tolle Arbeit und die tollen neuen Features !!!!
Ein Vorschlag hätte ich. Wäre es möglich für Streckenanfangspunkte auch eine Debug Information, wie für Tote Enden, einzubauen?
Weil wenn man die Strecken automatisch erstellen lässt gibt es, gerade auf Haut-Beyleron, doch viele unnütze Anfangspunkte welche von anderen Streckenpunkten überlagert werden. Diese durch verschieben der anderen Punkte zu finden ist eine Sisyphus Arbeit.
Daher fände ich es schön wenn diese Punkte auch im Debug-Streckennetz angezeigt würden.
Wäre sowas für zukünftige Releases vielleicht denkbar?

Nochmals Danke !

Grüße,
Clou

**Comment by Iwan1803** [comment]
Aktuell gibt es noch ein Bug in der automatischen Routenerstellung, was leider zu diesen Sackgassen führt.
Ein Fix ist bereits in Arbeit und danach tritt das Problem nicht mehr auf (siehe https://github.com/Stephan-S/FS22_AutoDrive/issues/4 ).

**Comment by Clouseau219** [comment]
Ah, ok, ich dachte es liegt an den Punkten auf den Karten die Giants gesetzt hat.

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
