### ISSUE TITLE
Mod wird als Installiert angezeigt aber man kann ihn nicht aktivieren

### ISSUE THREAD

**Issue by RobinHooooood** [Stephan-S/FS22_AutoDrive#361]
Hey zusammen, 

habe das Problem, das ich den Mod nicht aktivieren kann. Mir  wird zwar angezeigt, dass ich ihn installiert hab (siehe Screenshot) 
![fsScreen_2022_02_12_20_20_58](https://user-images.githubusercontent.com/59301819/153725285-2c040ea0-d01c-4109-b2de-b772546ad674.png)

allerdings wird er nicht aufgeführt in dem Menü wo man Mods aktivieren kann. 

Hat jemand ein Tipp woran es liegen kann? 

Version ist 2.0.0.4

Hab grad mal in die Log nachgeschaut, hab den Error gefunden.
![grafik](https://user-images.githubusercontent.com/59301819/153725557-9170ba03-87e6-4093-be28-d6cc4669b748.png)

kann mir wer sagen was man da ändern soll?

**Comment by svensigi** [comment]
Schau mal in den Modordner von Farming Simulator.
Eventuell kann es sein das der Bindestrich zwischen Autodrive-main nicht erlaubt ist, steht ja so auch da nur _  dann A-Z und a-z und 0-9.
Änder den Namen der Moddatei mal auf "FS22_Autodrive" dann sollte des gehen

**Comment by RobinHooooood** [comment]
Hab grad den "-" durch einen Unterstrich ersetzt. Jetzt Funkt alle :D
