### ISSUE TITLE
Creating only One Waypoints doesnt work, it produces 200+ points

### ISSUE THREAD

**Issue by svensigi** [Stephan-S/FS22_AutoDrive#362]
Normally if i wanna create a single more waypoint, it works with LCTRL and leftclick. 
It works, but not as requested 🥇 
After clicking it creates a triangle of waypoints.
How many?
Didnt count them haha
Maybe someone else have this bug? 
Using the 2.0.0.4 version with newest Courseplay
![Screenshot (44)](https://user-images.githubusercontent.com/99558489/153725423-086559c9-f0ec-43e3-81e8-b6f9cb3791ac.png)

**Comment by Tensuko** [comment]
Dude that is (as far as I know) just to choose the color ofthe waypoints....
I am not sure what you want to try to do there...

**Comment by Axel32019** [comment]
@svensigi See here: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#new-color-assignment-for-users-with-different-color-perception
