### ISSUE TITLE
Ballen abladen

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#363]
Hallo
Kann ich mit Autodrive Ballen sammeln und dann abladen
Wenn ja was muss ich einstellen

**Comment by RealNeo80** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/981

hat dir doch Tensuko schon gesagt

**Comment by Tensuko** [comment]
Bisschen Aufmerksamkeit generieren: #354

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
