### ISSUE TITLE
FS22_CollectStrawAtMissions, FS22_CollectStonesAtMissions. plugins are getting broken ~ some low level plugins but still.

### ISSUE THREAD

**Issue by maddoglv** [Stephan-S/FS22_AutoDrive#364]
One of them is mine, but the public one what you can test with is

FS22_CollectStrawAtMissions
Also: https://github.com/maddoglv/FS22_CollectStonesAtMissions
I bet someone has issues as well.

So to reproduce: (create a game without AutoDrive) -> then start to collect Straw using (FS22_CollectStrawAtMissions) and then save the game enable the AutoDrive and you will be notified that this field does not belong to you (and will stay this way you can even remove Auto Drive mod) ~ would love to find a solution to this one.

Sorry but I'm a bit new, to Lua and fs22 so it will be a lot harder for me
Tnx for any help, Cheers

**Comment by RealNeo80** [comment]
its working fine with autodrive, special for collection straw. i have sometimes the issue that some fields are not recognized from the mod (especial after loading a savegame), but i don´t think it comes from Autodrive
