### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maddoglv** [Stephan-S/FS22_AutoDrive#366]
Is it possible to, 
Like in the case of Stonepicker -> work the field, then when it full drive to delivery point then return and continue working?

**Comment by RealNeo80** [comment]
#367 same as here, its a Giants bug. It will not recognized that it is full, needs to be fixed from Giants

**Comment by maddoglv** [comment]
There is one mode that fixed that `FS22_StonePickerStopper` don't know if it`s compatible with logic that is in this plugin

**Comment by sperrgebiet** [comment]
Hey guys

Nope, my StonePickerStopper won't help here. As it just stops the helper (Giants AI or CP). But Giants told me that this issue will be fixed in Patch 1.3, therefore they won't accept my mod in Modhub. Now lets ask the crystal ball when v.1.3 will be released ;)
