### ISSUE TITLE
Steinesammler wird in Zusammenarbeit mit CP nicht von AD geleert

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#367]
Hi zusammen,

ihr wollt wissen wenn ein Gerät sich in Verbindung mit CP nicht leert? Hier ist ein solches Problem.
Der Steinesammler ist voll und wird von AD auf einem CP-Kurs nicht geleert, er fährt voll weiter. Er sammelt komischerweise die Steine zwar noch ein, aber voll ist nun mal voll.

Gruß

**Comment by RealNeo80** [comment]
das ist ein Giants Bug, der sammelt mit dem Standard-Helfer auch weiter obwohl er voll ist. Muss Giants fixen

**Comment by BigBlackBahamut** [comment]
Ah, okay... Aber vielleicht kann AD ja den Fahrer zwingen eine Pause ein zu legen.  Aber ok, Danke für diese Info.

**Comment by BigBlackBahamut** [comment]
Also, so oder so nicht AD bzw CP Fähig. Dann warten wir einfach mal ab. ;-) Danke :-)
