### ISSUE TITLE
Autodrive gibt nicht an CP ab im MP

### ISSUE THREAD

**Issue by prehnj112** [Stephan-S/FS22_AutoDrive#368]
Hallo,
bei mir gibt Autodrive nicht an CP weiter. Ich lasse den Schlepper mit Sammelwagen zum Feld fahren und habe Beladen am Feld und Abkippen im Silo. Mit CP habe ich einen Kurs auf dem Feld und bei Autodrive CP an.
Der Abfahrer fährt nur bis zum Feld und schaltet dann ab, aber wenn ich CP selber starte übergibt CP an Autodrive wenn der Wagen voll ist. Beim Rückweg bleibt er aber nur wieder am Feld stehen.
Mache ich irgendetwas falsch?

**Comment by dddanny79** [comment]
Hier selbes Problem. Im SP kann man im Schlepper sitzen. 
Ist auf jeden Fall hinderlich, wenn es so sein sollte, dass man NICHT im Schlepper sitzen darf. Oft genug passiert genau am Anfang das Meiste.

**Comment by prehnj112** [comment]
Habe es Mal probiert und es funktioniert wenn man nicht im Fahrzeug sitzt. In der Log kommen dann aber luafehler, die aber nichts beeinträchtigen (zumindest bei mir nicht)

**Comment by steffenZ640** [comment]
danke jetzt weis ich warum ad an nicht an cp übergeben hatt weil ich immer drin gesessen habe , weil es kontrollieren wollte .
