### ISSUE TITLE
Falsches Ziel wird angefahren

### ISSUE THREAD

**Issue by Micha0686** [Stephan-S/FS22_AutoDrive#369]
Wenn zwei Ziele zu nah beieinander und auf der selben Strecke sind, fährt AD leider direkt das erste an selbst wenn das zweite ausgewählt ist. Ichhabe das Bild aktuell ohne Anhänger gemacht. Ein anderes folgt noch. Ziel ist es die Gewächshäuser mit Wasser zu versorgen. Was für ein Logfile soll ich hochladen?
![20220214_134739](https://user-images.githubusercontent.com/13754951/153920459-f34fb672-7a15-42c9-9808-3bc9d6dc0e8c.jpg)

**Comment by Tensuko** [comment]
Und ?
Screenshot mal hochladen lassen wäre super.
Ein Logfile ist auch immer hilfreich...

**Comment by Natsu83** [comment]
Ich glaueb, das ist kein Bug, sondern gewollt bzw. Einstellungs bedingt. Schaue mal in den AD-Einstellungen nach "max. Siloabstand" Wenn der zu hoch eingestellt ist (glaube Standard sind 25 Meter), dann fährt er erst den ersten Trigger auf der Linie auf der 25 m Strecke an und dann erst den zweiten. Habe ich bei mir auch. Lässt sich durch die Einstellung beeinflussen. Aber achtung: Wenn du den max. Abstand zu gering einstellst, dann können größere Fahrzeuggespanne (z.b. Tracker mit mehreren Anhängern) u.U. den Trigger nicht für alle Anhänger fangen. Ist leider eine Einstellung, die sich auf alle Fahrzeuge auswirkt.
