### ISSUE TITLE
Fahrer bleibt bei vollem Silo stehen

### ISSUE THREAD

**Issue by MrMyller** [Stephan-S/FS22_AutoDrive#37]
Moin Moin, gibt es eine möglichkeit bei dem Modus Abholen und Liefern z.B mit nur einem Zielpunkt eine Reihe aus Gewächshäusern zu beliefern? Mein Fahrer bleibt stehen sobald das erste Gewächshaus aus der Reihe voll ist. Macht hier eine "Weiterfahren wenn Silo voll" Funktion Sinn? Oder gibt es da bereits eine Funktion?  

Dankeschön :)

**Comment by Iwan1803** [comment]
siehe https://github.com/Stephan-S/FS22_AutoDrive/issues/10
Da doppelt -> geschlossen.
