### ISSUE TITLE
Gibt es schon ein Branch wo "Fixed (in next release)" schon enthalten sind?

### ISSUE THREAD

**Issue by Clouseau219** [Stephan-S/FS22_AutoDrive#370]
Hi,

nur eine kleine Frage, bitte nicht steinigen.
Gibt es schon ein Branch wo "Fixed (in next release)" schon enthalten sind?

Schon mal Danke !

**Comment by ct177mak** [comment]
nicht wirklich ,ich nutze den Branch von dev_axel ,bis hier hin habe ich keine Probleme mit dem Branch ,aber nicht wundern weil das eh noch Beta ist und er ständig was dran ändert..

**Comment by Clouseau219** [comment]
Danke, werde ich mal testen. Ist mir schon klar dass da Fehler drin sein können. Aber das Testen macht mir eh spaß :)
Ich glaube ich probiere beim FS22 mehr rum als dass ich wirklich sinnvoll spiele :)

**Comment by ct177mak** [comment]
Bei CP Branches mache ich das gleiche ,das bischen Engl. bekomme ich noch zusammen *lach ,ok back to the Testing and happy Farming :)

**Comment by Dzi4d3k** [comment]
@Clouseau219 
But there are some caveats using dev branch:
https://github.com/Stephan-S/FS22_AutoDrive/issues/365

**Comment by Iwan1803** [comment]
Jeder DEV-Branch ist halt eine Entwicklungs- und Testumgebung für die Modder und die (offiziellen) Tester.
Natürlich kann sie sich jeder runterladen, aber es gibt dafür von uns keinerlei Support - selbst dann nicht, wenn der Rechner explodiert 😋
