### ISSUE TITLE
IVT Getriebe am Berg keine Leistung

### ISSUE THREAD

**Issue by Geri-G93** [Stephan-S/FS22_AutoDrive#371]
schönen guten Abend
ich denke das es vom AutoDrive her rührt, die Abfahrer mit IVT Getriebe (6250R, 7...R usw) haben Berg aufwärts keine Kraft, tuckeln im Standgas dahin, macht sich am Hang mit 3Achser schlecht beim häckseln
Schaltgetriebe (7810 zb) hat da keine sorgen, der hält mit
Fotos kann ich nachreichen wenn was benötigt wird.

noch ein Problem ist, wenn der Abfahrer rückwärts rangiert beim umlenken am Vorgwende fährt er nicht wieder los und ein anderer kommt angebraust.

**Comment by Iwan1803** [comment]
Bitte Log.txt posten, danke!

**Comment by Axel32019** [comment]
Hallo @Geri-G93 , Bitte auch einen Screenshot der Bergfahrt mit aktivem Debug Sensoren anfügen.

**Comment by Geri-G93** [comment]
kannst du selber testen, ich hab auch einen Lösungsvorschlag gemacht, ich vermute das ihr min und max vertauscht habt 
ADSpecialDrivingModule
Line 162  local acc = math.min(0.75, maxAcc) 
dort math.max und es geht

**Comment by Axel32019** [comment]
@Geri-G93 Wenn es hilft Super & Danke!
