### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Diselsa** [Stephan-S/FS22_AutoDrive#372]
Hello, I have 2 questions.
1 is possible make little convoy?
I mean If I want 2 or 3 vehicle go on same field is possible make that they follow each other? Somtimes second vehicle crash in first or something else.
Second question is why always ai go in tree? I dowloaded autodrive for map from map creator but when I have truck and lowloader or tractor with trailer ai driver often go in tree and stuck there.

**Comment by Dzi4d3k** [comment]
I would say that is is better to wait for:
https://github.com/DeckerMMIV/FarmSim_Mod_FollowMe
Then you would be able to send first vehicle with AD and rest following each other.

**Comment by Iwan1803** [comment]
No, there is no convoy mode in AD.

`why always ai go in tree`
Sorry, but how should we know if you don't even post some info about it?

**Comment by Diselsa** [comment]
> No, there is no convoy mode in AD.
> 
> `why always ai go in tree` Sorry, but how should we know if you don't even post some info about it?
![20220218003655_1](https://user-images.githubusercontent.com/99608836/154590417-de5a78a4-0a19-499a-b0b3-dcdd9ea1cdfc.jpg)
![20220218003659_1](https://user-images.githubusercontent.com/99608836/154590422-41a936db-b8db-4389-8ba3-b28e2e5a2233.jpg)
He need go on other field but he stuck on tree. In options i had enabled collision detect but he stuck on tree
![20220218004828_1](https://user-images.githubusercontent.com/99608836/154591125-b3f1f22b-c901-4341-8ec0-6c409970e2b6.jpg)
https://gist.github.com/Diselsa/8237f781ccc9bf3686f0d8982df5eb8a (Here is part of log all log is too long so I take part but I am not sure is any information about AD)

**Comment by Axel32019** [comment]
Hello @Diselsa , I am not sure if the issue is the mod tractor or the >200 errors in "part" of log. At the moment I can not see the issue related to AD!

**Comment by Axel32019** [comment]
There are 2 speed settings - one on fields, one on streets, 6 / 13 see: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Buttons-with-short-description
