### ISSUE TITLE
2022-02-16 23:39 Error: Running LUA method 'packetReceived'.

### ISSUE THREAD

**Issue by Haumichweg** [Stephan-S/FS22_AutoDrive#373]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8084144/log.txt)

Hallo Jungs, hab den fehler im MP und dann dreht alles durch :-D Könnt ihr gucken was da falsch läuft. Egal welches Fahrzeug ab und zu kommt der Fehler. Nach Server neustart geht alles wieder wie immer 

Gruß Steve

**Comment by Haumichweg** [comment]
jo werd ich probieren :-)

**Comment by Haumichweg** [comment]
@Axel32019  hab das neue update von Courseplay geholt die 7.0.1.2 und da wird es zwar noch angezeigt aber es dreht nicht durch sondern macht alles was das soll :-)

**Comment by Haumichweg** [comment]
Problem ist wieder auf getaucht wenn anscheind zu viele Helfer aktiv kommt der Lua Fehler vllt hilft dir das weiter. bzw wenn Courseplay auf Autodirve umschaltet kommt der lua Fehler.

**Comment by Axel32019** [comment]
Welche CP Version hast Du im Einsatzt?

**Comment by Haumichweg** [comment]
7.0.1.2  das aktuellste

**Comment by Haumichweg** [comment]
@Axel32019  der Fehler tritt aber nur bei Abolen und abliefern modus auf sonst bei keinem, wurde mir gerade vom freund gesagt hoffe das hilft euch weiter

**Comment by Axel32019** [comment]
In diesem Fall würde ich eher auf CP tippen, da wird ein Job gestoppt:
AIJobStopEvent.lua(37) : attempt to index field 'aiMessage' (a nil value)
Auf dem Server müsste noch ein callstack auftauchen - bitte Server-log mit anfügen.
Gerne mal an CP adressieren -> @Tensuko
