### ISSUE TITLE
Probleme mit Rübenernter

### ISSUE THREAD

**Issue by Zwoxlol** [Stephan-S/FS22_AutoDrive#375]
Hallo,

https://youtu.be/KETVfx8L-xM

Hier ein kleines video von einem Abtankversuch. 
Kann mir jemand sagen ob das an einer Einstellung liegt?

**Comment by Zwoxlol** [comment]
![image](https://user-images.githubusercontent.com/65707907/154574714-aab6d78a-4885-48d5-af69-20ae96d142c3.png)


Weiteres Problem

**Comment by Zwoxlol** [comment]
![image](https://user-images.githubusercontent.com/65707907/154577011-ee7ba15b-387a-476b-b86a-ece7328791be.png)

Weiteres problem: er fährt hier seit 2 Minuten im kreis

**Comment by Zwoxlol** [comment]
> Hallo @Zwoxlol , An Einstellungen bitte mal alles einschalten: Fruchtumfahrung, Feldbegrenzung, warten im Feld. Dann sollte auch das 2. Problem nicht auftreten. Zur Fruchtumfahrung kommt im nächsten Release noch eine Verbesserung.

Ich hab zumindest die Lösung fürs erste problem gefunden. Und zwar ist mit dem Anhänger nur ein kleinerer Wendekreis möglich. Ich hab einen anderen probiert und da funktioniert es wunderbar

**Comment by Axel32019** [comment]
Klingt doch schon mal gut :-)
