### ISSUE TITLE
Cant drive under Augers

### ISSUE THREAD

**Issue by Bovrinox** [Stephan-S/FS22_AutoDrive#376]
Encountered an issue loading trailers from an auger. AD wont drive under the end of the auger.
![image](https://user-images.githubusercontent.com/63093402/154578350-f84da27c-e7f9-4a21-8117-f6638598bb3c.png)
This happens with collision detection on or off, and it also wont drive under it just in drive to mode.
![image](https://user-images.githubusercontent.com/63093402/154578474-5d4b1c7a-538f-4ec5-bccb-d6d53d5465db.png)
As soon as i move the auger, AD sets off again. I tried it with both the deliver modes, not entirely sure what the difference between them is but neither would do it.

**Comment by Iwan1803** [comment]
There is a hidden collision which AD detects and that's why they stop.

**Comment by Axel32019** [comment]
see also #230
