### ISSUE TITLE
Radlader Strecke aufzeichnen führt zu Bug

### ISSUE THREAD

**Issue by M4rlnk0** [Stephan-S/FS22_AutoDrive#377]
Hallo zusammen, 

mir ist seit gestern ein Bug aufgefallen, bei welchem jeder Radlader beim aufzeichnen einer Strecke recht zügig in eine endlose Rechtsbewegung übergeht. Manchmal verschwindet auch der Mauszeiger. Wenn ich ins Menü wechsel, wird das UI nicht angezeigt. Sollte da gerade ein Autosave starten hängt sich das Spiel auf. Solang der Fahrzeugwechel via Tab noch funktioniert kann man schlimmeres verhinder, oder aber der Mauszeiger ist noch da und man beendet die Aufzeichnung schnell genung. Mit anderen Fahrzeugen funktioniert alles wie gewohnt gut. 

Alte Savegames als auch neue Spielstände reagieren gleich. Auch habe ich testweise alle Mods außer Autodrive deaktiviert. Der Fehler bleibt bestehen. Ich spiele auf der Elmcreek mit AD v.2.0.0.4 .

Viele Grüße
Marinko

**Comment by Axel32019** [comment]
Hallo @M4rlnk0 , Eine komplette log-Datei würde schon mal helfen.

**Comment by M4rlnk0** [comment]
Hallo  @Axel32019 ,
entschuldige bitte. Hier ist sie. Ich habe das Spiel gerade gestartet und nur den Fehler rekunstruiert. 

Viele Grüße
Marinko

[Uploading log.txt…]()

**Comment by Axel32019** [comment]
Hallo @M4rlnk0 , Danke für die log. Und daraus erkennbar haben wir das schon (gefixt in nächster Version): #301
