### ISSUE TITLE
Bei mehreren Abfahrern bleibt der 1ste Aktive immer stehen und der 2te wird gerufen

### ISSUE THREAD

**Issue by svensigi** [Stephan-S/FS22_AutoDrive#378]
![Screenshot (45)](https://user-images.githubusercontent.com/99558489/154800631-7c3b2934-e083-49d8-9f3d-12d6c4eb588d.png)
Bin gerade am Maishäckseln mit dem Standard Helfer und Courseplay (gleiches Resulat)
Sobald der Häcksler wendet, wartet der 1ste Abfahrer auf den Ruf nachdem das Wendemanöver beendet ist.
Wenn der Häcksler wieder bereit ist, ruft er erneut einen Abfahrer, was allerdings nicht der ist der gerade befüllt wurde.
Gibt es da eine Möglichkeit, den Abfahrer der zuletzt gefüllt wurde, wieder als Priorität zu setzen, bis der Füllstand erreicht wird zum Abladen?

Danke

**Comment by rohne83** [comment]
Kann das damit zusammenhängen, dass bei AD die Abfahrer-Prioritäten derzeit immer auf Entfernung gestellt sind? Wäre generell (gerade auch beim Dreschen) schon ganz sinnvoll wenn man festlegen könnte, dass nicht der naheste sondern der vollste Abfahrer gerufen werden soll.

**Comment by Geri-G93** [comment]
was ich beobachtet habe, mei mir setzt der aktive Abfahrer zurück und geht auf Wartemodus 60sek 
währenddessen kommt der nächste angebraust

**Comment by svensigi** [comment]
@Geri-G93 genau
Der Abfahrer wird beladen, setzt dann aus nicht nachvollziehbaren Gründen zurück und der nächste kommt dann angefahren, obwohl andere näher am Häcksler sind. Ist wohl ein Bug, weil teilweise funktioniert es ohne Problem und manchmal kommt nach jedem Wendemanöver ein neuer Abfahrer

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
