### ISSUE TITLE
Missing 'AD_parkVehicle_deleted' in l10n_fr.xml despite being in l10n file

### ISSUE THREAD

**Issue by Lactic68** [Stephan-S/FS22_AutoDrive#379]
When we delete a parking spot, the dialogbox is not translated despite this entry being in the l10n_fr file
![2022-02-19_18-41-39](https://user-images.githubusercontent.com/70093234/154812655-4da0d8e0-6195-495a-b758-52507ccdedd9.png)
.

**Comment by Iwan1803** [comment]
Thanks for the pull request. We will add this in the next version.
