### ISSUE TITLE
Erweiterte Kollisionserkennung sorgt bei minimalen Unebenheiten für ein stehenbleiben des AD-Fahrers

### ISSUE THREAD

**Issue by mlewelt** [Stephan-S/FS22_AutoDrive#38]
Auf Beyleron sorgen auch kleine Gefälle bzw. Steigungen dafür, dass der AD-Fahrer vor dem Steigungswechsel stehenbleibt. Nach dem Deaktivieren der erweiterten Kollisionserkennung tritt das Problem nicht mehr auf.

**Comment by Iwan1803** [comment]
Stell die Kollisionshöhenerkennung auf 2,00 oder 2,25m.

**Comment by mlewelt** [comment]
Jau, Problem dadurch behoben :)
