### ISSUE TITLE
AD bleibt an manchen Punkten einfach stehen 

### ISSUE THREAD

**Issue by vollhorst27** [Stephan-S/FS22_AutoDrive#381]
Hi, ich habe seit Gestern das Problem, dass meine AD-Fahrer an manchen Orten einfach anhalten und dann nicht mehr weiter fahren. Dies sind immer die gleichen Punkte und gilt dann auch für alle Fahrzeuge. Sobald man zwei drei Wegpunkte fährt und AD wieder einschaltet, fährt er auch weiter. Die Punkte sind auch ordnungsgemäß verbunden und die Problemlösung sieht auch nicht darin aus, die jeweiligen Abschnitte neu einzufahren, das habe ich bereits ausprobiert. Hoffe da kann jemand helfen.

**Comment by Iwan1803** [comment]
Auf welche Höhe ist die Kollisionsprüfung denn eingestellt?

**Comment by vollhorst27** [comment]
Kollisionshöhe über Grund ist auf 2m

**Comment by Iwan1803** [comment]
Stell mal testweise auf 2,25 oder 2,50m. Auf der französischen Map habe ich bei einigen Stellen, das die Fahrzeuge stehen bleiben.
Wenn es immer an den gleichen Stellen passiert, wäre interessant zu wissen, was rundherum so steht.

**Comment by Axel32019** [comment]
Nichts Neues hier -> closed
