### ISSUE TITLE
Frage! Kartoffelernter und Abfahrer

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#382]
Hi zusammen,

bei mir kommt es immer öfters vor das der Abfahrer auf dem Weg zu mir zum abtanken ist dann aber weiter fährt zum Feldende und dann wieder zum Feldrand fährt, dann fährt er erneut mich an und dann schafft er es auch mich abzutanken.

Das passiert meist wenn er nach der Runde wo er sich entleert hat versucht mich abzutanken. 

Hat da jemand vielleicht Erfahrung und eine Lösung?

**Comment by BigBlackBahamut** [comment]
OK, kenne den Fehler nun. Wenn ich das Rohr ausfahre während ich noch fahre weil ich noch nicht voll bin und der Abfahrer losfährt erkennt er nicht das ich weitergefahren bin und dann fährt er wieder zum Ausgangspunkt...

**Comment by BigBlackBahamut** [comment]
Okay, jetzt geht´s mir aber auf die Nerven. Immer wieder werden meine Ernter nicht Richtig angefahren und die Abfahrer fahren einfach eine Ehrenrunde. Ich habe das Parken auf dem Feld verboten, Fruchtumfahrung ist deaktiviert und das Feld sollten die Abfahrer nicht verlassen dürfen.

**Comment by AstraThomas** [comment]
Vlt solltest du beim abladen mal anhalten. das problem zwischen ad und fehler 40 besteht keine schnittstelle und ad nicht vorrausberechnen kann wann du lenkst oder irgendwas anderes machst. nicht wie bei cp wo es berechenbar ist.
also ein klassischer fehler 40

**Comment by BigBlackBahamut** [comment]
Habe ich nicht erwähnt aber ich halte immer an da ich das Abfahren während der Fahrt deaktiviert habe bzw. eh nicht mache. Ich lasse immer im stehen abtanken. Daher kann das leider nicht das Problem sein.

**Comment by BigBlackBahamut** [comment]
![20220222113152_1](https://user-images.githubusercontent.com/59480223/155114304-a5b40a88-78d5-4dd7-a8b5-297e7a77d8bc.jpg)

Und wieso fährt der Abfahrer aus dem Feld heraus? ich dachte wenn man den Abfahrer begrenzt sollte das nicht passieren?

**Comment by BigBlackBahamut** [comment]
Was mir gerade noch aufgefallen ist: Ich fahre meist in der Innenansicht und wenn ich aber in der Außenansicht fahre passiert es nicht so oft (bis gar nicht) das der Ablader auf mich zu kommt und dann vorbei fährt und eine Ehrenrunde dreht.

**Comment by BigBlackBahamut** [comment]
![20220223094359_1](https://user-images.githubusercontent.com/59480223/155285759-89bb83eb-b8b5-4a0f-ab97-7176858dbd33.jpg)
Wieso? nachdem er "wieder einmal" mich nicht abgetankt hat und eine Ehrenrunde gedreht hat trifft er nicht mal die AD Spur. Und ja, es ist alles Richtig eingefahren. Das passiert immer wieder das AD meint von der Spur zu fahren ohne jeglichen Grund.

**Comment by Papa-Scherzkeks** [comment]
Ich frage mal ins blaue rein , welche Einstellungen benutzt du bei den Fahrzeugen?

**Comment by BigBlackBahamut** [comment]
So, nun habe ich langsam die Lust an AD verloren. Immer wieder kommt der Abfahrer an und macht dann auf einmal kehrt Marsch und dreht eine Extrarunde. Da bin ich schneller dran wieder komplett selbst zu fahren... Oder ich geh wieder auf LS19...

@Iwan1803 @Stephan-S Vielleicht könnt Ihr mal was dazu sagen was ich versuchen könnte. Oder ist es bei den Kartoffel und Rübendreschern einfach unmöglich das es wirklich klappt?

**Comment by Iwan1803** [comment]
Wie wäre es mal einem Bild der Drescher- sowie Abfahrereinstellungen? Vielleicht ist hier etwas falsch eingestellt.

**Comment by BigBlackBahamut** [comment]
Der Fahrer des Ernter bin ich selber. Ich habe schon hin und her probiert, aber leider ohne Erfolg. Der Abfahrer kommt an und kurz hinter dem Ernter auf einmal dreht er ab und fährt seine Ehrenrunde. 

Ich muss sagen das habe ich bisher immer nur mit dem Kartoffel-Ernter.

![20220227224138_1](https://user-images.githubusercontent.com/59480223/155901008-48869484-de43-45d0-931c-f7bcef00fd61.jpg)
![20220227224143_1](https://user-images.githubusercontent.com/59480223/155901009-9820dece-f5b6-4ea9-bf0b-36a809580c14.jpg)
![20220227224145_1](https://user-images.githubusercontent.com/59480223/155901010-d34e3b13-8d59-4e24-af35-88bf8e124d3f.jpg)

**Comment by Iwan1803** [comment]
Aktives Abfahren = Nein = der Ernter muss stehen bleiben, damit er abgetankt wird.
Du solltest das Rohr also erst ausfahren, wenn das Fahrzeug steht, damit AD es als Ziel anfahren kann.

**Comment by BigBlackBahamut** [comment]
Ja, genau das mache ich ja. Ich warte immer bis er steht. Aber vielleicht ist genau da das Problem. Vielleicht hängt da etwas. Vielleicht muss man da auf noch etwas achten. Meist halte ich schon bei 98 Prozent an, warte bis die restlichen Kartoffeln angekommen sind und fahre dann das Rohr aus.

**Comment by Axel32019** [comment]
Welcher Kartoffel-Ernter genau?
Wartet der Abfahrer nur bevor er wegfährt oder fährt er rückwärts ein Stück zurück?

**Comment by BigBlackBahamut** [comment]
Grimme VENTOR 4150 ist es.

Er kommt angefahren und direkt hinter dem Ernter dreht er ab. Als würde der Abfahrer zu nah auffahren und findet keinen Weg um den Ernter rum um diesen dann abzutanken. Ich würde ein Video machen habe aber leider keine Software dafür auf dem Rechner.

**Comment by Axel32019** [comment]
Fruchtumfahrung und Parken im Feld einschalten, Globale Einstellungen: Pfadfindungs-Faktor auf x2 oder sogar x3 -> F77 auf der NFM ist schon größer als auf den Standard-Karten.
Wenn der Abfahrer von hinten außerhalb Frucht kommt, sollte er nicht abhauen.

**Comment by BigBlackBahamut** [comment]
Ok, ich schau mir das mal morgen an und melde mich dann wieder. Danke für die Hilfe :-)

**Comment by BigBlackBahamut** [comment]
Ich Danke Dir @Axel32019, bisher klappt das mit dem Abfahrer. Aber eine Frage zur Einstellung "Fruchtumfahrung": Sollte der Abfahrer da nicht um die Frucht fahren? Beim anfahren zum Ernter fährt aber mein Abfahrer durch die komplette Frucht durch. Ich habe zwar Fruchtzerstörung aus, aber wenn dann hätte ich stets das Problem das der Abfahrer meine Frucht zerstört.

**Comment by Axel32019** [comment]
Hast Du schon Pfadfindungs-Faktor auf x2 oder sogar x3  eingestellt?
Der Pfad auf dem Feld wird immer erst unter Berücksichtigung von Feld begrenzen, Fruchtumfahrung usw. gesucht.
Ist das nicht möglich werden diese Schritt für Schritt deaktiviert und neu versucht - sieht man beim Abfahrer an den Zahlen n / 1..5
Wenn alles nicht möglich ist, bleibt am Ende nur die direkte Strecke quer zum Ernter, eben durch die Frucht.

**Comment by BigBlackBahamut** [comment]
Ja, bin auf x3. Aber mich stört das nicht, ich habe eh Fruchtzerstörung aus. Aber Danke für die Erklärung ;-)

**Comment by Axel32019** [comment]
Schalt die ruhig mal ein.

**Comment by BigBlackBahamut** [comment]
Vielleicht später mal wenn es mein Feld ist. Gerade ernte ich im Auftrag ;-)

**Comment by rohne83** [comment]
Kannst du bedenkenlos sofort aktivieren. Frucht wird bei vom Helfer gesteuerten Fahrzeugen eh nicht zerstört, auch wenn Fruchtzerstörung aktiv ist. Das passiert nur, wenn man manuell fährt. Leider eigentlich, weil man damit Fahrgassen immer manuell machen muss.

**Comment by BigBlackBahamut** [comment]
> Kannst du bedenkenlos sofort aktivieren. Frucht wird bei vom Helfer gesteuerten Fahrzeugen eh nicht zerstört, auch wenn Fruchtzerstörung aktiv ist. Das passiert nur, wenn man manuell fährt. Leider eigentlich, weil man damit Fahrgassen immer manuell machen muss.

Ah, okay. Gut zu wissen :-) Werde es die Tage mal testen. Im Moment habe ich leider keine Stimmung dazu dank unserer Regierung. 

Da ja das Hauptproblem erfolgreich beantwortet ist werde ich mal schließen. Danke an alle :-)
