### ISSUE TITLE
Deaktivierung CP-Button je nach gewähltem AD-Modus

### ISSUE THREAD

**Issue by taylorfx** [Stephan-S/FS22_AutoDrive#385]
Hallo, obwohl die Übergabe zwischen den beiden Mods gut funktioniert möchte ich eine Erweiterung vorschlagen. Hintergrund dafür ist das Ziel, den Helder schon automatisch zum zu bearbeitenden Feld zu schicken und dort auch den Auftrag Sähen oder Düngen zu starten. Wenn allerdings die Saatgut oder Dünger alle sind, soll er doch einfach stehenbleiben und warten. Das hat in den letzten Versionen gut funktioniert, weil wohl CP nicht zurückgegeben hat an AD. So hatte die Einstellung "Fahre zum Ziel" genau den gewünschten Effekt. Jetzt funktioniert aber die Übergabe von CP zu AD und der "falsche" Modus hat einen anderen Effekt. In einem Sähauftrag kann aktuell folgendes passieren. Der leergearbeitete Driller übergibt ja an AD, damit dieser zu einer Saatgutstation fährt um wieder Saatgut nachzutanken. Ist allerdings jetzt ein falscher Modus im AD eingestellt, bei mir ist es der einfachste Modus (fahre zu Ziel), fährt der Traktor unter AD einfach los. Mittlerweile reime ich mir zusammen, das er eine Route zu dem Feld sucht auf dem er ja schon ist und das führt er auch aus und immer wieder, bis der Tank leer ist quasi. In der Diskussion mit dem CP-Crack meinte dieser, AD könnte sich ja möglicherweise ausschalten bei Ankunft am Ziel. Ich denke aber, damit würde man sich aber weitere Funktionen auf dem Feld verbauen, wozu AD wahrscheinlich quasi horchen muß, insfern wäre ein Button im AD-Panel ganz gut, das das AD nach dem Erreichen des Zieles abschaltet so wie ein Taster, die Betätigung aktiviert die Funktion einmal und ist dann neutral

**Comment by BigBlackBahamut** [comment]
Für das nachfüllen der Saat musst Du auch AD so einstellen das dass Feld als Zielpunkt dient und zum laden muss der Saatgutladepunkt eingestellt sein.

Sobald also die Übergabe an CP erfolgt ist fährt CP. Sobald aber das Saatgut leer ist erkennt es dann AD und übernimmt wieder die Kontrolle und fährt nun zum eingestellten Ladepunkt für das Saatgut, nach dem Laden fährt dieser dann wieder zum eingestellten Feld und übergibt dort wieder an CP.

So sollte es ohne Probleme ablaufen.

**Comment by taylorfx** [comment]
Sorry, Sorry, ich habe mich bemüht, aber trotz der biblischen Ausmasse des Textes habe ich mich wohl verdrückt ausgekehrt.

ich weiß doch, das der korrekte und benötigte Modus im AD "abholen" ist für das Nachtanken der Sähmaschine und das funktioniert ja auch prima. Aber das will ich doch garnicht, ich würde mir die Option "Warten, wenn leer" wünschen. Das war in der Vergangenheit kein Problem, wenn man den "falschen" Modus benutzt hat. Das geht aber nicht mehr, egal welchen Modus man wählt, vorzugsweise "Fahr zu Ziel", wenn leer stoppt CP und übergibt an AD, AD sieht leere Sähmaschine und fährt los.

**Comment by dominiczeth** [comment]
Ich verstehe, im einfachen Modus sollte Ad-Cp abgeschaltet werden sobald das Ziel erreicht ist bzw sobald CP gestartet ist richtig?

**Comment by taylorfx** [comment]
Ja, das wäre schon eine Lösung, aber erst nach der Übergabe an CP.

**Comment by Tensuko** [comment]
Ihr seid da viel zu kompliziert, wartet es ab.

**Comment by BigBlackBahamut** [comment]
:-D Ich glaube was anderes bleibt uns eh nicht übrig. Hihi

**Comment by taylorfx** [comment]
nein, das ist nicht die Anfrage gewesen, er soll doch einfach nur das tun, was er ohne eingeschaltetes AD tun würde, wenn er auf dem Feld leer wird, stehenblieben, ganz einfach nix tun und da AD wegen dem Hinfahren zum Feld eingeschaltet ist bleibt er halt nicht stehen, sondern fährt wieder los

**Comment by haamic** [comment]
Was ist der Sinn dahinter, das er mit leerem Tank stehen bleiben soll? Das erschließt sich mir noch nicht ganz. Weil er bei dir nich im Einfachen Fahrmodus noch ist?

Ich starte einen Feldjob mit dem AD Modus ABHOLEN und nicht mit einer einfachen AD-Fahrt.
Am Beginn möchte das Fahrzeug zwar gleich zum auffüllen, wenn Dünger, Saat, Kalk, herbizid nicht mehr 100% sind, aber das umgehe ich mit dem WEITERFAHREN Button im AD. So fährt er gleich zum Feld, startet die arbeit und füllt auf, wenn er leer ist.

**Comment by taylorfx** [comment]
Oh Leute, man sollte die vorangegangenen Tweet vielleicht bevor man seinen Senf dazu gibt, da steht ein halbes Dutzend mal drin, das ganz bewußt der Modus "fahr zum Ziel" gewählt wurde und eben nicht "abholen" um das Auftanken vom Feld her zu verhindern

**Comment by BigBlackBahamut** [comment]
Ich schrieb ja schon das AD immer läuft das dieser den Status des Helfers (In Deinem Falle ist CP der Helfer) beobachten muss um erkennen zu können ob AD übernehmen muss weil CP nicht mehr an AD übergibt. 

Aber hier scheint der Fehler zu sein das AD im Modus "einfache Fahrstrecke" mit CP nicht diesen Modus als "ankommen" registriert. 

Vielleicht ist das auch schon der Grund warum Tensuko schrieb das wir einfach mal warten sollen da dieses Problem wahrscheinlich schon bekannt und für die nächste Version gefixt ist.

**Comment by haamic** [comment]
Ich hatte gedacht, du bemängelst, das AD im falschen Modus am Feld ankommt und dadurch bei Leere von CP übernimmt und die Fahrt zum Feld wieder beginnt, anstatt zum auffüllen. 

Aber Was möchtest du dann tun, wenn er wie gewünscht leer auf dem Feld steht?
So verhält sich der normale Helfer, er fährt zum Feld, arbeitet und stoppt, wenn er leer ist. Dazu brauch es kein AD+CP.

**Comment by BigBlackBahamut** [comment]
> Ich hatte gedacht, du bemängelst, das AD im falschen Modus am Feld ankommt und dadurch bei Leere von CP übernimmt und die Fahrt zum Feld wieder beginnt, anstatt zum auffüllen.
> 
> Aber Was möchtest du dann tun, wenn er wie gewünscht leer auf dem Feld steht? So verhält sich der normale Helfer, er fährt zum Feld, arbeitet und stoppt, wenn er leer ist. Dazu brauch es kein AD+CP.

Ich Denke was er meint ist folgendes:

AD fährt zum Feld und CP fängt an zu Arbeiten an. Ist das Material leer registriert es AD und schaltet sich wieder ein obwohl es auf "normale Fahrt" eingestellt ist. Anstatt nun das Fahrzeug stehenbleibt weil CP leer nicht weiter macht meint AD vom Feld zu fahren und wieder zum Feldanfang zu fahren, hier übergibt AD aber wieder an CP, dieser aber wie schon vorher bricht ab weil wegen leer, AD übernimmt wieder usw. usw. usw..

**Comment by taylorfx** [comment]
joo, der normale Helfer nutzt aber keine Vorgewende und kann so auf vielen Feldern nicht mit jedem Gerät eingesetzt werden, da macht sich AD mit CP kombiniert auch ganz gut, wenn ich die Option habe, den Prozess auf dem Feld zuenden. jetzt muss ich halt drau achten, in der Drillphase AD abzuschalten

**Comment by Iwan1803** [comment]
Liebe Leute,
lest doch einfach erstmal, um was es geht, bevor ihr irgendwelche Texte postet 🙄
Der Ersteller möchte _nicht_, das die Saatmaschine automatisch nachgefüllt wird und daher soll auch nicht der Abholen-Modus zum Einsatz kommen. Warum wieso weshalb ist doch seine Sache. Es könnte stattdessen auch ein Grubber, Pflug oder jegliches anderes Equipment oder Fahrzeug sein und das Problem wäre das gleiche: AD und CP aktivieren sich gegenseitig im Kreis.

**Situation:** Fahrzeug X wird mit aktiviertem CP-Button per reinem Fahrmodus zum Feld geschickt
**Ergebnis IST:** AD übergibt an CP bei Ankunft am Zielpunkt, der CP-Button bleibt aktiv:
CP übergibt (bei Bedarf) an AD, AD fährt wieder zum Zielpunkt, übergibt wieder zurück an CP und das Spiel fängt von vorne, was keinen Sinn macht.
**Ergebnis SOLL:** AD übergibt an CP bei Ankunft am Zielpunkt, der CP-Button wird aber deaktiviert:
CP kann somit nicht mehr an AD übergeben und das Fahrzeug bleibt dort stehen, wo CP aufgehört hat.

**Comment by haamic** [comment]
Wir haben verstanden, das es um das aktivieren von AD bei fehlendem Material geht. Das durch den falschen Fahr-Modus eine Endlosschleife entsteht. Die Lösung das das nicht passiert, habe ich aufgezeigt.  sicher ist das seine Sache, warum er das so möchte, das das Fahrzeug stehen bleiben soll.  Warum auch immer.
Um das stehenbleiben mit AD zu erreichen, müsste er einen einzigen Wegpunkt anlegen, der keinerlei Verbindung hat. Diesen als auffüllziel im abholen Modus setzen. Dann sollte doch AD abbrechen, weil es dort nicht hinfahren kann und stehen bleiben.

**Comment by Iwan1803** [comment]
Sorry @haamic aber du hast nicht verstanden, worum es geht. Es macht im einfachen Fahrmodus keinen Sinn, das der CP-Button weiter aktiv bleibt, wenn an CP übergeben worden ist - egal ob Saatmaschine, Grubber oder irgendwas anderes.
Und nun genug der Diskussion von wegen "nimm den anderen Modus"...

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
