### ISSUE TITLE
AD-HUD bei den beiden Baumwollvollerntern verhaelt sich komisch

### ISSUE THREAD

**Issue by matze0301** [Stephan-S/FS22_AutoDrive#387]
Hi,

das AD-HUD laesst sich bei den beiden Baumwollvollerntern (CASE und John Deere) nicht immer oeffnen und schliessen.
Und zwar weder mit der Tastatur noch mit dem Gamepad.

Ebenso verhaelt es sich auf jeder Karte, auf der ich das bisher getestet habe, sollte also relativ leicht nachzuvollziehen sein.

Bitte bescheidsagen, falls noch mehr Infos benoetigt werden.

**Comment by Iwan1803** [comment]
Logfile?

**Comment by matze0301** [comment]
Ich bin gerade leider nicht an meinem Spiele-PC.

Das laesst sich aber in 1 Minute selbst nachstellen:

- Neuer Spielstand, beliebige Karte, nur Autodrive Mod
- Einen der beiden Baumwollvollernter kaufen
- Einsteigen und "Alt Keypad 0" druecken
- Beim AD-HUD tut sich nichts.
- Crosscheck mit anderen Fahrzeugen: AD-HUD laesst sich ein- und ausblenden.
- Es machte bei mir keinen Unterschied, ob AD Kurse generiert waren oder nicht.

Meine AD-Version: 2.0.0.4

**Comment by Axel32019** [comment]
Hallo @matze0301 , Kann mit Deinen Schritten kein Problem feststellen - bitte komplettes log anfügen.

**Comment by matze0301** [comment]
Hi @Axel32019,

here we go:

- Im Modordner ausschliesslich AD
- Neuer Spielstand, Elmcreek, keine Kurse automatisch generieren lassen.
- Baumwollvollernter und beliebigen anderen Traktor kaufen.
- In Traktor einsteigen -> Alt-0 blendet AD-HUD ein und aus
- In Baumwollvollernter einsteigen -> Alt-0 zeigt keine Wirkung, das AD-HUD bleibt eingeblendet.
- Wenn man das AD-HUD des Baumwollfahrzeuges per Maus schliesst, laesst es sich auch nicht mehr per Alt-0 einblenden.

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8147153/log.txt)

**Comment by Axel32019** [comment]
Hallo @matze0301 , Ich kann mit meiner Radeon-GraKa das nicht reproduzieren - Vermutung: #312
Bitte mal wie dort beschrieben:
DX 12 nach 11 ändern
Treiber down-/upgraden
Einstellungen probieren

**Comment by matze0301** [comment]
Hi Axel,

vielen Dank fuer's Anschauen und die Tipps :-)

Allerdings werde ich keine Treiber aendern und auch kein Direct-X downgraden, nur weil genau 2 (bzw. 3 mit dem neuen breiten JD-Ernter aus dem Modhub) Fahrzeuge aus der selben Kategorie Probleme haben.
Damit kann ich leben :-)
Falls ich mal ne Loesung habe, melde ich mich natuerlich wieder.

Vielen Dank also nochmal und grosses Lob fuer eure Arbeit an AD, erst damit hat mich der LS so richtig gepackt :-)

**Comment by Iwan1803** [comment]
Jut, wenn du die Vorschläge nicht testen möchtest, dann mach ich hier mal zu, da wir ansonsten auch nicht helfen können.
