### ISSUE TITLE
Probleme seit update 1.3

### ISSUE THREAD

**Issue by Matze9876** [Stephan-S/FS22_AutoDrive#388]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8140230/log.txt)
Hallo ,
seit dem update 1.3 kann ich im Shop einige Fahrzeuge nicht mehr kaufen, ich kann es zwar noch konfigurieren 
aber beim kaufen oder mieten friert das Spiel ein und meine Log füllt sich mit folgendem Fehler:
Error: Running LUA method 'update'.
E:/mods/FS22_AutoDrive/scripts/Specialization.lua:357: attempt to compare number with nil

Ich kann im Shop auch nicht mehr die Fahrzeuge betrachten (rundumsicht) oder herein-/herauszoomen.
Auch die Bilder der Fahrzeuge wirken unscharf.
Allerdings nicht bei allen Fahrzeugen/Geräten (was ich sehr Merkwürdig finde)
Was ich bisher festgestellt habe, tritt dies bei Traktoren und Erntemaschinen auf.

Der Fehler tritt im Singleplayer und Multiplayer auf.

Für weitere Unterstützung bitte ich um kurze Rückinfo.

**Comment by Kitekater** [comment]
E:/mods/FS22_AutoDrive/scripts/

???

C:/Users/mstal/Documents/My Games/FarmingSimulator2022/



das passt irgendwie nicht zusammen oder habe ich da einen Denkfehler?
Mods auf Laufwerk E:\mods
der Reste aber unter dem My Games Verzeichnis, wo es auch hin soll.

**Comment by Matze9876** [comment]
Ich habe meine Mods auf einem anderen Laufwerk gespeichert.

**Comment by Iwan1803** [comment]
Der mods-Ordner selber kann sonstwo liegen, aber was uns hier verschwiegen wird: 2.0.0.5-RC
Wenn man schon eine DEV-Version benutzt, sollte man auch wissen welche und das man sie regelmäßig auf Updates kontrollieren sollte.
Da es für DEV-Versionen keinen Support gibt und es zudem schon eine gibt, wo der Fehler behoben ist -> geschlossen.
