### ISSUE TITLE
AD 2.0.0.5 RC dev_axel32019 und VehicleInspector

### ISSUE THREAD

**Issue by IcemanGSXR** [Stephan-S/FS22_AutoDrive#389]
Ich habe ein Anliegen an euer Team.
Bis zur Version 2.0.0.4 tritt dies nicht auf. Wenn AD zum zugewiesenen Parkplatz fährt wird der Helfer inaktiv und das Fahrzeug wird in der aktiven Helfer Ansicht nicht mehr angezeigt, ist auch gut so.
Inder Version 2.0.0.5 RC dev_axel32019 ist es aber nun so, wenn Ad zum zugewiesenen Parkplatz fährt bleibt der Helfer als H-VC als aktiver Helfer in der Ansicht stehen obwohl er nicht mehr aktiv ist (siehe Bild).
Dies ist halt sehr verwirrend weil ich manchmal nachsehe ob das nicht ein Helfer ist der blockiert wird.
Danke für eure Hilfe.

Danke vielmals an euer Team das ihr eure kostbare Zeit opfert und wir mehr Spaß an diesen Spiel haben. Weiter so.

![AD+VC](https://user-images.githubusercontent.com/6430509/155805065-c7648abb-4231-4781-9482-36175c0f2127.png)

**Comment by regs1980** [comment]
Die 2.0.0.5 RC Version ist kein Release, sobald du aber VCA im Modordner hast erscheint vor deinem Namen H-VC, das ist kein Fehler von AD sondern so gewollt vom VehicleInspector. 

<img width="482" alt="2022-02-26 09_51_02-LS 22_ VehicleInspector v 1 88 Beta Scripte Mod für Landwirtschafts Simulator 22" src="https://user-images.githubusercontent.com/13314443/155836952-5fe4dedf-fa62-44f4-afeb-adcb885c0bf4.png">

**Comment by Axel32019** [comment]
Hallo @IcemanGSXR , sehe das Problem nicht bei AD, vielmehr bei VCA, warum auch immer:
if vehicle.spec_vca ~= nil and vehicle:vcaIsActive() then hType = "-VC";iType = "H-VC";end;
