### ISSUE TITLE
MUltiplayer Fahrzeug zugehörigkeit beim Verkauf

### ISSUE THREAD

**Issue by nimanox** [Stephan-S/FS22_AutoDrive#39]
haben das problem festgestellt das wenn ich in einem tracktor von einen anderen hof sitze mit lohnunternehmer status und ad etwas verkaufen schicke und wieder aussteige er mir das geld überweist anstatt dem jenigen das geld zu geben dem das fahrzeug gehört.

**Comment by Iwan1803** [comment]
Das war in LS19 schon so und ist eigentlich kein Problem von AD.  Woher soll das Spiel bzw. die Helfer sonst wissen, das der Verkauf für einen anderen Hof passiert?

**Comment by nimanox** [comment]
naja weil das fahrzeug ja von wem anderen ist wen ich normal ein fahrzeug von wen anderes fahre und was verkaufe bekommt der das geld und ich nicht

**Comment by Stephan-S** [comment]
Wenn das normale Verhalten anders als das mit AD ist, dann ist es ein Bug.
Ich nehme es so auf aber aktuell hat es keine Prio :-)

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
