### ISSUE TITLE
Punkte verbinden sich nicht

### ISSUE THREAD

**Issue by Knoppersfresser** [Stephan-S/FS22_AutoDrive#390]
Hallo, wenn ich auf dem Dedi Server neue Strecken einfahren will, verbinden die Punkte sich nicht miteinander.
![Farming Simulator 22 26 02 2022 10_32_19](https://user-images.githubusercontent.com/100467239/155838009-cfd6c1a1-a8fc-4fa8-99db-e21ffe7b94ab.png)

**Comment by Axel32019** [comment]
Bitte mal die kompletten logs von Server und Client anfügen.

**Comment by Knoppersfresser** [comment]
[Game log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8146684/Game.log.txt)
[Server log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8146686/Server.log.txt)

Danke dir.

**Comment by Axel32019** [comment]
Die Server log ist von AD schon mal unauffällig.
Server log.txt -> Diese Server-Datei benötigen wir fast nie.
Game log.txt -> Das ist die log vom Server -> OK
Fehlt: log.txt vom Client -> von Deinem PC

**Comment by Axel32019** [comment]
@Knoppersfresser Bitte log.txt vom Client -> von Deinem PC anfügen.

**Comment by Knoppersfresser** [comment]
Mittlerweile scheint es wieder zu funktionieren. Die Punkte verbinden sich. Vielleicht lag es wohl nur am Server.
Vielen Dank

**Comment by Axel32019** [comment]
Wenn es wieder auftritt bitte öffnen.
