### ISSUE TITLE
Abfahrer folgt Drescher ohne abzutanken

### ISSUE THREAD

**Issue by TobiHH78** [Stephan-S/FS22_AutoDrive#391]
Ich habe häufiger das Problem, dass der Abfahrer den Drescher trotz ausreichend Platz und ausgefahrenem Rohr nicht abtankt. Er folgt dem Drescher mit dem Hinweis "Seite hinten". Genau wie er es auf den Bahnen macht, bei denen das Rohr in der Frucht ist.
Erst wenn man beim Drescher kurz die Geschwindigkeit auf 8 km/h oder weniger reduziert,, fährt der Abfahrer unter das Rohr.

Passiert sowohl beim dreschen mit CP wie auch bei eigener Steuerung des Dreschers.
Abfahrer früher rufen ist beim Drescher eingestellt (30%).

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8148792/log.txt)

![1](https://user-images.githubusercontent.com/56259322/155886375-a9f23a0e-ecd9-4a0d-826d-3272818dc88b.PNG)

![2](https://user-images.githubusercontent.com/56259322/155886391-c1933e1e-336f-436d-88e4-36ecad090096.PNG)

**Comment by Iwan1803** [comment]
Hast du aktives Abtanken im Drescher aktiviert?

**Comment by TobiHH78** [comment]
Ja, ist aktiviert. Wie gesagt, sobald man kurz die Geschwindigkeit reduziert, fährt der Abfahrer auch direkt unter das Rohr.
Das Phänomen hatte ich im 19er auch schon

**Comment by Axel32019** [comment]
An der Geschwindigkeit sollte das eigentlich nicht liegen.
Bitte in Ernter-Ansicht mal Debug Sensoren anschalten und die Bereiche links und links vorn beobachten / Screenshots machen.
Blaue Diagonale -> Frucht erkannt -> Ernter fährt nicht hin
Grüne Diagonale -> Feld nicht erkannt -> Ernter fährt nicht hin

**Comment by TobiHH78** [comment]
Sorry, aber ich habe kein IT studiert, verstehe leider nur Bahnhof.
Was soll ich tun und wie geht das?

**Comment by Axel32019** [comment]
Hab ich auch nicht :-)
Im Ordner c:\Users\....\Documents\My Games\FarmingSimulator2022 die log.txt anfügen.
Ist 1 Ebene tiefer als der mods Ordner

**Comment by TobiHH78** [comment]
Das ist die normale Log, die bei jedem Spiel neu erzeugt wird? Die hängt oben an der ersten Nachricht über den Bildern.

**Comment by Axel32019** [comment]
Sorry, bin  durcheinander gekommen.
In den Debug-Einstellungen von AD den Haken bei Sensoren setzen.

**Comment by TobiHH78** [comment]
Wo finde ich denn diese Einstellungen? Habe im AD-Menü dazu nichts finden können.
Bei CP gibt es da einen Punkt Vehicle Debug, den meinst du aber vermutlich nicht, oder?

**Comment by Axel32019** [comment]
Siehe hier: https://www.youtube.com/watch?v=AjeZ-scB0Vk

**Comment by TobiHH78** [comment]
Okay, werde ich versuchen. Vor dem Wochenende komme ich aber nicht dazu. In der Woche fehlt mir die Zeit zum spielen.

**Comment by TobiHH78** [comment]
Hatte nicht allzu viel Zeit das nachzustellen. Hatte nochmal CP/AD aktualisiert, und auf einem anderen Missionsfeld ist das Problem nicht aufgetreten. War natürlich dann auch ein anderer Drescher und andere Abfahrer, da ich die Geräte nutze die bei der Mission zur Verfügung gestellt werden. Glaube allerdings nicht, dass es ein Fahrzeugproblem gewesen ist.
Im 19er hatte ich diese Phänomen ebenso.

Anyway, in der halben Stunde Spielzeit lief es problemlos, ohne das ich an den Einstellungen etwas geändert habe.

**Comment by Axel32019** [comment]
@TobiHH78 Gibt's neue Erkenntnisse?

**Comment by TobiHH78** [comment]
Problem tritt tatsächlich sporadisch immer noch auf. Kann es nur leider nicht sicher reproduzieren.

![1](https://user-images.githubusercontent.com/56259322/167238621-d34ba093-662e-4b6f-ba6c-46e1497a60b7.PNG)

![2](https://user-images.githubusercontent.com/56259322/167238626-4f2d962c-1b49-44c6-8080-1710a42f24b2.PNG)

![3](https://user-images.githubusercontent.com/56259322/167238633-830a2c7a-09a4-4292-aa21-277e2386c2c2.PNG)

![5](https://user-images.githubusercontent.com/56259322/167238636-5cf16232-6d59-4d4e-ac36-5b0932bee80c.PNG)

![6](https://user-images.githubusercontent.com/56259322/167238644-db219c54-69ea-4ee7-b36e-e81cfb0c6194.PNG)

![7](https://user-images.githubusercontent.com/56259322/167238645-444d853b-ce05-4cc3-b15f-585001f2aa2e.PNG)

![8](https://user-images.githubusercontent.com/56259322/167238651-2b4af24b-7492-4e78-9c35-81cbf05386d5.PNG)

**Comment by RedGun1978** [comment]
Der Abfahrer kommt übrigens sofort zum Abtanken, sobald am Drescher die Geschwindigkeit runtergedreht wird. 

Beispiel: Drescher fährt mit 10 km/h (egal ob CP oder selber gefahren) und der Abfahrer fährt, wie im Bild oben, hinter dem Drescher her. Geschwindigkeit beim Drescher kurz auf 9 oder 8 km/h runter und der Abfahrer fährt sofort neben den Drescher und tankt ab.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
