### ISSUE TITLE
[Frage] ist die Kombination von zwei Autodrive Kursen möglich?

### ISSUE THREAD

**Issue by hermannbrauer** [Stephan-S/FS22_AutoDrive#393]
Hallo @Iwan1803,

du bist ja der Erklärbär hier, aber die Frage geht auch in die Runde der Entwickler. 

Ist es möglich zwei .xml zum kombinieren um aus zwei Autodrive Kursen .xml eine zu machen? Ziel ist es die Kruse aus beiden zusammen zubringen um nicht die erfolge von beiden zunichte zu machen.

In einer .xml sind die Kruse aus den splines  und Feldanbindungen, die andere hat Parkpaltzkonfigurationen.

Beide haben keine Kurse im Bereich des anderen!

Gruß Hermann

**Comment by Iwan1803** [comment]
Nein, sie können leider nicht kombiniert werden, da jeder Wegpunkt eine eigene ID hat und diese ja somit doppelt vorhanden sind.
