### ISSUE TITLE
Probleme beim befüllen der Gewächshäuser mit Wasser seit Patch 1.3

### ISSUE THREAD

**Issue by Hatschi99** [Stephan-S/FS22_AutoDrive#394]
Hallo liebes AD Team,

ich habe seit kurzem, vermutlich seit Patch 1.3 (vorher ist es mir zumindest nicht aufgefallen), folgendes Problem.
Beim befüllen der Gewächshäuser per Autodrive fährt das Fahrzeug nicht mehr weiter sobald das Gewächshaus komplett mit Wasser befüllt ist. **Aber nur wenn die Gewächshäuser zu diesem Zeitpunkt auch aktiv sind, also produzieren und somit auch Wasser verbrauchen.**
Schaltet man die Produktion **aus**, so das kein Wasser verbraucht wird, funktioniert alles wie gewünscht, hier fährt Autodrive dann zum nächsten Punkt seiner Liste und befüllt die Gewächshäuser abwechselnd (rotierend Entladen) mit Wasser.

Getestet habe ich das ganze auf einem neuen Spielstand auf der Karte Elm Creek und komplett ohne Mods, außer AD natürlich

Bitte entschuldigt wenn das schon gemeldet wurde, habe aber kein entsprechendes Issue dazu gefunden.

P.S.: Vielen Dank an das ganze Team für euren tollen Job den ihr hier in eurer Freizeit macht.

![20220228191725_1](https://user-images.githubusercontent.com/100615194/156038188-642c94a5-4ff1-4fb3-aa9c-63b977e613d6.jpg)
![20220228191745_1](https://user-images.githubusercontent.com/100615194/156038199-7897e2ff-2066-4cb2-a6c0-451567c0658a.jpg)
.

**Comment by Hatschi99** [comment]
Sorry, noch vergessen.
Im ersten Bild sind die Gewächshäuser aktiv und der Traktor bleibt stehen. Könnte das Problem mit dem "unloadDelayTimer" zu tun haben? Dieser taucht auf dem zweiten Bild beim die Gewächshäuser deaktiviert sind nämlich nicht auf.

**Comment by RalfGorden** [comment]
habe das selbe Problem mit den Gewächshäusern

**Comment by rohne83** [comment]
das dürfte damit zusammenhängen, dass die ja kontinuierlich Wasser verbrauchen, und damit auch immer wieder neues Wasser aus dem Fass gezogen wird. Hatte man im 19er bei den Tierställen zB genauso

**Comment by dominiczeth** [comment]
Das war auch vor Patch 1.3 so. 
Es müsste einen Trigger in AD geben, der erkennt dass es plötzlich langsamer läuft, aber das würde womöglich wieder an anderer Stelle probleme nach sich ziehen.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
