### ISSUE TITLE
Automatisch erzeugte Kurse nicht korrekt

### ISSUE THREAD

**Issue by Matrekus** [Stephan-S/FS22_AutoDrive#395]
Hallo,

ich habe die Kurse aus der Map erzeugt. Beim befahren fahren die Fahrzeuge nicht die Punkte sauber ab, sondern "hüpfen" von Punkt zu Punkt. Also immer Stop&Go.

**Comment by Iwan1803** [comment]
Auf welcher Map und mit welcher AD-Version? Screenshots der Strecke?

**Comment by Matrekus** [comment]
Wild West 16x - AD 2.0.0.4
![grafik](https://user-images.githubusercontent.com/100630918/156084336-f13acf78-1b43-4458-ad1e-efdf9022e84f.png)

**Comment by Tensuko** [comment]
Was ist in dem Bild nun falsch ?

**Comment by Iwan1803** [comment]
6 aktive Helfer, wenn ich das richtig sehe und die Wegpunkte sehen gut aus. Hast du den Mod "More Trees" am Start, welcher ordentlich Performance frisst?

**Comment by Matrekus** [comment]
@Tsenuko Nichts, denke Iwan wollte nur sehen, wo auf der Strecke das Problem besteht. Ich habe auch ein Video, aber das kann man hier nicht hochladen.

@Iwan1803 Ja, More Trees wird für die Funktion der Karte benötigt. Performance glaube ich fast nicht. Es sieht eher so aus, als ob die Traktoren beschleunigen und wieder abbremsen. Sind bei den Punkten auch Geschwindigkeiten hinterlegt? Ich meine, wenn man einen Kurs "langsam" einfährt (Kurve z.b.), dann fahren dort doch alle Fahrzeuge langsam?! Kann man diese Geschwindigkeiten manuell ändern... in der XML zum Beispiel? Oder das diese ignoriert werden?

**Comment by Iwan1803** [comment]
"More Trees" ist nicht zwingend erforderlich und zieht enorme Performens.
Wegpunkte haben keine Geschwindigkeitsbegrenzungen.
Ist die Kollisionshöhe vielleicht zu niedrig eingestellt?

**Comment by Matrekus** [comment]
![grafik](https://user-images.githubusercontent.com/100630918/156167707-c103cc54-66bf-4588-8155-56641c1392e3.png)
Da mit More Trees steht dort.. aber ich denke tatsächlich, dass es kein Performance-Thema ist. Dann würde der ganze Bildschirm ruckeln und nicht nur das Fahrzeug.. es ruckelt auch nicht, sondern fährt halt nur von Punkt zu Punkt und bremst dort wieder ab.
Kolliesionprüfung ist auf 1.25 - das war Standard so, denke ich.

**Comment by Iwan1803** [comment]
Stell die Höhe mal testweise auf 2m ein und schalt auch mal anderen Helfer aus.

**Comment by Matrekus** [comment]
Ok, werde ich dann mal versuchen.
Was macht eigentich der Pfadfindungsfaktor? Der steht bei mir auf 0,5?

**Comment by Guido19671** [comment]
Matrekus, falls aktiv deaktiviere  in den globalen Einstellungen die Kollisionserkennung, das hat bei mir das Problem behoben
