### ISSUE TITLE
How to rename a folder

### ISSUE THREAD

**Issue by dickybora** [Stephan-S/FS22_AutoDrive#396]
i've created some folders / groups for my waypoints, but found that cannot change the name of them
please help

**Comment by Joko-Ger** [comment]
You can rename it in the AutoDrive_config.xml file.
You have to edit every occurance of the group name.

C:\Users\<username>\Documents\My Games\FarmingSimulator2022\savegame

**Comment by dickybora** [comment]
Thanks Joko, already done
