### ISSUE TITLE
Zurücksetzen beim Drescher abtanken macht er nur manchmal.

### ISSUE THREAD

**Issue by Elias11022** [Stephan-S/FS22_AutoDrive#397]
Moin,
ich hatte mich so gefreut das der Abfahrer nach dem abtanken zurücksetzt um dem Drescher platz zu machen. (Wenn Rohr in der Frucht setzt CP zurück für Abfahrer) 
Nun habe ich eine Erntemission mit einem LKW und der setzt nicht zurück, so das der Drescher immer gegen den LKW fährt.
Kann man das irgendwo eistellen?

LG
Elias

**Comment by matze0301** [comment]
Was ich gestern beobachtet habe:
Entweder der Abfahrer meldet "Frucht verlassen", nur um dann direkt links in der Frucht auf den naechsten Ruf zu warten, oder der Abfahrer gibt kurz Gas, nur um dann **direkt** vor dem Drescher in der Frucht auf den naechsten Ruf zu warten, was dann natuerlich nie passieren wird.

So oder so, nicht das von mir erwartete und konfigurierte Verhalten.
CP oder AD Problem?

**Comment by Axel32019** [comment]
Hallo, Die Zusammenarbeit CP - AD ist hier noch in Arbeit, wird im nächsten Release besser laufen.

**Comment by Kitekater** [comment]
Was ich beobachet habe, dass CP nach dem Abtanken das Rohr nicht mehr einfährt, und daher auch anscheinend nicht das "Fertig, ab zum Zurücksetzen" Signal an AD geleitet wird.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
