### ISSUE TITLE
[Feature] Give us the ability to set wage as a per hour basis. 

### ISSUE THREAD

**Issue by talianagisan** [Stephan-S/FS22_AutoDrive#398]
The ingame wages are way way to high. 4200 an hour or so. Even at 50% wage thats a dollar every second or two. Can we have the ability to set the wages by hand? You don't use the ingame wage system so mods that edit that dont work. Although if we can edit an xml to set wages that would be nice to.

**Comment by Axel32019** [comment]
adjusted wage calculation based on ingame AIJobFieldWork, which might be influenced by other mods, so it gets calculated accordingly

**Comment by talianagisan** [comment]
Thank you very much that's the perfect fix as a mod to edit that value does exist. I can finally pay my workers so then can feed their families.
