### ISSUE TITLE
Seltsame Wegfindung beim Abfahrer

### ISSUE THREAD

**Issue by iljarogoff** [Stephan-S/FS22_AutoDrive#40]
Hallo,
ich weiß, der Mod steckt noch ziemlich in den Kinderschuhen, ich möchte aber diese Beobachtung teilen, da es noch nicht optimal läuft:
Ich lasse den Drescher von AD abtanken, dabei zieht der Abfahrer, sobald er gerufen, ziemlich umständliche Bahnen, habe es mal auf den Bildern illustriert:
![fsScreen_2021_12_20_17_18_42](https://user-images.githubusercontent.com/21023840/146799780-aedf6d70-a381-43d0-a593-c509803c5aa7.png)
![fsScreen_2021_12_20_17_19_05](https://user-images.githubusercontent.com/21023840/146799786-def5b7a8-52cb-46cc-b7e2-5234185b8059.png)
![fsScreen_2021_12_20_17_19_19](https://user-images.githubusercontent.com/21023840/146799789-6073f09d-ee89-44a5-9907-41139bc43550.png)
![fsScreen_2021_12_20_17_19_30](https://user-images.githubusercontent.com/21023840/146799793-252a20d7-928b-495a-b077-1e8e15a02b95.png)
![fsScreen_2021_12_20_17_19_43](https://user-images.githubusercontent.com/21023840/146799799-871aab7c-c831-4cdb-b9d8-977c237d6d2e.png)

Auch sonst zieht der Abfahrer seeeehr weite Kreise, um parallel zum Drescher zu kommen, oftmals ist der Drescher bis dahin schon am Feldende angekommen und wendet, weil der Abfahrer einfach zu lange braucht.

**Comment by Stephan-S** [comment]
So so, in den Kinderschuhen steckt AD also noch :D

Ich werde mich da demnächst aber eh mal dran setzen.

**Comment by iljarogoff** [comment]
Ich meinte doch in Bezug auf LS22 :) habs blos blöd ausgedrückt
Beim LS19 war die Pfadfindung eleganter.
Ansonsten muss ich sagen, sehr geil, was ihr da auf die Beine gestellt habt, und das in so kurzer Zeit. Danke!

**Comment by Stephan-S** [comment]
Ich habe gerade in meinem branch ein Update gepusht.
Wenn du weißt wie du dran kommst und dir selber zippen kannst, dann kannst du es gerne mal ausprobieren :D

**Comment by iljarogoff** [comment]
Bin jetzt auf deinem Branch und hatte eben die Möglichkeit, das Abtanken zu testen. Gefällt mir ziemlich gut, auch dass er immer in der Nähe des Dreschers bleibt und ihn begleitet.
Falls es Probleme gibt, würde ich mich wieder melden.

**Comment by iljarogoff** [comment]
Was mir jetzt aufgefallen ist - vielleicht ist das so gewollt? Der Abfahrer ist eingestellt, dass er bei 85% zum Abladepunkt fahren soll. Das macht er nicht, war nach der letzten Abtankung bei 88%, ist dann wieder dem Drescher gefolgt und wurde dann bei der nächsten Wende des Drescher bis auf 100% befüllt. Ich finde es ok, aber die Frage ist, Bug oder Feature?
