### ISSUE TITLE
Unterordner

### ISSUE THREAD

**Issue by MacRama1** [Stephan-S/FS22_AutoDrive#400]
Hallo AD-Team,
danke für Autodrive und all die tollen Funktionen, leider vermisse ich die Möglichkeit Unterordner zu erstellen.
Im Multi hat jeder seine eigenen BGA's, Produktionen etc.
Da hat sich mittlerweile eine ganze Menge an Ordnern für jeden einzelnen angehäuft.
Es wäre wirklich schön wenn jeder seine Ordner in seinen eigenen Ordner verschieben könnte. (Das hat schon im 19er gefehlt)
Als kleines zusatz-Feature wäre vllt. noch ne Farbauswahl nett welche sich jeder selbst zuordnen kann aber das ist zweitrangig.
Viel wichtiger sind einfach Unterordner, Bitte...

Und bekommen wir den Schaufelmodus auch wieder?
Viele Grüße Mac

**Comment by Iwan1803** [comment]
Es ist nicht geplant, den BGA-Modus wieder zu aktivieren, da er zu viele Probleme machte und zudem auch nur eine frühe Beta war.
Bzgl. Unterordner: siehe #215 
Da somit doppelt -> geschlossen!
