### ISSUE TITLE
Blocked route

### ISSUE THREAD

**Issue by Bovrinox** [Stephan-S/FS22_AutoDrive#401]
The amount of times I've set a driver off on an autodrive route, only to realise the clown has been sat going nowhere for the last hour. Please, for all our sakes, add a notification when the route is blocked.  Just a simple line saying something along the lines of "driver of x cant move forward" or some thing like that. Its extremely annoying to think your driver is off on a job while you do something else, only to discover its been sat with the engine running doing nothing haha

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/issues/399
