### ISSUE TITLE
Falsche Einstellungen bei der Zuckerrohrernte ?

### ISSUE THREAD

**Issue by Noggele** [Stephan-S/FS22_AutoDrive#403]
Hallo zusammen,

ich das Problem, bei der Zuckerrohrernte, dass der Ernter und der Abfahrer nicht in einer Linie fahren, sondern der Abfahrer ein Stück hinterher. So kommt das Rohr nicht über den Anhänger.
Mache ich bei den Einstellungen etwas falsch? 

Liebe Grüße

**Comment by Noggele** [comment]
Hallo, 

ja das ist der Giants Ernter, gibt ja glaub ich nur diesen.. 
Das beste was ich hinbekomme ist, dass der Ernter mit ca. 2-4 kmh fährt und dann auf den Abfahrer wartet. Dann wieder 1-2m weiter, usw. 
Ich glaube, würde der Abfahrer etwas weiter vorfahren, würde es flüssiger gehen. 
Aber vielleicht ist es auch mein Fehler und die Einstellungen passen nicht.. 

Liebe Grüße
![Zucker2](https://user-images.githubusercontent.com/101008421/158038211-6581925e-dbdd-4667-8bd2-ccbccea468b3.jpg)

**Comment by Axel32019** [comment]
Hallo @Noggele , Versuch den mal selbst abzutanken...
Da ist zu viel Bewegung in der Abladeposition, die von mehreren Faktoren abhängt - hab da schon mehrere Stunden investiert um das hinzubekommen, kein wirklicher Erfolg.
Fazit: bleibt momentan so wie es (nicht) geht.

**Comment by Noggele** [comment]
Schade das es schon geschlossen wurde, 

ich hätte nach langem probieren eine kleine Lösung gefunden, falls andere ein ähnliches Problem haben :(

LG
