### ISSUE TITLE
Exiting a field

### ISSUE THREAD

**Issue by Will-Smith1965** [Stephan-S/FS22_AutoDrive#405]
When changing field s after job has finished would it be possible to exit at the entry point as at the moment it goes accross the other fields and through the hedges, ditches etc to get to the next field instead of exiting at the entry point and following a route to get there, many thanks for the hard work you all put in to make this game much better.

**Comment by Axel32019** [comment]
How should we know the entry point of the field job if you change the target? AD has no brain or history for such idea!
Solution: Look how to create a "exit"-route around a field in YT etc. Use closest exit in the settings

**Comment by Will-Smith1965** [comment]
ok that seems that it has no memory but it does not even pick up a route after going through the ditch/hedge even if one is there it still goes across multiple fields ditches hedges to get to the next target if set to nearest point you do great work on this program What about when the task is finished return to the entry point if driven there by ad in the first place like when the seeder runs out of seeds it returns to the entry point to pick up a route to go and refill and returns to the field to carry on where it left off unload combine drives on the field and returns to the entry point to go do the delivery then returns so i would imagine the answer to your question of HOW DO WE KNOW WHERE THE ENTRY POINT IS  is already in the program it just needs finding give me time to learn a bit more and i may be able to help solve the problem but for now i leave it in you hands

**Comment by Axel32019** [comment]
As I told: If you change the field, AD do not know anymore which is the entry to the field it is on. So it tries to find a way to the first target in HUD, depending on the field exit settings!
