### ISSUE TITLE
how to get all headlights and worklights turned on when autodrive is turned on?

### ISSUE THREAD

**Issue by kf6shc** [Stephan-S/FS22_AutoDrive#407]
please advise of how i can turn on all headlights, highbeams and worklights on all vehicles globally with one setting change?

thank you

**Comment by rohne83** [comment]
Afaik there is no such setting and I don't see any need to add it. Lights are turned on automatically as for other helpers. Normal lights on roads, and work lights additionally on the field. No high beams used.

**Comment by Iwan1803** [comment]
As rohne83 said: there is no need for that and so we will not integrate that, sorry.

**Comment by kf6shc** [comment]
That’s an opinion. A wrong one at that. I guess I will do it myself since I can’t see in the dark

-Sean

**Comment by Iwan1803** [comment]
If the helper is driving the vehicle, he could do this without any light. So why do you need to be able to see anything if you are not the driver? 🙄
Why should we always adjust AD when only one person has a personal (luxury) problem?
