### ISSUE TITLE
Probleme mit der neusten Dev-Version vom 08.03.2022 beim Strohabfahren

### ISSUE THREAD

**Issue by PanikPitty** [Stephan-S/FS22_AutoDrive#408]
Nach dem gestrigen Update funktioniert das abfahren von Stroh vom Feld zur BGA bei mir nicht mehr.  Gewählkter Modus ist dabei "Abholen und Abliefern" mit aktivierter Curseplayübergabe.
Nachdem das Stroh mit Curseplay gesammelt wurde, fährt der Abfahrer zum "Aufladepunkt" und hängt sich dort auf. 
Es erfolgt dann immer wieder der Aufruf "Fahre zum Aufladepunkt" und nicht der Wechsel zu "Fahre zum Abladepunkt". Es erscheint dann fortlaufend die Meldung "Helfer hat die Arbeit gestoppt - Gerät ist voll!".
Nachdem sich der Traktor dann am Aufladepunkt vorbei geruckelt hat, geht es wieder auf das Feld und das ganze beginnt von vorn. (Fahrt zum Aufladepunkt -> Fehler  -> zurück auf das Feld)
Die log.txt hänge ich gleich mal mit an
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8213579/log.txt)
.

**Comment by rohne83** [comment]
Nur eine Vermutung, aber kann es sein dass du den Abfahrfüllstand zu hoch eingestellt hast? CP übergibt aktuell immer bei 95% Füllstand. Wenn die AD-Einstellung dafür aber auf 99 oder 100% gestellt ist, würde AD ihn immer wieder erneut zum Feld schicken wollen statt zum Abladepunkt.

**Comment by Axel32019** [comment]
Dann ist das ja klar -> closed
