### ISSUE TITLE
Kein Motorsound

### ISSUE THREAD

**Issue by MacRama1** [Stephan-S/FS22_AutoDrive#409]
Hallo AD Team, 
manchmal haben Fahrzeuge keinen Motorsound, es passiert in den unterschiedlichsten Situationen. 
Fast immer wenn CP bei der Feldarbeit Saat, Dünger etc.:-Tank leer wird und AD dann zum auffüllen das Fahrzeug übernimmt verschwindet der Sound. Sämtliche Umweltgeräusche sind nicht davon betroffen. Sobald AD das Fahrzeug zurückbringt und CP wieder übernimmt ist im selben Moment der Übernahme der Sound wieder da.

Da ich zuerst glaubte CP löse das ganze aus, habe ich mich vor einigen Tagen damit auch dorthin gewandt. Tensuko hat sich unsere Logfiles angesehen und konnte CP als Auslöser ausschließen.
Das CP nicht der Auslöser dafür ist, erschloss sich mir als ich durch meine Fahrzeuge tabbte und bei einem Traktor, welcher von AD einfach von A nach B überführt werden sollte ohne Motorsound unterwegs war.

Heute, ich meine es war gegen 21:30Uhr,  war mein Claas Arion 660 mit einem Claas Kipper beim Ernten den Drescher am abtanken. Auf dem Weg zum Silo war wieder der Sound verschwunden.

Dedi-Log und Client-Log im Anhang
[game.log](https://github.com/Stephan-S/FS22_AutoDrive/files/8218233/game.log)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8218234/log.txt)

Grüße Mac

**Comment by Iwan1803** [comment]
Was mir gleich am Anfang der log.txt auffällt:
Error: Unsupported mod description version in mod **FS19**_Agramark_American_Garage_Workshop
Error: Unsupported mod description version in mod **FS19**_fertilizerTankVD
Error: Invalid mod name 'FS22_BaNe-main'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Dazu kommt noch:
- mehrere Maps im mods-Ordner, u.a. CountyLine, Frankenmuth_Map, Wild West
- mehrfach ähnliche Mods vorhanden, wie z.Bsp. Fliegl DPW180, Strautmann, moretrees oder auch placeAnywhere
- LUA call stacks ohne Bezug auf AutoDrive
Du solltest vielleicht erstmal deinen mods-Ordner ordentlich ausmisten, bevor man dir überhaupt helfen kann. So ist es wie die Suche nach der Nadel im Heuhaufen, welcher Mod u.U. für dein Soundproblem sorgt.

**Comment by dominiczeth** [comment]
Hi, nur kurze Info dass ich das Problem ab und an auch habe. 
Es ist als ob der Motor nicht richtig gestartet wurde. Ich denke folgendes passiert: 
AD erreicht endpunkt, schaltet dort Motor ab, CP schaltet Motor auf der Stelle wieder ein. (Kann man manchmal auch hören).
Ab und zu führt das zu dem beschriebenen verhalten. 
Lösung wäre, dass AD den Motor, bei eingestellter CP-Verbindung, nicht am Zielort abschaltet.

**Comment by MacRama1** [comment]
> Was mir gleich am Anfang der log.txt auffällt: Error: Unsupported mod description version in mod **FS19**Agramark_American_Garage_Workshop Error: Unsupported mod description version in mod **FS19**fertilizerTankVD Error: Invalid mod name 'FS22_BaNe-main'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit Dazu kommt noch:
> 
> * mehrere Maps im mods-Ordner, u.a. CountyLine, Frankenmuth_Map, Wild West
> * mehrfach ähnliche Mods vorhanden, wie z.Bsp. Fliegl DPW180, Strautmann, moretrees oder auch placeAnywhere
> * LUA call stacks ohne Bezug auf AutoDrive
> 
> Du solltest vielleicht erstmal deinen mods-Ordner ordentlich ausmisten, bevor man dir überhaupt helfen kann. So ist es wie die Suche nach der Nadel im Heuhaufen, welcher Mod u.U. für dein Soundproblem sorgt.

Hallo  Iwan,
danke für deine schnelle Antwort. 
Habe jetzt sämtliche Mods aus meinem lokalen Modordner rausgeschmissen und ausschließlich relevante Server-Mods drin.
Werde das ganze jetzt noch mal beobachten und mich ggf. noch mal melden.
