### ISSUE TITLE
 Warning (script): 'playSample' D:\auto_builder\cache\svn\

### ISSUE THREAD

**Issue by Memdor** [Stephan-S/FS22_AutoDrive#41]
Ich habe einige Warnungen in der LOG die sich ständig wiederholen:

2021-12-20 15:10 Warning (script): 'playSample': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2021-12-20 15:10   D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\base\scripting\lua\LuaScriptSystem.cpp (890): expectedType == Value::VoidType || expectedType == Value::ClassType
2021-12-20 15:10 LUA call stack:
  =C:/Users/golda/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/UtilFuncs.lua (1380) : playSample
  =C:/Users/golda/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Manager/GraphManager.lua (671) : playSample
  =C:/Users/golda/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrafficSplineUtils.lua (114) : recordWayPoint
  =C:/Users/golda/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrafficSplineUtils.lua (24) : createWaypointsForSpline
  =C:/Users/golda/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/AutoDrive.lua (444) : adParseSplines
  dataS/scripts/BaseMission.lua (1304) : update
  dataS/scripts/FSBaseMission.lua (2006) : update
  dataS/scripts/missions/mission00.lua (582) : update
  dataS/scripts/main.lua (1323) : update

Ich habe gar keinen Ordner: D:\auto_builder

Gibt es vielleicht schon ein Lösung, die man selbst anwenden kann?
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7746827/log.txt)

**Comment by Iwan1803** [comment]
Sieht wie das Problem hier aus: https://github.com/Stephan-S/FS22_AutoDrive/issues/4
Wird im nächsten Release gefixt sein.
