### ISSUE TITLE
Script Error in Settings.lua (984)

### ISSUE THREAD

**Issue by Plopsi** [Stephan-S/FS22_AutoDrive#410]
We experienced a problem with the following log output today (hanging server):

2022-03-10 00:27 Error: Running LUA method 'update'.
config/mods/FS22_AutoDrive/scripts/Settings.lua:984: attempt to index field 'ad' (a nil value)

Looking on the specific line at https://github.com/Stephan-S/FS22_AutoDrive/blob/main/scripts/Settings.lua#L984 I think that `vehicle.ad` wasn't set that moment.

As I'm complete unsure why this would or could happen (timing as usual?) maybe a additional check would make sense here?

- Plopsi

**Comment by Iwan1803** [comment]
_In my car a red light is blinking and now tell me, what is the problem..._ 🙄

What did you do when the error comes up? Log file from client and server?

**Comment by Plopsi** [comment]
If you think it helps ;) - as it just spams til AD was deactivated on the vehicle.

As the client logs got overwritten if a game restart they would be of no help but here is the server log in the timeframe from hang to release by finding and deactivating AD on the vehicle (as always its funny that you can switch and walk/run by foot while update fails)

[server.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8219369/server.txt)

- Plopsi

**Comment by Axel32019** [comment]
At least I have never seen an error at this point, the log is not complete, so there might be something going wrong a time before.
Please add the complete log.

**Comment by Plopsi** [comment]
I didn't want to spam up a 15MB log, but here it is:

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8227277/log.txt)
(starts at 2022-03-10 00:27 line 94308)

I also never saw such an error up to now, up to now also never again. Also from the logs it seems to just start out of nowhere, and stopped after the vehicle causing it deactivated AD. Worked after activating AD as it should.

**Comment by Axel32019** [comment]
@Plopsi Thanks for the log, this shows much more!
From AD I could not see any issue which might cause it, but might be the lua errors before caused the system to come in a unnormal state:
2022-03-10 00:22 :43 [info lp714476] 942 Vario/723: stop message: AI worker %s has stopped work unexpectedly - tank is full!
2022-03-10 00:22 Warning (script): 'streamWriteInt32': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2022-03-10 00:22   D:\auto_builder\cache\svn\0ebd205709dafcdbd3fef400d64b8406\src\base\scripting\lua\LuaScriptSystem.cpp (903): expectedType == Value::VoidType || expectedType == Value::ClassType
2022-03-10 00:22 LUA call stack:
...
  =config/mods/FS22_Courseplay/scripts/specializations/CpAIWorker.lua (136) : superFunc

**Comment by Plopsi** [comment]
Interessting.. but 5minutes?

But yeah this superfunc error appears more often since CP 7.0.1.4. I will keep an eye on it, if it happens again.

- Plopsi
