### ISSUE TITLE
Unloader doesn't stop Unloading Moving Combine

### ISSUE THREAD

**Issue by dominiczeth** [Stephan-S/FS22_AutoDrive#411]
Hello. 
I still have the problem that the Unloader from a Combine doesn't stop while Combine is moving.
It will drive under the pipe until the trailer is full. 
I use it with CP version 7.0.1.3, active unloading is selected. 
When i choose in CP Settings to stop the combine while unloading, it works fine. 
Also when i drive by myself and retract pipe it also stops following the combine and stops on the field, like it should. 
Tested with Version 2.0.0.4 and also with 2.0.0.5RC on a new Savegame without any mods except CP and AD. 

Tried to look into the script, i only found out that there is an condition for the filllevel for unloading while Combine is stopped, not while it's moving, could this be a Problem?

**Comment by Iwan1803** [comment]
If you set active unloading to yes in the combine settings, the unloader will drive under the pipe if it is open.
So it's ok for the unloader to chase the combine in that case. Please check your combine setting.

**Comment by dominiczeth** [comment]
Will test it. But i think i also tested it with deactivated active unloading Setting and had the same result. 
Will check it this afternoon.

**Comment by dozerjz** [comment]
I am having the same issue with the unloader following along with the combine for the whole run, even after the combine has hit 0.  I am running modded equipment, so i kept my comments to myself :)

**Comment by Invr4get** [comment]
Isn't that a normal action as long as you have your pipe out?

**Comment by Crinouche** [comment]
I think it's good that the tractor follows the harvester while driving, but it is true that it would be good if the tractor stops when the harvester is empty. I agree with bulldozerjz

**Comment by Iwan1803** [comment]
Set "active unloading" for the harvester to "no" and the unloader will not chase the open pipe. If it is set to "yes", he will chase the open pipe. You can also set an option for the pipe in CP. So where is the problem now?

**Comment by dominiczeth** [comment]
Ok it's right. Active Unloading to "No" pretends that behaviour. 
One thing i noticed: When set to "No" the unloader takes much more time to drive to the combine. He drives a much longer route, why is there a difference? As far as i understand the pathfinder is the same no matter if Active Unloading is "Yes" or "No"?

**Comment by Iwan1803** [comment]
If the unloader is called because of the fill level, it will drive 1st to the destination where the call was done and from there then to the harvester.

**Comment by dominiczeth** [comment]
Is there a way to make that faster? Or is it possible that the unloader just follows the combine with a distance from about 30-50m until the call?

**Comment by Iwan1803** [comment]
Many requests here are based on the wishes or problems of individuals. Don't misunderstand, but we can't implement everything because of this. The process with the unloader is complicated enough.
Everyone can set for themselves and their different combine and bunker sizes when the unloader should come it (fill level) OR that they should be unloaded directly during the harvesting process. If you can wait a few seconds for the unloader, you can use the first option, and if you don't want to, you can use the second.
If i'm not wrong, for the first option the unloader will chase the combine after it has reached the 1st destination.
