### ISSUE TITLE
AD fährt immer noch ein zweites Mal rückwärts ins Keilsilo - was mache ich falsch?

### ISSUE THREAD

**Issue by DemsMani** [Stephan-S/FS22_AutoDrive#414]
Hallo zusammen
Ev. wurde die Frage schon mal beantwortet, ich habe aber leider nichts gefunden: Bei mir fährt AD nach dem korrekten Abladen im Keilsilo  aus dem Silo raus, aber dann gleich nochmals zurück ins Silo, meistens voll auf den Haufen drauf und bleibt so manchmal auch stecken. Ev. ists ein Fehler beim einfahren, aber was genau weiss ich leider nicht. Hat jemand eine Idee was das sein könnte?

**Comment by Plopsi** [comment]
Das hatte ich auch. das liegt am abfahrpunkt wieder raus, den kriegter dann nicht gegriffen - warum auch immer. Ich empfehle am obersten punkt (da wo er von rückwärts wechselt eine abfahrstrecke hinzuzufügen.

![grafik](https://user-images.githubusercontent.com/17942998/158008732-17ab2438-55bc-45c0-95a8-06fe11f1a3a2.png)

Ich denke das grün-blau-grüne system hast du, oder? Bau noch eine Fluchtstrecke (Gelb-Orange) dazu, dann kommt er immer raus. (sry, ist etwas krakelig :D)

- Plopsi

**Comment by DemsMani** [comment]
Wow, danke für die ausführliche Erklärung und die zwar krakelige, aber sehr gut erklärende Skizze. Werde ich so ausprobieren.
Beste Grüsse
Mani

**Comment by andreasthu** [comment]
eine möglichkeit ist noch, die Strecke rückwärts und wieder raus nicht als zwei strecken zu nehmen, sondern nur eine Beidseitig befahrbare zu machen,
mario hirschfeld hat da im 19er mal ein video von auf youtube gestellt
lg
andreas

**Comment by RalfGorden** [comment]
https://www.youtube.com/watch?v=h9HxOlC9hPQ&list=PL5cOkXj5iscrkh_7Iz6IFOt5oyP732sAZ&index=17

viel besser

**Comment by DemsMani** [comment]
Danke euch!
