### ISSUE TITLE
AD Stopping at ditches around US map

### ISSUE THREAD

**Issue by Covakel** [Stephan-S/FS22_AutoDrive#416]
Good Day AD Team, 
First, thank you very much for this mod, it is an excellent addition to Farming Simulator. 

I've been experiencing a bug recently where my vehicles are stopping when they try to go through the ditches surrounding the US map starting farm (see images 1 & 2). The bug also sometimes happens near the covered bridge on the US map (image 3), but not as consistently. 

Image 1:
![FarmingSimulator2022Game_8X7rc1AiQS](https://user-images.githubusercontent.com/10922576/158221093-0cfccade-c1d7-48ee-ad12-7ef0931f2d72.jpg)

Image 2: 
![FarmingSimulator2022Game_bjP1eqmFVc](https://user-images.githubusercontent.com/10922576/158221098-d58c9e0a-304f-4fcc-8696-3c12f2967d31.jpg)

Image 3:
![FarmingSimulator2022Game_GHQI6Ot2p1](https://user-images.githubusercontent.com/10922576/158221886-ab4ab714-bb99-4290-b95c-12b71ad4f238.jpg)

Should you require further information, please let me know. Again thank you very much for the mod.

**Comment by Iwan1803** [comment]
In the global AD settings, set collision heigt to 2 or 2,25m.

**Comment by Covakel** [comment]
> In the global AD settings, set collision heigt to 2 or 2,25m.

Thank you @Iwan1803 I'll give it a try.

**Comment by Covakel** [comment]
Looks like that solved the problem, thanks.
