### ISSUE TITLE
[Feature Request] Set minimum amount for cart to move on after delay.

### ISSUE THREAD

**Issue by talianagisan** [Stephan-S/FS22_AutoDrive#417]
So emptying a cart is impossible sometimes filling up my grain truck. The cart waits and waits and waits and blocks the truck from arriving due to 300l left of grain inside. Is this something we can set like... percent minimum to ignore or etc. I should use a motherbin but i cant afford it ingame.

**Comment by Iwan1803** [comment]
If your transfer truck is blocking the truck, then maybe you should adjust your route or am i misunderstanding the problem?

**Comment by talianagisan** [comment]
> If your transfer cart is blocking the truck, then maybe you should adjust your route or am I misunderstanding the problem?

You are entirely correct. However I don't have room to adjust the route. So hence why I am asking for the ability to have it so the cart moves on if it cant empty its entire load. 

As of right now it will sit there waiting till it gets down to 0 before moving on and block the truck from circling around, I'd like the ability for it to ignore a certain amount in the trailer and move back to its rest/wait location if it cant empty its entire load. 

So instead of waiting for 0% it moves to home with 1-3% left in the trailer. It's not a big deal having to babysit and click continue but at the same time it would be a nice feature.

**Comment by Iwan1803** [comment]
There is no room to adjust the root? Could you should post a screenshot of it? Maybe moving the lines a little bit could help.

**Comment by talianagisan** [comment]
I'll have to redesign the loop to do that. Oh well.

**Comment by Axel32019** [comment]
@talianagisan I do not understand the issue . Please add a screenshot of the situation.

**Comment by Axel32019** [comment]
no update -> closed
