### ISSUE TITLE
Mod Conflict - Grease Addon

### ISSUE THREAD

**Issue by dozerjz** [Stephan-S/FS22_AutoDrive#418]
Good Morning!  I wanted to bring to your attention that there is a conflict with the grease addon, where the vehicle will drive to the unload point, unload the material, but stays at the unload because it thinks the "grease" needs to be unloaded as well. Just wanted to let you know. Thank you for all you do!

**Comment by jeje3537** [comment]
Same thing happened to me. The FS19 version of AD with the crosetto pack (which has the grease addon built-in) worked well

**Comment by Axel32019** [comment]
Hello @dozerjz , @jeje3537 , If you are able you might test in the dev version - will help us to get it working!
https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

**Comment by jeje3537** [comment]
Soory for the delay. Played a little with this version too and can confirm all is working as intended. Thank you.
