### ISSUE TITLE
Pfadfindung zum Drescher lädt zu früh

### ISSUE THREAD

**Issue by NeonRider1999** [Stephan-S/FS22_AutoDrive#419]
Hallo. Ich habe ein Problem. Ich habe einen Moddrescher bei dem das Rohr verzögert Ausklappt wenn er mit cp Gesteuert wird.
Das Problem ist daran das die Pfadberechung nicht auf das Ausgeklappte Rohr Berechnet wird sondern auf das Eingeklappte Rohr(SIehe nachfolgende Fotos)
Verwendend wird die 2.0.0.5 RC

![fsScreen_2022_03_17_19_40_11](https://user-images.githubusercontent.com/80832669/158873905-0252f93b-2b79-49bf-a10f-3a8a4baf4e5b.png)
![fsScreen_2022_03_17_19_39_44](https://user-images.githubusercontent.com/80832669/158873962-221bbc87-830f-4d70-84ed-e77311239473.png)

Ist das Rohr dann aber Ausgeklappt und man Stoppt und Startet den Helfer neu klappt die Pfadfindung Perfekt
![fsScreen_2022_03_17_19_40_33](https://user-images.githubusercontent.com/80832669/158874087-5c60d518-ef8c-48d7-a05c-3984ad252811.png)

Log:
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8289310/log.txt)

Sry das die Bilder im Dunkeln sind hoffe man erkennt trotzdem das Problem

**Comment by Axel32019** [comment]
Hallo @NeonRider1999 , Ich sehe hier kein Problem: Ab 90% Füllstand im Drescher klappt dieser das Rohr ein, damit der Abfahrer nicht darunter fährt, da CP gleich eine Tasche dreschen könnte. Er wartet bis der Drescher steht, das Rohr ausgeklappt hat und fährt ihn erst dann an.

**Comment by NeonRider1999** [comment]
Das Problem ist das der Drescher nicht sofort bei 100 % ausklappt. Er berechnet den Pfad eher wie der Drescher das Rohr asugeklappt hat. Ist Kompliziert zu schreiben. Könnte ich mal bei euch auf Dc vorbeikommen um das mal richtig zu erklären. Video hochladen ist meine Internetleitung zu schlecht

**Comment by Tensuko** [comment]
@Axel32019 wir müssten mal über mögliche abläufe sprechen und wie diese zu lösen sind.
Wir wissen, wann der Drescher das Rohr nicht in der Frucht hat, einem Abtanken in der Situation spricht nichts dagegen.

**Comment by NeonRider1999** [comment]
Nochmal Bilder zur Problematik

Drescher hat die Tasche ausgedroschen und Klappt Rohr aus (soweit so gut)
![fsScreen_2022_03_19_11_31_56](https://user-images.githubusercontent.com/80832669/159117544-236a1d34-6d87-4e1c-9951-9c8a8ba91203.png)

Rohr ist noch nicht Ausgeklappt da wird der Pfad schon berechnet der voll in den Drescher rein geigt
![fsScreen_2022_03_19_11_32_02](https://user-images.githubusercontent.com/80832669/159117580-11f16ed7-bc6d-4382-bfd0-c0c81e67c886.png)


Er brechnet den Pfad dann auch nicht neu sonder Fährt dann auch in den Drescher hinein

**Comment by Axel32019** [comment]
Solche Konfigurationsmöglichkeiten hatten wir bisher noch nicht gesehen, daher das Verhalten.
Kann gern in dev Version überprüft werden.

**Comment by NeonRider1999** [comment]
Also bis jetzt läuft es super
