### ISSUE TITLE
I have a trouble in game with autodrive 2.0

### ISSUE THREAD

**Issue by criss20ster** [Stephan-S/FS22_AutoDrive#42]
I have this errol log in my game 

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7747699/log.txt)

**Comment by Iwan1803** [comment]
See also https://github.com/Stephan-S/FS22_AutoDrive/issues/41

**Comment by Axel32019** [comment]
Same as #41 -> closed
