### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by fuggo2** [Stephan-S/FS22_AutoDrive#421]
Dear Developers

I would have a functional idea to empty the stone picker. The current function is to fill, here you can specify the place where the AD should go and then where to load the trailer and what, in the same solution, the function would not only be filling but emptying, so that if the compiler is full in the given number country then take it to empty and then return to the given number of lands to continue the work. I took a screenshot of the feature to see what it would look like and attach the original feature that is currently available.
I have tried the Fill-Empty function but they don't really work because it goes to the ground but if the compiler does not deliver it just waits until I intervene manually

![stone picking emptying function](https://user-images.githubusercontent.com/66201069/159135766-0852906e-12bc-46f0-8667-f168cf3075e8.png)

I hope I wrote it pretty understandably even though my English was borrowed from google :)

**Comment by Axel32019** [comment]
Hello @fuggo2 , For me it is not clear what you mean. 
Do you request AD to collect stones from a field itself? Without the help of CP, AIVE or build-in helper?
For collecting stones on a field you may use CP, which will handover to AD if the stonepicker is full. AD will drive from the field, deliver to the destination (unload), return to field and pass back to CP, which will continue to collect the stones.

**Comment by fuggo2** [comment]
_"For collecting stones on a field you may use CP, which will handover to AD if the stonepicker is full. AD will drive from the field, deliver to the destination (unload), return to field and pass back to CP, which will continue to collect the stones."_ <- **Yes** this would be the essence of the function, so I set the cp to collect the stone in the "X" field, then take it with AD to the "Y" place where you unload it, then return with AD to the "X" field where he continues to stone with the CP where he stopped. Like when the seed runs out of seed, it goes to fill and then returns and continues its task

**Comment by Axel32019** [comment]
Setup AD in pickup and deliver mode, see: https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-HUD-Button
Still something unclear?

**Comment by fuggo2** [comment]
I tried, but when the stonemason is full, it doesn't go emptying, only when I intervene manually, I made a quick video to see the setting, but when the stonemason is full, it just stands and waits, it doesn't deliver the stone. is it possible that some settings are still missing?

[https://youtu.be/qjVUn0MTMRM](url)

**Comment by Axel32019** [comment]
Sorry, missed that this is still TODO from CP: https://github.com/Courseplay/Courseplay_FS22/issues/1226

**Comment by Axel32019** [comment]
Implemented in dev -will be part of next release.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
