### ISSUE TITLE
Abholen und Abladen mit Ladewagen

### ISSUE THREAD

**Issue by SchorschiBW** [Stephan-S/FS22_AutoDrive#422]
Beim Versuch, mit dem Ladewagen Krone ZX560 im Modus "Abladen und Abliefern" Hächselgut zu holen, musste ich feststellen, dass er mit Autodrive kein Hächselgut laden möchte. Der Ladewagen kann es, beim Abfahren des Hächslers mit Autodrive lässt er sich auch mit Hächselgut füllen und er lässt sich am entsprechenden Trigger auch manuell füllen. Nur eben nicht per Autodrive

**Comment by Axel32019** [comment]
Bitte Screenshot mit aktiviertem AD-Netz und link zum Ladewagen Krone ZX560 anfügen

**Comment by SchorschiBW** [comment]
Tja, ich weiß nicht, was ich sagen soll, aber als ich es reproduzieren wollte, um einen Screenshot zu machen, funktionierte es auf einmal. Es war übrigens der Ladewagen aus dem Spiel, also kein Mod.
Und ob es am Traktor liegen könnte, müsste ich die Tage nochmal nachprüfen, beim Versuch, es nachzustellen, hatte ich einen andren Traktor  gemietet

**Comment by Axel32019** [comment]
Also ich habe keinen Ladewagen Krone ZX560 im Spiel, doch ein mod?

**Comment by SchorschiBW** [comment]
Du hast Recht, es ist ein Mod. Ich habe ihn mit dem 520 GD verwechselt. Mein Fehler.

Wie gesagt, im Moment funktioniert es, ich werde aber versuchen, es nachzustellen

**Comment by SchorschiBW** [comment]
Okay, ich konnte es reproduzieren.

Es ist der Ladewagen:

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234614&title=fs2022https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234614&title=fs2022

![Landwirtschafts-Simulator 22_2022 03 21-08 25](https://user-images.githubusercontent.com/16411797/159219717-5551c1ab-a2ee-45d6-9d7a-3010a7eeb949.png)
![Landwirtschafts-Simulator 22_2022 03 21-08 25_1](https://user-images.githubusercontent.com/16411797/159219725-d3b5c2c5-c0b8-44dc-87e2-81213adbbbdd.png)

**Comment by Axel32019** [comment]
Das sieht so aus als ob der Ladebereich nicht erreicht wird.
Zielpunkt verschieben - Regel: Zielpunkt min. 1 Gespann-Länge hinter dem Trigger in Fahrtrichtung platzieren.

**Comment by SchorschiBW** [comment]
Das hat funktioniert. Vielen Dank

**Comment by Axel32019** [comment]
Manchmal Millimetersache :-)
