### ISSUE TITLE
Feature Request - Speed Limits on route

### ISSUE THREAD

**Issue by HaploAW** [Stephan-S/FS22_AutoDrive#423]
I was creating an auto drive config for Elk Mountains map and when I was testing routes across rough roads I thought it would be nice to be able to dynamically change the AD speed limit on the vehicle as it drives. With the rough roads if you are going too fast then the vehicle bounces around and can fly off the road. Also would be nice to reduce speeds in some curves as full speed causes unstable driving. The vehicle can fishtail and spin out. If a node has a speed limit apply that but if not the vehicle speed limit set in controls takes effect.

-Great mod. If that can't be done I understand. Keep up the good work!

**Comment by Iwan1803** [comment]
You can set the curve speed for each vehicle individually.
As mentioned in earlier enhancement requests: at the moment we will not add such a "special" for waypoints.
