### ISSUE TITLE
Auswahl Referenzpunkt für Auffüllung

### ISSUE THREAD

**Issue by 0scarZulu** [Stephan-S/FS22_AutoDrive#424]
Hallo,

wäre es möglich in einem der kommende Update eine Auswahl einzubauen ob beim Anfahren eines Wegpunktes für das Auffüllen am Silo die Front oder Heckhydraulik als Referenzpunkt genommen werden soll? 
Wenn ich zB Paletten für Saatgut und Dünger hinstelle dann passt der Punkt vielleicht für eine Amazone im Dreipunkt aber zB nicht mehr für eine 8m Väderstadt. Da müsste der Punkt dann um ca. die Länge der Drille nach vorn verschoben werden und das sieht dann immer naja aus wenn der Wegpunkt nicht direkt vor dem Ziel liegt. 

Beste Grüße

**Comment by Iwan1803** [comment]
In Abhängigkeit vom eingestellten Wert für "Abstand Silo" sucht AD vor dem Zielpunkt schon nach Triggern, um die eingestellte Aktion auszuführen.
Der Zielpunkt sollte also mind. 1,5-fache Fahrzeuglänge HINTER dem Trigger sein, damit unterschiedliche Gespanne funktionieren.

**Comment by 0scarZulu** [comment]
Hm ok und könnte man das irgendwie als Auswahl machen das der Zielpunkt geben nicht dahinter sein muss? Der innere Monk ist irgendwie so drauf, das er den Zielpunkt genau vor dem Ziel haben will und nicht 1.5fache dahinter :D
