### ISSUE TITLE
Keeps stopping at unload spots with a downwards slope

### ISSUE THREAD

**Issue by Goofball2** [Stephan-S/FS22_AutoDrive#425]
On Calmsden and Haut-Beyleron at the tip triggers that go up and down a ramp; it tips fine then when leaving it stops and will not move until you move it manually

**Comment by Iwan1803** [comment]
Check the collision height in the global settings and set it to 2m.

**Comment by Goofball2** [comment]
> Check the collision height in the global settings and set it to 2m.

Will try that tomorrow morning

**Comment by iilonmasc** [comment]
Not the original reporter, but I was having the same issue on Erlengrat. Just wanted to inform you, the suggestion about setting collision height to 2m from @Iwan1803 worked for me!
