### ISSUE TITLE
Ballen zur BGA liefern

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#426]
Hallo
Was muss ich einstellen damit die Ballen vom Feld zur BGA gefahren werden, der Abfahrer fährt vom Feld runter und dann wieder auf das Feld rauf
![Ballen ahren](https://user-images.githubusercontent.com/47453761/159774982-b8218609-87bd-416f-bcb9-7091f8d1b366.png)

**Comment by TimoR1014** [comment]
Du hast den falschen Modus eingestellt. der hier ist dafür da, Dinge zum Feld zu bringen. z.B. Dünger

**Comment by Hendirk** [comment]
Welchen muss ich einstellen


Gesendet von Mail für Windows

Von: TimoR1014
Gesendet: Mittwoch, 23. März 2022 20:52
An: Stephan-S/FS22_AutoDrive
Cc: Hendrik; Author
Betreff: Re: [Stephan-S/FS22_AutoDrive] Ballen zur BGA liefern (Issue #426)

Du hast den falschen Modus eingestellt. der hier ist dafür da, Dinge zum Feld zu bringen. z.B. Dünger

**Comment by Axel32019** [comment]
Hallo,
1. Abholen und Abliefern
2. Ballentransport kommt mit dem nächsten Release

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.5
