### ISSUE TITLE
Pickup and deliver

### ISSUE THREAD

**Issue by MrDalsgaard** [Stephan-S/FS22_AutoDrive#427]
A question.

If I use AD with CP to pickup stones or straw it works fine, when I setup a new job - After delivering a load, the tractor go to the field and continue from last point in CP. Nice...

However, if the tractor runs into a issue, and I have to stop the job, or I have loaded a saved game where the job is half done, and I then start the job from last CP point, I can't get AD/CP to do it right. After delivering a load, AD will always start at point 1.

Now.... In your text regarding "Release 2.0.0.4 (30.01.2022)" you write: "If AD was started from CP, then on return at the first AD destination CP is started with the point of the CP course where it left off." - How du I start AD from CP??

**Comment by rohne83** [comment]
> How du I start AD from CP??

Just activate the CP button in AD HUD but leave AD disengaged. Instead place your vehicle on the field, start CP and it will directly handover to AD if full already.

**Comment by MrDalsgaard** [comment]
> > How du I start AD from CP??
> 
> Just activate the CP button in AD HUD but leave AD disengaged. Instead place your vehicle on the field, start CP and it will directly handover to AD if full already.

I have the newest CP and AD.
If I do that, CP just stay there. If it´s full already, nothing happens. If it´s empty, it starts CP route untill it´s full, and then it stop. It´s not handing the control over to AD. And yes, the CP button in AD HUD is activated.

**Comment by Axel32019** [comment]
That is a CP topic, see #421
