### ISSUE TITLE
Gewächshäuser reihenweise befüllen. Schlepper bleibt bei vollem Gewächshaus stehen

### ISSUE THREAD

**Issue by H0schii1** [Stephan-S/FS22_AutoDrive#428]
Hallo,

Folgendes Problem:
5 Gewächshäuser in Reihe. Der Schlepper fährt an das erste (bereits gefüllte) Gewächshaus heran, befüllt es wieder auf 100% und bleibt dann stehen. Drücke ich dann auf die beiden Pfeile "weiterfahren" fährt er das nächste an und bleibt dann wieder stehen.

Bereits ausprobiert habe ich:
-Jedes Gewächshaus ein eigenes Ziel gegeben, Die Punkte in einen Ordner verschoben und Die Modis Rotieren Be- entladen durchprobiert.
-Nur den letzten Gewächshaus als Anfahrpunkt ausgewählt. Auch hier hält er am ersten an und bleibt stehen.
-"Wenn Silo leer" auf Weiterfahren gestellt. Hätte ja sein können das es auch bei Silo voll etwas ändert.
-Maximaler Siloabstand geändert.

Hat vielleicht jemand einen Tipp wie ich AD einstelle damit er bei vollem Gewächshaus das Anfahrziel zu wechseln?
Oder muss ich die Gewächshäuser anders Positionieren?

Mfg Hoschi
![Screenshot_106](https://user-images.githubusercontent.com/102299399/159917555-baaafce2-7615-426f-919f-6055550d6006.jpg)
i

**Comment by Hatschi99** [comment]
Hallo Hoschi,

ist schon bekannt, siehe #394 , wird mit dem nächsten release behoben.

Viele Grüße
