### ISSUE TITLE
Modus Abholen und Abliefern, Teil 2

### ISSUE THREAD

**Issue by SchorschiBW** [Stephan-S/FS22_AutoDrive#429]
Ich muss mich nochmal zu Wort melden bezüglich des Problems mit dem Abholen und Abliefern an einem Kaufsilo (Ladewagen lässt sich per AutoDrive nicht füllen). Meine erste Meldung wurde geschlossen, da es scheinbar gelöst war. Leider ist dies nicht der Fall.

Nachdem ich auf Anraten die Markierung verschoben hatte, sah es so aus, als würde es funktionieren. Leider ging es beim nächsten Spielstart nicht mehr. Nach etwas hin und her experimentieren hatte ich mir einen Ladewagen geholt, den das Spiel mitbrachte. Auch hier zeigt sich das Phänomen, dass sich der Ladewagen mit AutoDrive im Modus Abholen und Abliefern nicht füllen lässt. Auch hier kann ich nur AD unterbrechen und manuell Füllen. Ich habe die entsprechende Markierung schon hin und her geschoben, es hilft alles nichts.

**Comment by rohne83** [comment]
Wie soll dir hier jemand helfen können ohne zu wissen welcher Ladewagen, welches Silo, und wie überhaupt dein AD-Netzwerk an der entsprechenden Örtlichkeit aussieht?

**Comment by SchorschiBW** [comment]
Verzeihung, das konntest Du nicht wissen, dass ich schon mal Bilder gepostet habe. Ich hole es hiermit nach:

Es waren folgende Ladewagen:

1. Der im Spiel befindliche Strautman Magnon CFS 530 DO
2. https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234614&title=fs2022

Probiert wurde es mit folgenden Silos:

1. https://www.modhoster.de/mods/universal-kaufsilo#description
2. https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=224316&title=fs2022

![Landwirtschafts-Simulator 22_2022 03 24-17 55](https://user-images.githubusercontent.com/16411797/159969667-9d5671a3-00aa-459b-9461-c8527d47b0cc.jpg)

**Comment by Iwan1803** [comment]
Das erste Issue: #422 
Soll er da immer noch Häckselgut kaufen oder Stroh wie auf dem Screenshot? Macht er da überhaupt was, wenn er da steht? Also kommt eine Ladeanimation oder passiert gar nichts oder fährt er direkt zum Zielpunkt durch?
Falls er korrekt stehenbleibt, kannst du dann AD stoppen und direkt per Tastenkombi laden?

**Comment by SchorschiBW** [comment]
Es spielt keine Rolle, um welches Ladegut es sich handelt. Ich habe es mit Gras, Silage, Hächselgut, Heu und Stroh ausprobiert, eben das, was der Ladewagen kann. Sinn des Ganzen war eigentlich, die Lager meines Kuhstalls mal für den Anfang voll zu machen, bis mein Fahrsilo Silage hat und ich Heu usw. machen kann. Also wären jeweils mehrere Fahrten mit dem gleichen Ladegut notwendig gewesen. "Normale" Anhänger, wie der Bergmann HTW 65 oder der Farmtech Fortis 3000 meistern die Aufgabe mit Bravour. Denen ist es auch völlig egal, wo sich der Zielpunkt befindet.
Es passiert nichts, er fährt langsam durch bis zum Zielpunkt, unabhängig, wo sich der Zielpunkt befindet. Ich hatte in der ersten Meldung den Zielpunkt einen Punkt weiter hinten gesetzt, so dass der Ladewagen direkt im Ladetrigger steht. AD kann ich grundsätzlich manuell stoppen, dann kann ich auch manuell laden (Befüllung mit R erscheint dann im Hilfe Fenster)

**Comment by Axel32019** [comment]
Bitte log mit Debug Fahrzeuge, Anhänger und Pfadfindung anfügen.

**Comment by SchorschiBW** [comment]
Die Log: https://workupload.com/file/wKMbDAdTzUa

Ich hatte einen Geistesblitz: Die Ladewagen haben einen Siliermitteltank. Mit Diesem habe ich experimentiert und ich denke, ich habe den Fehler gefunden.

Ladewagen ohne Siliermittelank funktioniert
Ladewagen mit Siliermitteltank funktioniert nicht, egal, ob der Tank voll oder Leer ist

**Comment by Axel32019** [comment]
Das mit dem Siliermittel ist im nächsten Release behoben.
Kann somit geschlossen werden?

**Comment by SchorschiBW** [comment]
Wenn es tatsächlich das gewesen sein sollte, kann geschlossen werden.

Vielen Dank

**Comment by Kitekater** [comment]
Kann das Verhalten bestätigen. Verschiedene Anhänger können nicht beladen werden. CP gesteuerter Kalker, fährt mit AD zum auffüllen, öffnet unter dem Trigger den Deckel, fährt drunter her und es passiert nichts. Fährt dann auch weiter.
Auflieger, der Rüben holen und wo anders hinbringen soll, bleibt einfach drunter stehen und es passiert nichts. Deckel wird aufgemacht, aber keine Animation, nix

**Comment by SchorschiBW** [comment]
Mein Kalkstreuer funktioniert, zumindest die Bredal und auch der Rauch Aero 32.1 von CreativeMesh funktioniert einwandfrei. Probleme konnte ich tatsächlich nur bei den Ladewagen, konfiguriert mit SIliermitteltank, feststellen. In der neuen Version habe ich es noch nicht probiert

**Comment by Iwan1803** [comment]
@SchorschiBW erst alles updaten und dann erneut testen, danke!

@Kitekater schon mal dran gedacht, das es vielleicht am Silo liegen könnte? Ist es ein Mod-Silo oder das der NFM?
Vielleicht einfach mal mit dem Standardsilo probieren.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
