### ISSUE TITLE
bei mehreren Häckslern Abfahrerprobleme

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS22_AutoDrive#430]
Hallo Leute,

mit Freude durfte ich feststellen, dass der neue RC das Gras häckseln unterstützt :-)

Ich finde es so cool, nun endlich auf der NF Marsch die großen Grasfelder sinnvoll nutzen zu können. Kann mich nicht genug oft bedanken, bin am Feld 45 bereits zum 2. mal am mähen. 

Auf jeden Fall ist aber wichtig, mindestens 4 Vorgewende (á 10m) zu machen und beim mähen eine Reihe überspringen, so läuft es wirklich Fehlerfrei :-)

Aber eine Sache ist mir aufgefallen:

Aufgrund der Größe des Feldes habe ich einen 2. Häcksler auf den Kurs gesetzt, und durch die Funktion "rufe 2. Abfahrer" kommt es vor, dass sich die Abfahrer ein wenig verirren. 
Beide Häcksler haben Feld 45 im AD eingestellt.
Der 1. Häcksler ruft sich einen 2. Abfahrer, welcher auch ganz normal beginnt zum Häcksler zu fahren. Der 2. Häcksler ruft sich einen 2. Abfahrer, auch dieser fährt zum 2. Häcksler. Und jetzt tritt der Fehler auf: Wenn es genau zusammen passt kommt es vor, dass der 2. Abfahrer vom 1. Häcksler vom 2. Häcksler gerufen wird und umgekehrt. jetzt stehen beide Häcksler weil die ersten Abfahrer voll sind. Beide 2. Abfahrer wechseln sozusagen die Häcksler.

Ist es möglich den 2. gerufenen Abfahrer an den Häcksler zu binden von dem er früher gerufen wurde? Sozusagen dass der 2. Abfahrer kein Rufsignal von dem anderen annimmt? 

Ich weiß dass ich einen 2. Anfahrpunkt machen und beide Häcksler getrennt von einander abfahren lassen könnte. Das würde aber zusätzliche Abfahrer benötigen. 

Ich hoffe mein Text war halbwegs verständlich, wenn nötig kann ich euch auch gerne mal ein Video posten.

nochmals Danke dass dieses Feature jetzt drinnen ist :-)

LG aus Österreich
Eric

**Comment by Iwan1803** [comment]
`Ich weiß dass ich einen 2. Anfahrpunkt machen und beide Häcksler getrennt von einander abfahren lassen könnte.`
Da Häcksler nun mal permanent einen Abfahrer benötigen, wird dir wohl nichts anderes übrig bleiben oder du deaktivierst das Rufen des 2. Abfahrers in den Häckslern, damit sie sich halt nicht gegenseitig die Abfahrer "klauen".
Wenn ein Ernter ruft, kommt nun mal immer der Abfahrer, welcher am nähesten dran und in Rufbereitschaft ist.

**Comment by eric4072** [comment]
eben, darum meine ich ja: wenn ein Abfahrer früher gerufen wird, dann sollte dieser doch auch bei diesem Häcksler bleiben. sonst werden nur unsinnige Fahrten auf dem Feld produziert...

**Comment by Iwan1803** [comment]
Und dann soll der andere Häcksler rumstehen, nur weil dieser 2. Abfahrer vom anderen Häcksler geblockt wird?

**Comment by eric4072** [comment]
nein das verstehst du aber jetzt falsch. Der Häcksler mit dem 1. Ruf nach dem 2. Abfahrer wird ja auch als ersters voll. 

Wenn aber der Abfahrer zu dem Häcksler gerufen wird, er hinfährt, und dann den zu dem Ruf vom 2. Häcksler fährt, steht dann der erste Häcksler. Ich habe das jetzt mehrmals getestet, immer mit dem selben Ergebnis.

Würde der Abfahrer bei dem Häcksler bleiben, von dem erst bei 60% gerufen wird, würde das Ganze viel flüssiger laufen

**Comment by Iwan1803** [comment]
Ich verstehe schon, was du meinst und dennoch sehe ich das Problem, das u.U. ein Häcksler dann auch mal ganz ohne Abfahrer da steht.
Beispiel mit 2 Häckslern und 4 Abfahrern (und nur einem AD-Zielpunkt am Feld):
Häcksler1 hat seinen Abfahrer und der 2. wurde schon gerufen, welcher nun treudoof hinterher fährt
Häcksler2 sein 1. Abfahrer ist noch unterwegs (warum auch immer) und der 2. Abfahrer fast voll
Das Ergebnis wäre, das Häcksler2 gleich rumsteht, weil der einzige freie Abfahrer immer noch hinter Häcksler1 herfährt.

Schlimmer wird das ganze noch, wenn die Häcksler per CoursePlay im Verband fahren. Wäre Häcksler2 das führende Fahrzeug, würde Häcksler1 dahinter im entsprechenden Abstand warten. Somit wären beide Häcksler inaktiv und das nur, weil die Abfahrer fest einem Häcksler zugewiesen sind.

So oder so wird es immer Situationen geben, in denen mal Häcksler auf einen Abfahrer warten müssen, aber eine fest Zuordnung nach dem ersten Ruf halte ich für eher kontraproduktiv.

**Comment by Axel32019** [comment]
Sehe hier keinen Handlungsbedarf -> closed
