### ISSUE TITLE
Autoload Paletten aufladen.

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS22_AutoDrive#431]
Guten Morgen,

ich hab da einen Verbesserungsvorschlag für den Autoload mit Paletten.
Bisher gibt es ja nur eine Autoload Wartezeit zum Abladen, bei dieser
Autoload Spezialisierung wäre es auch nötig hier eine Wartezeit zum Aufladen mit einzubringen.
Der Grund dahinter ist, man kann ja bei einer Belade Rotation z.B. nicht immer vorhersagen
wieviel Paletten aufgeladen werden. Dementsprechend ist es auch nicht möglich
bei jeder Fahrt immer den passenden Abladen ab Level einzustellen. 
Beispiel. Der Trailer kann 44 Paletten laden, holt aber nur 10 ab weil nicht mehr
da sind, müsste man in dem Fall Abladen ab Level auf 20% stellen damit er nach dem Beladen auch weiter fährt weil er die 20%
erreicht hat. Kommt er aber mit dieser Einstellung an einen Trigger wo 30 Paletten raus kommen,
würde er zu früh wieder los fahren weil so schnell spawnen die Paletten ja nicht nach.
Deswegen wäre hier eine Auflade Wartezeit gut, weil bei den unterschiedlichen Palettenmengen die man
vorfindet eigentlich Abladen ab Level unter 20% stellen muss. Vielleicht könnte man auch im
Autoload Modus das Abladen ab Level komplett ignorieren und nur mit einstellbarer Wartezeit arbeiten.

Ich hoffe ich hab das einigermaßen verständlich erklärt.

Liebe Grüße Timmi

**Comment by Farmer-DD** [comment]
Hallo,
Ich habe viele Gewächshäuser, der Aufladepunkt, ist am Letzten Gewächshaus. Ich starte am 1. Gewächshaus und AD fährt die Häuser ab, um zum Aufladepunkt zu kommen und lädt dabei Paletten auf. 
Ist die maximale Pallettenzahl erreicht, fährt es aber weiter, Richtung letztes Haus "Aufladepunkt" und nicht zum Abladepunkt.  
Muss AD am Aufladepunkt die maximale Palettenanzahl aufladen, um zum Abladen zu fahren und nicht vorher? 
Oder woran könnte liegen, das es bei mir nicht mit dem Wechsel auf den Abladepunkt klappt?

**Comment by Iwan1803** [comment]
@Farmer-DD wie beim normalen Abholen&Abliefern auch wird nach Erreichen des eingestellten oder halt bei vollem Füllstand immer noch der Zielpunkt angefahren, bevor es dann zum Abladepunkt geht. Warum sollten wir dies nun für Paletten & Co. ändern?

Was dies jetzt aber mit der vorgeschlagenen "Aufladezeit" zu tun hat.... 🙄

**Comment by MaGGuS3206** [comment]
Ich schreib das jetz einfach mal hier mit rein, da ich denke das Thema passt gut dazu.

Bei Paletten wäre es halt auch cool, wenn man einstellen könnte, dass er die Stationen zum Beladen solange rotiert bis er voll ist und dann erst zum abladen fährt. Ich fahre zB mit nem kleinen LKW alle Produktionen ab und bring die Sachen in ein Zentrallager. Wenn der jetz zu Produktion 1 fährt und da stehen nur 4 Paletten, fährt er danach erst die 4 abladen, obwohl noch 20 reinpassen. Das würde halt ungemein Sprit sparen, wenn er nach Produktion 1 zu Produktion 2 fährt usw und erst abladen fährt, wenn er wirklich voll ist. 

Eine kleine Wartezeit an den Produktionen einzustellen wäre auch gut, bei Gewächshäusern zB ist mir aufgefallen, dass wenn er aufläd, gerne nochmal Paletten nachspawnen und die lässt er dann auch stehen.


Gruß MaGGuS

**Comment by Axel32019** [comment]
@timmi4026 Bitte mal testen:

**Comment by timmi4026** [comment]
Mach ich doch glatt

**Comment by Axel32019** [comment]
> Mach ich doch glatt.
> 
>     1. Produktion 30 Paletten Mehl, 30 Sek Haltezeit. Hat geklappt.
> 
>     2. Produktion 42 Paletten versch. Sorten, 30 Sek Haltezeit. Hat geklappt.
> 
>     3. Produktion 28 Paletten Zucker, 30 Sek Haltezeit. Hat geklappt.
> 
> 
> Getestet auf MP mit Belade Rota an 3 großen Produktionen. Alles sauber geladen. Super Arbeit. Danke schön. Client Log ist sauber, aber die Server log hat Fehler beim beladen. Log liegt bei. [log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8563963/log.txt)

Die Fehler stammen vom Entladen und werden vom AutoLoad ausgelöst. Das sollte sich @Achimobil mal ansehen.

**Comment by timmi4026** [comment]
ok

**Comment by timmi4026** [comment]
Ich sehe gerade mit der neuen Version sehe ich Autodrive nicht mehr im Vehicle Inspector. Standard Helfer und CP sind drin, ist das so gewollt ?

**Comment by Axel32019** [comment]
> Ich sehe gerade mit der neuen Version sehe ich Autodrive nicht mehr im Vehicle Inspector. Standard Helfer und CP sind drin, ist das so gewollt ?

Siehe #441

**Comment by timmi4026** [comment]
> > Ich sehe gerade mit der neuen Version sehe ich Autodrive nicht mehr im Vehicle Inspector. Standard Helfer und CP sind drin, ist das so gewollt ?
> 
> Siehe #441

Und was genau mache ich jetzt das ich das wieder sehe? in der 2005 brauchte ich nur eine zeile aktivieren, die ist aber jetzt nicht mehr da oder?

**Comment by Axel32019** [comment]
Bei HappyLooser nachfragen, es ist ja der einzige mod der es nicht mehr anzeigt, andere aber schon.

**Comment by Achimobil** [comment]
Also das mit dem VI finde ich auch traurig, dass da nicht miteinander gesprochen wird. Die Kombination aus AI, CP, AD und VI ist einfach das optimum an übersicht und kontrolle, ist aber hier nicht thema.

**Comment by Achimobil** [comment]
> > Mach ich doch glatt.
> > ```
> > 1. Produktion 30 Paletten Mehl, 30 Sek Haltezeit. Hat geklappt.
> > 
> > 2. Produktion 42 Paletten versch. Sorten, 30 Sek Haltezeit. Hat geklappt.
> > 
> > 3. Produktion 28 Paletten Zucker, 30 Sek Haltezeit. Hat geklappt.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Getestet auf MP mit Belade Rota an 3 großen Produktionen. Alles sauber geladen. Super Arbeit. Danke schön. Client Log ist sauber, aber die Server log hat Fehler beim beladen. Log liegt bei. [log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8563963/log.txt)
> 
> Die Fehler stammen vom Entladen und werden vom AutoLoad ausgelöst. Das sollte sich @Achimobil mal ansehen.

Ursache ist der Giants Patch 1.4, was auch sonst.
Wenn man Objekte mittels Skript verschiebt werden meine Trigger nicht mehr ausgelöst und deshalb mekrt der Autoloader nicht mehr, dass Objekte durch das abkramen gelöscht wurden. Warum er das nicht mehr korrekt macht, kann ich nicht sagen, aber ich konnte es umgehen und da wird es einen fix für geben im Autoloader.

**Comment by andremeyer123** [comment]
[> ](https://github.com/Stephan-S/FS22_AutoDrive/issues/431#issuecomment-1110134824) 

Das stimmt so nicht, es sind alle Mods wo Helfer ausgelesen werden .  Es haben sich alle User ad angepasst nach Achim seine Änderung.

**Comment by Iwan1803** [comment]
SimpleInspector konnte es vor dem Giants-Patch als auch danach und auch vor und nach dem letzten AD-Release. Warum der VehicleInspector das nicht kann, ist eine gute Frage, die man HappyLooser mal stellen sollte, denn irgendwas scheint er ja "anders" zu machen. Oben VI und unten SI:
![image](https://user-images.githubusercontent.com/47528836/165530121-d22a988d-07f4-402e-90c1-45da147fb6b6.png)

Hier geht es aber gerade um Paletten und nicht um die Helferanzeige....

**Comment by timmi4026** [comment]
Auch hier zum Abschluss, den vorhanden Lua Fehler, da kümmert sich Achim drum. Hab jetzt jeden Tag Paletten von 12 Produktionen abholen lassen, bisher alles problemlos. Gute Arbeit Danke nochmal.

**Comment by Axel32019** [comment]
Das ursprüngliche Thema sehe ich als gelöst im nächsten Release an.
Für die anderen Themen bitte separate Issues aufmachen, falls nötig!

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
