### ISSUE TITLE
Lenkachse sperren bei Rückwärtsfahrt

### ISSUE THREAD

**Issue by 0scarZulu** [Stephan-S/FS22_AutoDrive#435]
Hallo :) 

wäre es möglich das der AD Fahrer beim Rückwärtsfahren die Lenkachsen sperrt um nicht ins schlingern zu kommen? Hab die den Kurs so eingefahren wie Iwan es in seinen Videos zeigt und eigentlich auch einige Punkte zusätzulich aber irgendwann "schaukelt" er sich regelrecht auf und bekommt den Anhänger dann nicht mehr gerade.

CHeers 

Oscar

**Comment by Iwan1803** [comment]
Die Deichsel wird gesperrt oder was meinst du mit Lenkachsen?

**Comment by 0scarZulu** [comment]
Nein es gibt doch zB Güllefässer oder Ladewagen als Tandem oder Tridem wo eine Achse mitlenkt. Und die beim Rückwärtsfahren ggf. auch sperren. Bin mit einem HAWE ULW auf die P Position gefahren und er hat sich aufgeschaukelt wegen der Lenkachse und dann quasi nur noch in ner Schlangenlinie gefahren zum ausgleichen

**Comment by Axel32019** [comment]
Hallo @0scarZulu , Wenn Du dazu irgendetwas findest, mod o.ä., immer her damit.

**Comment by 0scarZulu** [comment]
Moin :) Hier gibt es einen Mod dafür. COol wäre es wenn AD das automatisch macht beim Rückwärtsfahren. 

https://www.lsfarming-mods.com/filebase/file/83-lenkachse-sperren/

**Comment by Axel32019** [comment]
Hallo @0scarZulu , Du würdest uns mit dem Test der folgenden Datei sehr weiterhelfen...
Bitte in FS22_AutoDrive\scripts\Modules ersetzen.
[TrailerModule.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8420537/TrailerModule.zip)

**Comment by 0scarZulu** [comment]
@Axel32019 jo danke mach ich :)

**Comment by 0scarZulu** [comment]
Also bei 3 unterschiedlichen Anhängern hat es Funktioniert :) Danke dafür!!

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
