### ISSUE TITLE
AD 2.0.0.5 + aPalletAutoLoader 1.6.2.0 = Kein Drescher abfahren möglich

### ISSUE THREAD

**Issue by BizzWareX** [Stephan-S/FS22_AutoDrive#437]
Hallo,

ich hab mich jetzt mal komplett durchgetestet mit Mods an/aus usw.

Die Kombination mit dem neusten AD + aPalletAutoLoader funktionieren nicht zusammen.
Sobald man einen Abfahrer im "Drescher abfahren" startet, passiert einfach nichts.
Der Abfahrer fährt noch nicht mals zum eingestellten Feld, sondern bleibt einfach stehen.

Ich hab es ebenfalls mit der aPalletAutoLoader 1.6.1.2 + 1.6.1.1 versucht.
Erst als ich 2.0.0.4 + aPalletAutoLoader 1.6.2.0 getestet habe, funktioniert das abfahren wieder.

Anbei noch ein Youtube Video: [https://youtu.be/tpLG7fsLYes](https://youtu.be/tpLG7fsLYes)

wo auch der Fehler im Log zusehen ist, der auftaucht sobald man den Abfahrer startet.

**Comment by timmi4026** [comment]
> Hallo,
> 
> ich hab mich jetzt mal komplett durchgetestet mit Mods an/aus usw.
> 
> Die Kombination mit dem neusten AD + aPalletAutoLoader funktionieren nicht zusammen. Sobald man einen Abfahrer im "Drescher abfahren" startet, passiert einfach nichts. Der Abfahrer fährt noch nicht mals zum eingestellten Feld, sondern bleibt einfach stehen.
> 
> Ich hab es ebenfalls mit der aPalletAutoLoader 1.6.1.2 + 1.6.1.1 versucht. Erst als ich 2.0.0.4 + aPalletAutoLoader 1.6.2.0 getestet habe, funktioniert das abfahren wieder.
> 
> Anbei noch ein Youtube Video: https://youtu.be/tpLG7fsLYes
> 
> wo auch der Fehler im Log zusehen ist, der auftaucht sobald man den Abfahrer startet.

Ich hab mal versucht das nachzustellen. Bei mir kommt der Abfahrer und tankt den Drescher ab ohne Fehler. Vielleicht hast Du andere Mods die das auslösen. Schau da nochmal durch. Und meines Wissens hat  der aPalletAutoloader da nichts mit zu tun.

![image](https://user-images.githubusercontent.com/46847594/160279941-b08d8a05-0320-42ed-95e9-5fcb3debff60.png)

**Comment by frankrexdale** [comment]
I had similar issue. I updated FS22_aPalletAutoLoader to version 1.6.2.0  and fixed the issue.

**Comment by BizzWareX** [comment]
Ok ich konnte es noch einmal eingrenzen.

Das Problem sind Anhänger mit integriertem aPalletAutoLoader die aber auch normal genutzt werden können für Früchte.
Sobald ich einen normalen Anhänger nehme ohne aPalletAutoLoader integration funktioniert es einwandfrei.

**Comment by McBenzer** [comment]
Wenn man einen  Abfahrer mit einem Autoload-Anhänger gibt es folgenden LUA Fehler:

`2022-03-29 13:54 Error: Running LUA method 'mouseEvent'.
D:/LS22-Modding/projekt_nf/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: bad argument #1 to 'max' (number expected, got nil)`

Fährt der Abfahrer über einen Abladetrigger, kommt das:
`2022-03-29 14:01 Error: Running LUA method 'update'.
D:/LS22-Modding/projekt_nf/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: bad argument #1 to 'max' (number expected, got nil)`

Und das Spiel bleibt hängen.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8371238/log.txt)

**Comment by Achimobil** [comment]
Schein ein Problem im Autoloader Mod zu sein. Ich werde versuchen das nachzustellen und im Autoloader zu fixen.

**Comment by McBenzer** [comment]
> 



> Schein ein Problem im Autoloader Mod zu sein. Ich werde versuchen das nachzustellen und im Autoloader zu fixen.
Hallo Achimobil,
was mir auch noch aufgefallen ist, man kann den Anhänger nicht über Autodrive befüllen lassen, d.h. es werden keine Füllgüter angezeigt.

![image](https://user-images.githubusercontent.com/96957355/160614337-d0b233df-f4bc-4674-9f28-8f14a09e4d58.png)

**Comment by Achimobil** [comment]
Ich konnte es im AD fixen, da waren ein paar abfragen für den Autoloader nicht kompatibel zu Fahrzeugen bei denen autoload wahlweise aktiv ist oder nicht. Jetzt muss ich nur noch raus finden wie ich das als pullrequest schicken kann

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
