### ISSUE TITLE
AD 2.0.0.5 Kurvengeschwindigkeit

### ISSUE THREAD

**Issue by Nealswiss96** [Stephan-S/FS22_AutoDrive#439]
Ist es möglich das AD in der neuen Version die reduzierte Kurvengeschwindigkeit nicht erkennt?

**Comment by ct177mak** [comment]
stell sie mal auf 70% ,ich persöblich hab das so eingestellt und keine Probleme .

**Comment by Nealswiss96** [comment]
hab es bei allen Fahrzeugen bereits auf 50% immer noch das gleiche problem

**Comment by Iwan1803** [comment]
Ich habe es auf 80-85% und keine Probleme. Poste doch mal Screenshots von problematischen Kurven.

**Comment by Iwan1803** [comment]
Was ja aber kein Problem ist, da man die Kurvengeschwindigkeit pro Fahrzeug und nicht global einstellt 😉

**Comment by oldmicha** [comment]
Wir haben auch die gleichen Probleme auf dem Dedi Server mit den Kurvengeschwindigkeiten. Diese sind bereits auf 50% gestellt und trotz allem fährt der AD Fahrer mit voller Geschwindigkeit in die Kurve. Der Rest ist vorprogrammiert. Es scheint so seit der neuen Version, das die Einstellungen nicht greifen!

**Comment by Iwan1803** [comment]
Sind die Kurven vielleicht zu rund und haben zu viele Punkte?
Das führt auch gerne mal zu überhöhten Geschwindigkeiten.

**Comment by Iwan1803** [comment]
Zur Info: die Kurvengeschwindigkeit ist abhängig von den Winkeln der Wegpunkte zueinander.
Zu viele Wegpunkte = zu kleine Winkel = hohe Geschwindigkeit.

Da kein weiteres Feedback -> geschlossen.
