### ISSUE TITLE
Mouse Event Error and Draw Error

### ISSUE THREAD

**Issue by iraydawg** [Stephan-S/FS22_AutoDrive#44]
Getting these two log errors when attempting to either move a marker or add new after using the (yellow) path markers for secondary paths. One is a mouse event error, and the other is a draw error. 

$FS22DirPath/FS22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:198: attempt to perform arithmetic on field 'y' (a nil value)
2021-12-20 15:23 Error: Running LUA method 'mouseEvent'.

$FS22DirPath/FS22_AutoDrive/scripts/Hud.lua:802: attempt to perform arithmetic on field 'y' (a nil value)
2021-12-20 15:23 Error: Running LUA method 'draw'.

Additionally, I have discovered that once those two errors happen it completely deletes the "AutoDrive_Config xml" and "AutoDriveUsersData xml" from save game folders making you have to regenerate once you reload the save game file or you have to go into the save game backup folder and move the files back into the current save file.

**Comment by prometheus247** [comment]
Reads like identical to https://github.com/Stephan-S/FS22_AutoDrive/issues/22

**Comment by Axel32019** [comment]
Right root cause #22 -> closed
