### ISSUE TITLE
Autodrive Kurse auf Dedi im ESC-Menü nicht angezeigt

### ISSUE THREAD

**Issue by SirJoki** [Stephan-S/FS22_AutoDrive#440]
Sobald man im ESC-Menü aus dem Editor Modus geht wird der aktuelle Kurs nicht angezeigt. Im SP funktioniert es.

**Comment by Axel32019** [comment]
Bitte Screenshots anfügen - ich zumindest verstehe gerade nicht was gemeint ist, gibt mehrere Darstellungen.

**Comment by Axel32019** [comment]
Editormodus nicht aktiv -> keine Anzeige der Kurse, so soll es sein.

**Comment by SirJoki** [comment]
Hä, im SP seh ich doch auch die aktulle Strecke die er fährt außerhalb vom Editormodus.

**Comment by Axel32019** [comment]
> Hä, im SP seh ich doch auch die aktulle Strecke die er fährt außerhalb vom Editormodus.

Korrektur: Ja sollten auch ohne Editormodus sichtbar sein.
Auf unserem dedi klappt das auch.
Bitte mal log.txt anfügen
