### ISSUE TITLE
AD 2.0.0.5 Helfer löscht sich nicht 

### ISSUE THREAD

**Issue by andremeyer123** [Stephan-S/FS22_AutoDrive#441]
Version 2.0.0.5 Ad löscht sich am ende seiner Arbeit (beenden Ad ) nicht aus dem Inspektormod.
Zu sehen auch im Video von Iwan Fendt 1050  Z.B.
 https://www.youtube.com/watch?v=yCS87F6KLk0&list=PL5cOkXj5iscrkh_7Iz6IFOt5oyP732sAZ&index=19  
Minute 22  Adhelfer ist aus 
In Version 2.0.0.4 ist das Problem nicht ..

**Comment by Achimobil** [comment]
Ich habe das gleiche Problem festgestellt. Wenn man länger spielt wird die Liste dadurch ganz schon voll.

**Comment by andremeyer123** [comment]
Notlösung Giantshelfer einstellen, entlassen oder cp dann ist es weg aber jedes einzelne Farzeug was im Inspektor steht .

**Comment by Achimobil** [comment]
> Notlösung Giantshelfer einstellen, entlassen oder cp dann ist es weg aber jedes einzelne Farzeug was im Inspektor steht .

Danke, das wird mir bei längeren Sessions helfen.

**Comment by Axel32019** [comment]
Die Ursache ist die Vermeidung eines lua Fehlers #322, welche nur durch Nicht-Entlassen des Helfers in spec_aiJobVehicle zu beheben war.
Anscheinend hat Giants mit den zwischenzeitlichen Patches hier etwas geändert, sodas dies nicht mehr erforderlich ist.
Wer möchte kann die Zeile 1093 in Specialization.lua von
`self.spec_aiJobVehicle.currentHelper = currentHelper`
ändern in
`-- self.spec_aiJobVehicle.currentHelper = currentHelper`

**Comment by timmi4026** [comment]
> Die Ursache ist die Vermeidung eines lua Fehlers #322, welche nur durch Nicht-Entlassen des Helfers in spec_aiJobVehicle zu beheben war. Anscheinend hat Giants mit den zwischenzeitlichen Patches hier etwas geändert, sodas dies nicht mehr erforderlich ist. Wer möchte kann die Zeile 1093 in Specialization.lua von `self.spec_aiJobVehicle.currentHelper = currentHelper` ändern in `-- self.spec_aiJobVehicle.currentHelper = currentHelper`

Wenn ich das mache, sehe ich überhaupt keine Tätigkeiten mehr von AD im Inspector.

**Comment by regs1980** [comment]
Ganz richtig, nur wenn du in dem Fahrzeug was von AD gesteuert wird drin sitzt, wird es angezeigt, sonst nicht.

**Comment by andremeyer123** [comment]
Da es bei version 2004 nicht ist hat ad etwas geändert was es auslöst .

**Comment by regs1980** [comment]
Es kann ja dann nur daran https://github.com/Stephan-S/FS22_AutoDrive/issues/368 oder https://github.com/Stephan-S/FS22_AutoDrive/issues/322 liegen, weil danach kam ja schon er https://github.com/Stephan-S/FS22_AutoDrive/issues/389 mit dem Problem.

**Comment by andremeyer123** [comment]
Dieser Fehler hier, behindert ad ja nicht an seiner Arbeit daher abwarten und Tee trinken .

**Comment by andremeyer123** [comment]
So habe die Lua aus der 2.0.0.4 genommen damit geht wieder alles wie gewohnt.
Kann geschlossen werden danke für die Mühe.

**Comment by regs1980** [comment]
Sowohl der FS22_VehicleInfo als auch der FS22_SimpleInspector funktionieren tadellos, nur halt der VehicleInspector von HappyLooser hat mit der 2.0.0.5 Probleme mal schauen was er da noch ändert.

<img width="353" alt="2022-03-29 20_16_02-LS 22_ VehicleInspector v 1 90 Beta Scripte Mod für Landwirtschafts Simulator 22" src="https://user-images.githubusercontent.com/13314443/160679978-5ae8ad70-1bd1-448f-88be-234ffbdef3e0.png">

**Comment by Achimobil** [comment]
Also der VehicleInspector basiert auf der getCurrentHelper methode um zu sehen ob ein Helfer im Fahrzeug sitzt. 
Das basiert nun mal auf spec_aiJobVehicle.currentHelper
Warum sollte man das jetzt raus nehmen aus dem AD diesen zu setzen? Besser wäre es zu fixen, dass der Helfer aus dem spec_aiJobVehicle.currentHelper auch wieder raus genommen wird, wenn AD fertig ist.

**Comment by regs1980** [comment]
Nicht schlecht funktioniert.

**Comment by GulliGriff** [comment]
@Axel32019 hi, ich habe mir mal Deine dev. runter geladen. jetzt wird der AD-Helfer nicht mehr im vehicleinspector angezeigt, das scheint dann doch nicht das Problem gewesen zu sein. Bei CP und dem normalem Helfer wird der Helfer im vehicleinspaector als solcher angezeigt und eben auch entsprechend ausgetragen wenn kein Helfer aktiv ist. AD wird gar nicht mehr eingetragen bzw. angezeigt, selbst wenn ich im Fahrzeug sitze. Dann werde nur ich selbst in der Liste aufgefürht, verlasse ich das Fahrzeug verschwindet auch der Eintrag komplett aus der Liste.
Da ich mit echt vielen CP und AD Helfern spiele habe ich nun keine wirkliche Übersicht mehr und werde wohl solange auf die alte AD-Version zurück müssen :(
Wäre schön, wenn Ihr den Fehler finden und beheben könntet.

**Comment by GulliGriff** [comment]
so, ich habe mal ein bisschen gebastelt und ´habe in der Specialization.lua hinter (Zeile 1283)
`        if self.spec_aiJobVehicle ~= nil and self.spec_aiJobVehicle.currentHelper ~= nil and self.spec_aiJobVehicle.currentHelper == self.ad.currentHelper then
            -- we assign a helper for spec_aiJobVehicle, but do not remove it!
            -- self.spec_aiJobVehicle.currentHelper = nil
        end`
folgenden Code eingefügt
`        if self.spec_aiJobVehicle ~= nil then
            self.spec_aiJobVehicle.currentHelper = nil
        end`
       
so wird der AD-Helfer angezeigt wie er muss und wenn er raus ist verschwindet er auch. Ob das alles so richtig ist weiss ich nicht aber zumindest für mich eine Lösung.

**Comment by GulliGriff** [comment]
ich bin aber auch blind :(

    if self.spec_aiJobVehicle ~= nil and self.spec_aiJobVehicle.currentHelper ~= nil and self.spec_aiJobVehicle.currentHelper == self.ad.currentHelper then
        -- we assign a helper for spec_aiJobVehicle, but do not remove it!
        -- self.spec_aiJobVehicle.currentHelper = nil
    end
hier soll die IF-Anwendung ja offensichlich gar nix tun, denn "-- self.spec_aiJobVehicle.currentHelper = nil" ist ja auskommentiert, folglich soll hier gar nichts gemacht werden. Also einfach in Zeile 1285 gehen und die "--" entfernen. Schon geht es wie es soll.
