### ISSUE TITLE
AD Streckennetz überlappt

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#444]
Hier sieht man wie das Streckennetz von AD alles überlappt. Ist das ein Bug oder kann man das irgendwie einstellen. Das nervt gerade ein bisschen viel.

![20220328150049_1](https://user-images.githubusercontent.com/59480223/160403771-f31470cf-41ef-4855-b2ea-fbd658d33af8.jpg)

Gruß BigBahamut

**Comment by TobiHH78** [comment]
Warum bist du im Editormodus? Da einfach rausgehen, dann tauchen da auch keine Linien auf.

**Comment by BigBlackBahamut** [comment]
Ups, vergessen aus dem Editiermodus raus zu gehen. Aber trotzdem frage ich mich ob das so geplant ist das es über das LS22 HUD geht.

**Comment by timmi4026** [comment]
> Ups, vergessen aus dem Editiermodus raus zu gehen. Aber trotzdem frage ich mich ob das so geplant ist das es über das LS22 HUD geht.

Ja das ist seit einigen Versionen so, damit man schauen kann ob vielleicht eine Teilstrecke noch nicht eingefahren ist, und besser Unterbrechungen zu finden
