### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by Resandise** [Stephan-S/FS22_AutoDrive#445]
I am having issues with folders.  When I first activated "Use Folders", I was able create and move destinations to folders.  Once I restarted my game, I am no longer able to create folders or move destinations.  I know about editing the AutoDrive_config file in the save game files, but I don't see why we should have to use that route, when we can do it in game.

**Comment by Iwan1803** [comment]
For editing folders, you need to activate the edit mode.

**Comment by Axel32019** [comment]
@Resandise Any update?
