### ISSUE TITLE
Ich weiß nicht, ob das ein Problem bei mir ist oder an der AutoDrive Version  2.0.0.5. Wenn ich bei meiner Wild-West-Karte von Feld 32 zu Feld 54 mit AD fahre und den Mauszeiger deaktiviere bleibt die Kameraeinstellungen starr. Erst bei Ankunft kann ich wieder frei Schwenken. Wären dessen kann ich kein anderes Fahrzeugbewegungn

### ISSUE THREAD

**Issue by stwr78** [Stephan-S/FS22_AutoDrive#446]
@Stephan-S 
![AutoDrive 2 0 0 5  fahrt](https://user-images.githubusercontent.com/102571044/160531220-bb140790-e96b-4ff5-beab-50f06c8ec5da.jpg)

![AutoDrive 2 0 0 5  fahrt Ende](https://user-images.githubusercontent.com/102571044/160531270-f52372bd-eefe-44fe-aee5-bb5bef90a9b1.jpg)

**Comment by timmi4026** [comment]
Es steht doch schon in der log. NoWagePaymewnt, den mod mal raus nehmen, der müsste dann mal repariert werden.

**Comment by stwr78** [comment]
Danke, das ist der Mod gewesen. Hatte mit der AutoDrive Version 2.0.0.4 keine Probleme gemacht.
