### ISSUE TITLE
Keine Wegmarkierung zu finden.

### ISSUE THREAD

**Issue by WernerWusel** [Stephan-S/FS22_AutoDrive#447]
Hallo AD-Team.

Auf dem Screenshot ist eine Strecke zu erkennen die nicht wieder zu finden ist (Auf dem Feld). Ist es möglich in der AutoDrive_config.XML diese Strecke zu finden und zu eliminieren ?

Mit bestem Dank

![20220329140508_1](https://user-images.githubusercontent.com/102391757/160617176-dc5823ac-1351-4283-9a5d-df602199d2c1.jpg)

**Comment by Axel32019** [comment]
Hallo @WernerWusel , Versuche mal den Streckenabschnitt zu löschen: 
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-Tastenkombinationen
Wegpunkte zwischen 2 Kreuzungen löschen: 1. LMB auf den Kreuzungspunkt, 2. LShift + LSTRG + LALT + LMB auf 1. Wegpunkt hinter der Kreuzung
Funktioniert auch mit "Stich"-Strecken, kann jedoch sein das der letzte Punkt übrig bleibt. Den muss man dann in der AutoDrive_config.xml finden.

**Comment by WernerWusel** [comment]
Hallo @Axel32019

Das Löschen der Verbindung/des Wegpunktes wäre nicht das Problem. Wie ich eingangs geschrieben habe, ist kein Wegpunkt an der Stelle vorhanden an der der Strahl starten könnte. Auch die Überprüfung durch AD zeigt an der Stelle keinen Fehler, nur an dem nicht erreichbaren Endpunkt des Strahls wir ein 4_33 eingetragen.
Daher meine Frage nach der AutoDrive_config.XML. Wonach muss man denn in der Datei suchen ?

**Comment by Axel32019** [comment]
Hallo @WernerWusel , Bitte füge mal die AutoDrive_config.xml und einen Link zur Karte ein - dann kann ich mir das mal anschauen.

**Comment by WernerWusel** [comment]
Hallo @Axel32019

Hier der gewünschte Link zur Map und als Anhang die zugehörige AutoDrive_config.xml. Bitte beachte dass das Einfahren der Karte noch ziemlich am Anfang ist. Also nicht zu sehr über die vorhandenen Fehler wundern.

https://farmingsimulator22mods.de/huron-county-michigan-v1-1-0-4/

Mit bestem Dank
Lothar
Gesendet von Mail für Windows

Von: Axel32019
Gesendet: Dienstag, 29. März 2022 23:29
An: Stephan-S/FS22_AutoDrive
Cc: WernerWusel; Mention
Betreff: Re: [Stephan-S/FS22_AutoDrive] Keine Wegmarkierung zu finden. (Issue #447)

Hallo @WernerWusel , Bitte füge mal die AutoDrive_config.xml und einen Link zur Karte ein - dann kann ich mir das mal anschauen.

**Comment by WernerWusel** [comment]
Wo die AutoDrive_config.xml hin ist ... keine Ahnung. Wurde als Anhang zur eMail mitgeschickt.

**Comment by Axel32019** [comment]
Keine Ahnung wie dieser Punkt entstehen konnte, hab ihn mal gelöscht. Und nein, das kriegt man von Hand nicht hin!
[AutoDrive_config.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8382779/AutoDrive_config.zip)

**Comment by WernerWusel** [comment]
Danke @Axel32019 
Hast du evtl. auch den 2ten Strahl eliminiert ? der zeigt nach Süden. Wäre toll wenn das Element auch weg ist.

**Comment by Axel32019** [comment]
Da waren ja noch 2 weitere.
[AutoDrive_config.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8383731/AutoDrive_config.zip)

**Comment by WernerWusel** [comment]
Den 3ten hab ich garnicht gesehen. Meinen herzlichen Dank für die Mühe, die du dir gegeben hast, um den Fehler zu beben.
