### ISSUE TITLE
Gewächshäuser / Greenhouse ?

### ISSUE THREAD

**Issue by hleithoff** [Stephan-S/FS22_AutoDrive#448]
Warum kann Autodrive immer nur 2 Gewächshäuser mit Wasser füllen ?
Könnte mann nicht einfach an allen Überladtriggern(Wasser) auf der Strecke anhalten und überladen?
( z.B. bei mehr als 30 Gewächshäusern nebeneinander )
Wenn Tank leer dann Hole Wasser z.B. an Hydrant und mache da weiter wo aufgehört?

Vielen Dank.
H.Leithoff

**Comment by Iwan1803** [comment]
Schon mal an verteiltes Abladen gedacht?
