### ISSUE TITLE
Kurve vom gleichen Typ erstellen.

### ISSUE THREAD

**Issue by WernerWusel** [Stephan-S/FS22_AutoDrive#449]
Hallo AD-Team.

Gibt es die Möglichkeit eine "Kurve zwischen 2 Wegpunkten", die vom gleichen Typ sind (die beiden zu verbindenden Wegpunkte), beim Erstellen der Kurve den gleichen Typ zu erzeugen ?

Mit bestem Dank

**Comment by 60erjonny** [comment]
Hallo

Nun, ist das heir keine Hilfe für dich...?
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-Tastenkombinationen

**Comment by WernerWusel** [comment]
Hallo

Nein, nicht wirklich. Die Wiki kenn ich. Aber da ist eben nur die "normale" Kurve drin und die wird immer Grün, egal welcher Typ die Anschlusspunkte sind. Man muss eben immer jeden einzelnen Punkt der Kurve u. U. 2x Nacharbeiten. Das ist bei großen Karten sehr Zeitaufwendig und Fehlerbehaftet. Daher meine Frage nach der "automatischen" Möglichkeit.

**Comment by TobiHH78** [comment]
Genau dafür gibt es ja diesen Punkt…

Wegpunkte zwischen 2 Kreuzungen ändern -> Priorität ändern: 1. LMB auf Kreuzungspunkt, 2. LShift + LMB auf 1. Wegpunkt hinter der Kreuzung
