### ISSUE TITLE
Drivers won't mow grass

### ISSUE THREAD

**Issue by PliskoFarmer** [Stephan-S/FS22_AutoDrive#45]
The autodriving is somehow stopping the mower from cutting grass.  I tried the Krone Big M and the Kongskilde attachments and both of them had the same problem.   The bailer worked running a route over grass... so it seems to be related to harvesting.  This is a major bummer because I have been mowing manually for two weeks and I was really happy to see Autodrive show up so early...   It would be really nice if I could use your paths to mow.  Is this possible?

**Comment by Iwan1803** [comment]
AutoDrive is for driving, not for field work like mowing.
For field work use the helper or a mod like AIVE or (if released) CoursePlay.

**Comment by Plisko1** [comment]
That is confusing...since there are various modes for AutoDrive including unloading harvesters in a field...and I can tow working field equipment behind a vehicle that is autodriving.   Mowing is a special kind of field work that targets more than just fields... you may want to consider enabling it.  Other mods are not available.

**Comment by Iwan1803** [comment]
Again: AD is not designed for field work like mowing or chopping.
Try AIVE for that or wait for Courseplay 😉

**Comment by Plisko1** [comment]
Again.  Nobody needs you to design field work.  That is a non argument.  I just want the tractors to function like the game designed them for while driving.  I don't know why you gave yourself permission to break tractors following your paths...and then you lay it on me like I want something special for them to work as designed.

**Comment by Iwan1803** [comment]
Just because something isn't meant to do something else, it doesn't mean that by chance it somehow can.
That's all I wanted to say and if you interpret something else from my statement, that was not my intention.

**Comment by Plisko1** [comment]
It would be really helpful if I knew there was a technical reason why the tractors can't harvest while on a path.  If there is not a technical reason... then I don't know why it is satisfying to you that they are broken in this way.  Isn't it only a good thing if your mod can be even more helpful with just a small fix?

**Comment by Iwan1803** [comment]
Again and i will not repeat it: AD was not designed to do field work.
If it works somehow, then be happy, but we have no intention of integrating fieldwork into AD in the future. 
There are already specialists for that, and AD even collaborates with them (AIVE & CP).

**Comment by Plisko1** [comment]
Wow.  There was really no need to repeat that at all.

My position is that AD breaks the primary game design of tractors while using it.  You can hide behind whatever excuses make you feel better.

I can see we are done here.
