### ISSUE TITLE
Config file loads, but not able to set park destinations.

### ISSUE THREAD

**Issue by Ruudjhuu** [Stephan-S/FS22_AutoDrive#450]
I have a config file that works and loads correctly, but apparently it prevents to set and reset parking destinations.
It is created for Papenburger map, However, the issue exists on any map where you use this config file. Autodrive loads all points succesfull. 

[AutoDrive_config.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8373348/AutoDrive_config.zip)

**Comment by Iwan1803** [comment]
You know, that you can only assign parking places in edit mode?
If yes, what exactly happens if you try to assign them? Any message in the log?

**Comment by Ruudjhuu** [comment]
I was not aware of that. One way or another it went well without knowing this while using autodrive for multiple years. However, thank you for your help.
