### ISSUE TITLE
TrailerUtil.lua problem

### ISSUE THREAD

**Issue by Albatrozs112** [Stephan-S/FS22_AutoDrive#453]
Hello
All time when i take grass or silage contract,i just start cut grass
Show this.
I use Latest Release: 2.0.0.5
C:/Users/ASUS/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: bad argument #1 to 'max' (number expected, got nil)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8379852/log.txt)

**Comment by Achimobil** [comment]
Do you use a Trailer which can be configured as Pallet Autoload? Then it will be the same as #437

**Comment by Albatrozs112** [comment]
Nop in game trailer 

> Do you use a Trailer which can be configured as Pallet Autoload? Then it will be the same as #437

**Comment by BizzWareX** [comment]
Strange, but I had tested it with the same trailer both with Vanilla and Pallet Autoload trailer and only the Vanilla worked normally.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
