### ISSUE TITLE
Option to hide mouse-pointer after activating the helper

### ISSUE THREAD

**Issue by thraidh** [Stephan-S/FS22_AutoDrive#455]
My usual workflow is
- activate mouse cursor
- change autodrive settings (mode, targets, products,...)
- activate helper
- deactivate mouse cursor
- tab-jump to a different vehicle to do something else, as the current vehicle does not need my attention anymore anyway

It almost never happens, that I need to do something with the current vehicle's autodrive gui after activating the helper. Therefore I'd like, if the mouse cursor mode is automatically deactivated when a helper is activated. Since other people might like the current behavior (because they are using a mouse-cursor-based way to switch vehicles) this should be an option.

Alternatively or additionally, it would be helpful if tab would work while in mouse-pointer-mode.

**Comment by Iwan1803** [comment]
Your "improvement" sounds more like a problem with your key bindings or a mod that interferes somewhere unnecessarily. I can tab back and forward between the vehicles with and without a visible mouse pointer.
Maybe a log could be helpful to check this...

**Comment by thraidh** [comment]
The tabbing problem seems to be caused by some mod incompatibility. With only autodrive it works and even automatically exits mouse-pointer mode.
It would still be nice, if activating the helper would also exit mouse-pointer mode (maybe controlled by an option).

**Comment by Tensuko** [comment]
Don't see the problem here.

**Comment by thraidh** [comment]
The VehicleInspector mod is causing the problem. Need to find something else.

**Comment by Iwan1803** [comment]
There is a not so nice but working alternative called "Simple Inspector", which can be found in the ingame modhub.

**Comment by thraidh** [comment]
Thanks a lot! Already changed it and it fulfills my needs. Apparently VehicleInspector gobbled all the keyboard and some mouse input, so after removing it, I found that I can actually even drive the vehicles while in mouse pointer mode and ClickToSwitch also works now. That makes my life a lot better. Thanks again!

Is there a list of mods that are known to be incompatible with AD?

**Comment by Axel32019** [comment]
> Is there a list of mods that are known to be incompatible with AD?

No.
