### ISSUE TITLE
Contract locations

### ISSUE THREAD

**Issue by thraidh** [Stephan-S/FS22_AutoDrive#456]
Would it be possible to automatically add a dynamic folder with the locations of the current contract fields and sell points?

**Comment by Iwan1803** [comment]
Yeah, let's get to 100% automatism so everybody just needs to watch the vehicles driving....
As the target points are only points on the map and not assigned to field or productions IDs it's not possible to do that.

**Comment by Iwan1803** [comment]
If you don't want to search for the target points in the dropdown menus (magnifying glass), you can also click on the target points in the helper map to take them over to AD (if activated in you personal AD settings).
Leftclick will set the upper target and right click the lower.

**Comment by thraidh** [comment]
Thanks for the hint. Not exactly what I was looking for, but definitely helpful.
