### ISSUE TITLE
No wage for vehicles driven by me

### ISSUE THREAD

**Issue by thraidh** [Stephan-S/FS22_AutoDrive#458]
Today I can set the cost of helpers to 0, but I'd like to leave them at 100%. Anyway, I'd like to pretend that while I'm in the same vehicle as a helper, it is actually me that is driving and not the helper. Therefore that helper is not actually there and does not need to be paid.

So I'd like to have an option to set the helper wage to 0, but just for the vehicle I'm in. That does not matter if you have millions in your account, but every Euro counts during the early phases of the game, which I personally enjoy most.

**Comment by Iwan1803** [comment]
If there is no helper driving the vehicle, there will be no wages or did i misunderstood something?

**Comment by thraidh** [comment]
The helper is driving, but I'm in the same vehicle, just watching. So I cannot do something else, which I take as an excuse not to pay the helper.

**Comment by TobiHH78** [comment]
When the helper is still driving, he needs to get paid. Otherwise it would be cheating for me. The helper is hired and he is doing his job, why should he do that for free?

You can do something else than just watching him drive. Don’t get that point why payment should be different if you watch him or if you do something else in the meantime.

**Comment by thraidh** [comment]
When I'm in the same vehicle, the helper is actually my daughter, whom I'm teaching to drive. She's not paid...
As soon as I leave, the vehicle it is handed over to a paid helper.

Alternative explanation: if you have a reasonably modern car you can leave a lot of driving to automation. You are still the driver, but the car mostly drives itself.

The actual reason for this feature request is because driving with keyboard is bad, I'm apparently to old to use a gamepad properly and I don't have a steering wheel or joystick. Mapping the left-right axis to the mouse is almost perfect for me, but you'd have to remap changing the camera to right-mb+move, which is also not perfect, because that conflicts with using cranes. If there are other options, I don't know of, I'm happy to hear.

**Comment by TobiHH78** [comment]
And if you are running 5 helpers same time, and you jump between them, than suddenly all of them become your daughters?

Sorry, but for me this request makes not much sense. The helper is used, so it has to be paid, that´s my opinion.

**Comment by Iwan1803** [comment]
And if i switch fast enough through all verhicle, no one gets paid... 🙄
I've been driving with the keyboard for a long time and it is a matter of practice until you master it. 
This and the daughter story are not arguments for me to disable helper wages just because you are in the vehicle.

**Comment by thraidh** [comment]
If I wanted not to pay anything, I'd just use the already existing option to set the wage to 0%. And I guess there is an in-game justification that this is possible, which I haven't found written down anywhere.

Your justifications boil down to "I have a different play style than you and yours is not valid" or "I acknowledge the shortcomings of the game controls, but after _a long time_ you get used to it, so there is no reason to make any improvements", which are not really good justifications for closing a request.

A good justification would be: "This seems to be a very uncommon request and implementing and maintaining it would take too much of the already sparse developer resources without adding an equal amount of perceived value to the whole user base."

**Comment by Iwan1803** [comment]
Why do some people think that we always have to implement what they "wish" us to do?
If your suggestion had been posted by hundreds of others as well, we could think about it.
However, since your "idea" doesn't really make sense, we don't need to do that.

**Comment by thraidh** [comment]
I don't think that at all. If you read the last paragraph of what I've written above again, you'll see that it is mostly the same as what you wrote (albeit without putting a value on the idea) and I perfectly accept that. Just don't tell people "Your idea is stupid" (with these or other words). Tell them, that the idea does not benefit enough users to justify using limited developer resources for that.

Anyway, you probably know the VCA mod. That one allows you to automatically keep lanes and also automatically drive to the next one (at the push of a button). All that automatic driving does not involve any helpers and does not cost anything. What I wanted is in that same spirit except that the vehicle does not keep and switch lanes, but follows an AutoDrive network.
This could be implemented into VCA if it would access the AutoDrive network or by setting the wage of the AutoDrive helper to 0. I guess the latter would be way easier to implement and it would have the additional benefit that AutoDrive takes care of the vehicle speed, which is not even what I'm after.

But I see now, that I actually want assisted driving, which could be implemented as a no-wage AutoDrive helper, but only requested the solution without explaining my problem. I'll try to better in the future.

**Comment by Iwan1803** [comment]
"I am only responsible for what i write - not for what others understand."
I didn't say that the idea is stupid, but it doesn't make sense to stop paying wages while the player is sitting in the vehicle.

**Comment by thraidh** [comment]
So, does it make more sense if I ask for an assisted driving mode, that automatically activates, when I use "Goto" and I'm in the vehicle, but does not use helpers?

**Comment by thraidh** [comment]
Btw, I'm completely fine, if you say, that AD isn't meant for that and accept that helpers should be paid. I just think, that the idea is sound, even if it may not fit into the vision of what AD should be and therefore AD is not the right place for it to be implemented in.

**Comment by TobiHH78** [comment]
> So, does it make more sense if I ask for an assisted driving mode, that automatically activates, when I use "Goto" and I'm in the vehicle, but does not use helpers?

Honesly, no. It does not make more sense.
Your daughter story and the automated modern car argument are weak and not very convincing.
You had an idea and ask for implementation, which is totally fine.
But you got a clear NO for that, so you should accept it and stop the further discussion.
