### ISSUE TITLE
AD+CP: Abholen und Abliefern mit dem elho steinsammler funktioniert nicht

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#460]
Hallo Leute
ich habe einen CP kurs zum steinsammeln, und möchte den vollen sammler auf HB zum viehmarkt abladen schicken.
der sammler arbeitet mit CP, aktuelles main auf deren github, und füllt den sammler zu 100% an. AD (version dev-axel) übernimmt den aber nicht zum abtransport, obwohl das cp-symbol im AD-hud angewählt ist.
wenn ich manuell cp beende und ad aktiviere fährt er mit ad abladen, zu mfeld zurück und cp setzt dort fort wo cp beendet hat
ist das ein ad oder ein cp problem?
mit ladewagen und strohschwad funktioniert es super.
lg
andreas

**Comment by Iwan1803** [comment]
Wenn CP nicht an AD übergibt, ist das kein AD-Problem und wenn ich nicht falsch liege, dann ist CP mit dem Steinesammler noch nicht so weit.
