### ISSUE TITLE
Tanken eines mobilen Tankwagens am Fluss/See nicht möglich !?

### ISSUE THREAD

**Issue by WernerWusel** [Stephan-S/FS22_AutoDrive#461]
Hallo AD-Team

Ist es nicht möglich, einen Tankanhänger im Fluss zu betanken ? AD fährt den Tank normal ins Wasser und bliebt stehen, tankt aber nicht. Erst muss AD ausgeschaltet werden, dann ist es mit Taste "R" möglich den Tank zu befüllen.
Wenn der Tank voll ist, kann man AD wieder einschalten und es geht normal weiter.

Danke für die Hilfe.

**Comment by Iwan1803** [comment]
Nicht jeder See hat auch einen Trigger, den AD zum Betanken erkennt. Warum Giants das so "seltsam" gemacht hat, weiß ich nicht.
Ich würde einen Hydranten empfehlen, welchen man sich irgendwo platziert und von dem aus man dann das Wasser entnimmt.

**Comment by WernerWusel** [comment]
Dann sag mir doch mal Bitte, in welchem "Baumarkt" ich einen Hydranten finde. Bei mir gibt es keinen.

**Comment by andreasthu** [comment]
https://www.farming-simulator.com/mods.php?title=fs2022&searchMod=Hydrant
Da sind mal einige 
Lg
Andreas
