### ISSUE TITLE
Spiel hängt sich auf

### ISSUE THREAD

**Issue by Danielmeier1985** [Stephan-S/FS22_AutoDrive#462]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8392230/log.txt)

Version 2.0.0.5

Der Fehler führt dazu, dass das Spiel hängen bleibt und beendet werden muss.

**Comment by regs1980** [comment]
Du musst auch mindestens den Paletten Autoloader Spezialisierung Mod Version 1.6.2.0 haben, hier https://forbidden-mods.de/filebase/file/27909-ls22-paletten-autoloader-spezialisierung/#overview bekommst du immer den aktuellen.

**Comment by Iwan1803** [comment]
Das steht auch in den Release Notes: mind. 1.6.0.0
Davon abgesehen haut FS22_Grimme_SL8022_Autoload haufenweise Warnings raus, weil da zu viele Farbconfigs eingetragen sind.
