### ISSUE TITLE
Request - Scheduled work

### ISSUE THREAD

**Issue by CurtisFeatures** [Stephan-S/FS22_AutoDrive#463]
I think it would be really cool if you could schedule work to take place at set times (mainly for dedis) where you can set certain tasks to take place at a set time - Like feeding animals for example.

**Comment by Iwan1803** [comment]
I think that this is not possible as script mods can't set up a scheduler (if i'm not wrong).

**Comment by CurtisFeatures** [comment]
I'm pretty sure there is a cow shed that does scheduled feeding.

**Comment by Tensuko** [comment]
> I'm pretty sure there is a cow shed that does scheduled feeding.

Thats a whole other things.

**Comment by Axel32019** [comment]
To much efffort for 1 use case, increasing complexity...
