### ISSUE TITLE
AD fährt am Zielpunkt weiter, wenn ich im Fahrzeug sitze

### ISSUE THREAD

**Issue by TheDardevil79** [Stephan-S/FS22_AutoDrive#464]
Wenn ich einen Traktor oder Drescher mit autodrive fahren lasse und im Fahrzeug sitze hält dieser am Zielpunkt nicht an sondern fährt einfach weiter

**Comment by Iwan1803** [comment]
Dann hör auf, Gas zu geben 😉
Ansonsten wären mehr Infos hilfreich...

**Comment by TheDardevil79** [comment]
was für infos brauchst du da genau da ich sowas noch nicht gemacht habe

**Comment by Iwan1803** [comment]
Schau mal hier rein: #1
