### ISSUE TITLE
REQUEST Überarbeitung 

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS22_AutoDrive#465]
Hallo,

könntet ihr das Thema CP-Button nochmals überdenken?

Es kommt so oft vor, dass man den "Fahren-Modus" mit CP verbinden muss (beim grubbern,  Häcksler, alle Feldarbeiten ohne Tanks)

Wäre es möglich, um die ungewollten Schleifen zw. CP und AD zu verhindern, nur den aktiven CP-Button zu deaktivieren, sobald eine Übergabe stattfand?

Ansonsten läuft das Ding ja schon sehr geil, vor allem die turns auf den Felder sehen viel besser  aus..

Danke dafür
Eric

**Comment by regs1980** [comment]
> Wäre es möglich, um die ungewollten Schleifen zw. CP und AD zu verhindern, nur den aktiven CP-Button zu deaktivieren, sobald eine Übergabe stattfand?

Von was für einer Schleife redest du?

**Comment by Iwan1803** [comment]
Aus den Release Notes:
- Deaktivierung CoursePlay-Button in den AD-Modi "Fahren" und "Abladen"
Wenn es nicht funktioniert, dann bitte mehr Infos hierzu.

**Comment by eric4072** [comment]
Problem dürfte wieder mal vorm PC sitzen... 

Problem dürfte auch von CP-Seite gefixt worden sein...

Danke

**Comment by Iwan1803** [comment]
Gerne und ich mach hier erstmal zu 😉
