### ISSUE TITLE
ÜLW Aktive Abfahrt klappt nicht / Setzt vom Drescher nicht zurück

### ISSUE THREAD

**Issue by NeonRider1999** [Stephan-S/FS22_AutoDrive#467]
Hallo. 

Fahrzeuge: Drescher + Traktor Mod
                   ÜLW Orginal Giants

AD Version: 2.0.0.5
CP Version: 7.0.1.9

Und zwar lasse ich mein Feld von einem Drescher Dreschen und von einem ÜLW Abfahren. Problem ist ich habe Aktives Abfahren auf Aktiviert und bei CP die Einstellung ,,Beim Abtanken stehen bleiben" deaktiviert.

![fsScreen_2022_04_02_15_43_20](https://user-images.githubusercontent.com/80832669/161386248-cb807a33-cd27-458e-adb9-24f0553f2666.png)

Wie im Bild zu sehen bleiben beide Trotzdem stehen. 

2. Problem

Nach dem erfolgten Abtanken setzt der Abfahrer nicht zurück sondern bleibt stehen. Dadurch fährt der Drescher nicht weiter
![fsScreen_2022_04_02_15_45_03](https://user-images.githubusercontent.com/80832669/161386340-18ac4c04-7cde-4ecf-825d-73c28b7bc021.png)

Log
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8402651/log.txt)

Nun weiß ich nur nicht ob das allgemein noch nicht richtig klappt, es ein BUG ist oder es meine Inkompetenz ist :D

Ich hoffe es ist auch ok das ich gleich 2 Sachen in ein Issue Packe.

**Comment by NeonRider1999** [comment]
Edit: Das Problem das der Drescher nach dem Bunkern nicht weiter Fährt tritt nur im Vorgewende auf !

**Comment by ct177mak** [comment]
Hast Du abtanken im ersten Vorgwende aktiviert ? wenn ja mal deaktvieren ,vllt klapps denn ,oder ich lieg völlig daneben .

**Comment by 60erjonny** [comment]
@ct177mak ...diese Einstellung ist aber in CP zu machen...

**Comment by ct177mak** [comment]
Ja ich weiss ,vergas es dazu zuschreiben sry ,aber CP und AD comunizieren nun mal gerne wenns ums Abfahren der Drescher geht , ich habe z.B Fruchtumfahrung aktiviert und im CP das abtanken im Vorgewende deaktiviert ,zumal meine MAp außen garnicht den Platz hätte zum abtanken des Dreschers.

**Comment by ct177mak** [comment]
sry ja stimmt CP vergessen zu erwähnen ,Asche auf mein Haupt :)

**Comment by NeonRider1999** [comment]
@ct177mak Nein das ist Deaktiviert

**Comment by Iwan1803** [comment]
Warum soll AD da zurücksetzen? Immerhin behindert der Abfahrer den Drescher ja nicht an der Weiterfahrt, da er ja neben ihm steht und wenn aktives Abfahren aktiviert ist, warum wartet der Abfahrer im 2. Bild dann auf den Ruf vom Drescher?
Im ersten Bild ist zudem der normale Fahren-Modus eingestellt.
Irgendwas passt da also nicht so ganz an den Bildern oder der Problembeschreibung... 🙄

**Comment by Iwan1803** [comment]
Schon mal dran gedacht, das es am Drescher-Mod liegen könnte?
Versuch es doch mal mit Vanilla-Fahrzeugen, bevor wir hier weiter rumrätseln, welche Einstellung falsch sein könnte.

**Comment by NeonRider1999** [comment]
Also es ist ein Drescher Konflikt. Beim Vanilla Fendt Drescher geht es

**Comment by ct177mak** [comment]
also was sagt uns das ? immer schön Vanilla testen ,nicht mit Mods :)
