### ISSUE TITLE
Click to switch

### ISSUE THREAD

**Issue by svabo1977** [Stephan-S/FS22_AutoDrive#468]
Keine Funktion von Click to switch unter Autodrive 2.0.0.5 😩

**Comment by schwiti6190** [comment]
@svabo1977 Click to switch only works, when the autodrive editor mode is deactivated and the mouse is not over the ad hud. This is by design as it would interfere with the moving of waypoints and so on .. :)

**Comment by svabo1977** [comment]
oh ! ok Thank you

**Comment by Iwan1803** [comment]
Da Frage/Problem scheinbar geklärt -> geschlossen 😉
