### ISSUE TITLE
Frage, Abladestelle von beiden Seiten anfahrbar?

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#469]
Hallo Leute, 
Wegen einer sondersituation auf einer map frage ich mal, ob es möglich ist, eine Abladestelle von beiden seiten mittels blauer linie Anzufahren?
Normal ist der zielpunkt ja immer hinter die abladestelle zu setzen, d.h. ich müsste je einen punkt links und rechts der abladestelle setzen, und beim abladepunkt im AD hud dann immer den richtigen (in anfahrtsrichrung hinter der schütte) punkt wählen?
Mittig am trigger geht ja nichts.
Lg
Andreas?

**Comment by Iwan1803** [comment]
Wie wäre es mit 2 grünen Linien, welche über den Trigger gehen?

**Comment by andreasthu** [comment]
Hallo iwan,
Das wäre aber dasselbe "in grün"
Trotzdem nur mit zwei abladepunkten zu lösen.
D.h. ich muss mich entscheiden ob der abladepunkt von links bzw von rechts angefahren wird, nämlich indem ich denjenigen triggerpunkt wähle der in anfahrtrichtung hinter der schütte liegt.
Lg
Andreas

**Comment by Iwan1803** [comment]
Die aktuelle Situation ist nun mal wie oben beschrieben: der Zielpunkt muss in Fahrtrichtung hinter dem Trigger liegen.
Entweder machst du 2 Zielpunkte und das mit grünen Linien, wenn von beiden Seiten aus rangefahren werden soll oder eben nicht.
Diese Logik, welche einfach mal funktioniert, um irgendwas zu erweitern, nur weil du eine nicht näher beschriebene "Sondersituation" hast, würde wohl den Aufwand nicht rechtfertigen.

**Comment by Tensuko** [comment]
Ich weis nicht wie gut AD rückwärts fahren kann, aber wenn du vom Süden kommst und dann rückwärts "in die nördliche" Einfahrt fährt?
Kann das klappen?
Müsste natürlich der rückwärtspart an dem Weg zur Ziel am Südeingang anknüpfen.

Hab mich nur noch 0 mit Rückwärts fahren bei AD beschäftigt ob der das so hinkriegt.
Müsste halt in der Berechnung für den Weg mit einbezogen werden.

**Comment by rohne83** [comment]
Von Süden rein in die Einfahrt, Abladepunkt hinterm Trigger, und im Norden wieder raus. Mit bischen Ausholen sollte sich das den Bildern nach durchaus auch in beiden Richtungen auf der Straße anbinden lassen. Extra für so nen Spezialfall werden die AD-Jungs da sicher kein neues Feature implementieren das vieles der bisherigen Logik über den Haufen werfen würde.

**Comment by Axel32019** [comment]
Probier mal dies:
![469](https://user-images.githubusercontent.com/52026009/161793562-8104e5f3-eb33-44d7-8a1f-733852e40c9b.png)

**Comment by andreasthu** [comment]
Hallo Leute:
Dank dir axel, werd das aber ev so machen:
![unnamed](https://user-images.githubusercontent.com/24860501/162043730-a87ccfce-b53a-42b3-a69c-420f859b6432.png)
Sry für die laienhafte skizze, geht am handy nicht anders, aber ich werds probieren von spden normal reinzufahren und nach norden normal raus, nach Süden mit einer schleife. Ev werden einige bäume dran glauben müssen.
Von norden kommend werd ich auch mal vorbeifahren und mit einer schleife dann von süden die ablade anfahren. Bäume im weg werden gefällt.
Da die Frühlingsmap eher eng ist, fahr ich da mit drehschemel, da ist rückwärts reversieren eher ungünstig.
@rohne83 
Ich hab nur angefragt, keine rede vom ändern  der AD logik.
Es ist immer gut ideen von anderen anzufragen, sonst wird man betriebsblind.
Btw, bin solche traktoren selber lange gefahren, mein größter war ein JD mit 240ps.
Heute fahre ich noch gerne mit meinem 8130 steyr rum, die anhänger sind aber kleiner, max 6t nutzlast.
Lg
Andreas

**Comment by Axel32019** [comment]
nichts Neues -> closed
