### ISSUE TITLE
Rückwersfahren und drescher Probleme 

### ISSUE THREAD

**Issue by ppeell** [Stephan-S/FS22_AutoDrive#47]
Guten morgen mir ist aufgefallen wenn man Kurse einfährt und zwar rückwärts das die Punkte viel zu weit hinterm Fahrzeug kommen und man nicht vernünftig einfahren kann. Sondern man muss dan alle Punkte mit der Maus richten. Und was mir auf gefallen ist bein drescher abtanken bleibt der AD Fahrer stehen wenn er vertig abgetankt hat im ls19 ist er immer ein Stück zurück gefahren. Dadurch das der AD das im 22 nicht macht bleibt manchmal der drescher leer stehen mit ausgefahrenen rohr und will nicht weiter fahren erst wenn ich den AD abschalten und ein Stück zurück fahre.

**Comment by BigBlackBahamut** [comment]
Ich habe es noch nicht ausprobiert, aber ich habe schon in LS19 den Abfahrer verboten auf dem Feld zu Parken. Vielleicht löst das dass Problem das der Abfahrer auf dem Feld neben dem Drescher stehen bleibt.

**Comment by regs1980** [comment]
> Guten morgen mir ist aufgefallen wenn man Kurse einfährt und zwar rückwärts das die Punkte viel zu weit hinterm Fahrzeug kommen und man nicht vernünftig einfahren kann.

Es gibt nicht nur eine Variante von Rückwärts schrecken zu bauen, die Variante die ich bauen ist einfacher man muss nur einmal gerade aus fahren dunkelblaue Linie, einen Zusatzpunkt oben drüber setzen für die hellblaue Linie, darunter noch einen für die grüne Zubringerlinie und durch die neue Funktion mit dem Mausrad wird die ganze Sache einfacher. 

<img width="1370" alt="2021-12-21 12_05_41-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/146922276-06a7f5b1-9a42-42ec-908e-857244410259.png">

<img width="704" alt="2021-12-21 12_07_31-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/146922292-82fe3653-0d89-4441-805b-2655b7d7403c.png">

Dieses mache ich schon seit LS19 und es klappt wunderbar.

**Comment by ppeell** [comment]
Ok danke das versuche ich mal

**Comment by ppeell** [comment]
Kann man die hellblaue Linie auch mit der Maus setzen oder nur mit dem Fahrzeug?

**Comment by ppeell** [comment]
> > Guten morgen mir ist aufgefallen wenn man Kurse einfährt und zwar rückwärts das sterben Punkte viel zu weit hinterm Fahrzeug kommen und man nicht vernünftig einfahren kann.
> 
> Es gibt nicht nur eine Variante von Rückwärts schrecken zu bauen, die Variante sterben ich bauen ist einfacher, man muss nur einmal gerade aus fahren dunkelblaue Linie, einen Zusatzpunkt oben drüber setzen für die hellblaue Linie, darunter noch einen für die Zubringerlinie und durch die neue Funktion mit dem Mausrad wird die ganze Sache jetzt noch einfacher.
> 
> <img alt="2021-12-21 12_05_41-Landwirtschaftssimulator 22" width="1370" src="https://user-images.githubusercontent.com/13314443/146922276-06a7f5b1-9a42-42ec-908e-857244410259.png">
> 
> <img alt="2021-12-21 12_07_31-Landwirtschaftssimulator 22" width="704" src="https://user-images.githubusercontent.com/13314443/146922292-82fe3653-0d89-4441-805b-2655b7d7403c.png">
> 
> This mache ich schon seit LS19 und es klappt wunderbar.

Kann man die hellblaue Linie auch mit der Maus setzen oder nur mit einem Fahrzeug?

**Comment by regs1980** [comment]
> Kann man die hellblaue Linie auch mit der Maus setzen oder nur mit dem Fahrzeug?

Ja natürlich rechte Shifttaste drücken und linker Maustaste.

**Comment by BigBlackBahamut** [comment]
Für was war noch mal braun?

**Comment by regs1980** [comment]
> Für was war noch mal braun?

Nebenstraßen, hell in eine Richtung und dunkel in beiden Richtungen.

**Comment by BigBlackBahamut** [comment]
> > Für was war noch mal braun?
> 
> Nebenstraßen, hell in eine Richtung und dunkel in beiden Richtungen. Hellbraun ideal für Feldzufahrten oder dunkel braun für Feldwege die beidseitig befahren werden können.

Ahh. Okay. Danke :-)

**Comment by regs1980** [comment]
> Dadurch das der AD das im 22 nicht macht bleibt manchmal der drescher leer stehen mit ausgefahrenen rohr und will nicht weiter fahren erst wenn ich den AD abschalten und ein Stück zurück fahre.

Wenn du AIV benutzt liegt das nicht an AD.

**Comment by ppeell** [comment]
> > Das der AD das im 22 nicht macht bleibt manchmal der drescher leer stehen mit ausgefahrenen Rohr und will nicht weiter fahren erst wenn ich den AD abschalten und ein Stück zurück fahre.
> 
> Benutzt du AIV als Helfer?

Benutze aiv

**Comment by regs1980** [comment]
Mit dem Standard Helfer fährt der Drescher oder Ernter weiter nach dem er leer ist, liegt also an AIV eher.

**Comment by DarkDoldier** [comment]
> Mit dem Standard Helfer fährt der Drescher oder Ernter weiter nach dem er leer ist, liegt also an AIV eher. Bei AIV die Kollisionskontrolle deaktivieren.

Kennst du eine Lösung für AIVE Häcksler und AD? Bei mir ist trotz ausgeschalteter Kolli bei AIVE immer etwas im weg wenn der AD daneben ist. Die Abstandsregelung kann ich nicht erhöhen in AD( Habe einen issue gemeldet ist noch offen) egal welche Zahl der Abstand bleibt gleich.

**Comment by Axel32019** [comment]
Geschlossen mit #58
