### ISSUE TITLE
Strecken und Parkplätze nach Serverneustart weg

### ISSUE THREAD

**Issue by Sensai25** [Stephan-S/FS22_AutoDrive#471]
Hi nachdem wir unseren Server neustarten, werden alle Strecken auf "Shop" gesetzt. Sodass wir immer alle Kurse neu anlegen müssen. 
Desweiteren werden alle Parkplätze gelöscht. 

Karte ist die La Plaine France

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8412466/log.txt)

**Comment by Iwan1803** [comment]
Das liegt daran, weil ihr die meisten Mods von einer bekannten Modklau-Seite "fs22planet" runtergeladen habt. Das erkennt man daran, das die Mods alle den Namen "_fs22planet" im Namen haben und vor allem keiner so genau weiß, was sie nicht noch alles am Mod verändern.
Wenn ich das schon sehe und wieviele Mods da Warnings und Errors ins Log schreiben, wird mir ganz anders.
Besorgt euch doch bitte nach Möglichkeit die Mods von den Original-Modderseiten oder zumindest vertrauenswürdigen Quellen.

Für AutoDrive kann ich sagen, das eine umbenannte ZIP genau zu solchen Problemen führt, wie ihr sie gerade habt.

**Comment by Axel32019** [comment]
Available mod: (Hash: f40c4d2a87dbe9074ad92fb472e4240d) (Version: 2.0.0.5) FS22_AutoDrive_fs22planet
FS22_AutoDrive_fs22planet -> closed
