### ISSUE TITLE
Seeder/Planter Refill

### ISSUE THREAD

**Issue by Resandise** [Stephan-S/FS22_AutoDrive#472]
Using a Seeder/Planter with dual tanks for Seeds and Fertilizer, there is not an option to fill both, we can only fill one or the other.  Using CP to do the field work, and the Load option in AD, we can only chose one fill type, so when the other is empty, its stops

**Comment by Axel32019** [comment]
> Using a Seeder/Planter with dual tanks for Seeds and Fertilizer, there is not an option to fill both, we can only fill one or the other. 
AD will always fill seeders with seed and fertilizer, does not matter what one you select.
Using CP to do the field work, and the Load option in AD, we can only chose one fill type, so when the other is empty, its stops
You should set unload fill level to 90,95,99 %, so all fill units will be refilled before return to field.

**Comment by Resandise** [comment]
That works when the pickup for both Seeds and Fert are the same place or right next to each other, but it they are spread out or in two different locations, it does not fill both.

**Comment by TimoR1014** [comment]
set the distance to find a trigger higher (50 or even 100m) and let the traktor drive though both. than it should work.

**Comment by Axel32019** [comment]
no update -> closed
