### ISSUE TITLE
Repair Lua Errror on NF-Marsch

### ISSUE THREAD

**Issue by Thesralcraft** [Stephan-S/FS22_AutoDrive#473]
NF-Marsch 4gach without dig version 1.4.1
Autodrive Version 2.0.0.4

2022-04-05 10:47 Warning (script): Unknown entity id 168243 for 'object' in method 'getWorldTranslation'.
2022-04-05 10:47 LUA call stack:
  =D:/home/sid_3163771/farmingSim_2022/profile/mods/FS22_AutoDrive/scripts/Manager/TriggerManager.lua (604) : getWorldTranslation
  =D:/home/sid_3163771/farmingSim_2022/profile/mods/FS22_AutoDrive/scripts/Modules/TaskModule.lua (157) : getClosestRepairTrigger
  =D:/home/sid_3163771/farmingSim_2022/profile/mods/FS22_AutoDrive/scripts/Modules/TaskModule.lua (94) : RepairIfNeeded
  =D:/home/sid_3163771/farmingSim_2022/profile/mods/FS22_AutoDrive/scripts/Specialization.lua (395) : update
  dataS/scripts/specialization/SpecializationUtil.lua (19)
  dataS/scripts/vehicles/Vehicle.lua (1883) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (129) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1133) : update
  dataS/scripts/FSBaseMission.lua (1974) : update
  dataS/scripts/missions/mission00.lua (583) : update
  dataS/scripts/main.lua (1381) : update
2022-04-05 10:47 Error: Running LUA method 'update'.

**Comment by Tensuko** [comment]
> Autodrive Version 2.0.0.4

Find the Error...

**Comment by Iwan1803** [comment]
Please update to latest version and try again: https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.5/FS22_AutoDrive.zip
