### ISSUE TITLE
Produktinsfabriken

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#474]
Hallo
Ich will bei ein bereits erstellten Streckennetz noch eine Produktion wie die Silageherstellung mit einbinden, wie geht das ? Oder welche Tutorial wäre dafür Hilfreich

**Comment by andreasthu** [comment]
Die hier von iwan1803:
https://m.youtube.com/playlist?list=PL5cOkXj5iscrkh_7Iz6IFOt5oyP732sAZ
Lg
Andreas
