### ISSUE TITLE
autofuel

### ISSUE THREAD

**Issue by levisbaja** [Stephan-S/FS22_AutoDrive#480]
hi,

I have an oil pump jack production point on the map, diesel input, crude oil output. the buying station has only crude oil filltype. When a driver wants to buy some fuel, always drives to this production point and driving around to find the diesel buying station even there is non.

**Comment by levisbaja** [comment]
I said it has only diesel input and crude oil output. 
![image](https://user-images.githubusercontent.com/50078961/163028587-2b80aebc-c11b-47ba-93eb-48286e125594.png)

**Comment by Iwan1803** [comment]
Are you using the mod for AdBlue/DEF?

**Comment by levisbaja** [comment]
yes

**Comment by Iwan1803** [comment]
Than maybe this is the problem.

**Comment by levisbaja** [comment]
shouldnt. aurodrive.lua has def filltype as fuel
![image](https://user-images.githubusercontent.com/50078961/163400726-742d376b-7516-404b-9ab8-fcc2af020b24.png)

**Comment by Axel32019** [comment]
@levisbaja You know how this table is used inside AD? If not please look for it.

**Comment by Axel32019** [comment]
no update -> closed
