### ISSUE TITLE
Rotation Beladen mit Paletten

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS22_AutoDrive#481]
Moin, ich weiß nicht ob das so gewollt ist, aber wenn AD mit Paletten zum Lager fährt kommt es schonmal vor, das Paletten schon komplett von der Ladefläche verschwunden sind bevor AD den Zielpunkt erreicht hat, und bleibt dann nicht stehen und entgurtet. Verschiedene Paletten entladen sich schneller manche langsamer, bei den langsamen kommt das Fahrzeug zum Zielpunkt, dann wartet er die eingestellte Zeit ab, entgurtet und fährt weiter. Wird allerdings nicht entgurtet denkt wohl Autoload das die Paletten noch drauf sind und bei der nächsten Station werden sie nicht richtig geladen sondern stehen mitten auf der Ladefläche oder sogar in der Luft. Habe das auch Achim schon geschrieben. Ich weiß jetzt nicht wer da vielleicht was machen kann.

LG Timmi

**Comment by Axel32019** [comment]
Moin @timmi4026 , AD prüft den Füllstand. Dieser wird von AL abgefragt - sehe ich somit als Thema für Achim.
Hast Du dazu was von ihm gehört?

**Comment by timmi4026** [comment]
Glaub die letzte Version von Achim scheint zu gehen, ich beobachte das mal weiter. Gibt es bezüglich der Belade Rotation mit einstellbarem Warteintervall schon was neues?

**Comment by Axel32019** [comment]
> Glaub die letzte Version von Achim scheint zu gehen, ich beobachte das mal weiter. Gibt es bezüglich der Belade Rotation mit einstellbarem Warteintervall schon was neues?

Siehe #431

**Comment by timmi4026** [comment]
Um das Issue abzuschließen, mit Achim seiner neuesten Version klappt es.
