### ISSUE TITLE
Suggestion: Traffic Light System

### ISSUE THREAD

**Issue by joaoesp** [Stephan-S/FS22_AutoDrive#483]
I don't know if someone mentioned this or not.
A lot of times the vehicles run into each other in tight turns or narrow roads.
What if we could have a system that stops vehicles at 1 point (red light) when the opposite side has a vehicle passing (green light)?
I don't know if this is the best solution for this problem or if its a problem for other people at all.
Please lmk what you think.

**Comment by Iwan1803** [comment]
This makes AD unnecessarily complicated and implementation would not justify the time investment. 
However, at tight curves or intersections, you can fall back on the blue lines. On these, vehicles can only drive in one direction and oncoming vehicles will wait beforehand.

**Comment by joaoesp** [comment]
The main goal was not to account for game traffic but to control the traffic of your own vehicles.
I do understand if it's something complicated to implement because of the vehicle detection though...

**Comment by Iwan1803** [comment]
Very old... -> closed!
