### ISSUE TITLE
Unload combine: Clearing crop is actually parking in crop

### ISSUE THREAD

**Issue by PhoenixtheII** [Stephan-S/FS22_AutoDrive#484]
Autodrive 2.0.0.5
TLX Phoenix + trailer bulk flatbed

Truck is just finished unloading a harvester. Reverses into freshly harvested field. Harvester continues... Truck: waiting for room
After a moment, Truck: "Clearing crop" -> decides to go from harvested area, into parking in yet to harvest crop.

**Comment by Iwan1803** [comment]
Which map? Which field? Which fruit? Screenshot? Log?

**Comment by PhoenixtheII** [comment]
Map: https://forbidden-mods.de/filebase/file/29533-nordermarsch/#overview
Field 17: wheat
Field 32+33 (merged): Potatoes
Field 8: Barley

Courseplay helper is driving the harvesters. Headland: 2, clockwise, 18.2m durex header + claas lexion 8900.

I'll try make a screenie when it happens next time.
