### ISSUE TITLE
Auto refuel selecting fill points that don't seem to  fill vehicles just trailers and possible suggestions for

### ISSUE THREAD

**Issue by judg393** [Stephan-S/FS22_AutoDrive#485]
Hi 

I'm loving AD first off great job and the wealth of new possibilities from 19 to 22 is incredible. 
I'm struggling however to get vehicles to refuel it seems like I tell it to go to refuel from the keybinds and it does nothing or continues to the last selected destination. 

Sometimes it does seem to work but it seems to select a factory mod this [one](https://farmerboysmodding.com/index.php?/files/file/182-fs22-chemical-plant/)

And just drive to the point that outputs fuel to a trailer not refuelling the vehicle which the factory does from another point. Not sure if this is just my settings or what. It then gets stuck trying to drive to the refuel point https://user-images.githubusercontent.com/55981682/162752960-d3fa8735-4090-43d6-ab11-5748197d0cb9.MOV

Having said that I need to try without a fuel trailer to see if that works but surely it should ignore whatever its got attached if I tell it to refuel. 

This started because I wanted to use the refillable tank I had to refuel not buy fuel at the petrol station. But it doesn't seem to recognise this as a refuel point [[mod](https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=226035&title=fs2022)]or base game version  at least for me. 

I think we could get around this quite easily (at least to a none developer) by reusing the "park" feature but instead make it fuel related I'd be happy if I had to manually set each fuel point (like park) but I guess if there's a way to have one per map or maybe a handful (5/6) and then maybe have AD calculate which is closest and go there.  Again I say I'd be happy with a direct go to manual point a refuel and need to set this per vehicle but others may not. I do think we'd need more than 1 point per map ideally though. If it's even possible. 

Secondly I read you brought in autoload support for architmobils script not used it yet but interested however I wondered if you could add support for [universal autoload ](https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=237080&title=fs2022) which also has a GitHub page? Again not sure on the complexity or if the modder of UAL would give permission 😂 but maybe worth an approach?

**Comment by Axel32019** [comment]
Hello @judg393 , For the refuel topic I hope found a solution yesterday.
Feel free to test it: https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

The support universal autoload is not so easy, as we need interface funtions in the mod itself. Let's see what will come up in the future...

**Comment by judg393** [comment]
Oh also the dev of UAL mentioned he wasn't sure whether UAL would work with AD so absolutely understand it's a pipe dream

**Comment by judg393** [comment]
Hi @Axel32019 sorry for the multiple tags someone told me to swap out standard AD with your AD link. To test the configuration you supplied. I've been met with limited success. 

The tractor no longer got stuck at the trailer refill point but it drove through the refuel trigger without refuelling. It also used the factory refuel point (not that this is a problem) 

It's now stuck in a loop with the driver of XXX to refuel station message on screen. 

Also I presume it's intentional to only have the tractor respond once it gets low on fuel? ![image](https://user-images.githubusercontent.com/55981682/163067372-25118ed5-5f62-4d36-806e-91f90c3ea561.jpeg)

**Comment by judg393** [comment]
> > Hi @Axel32019 thanks for your response can you tell me how I test it? Do I need to overwrite something in the AD file? Sorry I'm completely new to this kind of testing :) but more than happy to test
> 
> 
> 
> Open link https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019
> 
> Code -> Download ZIP -> save 
> 
> Extract ZIP -> step inside and zip again so it is like the original release

Done this thank you (sorry for the obvious question) see results above

**Comment by timmi4026** [comment]
Moin, ich glaube judg393 hat das FS22_DefPack mit im Spiel, sobald das drauf ist, klappt das Tanken nicht mehr. Hab das gleiche Problem, auch mit der dev Version geht es nicht. Nehme ich das FS22_DefPack raus klappt das Tanken wieder.

**Comment by judg393** [comment]
No def pack mod installed knowingly buddy? I don't usually mess with that kinda mod  I could try removing the factory incase it's that but to be honest I'm probably just gonna manually refuel unless anyone else has any ideas

**Comment by Axel32019** [comment]
The refuel topic is stil WIP - stay tuned....

**Comment by judg393** [comment]
Ok thanks @Axel32019 do you still want this open? I'm happy to close it until an official update unless you want me to test anything prior.

**Comment by Axel32019** [comment]
We keep it open until topic is complete.

**Comment by judg393** [comment]
fab ok well i look forward to seeing it in action soon then :)

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip

**Comment by judg393** [comment]
Thank you Iwan I'll test and report back :)
