### ISSUE TITLE
Abfahrer Fährt mit Vollgas in enge Kurven 

### ISSUE THREAD

**Issue by Playlord75** [Stephan-S/FS22_AutoDrive#486]
Hallo ich habe ein Problem unzwar weiß ich nicht was ich noch ausprobieren soll meine abfahrer Rassen mit Vollgas in jede kurve rein und Bremsen erst wenn sie mitbekommen haben das sie vom kurz abgekommen sind
 Distanz Vorausschauend habe ich auf 8m gestellt aber es ändert sich leider nichts
![fsScreen_2022_04_11_17_12_40](https://user-images.githubusercontent.com/71101944/162772389-2c7dd75b-9a6c-4286-bf48-2e82de9c4cfc.png)
![fsScreen_2022_04_11_17_19_13](https://user-images.githubusercontent.com/71101944/162772400-00ead8c6-ef8e-4ec0-950b-50b0bfce476e.png)
![fsScreen_2022_04_11_17_20_09](https://user-images.githubusercontent.com/71101944/162772409-47c9d7b5-609b-4c80-b737-cf47efaa847a.png)

**Comment by Axel32019** [comment]
Bitte mal die Kurvengeschwindigkeits-Einstellung reduzieren.

**Comment by timmi4026** [comment]
Ich hab Kurvengeschwindigkeit auf 70%, da fällt nichtmal ein voll beladener Palettenanhänger um.

**Comment by Axel32019** [comment]
@Playlord75 Ausprobiert? Bitte mal die log.txt anfügen.

**Comment by Playlord75** [comment]
ja hat geklappt

**Comment by Iwan1803** [comment]
Super, dann mach ich hier mal zu 😉
