### ISSUE TITLE
Strecke verbinden

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#488]
Hallo
Ich habe eine Strecke eingefahren vom Hof zum Schweinestall und verbunden, er fährt die Strecke aber nicht ab, was habe ich falsch gemacht
![Schweine](https://user-images.githubusercontent.com/47453761/163017163-08a1e653-c7da-4eeb-95fb-a7fd61454c8d.png)

**Comment by manne70** [comment]
man sieht leider die obere Kreuzung nicht, aber geh mal Punkt für Punkt mit der Maus durch dann müsste der vordere und der hintere Punkt aufleuchten wenn eine Verbindung besteht.

**Comment by timmi4026** [comment]
Vielleicht ein zu großer Umweg eingestellt?

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
