### ISSUE TITLE
Ballensammler

### ISSUE THREAD

**Issue by Gummiente1972** [Stephan-S/FS22_AutoDrive#489]
Nach dem Aufsammeln von Ballen in Verbindung mit CP Läd der AD nicht automatisch ab, besteht die Möglichkeit das es noch geädert wird

**Comment by Iwan1803** [comment]
Ein paar mehr Infos wären vielleicht hilfreich... 🙄

**Comment by Gummiente1972** [comment]
Ich fahre mit einem Ballensammler zB auf das Feld 1 wo dieser Per CP die Ballen sammelt wenn er voll ist übergibt CP an AD und fährt dann zum Zielpunkt wo ich dann abladen muss, das jedoch wird nicht automatisch veranlasst das muss per Hand gemacht werden,

**Comment by Iwan1803** [comment]
Welcher Ballensammler? Welche Map? Screenshot vom Trigger inkl. Zielpunkt?

**Comment by Gummiente1972** [comment]
![2022-04-14_2](https://user-images.githubusercontent.com/103626109/163347934-dd74ca12-d387-4afd-9722-1a8a430c18df.png)

**Comment by Gummiente1972** [comment]
4 fach March ohne Gräben

**Comment by Gummiente1972** [comment]
![2022-04-14 (1)](https://user-images.githubusercontent.com/103626109/163348498-f40d1f72-8c34-41f3-8c31-d9d28c606f33.png)

**Comment by Iwan1803** [comment]
Nicht, das ich irgendwas behaupten möchte aber es ist schon sehr auffällig, das sehr oft die Marsch gespielt wird, wenn es um Ballen-Ablade-Probleme geht - sei es an der BGA oder nun da beim Händler.
Nimmt die Gärnerei überhaupt Baumwolle? Zumindest in LS19 war es nicht so, wenn ich mich recht erinnere...

**Comment by eric4072** [comment]
Hallo, hätte da auch eine Frage zum Ballen sammeln.

Wenn ich den Ballensuchmodus (CP ohne Kurs) aktiviert habe, übergibt bei mir CP an AD, der Ballensammler entläd aber auch bei mir nicht, weder mit Autoload noch mit dem Vanilla-Ballensammler.

Egal, ich deaktiviere AD (CP-Button ist an), entlade selbst und schicke AD zurück.

Dann übergibt AD aber nicht mehr an den Ballensammler zurück (Wegpunkt liegt am Feld)

ist das noch nicht implementiert oder mache ich was falsch?

Danke für jede Hilfe

**Comment by Tensuko** [comment]
AD muss auf dem Feld ankommen und nicht neben dem Feld, CP Sucht auf dem Feld auf dem er steht, steht er neben dem Feld, geht es nicht.

**Comment by AlexStephenLytton** [comment]
@Iwan1803 das Problem betrifft nicht nur die Marsch... Beim Viehhandel auf der Elmcreek (Kurs fährt rückwärts an den Abladepunkt) bleibt der Ballensammelwagen auch einfach nur stehen und man muss von Hand abladen.... (Vanilla Ballensammler für Rundballen)

**Comment by Axel32019** [comment]
> ![2022-04-14_2](https://user-images.githubusercontent.com/103626109/163347934-dd74ca12-d387-4afd-9722-1a8a430c18df.png)

Der Zielpunkt muss noch weiter in Fahrtrichtung liegen - hier gilt es probieren bis es funktioniert.

**Comment by Axel32019** [comment]
> @Iwan1803 das Problem betrifft nicht nur die Marsch... Beim Viehhandel auf der Elmcreek (Kurs fährt rückwärts an den Abladepunkt) bleibt der Ballensammelwagen auch einfach nur stehen und man muss von Hand abladen.... (Vanilla Ballensammler für Rundballen)

Rückwärts abladen funktionier (noch) nicht. Nur Durch- oder Vorbeifahren.

**Comment by Axel32019** [comment]
no update -> closed
