### ISSUE TITLE
Eingefahrene Strecken nur mit einem Trecker möglich

### ISSUE THREAD

**Issue by TheUsforcer** [Stephan-S/FS22_AutoDrive#49]
Guten Tag,

ich habe für meinen Häcksler einen Weg erstellt mit abfahren in ein Keilsilo. Klappt gut, bis ich den Traktor wechselte. Auf einmal findet er die Punkte nicht mehr. Ich dachte erst mir ist ein Punkt flöten gegangen, kann in der Hektik ja mal passieren, aber als ich den Traktor wieder zu dem gewechselt hatte mit dem ich die Strecker gemacht hatte, war alles wieder in Ordnung.
Hab ich vielleicht eine Einstellung verkackt, oder sollte das normal gehen?

Liebe Grüße :)

**Comment by TheUsforcer** [comment]
Fehler gefunden, es lag daran, das der Traktor nicht genügend repariert. Der Weg zur Werkstatt war aber vorhanden.

**Comment by Iwan1803** [comment]
Supi, dann mach ich hier mal wieder zu 😎
