### ISSUE TITLE
Herbizid auffuellen an Multifrucht-Einkaufsstation

### ISSUE THREAD

**Issue by schoos76** [Stephan-S/FS22_AutoDrive#490]
Mahlzeit,

ich benutz die Multifrucht-Einkaufsstation https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=224316&title=fs2022 und ein Hardi Rubicon 9000 wurde dort jetzt mehrmals mit  Fluessigdünger statt Herbizid befüllt im "Abholen" Modus, obwohl dort Herbizid eingestellt war - beim letzten Mal waren (wahrscheinlich) sogar noch einige wenige Liter Herbizid im Tank vorm auffüllen. 

Welche Infos kann ich euch zum Debuggen noch liefern?

**Comment by rohne83** [comment]
Wenn ich mich recht erinnere ignoriert AD die eingestellte Fruchtart beim Abholen-Modus für die CP-Feldarbeit sowieso. Zumindest bei Sämaschinen. Bei denen wird da immer versucht Saatgut+Dünger aufzufüllen sofern am entsprechenden Abholen-Punkt auch Trigger für beides erreichbar sind.
Passiert dir das auch mit normalen Spritzen oder nur bei der Rubicon?

**Comment by Iwan1803** [comment]
Wenn noch Herbizid im Tank ist, wieso sollte AD dann Flüssigdünger tanken?
Der Tank muss entweder das enthalten, was getankt werden soll oder er muss halt leer sein.

**Comment by schoos76** [comment]
> Wenn noch Herbizid im Tank ist, wieso sollte AD dann Flüssigdünger tanken? Der Tank muss entweder das enthalten, was getankt werden soll oder er muss halt leer sein.

Das dachte ich eigentlich auch (aber das Gegenteil ist mir jetzt schon mehrmals passiert, auch mit anderen Fluessigkeiten), darum ja auch der Test mit einem Rest Herbizid.


Ich mach jetzt mal nen Test mit nem neuen Spielstand: meine aktuelle Lieblingsmap Huron County, zwei geladenen Mods: Autodrive (2.0.0.5) und die Multifruchtstation, ich nutz die Autodrive-Config fuer die Map, die ich vor ein paar Tagen mal abgespeichert hab und lad die in den Spielstand erstell noch nen rudimentaeren Kurs um Multifruchtstation anzubinden.  

1. Ich erstell fuer ne (gekaufte) Rubicon im Autodrive im Modus "Abholen", Feld 94, die Multifruchtstation, Herbizid und es wird  Duenger statt Herbizid gekauft 
2. Ich kauf nen Traktor (Fendt Vario 311), und ne Spitze Mega 1200L, gleiches Autodrive-Programm. Hier wird tatsaechlich Herbizid gekauft. 

![image](https://user-images.githubusercontent.com/4555004/165494936-41f74db4-5212-4daf-b6f5-25638cd5b40b.png)

**Comment by Iwan1803** [comment]
Das Log hierzu wäre vielleicht noch interessant.

**Comment by Axel32019** [comment]
> > Wenn noch Herbizid im Tank ist, wieso sollte AD dann Flüssigdünger tanken? Der Tank muss entweder das enthalten, was getankt werden soll oder er muss halt leer sein.
> 
> Das dachte ich eigentlich auch (aber das Gegenteil ist mir jetzt schon mehrmals passiert, auch mit anderen Fluessigkeiten), darum ja auch der Test mit einem Rest Herbizid.
> 
> Ich mach jetzt mal nen Test mit nem neuen Spielstand: meine aktuelle Lieblingsmap Huron County, zwei geladenen Mods: Autodrive (2.0.0.5) und die Multifruchtstation, ich nutz die Autodrive-Config fuer die Map, die ich vor ein paar Tagen mal abgespeichert hab und lad die in den Spielstand erstell noch nen rudimentaeren Kurs um Multifruchtstation anzubinden.
> 
>     1. Ich erstell fuer ne (gekaufte) Rubicon im Autodrive im Modus "Abholen", Feld 94, die Multifruchtstation, Herbizid und es wird  Duenger statt Herbizid gekauft
> 
>     2. Ich kauf nen Traktor (Fendt Vario 311), und ne Spitze Mega 1200L, gleiches Autodrive-Programm. Hier wird tatsaechlich Herbizid gekauft.
> 
> 
> ![image](https://user-images.githubusercontent.com/4555004/165494936-41f74db4-5212-4daf-b6f5-25638cd5b40b.png)

Danke, konnte es mit der Rubicon reproduzieren -> Fehlersuche...

**Comment by schoos76** [comment]
Ich sag hier mal Danke fuers anschauen und fixen.

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
