### ISSUE TITLE
SUB - Ordnersystem

### ISSUE THREAD

**Issue by Sirpoco** [Stephan-S/FS22_AutoDrive#491]
Hallo,
wir spielen auf einem Deli - Multiserver, dort sind wir mit mehreren Spielern Online. 

Da es dort jetzt durch viele Ordner  (z.B. durch Automatisierungen und/oder eigene Ordner der Spieler), die Liste sehr lang und unübersichtlich wird, nun die Frage: 

" Gibt es die Möglichkeit (z.B. Windows/Linux) in Autodrive das man Unterordner einrichten kann?" 

So hätte man die Möglichkeit z.B. 👍 

01 Spieler 

     -> 01 Fabrikation
               -> z.B. Gärtnerei
               usw.
     -> 02 Kühe Automatisierung
     -> usw.
02 Spieler 2
    -> usw.
03 Spieler 3
   -> usw.

einzurichten. Es wäre schön, wenn man so etwas realisieren könnte.

Danke an Euch für die geleistete Arbeit.

Grüße Andy (Sirpoco)

**Comment by Iwan1803** [comment]
siehe #400 und #215
Da doppelt -> geschlossen!
