### ISSUE TITLE
[Feature] Grubber Sähmaschine usw nach Hause Fahren von Curseplay übergeben

### ISSUE THREAD

**Issue by Selyria** [Stephan-S/FS22_AutoDrive#494]
Es wäre schön wenn AutoDrive die Geräte nach Hause Fahren könnte sobald dieser fertig ist sonst steht er auf dem Feld rum wenn Curseplay fertig ist  und Maschinen können zusammenhauen.

 z.b. nach dem sähen Striegel ich gleich da die Sämaschine schneller ist als der Striegel geht das ja nur am ende des Cruses bleibt die Sämaschine stehen und der Striegel knallt hinten rein.

Z.b. der Grubber ist am ende seines Weges das dieser dann von Curseplay an AutoDrive übergeben wird und diesen dann parkt oder auf den Hof fährt. das gleiche sollte auch für Sämaschinen usw gelten.

Hatte bei Curseplay angefragt die sagten mir sie hätten eine Schnittstelle an die AutoDrive anknüpfen könnte

**Comment by rohne83** [comment]
Also Parkfunktion am CP-Kursende wie es sie im 19er schonmal gab (musste damals noch in CP selbst eingestellt werden)

**Comment by Iwan1803** [comment]
Ja, es gibt Schnittstellen zwischen AD und CP, aber woher soll AD wissen, wenn CP fertig ist und das nun geparkt werden soll?
Diese Info müsste (wie in LS19) von CP aus an AD gemeldet/übergeben werden.

**Comment by Axel32019** [comment]
Die Schnittstelle ist CP-seitig schon vorhanden, Umsetzung in AD steht noch aus....
@Iwan1803 CP hat ein Event für "Fertig" in der Schnittstelle.

**Comment by Selyria** [comment]
ah okay dann freue ich mich wenn es soweit ist und warte ab

**Comment by timmi4026** [comment]
@Axel32019 
Moin, hab gerade gesehen, du hast die Parkfunktion nach beenden der Arbeit eingebaut. Hab mal getestet, Stand heute, 8 Uhr.
Mulcher beendet Arbeit, klappt zusammen aber fährt nicht zum Parkplatz. AD hat das CP Symbol aktiv. 
Sämaschine Citan beendet Arbeit, hebt aus, klappt aber nicht zusammen und Motor wird abgeschaltet. Hier auch im Ad das CP Symbol aktiv.
Muss ich da irgendwo was einstellen? Beide Versuche hatten Anbaugeräte aktiv, und Parkplatz zugewiesen. 

Gruß Timmi

**Comment by Axel32019** [comment]
@timmi4026 Moin, Da müsste es lua Fehler im Server-log geben mit "onCpFinished". Hab einen fix commited, bitte aktualisieren.

**Comment by timmi4026** [comment]
> @timmi4026 Moin, Da müsste es lua Fehler im Server-log geben mit "onCpFinished". Hab einen fix commited, bitte aktualisieren.

Das hatte ich im SP getestet, war nicht auf Server, aber jetzt klappt es im SP. Ich teste es gleich auf dem Server.

**Comment by 60erjonny** [comment]
...auch ich habe es getestet ( SP ) und es funktioniert beim grubbern, düngen und ansähen wunderbar...gute Arbeit...:-)

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
