### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by Albatrozs112** [Stephan-S/FS22_AutoDrive#495]
Latest Release: 2.0.0.5 AutoDrive i use 
I use this mode FS22_AutoloaderStockPackj and then starter this.
FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: bad argument #1 to 'max' (number expected, got nil
All weekend all worked and now error
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8501457/log.txt)

**Comment by amayfield** [comment]
I get the following error after updating FS22 to version 1.3.1.0

2022-04-20 05:16 Error: Running LUA method 'update'.
FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: bad argument #1 to 'max' (number expected, got nil)

**Comment by RolfN9597** [comment]
Same here.

**Comment by Iwan1803** [comment]
Like written in the Release Notes, you need a version 1.6 or higher of the AutoLoad mod.
In the log i can see: (Version: 1.5.0.0) FS22_aPalletAutoLoader
Please update to the latest version to get it work: https://forbidden-mods.de/filebase/file/27909-ls22-paletten-autoloader-spezialisierung/

**Comment by Albatrozs112** [comment]
![Bez nosaukuma](https://user-images.githubusercontent.com/79331061/165137934-38e43dbd-c1a9-4c6a-8c06-ad5e589d73a4.png)
In game version

> Like written in the Release Notes, you need a version 1.6 or higher of the AutoLoad mod. In the log i can see: (Version: 1.5.0.0) FS22_aPalletAutoLoader Please update to the latest version to get it work: https://forbidden-mods.de/filebase/file/27909-ls22-paletten-autoloader-spezialisierung/

**Comment by Iwan1803** [comment]
Achimobil has submitted the latest version, but unfortunately it takes a long time for updates to appear in the ingame modhub.
Either wait for it and in the meantime you can't use AL with AD or update the mod manually.

**Comment by Iwan1803** [comment]
@Albatrozs112 please update and try again.
If we don't get a feedback whithin some day, we will close the issue.

**Comment by amayfield** [comment]
My issues appear to have been resolved.  Thank you everyone!

**Comment by Albatrozs112** [comment]
> @Albatrozs112 please update and try again. If we don't get a feedback whithin some day, we will close the issue.

yes you can close all work

**Comment by Iwan1803** [comment]
Great, thanks for the feedback :)
