### ISSUE TITLE
Aktives Abfahren vom Drescher funktioniert nicht immer.

### ISSUE THREAD

**Issue by WernerWusel** [Stephan-S/FS22_AutoDrive#496]
Hallo AD-Team.
Funktioniert nicht immer soll bedeuten, dass das aktive Abfahren vom Drescher nur funktioniert, wenn unter dem Rohr keine Frucht vorhanden ist durch die der Abfahrer fahren muss. Ist Frucht vorhanden, ist es nicht möglich, das aktive Abfahren zu aktivieren. Ist keine Frucht vorhanden, läuft alles ganz einfach und korrekt. Das aktive Abfahren ist bei großen Feldern sehr wichtig. Ist der Drescher voll und unter dem Rohr ist Frucht, wird das Abladen nur stehend durchgeführt.
Das Ganze ist unabhängig von der Frucht auf dem Feld und von den eingesetzten Gerätschaften.

**Comment by TobiHH78** [comment]
Funktioniert wie beabsichtigt...nennt sich Fruchtumfahrung.

**Comment by ct177mak** [comment]
vllt Fruchtumfahrung deaktvieren ;)

**Comment by WernerWusel** [comment]
Man kann davon ausgehen, wenn ich einen Problembericht schreibe, das alle Einstellungen in AD und CP für aktives Abfahren eingestellt sind.
Folgende Einstellungen sind aktiviert/deaktiviert:
AD - (Abfahrer) Fruchtumfahrung Nein
AD - (Drescher) Aktives Abfahren Ja
CP - (Drescher) Fruchtumfahrung deaktiviert
CP - Beim entladen stehen bleiben deaktiviert
Im Normalfall brettert ja der Abfahrer auch durch die Frucht durch, z.B. wenn er den Hänger leer macht. Eben nur beim Abtanken funktioniert das nicht.

**Comment by ct177mak** [comment]
Problembericht ?? Sieht anders aus ,das nur mal zur Info ,Mods oder Vanilla werden nicht genannt ,Map unknown usw. Wir sind auch nur normale User hier die versuchen zu helfen ;) Log.txt fehlt womit die DEVs auch was anfangen können.

**Comment by rohne83** [comment]
Fruchtumfahrung bei CP-Erntern bedeutet, dass der Drescher sich eine Tasche zum Abladen drischt wenn die Rohrseite nicht frei ist oder generell auch auf der ersten Vorgewendebahn. Bei AD-Abfahrern bezieht sich die Fruchtumfahrung mW doch soweit erstmal auch nur darauf ob der direkte Weg zum Ernter berechnet werden soll, oder um die Frucht herum. Weiß gerade nicht wie weit die AD-CP-Schnittstelle erweitert wurde, ob CP-Drescher die AD-Abfahrer überhaupt rufen wenn das Rohr über der Frucht ist (siehst du ja im AD-Hud ob er überhaupt versucht einen Weg zu berechnen oder einfach weiter vor sich hin wartet - wäre eine ziemlich wichtige Information für dein Problem).
Generell ists natürlich auch völlig unsinnig auf der einen Seite zwar aktive Abfahrer haben zu wollen, andererseits dann aber so zu arbeiten, dass das Rohr dauernd über der Frucht ist. Nicht umsonst kannst du beim CP-Kursgenerator die Feldmitte auf spiralförmig oder Beete einstellen, womit du genau solche Probleme von vornherein vermeiden kannst.

**Comment by WernerWusel** [comment]
Unsinnig ist es, in den Einstellungen mit dem Punkt "Fruchtzerstörung AUS" die in CP und AD vorhandenen Einstellung zu benutzen. Egal was man mit der Fruchtumfahrung macht, durch die globale Einstellung "Fruchtzerstörung" sind die anderen Einstellungen (speziell die Fruchtumfahrung) irrelevant, weil auf dem Feld nichts passieren kann. Daher ist es nach wie vor ein Bug, wenn der Abfahrer nicht unter das Rohr fährt zum aktiven Abtanken. Er nimmt ja sonst auch keine Rücksicht auf die Frucht. Und warum soll man etwas anderes in AD einstellen, nur weil AD nicht das macht was ich eingestellt habe ?

**Comment by rohne83** [comment]
KI-Helfer inkl AD und CP zerstören generell nie die Frucht, egal was global bei der Fruchtzerstörung eingestellt ist. Das ist im Giants-Code schon so verankert. Leider, muss man sagen - weil dadurch zB CP auch keine Fahrgassen machen kann.
Die Fruchtumfahrung von AD und CP hat daher nicht das geringste mit der globalen Fruchtzerstörung zu tun. Hier gehts eher um mehr Realismus, um den nun wirklich nicht zu ertragenden Anblick von quer durchs Getreide fahrenden Fahrzeugen zu verhindern.
Wird denn dein Abfahrer überhaupt gerufen?

**Comment by WernerWusel** [comment]
Alles ganz normal. Der Abfahrer bekommt den Ruf bei (eingestellten) 40% und fährt los. Zwischendurch immer mal wieder eine Routenberechnung. Wenn Frucht unter dem Rohr ist, bleibt der Abfahrer bis 90% hinter dem Drescher. Solange hat der Drescher auch das Rohr ausgeklappt. Danach muss der Abfahrer Abstand zum Drescher gewinnen und fährt Rückwärts (warum auch immer) !! Bei ca. 94% klappt der Drescher das Rohr wieder ein und bei 99-100% bleibt er stehen und klappt das Rohr wieder raus. Dann kommt der Abfahrer durch die Frucht zum Drescher und tankt ab.

**Comment by Iwan1803** [comment]
Der Abfahrer soll beim Abtanken nicht durch die Frucht fahren und da dies vermehrt gefordert worden ist, haben wir es auch so umgesetzt. CP "erntet" sich daher auch zum Abtanken eine Parkbucht, damit das Rohr eben nicht in der Frucht ist.
Bzgl. LS22-Fruchtzerstörung und AD-/CP-Fruchtumfahrung wurde ja schon alles gesagt.
Ist nicht böse gemeint, aber wir werden jetzt nicht den Code wieder ändern und anpassen, damit es einzelnen wieder gefällt.
Vielleicht solltest du deinen Drescher einfach so fahren, das das Rohr eben nicht in der Frucht ist.

**Comment by Axel32019** [comment]
Kann keinen Fehler erkennen, alles funktioniert wie beabsichtigt.
