### ISSUE TITLE
Drescher Abfahrer hält nicht unterm Rohr

### ISSUE THREAD

**Issue by Foss-ops** [Stephan-S/FS22_AutoDrive#497]
Hallo
AD 2.0.0.5 
Karte Niedersachsen22
Drescher Lexion8900 von Giants mit Draeper45ft von Giants.
Abfahrer Claas 870 mit Rudoilf 18.5m³ bzw Fliegl ASW (silber mit Schiebeschild Entladung) von Giants.
Log ist Clean.

Drescher fahr ich selber, Feld Nr eingestellt bei beiden Fhrz. Aktives Abladen: Nein. Drescher fast voll, ich halt an, Motor läuft, Rohr fährt aus. Ich warte im Fahrzeug.

Abfahrer kommt, Spur ist mittig unter dem Rohr (0.75m), er wird langsamer aber hält ca 5m, nachdem er das Rohr verpasst hat, an.
Merkt seinen Fehler, macht 2x 180° und kommt wieder, und wieder zu spät angehalten. Usw.

EDIT: Achja, Feldgeschwindigkeit vom Abfahrer hab ich runter auf 25km/h, Bremskraft in VCA nachträglich auf 200%

Jemand eine Idee, wonach ich schauen könnte? Häcksler folgen Einstellung 1.75m ist es ja wohl nicht, oder? Geht ja um das Drescher Rohr.

EDIT2: Mein Fahrmuster im Drescher ist im Uhrzeigersinn Spiralförmig mit 90° Turn am Ende der Frucht. also wie AIVE im LS19

Hier zeig ich das Problem. https://youtu.be/KJW3YUjdiwc 
Habe den Verdacht, das es mit der Neigung des Feldes zu tun hat.

**Comment by Goofy78** [comment]
Aktives Abfahren im Drescher ausgestellt?

**Comment by Foss-ops** [comment]
> Aktives Abfahren im Drescher ausgestellt?

Ja @Goofy78, hab ich im Eingangspost auch erwähnt. Übersieht man leicht.
Hab auch zwecks Troubleshooting mal mit angeschaltetem aktiven Abladen probiert, waar aber nicht hilfreich.

grüße

**Comment by knalliger0z** [comment]
Hab das gleiche Problem wenn der Drescher höher am Hang steht als der abfahrer dann fährt er immer vorbei und bleibt erst nach dem Drescher stehen.

**Comment by Foss-ops** [comment]
> Hab das gleiche Problem wenn der Drescher höher am Hang steht als der abfahrer dann fährt er immer vorbei und bleibt erst nach dem Drescher stehen.

Ich hatte eher das Gefühl, das der Abfahrer bergauf besser klarkommt, auch wenn er um Haaresbreite grade eben noch vor der Heckklappe beladen wird, bei dem kleinen Rudolf Anhänger, vielleicht probier ich mal mit dem längsten Hänger den ich finden kann.

**Comment by Goofy78** [comment]
Ich hab es mal getestet. Ich hab alles auf Standard und was soll ich sagen, er macht alles so wie es soll.

**Comment by Foss-ops** [comment]
> Ich hab es mal getestet. Ich hab alles auf Standard und was soll ich sagen, er macht alles so wie es soll.

Dann könnte es an der Karte liegen, oder vielleicht an dem 300m langem Entladerohr des Lexion?
Standard Settings hab ich ja auch. Vielleicht teste ich mal auf der nf marsch. Wo hast du getestet, wenn ich fragen darf?

**Comment by Goofy78** [comment]
Getestet auf der NDS22 mit dem Geräten die du geschrieben hast.

**Comment by Foss-ops** [comment]
> Getestet auf der NDS22 mit dem Geräten die du geschrieben hast.

Danke das du das Szenario nachgestellt hast,
Ich habe jetzt auf den Fliegl ASW Anhänger umgestellt, habe verifiziert das ich Standard Settings habe, und kann erstmal wieder AD Abtanken lassen, wenn auch nur knapp vor der Heckklappe.

**Comment by Iwan1803** [comment]
Schön, das es geklärt und dann mache ich auf Wunsch hier mal zu 😉
