### ISSUE TITLE
Reversing from Combine

### ISSUE THREAD

**Issue by Nebular64** [Stephan-S/FS22_AutoDrive#498]
Map: Any
AD Ver: 2.0.0.5
Combine: Any
Unloader Vehicle: Any trailer

When a combine reaches 80% the unloader follows the combine as expected.  However, once the unloader reaches the combine and the combine starts to unload (while still moving), the unloader will immediately start reversing from the combine for no apparent reason and waits until the combine reaches 100% and stops.  Once the combine has stopped, the unloader will approach again and start unloading the combine.

Since I can recreate this on any map with any vehicle combination, I assume this is a "function" of AD.  Can this be deactivated in any way so the unloader stops reversing once it reaches the combine?

**Comment by Axel32019** [comment]
Please attach a screenshot when the unloader starts reversing.
There are several reasons for reversing.

**Comment by Nebular64** [comment]
Sorry for my delay.  It doesn't happen all of the time, but I will provide the info once captured.  Thanks!

**Comment by Axel32019** [comment]
In case please reopen, for now closed.

**Comment by coatsy35** [comment]
This is also still happening
