### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by TerryFarming** [Stephan-S/FS22_AutoDrive#499]
Ich habe das Update auf Version 2.0.0.5 gemacht und jetzt wird angezeigt, dass es nicht installiert ist.

**Comment by 60erjonny** [comment]
...und wie genau, hast du das "Update" gemacht...?

**Comment by TerryFarming** [comment]
Sorry für die späte Antwort:
Zu erst habe ich die neuste Version (2.0.0.5) heruntergeladen und in den Modordner eingefügt. Danach öffnete ich das Spiel und es wurde mir auch im Modstore als Download angezeigt, aber nicht, wenn ich im Karrieremodus ein Spiel öffnen wollte.

**Comment by 60erjonny** [comment]
Hallo
...dumme Gegenfrage, hast du die alte Version gelöscht...?

**Comment by TerryFarming** [comment]
Leider ja, da die neue Version nicht erkannt wurde, aber ich hab den LS22 nochmals neu installiert jedoch vergebens. Was kann ich tun?

**Comment by TerryFarming** [comment]
Ich hab mir jetzt Autodrive neu installiert und es funktioniert auf einmal. Danke für deinen Support!!!
