### ISSUE TITLE
Problème lors de déplacement de points sur ponts

### ISSUE THREAD

**Issue by Pcab59** [Stephan-S/FS22_AutoDrive#50]
![AD_Prob1](https://user-images.githubusercontent.com/91502633/146945708-77d9b9ba-d6f6-4586-a9a4-ff676dabc959.jpg)
Lors du déplacement de points sur un pont et certaines routes, le point passe à travers la route. le problème avait existé sur la version FS19.
Problème détecté sur Haut beyleron Map sur le pont proche du shop.
Cordialement.

**Comment by Iwan1803** [comment]
La solution existait déjà dans LS19 :
- saisir le waypoint avec le bouton droit de la souris
- appuyer sur la touche shift gauche et la maintenir enfoncée
- déplacer maintenant le waypoint
- lorsqu'il est au bon endroit, relâcher les deux touches

J'espère que le traducteur a fait du bon travail 😀
