### ISSUE TITLE
[enhancement][request] Allow honking while AD is active

### ISSUE THREAD

**Issue by Plopsi** [Stephan-S/FS22_AutoDrive#500]
Just because it's funny and a little sad that you currently can't honk while AD is driving, to greet (or annoy) other farmingfellows. ;)

Not sure if it would be possible at all.

- Plopsi

**Comment by Selyria** [comment]
Spanngurte anlegen wäre auch nett auf Dedi Servern lege ich die lieber selber an da die autoloader diese zu früh anlegen und die Paletten in der Luft dann gehalten werden dann müsste man nicht immer AutoDrive aus spanngurte anlegen und wieder einschalten

**Comment by Iwan1803** [comment]
@Selyria und was haben die Spanngurte mit dem Hupen zu tun? 🙄

@Plopsi there is no way to implement this if a helper is active.
