### ISSUE TITLE
[suggestion] Highlight nodes with potential problems

### ISSUE THREAD

**Issue by billw2012** [Stephan-S/FS22_AutoDrive#501]
Something that would immediately make creating routes easier would be better visual indication of problems.
Problems I see often:
- Nodes with only a single one way connection, these are never valid so could always be highlighted
- A node with any angles greater than whatever it is that the route finder accepts. I have noticed that if a route has a high angle the route finder won't route past it. This high angle can happen frequently due to auto connect selecting a node in front of the current position (this could also be fixed: restrict the current node selection to those behind the vehicle).

Increasing the width of the lines and the size of the direction indicator would also help a lot (maybe 3 times thicker?). They are difficult to see currently unless zoomed right in.

**Comment by Iwan1803** [comment]
You know, that you can debug the AD network ingame and that there are allready some options for it?
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Release-Notes-for-AutoDrive-english#bugfixes-and-improvements

**Comment by billw2012** [comment]
Thanks, but this link doesn't help? I found the related issue #36 and translated it, but no where can I see where it says how to use it, I don't see any shortcut key, or anything in the wiki.

**Comment by Axel32019** [comment]
In german, but visual should help as well: https://www.youtube.com/watch?v=AjeZ-scB0Vk

**Comment by billw2012** [comment]
Thanks, this isn't something I would use, it looks more like its intended for creating an initial network, whereas I want something that will show errors live while I am adding new routes in an ad-hoc manner. I would imagine it is trivial to know if a node has only one connected link, all I want is for that to be indicated somehow, preferably at all times. e.g. just make the node slightly bigger, or make it a cube instead of a sphere, or add an extra vertical line to it or something.

**Comment by Axel32019** [comment]
Not only for initial network. It is not trivial to find issues in the network! To check for errors take a huge amount of computing time depending on the number of waypoints in the network, so a live investigation will slow down the editing and might make it not usablable anymore!
So for the time being there will be no change.

**Comment by billw2012** [comment]
I don't understand, how is it expensive to determine if a node has one link? You already highlight nodes with no links with a little X above them. All I want is a little 1 above ones that only have 1 (or something like that). I see `point.out` and `point.incoming` which you use to determine nodes with no connections, can you not just check `point.out == 1` (or whatever, I don't know exactly what these variables mean, just guessing)?

For that matter it would also be useful to highlight junctions (more than  2 links) in the same manner, as its often hard to see them as well!

**Comment by billw2012** [comment]
![image](https://user-images.githubusercontent.com/1453936/165379243-8c2cdc5b-664e-4a45-bfe9-3bc19f65114a.png)

```
--just a quick way to highlight single (forgotten) points with no connections
if (#point.out == 0) and (#point.incoming == 0) and not table.contains(outPointsSeen, point.id) and point.colors == nil then
    y = getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, x, 1, z) + 0.5
    DrawingManager:addCrossTask(x, y, z)
end

if AutoDrive.isInExtendedEditorMode() then
    if (#point.incoming == 1 and (#point.out == nil or #point.out == 0) or (#point.incoming == nil or #point.incoming == 0) and #point.out == 1) then
        y = getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, x, 1, z) + 0.25
        DrawingManager:addSphereTask(x, y, z, 2, 1, 0, 1, 1)
    end

    if (#point.out > 1 or #point.incoming > 1) then
        y = getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, x, 1, z) + 0.25
        DrawingManager:addSphereTask(x, y, z, 2, 0, 1, 1, 1)
    end
end
```

This is what I mean.

**Comment by Axel32019** [comment]
@billw2012 Seems you are able to program lua? :-;
You may check the cases in ADGraphManager:createDebugMarkers...

**Comment by Iwan1803** [comment]
No further feedback -> closed!
