### ISSUE TITLE
Strecke

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#503]
Hallo
Was mache ich falsch, habe Strecke eingefahren aber nur auf den Bild und es wird kein Verbindung angezeigt
![GGG](https://user-images.githubusercontent.com/47453761/164295249-83f29d8f-578e-4fb3-a00b-e2711cf728ea.png)

**Comment by 60erjonny** [comment]
...da simmt was nicht, ganz rechts, sehen ich 2 grüne Strecken in beiden Richtungen...??? Ist die obere Strecke nicht doppelt, sieht man leider nicht so genau...

**Comment by rohne83** [comment]
nicht nur da. Zwischen allen Punkten sind da doppelte Linien, die aber alle mit unterschiedlichen Punkten verbunden sind. Am besten den ganzen Abschnitt erstmal nochmal komplett neu einfahren.
