### ISSUE TITLE
Fold implements feature folds combine when its not empty

### ISSUE THREAD

**Issue by billw2012** [Stephan-S/FS22_AutoDrive#506]
It results in what is shown in the image, I can't unfold it again manually because fold and unfold are both blocked if the combine isn't empty.
![image](https://user-images.githubusercontent.com/1453936/165317938-64a14f38-b8bd-451c-9905-bb882a21e4f6.png)

I can actually unload it manually, although the auto drive unload combine doesn't work because the auger position is wrong.
![image](https://user-images.githubusercontent.com/1453936/165319657-4c3d3014-d98e-45c2-8a8a-d7b51331d2f1.png)
Sadly even after this I can't unfold it as the pipe is stuck extended, which blocks fold AND unfold. Reset to shop works, and I manged to unload it so nothing was lost except time!

**Comment by Axel32019** [comment]
Not reproducible: Even if harvester is folded, I am able to unfold manual.

**Comment by billw2012** [comment]
The bug is that it folded it while not empty, which isn't meant to be possible.

**Comment by Axel32019** [comment]
@billw2012 This should no longer happen in dev version with fix for #477
You may give it a try...

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
