### ISSUE TITLE
Das neue AD-Fahren reduziert mein Spielspass

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#507]
Hallo,

ich weiß, vielen mag es nerven, aber ich habe da eine Problem mit dem "neuen abfahren des Streckennetz"

Das "neue" AD -Fahren und Streckennetz.... Ich fahre eine Original Map und es ist an vielen Ecken Eng und/oder Deko steht rum (Laternen und so was) und egal was ich mache, es passt einfach nicht. Euer neues Verfahren wie AD die Strecke folgt ist einfach nur noch sehr kompliziert und ist kaum einstellbar auf Maps mit engen Straßen und Kreuzungen. Hier ist das Argument "Man kann es keinem Recht machen" nicht passend da es einfach ungenauer geworden ist bzw sehr schwer die Strecke Richtig eingefahren werden kann.

Es nimmt die Lust den Mod zu nutzen weil man "nur" noch dran sitzt und versuchen möchte das Streckennetz zu Richten. Meist ohne Erfolg da man das Gefühl bekommt das AD auch die kleinen Korrekturen einfach "überfährt" bzw ignoriert.

**Comment by 60erjonny** [comment]
...nur so viel, bedenke auch das Mod-Fahrzeuge, auch nicht immer mit AD zurecht kommen...aber was meinst du mit den "neuen AD-Fahren"...so viel hat sich ja nicht von LS19-Version zu LS22 Version geändert...?

**Comment by BigBlackBahamut** [comment]
AD hat das Verfolgen der Strecke verändert, damit fahren Sie "geschmeidiger" durch die Kurve. Aber leider fahren Fahrzeuge (und das sind keine Modfahrzeuge) ziemlich fern der eigentlichen Strecke die eingefahren ist. 

Ich verstehe das man versuchen möchte das es geschmeidiger in den Kurven ist, das Traktoren dann aber von der "eingefahrende" Strecke rausgetragen werden und somit halt mit Objekten zusammenstoßen sollte aber auch bedacht werden.

Wie gesagt, AD ist meine MOD Nummer 1, aber so bringt mir das gerade nicht viel. Schade eigentlich.

**Comment by 60erjonny** [comment]
...Kurfengeschwindichkeit, generell die Geschwindigkeiten schon reduziert...? Alles zum richtigen einstellen schon versucht...???
 Ich kann das so nicht bestätigen...gut immer geht es auch bei mir auch nicht gut, aber das liegt an der Karte, den Fahrzeug und den KI-Verkehr ( ich spiele ohne ), nicht an AD...

**Comment by BigBlackBahamut** [comment]
Den KI habe ich auch deaktiviert, Kollisionserkennung ist auch aus, bei den engen Straßen ein muss.
Ich habe schon ziemlich weit die Geschwindigkeiten reduziert, werde dieses aber noch einmal reduzieren. 
:-)

**Comment by Iwan1803** [comment]
"Man kann es _keinem_ Recht machen" ist falsch, denn es muss heißen "man kann es _nicht allen_ Recht machen".
Ja, es wurde etwas bzgl. dem Fahren und Kurvenverhalten geändert und uns ist bewusst, das man dadurch auch die ein oder andere Stelle im Streckennetz mal anpassen muss. Immerhin darf man nicht vergessen, das hier Skripte am Werk sind und keine KI die Fahrzeuge lenkt.
Der Großteil meines Streckennetzes für die Haut-Beyleron besteht noch aus der ersten automatischen Generierung. Diese habe ich mir direkt nach dem Release von AD generieren lassen. Natürlich muss ich auch mal Streckenteile anpassen, aber das passiert doch eher selten. Mal die Strecke in einer Kurve weiter nach außen legen, mal eine Kreuzung oder Abbiegung anpassen, aber das war es dann auch schon.
Wenn du allerdings so oft Anpassungen vornehmen musst, das dir "Spielspass" verloren geht, dann würde ich mal die Qualität deines Netzes anzweifeln. Die Schuld immer bei AD zu suchen, finde ich da eher "suboptimal", denn auch Giants ändert gerne mal was im Hintergrund, was sie aber nicht immer öffentlich preisgeben.
Btw. die Giants-Straßen haben eine Fahrspurbreite von ~3,6m, ein Claas Lexion 8900 TerraTrac eine Fahrbreite von 3,5m und nun versuch mal die AD-Routen so aufzuzeichnen, das sich 2 entgegenkommende Fahrzeuge nicht rammen oder voreinander stehen bleiben... na, merkste was?

Da das ganze ja kein wirklicher Supportfall ist, mache ich hier mal zu.

**Comment by BigBlackBahamut** [comment]
Ich bin der letzte der mit Kritik nicht umgehen kann, aber die "Schuld" (wie Du es so gerne nennst) weiter zu schieben auf meinem angeblichen "schlechten Netz" ist traurig. Das habe ich jetzt so wirklich nicht erwartet.... 

Es ist ein neues Streckennetz von der Übernahme von Giants. Also habe ich daher in diesem neuen Profil noch nicht so viel verändert wie in einem anderen Profil wo, und das möchte ich noch gerne mitteilen auf eine Map ist wo die Straßen bisschen breiter sind. Und siehe da, da klappt es.

Außerdem habe ich nur versucht mitzuteilen das es auf Karten mit engen Strecken nun doch ziemlich kompliziert ist eine schönes Streckennetz zu erbauen.

Auch möchte ich betonen das nicht jeder von uns so viel Zeit an AD verbringt wie die Modder und deren Tester und daher einfach nicht die Erfahrung hat. 

Aber nun gut. Ich möchte mich da auch nicht weiter streiten. Ich lasse es so stehen und bin mal raus hier.

Lieben Gruß
BigBahamut

**Comment by Iwan1803** [comment]
Es war nicht meine Intention, dich oder dein Streckennetz anzugreifen oder zu beschuldigen. Falls das so rüberkam, dann entschuldige ich mich dafür. Das geschriebene Wort lässt halt gerne mal sehr viel Freiraum für Interpretationen... 🙄
Straßen (und besonders enge) sind und werden immer ein Problem sein. Es sind nun mal keine Schienen, wo per Standard definierte Fahrzeuge immer identisch drauf fahren.
Wo Treckermodell A noch problemlos rumfahren kann, kann Treckermodell B oder ein Drescher schon hängenbleiben - das ist einfach mal so und da wird AD auch nichts dran ändern können. Das liegt weder an AD noch an dir sondern einfach an der Natur der Dinge: sie sind halt einfach mal nicht 100% identisch und verhalten sich eben auch so.
