### ISSUE TITLE
unable to save routes after and before patch 1.4 dedicated servers 

### ISSUE THREAD

**Issue by DavidSpeicher** [Stephan-S/FS22_AutoDrive#508]
as title says 
unable to save routes after and before patch 1.4 dedicated servers

**Comment by DavidSpeicher** [comment]
version 2.0.05 is used 

i did not notice any errors in logs though, how ever i press the save button multiple times and nothing happens.

**Comment by Axel32019** [comment]
since FS19 routes manager is deactivated on dedi servers as is unpredictable, may cause heavy data loss, work/don'n work etc.
user might activate with experimental switch on risk!

**Comment by DavidSpeicher** [comment]
FS22 not FS19

**Comment by Iwan1803** [comment]
On a dedi server the save button on the AD HUD is deactivated. You can see it, but if you click on it nothing will happen.
Like in SP the route will be automatically saved if the server saves the game.
