### ISSUE TITLE
Vorschlag / Suggestion: automatisches Schließen aller Ordner nach Zielauswahl

### ISSUE THREAD

**Issue by ZGuderian** [Stephan-S/FS22_AutoDrive#509]
Zur besseren Übersicht bei der Zielauswahl die Ordner automatisch schließen wenn die Zielauswahl geschlossen wird. Oder eine Checkbox in der man diese Option auswählen kann.

To provide a better overview at the target selection closing of the folders by default when closing the tab or a checkbox to select this as a option

**Comment by Iwan1803** [comment]
In der offenen Zielliste gibt es oben neben der Lupe einen Button, um alle Ordner zu schließen:
![image](https://user-images.githubusercontent.com/47528836/165890598-aaf8522b-7f5c-4e12-827e-5f03d01c0523.png)
Die beiden Button sind auch immer sichtbar. Reicht das nicht als Option schon aus?

**Comment by ZGuderian** [comment]
Im Grunde schon, würde sich die Zielliste nicht unmittelbar nach "Klick" schließen. Im Ergebnis hat Du dann die hälfte aller Ordner offen bis Du den Button drückst. Und Du hast dann beim nächsten öffnen der Zielliste trotzdem den letzten verwendeten Ordner wieder offen.
Außerderdem: Es lebe die bequemlichkeit  :-)

**Comment by Iwan1803** [comment]
Und aufgrund deiner "Bequemlichkeit", sollen wir nun Programmieraufwand betreiben, nur weil dir diese eine Mausklick zu viel ist?

**Comment by ZGuderian** [comment]
...nicht aufgrund meiner Bequemlichkeit sondern weil Ihr Spass am programmieren habt. 
Außerdem ist es nur ein Vorschlag, der ja auch abgeleht werden kann.

**Comment by Iwan1803** [comment]
Am Ende ist es eine Aufwand-/Nutzenfrage: wie lange müsste jemand programmieren, um es umzusetzen und macht es wirklich Sinn, diese (private) Zeit dafür zu investieren?
Ich sage nicht, das der Vorschlag Müll oder so ist, aber es gibt ja quasi schon so eine Funktion, nur das du sie aus Bequemlichkeit gerne automatisiert hättest. Aus Spaß am Programmieren werden wir dennoch nicht unsere freie Zeit opfern, wenn man in dieser auch was anderes machen könnte, was deutlich mehr Nutzen bringt.

**Comment by Axel32019** [comment]
@ZGuderian Ich verstehe es noch nicht richtig! Wie ich das interpretiere:
In der Zielauswahl wird ein beliebiger Ordner geöffnet.
Wird in diesem ein Ziel ausgewählt, soll dieser Ordner sich wieder schließen?
Sollen alle Ordner eingeklappt werden wenn ein Ziel, egal aus welchem Ordner, ausgewählt wird?

**Comment by billw2012** [comment]
I think this would be quite nice: I have 15 folders, and >100 waypoints (and only 3 fields so far, I use 6 for each one), and I don't find it helpful having the open folders remembered, I would prefer if it is always a collapsed list when I open it, making the navigation consistent each time, instead of sometimes having to close folders, sometimes not.

**Comment by Axel32019** [comment]
It is always a personal perspective: some want it to close always, others to remember the opened.
For now no change -> closed
