### ISSUE TITLE
Hud.lua bug line 802: attempt to perform arithmetic on field Y

### ISSUE THREAD

**Issue by Markus33-ITA** [Stephan-S/FS22_AutoDrive#51]
I found a bug.
In a nutshell I was creating the entry path into the farm. I clicked the middle mouse button and that error appeared.
I still have version 1.1. I have too many active downloads and the connection is not good. For tomorrow I should have the 1.2 and I'll do the test again with a new game.
[https://i.imgur.com/Oab0kdQ.png](https://i.imgur.com/Oab0kdQ.png)

**Comment by Axel32019** [comment]
Hello @Markus33-ITA , Is there something mixed? Looks like you included something from your PR :-)
The issue you observed looks like #22 -> fixed in next Release, therefor closed here.
