### ISSUE TITLE
AttacherJointType "semitrailerCar" funktioniert nicht rückwärts

### ISSUE THREAD

**Issue by cantonsilver** [Stephan-S/FS22_AutoDrive#510]
Liebe Entwickler. Ich habe festgestellt, dass Autodrive das Rückwärtsfahren von Goosenecktrailern, die den AttacherJointType "semitrailerCar" haben, nicht beherrscht. Ein Korrigieren der Route beim Rückwärtsfahren wird nicht gemacht.
Als Modell betrifft das den Stock-Trailer für Pferdetransport "Kingston Trailers Belvedere", der auf das Fifth Wheel oder den Gooseneckpinöppel von PickUps angekoppelt wir, sowie einige Mod-Gooseneck-Trailer. Ich habe den "Belvedere" mal geändert auf den AttacherJointType "semitrailer" und da funktioniert ein Rangieren problemlos.

**Comment by Iwan1803** [comment]
Gleiches scheint auch für das Claas Saddletrack-Pack zu gelten, da er mit den Gülle-Anhänger auch diese beim Rückwärtsfahren ignoriert.

**Comment by Axel32019** [comment]
Da sind wohl einige AttacherJointTypen hinzugekommen -> TODO

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
