### ISSUE TITLE
Probleme beim Drescher abfahren 

### ISSUE THREAD

**Issue by schoos76** [Stephan-S/FS22_AutoDrive#511]
Ich benutze CP und Autodrive um Drescher abzufahren und dabei ist mir jetzt mehrmals ein Problem aufgefallen:

1. Drescher ist bei 95% voll und steht, Rohr ist ausgeschwenkt. CP Einstellungen sind "Beet" mit 8 Bahnen
2. Der Abfahrer kommt vom Entleeren zurueck, faehrt dann vom Feldrand aufs Feld naehert sich dem Drescher, aber statt unter das Rohr des stehenden Dreschers zu fahren wird ein nierenfoermiger Kurs knapp vorm Rohr des Dreschers gewaehlt und der Abfahrer kommt auch nach mehreren Iterationen nicht an. 

![20220501084812_1](https://user-images.githubusercontent.com/4555004/166128086-59341140-86ef-423f-a0e0-31991b8556fb.jpg)
![20220501092052_1](https://user-images.githubusercontent.com/4555004/166128123-8f96844a-2a95-46f2-887e-d28953d92cfd.jpg)

Eingesetztes Geraet: 
* Case Axial Flow 9250 mit nem Varifeed 41Ft Schneidwerk  (New Holland CR10.90 Revelation Mod)
* Case Maxxum CVX 115 mit Brandtner TR 30800 (gleichnamiger Mod). 
* Huron County Map
* 
Ist aus meiner Sicht recht zuverlaessig reproduzierbar wenn der Drescher bereits steht und wirklich auf den Abfahrer warten muss. Ich haeng auch mal das log der aktuellen session an. 

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8598116/log.txt)

**Comment by ct177mak** [comment]
mir ist auch was aufgefallen in deiner LOG.TXT ,viele Call Stack LUA errors , würde mal die Mods alle verschieben und nur CP und AD nutzen und kucken wie es sich dann verhält ,mir persönlich wurde das oft genug geschrieben das auf fremd Mods (Scripte) usw. kein Support erfolgt.

**Comment by schoos76** [comment]
1. Auch mit AD 7.0.1.13 ist das Verhalten im normalen Spiel reproduzierbar. 
2. Der erste Versuch das in nem Testspiel nur mit AD und CP zu reproduzieren ist nicht geglückt, ich denke aber das liegt daran, dass dort die Anfahrt nicht korrekt war - normalerweise nutze ich im CP die "längste Kante" und dann faehrt auf der HCM der Drescher parallel zur Strasse von der der Ablader kommt, im Test stand das auf Auto und der Kurs auf Feld 96 war deutlich geneigt. Neuer Versuch wird folgen

**Comment by ct177mak** [comment]
CP Version ist 7.0.1.13 ,aber egal ,vllt mal im AD den Abstand zur Pipe größer oder was kleiner machen ,ich persönlich lasse meinen Drescher beim abtanken stehen bleiben ,so das er nicht ungewolllt wieder nach vorne sich bewegt und der Abfahrer versucht wieder nach zurücken ,denke mal bei vielen sind paar Einstellungen zum krumm oder anders eingestellt das es zu Problemen kommt.

**Comment by schoos76** [comment]
Nur falls es untergegangen sein sollte, ob deiner ganzen Verbesserungshinweise: das Problem tritt auf wenn das CP-Fahrzeug **steht**: in dem Fall passiert es im 'richtigen Spiel' recht haeufig, wenn der leere AD-Ablader zurueckkommt dass er nierenfoermig praktisch um den Entladepunkt herumfaehrt. Passiert nicht nur bei Dreschern, auch bei Kartoffelerntern, wie ich heute gesehen habe. Ich nehm an, es liegt (auch) am Anfahrwinkel.

**Comment by Axel32019** [comment]
viele Maps im mod-Ordner -> max 1 Map pro Spielstand!
1. Bayrischerwald
2. fs22planet -> verursacht potentiell Probleme
3. BigRiverx16
4. FS22_Dunalka
...
lua-callstacks -> mods entfernen die diese verursachen!

Könnte hieran liegen:
2022-05-01 07:14 LUA call stack:
  dataS/scripts/mods.lua (396) : printCallstack
  =D:/Games/FS22/mods/FS22_ManualCombineDischarge/src/main.lua (60) : addSpecialization
  =D:/Games/FS22/mods/FS22_ManualCombineDischarge/src/main.lua (77) : init
Manuelles Drescher-Entladen???

Der Anfahrwinkel hängt vom Feld-Ziel ab. Es wird immer von hinten an Ernter herangefahren.
Es ist somit normal das dies auch von vorn in was-auch-immer-für-einer Kurve passieren kann.
Generell empfehle ich dringend erstmal gründlich mit den mods aufzuräumen!

**Comment by schoos76** [comment]
@Axel32019 Fuer mich zum Verstaendnis: die nicht genutzten Maps die ich mal zum ausprobieren runtergeladen habe und nicht gleich wieder geloescht habe sind Teil eines anderen Spielstands? Muss ich um nen sauberen Debug-Trace zu bekommen die anderen Mods komplett entfernen oder reicht es einfach nru ein neues Spiel ohne andere Mods zu starten?

**Comment by ct177mak** [comment]
komplett raus ausm Modordner ,irgend wohin verschieben .

**Comment by Axel32019** [comment]
@schoos76 Gib es hier etwas Neues?
