### ISSUE TITLE
Adminrechte vorschlag

### ISSUE THREAD

**Issue by Schlumpf159** [Stephan-S/FS22_AutoDrive#512]
Guten Morgen.  Danke erst mal für den Super tollen Mod und das er so schnell im LS22 zur Verfügung  gestellt wurde.

Was ich fragen wollte: Wird es wie im LS19 möglich werden das im MP nur der Admin Einstellungen wie Fahrer Lohn vornehmen kann.

Good Morning. Thank you for the super great mod and that it was made available so quickly in the LS22.

What I wanted to ask: Will it be possible like in LS19.

**Comment by Iwan1803** [comment]
In LS19 konnten nur die Admins das einstellen? 🙄
Wäre ähnlich wie #187 und #25

**Comment by Axel32019** [comment]
> Guten Morgen. Danke erst mal für den Super tollen Mod und das er so schnell im LS22 zur Verfügung gestellt wurde.
> 
> Was ich fragen wollte: Wird es wie im LS19 möglich werden das im MP nur der Admin Einstellungen wie Fahrer Lohn vornehmen kann.
> 
> Good Morning. Thank you for the super great mod and that it was made available so quickly in the LS22.
> 
> What I wanted to ask: Will it be possible like in LS19.

Guten Abend, Keine Ahnung wie Du darauf kommst das in LS19 die Einstellung nur der Admin vornehmen kann?
Das einzige was da eingeschränkt war/ist das der Routenmager dem Admin vorbehalten ist.
