### ISSUE TITLE
Nodes speed setting

### ISSUE THREAD

**Issue by lordbanastor** [Stephan-S/FS22_AutoDrive#514]
How about a speed setting for nodes, where we would be able to set a specific speed to individual nodes for vehicles. The maximum speed would be limited to the top speed of the vehicle edditing the node, but should obey the top speed of the vehicle using the track when the editing is done. Also, this feature should be optional, so those who don't want to manually set it doesn't need to worry about, because each node will be created with the default speed already set. This would help minimize the wacky movement they sometimes do when approaching curves.

**Comment by Iwan1803** [comment]
Was requested several times and we will not something like that.
The implementation would be too complicated and also the use.
