### ISSUE TITLE
Autodrive XML stopping FS22 to load Savegame

### ISSUE THREAD

**Issue by BrainyTX** [Stephan-S/FS22_AutoDrive#516]
Hi there,
don't know if I'm at the right place.
I made a rather large autodrive of Waldstetten and now every time I want to start the game, it "crashes" at 85% loading.

If I start a new game and copy the config into the new savegame, I can start it once. But starting it a second time isnt possible...

Any clue? Attached is the config.

Thanks for any help.

Deutsch geht auch, kein Plan wieso englisch.. Spiele auf Englisch xD

[AutoDrive_config.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8619597/AutoDrive_config.zip)

**Comment by BrainyTX** [comment]
C:/Users/games/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Specialization.lua:222: attempt to compare number with nil
2022-05-04 12:58 Application exit request forced.
2022-05-04 12:58 Application exit request forced.


![2022-05-04 12_53_16-Farming Simulator 22](https://user-images.githubusercontent.com/104901211/166668262-66b5a8ed-5768-4a1a-8c95-aa3740590065.jpg)

**Comment by BrainyTX** [comment]
Ah! Danke :)

Die Idee mit Umlauten hatte ich auch schon, aber das Komma das Problem ist.. Hab die Kommas gelöscht und alles funzt!!!

:-)))

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
