### ISSUE TITLE
changement de destination

### ISSUE THREAD

**Issue by bennarbed** [Stephan-S/FS22_AutoDrive#517]
bonjour
depuis la dernière version fs22 la 1.4, AD lorsque je joue avec plusieurs destinations change d'une manière aléatoire les destinations
(silo ferme, par champ 50) j ai la version 2.0.0.5
merci pour votre  aide
Cordialement
AC

**Comment by bennarbed** [comment]
bonjour,
merci pour la réponse. Toutefois le problème est toujours présent. En effet même avec une charrue(plow) la destination change!!
sur deux ou trois véhicules deux cas .
Ce problème c'est depuis la version fs22 1.4 .
j'utilise "AD et CP" ensemble.
merci pour votre aide
Cordialement

**Comment by Iwan1803** [comment]
Did you perhaps activate distributed loading or unloading by mistake?

**Comment by bennarbed** [comment]
Bonjour,
merci, hélas ça continue à ne pas fonctionner.
exemple: paramétrage deux tracteurs avec semoirs  c est ok. Je programme un autre tracteur avec aussi un semoir, un des deux tracteur perd son paramétrage et s'arrête.
merci pour votre aide
Cordialement
