### ISSUE TITLE
autodrive and courseplay linkage

### ISSUE THREAD

**Issue by ssk67** [Stephan-S/FS22_AutoDrive#519]
hi,I suggest developing a function，when courseplay have finished work, auto start autodrive to anywhere, maybe stop or load

**Comment by Iwan1803** [comment]
There will be something in the next version 😉

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
