### ISSUE TITLE
Bug: UtilFuncs.lua:378 attemp to perform arithmetic on local toy

### ISSUE THREAD

**Issue by Markus33-ITA** [Stephan-S/FS22_AutoDrive#52]
Hi. I wanted to test the position of the red line and the error is looping even with the engine off and the autodrive not running.
[https://i.imgur.com/nDS7atC.png](https://i.imgur.com/nDS7atC.png)

**Comment by Markus33-ITA** [comment]
Update. I disabled the option, saved and reloaded the game.
He asked me to re-map the AD. It reset without me touching anything. It is as if it had been reset automatically.

A warning appeared [https://i.imgur.com/eyMaluB.png](https://i.imgur.com/eyMaluB.png)

**Comment by Markus33-ITA** [comment]
I wanted to take a look at the log and found about 134 thousand lines, all the same, with the following log.
I don't know now if it's related to this bug or if it's another one.

2021-12-21 16:33 dataS/character/player01/clothes/tops/topAviatorJacket.i3d (8.53 ms)
2021-12-21 16:33 Warning (script): 'playSample': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2021-12-21 16:33   D:\auto_builder\cache\svn\f00e38190983dd8c5a19e42a3fb94599\src\base\scripting\lua\LuaScriptSystem.cpp (879): expectedType == Value::VoidType || expectedType == Value::ClassType
2021-12-21 16:33 LUA call stack:
  =C:/Users/Marco/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/UtilFuncs.lua (1380) : playSample
  =C:/Users/Marco/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Manager/GraphManager.lua (671) : playSample
  =C:/Users/Marco/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrafficSplineUtils.lua (114) : recordWayPoint
  =C:/Users/Marco/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrafficSplineUtils.lua (24) : createWaypointsForSpline
  =C:/Users/Marco/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/AutoDrive.lua (444) : adParseSplines
  dataS/scripts/BaseMission.lua (1284) : update
  dataS/scripts/FSBaseMission.lua (2007) : update
  dataS/scripts/missions/mission00.lua (579) : update
  dataS/scripts/main.lua (1318) : update

**Comment by Axel32019** [comment]
Hello @Markus33-ITA , Same here:
The issue you observed looks like #22 -> fixed in next Release, therefor closed here.
