### ISSUE TITLE
Ladestations vergabe an 2 Fahrzeuge

### ISSUE THREAD

**Issue by OpiGunnar** [Stephan-S/FS22_AutoDrive#521]
hallo,
habe gerade festgestellt das es ein problem mit der vergabe von ladestellen gibt wenn 2 fahrzeuge "laden/liefern" sollen!
in diesem fall hab ich einem lkw mit tank gesagt: laden an wassertelle-> liefern bei kuhweide und go. soweit so gut.
fahrzeug 2 schlepper mit hänger sollte : laden hofsilo,gras->liefern heutrockner und go.
ergebniss: **lkw mit tank unterbricht seine fahrt und hat als ladestelle das "hofsilo"!**
alle bemühungen das irgendwie hinzubekommen,fehlanzeige. hab die beiden aufgaben dann halt hintereinander erledigen lassen.
ergo: 2 fahrzeuge mit verschidenen ladestellen = **problem**, verschiedene **AB**ladestelln =**kein problem**

hoffe auf ein fix bzw. hilfe für vieleicht selbst gemachten fehler

lg
Opi

PS.: was mir noch fehlt im AD .
warum nicht laden hofsilo (gras) -> liefern (trockner) -> laden am trockner (heu) -> liefern kuhstall in einem auftrag und rundkurs.
Will ich zuviel?

lg

**Comment by Iwan1803** [comment]
Mir scheint, das da bei dir was falsch läuft, denn ich schicke ständig mehrere Fahrzeuge mit Transportaufgaben durch die Gegend (teilweise gleiche und unterschiedliche Ent- und Ladestellen). So ein Problem wäre aufgefallen, wenn es denn ein generelles wäre.
Ist vielleicht der Anhänger vor den Zielpunkten blau? Falls ja, könnte das die Ursache sein. Einfach einmal drauf klicken, damit sie wieder weiß werden.

**Comment by OpiGunnar** [comment]
hi,ich werd mal im auge behalten.läuft stellenweise sehr chaotisch ab. aber
das liegt wohl eher dran, das viele ihre routen einfahren wollen (auf ihren
eigenen höfen) ,aber nicht jeder versteht das er die hof routen nur noch
ans haupstraßennetzt angeschliesen müssen.ich hab dann immer die aufgabe
das chaos wieder zu bereinigen,aber naja

wie gesagt ich halts im auge

lg

Am So., 8. Mai 2022 um 13:36 Uhr schrieb Iwan1803 ***@***.***

**Comment by rohne83** [comment]
Hast du evtl Rotierendes Be- und Entladen an? Das könnte ebenfalls deine Probleme verursachen.

**Comment by Axel32019** [comment]
keine Rückmeldung -> closed

**Comment by OpiGunnar** [comment]
nop, is aus


Am Mo., 9. Mai 2022 um 17:20 Uhr schrieb rohne83 ***@***.***>:
