### ISSUE TITLE
[REQ/Enhancement] Trennung von Map- und User-Einstellungen

### ISSUE THREAD

**Issue by Iwan1803** [Stephan-S/FS22_AutoDrive#524]
Die Idee stammt von Tensuko:
Wenn man die Routen anderer nutzt, hat man auch immer deren HUD-Einstellungen etc., da sie mit in der Config stehen.
Hier wäre eine Trennung sinnvoll: eine Config, welche lediglich das Straßennetz mit Map-spezifischen Einstellungen speichert und eine mit den User-Einstellungen. Im MP werden die User-Einstellungen eh schon separat gepeichert.

**Comment by ArtV-Nef** [comment]
the settings are reset when you re-enter the game :(

**Comment by Iwan1803** [comment]
Same here. Looks like the settings for "SinglePlayer" will not be read.

**Comment by ArtV-Nef** [comment]
the last fix fixed everything! it works stably :) thanks

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
