### ISSUE TITLE
LUA call stack (RoutesManager)

### ISSUE THREAD

**Issue by Revan1161** [Stephan-S/FS22_AutoDrive#526]
mionsen  habe auf ein mal seit so ca 2 tag LUA call stack
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8655721/log.txt)
ich hoff die log hilft denn fehler zu finden

**Comment by andremeyer123** [comment]
Mod ordner aufräumen bitte 
FS22_Configure_Maintenance
FS22_Filllevelwarning
FS22_StonePickerStopper und diesen FS22_sugarBeetHarvesterPotatoReady    rausnehmen und nach Updates suchen das sind alte Sachen .Diese kommen mit dem neuen Update vom spiel nicht klar.

**Comment by Revan1161** [comment]
Hy must unten gugen  hatte vergessen die log zu löschen  meine ja die ad lua die ich nicht verstehe

**Comment by Iwan1803** [comment]
Niemand kann ausschließen, das die Fehler anderer Mods nicht auch Auswirkungen auf AD & Co. haben.
Versucht ihr da was mit dem Routen Manager auf einem Server zu speichern, was nicht funktioniert?

**Comment by Axel32019** [comment]
keine Antwort -> closed
