### ISSUE TITLE
Wird nicht ausgewählt

### ISSUE THREAD

**Issue by Zerexo** [Stephan-S/FS22_AutoDrive#528]
Wenn ich das Spiel Savegame starte, dann wird mir die Autodrive Mod nicht angezeigt. Obwohl sie Ingame in meinem Mod Ordner ist.

**Comment by Iwan1803** [comment]
Dann solltest du mal einen Blick in deinen mods-Ordner werfen, ob AD z.Bsp. mehrfach vorhanden ist und die ZIP den richtigen Namen hat.
Am einfachsten ist es, alle ZIP von AD im mods-Ordner zu löschen und dann einmal neu runterzuladen: https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.5/FS22_AutoDrive.zip

**Comment by Zerexo** [comment]
> Dann solltest du mal einen Blick in deinen mods-Ordner werfen, ob AD z.Bsp. mehrfach vorhanden ist und die ZIP den richtigen Namen hat. Am einfachsten ist es, alle ZIP von AD im mods-Ordner zu löschen und dann einmal neu runterzuladen: https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.5/FS22_AutoDrive.zip

Danke hat geklappt lag am Namen war (1) dahinter.
