### ISSUE TITLE
Waypoint with speedlimitter

### ISSUE THREAD

**Issue by BattleHook** [Stephan-S/FS22_AutoDrive#530]
Is it possible to at a new waypoint-type where the driver has to slow down to a certain speed???
I want to use it for barriers with auto open.

Now I have to modify the course and add a little snake-like path just before the triggerbox range. Lowering the detectionheight causes driver to stop on hilly terrain. I use 2m obstacle detection height

**Comment by Tensuko** [comment]
Would be easier if AD use the same kind of proximitysensor that we had in FS19, for slow down and also swerve.

**Comment by Iwan1803** [comment]
If AD doesn't stop in front of a barrier, the collision settings are wrong for it.
And no, we will add speed-limited waypoints or something like that.

**Comment by BattleHook** [comment]
> If AD doesn't stop in front of a barrier, the collision settings are wrong for it. And no, we will add speed-limited waypoints or something like that.

Glad to hear that you will add speed-limited waypoints ;) (assuming you say no to FS19 proximitysensor). 

Sorry to hear that you will not add speed-limited waypoints (assuming you say no to my request).
I think it would be a great enhancement to control the maximum speed of vehicles on certain parts of the track.

Anyway, I appreciate the work you guys are doing with AutoDrive. Keep up the good work.

**Comment by Iwan1803** [comment]
Sorry, i forgot the NOT in my comment:

> we will NOT add speed-limited waypoints or something like that
