### ISSUE TITLE
Rotierendes Beladen zählt Anzahl Wiederholungen nicht runter

### ISSUE THREAD

**Issue by ralfmuehle** [Stephan-S/FS22_AutoDrive#532]
Hallo,
ich schließe nicht aus dass es ein Bedienfehler meinerseits ist:
ich habe zwei Kuhställe von denen ich die Milch mit AD zur Molkerei bringen lasse. AD ist hierbei Rotierendes Beladen gestellt, die zwei Beladepunkte der Kuhställe in einem Ordner. Dies funktioniert soweit prima - Danke für den genialen Mod
Allerdings ist mir aufgefallen, dass die Anzahl an Wiederholungen bei dieser Einstellung nicht heruntergezählt wird und der LKW somit unendlich zwischen meinen Kuhställen und der Molkerei pendelt.

Bitte korrigieren oder kurz erklären was ich falsch mache. Danke

**Comment by Iwan1803** [comment]
Beim rotierenden Beladen greift der Zähler aktuell nicht - beim rotierenden Entladen hingegen schon.

@Axel32019 darüber hatten wir schon mal gesprochen. Vielleicht kann man das noch einbauen...

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
