### ISSUE TITLE
Mittlere Maustaste wird korrumpiert

### ISSUE THREAD

**Issue by MikeSierra-AUT** [Stephan-S/FS22_AutoDrive#537]
Nachdem ich hier für die LS22-Version diesbezüglich nichts finden konnte, also ein eigenes "Issue":
Zunächst einmal: DANKE für Autodrive! Es ist soooo cool, einen Helfer zum Händler schicken zu können, während man selbst am Feld werkt... (egal, auf welcher Karte).
Aber:
Mir fällt auf, dass eine Reihe von AddOn-Mods die Funktion der mittleren Maustaste korrumpieren, also den Wechsel zwischen Blicksteuerung und "freiem" Mauscursor. Da sind u.a.auch (scheinbar) einfache Mods dabei wie z.B. der "Platzierbare Silos" von DD ModPassion oder der "Große Silos Multifrucht" von OmaTana , aber auch reine "Script-Mods" wie "Sleep Anywhere" von Ian898 (alle ingame installierbar). Erst nach Entfernen eines solchen Mods und LS-Neu(!)start funktioniert die Taste wieder so, wie für AD vorgesehen.
Michael
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8713885/log.txt)
.

**Comment by MikeSierra-AUT** [comment]
Ah! Diese Mods löschen die Zuordnung der "MITTE"-Taste für "Maus ein/ausblenden"!
Allerdings blockieren sie auch die Neu-Zuordnung. "LINKS" ginge, "RECHTS" schon wieder nicht, ein "Zurücksetzen auf Standard" funktioniert dafür positiv.

**Comment by Iwan1803** [comment]
Problem also gelöst?

**Comment by MikeSierra-AUT** [comment]
Scheint so. Bis zur Einbindung des nächsten Mods...
