### ISSUE TITLE
[MP] Probleme mit Vanilla - Ballensammelwagen 

### ISSUE THREAD

**Issue by Taylor1684** [Stephan-S/FS22_AutoDrive#538]
Weiß nicht ob ich der einzige bin oder andere auch das Problem haben. Wenn ich mit Autodrive abladen lasse, was auch soweit funktioniert. Sobald er aber fertig abgeladen hat klappt er nicht mehr sauber zusammen, wie man auf den Videos sieht.
Betrifft Rundballen wie Quaderballen Vanilla- Sammelwagen.

Im Singleplayer bzw Offline klappt es ohne Probleme. Die Problem hab ich nur im Multiplayer bzw Server.

https://user-images.githubusercontent.com/104156809/169163971-464b3d5e-0661-42d6-ac62-dae685459d2a.mp4

![Rundballen](https://user-images.githubusercontent.com/104156809/169164765-521efe15-53f2-4c72-9002-235feea89ddd.jpg)

https://user-images.githubusercontent.com/104156809/169163987-9c7ae709-3b88-4ff7-8204-bc8ca6493f55.mp4

![Quaderballen](https://user-images.githubusercontent.com/104156809/169164800-5e710d7f-e805-4957-9762-ba21b85bab8c.jpg)

Hier noch die Logs.

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8734329/log.txt)

[server-log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8734331/server-log.txt)

**Comment by Axel32019** [comment]
Bitte Client- und Server-logs anfügen.

**Comment by Taylor1684** [comment]
> Bitte Client- und Server-logs anfügen.

Sorry die hatte ich total vergessen. Hab sie jetzt im ersten Post mit eingefügt, hoffe es passt soweit.

**Comment by Axel32019** [comment]
Die logs sehen soweit OK aus.
Wenn ich jedoch das 1. Video sehe, läuft mit dem Spiel ja grundsätzlich etwas falsch:
Warum verschwindet die Deichsel nach dem Zurückklappen der Ladefläche im Boden und taucht später wieder auf? -> ca. 35s
Im 2. Video wird der Anhänger nicht komplett zusammen geklappt bevor weiter gefahren wird.
Ist "Fold Implements" in den Experimentellen Features deaktiviert?

Das 2. Bild zeigt einen hängen gebliebenen Ballen - sollte von allein runter fallen...???
Aus Sicht von AD wird immer ein Entladevorgang eingeleitet, mehr nicht.
Meine Vermutung geht in Richtung Syncro-Problem oder Grafik-Treiber.
Probier bitte mal die GraKa auf DX 11 zurück zu stellen - wir haben schon mehrere Phänomene mit DX 12 erlebt.

**Comment by Taylor1684** [comment]
"Fold Implements" war zwar an, aber selbst wenn ich es deaktiviere ändert sich nichts, auch nicht wenn ich server neu installiere und das Spiel neu installiere, bleibt alle gleich.  
Warum die Deichsel erst im Boden verschwindet weiß ich auch nicht, irgendwie sieht es so aus wie er beim zusammenklappen was falschrum macht, Selbst der Ballenschieber fährt  ja nicht zurück. Normal müsste der erst zurückfahren und dann erst den wagen senken, aber kann mich auch irrne.

Der hängende Ballen auf dem 2. Bild, geht nach unten wenn der 4. Ballen aufgeladen wird.

Spiele aktuell alleine auf dem Server.

Kenn mich zwar recht gut mit PC´s aus, aber wie kann ich die Graka auf DirectX 11 stellen? 
Habe Windows 11 und Nvidia RTX3080.

Ich danke auf jedenfall schon mal für die Hilfe.

**Comment by andremeyer123** [comment]
Kann ich auch so bestätigen auf den Server geht er nicht richtig in Transportstellung zurück . 
Es betrifft alle ballensammelwagen Log wie oben alles fehler frei.

**Comment by Axel32019** [comment]
@Taylor1684 , @andremeyer123 Wenn ihr das so super nachstellen könnt, würde es sehr helfen wenn ihr mal folgende Version probiert ob es da anders läuft:
[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8747438/FS22_AutoDrive.zip)

Danke!

**Comment by andremeyer123** [comment]
![fsScreen_2022_05_21_13_51_30](https://user-images.githubusercontent.com/70706468/169652318-f34a572a-2de3-49ca-908b-7765011f7644.png)
![fsScreen_2022_05_21_13_57_08](https://user-images.githubusercontent.com/70706468/169652320-a890e74c-1d14-4256-8205-977b8a994cc4.png)
Ist wie vorher geht nicht in orginal Transportstellung

**Comment by Taylor1684** [comment]
@andremeyer123 kann es bestätigen, das es mit der Test-Version auch nicht funktioniert

**Comment by Axel32019** [comment]
MP Synchro Thema von Giants.
