### ISSUE TITLE
 Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by Mageone** [Stephan-S/FS22_AutoDrive#539]
Hello,

I have this kind of error for 30 seconds and if i don't stop quick the car from this curse then the game crashes. 
Any solutions? I use AD 2.0.5 and Autoload 1.7.3

C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil
2022-05-19 16:36 Error: Running LUA method 'update'.
C:/Users/Asus/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Tasks/UnloadAtDestinationTask.lua:96: attempt to compare number with nil

**Comment by Mageone** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8733918/log.txt)

**Comment by Axel32019** [comment]
Hello @Mageone 
In vehicles.xml replace all `ALUnload="0"` with `ALUnload="1"`

**Comment by Mageone** [comment]
Many thanks! Everything is fine now!
I had this kind of error only at one map , what to do with the rest of maps? To change the vehicle files there, too?

**Comment by Axel32019** [comment]
Yes, to make sure it works OK.

**Comment by Mageone** [comment]
I started the game and i bought few more trucks, i got again same errors. 
I turned off the game and i did modify the vehicle file again. 

It works fine now, but i have to modify the vehicle file each time when i buy more trucks now?

**Comment by Axel32019** [comment]
The fix will be included in next release, for the time being you need to use the dev version:
https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
