### ISSUE TITLE
active unload no change

### ISSUE THREAD

**Issue by wackoamd1** [Stephan-S/FS22_AutoDrive#54]
if u put active unload on a combine on yes or no , the stupid fs22 ai keeps driving , no matter which setting.

btw thanks for the fast update to 22 , and a merry christmas .

ow and a small feature request , would it be possible to get a call unloader option. to use when the field is done but there is still grain in the combine

**Comment by Axel32019** [comment]
if u put active unload on a combine on yes or no , the stupid fs22 ai keeps driving , no matter which setting.
-> set precall level to 50% and active unload yes
btw thanks for the fast update to 22 , and a merry christmas .
-> Thanks!
ow and a small feature request , would it be possible to get a call unloader option. to use when the field is done but there is still grain in the combine
-> find a key assignment in the standard game for "call unloader", apply if combine is finished
the combine will not be unloaded automatic by AD if controlled by ingame helper, not possible at the moment
