### ISSUE TITLE
Autodrive (FS22) - request

### ISSUE THREAD

**Issue by MilanPali** [Stephan-S/FS22_AutoDrive#540]
Hi, I have two ideas for improving Autodrive for FS22.

I use Autodrive all the time. It works perfectly. The tractors also drive perfectly. For example, a New Holland combine harvester, Krone mower, and other large machines often do not fit on a tractor route.
1. Wouldn't it be possible to create a special route for large machines on the road? The classic route for tractors would remain in both directions.
  2. Would it not be possible to create a point from A to B at which a special speed could be set? For example, on a farm. Or in places of production modes. A space where we could set a special speed.

Thank you very much for MODS Autodrive for FS22. Regards Milan.

**Comment by Iwan1803** [comment]
Thanks for your ideas, but the search would have shown you that they already existed and that we will not implement them.
