### ISSUE TITLE
Question! Create a secondary folder

### ISSUE THREAD

**Issue by fuggo2** [Stephan-S/FS22_AutoDrive#541]
Question! would it be possible to create a secondary folder for the main folders? Let's say I create a folder for production and within that it would be possible to create a next folder so that the factories can be separated completely. This would be useful if we were playing a map where there were a lot of production plants and so a lot of production would be better separated.
In many productions, it would be good to be able to organize the various points for production in folders, such as delivering and picking up pallets from the sugar factory and loading raw materials in the same factory. I think it would be clearer.
![fsScreen_2022_05_22_23_20_56](https://user-images.githubusercontent.com/66201069/169716505-57e1bb85-e5aa-4689-9784-7104c3da47cc.png)

**Comment by Iwan1803** [comment]
Check #491, #400 and #215...
As this is dublicated -> closed!
