### ISSUE TITLE
Abfahrer fährt über Maisgebiss vom Häcksler

### ISSUE THREAD

**Issue by Desrow** [Stephan-S/FS22_AutoDrive#542]
Moin, wie der Titel schon verrät habe ich auf einem Feld das Problem dass der Autodrive Abfahrer in manchen (nicht in allen) Bahnen Probleme beim Wenden hat und dem Häcksler über das Maisgebiss fährt, wodurch beide fest hängen. 

Ich hab schon alles an Einstellungen in AD und CP ausprobiert, Kollisionen sind an und auch mit einem neu erstellten Kurs für Courseplay, sodass die Abfahrer mehr Platz haben (+1 Bahn Vorgewende, jetzt 5 Bahnen), ändert sich leider nichts.
![20220523113317_1](https://user-images.githubusercontent.com/31575829/169790889-156da347-ef87-43a9-a5c9-5e030f3978b4.jpg)

**Comment by Desrow** [comment]
Edit: 
Der Abfahrer fährt kurz vor Bahnende hinter den Häcksler, obwohl zur Seite und zum Feldrand massig Platz ist. Wenn der Abfahrer hinter dem Häcksler steht, fährt er wieder rückwärts und noch einmal hinter den Häcksler, dann schaltet er ab. Nachdem der CP Häcksler dann in die neue Bahn gefahren ist fährt der AD Abfahrer wieder los allerdings direkt auf den Häcksler zu und so dann über das Maisgebiss. Passierte so in mindestens 20 Bahnen bisher....bei einem 90 Hektar Feld.

**Comment by eric4072** [comment]
same here...

mit ist aufgefallen, dass der Abfahrer bei manchen Bahnen, ca 10m vor Bestandsende, schon zurücksetzt. Der Häcksler bleibt dann natürlich stehen weil kein Anhänger mehr in der Nähe ist. Danach beginnt ein "Stop and Go" bis zum Ende der Reihe (AD bleibt dann hinter dem Häcksler obwohl links genügend Platz... komisch, da er ja bis zu den besagten Punkt auch links war). Nach dem Wendevorgang tritt dann das oben genannte Problem auf.

Ich habe gerade auf der NF Marsch 3 Häckslerketten auf 3 Feldern laufen, vielleicht komme ich heute dazu ein Video zu machen.
Sonst funktioniert AD wirklich gut. Wenn man 5 Vorgewende macht, haben die Abfahrer auch genug zum Platz (auf Felder begrenzt ist aktiv) zum rechnen. Auch wenn die Turns zeitweise nicht nachvollziehbar sind (manchmal würde eine einfache Kurve reichen und AD beginnt mit 3-5-fachen Kurven, um neben den Häcksler zu kommen). 



LG
Eric

**Comment by Axel32019** [comment]
Sollte ab 2.0.0.6 besser funktionieren
