### ISSUE TITLE
Option for Workers to Run Lights?

### ISSUE THREAD

**Issue by Jayshua83** [Stephan-S/FS22_AutoDrive#543]
Can we get an Option like the Cover option for Lights? The AI turns off their lights ALL the time at night! Very odd!

Having an ALWAYS run with Lights would be nice.

**Comment by Iwan1803** [comment]
AD doesn't turn off the lights at night or what exactly do you mean?

**Comment by Axel32019** [comment]
@Jayshua83 AD switch light on at night, what else do you mean?

**Comment by Jayshua83** [comment]
So I am noticing the AD workers ARE running lights, I just missed that they were when I am using a TLX truck mod from Modhub. His 1st headlights aren't really lights and I think AD helpers only use the first headlights option?

So then my question changes to is it possible to have the AD workers run with ALL available lights at night? (Headlights, High-Beams, Work-Lights...) 

Also is an option possible to have them run lights ALL the time Day and Night?

**Comment by Iwan1803** [comment]
Ask the modder to use the Giants default light routines or check other mods to get the right order.

**Comment by Jayshua83** [comment]
So this isn't something that could be added as a feature?

Option for Workers to run ALL light routines?

**Comment by Iwan1803** [comment]
We will not add options to solve mod problems.
