### ISSUE TITLE
Autodrive tankt am falschen Punkt

### ISSUE THREAD

**Issue by Yakuza112v2** [Stephan-S/FS22_AutoDrive#545]
Moin moin, Autodrive nutzt leider den falschen Punkt zum Kraftstoff aufnehmen.
Statt an eine Zapfsäule zu fahren nimmt Autodrive das Multifrucht-Silo und Spamt dan die Nachricht "Fahre tanken".

**Comment by Iwan1803** [comment]
Nutzt du vielleicht noch eine veraltete Version? Dieses Problem sollte nämlich eigentlich gelöst sein.
Ansonsten wären mehr Infos hilfreich....

**Comment by Axel32019** [comment]
Moin @Yakuza112v2 , Bitte mal komplettes log anfügen.

**Comment by Yakuza112v2** [comment]
> Nutzt du vielleicht noch eine veraltete Version? Dieses Problem sollte nämlich eigentlich gelöst sein. Ansonsten wären mehr Infos hilfreich....

Nein es ist die aktuelle Version.

**Comment by Yakuza112v2** [comment]
> Moin @Yakuza112v2 , Bitte mal komplettes log anfügen.

Den Log von was?

**Comment by Yakuza112v2** [comment]
[glog.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8789693/glog.txt)

**Comment by Axel32019** [comment]
Ursache ist #485

**Comment by Yakuza112v2** [comment]
Ahh thx ich werde es einmal testen. Merci

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
