### ISSUE TITLE
Lift Achsen Fehler

### ISSUE THREAD

**Issue by Z0MBlI** [Stephan-S/FS22_AutoDrive#546]
Habe zum beispiel den Reisch Anhänger mit Lift achse wenn er oben ist macht er keine Probleme aber wenn ich die nach unten mache wirft AD einige fehler und braucht auch lange es zu berechnen 
Aktuelleste Version 2.0.0.5 davor war das Problem nicht

**Comment by Z0MBlI** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8775763/log.txt)

**Comment by andremeyer123** [comment]
Ersteinmal die ganze Log, da steht nicht das der fehler von ad kommt .

**Comment by Z0MBlI** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8777243/log.txt)

**Comment by Axel32019** [comment]
Ist bekannt und schon gefixt: #477

**Comment by Iwan1803** [comment]
Neuer Release / new release: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.6/FS22_AutoDrive.zip
