### ISSUE TITLE
[Suggestion] Hotkey for enable/disable AI-Traffic

### ISSUE THREAD

**Issue by Nickeling** [Stephan-S/FS22_AutoDrive#547]
Hey! ♥

Since AI drivers tend to get stuck with traffic, especially on custom maps, it would be a great relief if you could add a hotkey to easily turn off AI traffic and press it again to turn it back on.
That would be much easier than taking over the tractor and driving out of the traffic jam manually.

Thank you for your time and have a nice day.

**translated with Google**

**Comment by Mexel75** [comment]
Ah, that's a good idea

**Comment by Jayshua83** [comment]
My wife and I thought of this too! We were thinking more of a if AutoDrive has a worker running that it disabled AI Traffic?

**Comment by Jayshua83** [comment]
But an option for a hotkey or enable/disable would be nice

**Comment by Iwan1803** [comment]
AD should disable AI traffic because of traffic jam? 🙄
Maybe you should ask Giants für a key bind.
