### ISSUE TITLE
AD-Streckennetz nach savegame-edit gelöscht

### ISSUE THREAD

**Issue by mlewelt** [Stephan-S/FS22_AutoDrive#55]
Um auf der Beyleron die 1MW BGA wieder zu verkaufen habe ich in der placeable.xml die Farm-ID der 1MW BGA wieder auf "0" gesetzt, die zugehörige fillnode für gärreste ebenfalls auf farmID=0. Zusätzlich habe ich mir den ehemaligen Kaufpreis in der carreersavegame und farms.xml manuell wieder gutgeschrieben. Vor der Änderung habe ich den savegame-Ordner gebackuped. Beim anschließenden laden des Savegames wurde ich gefragt, ob ein Streckennetz erstellt werden soll und alle Strecken waren gelöscht. Ein laden des Backups brach keine Veränderung, hier ebenfalls alles gelöscht. der Autodrive-Ordner im myGames LS Verzeichnis ist abgesehen von der routes.xml (kein Inhalt abgesehen vom Header) leer.

Edit: Ich konnte die AD-config aus einem automatischen Backup wiederherstellen. Der Fehler ist natürlich trotzdem so aufgetreten.

**Comment by skjatala** [comment]
Same as above.

**Comment by regs1980** [comment]
> der Autodrive-Ordner im myGames LS Verzeichnis ist abgesehen von der routes.xml (kein Inhalt abgesehen vom Header) leer.

Dieser wird auch nicht automatisch angelegt, erst nach dem man eine Kurs im Routen Manager speichert.

da draufdrücken 
<img width="366" alt="2021-12-22 09_37_56-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147062991-b6717e64-0552-4019-8a77-348b078064bf.png">

dann öffnet sich das

<img width="1046" alt="2021-12-22 09_37_38-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147063017-34498983-61b3-4d9c-8f06-565c3a08807a.png">

Kurs speichern mit Name, dann entsteht in dem Ordner

<img width="519" alt="2021-12-22 09_33_55-FarmingSimulator2022" src="https://user-images.githubusercontent.com/13314443/147063142-ce6fda64-3e3b-49b1-9a52-d7d4087d3ab7.png">

das

<img width="544" alt="2021-12-22 09_34_07-routesManager" src="https://user-images.githubusercontent.com/13314443/147063182-02d42bdf-49ef-4287-9b6b-aedeff4e7a3f.png">

und in der routes.xml taucht dein Kurs auf, 

<img width="812" alt="2021-12-22 09_34_18-routes - Editor" src="https://user-images.githubusercontent.com/13314443/147063329-abbe72e9-025b-4633-803e-5f90487438cc.png">

im Ordner routes entsteht eine xml Datei die identisch mit der AutoDrive_config ist,

<img width="597" alt="2021-12-22 09_35_28-routes" src="https://user-images.githubusercontent.com/13314443/147063642-94730974-7d45-4b44-af50-83f3ebace5fd.png">

nur liegt sie nicht im Savegame Ordner ist somit Geschütz vor allem außer du löscht den autoDrive oder FarmingSimulator2022  Ordner.
Diese hat auch kein Autosave von daher ist es ratsam beim einfahren öfter mal zwischen zu speichern, wie viel du schon gespeichert hast erkennt man an dem revision= Eintrag in der routes.xml

<img width="812" alt="2021-12-22 09_34_18-routes - Editor2" src="https://user-images.githubusercontent.com/13314443/147064422-f7a123bd-b70f-4924-aaa5-f5e4b7911326.png">
