### ISSUE TITLE
Mist laden mit Förderband

### ISSUE THREAD

**Issue by franky-bb** [Stephan-S/FS22_AutoDrive#551]
Die neuen Kollisionen verhindern ein laden  mit Förderband. Der Schlepper fährt an das Förderband ran und bleibt mit einigem Abstand stehen. Ohne Meldung.

**Comment by franky-bb** [comment]
Zusatz: mit der Version Release 2.0.0.6.

**Comment by redimp** [comment]
Ich kann das Problem bestaetigen, siehe auch die Screenshots /
I can confirm this issue, see the screenshots attached.

![collosion1](https://user-images.githubusercontent.com/112056/170867719-b253459f-4684-4daa-a8fa-492410db2322.jpg)

![collosion2](https://user-images.githubusercontent.com/112056/170867773-7f6b0087-6a91-48b2-9a19-c9a1dc4099a8.jpg)

**Comment by franky-bb** [comment]
Besteht die Möglichkeit, dass man die neuen Kollisionen ausschalten kann. So, dass man weiterhin mit der V2.0.0.6 spielen kann.

**Comment by Axel32019** [comment]
Kollisionserkennung bringt hier leider nichts.
@hathor1411 Dieses Förderband komplett hoch und komplett ausfahren sollte funktionieren.
Für die anderen gibt es derzeit keinen Workaround, Sorry.

**Comment by Iwan1803** [comment]
Bitte mit der neuen Version 2.0.0.7 prüfen: https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.7/FS22_AutoDrive.zip

**Comment by franky-bb** [comment]
Release 2.0.0.7.
Das Problem besteht leider immer noch. Der Trecker fährt erst unter das Förderband, wenn ich auf das Förderband springe. Dann wird auch geladen.

**Comment by Iwan1803** [comment]
Das Förderband muss aktiv sein, damit die Kolli ignoriert wird.

**Comment by franky-bb** [comment]
Das Problem: Wenn ich das Förderband verlasse, springt es auf Inaktiv.

**Comment by Iwan1803** [comment]
Hast du den automatischen Motorstart an oder aus?

**Comment by franky-bb** [comment]
Ich habe automatischen Motorstart an. Spielt aber keine Rolle. Ich benutze das 'Grimme SL80-22 Quantum Autoload-Förderband'

**Comment by franky-bb** [comment]
Eben noch das Förderband mit Version 3.0 getestet. Keine Änderung.

**Comment by Cassy-Blair** [comment]
> Ich habe automatischen Motorstart an. Spielt aber keine Rolle. Ich benutze das 'Grimme SL80-22 Quantum Autoload-Förderband'

Na es macht schon einen Unterschied. Bei automatischem Motorstart an, schaltet sich das Förderband aus, sobald du  aussteigst. Im Modhub gibt es einen Mod, welcher verhindert, daß sich der Motor ausschaltet wenn du dich vom Fahrzeug entfernst. Automatischer Motorstart muß aber deaktiviert sein
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234180&title=fs2022

**Comment by franky-bb** [comment]
Ah, ok. Hab an die Mod nicht gedacht. Funktioniert jetzt. Danke.

**Comment by Iwan1803** [comment]
Supi, dann mach ich hier mal zu 😀

**Comment by GTA3Fan** [comment]
Just got back to game after a few months and noticed tractor wouldn't drive under auger wagon chute. Searched and found this apparently has been fixed on 0.7.

I updated and it started to drive under auger but then stopped before chute. I readjusted driving points and now it won't even go near it. 

0.6
![20220808143713_1](https://user-images.githubusercontent.com/106483338/183496007-19cc1fc4-ce3b-4dc7-a598-4863dd4bd62d.jpg)

0.7
![20220808151212_1](https://user-images.githubusercontent.com/106483338/183496039-9f39efb2-dce5-4214-9c32-a68cfc4c5054.jpg)
