### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by DrakkainenV** [Stephan-S/FS22_AutoDrive#552]
Hi there.

I have big problem with FPS drop. If I have map with ready routes, fields etc and then when I enter the editing mode to set my own routes on my farm, FPS drops to 5. It's happening only when I enter editor mode.

Any suggestions what can cause the problem?

**Comment by Axel32019** [comment]
Hi @DrakkainenV , Please attach the log.txt and a screenshot of the situation.
