### ISSUE TITLE
Persönliche AD Fenster Einstellung greift nicht

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#554]
Ich benutze die vorgefertigte Strecke von der NFMarsch und habe da das Problem das meine persönliche Einstellung vom AD Fenster bei jedem Neustart des Spieles auf die Einstellung vom Macher der Strecke gesetzt wird. Im Video habe ich verstanden das dieses eigentlichen nicht passieren sollte wenn die Strecken vor der letzten AD Versionen von jemand anderen einspielt.

Gruß BigBahamut

**Comment by Iwan1803** [comment]
@Axel32019 ich habe nun ähnliches schon mehrfach berichtet bekommen.
Werden ggfs. die User-Einstellungen nicht aus der AutoDrive_config.xml gelöscht, nachdem sie im SP in die AutoDriveUsersData.xml geschrieben worden sind?
HIer mal der Link zu den Kursen: https://forbidden-mods.de/filebase/file/33337-autodrive-streckennetz-landkreis-rostock/

**Comment by BigBlackBahamut** [comment]
So, ich habe einfach mal ein neues Savegame gestartet. _userDefault sind das was Du meinst? Wenn ja, diese sind nicht gelöscht worden in der AutoDrive_config.xml von vorherigen AD Version.

**Comment by Axel32019** [comment]
@BigBlackBahamut @ddierki @Iwan1803 Bitte folgende Dateien gezippt anfügen: AutoDrive_config.xml, AutoDriveUsersData.xml, log.txt

**Comment by ddierki** [comment]
Zu früh gefreut, das Problem tritt doch wieder auf.
[AutoDriveUsersData.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8822638/AutoDriveUsersData.zip)
[AutoDrive_config.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/8822640/AutoDrive_config.zip)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8822645/log.txt)

**Comment by cwattyeso** [comment]
Have downloaded and tested the latest development version, and whilst it seems to save user settings again which persist on relaunching and reloading the game. It doesn't fix some of the other issues I raised in #579 such as the Autodrive Hud being open on every vehicle when you relaunch or reload the game, nor does it fix this happening in multiplayer with the added issue of every player loading in to find Autodrive is in Edit Mode.

**Comment by BigBlackBahamut** [comment]
DE

In den letzten 20 Tagen kam wegen diesem Problem immer noch kein Update. Ich warte auch Sehnsüchtig auf die Fehlerbehebung. 

Seit einigen Tagen spiele ich auch kein LS22 mehr da mir dieses Problem doch mehr stört als es mir lieb ist. Aber das ist meine Sichtweise und soll hier nichts negativ andichten.

Ich glaube da brauchen wir noch Geduld.

EN

In the last 20 days there was still no update because of this problem. I'm also eagerly awaiting the fix.

I haven't been playing an LS22 for a few days because this problem bothers me more than I would like. But that's my point of view and shouldn't imply anything negative here.

I think we still need patience.
