### ISSUE TITLE
Seltsames Verhalten auf Rückwärtsstrecke im Abladen Modus.

### ISSUE THREAD

**Issue by Peiren85** [Stephan-S/FS22_AutoDrive#555]
Hallo zusammen,

Ich hoffe mal ich kann mein Problem bzw. den eventuellen Fehler hier so gut wie möglich erklären.
Und zwar ist mir heute aufgefallen das AD sich im Abladen Modus seltsam verhält bei Rückwärts angefahrenen Zielpunkten.
Wenn ich den AD Fahrer in dem Abladen Modus zu einen Zielpunkt schicke der Rückwärts angefahren werden muss dann funktioniert bis zu abladen alles korrekt. Also er fährt da Rückwärts hin und lädt ab. Danach fährt er aber nicht einfach ein Stück weiter zurück zum Zielpunkt sondern versucht diesen Vorwärts anzusteuern. Er lenkt also direkt nach rechts oder links ein und versucht so vorwärts den Zielpunkt zu erreichen. Wenn es auf der Rückwärtsstrecke für AD keine Möglichkeit gibt vorwärts wieder in das Streckennetz zu kommen, was man ja aber eigentlich machen muss da er ja von dem Zielpunkt aus sonst nirgends mehr hin kommt, dann fährt er trotzdem vorwärts bis zu dem Punkt an dem die Rückwärtsstrecke beginnt und fährt dann noch mal Rückwärts zum Zielpunkt.

Bin ich z.B. im Drescher Abfahren Modus dann funktioniert aber alles korrekt. Er fährt Rückwärts bis zum Trigger, lädt ab und fährt dann das kleine Stück weiter Rückwärts bis zum Zielpunkt und fährt dann auf der Strecke wieder vorwärts um wieder zum Feld zu kommen. 

Ich hoffe ich konnte es verständlich ausdrücken :) 
Ich benutze die Version 2.0.0.6

EDIT: Hab mal noch meine log mit hinzugefügt und Screenshots.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/8809264/log.txt)
![20220531222805_1](https://user-images.githubusercontent.com/96636006/171279630-81b28a25-31c9-493f-8cf9-5d0a8eccd552.jpg)
![20220531222821_1](https://user-images.githubusercontent.com/96636006/171279634-7c06e9ef-bd19-4020-b786-48a2adcad622.jpg)
![20220531222846_1](https://user-images.githubusercontent.com/96636006/171279636-c6dbe517-e345-41c5-9e05-0fef1c22430f.jpg)
![20220531222900_1](https://user-images.githubusercontent.com/96636006/171279638-f6674929-718a-43af-a273-ba408d116d2f.jpg)

**Comment by Axel32019** [comment]
Hallo @Peiren85 , Einfach gesagt: Falscher Modus
Du schickst das Fahrzeug nur zum Entladen. Ist das erledigt wird der, hier einzige, Zielpunkt angefahren.
Ein Parkplatz ist nicht aktiv, somit wird auch kein Parkplatz nach dem Abladen angefahren.
Im Drescher-Modus gibt es 2 Ziele zwischen denen hin und her gefahren wird, in Deinem Fall nur 1!
Was ist denn das Ziel der Aktion?

**Comment by Peiren85** [comment]
Ich bin bestimmt nicht im falschen Modus. Wenn ich einen AD Fahrer zum Abladen schicke dann soll er das machen und danach auch dort stehen bleiben und seine Arbeit beenden und keine Kreise drehen um den Zielpunkt erneut anzufahren. Er soll auch keinen Parkplatz anfahren. Sondern eben, wie bereits gesagt, nach dem abladen das kleine Stück zum Zielpunkt weiter Rückwärts fahren so wie er das in anderen Modis auch macht.
Ich glaube kaum das es Sinn und Zweck ist das er im Abladen Modus macht was er will und nicht das was eingefahren ist.

Aber gerne noch einmal, auch wenn ich das oben schon geschrieben habe.

Folgende Schritte sollte AD normalerweise machen in diesem Modus. 
-Rückwärts ran fahren zum Abladen <--- das tut er und lädt auch ab
-danach das kleine Stück weiter Rückwärts zum Zielpunkt (da er im ersten Schritt ja nur bis zum Trigger fährt) und dann seine Arbeit beenden und stehen bleiben <--- das macht er nicht sondern versucht vorwärts den Zielpunkt erneut an zu fahren. Er berechnet also quasi noch mal erneut einen Weg zum Zielpunkt um dann die Arbeit zu beenden.

Der Drescher Modus war nur als Beispiel und ist auch als ein Beispiel definiert und heißt nicht das er im Abladen Modus das gleiche machen soll wie im Drescher Modus. Das ergibt ja auch überhaupt keinen Sinn.

Zum Vergleich die Arbeitsschritte im Drescher Modus
AD Fahrer fährt zum Abladepunkt und fährt diesen Rückwärts an bis zum Trigger und lädt ab. 
Danach wird das kleine Stück weiter Rückwärts zum Zielpunkt gefahren und der Arbeitsschritt beendet. <-- Das sollte auch im Abladen Modus geschehen was es aber nicht mehr tut.

Also ich weiß echt nicht wie ich es noch verständlicher schreiben soll.

**Comment by Iwan1803** [comment]
In dem Modi "Abladen" ist es so, das er nach erfolgtem Abladen den Zielpunkt erreicht, um ihn dann noch mal anzufahren.
Er lädt also bei dir auf der Rückwärtsfahrt ab, erreicht den Zielpunkt und möchte ihn dann erneut anfahren. Dies passiert allerdings so schnell, das du es nicht siehst, aber du kannst es mit einem Silo o.ä. (auf einem Rundkurs, keine Rückwärtsstrecke) selber ausprobieren.

@Axel32019 mir ist das auch schon aufgefallen. Vielleicht sollte er dieses erneute Anfahren nicht machen, wenn er einen Trigger/Zielpunkt rückwärts anfährt.

**Comment by Peiren85** [comment]
@Iwan1803 
Auf einem Rundkurs funktioniert das ja auch, da er da ja sowieso vorwärts fährt. Also schicke ich den zum Abladen zu meinem Silo dann fährt er bis zum Trigger und nach dem Abladen weiter zum Zielpunkt und beendet dann dort seine Arbeit. Also vorwärts funktioniert alles wie es soll.
Beim Rückwärts fahren fährt er aber eben nur bis zum Trigger, lädt ab und fährt danach direkt vorwärts und versucht auf direktem Weg (also nicht auf der AD Strecke) den Zielpunkt zu erreichen. In den anderen Modis sehe ich ja wie er nach dem Abladen das kleine Stück rückwärts fährt zum Zielpunkt aber im Abladen Modus sehe ich das er das nicht macht. 

Aber gut das es dir auch schon aufgefallen ist. Hätte ja auch sein können das ich irgendwas falsch mache beim Einfahren aber ich bin der Meinung das er das sonst nicht gemacht hat.

**Comment by Iwan1803** [comment]
Bisher bin ich Trigger nicht nur zum Abladen rückwärts angefahren sondern immer nur per Abholen&Abliefern.
Das ist mir jetzt auch erst aufgefallen, nachdem mich jemand drauf angesprochen hat.

**Comment by Iwan1803** [comment]
Fixed -> https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
