### ISSUE TITLE
Strecken(Linien) nicht sichtbar mit Hohen Settings [bei Mittel schon]

### ISSUE THREAD

**Issue by FlighN8gh** [Stephan-S/FS22_AutoDrive#559]
Hallo,
ich sehe meine **Linien bzw. Strecken** nicht mehr im Editor Modus. Man kann nur die Namen der Ziele sehen (siehe Bild)
Ich habe die neuste Version von AD / Ls 22 und habe alles mögliche probiert, aber ich kann die Routen einfach nicht mehr sehen ...
Aber die Strecken funktionieren noch. 
Hoffe jmd kann mir weiterhelfen. 
Bild:
![h](https://user-images.githubusercontent.com/106766676/171695326-1065315c-5016-4b4e-8fae-53aae76faa52.png)

**Comment by Axel32019** [comment]
Hallo @FlighN8gh 
Bitte folgende Dateien gezippt anfügen: AutoDrive_config.xml, AutoDriveUsersData.xml, log.txt

**Comment by Iwan1803** [comment]
Ich vermute mal, du bist "𝗛𝗶𝗴𝗵𝗘𝗡𝗗✔" aus dem DC, oder?
Wie dort schon geschrieben:
prüf mal deine Grafikeinstellungen und setz sie einfach mal auf "Mittel" zurück, ggfs. mal V-Synch aktivieren.

**Comment by FlighN8gh** [comment]
Ja das ist korrekt @Iwan1803 
Ich habe gerade Mal die Grafik Einstellungen auf Mittel gesetzt und V-sync aktiviert und auch wieder zurückgesetzt, aber ich sehe immer leider noch keine Linien ....

**Comment by Axel32019** [comment]
@FlighN8gh Wie ist es mit der Lininen-Anzeige von CP?
