### ISSUE TITLE
Probleme bei Nutzung eines anderen Schleppers

### ISSUE THREAD

**Issue by TheUsforcer** [Stephan-S/FS22_AutoDrive#56]
Guten Morgen,

ich habe eine Route zum Abfahren meines Häckslers erstellt und im Aschluss dann gleich Abladen in ein Keilsilo. Als ganz erste Route habe ich die Route mit dem Claas Xerion als Mod angefahren und das hat auch super funktioiniert. Dann habe ich den von LS gestellten Fendt 1050 genommen, weil der mit den Anhänger einen besseren Wendekreis hat. Dann fingen die Probleme an. Mit dem Xerion alles Top, aber mit dem Fendt ...  Er findet die Punkte nicht, bleibt auf einmal mitten drin stehen und macht den Motor aus. Nimmt man wieder den Xerion, ist alles wieder Super.
Fahrzeug war getankt, repariert und auch das Gewicht war repariert und der Anhänger auch.
Auch bei einer neu erstellten Route mit dem Fendt macht er probleme wie oben beschrieben, aber der Xerion ging da durch, ohne Probleme.
Woran kann das liegen? Einstellung meinerseits?

Grüße :)

**Comment by Axel32019** [comment]
Guten Morgen @TheUsforcer , Bitte hilf uns mal mit Screenshots wo der Fendt hängenbleibt. Aus der Beschreibung kann ich keinen Grund erkennen. Bitte auch mal Kolli ein (F5) wenn er hängt.

**Comment by TheUsforcer** [comment]
Werde ich mal machen, kann aber erst heute abend.

**Comment by TheUsforcer** [comment]
Hier das Bild. Der Fendt bleibt einfach stehen. Mit dem Xerion fährt er die selbe Strecke durch
![2021-12-23 13_34_25-Farming Simulator 22](https://user-images.githubusercontent.com/12585847/147241419-7d791050-2038-4ec2-8ccb-ce4a58b780c9.png)
.

**Comment by Stephan-S** [comment]
Das ist die Kollisionserkennung. Entweder in den Einstellungen höher vom Boden wegstellen oder ganz ausschalten.
Oder die Kurse anpassen, dass er nicht so schräg Richtung Boden schauen muss
