### ISSUE TITLE
Lade/Entladekurs, Entladeziel wird von AD abgeändert

### ISSUE THREAD

**Issue by MikeSierra-AUT** [Stephan-S/FS22_AutoDrive#560]
Neue Beobachtung: LS22 (1.5.0.0.build 27568/62677), Karte Hof Bergmann v1.0.01 vom 25.5.2022, Autodrive v2.0.0.6 mit den Kursen von elMatador.
Ich hatte mit der HofBergmann-Beta einen Lade-Entlade-Kurs von Feld 5 zum Heu/Strohentladepunkt und retour, Ladung Stroh, Fahrzeug John Deere + Pöttinger Aufnahmewagen. Funktionierte prächtig. Nach Neu-Beginn mit der v1.0.0.1 der Hof Bergmann gleicher Kurs, diesmal mit Heu. Funktioniert genauso prächtig. Jetzt ernte ich (endlich) und will das Stroh ins Heulager einbringen... Erstaunen! AD erlaubt mir das Heulager nicht als Entladepunkt, sondern ändert das Ziel in "Vk - Futtermittelhandel", wenn cih den Lade/Entladezyklus nehmen will. Wähle ich das Heulager als einfaches Fahrziel und entlade das Stroh dort manuell, wird Stroh problemlos angenommen. Also _müsste_ das doch eigentlich gehen. Am Namen des Entladepunktes kann's ja wohl nicht liegen, oder?
Michael.
P.S.: nächster Versuch: Diesmal "schummle" ich und gebe "Heu" als Ladegut an, obwohl ich Stroh eingeladen habe. Jetzt nimmt AD das "Heulager < einlagern" als Entladepunkt ohne Probleme. Es wird sogar automatisch entladen.... (Da kenn' sich einer aus. ;o) )

**Comment by Axel32019** [comment]
Sie die Anhänger-Symbole im HUD nicht weiß sondern blau?
Siehe: https://youtu.be/2bdql33eZIk?t=1475

**Comment by MikeSierra-AUT** [comment]
Ähm.... wäre mir nicht aufgefallen, werde das nächste Mal darauf achten. (Video gesehen, könnte ein Fall von RTFM sein...)

**Comment by MikeSierra-AUT** [comment]
War wohl grün (das Symbol). Wenn's weiß ist, funktioniert's problemlos. Danke für den Tipp.
