### ISSUE TITLE
Hänger Krone GX520

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#561]
Hallo zusammen, ich fahre seit ein paar Tagen den Hänger Krone GX520 und habe da ein Problem mit dem Entladen wie Beladen. 

Beim Entladen wird die Heckklappe nicht geöffnet, er ladet zwar mit der Schiebewand ab allerdings sieht das halt komisch aus.
Beim Beladen wurde der Trailer zwar voll geladen allerdings Texturtechnisch nur der hintere Teil befüllt.

Beim manuellen be- und entladen enstehen die beschriebenen Fehler nicht.

Lieben Gruß
BigBahamut

**Comment by Iwan1803** [comment]
Klingt wie das Problem hier: #422
Nutzt du die aktuelle AD-Version 2.0.0.6?

**Comment by BigBlackBahamut** [comment]
Ja, ich benutze die aktuellste Version (2.0.0.6) Und bei mir lädt und entädt er ja, aber wenn ich es manuell mache dann öffnet sich die hintere Klappe und er ladet mit der Schiebewand ab, schließt dann die Klappe wieder und fährt weiter. Wenn AD abfährt enlädt AD auch allerdings ohne die Heckklappe zu öffnen. Sieht halt komisch aus. 

Ich habe es gerade noch mal bisschen ausprobiert. Das mit dem Beladen scheint wirklich nur mit AD zu passieren, ich habe es gerade ein paar mal getestet mit und ohne AD. Aber auch mit AD ist es nicht immer so, manchmal ist es auch normal ;-)
![fsScreen_2022_06_04_11_10_31](https://user-images.githubusercontent.com/59480223/171992942-e33e2d27-5372-4418-877f-4b07043972b5.png)
![fsScreen_2022_06_04_11_12_15](https://user-images.githubusercontent.com/59480223/171992946-6b12c0d7-9a22-4959-a8d6-c2ba74883f32.png)

**Comment by andreasthu** [comment]
Ich habe dasselbe beim Abladen, das sich die heckklappe nicht öffnet.
Alle anderen verwendeten Anhänger bzw Ladewagen öffnen die klappe wie vorgesehen.
Ad version die aktuelle dev von axel.
Beim befüllen (mit silage vom fermenter-silo) habe ich jedoch eine normale plane, das sieht bei mir sauber aus.
Lg
Andreas

**Comment by Axel32019** [comment]
Anhänger hat eine Entladeposition ohne Heckklappenfunktion und ohne Effekt - Giants bietet diese manuell wohl gar nicht an, AD nutzt alles was geht....

**Comment by andreasthu** [comment]
funktioniert mit dem fix von vor 15stunden noch immer nicht:
![fsScreen_2022_10_01_10_10_34](https://user-images.githubusercontent.com/24860501/193402097-18d73645-2640-4b5b-8b26-ff236168f276.png)
abladen beim Hayloft, aber die klappe bleibt zu
version:
https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

lg
andreas

**Comment by Axel32019** [comment]
@andreasthu Danke fürs Testen - hab die Ursache hoffentlich gefunden.

**Comment by andreasthu** [comment]
funktioniert (bei mir) nun wie es soll.
danke, der gx520 ist ein toller Anhänger, nun ist auch die Abladeanimation mit Klappe perfekt.
lg
andreas

**Comment by 60erjonny** [comment]
Hallo
Mir der neuen Version 2.0.0.9 läd der Ladewagen nicht mehr ab, im Abholen und Abliefern Modus. Karte NFM und mit Standartladewagen getestet. Mir der alten 2.0.0.7. ging es noch.
![Screenshot (80)](https://user-images.githubusercontent.com/6365918
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10149002/log.txt)
2/205502814-8a7fac92-7246-4f30-8cb3-9657276d93e3.png)

**Comment by Iwan1803** [comment]
Bitte ein neues Issue aufmachen und dann auch mit allen Infos wie z.Bsp. sichtbarem Streckennetzen, Einstellungen, etc., danke!
