### ISSUE TITLE
Keine Tankstelle möglich

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#562]
Hi, vielleicht habt Ihr eine Idee. Aber ich bekomme keine Tankanbindung in AD. Es heißt immer das keine Tankstelle gefunden wurde.
Ich bin gerade am verzweifeln.

LG BigBahamut

**Comment by Iwan1803** [comment]
AD sucht in einem Umkreis von 15m rund um Zielpunkte nach Tankmöglichkeiten.
Zieh also eine AD-Strecke an einer Tankmöglichkeit lang und setz dort einen Zielpunkt.

**Comment by BigBlackBahamut** [comment]
Also:

Ich habe mir 2 Felder frei gemacht und bebaut. Habe meine Wege eingerichtet und habe Silos und Werkstatt sowie Parkplätze und andere Gebäude mit AD eingefahren.

Alle Punkte werden erkannt, auch die Werkstatt. Nun habe ich eine Tankstelle auf dem Hof gestellt und natürlich auch einen Zielpunkt gesetzt. Alles stimmte, also kein Wegpunkt fehlt oder ist falsch gesetzt. 

Alle Zielpunkte werden erkannt und angefahren. Selbst der Zielpunkt meiner plazierten Tankstelle wird angefahren aber wenn ich AD sage er soll Tanken fahren heißt es "Keine Tankstelle gefunden" und der Zielpunkt ist genau Parallel neben dem Tanktrigger....

**Comment by Iwan1803** [comment]
Ist das ein Silo oder eine reine Tankstelle? Manuell kannst du dort tanken?

**Comment by BigBlackBahamut** [comment]
Es ist die Tankstelle von HoT. Aber ich habe auch schon versucht eine andere (Von Fed) am anderen Ort zu stellen und anzufahren, aber auch da klappte es nicht. Die von Fed hat allerdings immer funktioniert.
Und ja, selbst Tanken geht.

**Comment by BigBlackBahamut** [comment]
Ich habe gerade mal einen neuen Savegame erstellt mit den minimalen Einsatz von Mods, aber auch hier leider das gleiche Problem. Die original Tankstelle wird nicht gefunden. 

LG

**Comment by Iwan1803** [comment]
Ein Ziel anfahren ist halt was anderes als Tanken fahren 😉
Und ja, ich vergass: ist der Tank zu voll, fährt AD nicht tanken.
