### ISSUE TITLE
Option to not "x" trailers.

### ISSUE THREAD

**Issue by GunthorNC** [Stephan-S/FS22_AutoDrive#564]
Autodrive tends to (Like base game driving AI) "x", activate, or "Unfold" the trailer as it starts its course. This leads to dragging "ITRunner" dumpsters down the road instead of leaving them on the trailer, by offloading them onto the ground behind the trailer, and then starting the course, or moving the log forks on the Fleigel trailer from the previous position (So logs can fall out if not strapped)

Any option to add the ability to disable this function? I'm sure there's more situation's I've missed, those two stand out though.

**Comment by TheEaglez** [comment]
I'm also having the same issue with the Roland pack trailers it drops the container and then starts its course.

**Comment by Axel32019** [comment]
mod issue -> #662
