### ISSUE TITLE
Autodrive nodes dissapear

### ISSUE THREAD

**Issue by GunthorNC** [Stephan-S/FS22_AutoDrive#565]
I ran into this today, All the "Balls" on my nodes dissapeared. I have them set above the tractor, and I am in edit mode. I see all the lines, and if I am SUPER careful, I can click the right spot to move or edit them, but the actual balls are missing and I can't seam to get them back.

**Comment by WernerWusel** [comment]
Die Rechte STRG-Taste schaltet die Bälle Ein/Aus ..

**Comment by GunthorNC** [comment]
That fixed my issue, Thank you so much. My buddies didn't know that either.
