### ISSUE TITLE
autodrive freezes game

### ISSUE THREAD

**Issue by BRADP1980** [Stephan-S/FS22_AutoDrive#566]
When i have enabled autodrive to drive to a location it freezes my location where im watching it drive but the tractor continues to drive down the street and the screen no longer follows the tractor and the tractor continues to go until it hits something, but i can do anything because im froze. Thoughts? BTW i'm on the newest build.

**Comment by BRADP1980** [comment]
I believe I have figured out what was happening with Autodrive. I was doing some trouble shooting and had noticed it was happening more with one tractor then any other. so I started to send every tractor i had down the same Autodrive path. After sending them all down it only happen to one tractor so I focused my attention on that one. sent it down again same thing. so I disconnected the trailer I had connected to it sent it down same path no issues. so it was the trailer for some reason clashing with Autodrive. It was trailer SEK 802 Pallet Autoloader. If this happens to you and you are using this trailer i hope this helps.

**Comment by Iwan1803** [comment]
Is this the only autoload trailer and are you using the newest version of Achimobil Autoload script?

**Comment by BRADP1980** [comment]
As of right now, yes that's the only autoload trailer I am using as I started a new game. Reason I started this new game is because it was doing it on my old game as well. As far as the Autoload script I don't know if I have the newest. Can you point me to the right direction to check please?

**Comment by Iwan1803** [comment]
The latest version is 1.7.3.0 and can be found here: https://www.farming-simulator.com/mod.php?mod_id=228819&title=fs2022

**Comment by BRADP1980** [comment]
That seem to have worked. Ran the trailer down a few times to be sure and did not glitch or freeze once! Thank you for you help! It is much appreciated!

**Comment by Iwan1803** [comment]
You'r welcome 😀
