### ISSUE TITLE
[Suggestion] reusable Breadcrumb Trail

### ISSUE THREAD

**Issue by dezza69** [Stephan-S/FS22_AutoDrive#567]
Hi,

Thank you for AutoDrive!

In FS17 and FS19 I used CoursePlay to record a self-driven continuous path (breadcrumb trail of waypoints), which recorded turn speeds (etc) and could be saved and reloaded into other vehicles.

The FS22 version of CoursePlay has removed this feature and the devs have pointed me to your AutoDrive to do the same, but I'm unable to get such a simple thing to work with AutoDrive, as there is no applicable "mode" available.

Here's pretty much what I used to do, but I'll use the purchasable land around the animal dealer on FS22's "Elm Creek" for my example:
This property has a lake, trees and ... much untamed grass!!!!  I want to be able to drive my own continuous path around this entire land and "record the motions" for later use.  Just the path with the speeds would be awesome, but tool activation/de-activation recall points would be a super added bonus.

Edit:

Just to slightly extend my example, I've driven/recorded the track I want - but the vehicle won't use the tools when driving it, in this case front/back mowers and, then later using a foraging trailer.  Also when having two tools (eg the front back mowers on a tractor) AutoDrive stalls as it seems to only turn one - the back - off before attempting to drive the course if they're on before pressing the go button.

:Edit

My apologies for being goofy and not understanding how to use your software if this is already possible, but I am unable to find how to do it.

Thank you and kind regards.

**Comment by Iwan1803** [comment]
AutoDrive is not designed to do such field work like mowing and we will not add features like this.

**Comment by dezza69** [comment]
Thank you.

Exactly what I thought and I'm really not sure why they're not wiling/able to add a "save track as course" option to CoursePlay.

But that's just my POV.

Anyways, thanks for your time. Much appreciated.

**Comment by Iwan1803** [comment]
Maybe you can create a field border with CP. Then CP will recognize it as a field and you could use CP to cut the grass.

**Comment by dezza69** [comment]
Thank you for your suggestion, very kind and generous.

I've tried their new way, but the course generator doesn't work (correctly) on such a large custom field which ends up having a lake, trees and a series of buildings in the middle of it.  It produces straight lines with sharp turns and the vehicles get stuck and don't dodge the odd objects.

For actual fields, it's fine.

For some "field" shapes/circumstances it's just far easier to drive one continuous path and record it so you can follow the same path again, either with the same vehicle or another (to forage from the first, for eg).

I've done this with CoursePlay since FS17, moving from console to PC/Mac specifically to use CoursePlay and that feature.  It was great, and the earlier games I had tracks all over the map mowing "council grass" :) :)

Anyway, seems it's time to break out BB-Edit and get coding myself.

Kind regards.

**Comment by haamic** [comment]
@dezza69 
Hi. Record the complete driving path with CP. Send me the custom course of the record. I can convert this custom course into a Field course. The way you drove is the way the mower will drive.

**Comment by dezza69** [comment]
Thank you for your kind offer Michael, much appreciated - but their gauntlet has got my creative-coding juices flowing...

Kind regards and Happy Farming!!! :)

**Comment by dezza69** [comment]
This is for Michael and anyone else interested. Thank you for your suggestion/hack Michael, very much appreciated.

I've made a little 10 step process for creating the custom paths and per the CoursePlay link you provided.

Here's a link to the thread on the Giants forum.

https://forum.giants-software.com/viewtopic.php?f=963&t=189348&p=1514994#p1514994
