### ISSUE TITLE
Vorschlag Verbesserung - Drescher Betankung auf dem Feld 

### ISSUE THREAD

**Issue by JayDi999** [Stephan-S/FS22_AutoDrive#569]
Hallo,

mein Vorschlag wäre, dass Drescher Maschinen direkt auf dem Feld von AD betankt werden können (ggf. in Kombination mit CP)
da aktuell die Drescher wenn der Tank leer ist selbstständig CP beenden und in AD wechseln um zur Tankstelle zu fahren - Das Ergebnis ist, dass der Drescher mit dem Schneidwerk alles auf seinem Weg umfährt und sich irgendwo am Baum / Haus festfährt.

Eine Möglichkeit wäre wenn der Traktor mit Anhänger selbst zum befüllen kommen könnte oder falls das zu komplex ist die Möglichkeit besteht wenn der Drescher sein Schneidwerk selbst abhängt und ohne dieses tanken fährt und es dann bevor er an CP übergibt wieder ankoppelt

**Comment by Iwan1803** [comment]
Schalt doch das automatische Tanken für den Drescher einfach aus 😉

**Comment by JayDi999** [comment]
Gut das wäre zu einfach :D 
aber ja das ist natürlich die einfach (vergessene) Möglichkeit

**Comment by Iwan1803** [comment]
Ist das Thema damit erledigt?
Falls nicht, dann das Issue wieder öffnen.
