### ISSUE TITLE
LUA call stack

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS22_AutoDrive#57]
Ich hab heute mal das Streckennetz erstellen lassen und danach kam diese Meldung.
und was um alles in der welt soll dieser eintrag sein?
D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\base\scripting\lua\LuaScriptSystem.cpp (890): expectedType == Value::VoidType || expectedType == Value::ClassType

2021-12-22 12:50 Warning (script): 'playSample': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2021-12-22 12:50   D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\base\scripting\lua\LuaScriptSystem.cpp (890): expectedType == Value::VoidType || expectedType == Value::ClassType
2021-12-22 12:50 LUA call stack:
  =F:/Spiele/Landwirtschaftssimulator 22/mods/FS22_AutoDrive/scripts/Utils/UtilFuncs.lua (1380) : playSample
  =F:/Spiele/Landwirtschaftssimulator 22/mods/FS22_AutoDrive/scripts/Manager/GraphManager.lua (671) : playSample
  =F:/Spiele/Landwirtschaftssimulator 22/mods/FS22_AutoDrive/scripts/Utils/TrafficSplineUtils.lua (114) : recordWayPoint
  =F:/Spiele/Landwirtschaftssimulator 22/mods/FS22_AutoDrive/scripts/Utils/TrafficSplineUtils.lua (24) : createWaypointsForSpline
  =F:/Spiele/Landwirtschaftssimulator 22/mods/FS22_AutoDrive/scripts/AutoDrive.lua (444) : adParseSplines
  dataS/scripts/BaseMission.lua (1304) : update
  dataS/scripts/FSBaseMission.lua (2006) : update
  dataS/scripts/missions/mission00.lua (582) : update
  dataS/scripts/main.lua (1323) : update

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7762479/log.txt)

MFG Mannie313

**Comment by Stephan-S** [comment]
Duplicate. And already fixed in next release
