### ISSUE TITLE
Bale trailer not unloading round cotton bales at deliver point (Pickup & Deliver)

### ISSUE THREAD

**Issue by LoopyJuice** [Stephan-S/FS22_AutoDrive#570]
I have been unable to find any way for AD to trigger unload on this bale trailer (McCormack Cotton Tag Trailer), it requires 3x "Y" presses to unload but moving the waypoint back and for, re-recording the path does not work. I note the bale type in the hud doesn't populate and is blank when I click the dropdown box.

Courseplay intergration works fine for collecting and getting to the deliver point but it just sits here stuck.

![FarmingSimulator2022Game_2022-06-07_13-36-01](https://user-images.githubusercontent.com/107047276/172380354-3bf69aa9-cdb1-4305-9472-b923b1a9171b.jpg)

**Comment by Iwan1803** [comment]
If there is no trigger, AD will not unload to the ground.

**Comment by Yakuza112v2** [comment]
@Tritura2 but you have already read that he says that moving the unloading point does not work? I think it's because you haven't filled in the third tab, at least that was the problem for us. With bales AD is quite difficult if it does not recognize this and you fill in the third tab comes mostly in the console an error with a LUA error.

**Comment by Axel32019** [comment]
> @Tritura2 but you have already read that he says that moving the unloading point does not work? I think it's because you haven't filled in the third tab, at least that was the problem for us. With bales AD is quite difficult if it does not recognize this and you fill in the third tab comes mostly in the console an error with a LUA error.
> 
> c:.../FS2022/mods/AD/scripts/Hud/PullDownList.lua:589 attempt to index a nil value Error: Running LUA method ´draw´

#589

**Comment by Axel32019** [comment]
#597
