### ISSUE TITLE
Ballentrailer CP/AD Combi

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS22_AutoDrive#571]
Welchen Modus muss ich bei AD Auswählen das er automatisch nach dem Ballensammeln mit CP zum Entladepunkt fährt und ablädt und wieder zurück?

**Comment by Iwan1803** [comment]
Abholen und Abliefern.

**Comment by ArtV-Nef** [comment]
Und es ist wichtig, dass der Ladepunkt im AD innerhalb des Feldes liegt.

**Comment by Iwan1803** [comment]
Da Frage beantwortet -> geschlossen.

**Comment by kferrano** [comment]
Ist bekannt das beim Rundballenwagen das nicht funktioniert? falls nicht mach ich gerne Video dazu
