### ISSUE TITLE
Ladenwagen schließt nicht mehr 

### ISSUE THREAD

**Issue by marc950** [Stephan-S/FS22_AutoDrive#573]
![fsScreen_2022_06_10_10_42_34](https://user-images.githubusercontent.com/57912537/173087249-06a36542-422f-4413-bdbd-589566a3467b.png)
![fsScreen_2022_06_10_16_20_58](https://user-images.githubusercontent.com/57912537/173087255-0fbb0c41-4257-4538-9ddf-053f9cc2aeab.png)
Hi, nachdem Entladen im Silo rückwärts einfahren, das Entladen wird nicht beendet. es sei denn ich stoppe ad schließe die Klappe.

**Comment by marc950** [comment]
![fsScreen_2022_06_10_16_59_09](https://user-images.githubusercontent.com/57912537/173094033-ebe29f59-59a2-4945-af7b-2c3638db48db.png)

auch bei Durchfahrsilo

**Comment by marc950** [comment]
der mod https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=245479&title=fs2022 behindert Ad bei endladen

**Comment by FreddyS71** [comment]
> der mod https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=245479&title=fs2022 behindert Ad bei endladen

Vielen Dank! Hatte dieses Problem auch und deaktivieren des Mods hat geholfen.
