### ISSUE TITLE
Feature Request: Ability to change speed limits by holding LMB or RMB instead of clicking once per kph adjusted.

### ISSUE THREAD

**Issue by GunthorNC** [Stephan-S/FS22_AutoDrive#574]
Would be amazing. I find I need to limit my log trailers from 120 kph to 30kph so they don't flip over. Setting the speeds back and forth depending on task takes a lot of clicks.

**Comment by regs1980** [comment]
Mouse wheel is the solution

**Comment by Iwan1803** [comment]
What regs says: move the mouse pointer over the button and then scroll the mouse wheel 😎

**Comment by Iwan1803** [comment]
You can also set a % for the speed in curves.
