### ISSUE TITLE
Unloading from mother bin

### ISSUE THREAD

**Issue by Misamangame** [Stephan-S/FS22_AutoDrive#575]
Hello,  since version 2.0.0.6. trucks or tractors are refusing to go under mother bins unloading pipe. I moved course as far as possible but they are still only standing 1s before loading point. Same course with 2.0.0.5. works without any issues and trucks are loaded normally. Tractors which are filling mother bin have course much closer to it and driving there with no problems.   Maybe some wrong detection of mother bin pipe or that digital counter which comes up with fill level? 

![20220604235753_1](https://user-images.githubusercontent.com/33344465/173179372-ea8246ee-881e-4521-b1ca-3f342d8b9e2b.jpg)

![20220605003102_1](https://user-images.githubusercontent.com/33344465/173179378-aa69463e-776e-42f3-99be-dd9ccabc869e.jpg)

**Comment by rohne83** [comment]
Looks like that's an issue with collision detection. AD has changed in this regards with latest version, but this scenario might not have been thought about

**Comment by VortexGT** [comment]
I'm also experiencing the same problem.
![20220611052643_1](https://user-images.githubusercontent.com/107305920/173186057-8bd6e808-0217-4a3f-a321-b515c4e1c339.jpg)
.

**Comment by andrewrooke** [comment]
I appear to be having the same problem described above, but have not tried under previous releases

**Comment by JanCraymer** [comment]
I can confirm this problem. For me it happened with a potato harvester.

**Comment by MoslessNeo** [comment]
I confirm the same situation; collision detection has become more sensitive.
