### ISSUE TITLE
Nahes aneinander vorbei fahren

### ISSUE THREAD

**Issue by tobiasw83** [Stephan-S/FS22_AutoDrive#576]
HI,

hab das Problem mit Aktivierte oder Deaktivierte Kollisionserkennung das auf engen Straßen die Traktoren voreinander stehen bleiben obwohl sie ohne Kollision aneinander vorbei kommen würden.

Gibt es da eine Möglichkeit einzugreifen und das zu verhindern??

Danke
Tobias

**Comment by 60erjonny** [comment]
...auf solchen Teilstücken , wäre **eine** blaue Linie zu empfehen...die ist ja beidseitig befahrbar und wenn sich gerade ein Fahrzeug auf solch eier Stecke befindet, warten ander Fahrzeue bis sie wieder frei ist...

**Comment by Iwan1803** [comment]
Ein Screenshot der Situation mit aktiviertem Debugging (Fahrzeuge, Sensoren) wäre hier hilfreich, um das beurteilen zu können.
In 2.0.0.6 haben wir ja eine Verbesserung bzgl. der Kolliboxen vorgenommen.

**Comment by Tensuko** [comment]
Alte Version und kein debug an (damals nicht dran gedacht), aber ich vermute er meint solch eine situation.
Ich hab es noch nicht geschafft sowas nach zu stellen mit der neue Version.
Daher nur zur Anschauung...

![fsScreen_2022_03_27_19_23_46](https://user-images.githubusercontent.com/27344744/173633168-05231a7c-6a3e-4090-803d-664986faf854.png)

**Comment by Yakuza112v2** [comment]
Meißtens passiert es nur bei sehr engen Stellen oder in Kurven. Wo es aber immer passiert ist wenn einer der Traktoren Raupen statt Räder hat.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
