### ISSUE TITLE
Einstellung werden nicht mehr gespeichert

### ISSUE THREAD

**Issue by 0scarZulu** [Stephan-S/FS22_AutoDrive#577]
Hallo 
seit der x.x.0.6 speichert es gemachte Einstellungen nicht mehr. Zum Beispiel muss ich bei jedem neuem Savegame Start den Punkt auf Karte anwählen neu aktivieren. Mit 0.5 lief das ohne Probleme.

**Comment by Iwan1803** [comment]
Doppelt zu -> #554
