### ISSUE TITLE
Some Issues with 2.0.0.6 of Autodrive and settings not saving correctly.

### ISSUE THREAD

**Issue by cwattyeso** [Stephan-S/FS22_AutoDrive#579]
Have updated Autodrive to the latest version when it was released and have since discovered several rather annoying issues with the new version not present in the previous.

The first issue is that Autodrive doesn't seem to remember my user settings when loading into single player save games. What I mean by this is the Hud Size and Scaling is always reset to tiny instead of my preferred 90% settings, then within autodrive settings my other preferences such as having the the lines above the vehicle rather then on ground level are always changed, show next path is always re-enabled, as are other options such as showing keybindings in the F1 menu which I turn off.

Another issue I notice with the new version of Autodrive is that when loading into any game now, the Autodrive Hud is always open on every single vehicle by default. This is then a nusisance if you have lots of vehicles to go round and close the Hud again on all of them. Can we not have the Hud closed by default again please, as I only want to open it when I'm actually going to use Autodrive, and don't want it open everytime I load the game.

In Multiplayer I've noticed that not only do you have the same issue with the Hud being open by default on all vehicles when you log into the server, but Autodrive is also starting by default in Edit Mode, meaning all players complain about having lines and dots all over their screen, and have to manually turn off Edit Mode and then close the Hud. Again would be very nice in the next update if when playing in Multiplayer edit mode is turned off by default and players have to manually turn it on when they need it.

**Comment by DrBarnabus** [comment]
I've also run into this issue, user settings don't seem to be saving at all and boot up with the defaults every time you load into a save.

**Comment by Iwan1803** [comment]
As it is dublicated -> closed.
