### ISSUE TITLE
Abstandsregelung funktioniert bei Häckslern nicht

### ISSUE THREAD

**Issue by DarkDoldier** [Stephan-S/FS22_AutoDrive#58]
Hi zusammen!

Egal was ich einstelle der abstand bleibt gleich.  Wenn ich den Häcksler bediene oder der Standardhelfer ist das egal. Das Feature ist anscheinend wichtig in Kombi mit AIVE.  Auch haben die Abfahrer ein Komisches verhalten auf dem Feld.

Kennt jemand eine Lösung?

**Comment by Iwan1803** [comment]
Poste mal Screenshots von den Einstellungen vom Abfahrer und vom Häcksler.

**Comment by DarkDoldier** [comment]
![Farming Simulator 22 Screenshot 2021 12 22 - 21 26 37 95](https://user-images.githubusercontent.com/96529899/147151491-64f2f503-2e8f-4e23-b8ec-c188c8a6f6c3.png)
![Uploading Farming Simulator 22 Screenshot 2021.12.22 - 21.26.41.48.png…]()

**Comment by DarkDoldier** [comment]
![Farming Simulator 22 Screenshot 2021 12 22 - 21 26 41 48](https://user-images.githubusercontent.com/96529899/147151577-b6e4faa8-4af0-413d-a66a-cd5bdf2f4865.png)

**Comment by DarkDoldier** [comment]
Das ist der Abfahrer

**Comment by DarkDoldier** [comment]
![Farming Simulator 22 Screenshot 2021 12 22 - 21 27 03 99](https://user-images.githubusercontent.com/96529899/147151614-7a151013-ace9-4701-8123-7b8d0830d02b.png)
![Farming Simulator 22 Screenshot 2021 12 22 - 21 27 16 74](https://user-images.githubusercontent.com/96529899/147151629-8d18e5db-0984-4c36-b709-4aa06c520390.png)
![Farming Simulator 22 Screenshot 2021 12 22 - 21 27 17 100](https://user-images.githubusercontent.com/96529899/147151641-f59e764a-2a48-4aa0-bbe2-073566d3b139.png)

**Comment by DarkDoldier** [comment]
Das der Häcksler

**Comment by Stephan-S** [comment]
Der Abstand Häcksler wird nur genutzt, wenn wir hinter dem Häcksler fahren. Wenn wir seitlich versetzt fahren spielt der keine Rolle.
Erkläre doch bitte mal präziser was denn überhaupt das Problem ist und was deiner Meinung nach die Lösung ist.
Ein Screenshot von den beiden in Aktion wäre gut. Kannst auch geren dort dann reinmalen was du erwartest :D

**Comment by DarkDoldier** [comment]
> Der Abstand Häcksler wird nur genutzt, wenn wir hinter dem Häcksler fahren. Wenn wir seitlich versetzt fahren spielt der keine Rolle.
> 
> Erkläre doch bitte mal präziser was denn überhaupt das Problem ist und was deiner Meinung nach die Lösung ist.
> 
> Ein Screenshot von den beiden in Aktion wäre gut. Kannst auch geren dort dann reinmalen was du erwartest :D
> 
> 

Stephan danke für die super Arbeit und für deine Antwort!

Ok dann habe ich das Feature falsch verstanden ich dachte damit kommt mehr Abstand in allen Richtungen. Ist der Abstand Rohr nur für Drescher oder auch für Häcksler? Auch wenn ich den Wert hoch drehe ändert sich beim Häcksler nichts nur beim Drescher.

Ich wollte AIVE in Kreisfahrt nutzen um enge Felder mit AD zu häckseln weil beim Standard Helfer sonst AD riesige wenden in die Bäume fährt (Pfadplanung begrenzt und Abfahrer aufs Feld begrenzen habe ich probiert läuft aber auch nicht sauber auf kleinen Feldern). AIVE scheint aber immer etwas im Weg zu haben sobald der AD Abfahrer daneben steht. Dann setzt der AD Fahrer zurück es funktioniert für 3 Meter und direkt ist AIVE (Kolli Prüfung aus) wieder blockiert. Ich weiß das wird ein Problem mit AIVE sein ich hatte nur gedacht das ich es so lösen kann.
