### ISSUE TITLE
Quaderballen nicht auswählbar bei AD 2.0.0.6

### ISSUE THREAD

**Issue by kult16** [Stephan-S/FS22_AutoDrive#581]
Hi, ich spiele auf der Rostock Version 1.1 und möchte mit AD+CP Ballen automatisch sammeln und abladen lassen beim Landhandel.
Bei der Einstellung "Abholen+Abliefern" von AD werden mir Quaderballen nicht als Auswahlmöglichkeit angezeigt. Dies betrifft sowohl die ingame Ballensammlerwagen als auch einen autoload Anhänger.

Ich verwende AD 2.0.0.6 und das aktuelle Script von Achimmobil für Autoload.

Das Sammeln der Ballen und die Anfahrt bis zum Triggerpunkt funktioniert problemlos.

Hat jemand einen Tipp woran es liegen könnte?

**Comment by Tensuko** [comment]
Das ist auch nicht nötig, bei AD Quaderballen zu wählen.
Wenn du mit CP Ballen sammelst, dann stell das Script auf die Ballen ein und ab gehts (aktuell wird nicht eingeschaltet, WIP).
Was CP dann einsammelt und was AD dann transportiert sollte Banane sein...

**Comment by kult16** [comment]
Ad fährt dann aber nur zum Abladepunkt nach dem Sammeln, lädt aber nicht ab.

**Comment by Goofy78** [comment]
Den Zielpunkt weit genug hinter den Trigger setzen und NICHT im Abfahrer sitzen. Dann sollte es funktionieren.

**Comment by Tensuko** [comment]
Zum Abladen sollte aber Banane sein was geladen ist.
Auch wenn du Toast auf der Ladefläche hast sollte AD das egal sein zum abladen.

**Comment by kult16** [comment]
Ich habe ein wenig mit den Punkten gespielt und nun klappt es. Danke für die Hinweise.  Punkt kann geschlossen werden

**Comment by PhilippS1** [comment]
Hallo zusammen,
habe das selbe Problem jedoch finde ich keine Lösung. Auf der Map wurden zwei Ballen Trigger verbaut, einmal ein ganz normaler Ballenverkauf und der zweite für die BGA. Am Ballenverkaufstrigger läd AD ganz normal ab. Jedoch den BGA Trigger erkennt AD nur läd aber nicht ab, manuel kann ich dort aber abladen. Hab schon die Anfahrtsrichtung gedreht und den Wegpunkt etwar eine Fahrzeugslänge hinter das Trigger Ende gesetzt, leider ohne Erfolg. 
Siloabstand habe ich auf 50 Meter eingestellt.
