### ISSUE TITLE
Exiting vehicle with Edit mode on prevents use of middle click to obtain cursor again

### ISSUE THREAD

**Issue by andrewrooke** [Stephan-S/FS22_AutoDrive#583]
Hey, firstly, thanks for an amazing mod!

I have found a problem in 2.0.0.6 (i am also using Courseplay 7.1.0.0 - unsure if thats related) where if i exit a vehicle while in Autodrive edit mode, I lose the ability to obtain my cursor again by pressing middle click on the mouse.

When I bind a key bind for Edit mode, repeat the above, but turn on then off edit mode again, i can once again middle click to obtain the cursor.

**Comment by Iwan1803** [comment]
You've got a mouse pointer outside of a vehicle? 🤔🤨

**Comment by Tensuko** [comment]
Default should be right click to only move the notification window.
Not sure for what else you need that Mouse Cursor outside a vehicle.

**Comment by andrewrooke** [comment]
I understand your comment now @Iwan1803  - The mouse cursor can not be obtained after i have re-entered the vehicle, if i exited the vehicle while AD Edit Mode was enabled. The same issue occurs if i switch (tab) through vehicles when i have AD Edit Mode enabled.

The work around is to have a key bind for AD Edit mode, which i enable and disable via key binding. I can then use middle mouse to access the cursor and interact with the AD console again (or the CP console).

@Tensuko I have no idea what you mean.

**Comment by Iwan1803** [comment]
For leaving the vehicle while in edit mode there was a change in 2.0.0.9. So you should try the latest version: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
