### ISSUE TITLE
Blocked by water (ford) and bridges

### ISSUE THREAD

**Issue by onehandclapping** [Stephan-S/FS22_AutoDrive#584]
In my specific case this is Calmsden Farm map where there is a ford across a shallow river between fields 9 and 12. I've tried various bridges but AD will not cross them and (obviously) will not drive through the ford (though water seems less of a problem in FS22 than FS19). Can understand not driving through water even if it is a fording point but not sure why the bridges won't work (debug shows nothing to my ignorant eye).  Is AD seeing bridges as a collision?

Maybe just ignore water if the user has placed waypoints in it? After  it's then my fault if a vehicle drowns.

**Comment by Iwan1803** [comment]
Maybe the bridge has an unneeded collision box. Which bridge is it? Is it a mod?

**Comment by onehandclapping** [comment]
Sorr, but this is so long ago I cannot remember which bride I was using but I do recall that I tried several with no luck. In the end I created a different route. Maybe if AD would actually just drive through water? After all if a user puts a route through water then it's their responsibility.

**Comment by Iwan1803** [comment]
So we can't do any further ivestigations and driving through water without knowing how deep it is sounds not like a good solution.
