### ISSUE TITLE
Unloading combine

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS22_AutoDrive#586]
I guess as no one else has mentioned this im the only one with the problem.

When the AD tractor has emptied the combine it continues running alongside the combine, Its like it fails to recognise the combine is empty.
![20220623172123_1](https://user-images.githubusercontent.com/11178621/175349105-fa2d2048-8fc7-4f7a-a676-c696de3f147c.jpg)

Ive tried both modded and vanilla tractors but always have same issue.

Im on PC, Green Valley and 2.0.0.6

**Comment by Tensuko** [comment]
> I guess it may be issue with courseplay

It's not. AD checks the combine filllevel, not CP.

**Comment by rohne83** [comment]
check your AD combine settings (guess the second page of AD settings menue). You have to deactivate the setting for "active unloading" otherwise your unloader will stay under the pipe until he is full.

**Comment by venquessa** [comment]
There is a related bug however.  When a combine is set to allow active unloading, but has stopped in the field already, AD will drive along side, start to unload the combine, but as soon as the combine moves it shuts the covers and drives off (in front of the combine usually) or goes back to "waiting on call" (in front of the other combine usually)  (sorry for sarc :) )

**Comment by Axel32019** [comment]
> There is a related bug however. When a combine is set to allow active unloading, but has stopped in the field already, AD will drive along side, start to unload the combine, but as soon as the combine moves it shuts the covers and drives off (in front of the combine usually) or goes back to "waiting on call" (in front of the other combine usually) (sorry for sarc :) )

This is a differnt topic.

**Comment by Axel32019** [comment]
> There's no issue, that works as designed. Check your AD combine settings (guess the second page of AD settings menue). You have to deactivate the setting for "active unloading" otherwise your unloader will stay under the pipe until he is full.

Correct - no bug
