### ISSUE TITLE
Streckenerstellung auf Dedi nur für Admin??

### ISSUE THREAD

**Issue by Chaosfamily1207** [Stephan-S/FS22_AutoDrive#588]
Hallo, könnte man eine Funktion einfügen wo man das Streckenerstellen nur Spielern mit Admin Passwort ermöglicht macht?

**Comment by Tensuko** [comment]
Ich muss bei sowas immer fragen: Warum ?
Kannst du deinen Mitspielern nicht vertrauen, dass die das Streckennetz in Ruhe lassen und ggf nur bei sich etwas ändern ?

**Comment by Chaosfamily1207** [comment]
Doch ich kann meinen Mitspielern vertrauen. Aber es gibt leider auch Leute die es einfach nicht können und davon sind auch immer mal welche dabei die meinen das sie es können.  Des weiteren haben wir auch schon gehabt das jemand angeblich unwissentlich die Streckenaufzeichnung an hatte und dann einmal über die ganze Map und einige Felder Kurse aufgezeichnet hat. Ich mag solche Schritte auch nicht gerne, aber wenn man sich die Arbeit macht und eine komplette Map einfährt und dann kommt einer mit wenig Ahnung und naja ....
