### ISSUE TITLE
Helfer - kein Feld gefunden

### ISSUE THREAD

**Issue by Gramthug** [Stephan-S/FS22_AutoDrive#59]
aus dem AD-Discord:

hey leute, ich hab autodrive für den ls22 bei meinem vater installiert und wir haben das problem, dass der helfer nicht arbeiten will. sobald der aktiviert wird, erscheint rechts oben die Meldung, dass er das Feld nicht gefunden hat. ich habe eine menge probiert, von neuem savegame, alle mods bis auf autodrive raus etc pp. Aber irgendwie funktioniert er einfach nicht. sobald ich AD rauswerfe, funktioniert auch der helfer. habt ihr eine idee was das sein könnte?

grüße Gramthug

![ls22-kein-feld-gefunden](https://user-images.githubusercontent.com/96532817/147101766-2b57bf07-7fd4-4dca-97e9-31e37afca5ad.jpg)

**Comment by Iwan1803** [comment]
Auf welcher Map passiert das? Stand das Fahrzeug bei allen Tests immer an der gleichen Stelle auf dem Feld?
Logfile? Screenshots? Weitere Infos?

**Comment by Gramthug** [comment]
Hi Iwan,

aufgrund der Fragestellung nehme ich an, dass unser Problem nicht irgendwas Bekanntes ist. Ich installiere das Game jetzt erstmal neu bei ihm und wir werden es erneut testen. Sollte das wieder scheitern, versorge ich dich mit der Log-Datei und Screens oder Videos.

**Comment by Iwan1803** [comment]
"Kein Feld gefunden" hatte ich auch schon sehr oft mit dem Standardhelfer - sowohl mit als auch ohne AD. Meist lag dies aber daran, das das Fahrzeug zu dicht am Feldrand lag.
Lad am besten gleich mal die aktuelle 2.0.0.1 runter und dann bin ich mal gespannt, was bei rauskommt.

**Comment by Gramthug** [comment]
Aktuell scheint alles zu funktionieren. Ich habe wie gesagt das Spiel neuinstalliert, die frische AD 2.0.0.1 installiert und laut meinem Vater hat es auf den Standard-Maps geklappt. Er wird jetzt noch seine Mod-Maps testen. Danke soweit für den Support. Wenn wir weitere Probleme haben, melde ich mich (mit Logs, Screens etc.) zurück. 

Übrigens soll ich von meinem Vater ein großes Danke und Lob aussprechen. Er hat mich heute verzweifelt angerufen, weil er nicht weiter kam und bat mich darum, Euch direkt zu kontaktieren. Der gute Mann ist 70 Jahre alt und - seitdem er keine Nerven mehr für Courseplay hatte - ein riesen Fan von Euch der praktisch jedes Video von Euch aufsaugt. Klasse was ihr da macht!

**Comment by Iwan1803** [comment]
AD ist fürs Fahren, CP für die Feldarbeit und beide arbeiten wunderbar zusammen 😉
Grüße und Respekt an deinen Vater, das er sich in dem Alter mit solchen Themen überhaupt auseinander setzt 👍
Das kenne ich leider von anderen anders....

Sollte noch was auftauchen, dann einfach ein neues Issue aufmachen oder im DC vorbeischauen.
