### ISSUE TITLE
Abladen im Keilsilo

### ISSUE THREAD

**Issue by xerion8300** [Stephan-S/FS22_AutoDrive#590]
Hallo wenn ich Rückwärts im Keilsilo ablade, und er fertig ist fährt er vorwärts aus dem Silo, und dann fährt er wieder zurück ins Silo. Danach fährt er erst wieder aus dem Silo und fährt zum Feld zurück. Ist das normal, oder mach ich da was falsch.

**Comment by Iwan1803** [comment]
Wie sollen wir das beurteilen, ohne einen Screenshot vom AD-Netz zu haben?
Vielleicht hilft das Howto hier weiter: https://www.youtube.com/watch?v=h9HxOlC9hPQ

**Comment by xerion8300** [comment]
Danke werde mal das vom Video anwenden, wenn es dann nicht geht werde ich mich wieder Melden mit Sceens

**Comment by eric4072** [comment]
das passiert nur, wenn der Abfahrer als erstes die Linie erkennt, welche zum anfahren vorm Silo liegt. wenn du den Punkt, wo er zum rücksärtsfahren beginnt, mit der Strecke, welche aus dem Silo fürhrt, verbindest, kommt das nie wieder vor ;-)

**Comment by xerion8300** [comment]
Kannst du mir einen Screen machen, Dann würde ich mir leichter tun.
Im voraus schon mal Danke

**Comment by eric4072** [comment]
![Farming Simulator 22 Screenshot 2022 07 02 - 18 49 49 03](https://user-images.githubusercontent.com/60355129/177009465-67bdd95b-d668-4ee3-b59d-71c9765a9402.png)
ich habe z.B. nur eine Ausfahrtslinie und schließe alles drann...

funktoniert einwandfrei

**Comment by Iwan1803** [comment]
Warum nicht der Trick mit der blauen (in beide Richtungen befahrbaren) Linie? Dann spart sich mich Linien und vor allem diese Probleme (siehe oben verlinktes Video).
