### ISSUE TITLE
nach Einparken mit Anhänger Zielpunkte nicht anfahrbar

### ISSUE THREAD

**Issue by Xetras** [Stephan-S/FS22_AutoDrive#591]
Hallo,

ich habe mir auf der Elmcreek einen größeren Parkbereich eingerichtet. Dabei ist ein Problem aufgetaucht welches ich nicht gelöst bekomme. Ich habe einem Anhänger einen Parkplatz zugewiesen und ihn einparken lassen. Das funktioniert auch super. Leider kommt er von dort aber nicht mehr weg. Ich bekomme die Meldung "Kein Weg gefunden" (in meinem Fall zum Fahrzeughändler). 
Mach ich das ganze nur mit Traktor fährt er sauber Parken und von dort problemlos zum Fahrzeughändler.  
Ich hab mal ein paar Bilder zur Ilustration gemacht. Anbei ebenso die Errorfreie Log.
Jemand eine Idee wo der Fehler liegt? Danke im Voraus
 
![Ankunft mit Hänger](https://user-images.githubusercontent.com/108406229/176432533-6f3de99d-d487-48d4-922c-664cb9a46baf.jpg)

![Weiterfahrt mit Hänger](https://user-images.githubusercontent.com/108406229/176432657-80e1c2d3-5d9b-4f40-a350-ecaa5a552778.jpg)

![Ankunft ohne Hänger](https://user-images.githubusercontent.com/108406229/176432707-b3959822-7827-4c63-8972-429974fd2587.jpg)

![Weiterfahrt ohne Hänger](https://user-images.githubusercontent.com/108406229/176432746-1d65c839-4d80-4f3a-b5f7-864b780239ff.jpg)

![Eintsellungen 1](https://user-images.githubusercontent.com/108406229/176433008-182e1d25-06db-45bb-82c1-ce004cbd9b3a.jpg)

![Einstellungen 2](https://user-images.githubusercontent.com/108406229/176433036-02d01a0e-058e-48fc-9ca8-e782df8f45c1.jpg)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9010314/log.txt)

**Comment by hermannbrauer** [comment]
du musst die Punkte für den weg wieder auf die Strecke weiter vorm Trecker setzen... der erkennt einfach nicht das er gleich links auf die Spur muss weil die zu dicht dran ist!
