### ISSUE TITLE
AD hängt sich auf beim Ballen sammeln und abfahren

### ISSUE THREAD

**Issue by Xetras** [Stephan-S/FS22_AutoDrive#596]
Hallo,
habe gerade versucht AD (in Zusammenspiel mit CP) mit dem Ballen sammeln und abfahren (gewickelte Silageballen)  auf einem meiner Grasfelder zu beauftragen. Dabei hängt sich AD komplett auf. Zusätzlich lässt sich das CP-Fenster nicht mehr öffnen und das F1-Hilfefenster lässt sich nicht einblenden. 
Spiele auf der Elmcreek mit der neuesten AD-Version (Problem trat allerdings schon mit der Vorgängersversion auf).

Bis zu diesem Vorgang war die Log fehlerfrei. 
Anbei die Log.

Danke schon mal für die Hilfe

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9031407/log.txt)

**Comment by Iwan1803** [comment]
Vielleicht solltest du CP mal aktualisieren, weil die sind schon bei 7.1.0.0:
https://github.com/KillBait/AutoDrive_Course_Editor/releases

**Comment by Xetras** [comment]
Hab ich gemacht. Fehlerbild ist das selbe. 
gewickelte Ballen liegen auf Feld 71 der Elmcreek. Es existiert ein AD-Wegpunkt auf dem Feld. Konnte den Auslöser jetzt aber noch weiter eingrenzen. 
Hier ein paar Bilder. Zunächst die Ausgangssituation. Abholpunkt und  Ablieferpunkt sind eingegeben. CP- Fenster und Hilfemenü ebenso offen.
![20220702133053_1](https://user-images.githubusercontent.com/108406229/176999131-d12c32eb-2cbd-4b79-897f-eb3e1f10f5d7.jpg)
Klick ich in die Zeile wo ausgewählt wird was abgeholt/geliefert werden soll ist nichts wählbar. 
![20220702133058_1](https://user-images.githubusercontent.com/108406229/176999181-9eebc1d9-08d2-470c-84ac-69c234f3e647.jpg)
Wenn ich dieses eigentliche Auswahlfenster wieder schließe geht das CP-Fenster und das Hilfe-Menü zu und die Log wird mit Errors gefüllt. Das sieht dann so aus
![20220702133102_1](https://user-images.githubusercontent.com/108406229/176999222-a3bcaa1f-0994-4e3a-b5e4-4d276836042f.jpg)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9032946/log.txt)

**Comment by Xetras** [comment]
Hab jetzt mal testweise einen neuen Spielstand erstellt. Alle Mods, außer AD und CP, runter geworfen. 
Das Problem trat auch hier auf.  Ich sitze im Traktor ohne irgendeinen Anhänger. Sobald ich den Modus "Abholen und Abliefern" öffne kann ich noch einstellen wo er holen und wo liefern soll. Sobald ich in die Zeile gehe in der ich das Produkt auswähle fährt sich das ganze fest bzw. die beschriebenen Symptome treten auf.

**Comment by regs1980** [comment]
Komischerweise ist es nur bei dir, weder schreibt er bei mir Fehler in den log noch habe ich nicht dieselben Symptome. 
Ich habe es mit beiden Ballensammelwagen probiert, keiner macht was Derartiges.

![2022-07-03 02_12_03-Greenshot](https://user-images.githubusercontent.com/13314443/177019807-e00966a0-1ba8-4ea3-9995-0cf45e9f5ff9.png)
![2022-07-03 02_12_07-Greenshot](https://user-images.githubusercontent.com/13314443/177019808-fa657e97-8f4b-4196-a3ea-3ddf2deee151.png)
![2022-07-03 02_20_39-Greenshot](https://user-images.githubusercontent.com/13314443/177019909-6ebe7bd1-4f1f-4868-97a6-eea73100364b.png)
![2022-07-03 02_20_46-Greenshot](https://user-images.githubusercontent.com/13314443/177019910-2c6a0b66-e156-4aaf-9836-60581ae6b62d.png)

**Comment by Xetras** [comment]
Wie ich direkt über deinem Post geschrieben hab, habe ich das Ganze in einem neuen Save durchgespielt. 
Um sicher zu gehen heute das Game komplett von der Platte gehauen. Neu installiert, lediglich AD und CP, als Mods drauf (auch diese beiden nochmal in der aktuellsten  Version gezogen). Im neuen Save auf der Elmcreek einen kleinen Rundkurs Feld- Silo eingefahren. Selbes Spiel. Solange ich wie auf deinen Bildern zu sehen nur den Abhol- und den Ablieferpunkt einstelle läuft alles. Kann den Job auch normal starten und er macht was er soll. Sobald ich mich an der 3. Zeile, der Produktauswahl, im AD- Fenster vergreife hängt sich AD auf bzw. die beschrieben Symptome treten auf (incl. der Unmengen an Errors in der Log).

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9034874/log.txt)

**Comment by regs1980** [comment]
FS22_siloWood, das raus aus dem Ordner und mal einen Verkaufstrigger ansteuern.

**Comment by Xetras** [comment]
Hat sich nicht geändert. Silo komplett raus (auch aus Modordner). Stattdessen Viehhändler als Verkaufstrigger. 
Keine Änderung

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9035019/log.txt)

**Comment by regs1980** [comment]
Konnte den Fehler jetzt auch reproduzieren. 
Hier kann man drücken wie man will passiert nicht. 

![2022-07-03 17_33_02-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/177046805-29dbb51c-1aa0-4c30-b279-07e081852cbd.png)

So bald man aber in der Höhe drückt, wo die andere Zeile darunter ist,

![2022-07-03 17_34_43-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/177046854-23cb7ddd-2de1-41b5-bca3-d482876a84c4.png)

passiert genau das, dass HUD verschwindet

![2022-07-03 17_34_52-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/177046874-5992d809-b4c5-46ff-b1c6-62c9a4527d19.png)

**Comment by Xetras** [comment]
genauere Beschreibung? Also Bitte, ich rede seit gestern vom Klick in die 3. Zeile zur Fruchtauswahl! (seit ich es selbst darauf eingrenzen konnte). 
Aber schön das es jemand nachbilden konnte
