### ISSUE TITLE
Drescher Collibox verständnis

### ISSUE THREAD

**Issue by RealNeo80** [Stephan-S/FS22_AutoDrive#600]
wieso sitzt die Colli bei dem Lexion 8900 soweit rechts und blockt mir den obwohl vor der halle Platz wäre?

![image](https://user-images.githubusercontent.com/8066324/177043672-7eb8b505-b29a-40f8-9355-81a8cd46e1ec.png)

**Comment by Iwan1803** [comment]
Modfahrzeug oder Vanilla?

**Comment by RealNeo80** [comment]
vanilla

**Comment by Iwan1803** [comment]
Ich habe es gerade bei mir mit einem Vanilla Claas 8900 getestet und sowohl die Ingame- als auch AD-Kolliboxen sitzen da, wo sie hingehören. Könnte es vielleicht sein, das dort etwas in der Halle ist oder steht, was diese Box erzeugt?

Btw. was lässt du dir da überhaupt anzeigen?

**Comment by RealNeo80** [comment]
ich hab die debug sensoren an, aber normal darf der doch da net stehenbleiben. Kollisionserkennung hab ich aus

**Comment by Iwan1803** [comment]
Und nochmal: ist das wirklich die vom Drescher oder von etwas, was in der Halle steht?
Ich kann alle Debugs einschalten und hab mit dem Vanilla-Claas keine solche Box-Anzeige.

**Comment by RealNeo80** [comment]
alles gut, aber ja das ist Vanilla und ich habe beim Drescher die Sensoren eingeschaltet, dann habe ich diese 2 boxen rechts, sobald ein Schneidwerk dranhängt sind die links, bzw beidseitig. Sobald ich noch den Kollissionsbutton im AD einschalte habe ich auch die box vorne dran

**Comment by regs1980** [comment]
Die zwei Boxen sind für das Rohr.
 
Transportmodus mit eingeklappten Rohr

![2022-07-06 07_52_33-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/177484167-b1ebdf6c-f4ec-4c70-8b9e-a34fc4e13da8.png)

Arbeitsmodus mit ausgeklappten Rohr

![2022-07-06 08_30_37-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/177484306-0bc1711a-802a-4825-9217-01876b569f81.png)

Das ist die Kollisionsbox vom Drescher

![2022-07-06 08_23_56-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/177484481-b29d7618-0231-40c9-9c44-b639ce8f0b3e.png)

@RealNeo80 Ist zufällig ein aktiver AD Fahrer noch auf deinen blauen Linien unterwegs, der den Drescher zum Anhalten zwingt.
Die Triggerbox vom Rohr lässt den Drescher nicht stoppen, selbst wenn da ein aktiver AD Fahrer an einer Seite ist.

![2022-07-06 08_20_10-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/177485130-0c9b90c0-f949-4f0f-bbe8-d3f7a8d9f97d.png)

**Comment by RealNeo80** [comment]
nein der Fahrer wars net, es war die Collibox von dem Nardi Schneidwerkswagen. ich hab die Deichsel zwar umgeklappt, aber die colli ändert sich damit anscheined net. hab ich aber erst gesehen nachdem ich den vollen debug eingeschaltet hab
