### ISSUE TITLE
Function - Avoid collision

### ISSUE THREAD

**Issue by Myiamoto86** [Stephan-S/FS22_AutoDrive#604]
Dear,

Good afternoon. The "avoid collision" function, when activated, vehicles are colliding head-on in situations where the lane is two-way (using the dots with the connecting lines in purple), and when deactivated, vehicles simply stop one in front to the other and are on hold.

In FS19, the latest versions this functionality was perfect. In the same condition mentioned above, when the mod detected collision between vehicles, a small adjustment was made and none of the vehicles collide. This is fantastic for maps where the lane is two-way and doesn't have much of an option to manually avoid this by the player.

**Comment by Iwan1803** [comment]
There is no difference in that function between FS19 and FS22. AD has never swerved to avoid other vehicles by leaving the lane.

**Comment by KCHARRO** [comment]
Who I remember that went out of line to avoid collisions in FS19 was CoursePlay.

**Comment by Myiamoto86** [comment]
The issue is, before in fs19, when the vehicles were close, two possibilities occurred:
1 - If there was, one of the vehicles took another path that was not too far away.
2 - When there was no possibility of altering the route by another path, when the two vehicles were close, they decreased their respective speeds and arrived a little to the right each one, thus avoiding the collision. After they passed each other, they adjusted their route and headed for their destination.

On maps with dirt road, I configured AD a lot using the purple line between the points and it worked very well... This was one of the reasons that made me really like autodrive in fs19 along with course play. Sometimes it made some very crazy but tolerable errors.

If possible to come back with this functionality, it would be very good. Even on lanes with two lanes, one way and the other, if it's a little narrow, the vehicles are colliding, even with the collision avoidance mode active...

**Comment by Axel32019** [comment]
The kind of collision avoidance only happen on fields, not on roads.
