### ISSUE TITLE
Härtetest für die Lenkung ??

### ISSUE THREAD

**Issue by WernerWusel** [Stephan-S/FS22_AutoDrive#605]
Da hat der Programmierer wohl einen schlechten Tag gehabt. Sowas muss bestimmt  nicht sein. Ist nur beim Drescher abtanken so.

https://vimeo.com/726749464

**Comment by regs1980** [comment]
Das ist alles korrekt so, AD versucht den Entladeabstand einzuhalten der eingestellt ist. Da sind Lenkkorrekturen nicht ausgeschlossen.

**Comment by WernerWusel** [comment]
Wenn der Drescher ohne wilde Lenkbewegungen fährt,, und das macht er, wird sich der Entladeabstand wohl nicht ändern. Also ist nichts korrekt. Und Lenkkorrekturen sind was anderes als diese wilden Lenkbewegungen.

**Comment by regs1980** [comment]
Weißt du was man im Script umschreiben muss das es besser wird?
Beeinträchtigt es die Funktion des Entladezyklus?
Ist also rein eine optische Sache, die dir nicht gefällt?

**Comment by WernerWusel** [comment]
1. Ja. Kennst du SPS ?
2. Jain ! Kennst du Force Feedback ?
3. Ja. Weißt du, das alle neueren Spiele nur aus Optik bestehen? Wenn du keine Optik haben willst, nimm ein Text Adventure. Ich hab eine 1000€ Graka im PC. Daher steh ich voll auf Optik.

**Comment by regs1980** [comment]
Wenn du weißt, wie man das beheben kann, dann feuer frei. Glaube mal nicht das die Jungs von AD, da was dagegen hätten, wenn es funktioniert.

**Comment by Iwan1803** [comment]
@WernerWusel so Sprüche kannst du dir echt sparen und daher mach ich hier auch zu, denn sowas ist einfach nur eine Frechheit.
