### ISSUE TITLE
Abstand zum voraus fahrenden Fahrzeug

### ISSUE THREAD

**Issue by xerion8300** [Stephan-S/FS22_AutoDrive#608]
Ist es möglich das ich den Abstand einstellen kann zum voraus fahrenden Fahrzeug.
Wenn das Fahrzeug in den Felld abbiegt und auf Wartepunkt fährt, fährt das nächste hinterher und blockiert die Straße.
Andere Fahrzeuge sind dann Blockiert.
Wenn man den Abstand einstellen könnte würde er auf seiner Seite warten.
![fsScreen_2022_07_07_18_06_41](https://user-images.githubusercontent.com/25564472/177827886-4dba4ced-5c82-4ca2-9b6d-6017abfca809.png)

**Comment by regs1980** [comment]
Einfach mit 2 Wege Linien arbeiten.

**Comment by xerion8300** [comment]
Gut ich zeig dir mal meine Kreuzung. Was soll ich dann da ändern?
Kenn mich da auch nicht so gut aus.

[fsScreen_2022_07_11_11_56_18](https://user-images.githubusercontent.com/25564472/178244666-487e2cb4-13bb-46d8-b88e-4b8f9df26664.png)
?

**Comment by regs1980** [comment]
Deine Felder haben doch nicht nur eine Einfahrt, wenn doch das Straßennetz neu überdenken.
Was das für eine Map und den passenden AD Kurs.

**Comment by xerion8300** [comment]
Die Mappe ist die FS22_MecklenburgLakeDistrict_crossplay und der AD Kurs  ist siehe Anhang
[AutoDrive_config.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/9101964/AutoDrive_config.zip)
g

**Comment by regs1980** [comment]
Jedes Feld hat mindesten zwei Ausfahrten, über das ganze Netz würde ich noch mal nachdenken, ist zu viel blau. Lieber ein paar Einbahnstraßen und ein Gespann 1 Minute länger fahren lassen, als zu viel blau.
Dadurch kann man auch den Kurs so planen und legen, dass man den Gegenverkehr nicht behindert.

![2022-07-14 11_06_46-AutoDrive Course Editor 1 0 3 - C__Users__bob__Desktop_AutoDrive_config_AutoDriv](https://user-images.githubusercontent.com/13314443/178949114-007da459-9256-4f23-84f0-83467cc058e3.png)

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
