### ISSUE TITLE
Benutzereinstellungen speichern

### ISSUE THREAD

**Issue by sastno** [Stephan-S/FS22_AutoDrive#609]
Ich habe die Version 2.0.0.7.
In dieser Version sollte AD die Benutzereinstellungen im HUD wieder speichern. Bei mir macht er das zum Teil nicht.

Wenn ich die Einstellung "Abholen und Liefern" mit einer Fruchtart eingestellt habe, die AD verkaufen/transportieren soll, so habe ich beim nächsten Neustart des Spieles an Stelle statt meiner gewählten Fruchtart immer wieder die Einstellung "Weizen" drin.

**Comment by Axel32019** [comment]
@sastno  Kann es sein das am Traktor ein Gewicht gekoppelt ist?

**Comment by sastno** [comment]
Ich habe an allen Traktoren ein Frontgewicht dran.
