### ISSUE TITLE
lua fehler beim sync.

### ISSUE THREAD

**Issue by andremeyer123** [Stephan-S/FS22_AutoDrive#61]
Beim syncen auf einem  dedi server bekommt man lua fehler bis man den ad fahrer abstellt 
auf dem server sind keine fehler , die Spieler die schon auf dem Server sind bekommen auch keine .
dataS/scripts/vehicles/specializations/AIJobVehicle.lua(480) : attempt to index local 'currentHelper' (a nil value)
2021-12-22 17:07 Error: Running LUA method 'draw'.
dauerhaft bis ad abgestellt wird  
mfg

**Comment by Iwan1803** [comment]
Aktuellste Version 2.0.0.1? Falls nicht, bitte erstmal aktualisieren und dann noch mal testen.
Wenn der Fehler noch mal auftritt, wäre eine genaue Beschreibung, wann der Fehler auftritt sowie die Logs vom Client und Server hilfreich.

**Comment by andremeyer123** [comment]
Auf beide versionen  Fehler kommt beim verbinden (snc) auf einem server, server log ist sauber reiche die log nach wenn ich wieder sync mache .

**Comment by andremeyer123** [comment]
top arbeit fehler ist jetzt weg.

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
