### ISSUE TITLE
question can autodrive dump on the ground where there is no trigger?

### ISSUE THREAD

**Issue by shadow250** [Stephan-S/FS22_AutoDrive#611]
im trying to get it to work with the stone picker and courseplay to gather stone then take the full picker to a spot in front of a conveyor which will put the stone in a trailer. it picks up the stone but wont dump it by the conveyor.

**Comment by andreasthu** [comment]
You can use this mod as workaround:
https://forbidden-mods.de/filebase/file/35085-f%C3%B6rderband-sl80-22-quantum-mit-autodrive-ladetrigger/
Autodrive drigger inside and worker dont stop if you leave the conveur.
Lg
Andreas

**Comment by Iwan1803** [comment]
Dublicate to #670
