### ISSUE TITLE
File count per store item too high. 295 found (max. 128)

### ISSUE THREAD

**Issue by outraj3** [Stephan-S/FS22_AutoDrive#612]
Hi - I apologise in advance if I've missed something, however since yesterday AutoDrive is showing an active Issue on our Gportal Server (screenshots attached) before yesterday it was working perfectly, have we done something wrong?

![Screenshot 2022-07-09 193056](https://user-images.githubusercontent.com/108997226/178118549-039949ec-3cb8-4ca2-9ac7-c7bb558649a0.png)

![Screenshot 2022-07-09 193015](https://user-images.githubusercontent.com/108997226/178118552-85caac7e-833f-490a-90d4-9180f0d549e7.png)

**Comment by Tensuko** [comment]
Can be ignored.
