### ISSUE TITLE
Verbesserungsvorschlag - AD Fenster verschieben nur noch wenn Editor Modus aktiv

### ISSUE THREAD

**Issue by blubstar86** [Stephan-S/FS22_AutoDrive#613]
Moin,

kleiner Verbesserungsvorschlag.

Das AD Fenster nur noch verschieben können wenn der Editor Modus aktiv ist.

Vorteile:
Kein versehentliches verschieben des Fensters im normalen betrieb.

Grüße

**Comment by haamic** [comment]
Mich würde mal interessieren, wodurch passiert es dir denn, das das Fenster versehentlich verschoben wird? 🤔
Ich spiele seit Jahren mit AD und es ist mir noch nie passiert. Und wenn, dann schiebt man es einfach wieder zurück.

**Comment by blubstar86** [comment]
In dem man an einer falschen Stelle klickt und dann auch noch zu lange die Maustaste gedrückt hält und dabei die Maus bewegt.
Schön zu hören das es dir noch nie passiert ist.

Gerne auch als ein Art "Schlosssymbol" lock/unlock in der Statuszeile, am besten gleich noch für CP.
![image](https://user-images.githubusercontent.com/47928255/178161228-5a16a73e-f7db-4a5a-8a8e-fa665c1b366b.png)

Kann ich Tensuko hierauf irgendwie aufmerksam machen, in Bezug auf CP oder muss ich für CP ein neuen Verbesserungsvorschlag erstellen, kenne mich mit GitHub nicht so wirklich gut aus? 
Danke

**Comment by Tensuko** [comment]
Das Problem kann ich auch nicht ganz nach vollziehen.....
Ist mir noch nie passiert...
