### ISSUE TITLE
Dedicated Server Issue with base game Kaercher washer unit.

### ISSUE THREAD

**Issue by dezza69** [Stephan-S/FS22_AutoDrive#615]
Hi,

Found an issue today using FS22_AutoDrive development version 2.0.0.7 on my private dedicated server.

... went to use the base game Kaercher washer - owned by a fourth farm - as a player who had 3 other farms vehicles/trailers together on a flatbed all needing a bath.  After washing them I couldn't enter a different (unwashed) vehicle elsewhere on the map owned as/by the player who washed everything.  The unenterable vehicles icon changed from a vehicle to a tool on the ingame map.  Farms all have contract access to each other, there's no other issues that I'm aware of and can supply multiplayer save game if needed.

Found this in the dedicated server's game log whilst investigating not being able to enter the tractor, so stopped and restarted it...  Really not sure if it's related to not being able to get back in the vehicle, but thought you may need to know. Or not ... lol!

edit: probably important to note that AutoDrive had/has not been used at all during this player or continual server session since last restart, all vehicles were manually driven.

Thanks heaps for your awesome mod.

2022-07-12 15:43 Game saved successfully.
2022-07-12 16:12 data/placeables/kaercher/hds9184M/firstPerson/hds9184MLance.i3d (120.14 ms)
2022-07-12 16:20 Error: Running LUA method 'packetReceived'.
C:/Users/<<user_name>>/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/CollisionDetectionUtils.lua:289: attempt to index field 'ad' (a nil value)
2022-07-12 16:23 Game saved successfully.
2022-07-12 16:23   Info: [AD] ADUserDataManager: saved data for 2 users

**Comment by Axel32019** [comment]
dev version
