### ISSUE TITLE
Streckenpunkte editieren

### ISSUE THREAD

**Issue by Toaogurch** [Stephan-S/FS22_AutoDrive#616]
Hallo zusammen,
ich versuche diverse Streckenpunkte zu verschieben etc. aber es funktioniert nicht. Ich spiele, vielleicht ist es wichtig auf OS Monteray. Beim LS19 habe ich die rechte Maustaste gedrückt und ich konnte die Punkte verschieben. 
Was mache ich falsch?

Mein Englisch ist nicht besonders gut....!

**Comment by TobiHH78** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-Tastenkombinationen

Man muss im Editor-Modus sein!

Wegpunkte
**im Editor-Modus:**

Wegpunkte ein-/ausblenden: RSTRG drücken
einzelnen Wegpunkt erstellen: LSTRG + LMB
automatisch bei Erstellung verbinden: LSTRG halten + LMB
verbinden: grüne Linie: LMB auf 1. Punkt, LMB auf 2. Punkt
verbinden: blaue Linie: LMB auf 2. Punkt, LMB auf 1. Punkt
verbinden: hellblaue Linie (rückwärts): LMB auf 1. Punkt, RShift + LMB auf 2. Punkt
verbinden: orangene Linie: LMB auf 1. Punkt, LShift + LMB auf 2. Punkt
verbinden: braune Linie: LMB auf 2. Punkt, LShift + LMB auf 1. Punkt
Wegpunkt-Prio ändern: LShift + LMB auf Wegpunkt
Wegpunkt löschen: LALT + LMB auf den Wegpunkt
Wegpunkt verschieben: mit RMB greifen, dann verschieben und RMB am neuen Ort loslassen
Wegpunkt verschieben und Höhe beibehalten: mit RMB greifen, LShift drücken und halten, dann erst den Wegpunkt verschieben
Wegpunkte zwischen 2 Kreuzungen ändern -> Priorität ändern: 1. LMB auf Kreuzungspunkt, 2. LShift + LMB auf 1. Wegpunkt hinter der Kreuzung
Wegpunkte zwischen 2 Kreuzungen ändern -> Richtung ändern: 1. LMB auf Kreuzungspunkt, 2. LSTRG + LMB auf 1. Wegpunkt hinter der Kreuzung
Wegpunkte zwischen 2 Kreuzungen löschen: 1. LMB auf den Kreuzungspunkt, 2. LShift + LSTRG + LALT + LMB auf 1. Wegpunkt hinter der Kreuzung
Kurve zwischen 2 Wegpunkten: LMB auf Wegpunkt, mit dem Mauszeiger auf den anderen Wegpunkt zeigen, Mausrad drehen bis die gewünschte Kurve erreicht ist und dann LMB auf den Wegpunkt
