### ISSUE TITLE
Anbaugeräte klappen nicht ein wenn CP unterbrochen wird.

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS22_AutoDrive#618]
Hi, , ich hab festgestellt wenn ich CP bei einem laufenden Kurs abbreche, z.b. weil Auftrag fertig, und ich manuell AD sage er soll zum Parkplatz fahren, das Anbaugerät nicht zusammengeklappt wird. Schalte ich das Fold Impl. aus und dann wieder an, klappt er es ein und fährt dann los. Bug oder Server Problem ? Und kann dieser Fehler in der Server Log auch damit zu tun haben. Ich weiß nicht wie der zustande kommt. 
Server log beigefügt.

LG Timmi
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9105346/log.txt)

**Comment by rohne83** [comment]
Ähnliches Problem hab ich immer mit dem Arcusin FSX 6372 Ballensammelwagen (Vanilla). Zunächst fährt die bei mir immer erstmal auf dem Kurs der Presse. Wenn voll wird normal an AD übergeben um zur Abladestelle zu fahren, kommt allerdings nicht weit, da AD das Gerät nicht einklappt. Aber auch wenn man AD entlässt kann man das Gerät dann nicht mehr einklappen.

**Comment by regs1980** [comment]
@rohne83 Du stellst bei CP Ballen sammeln einen Kurs ein, anstatt den Ballensammelwagen die Ballen selbst suchen zu lassen ganz ohne Kurs?
CP kann Ballen auch selbständig suchen ohne Kurs und übergibt dann an AD.

**Comment by rohne83** [comment]
> @rohne83 Du stellst bei CP Ballen sammeln einen Kurs ein, anstatt den Ballensammelwagen die Ballen selbst suchen zu lassen ganz ohne Kurs? CP kann Ballen auch selbständig suchen ohne Kurs und übergibt dann an AD.

Der CP-Mode 7 ist hilfreich auf kleinen Feldern und zum Einsammeln der Reste, aber definitiv nicht auf großen Feldern mit mehreren hundert Ballen. Da kommt man immer besser erstmal den Kurs der Presse abfahren zu lassen. Die Möglichkeit dazu haben die CP-Jungs ja auch ganz bewusst wieder eingebaut.

**Comment by regs1980** [comment]
@rohne83 Ich habe das mal probiert mit Vanilla Ballensammelwagen den Ballenpresskurs abzufahren. Das Dumme daran ist nur, dass wenn sie mit sammeln fertig sind nicht an AD übergeben und einfach auf dem Feld stehen bleiben. Dieses Verhalten macht er nicht, wenn er ohne Kurs sammelt, außerdem ist mit Kurs noch die Kollisionskontrolle aktive, was bei Ballen sammeln nicht gerade von Vorteil ist. Kollision gegenüber andere Fahrzeuge wäre nicht schlecht aber stumpf vor dem Ballen stehen bleiben, ist nicht das was man will.

**Comment by Axel32019** [comment]
> Hi, , ich hab festgestellt wenn ich CP bei einem laufenden Kurs abbreche, z.b. weil Auftrag fertig, und ich manuell AD sage er soll zum Parkplatz fahren, das Anbaugerät nicht zusammengeklappt wird. Schalte ich das Fold Impl. aus und dann wieder an, klappt er es ein und fährt dann los. Bug oder Server Problem ? Und kann dieser Fehler in der Server Log auch damit zu tun haben. Ich weiß nicht wie der zustande kommt. Server log beigefügt.
> 
> LG Timmi [log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9105346/log.txt)

Hat ein Parmeter gefehlt.
