### ISSUE TITLE
wasser lädt nicht

### ISSUE THREAD

**Issue by andremeyer123** [Stephan-S/FS22_AutoDrive#62]
Ad lädt leider kein wasser bei mir im singelplayer  und multiplayer wird es leider auch nichts bei mir .
![fsScreen_2021_12_22_18_31_13](https://user-images.githubusercontent.com/70706468/147132419-34f5071c-3cc6-4dd1-9a3c-9ad21bea4ed9.png)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7764293/log.txt)
.

**Comment by Iwan1803** [comment]
Ich zitiere mal unseren guten Axel:
`Die "Wasser"-Marke wurde von Giants 200 m unter Grund verschoben, falls jemand fragt warum aktuell nicht aus Seen geladen werden kann.`
Ob wir hier was machen können oder wir auf einen Patch seitens Giants warten müssen, können wir aktuell nicht sagen.

Eine "Notlösung" wäre, einen Wasserbehälter/Hydrant irgendwo zu platzieren. Es gibt da Mods, wo man das Wasser (wie am See) auch kostenlos bekommen kann.

**Comment by andremeyer123** [comment]
Danke Iwan das hatte ich noch nicht gelesen im Discord kam leider keine Antwort damit hat sich meine frage gelöst .

**Comment by Iwan1803** [comment]
Ich lasse das mal zur Erinnerung offen und falls andere die gleiche Frage haben 😉

**Comment by Axel32019** [comment]
Fix: https://github.com/Stephan-S/FS22_AutoDrive/commit/9b4b76b2efe01bbe8a387511568446248f646cd2

**Comment by andremeyer123** [comment]
Singelplayer geht es  , multiplayer testen wir heute noch. 
Danke für die schnelle Hilfe

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
