### ISSUE TITLE
Turn on all lights when engaged

### ISSUE THREAD

**Issue by sjmills** [Stephan-S/FS22_AutoDrive#622]
With many mods, when you hit the Lights key once, only parking or dash lights will turn on. The next hit of Lights will turn on actual headlights, the next more lights, etc. Auto drive is only switching to the first hit, which leaves these mods driving around in the dark. It should turn on all lights.

I’ll also report this to GIANTS, since I seem to remember that it might be how they do it, and Autodrive can’t change that.

**Comment by rohne83** [comment]
then that's rather a mod issue. AD is not simulating a pressing of the F key, but enables the respective light states from vehicle xml. It turns on normal headlights on streets and the working lights on fields. But it can only do so if the lights are designated correctly in the vehicle xml. It does that absolutely correctly for every vanilla vehicle or mods with correctly setup lights configs.

**Comment by sjmills** [comment]
So simply turning on all lights isn’t something you’re interested in doing?

**Comment by ArtV-Nef** [comment]
> So simply turning on all lights isn’t something you’re interested in doing?

It's not a problem with the AD or the CPU, it's a problem with the modus operandi. The question is for the author of the technique.
