### ISSUE TITLE
Wiggles

### ISSUE THREAD

**Issue by Iam74Niner** [Stephan-S/FS22_AutoDrive#624]
Im not sure if this is a AD or CP issue   i use them both to pick up loose straw or hay from the field and deliver it to a unload area. it works well how ever when it returns to the field and starts to go back to the spot it left off at it wiggles all the way back taking it extreamly long time to make it back. it will eventually make it and run at normal speed until it returns to the field and starts to wiggle back

**Comment by venquessa** [comment]
A dup of my issue in CP issues?
