### ISSUE TITLE
Problem beim Abfahren eines Dreschers AD 2.0.0.7

### ISSUE THREAD

**Issue by Swinegel** [Stephan-S/FS22_AutoDrive#625]
Ich habe ein Problem beim Abfahren eines Dreschers auf der MAP Norfrisische Marsch 4fach. Ich weiß nicht ob es an der MAP oder AD liegt. Der Drescher wird von hinten links angefahren, es erfolgt eine kurzer Überladeprozess,, der Drescher setzt sich in Bewegung und der Ablader setzt sich ebenfalls in Bewegung und zieht sofort vor den Drescher, sodaß der Überladevorgang abgebrochen wird.  Nach einer kurzen Strecke bleibt der Ablader dann einfach vor dem Drescher stehen und lässt sich voranschieben. Dieser Vorgang wiederholt sich permanent. Zur Info, der Drescher wird von CP gesteuert.
Zur Verdeutlichung  hänge ich Screenshoots an und meine Einstellungen von AD. Ich habe auch diverse Einstellungen versucht, Fruchtumfahrung ja/nein etc.

![vlcsnap-2022-07-18-13h20m58s438](https://user-images.githubusercontent.com/59506866/179501529-448ff35f-d9aa-4285-8480-7e667d2f0362.jpg)
![vlcsnap-2022-07-18-13h21m08s454](https://user-images.githubusercontent.com/59506866/179501535-eec9acd9-9a23-4e36-850f-b2f33b301c17.jpg)
![vlcsnap-2022-07-18-13h21m14s084](https://user-images.githubusercontent.com/59506866/179501537-c127c481-a19b-4337-ad54-efc24aa0cd4c.jpg)
![vlcsnap-2022-07-18-13h21m19s229](https://user-images.githubusercontent.com/59506866/179501542-74f0d227-9e0b-4124-a837-0e5409668b12.jpg)
![vlcsnap-2022-07-18-13h21m21s555](https://user-images.githubusercontent.com/59506866/179501545-c68d8237-36da-41b6-9171-afa1c977d2ef.jpg)
![vlcsnap-2022-07-18-13h21m23s530](https://user-images.githubusercontent.com/59506866/179501548-42b90125-57aa-483e-a9b7-9b81f9edd9fb.jpg)
![vlcsnap-2022-07-18-13h21m27s991](https://user-images.githubusercontent.com/59506866/179501550-f632e24a-b7d5-4522-9130-95d24465b138.jpg)
![vlcsnap-2022-07-18-13h21m31s754](https://user-images.githubusercontent.com/59506866/179501554-53f80237-3d31-4949-9da6-0d60ec9c05cd.jpg)
![vlcsnap-2022-07-18-13h21m38s020](https://user-images.githubusercontent.com/59506866/179501555-3bd222f3-5909-485f-ae99-48e1a35daa65.jpg)
![vlcsnap-2022-07-18-13h21m52s104](https://user-images.githubusercontent.com/59506866/179501559-dbfba5ab-c45e-4aed-93d3-8dfd43bac73a.jpg)
![vlcsnap-2022-07-18-13h21m56s023](https://user-images.githubusercontent.com/59506866/179501560-5556ea73-6c4d-4447-8f1c-cfd2fa9c0775.jpg)
![vlcsnap-2022-07-18-13h22m00s186](https://user-images.githubusercontent.com/59506866/179501564-a46af793-1c01-46e9-a941-4eca4594873f.jpg)
![vlcsnap-2022-07-18-13h22m08s846](https://user-images.githubusercontent.com/59506866/179501567-24f79bf7-591e-48db-accd-2fe8be34c68f.jpg)
![vlcsnap-2022-07-18-13h22m20s625](https://user-images.githubusercontent.com/59506866/179501569-ded45658-8a47-446e-bfd0-52433e93d6fd.jpg)
![vlcsnap-2022-07-18-13h22m41s781](https://user-images.githubusercontent.com/59506866/179501572-a6fe35cd-b802-4487-94d7-49c5942b7215.jpg)
![vlcsnap-2022-07-18-13h22m57s547](https://user-images.githubusercontent.com/59506866/179501574-499fb397-b3ce-401b-80fa-d2fd2789a3ba.jpg)
![vlcsnap-2022-07-18-13h23m01s500](https://user-images.githubusercontent.com/59506866/179501578-30a7c236-dccf-41d5-b001-3a267a5f0c17.jpg)
![vlcsnap-2022-07-18-13h23m04s085](https://user-images.githubusercontent.com/59506866/179501580-e7380913-6e62-44e2-819b-7c9e3b9083d2.jpg)

**Comment by Swinegel** [comment]
Heir noch die aktuellen Einstellungen des Abfahrers
![20220718133520_1](https://user-images.githubusercontent.com/59506866/179503202-3ebfba9c-6320-4a79-a674-bba85c3b257f.jpg)
![20220718133546_1](https://user-images.githubusercontent.com/59506866/179503208-5f27c59f-3a37-47ec-9d4d-bd70cfcbd093.jpg)
.

**Comment by Xetras** [comment]
> ......Drescher wird mit Beete auf dem Feld bewegt. So vermeidest du, dass der AD Fahrer im Weg steht oder nach dem Abladen die Frucht verlassen will und dir in den Drescher fährt.

Was bedeutet mit "Beete" auf dem Feld bewegt?

**Comment by 60erjonny** [comment]
...du musst beim Drescher auch die Fruchtumfahrung aktivieren...

**Comment by Swinegel** [comment]
Danke für deine schnelle Rückmeldung. Wenn ich Dich richtig verstehe muß man im CP unter Feldmitte: Beete (innen nach außen) einstellen. Gibt noch weitere Fahrzeuge wo diese Einstellung sinnvoll ist. Beete ist bei mir Standard auf 6. Ist es Sinnvoll mit eher kleineren oder größeren Werten. 
@60erjonny: Das wäre gut, aber wo stellt man ein das der Drescher stehen bleibt. Sobald mit dem Abladen begonnen wird, setzt der Drescher sich in Bewegung, was wie ich es verstehe dazu führt, daß AD denkt das Abladen ist beendet und fährt vor den Drescher. Wie Du oben sehen kannst,  ist beim Abfahrer mit AD die Fruchtumfahrung aktiv. Beim Dresscher kann man es nicht einstellen, der wird ja von CP gesteuert. Würde beim Drescher auch keinen Sinn machen, er soll die Frucht ja ernten :-)

**Comment by 60erjonny** [comment]
nun, das muss man schon unter CP einstellen..
![Screenshot (49)](https://user-images.githubusercontent.com/63659182/179580843-3bbcaee1-c96a-4b39-92f2-4dcdd3be68f2.png)
.

**Comment by regs1980** [comment]
> Danke für deine schnelle Rückmeldung. Wenn ich Dich richtig verstehe muß man im CP unter Feldmitte: Beete (innen nach außen) einstellen. Gibt noch weitere Fahrzeuge wo diese Einstellung sinnvoll ist. Beete ist bei mir Standard auf 6. Ist es Sinnvoll mit eher kleineren oder größeren Werten. 

Das ist ganz dir überlassen, da gibt es nicht wirklich einen guten Hinweis, kommt auch auf das Feld an.

**Comment by Swinegel** [comment]
> nun, das muss man schon unter CP einstellen.. ![Screenshot (49)](https://user-images.githubusercontent.com/63659182/179580843-3bbcaee1-c96a-4b39-92f2-4dcdd3be68f2.png) .

OK, verstehe ich aber nicht beim Drescher. Einerseits fährt er sowieso nicht in der Frucht, da er diese ja vor sich drescht, andererseits muss er in der Frucht fahren um sie dreschen zu können. Ansichtssache. der Punkt ist aber, wieso beim Drescher einstellen, wenn doch der Abfahrer vor dem Drescher in die Frucht fährt. Ich verstehe nicht wie das relevant ist.

Im stehen abladen, habe ich jetzt im AD des Drescher gefunden "Aktives abfahren". Wie kann das wirksam sein, wenn doch AD gar nicht aktiv ist sondern CP?
Auf jedenfall danke ich euch (regs1980, Xetras  und 60erjonny) daß ihr euch Zeit nehmt mir bei meinem Problem zu helfen, DANKE.

**Comment by rohne83** [comment]
Fruchtumfahrung in den CP-Dreschereinstellungen bedeutet schlicht, dass zum Abladen mit Rohr über der Frucht (oder im ersten Vorgewende) sich immer eine Tasche gedroschen wird. Sollte man eigentlich absolut immer auf aktiviert lassen. Damit sind dann auch Fälle wie in deinen Screenshots nahezu ausgeschlossen.
Der Grund für das beobachtete Verhalten dürfte ja hauptsächlich die sehr ungünstige Einstellung bei der Fruchtumfahrung sein. Abfahrer soll außerhalb der Frucht bleiben (seine Fruchtumfahrung ist ja aktiv), aber der Drescher bleibt mangels eigener Fruchtumfahrung einfach mitten im Gemüse stehen. Sowas kann einfach gar nicht funktionieren.
