### ISSUE TITLE
Problem with AutoDrive and CoursePlay when using Autoload trailers for Bales

### ISSUE THREAD

**Issue by Lubjan** [Stephan-S/FS22_AutoDrive#626]
I'm not entirely sure if this problem should be reported here, in the CP or Autoload repo, but I've been trying out AD on [Waldstetten (ModHub)](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=241863&title=fs2022) together with CoursePlay to collect 220cm Bales from a field with an agroliner PWO 24 Autoload trailer from the [Autoload Stock Trailer Pack (ModHub)](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=233456&title=fs2022).
It has no problems unloading the bales at the sale point, but it never stops collecting them I have to manually stop CP to hand it over to AD. I assume it is because, no matter how many bales are on an autoload trailer it will always report 100% fill level. Each trailer does have it's own fill limit (see picture).
I'm using the default bale loaders in the meantime, with the same problem as in #597 but I'll try the same thing suggested there.

![image](https://user-images.githubusercontent.com/16855427/179521012-5e99d301-b085-48c9-a4a0-2870bbd60b7e.png)

(I hope I haven't overlooked an issue with the same problem)

**Comment by Mannie313** [comment]
Lade die neueste version von CP runter dann geht es.

MFG Mannie313
