### ISSUE TITLE
Konflikt zwischen AD und VehicleMonitor bekannt?

### ISSUE THREAD

**Issue by Pointer-de** [Stephan-S/FS22_AutoDrive#627]
Hallo.
Ich habe seit AD-2.0.0.6 einen Konflikt zwischen AD und VehicleMonitor (aus dem Modhub).

Sobald VehicleMonitor-Anzeige eingeschaltet/eingeblendet ist und dann AD eine Route startet, schmeißt es die Log.txt voll (der Eintrag rattert endlos durch, bis ich entweder AD stoppe oder VM ausblende). Ist die VM-Anzeige ausgeblendet, kann ich AD problemlos starten.

Getestet auf einem leeren Spielstand, ohne zusätzliche Mods und Mod-Order war auch leer.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9143132/log.txt)

![fsScreen_2022_07_19_18_28_21](https://user-images.githubusercontent.com/32867677/179806068-be6bd0c4-c180-4f65-9799-86f6e15a91dc.png)

![fsScreen_2022_07_19_18_28_42](https://user-images.githubusercontent.com/32867677/179806102-c7fa63e9-fc97-4b8f-90bc-6c7c8bc783c2.png)

Hier ein kurzer Gegentest mit AD2.0.0.5 - Problemlos VM und AD in Einklang ;-)
![fsScreen_2022_07_19_19_30_17](https://user-images.githubusercontent.com/32867677/179813359-bd4eef92-11aa-4f64-8885-8233580ce21a.png)

**Comment by Axel32019** [comment]
Vehicle Explorer aktualisieren
