### ISSUE TITLE
Seeder or implement filling. = 2 fill types

### ISSUE THREAD

**Issue by Kiraxon** [Stephan-S/FS22_AutoDrive#628]
This is not really an issue but a suggestion for Auto drive. 

As I understand it we've moved in a direction to have Course play handle the actual field work then have Auto drive handle the pickup and deliver an aspect of the game etc. I think this is a great move but, we have some FS19 features missing. 

Course play though was super at the logistical aspect but was superior at field actions, it did have a few logistical aspects that were helpful. One of these features was allowing two fill types  to be filled. In course play you could fill a seeder with both seeds and also fertilizer. 

I don't think this will feature will be added to course play but, could you consider for Auto drive a new mode that will allow for two fill types to be supported. Maybe call it two-fill type mode. Probably as I see it envision is, Field waypoint, then fill point 1 then fill point 2. In this scenario Field waypoint is the start and end of the course, then fill point one could be fertilizer location, and fill point 2 would be seeded. 

Its just a suggestion, but a valuable one. If you can have that happen, the overall grand scheme would be course play would seed the field, then when the tanks go empty, it would hand over filling responsibility to Auto drive.

As mention this is just a suggestion. If auto drive can already auto fill two fill types on a seed, could you disregard this and give me a brief description how it is accomplished?

Thank you for all your hard work on this wonderful mod.

Regards,

**Comment by rohne83** [comment]
If it's just for refilling seeders: if you place your seeds and fertilizer silos nearby, reachable via the same AD waypoint (or a silo where both is stored), it already refills both bins of your seeder today.

**Comment by Kiraxon** [comment]
Rohne83, thank you for the reply. At the moment I am using a silo mod for holding both fertilizer and seeds and there is one access trigger that shares both product inputs, so I will give your suggestion a try and see what happens. Thank you for the suggestion and I hope it works. :)

**Comment by Axel32019** [comment]
no update
