### ISSUE TITLE
AD + Courseplay Combine Mode

### ISSUE THREAD

**Issue by krambc** [Stephan-S/FS22_AutoDrive#629]
Hello,

First of all, excuse my English, because it is not as good as I would like.

I'm trying to combine a field using CP in the harvester and AD in the carting tractor.

I've disabled unload in the first headland in the CP menu of the harvester, but when it reaches the filling level set in the AD menu it calls the tractor.

Is this normal or I'm making something brong?

Thank you for your magnificent work.

**Comment by rohne83** [comment]
can be closed as duplicate, as this was already highlighted in #572
