### ISSUE TITLE
Probleme mit Kurven bei automatischer Erstellung Version 2.0.0.1

### ISSUE THREAD

**Issue by Burned-Ice** [Stephan-S/FS22_AutoDrive#63]
Hallo,

laut Release Video sollen ja keine Kruven mehr bei der automatischen Routenerstellung erstellt werden. Jedoch werden diese zum Teil doch mit erstellt und enthalten einen Fehler.
Der Endpunkt der Kurve ist nicht mir der weiterführenden Strecke verbunden. Der Endpunkt der Kurve und der Startpunkt der weiterführenden Strecke liegen dabei genau übereinander. Ich habe den Kurvenpunk im Screenshot lediglich zur Seite gezogen, um es zu zeigen. Es wurden keine Punkte oder Verbindungen gelöscht.

Spiel ohne weitere Mod, neuer sauberer Spielstand, keine Startparameter, mehrfach auf neuen Spielständen getestet.

![Screenshot LS22 AD 2001](https://user-images.githubusercontent.com/96543427/147134610-59c3a8bb-0980-4a34-9ef7-dc11594f6bda.png)

Edit: Zweiter Fehler in der automatischen Strecke an der gleichen Kurve. Zusätzlich eingekreist, auch hier den Punkt zu Veranschaulichung ein wenig verschoben

Grüße Ice

**Comment by Stephan-S** [comment]
Servus.
Danke für die Meldung.
Das sind allerdings tatsächlich Splines die so in der Map verbaut sind.
Aber wenn wir dazu kommen, könnten wir so exakt übereinander liegende Punkte sicher noch verbinden.

**Comment by Burned-Ice** [comment]
Ok, dass ist natürlich ärgerlich. Nagut, dann heißt es Kurvenbereiche händisch löschen und neu anlegen. Macht denke ich mehr Sinn als die nicht verbundenen Punkte in den Kurven zu suchen.

**Comment by Stephan-S** [comment]
Diese Kurvensegmente gibt es aber soweit ich das bisher gesehen habe nicht auf jeder Standardmap. Daher ist es mir beim Testen auf der Elmcreek nicht gleich aufgefallen

**Comment by Burned-Ice** [comment]
Alels gut. Ihr leistet super Arbeit. Bug suchen können auch wir ;)
