### ISSUE TITLE
Conflicts between CP 7.1.0.1 and AD 2.0.0.7 https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS22_AutoDrive#630]
Hallo AD Team. Ich hab das Problem wen ich diese beiden mods im modsordner hab bekomme ich folgenden fehler sobald ich bei CP den Kurseditor auf mache.

Hello AD Team. I have the problem when I have these two mods in the mods folder I get the following error when I open the course editor at CP.

Error: Running LUA method 'draw'.
G:/07 Landwirtschaftssimulatoren/Landwirtschaftssimulator 22/mods_Test/FS22_AutoDrive/scripts/Editor/EditorGUI.lua:132: attempt to index a nil value

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9156149/log.txt)

MFG Mannie313

**Comment by regs1980** [comment]
Was du da nutzt, ist keine Release Version. 
DEV Versionen nutzt man auf eigene Gefahr.

**Comment by Williwillswisse** [comment]
DEV Versionen erhalten keinen Support. Benutzung auf eigenes Risiko.
