### ISSUE TITLE
Doubt about line connectors colours

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS22_AutoDrive#631]
Hello all, hope someone can explain in a simple way my doubt......
Most of you know that there are different colours to the connecting lines between waypoints, being green for one way direction PRIORITY path, purple for 2 way PRIORITY path, cream for one way ALTERNATE path and brown for 2 way ALTERNATE path, and also the light blue for reversing path..........
Now, my doubt is, in the picture example at the bottom, will the vehicles still consider the green lines in the middle as PRIORITY even if they are not connected to the green lines of the main network?
The idea here is to have a path between the other ones where vehicles are forced to go instead of taking the "closest" path through any of the other "waiting points" i created, however the paths ahead and behind that small "priority" path are all set as alternate path until they connect to/from to the main network.
Will autodrive still consider that small path as priority and force vehicles to it, when they are just passing through and not going to the waiting points? or will it ignore it because its not connected to the main network and vehicles take any of the 3 possible paths?
Hope the image is good enough to understand the example.

As an addon to this question, could maybe the team open a "discussions" board for us to discuss these kind of things instead of reporting a new "issue" when its not an actual issue? I noticed the Courseplay team has it on their github, maybe it could benefit us commoners to understand better about autodrive tricks and tips, in the lack of an official "tutorial" or "Guide" for the mod. :)

![Course example](https://i.postimg.cc/3wwsxCXx/Course-Example-01.png)

**Comment by Iwan1803** [comment]
Screenshot seems to be corrupt as i can't see it complete.
If the newest version doesn't solve the "problem", please create a new issue with screenshots.
