### ISSUE TITLE
reversing with sowing machine

### ISSUE THREAD

**Issue by Leon83858** [Stephan-S/FS22_AutoDrive#637]
https://user-images.githubusercontent.com/23504996/181484838-bea81921-f6e9-439c-b18f-4886bea058ef.mp4

**Comment by Leon83858** [comment]
no mod 
![image](https://user-images.githubusercontent.com/23504996/181485029-2ba44ea0-3d85-4799-b260-0b12871548ad.png)

**Comment by regs1980** [comment]
Rückwärts Kurs verlängern.

**Comment by brandonvdongen** [comment]
I have this same problem with with the other combination plow/seeder. it appears asif the trailer hinge gets locked straight and the tractor seems to become unable to bend. no matter how long the parkway is, trying to reverse it just results in it driving straight backwards until it fails it's route.

**Comment by Axel32019** [comment]
solved with #255

**Comment by Axel32019** [comment]
fixed Release 2.0.1.2

**Comment by Dawson-X** [comment]
I have the same problem when reversing with the hinge.
The trailer hitch locks straight and the tractor is unable to turn with the tow regardless of the length of the route. Attempting to reverse will cause it to go straight backwards and off the marked route.
Fixing the problem in the version 2.0.1.2 and 2.0.1.4 does not work.

![Farming Simulator 22 Screenshot 2024 02 01 - 23 09 01 36](https://github.com/Stephan-S/FS22_AutoDrive/assets/158523033/42e77f91-b6b3-43f5-a3f6-3f6a101434a4)
![Farming Simulator 22 Screenshot 2024 02 01 - 23 09 03 22](https://github.com/Stephan-S/FS22_AutoDrive/assets/158523033/45436c8a-fe1e-41df-9068-308a06a73ee4)
![Farming Simulator 22 Screenshot 2024 02 01 - 23 09 07 94](https://github.com/Stephan-S/FS22_AutoDrive/assets/158523033/e9ee0779-af63-438f-ba5a-f746a52ccee2)
![Farming Simulator 22 Screenshot 2024 02 01 - 23 09 09 95](https://github.com/Stephan-S/FS22_AutoDrive/assets/158523033/9c117b75-ac94-4897-bf9b-9da53b86b1ea)
