### ISSUE TITLE
unloading bales in the middle of the road 

### ISSUE THREAD

**Issue by Leon83858** [Stephan-S/FS22_AutoDrive#639]
https://user-images.githubusercontent.com/23504996/181687576-9dae70d4-0117-4305-8b83-0e1665aa1e18.mp4

**Comment by Leon83858** [comment]
https://user-images.githubusercontent.com/23504996/181689264-588d4aaf-ce45-4110-965c-40e8f43f94e0.mp4

or just in front of the trigger if i force him to aporoach the area from the north

**Comment by Leon83858** [comment]
https://user-images.githubusercontent.com/23504996/181732058-76ad9219-aba5-4ba4-9107-b58546b6d1fe.mp4

the mod trailer also wasnt the problem

**Comment by regs1980** [comment]
Den maximalen Silo Abstand mal verringern.

**Comment by Leon83858** [comment]
@regs1980 schon probiert

**Comment by regs1980** [comment]
@Leon83858 Welche Map ist das und kannst du den AD Kurs zur Verfügung stellen.

**Comment by Leon83858** [comment]
@regs1980 https://mega.nz/file/81A0jI4C#BhaM3kV3GQZy47tD-5gyaHHnr2eYRgwSSDLmSc0iwYU
![image](https://user-images.githubusercontent.com/23504996/181906107-267b2800-93b8-4e43-a993-2f21dd7236ae.png)

**Comment by regs1980** [comment]
Liegt an der Map

**Comment by Leon83858** [comment]
@regs1980 weshalb?

**Comment by regs1980** [comment]
Ich habe AD per config auf 5 m gestellt er lädt weiter auf der Straße ab

![2022-07-31 08_01_17-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/182012833-e145c063-1895-4a8e-896a-3c04406f7abe.png)

![2022-07-31 08_03_33-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/182012840-1a98a343-cbd3-4f7d-a358-0f1c61dc479b.png)

nur erkennt er den Trigger in dem Pferdeshop nicht und fährt bis zum Zielpunkt

![2022-07-31 08_08_29-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/182012900-3cee888c-e7ad-4151-921e-0cfc7d49e623.png)

Stelle ich das ganze jetzt wieder auf 10 m lädt er schon direkt am Mist Silo ab

![2022-07-31 08_10_30-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/182012977-d0817d0b-ee2a-488a-a6e0-b78d818c5d43.png)

Was mich stört, sind die großen triggerboxen um die Objekte, was hat der mapper sich dabei gedacht sowas einzubauen, macht gar kein Sinn.
 
![2022-07-31 08_10_30-Farming Simulator 22](https://user-images.githubusercontent.com/13314443/182013071-6dccb081-679a-4e69-8d01-06882ee59e3b.png)

Das ist von der Rostock, die gelbe Triggerbox ist der einzige Trigger, den man braucht, dann funktioniert das ganze auch.

![2022-07-31 08_22_09-Greenshot](https://user-images.githubusercontent.com/13314443/182013124-70d2d307-1ec7-477b-8886-b4eacbf43869.png)
