### ISSUE TITLE
Ad berechnet das Streckennetz über den Kartenrand

### ISSUE THREAD

**Issue by Reiko40** [Stephan-S/FS22_AutoDrive#64]
Iwan wie unter deinem Video auf Youtupe schon erwähnt. In der ersten Version hat Ad das Streckennetz über den Kartenrand hinaus angelegt. Ich habe ein Screenshort gemacht und angehängt. Aber wie gesagt das ist die 2.0.0.0 von AD.

**Comment by Reiko40** [comment]
![fsScreen_2021_12_22_18_44_17](https://user-images.githubusercontent.com/35115409/147135293-e5314a48-7a52-4c9f-a5a8-7c8258e93d8f.png)

**Comment by Iwan1803** [comment]
Dann lad doch bitte erstmal die aktuelle Version und versuche es erneut.
Btw. ist das eine Standardmap?

**Comment by Reiko40** [comment]
Habe es mit der neuen Version gerade getestet auf der Elmcreek, da würde das selbe Foto entstehen. Ja ist die Standardmap.

**Comment by andremeyer123** [comment]
Der verkehr fährt dort ja auch lang ,dreht ja dort nicht um, daher gehen dort die spline gerade durch.gehe von aus das man diese stellen selber anpassen mus.

**Comment by Stephan-S** [comment]
Sollte ja möglioch sein, dass abzufangen. Wir setzen es mal auf die Todo Liste.

**Comment by Reiko40** [comment]
Ja das habe ich ja in meinem spielstand auch gemacht. Ich wollte es ja nur weiter geben

**Comment by Stephan-S** [comment]
Done / Erledigt :-)

**Comment by Reiko40** [comment]
Wow ihr seid super. Ich hoffe ihr bleibt dem ls noch sehr lange erhalten
