### ISSUE TITLE
AD does not wait for implements to bend to start driving

### ISSUE THREAD

**Issue by leo32128fs** [Stephan-S/FS22_AutoDrive#643]
Hello friends, I would like to know if this is an error or a bad configuration of the AD or the CP, or if it is an error but every time the CP passes to AD it does not wait for the implement to bend and drags it bumping into trees or others pbtáculos along the way, thanks in advance for the help .   Link to a video showing the problem

     https://drive.google.com/file/d/1L_LE2lo9v3tfJWPIeS03tN8X9AaMZaOR/view?usp=sharing

**Comment by Axel32019** [comment]
@leo32128fs Video not avaiable, could you share it again?
