### ISSUE TITLE
Issues with HUD and keybindings

### ISSUE THREAD

**Issue by HaroldtheBarrel** [Stephan-S/FS22_AutoDrive#644]
Hello!

How can I hide the hud by default so I dont need to close it every time i load a map?
Also there seems to be a conflict in the keybindings with Autodrive and the ingame crane keys. cant open and close the log-grab. had to delete Autodrive keybindings for gamepad to fix it. im using an xbox one gamepad.

**Comment by Iwan1803** [comment]
Try newest version: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
