### ISSUE TITLE
Frage: Anfahrt zum Abkippen, Aufladen,.. mit 5km/h

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#645]
Hallo Leute
AD fährt Triggerpunkte ja immer mit 5 km/h an.
![fsScreen_2022_08_03_21_19_38](https://user-images.githubusercontent.com/24860501/182691594-826709ae-7f78-4227-9ff4-47dcac61914c.png)

beispielsweise beim abladen/aufladen bei Getreidesilos, auffüllen von Düngerstreuern, Kalkstreuern, Fässern,....
wo im code ist denn dieser wert hinterlegt?
ich würde mir den mal (auf eigene gefahr) auf 8, 10 oder 12 km/h hochsetzen.
bearbeite derzeit eine 4x map und da dauert diese anfahrt im schneckentempo schon extrem lange zum zusehen.
lg
andreas

**Comment by Tensuko** [comment]
Das kann natürlich zu einem zu späten anhalten führen.
Oder man müsste mal schauen, dass er später langsamer fährt.
Auf mehr als 10 würde ich jedenfals nicht gehen.

**Comment by andreasthu** [comment]
Ja klar, dafür möchte ich es ja schrittweise steigern.
Aber wo im code ist dieser wert hinterlegt?
Ich finde ihn nicht.
Lg
Andreas

**Comment by Tensuko** [comment]
Ich kann nachher mal gucken ob ich was finde

**Comment by Stephan-S** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/blob/main/scripts/Modules/DrivePathModule.lua#L267

**Comment by andreasthu** [comment]
Danke dir stephan
                    self.speedLimit = math.min(5, self.speedLimit)
Werd mir das später mal mit 8, 10 oder 12 km/h ansehen

**Comment by andreasthu** [comment]
kurze rückmeldung:
habe den speed jetztmal auf 11kmßh angehoben:
	self.speedLimit = math.min(11, self.speedLimit)
funktioniert derzeit tadelos, der Traktor fährt ca. 0,5m weiter vor bevor der Lade-/Entladevorgang beginnt.
bei den langen Entladeschütten oder den Anhängern seh ich da kein problem.
was ich noch testen muss, sind 3punkt Spritzen oder Düngerstreuer, da diese eher kurz gebaut sind.
solcherart habe ich aber auf Hobos Hollow sowieso nicht im einsatz, werd ich aber noch probieren.
lg
andreas

**Comment by Tensuko** [comment]
Du musst aber bedenken, dass es Geräte mit sehr kurzem trigger gibt, die gerne mal durchrutschen. Im 19er haben wir mit CP viel damit rumexperimentiert.
Auch wenn das langsam fahren Zeit kostet, kostet es mehr Zeit wenn man Geräte hat, die dann stehen und nicht befüllt werden.

**Comment by andreasthu** [comment]
ja, das teste ich noch wie z.b Düngerstreuer oder Feldspritzen in Dreipunktaufhängung.
gebe dann nächste woche die erkenntnisse bekannt.
lg
andreas

**Comment by blubstar86** [comment]
Hallo Andreas, hattest du noch weiter getestet?
Die Erkenntnisse würden mich auch interessieren.

**Comment by andreasthu** [comment]
sorry für die späte rückmeldung,
ja hab ich
derzeit hab ich das speedlimit auf 11 kmh stehen
probleme gibt es so bei meiner spielweise nicht.
das einzige wo es probleme gibt ist dann wenn ein kurzer Gerät wie z.b. der 3punkt Düngerstreuer an einem Silo geladen werden soll, der eine kleine Triggerbox hat, wie z.b. ein Auslassrohr:
![fsScreen_2022_08_25_19_25_02](https://user-images.githubusercontent.com/24860501/186731406-e3ba1052-9ee3-4af3-bf60-62e2cf01d2e9.png)
![fsScreen_2022_08_25_19_26_06](https://user-images.githubusercontent.com/24860501/186731423-c43ee6fe-0693-4e2a-a75e-c42540aef262.png)
dann lädt er nur ein bissl was rein und bleibt zu spät stehen.
diese kombi hab ich i nder praxis nie, da ich gezogene Kalkstreuer habe, und die sind einfach länger
und die triggerbox beim Düngerlager ist sowieso größer daher bleibt er bei Dünger rechtzeitig stehen.

sollte dieser Fall aber trotzdem mal eintreten, kann ich die zufahrtslinien etwas"gezackt" gestalten - wie z.b. bei Temposchwellen - dann bremst der Traktor und fährt langsamer auf den Trigger zu.
lg
andreas

**Comment by rohne83** [comment]
Die 5km/h find ich auch etwas langsam. Bevor hier aber einfach das Tempo hochgesetzt werden kann, sollte vA auch mit Sämaschinen getestet werden. Die haben ja soweit meistens mit Abstand die kürzesten Trigger.

**Comment by Axel32019** [comment]
Sehe hier eher eine "Verschlimmbesserung", Sorry.
