### ISSUE TITLE
Problems with the BR translate

### ISSUE THREAD

**Issue by Myiamoto86** [Stephan-S/FS22_AutoDrive#646]
Dears

I'm here to inform you that the BR translation is having problem. 

I decided to make my own, more complete version of the translation to PT-BR, so that it is more understandable to brazilian players... I believe that not only I, but many, are using the mod that you developed. I tell you that since FS19, the first one I started playing, I have been using this mod in the game. It has always been useful, and still is for those who play alone.

This will be the most complete BR translation that you have obtained so far.

In the HUD, I needed to make changes, and not the translation. Due to the difficulties of understanding during the translation of the HUD (help "?"). Attached are the images for example.
I hope you consider, insert this translation for a next update.

![img code HUD](https://user-images.githubusercontent.com/108041428/182766778-7454263b-eea8-4306-8463-e649469da42a.png)
![img HUD in game](https://user-images.githubusercontent.com/108041428/182766794-f6f974ad-865f-482d-b03a-f2bd5dabaef1.png)
[modDesc.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9256751/modDesc.txt)
[translation_br.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9256752/translation_br.txt)

**Comment by Axel32019** [comment]
@Myiamoto86 , @Admilson Please align the translation, we are not able to check what is good or not!
see: #699

**Comment by Myiamoto86** [comment]
Gute Nacht Leute

Also habe ich einige Änderungen vorgenommen, die die Autodrive-Befehlsidentifikation in meiner Sprache klarer gemacht haben (einfacher zu verstehen - für neue Spieler). Auch die Übersetzung des HUB-Hilfemenüs habe ich nicht originalgetreu übersetzt, weil es in meiner Sprache sehr seltsam war. Ich habe eine Anpassung vorgenommen, um die Tipps für Spieler aller Spielstärken zu erleichtern. Diese Änderungen wirken sich nur auf die BR-Übersetzung aus.

Ich schicke die neue Datei mit den zusätzlichen Texten der neuen Version.
![img HUD Autodrive in game](https://user-images.githubusercontent.com/108041428/205766052-5942cf99-0e12-4558-98a9-71281ff79e2f.png)
[translation_br.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10158674/translation_br.txt)

**Comment by Axel32019** [comment]
@Myiamoto86 Is this still open?
