### ISSUE TITLE
Problems with gear shift on some tractors

### ISSUE THREAD

**Issue by Cheesecake79** [Stephan-S/FS22_AutoDrive#647]
I have problems with the John Deere 6030 Series from db modding. According to the shop and .xml, the 6910S should actually drive 50km/h. However, it does not go faster than 28 km/h either manually or with autodrive or cruise control. Cruise control is set to 50 km/h.
It shifts up to a maximum of 4th gear but only haltingly.

I once had the same problem with another tractor. As far as I remember, it was with an MF. But I can't remember which one.

Edit:
I have now pressed the + key on the numpad. Now it drives at 50 km/h. However, it does not save this setting and would have to be shifted up again manually every time it shifts down (and autodrive does this in bends).

---------------------------------------------------------------

Ich habe Probleme mit dem John Deere 6030 Series von db modding. Laut Shop und .xml sollte der 6910S eigentlich 50km/h fahren. Er fährt aber nicht schneller als 28 km/h, weder manuell noch mit Autodrive oder Tempomat. Der Tempomat ist auf 50 km/h eingestellt.
Er schaltet maximal bis in den 4. Gang, aber nur stockend.

Das gleiche Problem hatte ich einmal mit einem anderen Traktor. Soweit ich mich erinnere, war es mit einem MF. Aber ich kann mich nicht mehr erinnern, welcher es war.

Edit:
Ich habe jetzt die + Taste auf dem Ziffernblock gedrückt. Jetzt fährt er mit 50 km/h. Allerdings speichert er diese Einstellung nicht und müsste jedes Mal, wenn er runterschaltet (z.B. in Kurven), wieder manuell hochgeschaltet werden.

**Comment by Iwan1803** [comment]
Und was hat das nun genau mit AD zu tun, wenn ein Mod mit Schaltung Probleme macht?

**Comment by Cheesecake79** [comment]
Zum Beispiel dass man zwar manuell hochschalten kann, Autodrive das aber nicht macht. 
Ich weiß halt nicht woran es liegt. Habe jetzt irgendwas gelesen dass es ggf. eine alte .xml ist, wo die Drehzahl/Torque etc. falsche ingestellt ist und somit nicht die notwendige Drehzahl fürs Hochschalten erreicht wird.
Allerdings habe ich weiter nichts dazu gefunden.

**Comment by Tensuko** [comment]
Hört sich für mich eher nach Mod Issue an als ein bug von AD.

**Comment by blue-painted** [comment]
I have the same issue with the Mod MF AL 3/3700
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=228487&title=fs2022
When AD is driving it doesn't shift into High ratio, so cannot reach full speed.

**Comment by Axel32019** [comment]
> I have problems with the John Deere 6030 Series from db modding. According to the shop and .xml, the 6910S should actually drive 50km/h. However, it does not go faster than 28 km/h either manually or with autodrive or cruise control. Cruise control is set to 50 km/h. It shifts up to a maximum of 4th gear but only haltingly.
> 
> I once had the same problem with another tractor. As far as I remember, it was with an MF. But I can't remember which one.
> 
> Edit: I have now pressed the + key on the numpad. Now it drives at 50 km/h. However, it does not save this setting and would have to be shifted up again manually every time it shifts down (and autodrive does this in bends).
> 
> Ich habe Probleme mit dem John Deere 6030 Series von db modding. Laut Shop und .xml sollte der 6910S eigentlich 50km/h fahren. Er fährt aber nicht schneller als 28 km/h, weder manuell noch mit Autodrive oder Tempomat. Der Tempomat ist auf 50 km/h eingestellt. Er schaltet maximal bis in den 4. Gang, aber nur stockend.
> 
> Das gleiche Problem hatte ich einmal mit einem anderen Traktor. Soweit ich mich erinnere, war es mit einem MF. Aber ich kann mich nicht mehr erinnern, welcher es war.
> 
> Edit: Ich habe jetzt die + Taste auf dem Ziffernblock gedrückt. Jetzt fährt er mit 50 km/h. Allerdings speichert er diese Einstellung nicht und müsste jedes Mal, wenn er runterschaltet (z.B. in Kurven), wieder manuell hochgeschaltet werden.

Auch hier: Bitte komplette log anfügen.
