### ISSUE TITLE
Kein Parkplatz für "Strautmann SEK 802 Paletten Autoloader" zuweisbar.

### ISSUE THREAD

**Issue by WernerWusel** [Stephan-S/FS22_AutoDrive#648]
Wie der Titel schon aussagt: Kein Parkplatz zuweisbar an diesen Anhänger. Der einzige Anhänger wo diese Zuweisung nicht funktioniert.

AD-Version 2.0.0.7
(Mehr kann ich wirklich nicht schreiben).

**Comment by ct177mak** [comment]
ganz ehrlich ? Ich weise immer einen Fahrzeug sprich Traktor oder Drescher z.B den Parkplatz zu ,aber nie angehängte Geräte oder Trailer .Das ganze natürlich im Editormodus mit STRG´+ Linke Maustaste.

**Comment by WernerWusel** [comment]
Man kann sowohl dem Traktor als auch dem Tool einen Parkplatz zuweisen. Funktioniert auch alles. Habe bereits einige Parkplätze vergeben :)
![20220804132833_1](https://user-images.githubusercontent.com/102391757/182837241-9ff76a0f-2087-4f79-8d82-2d95929af0e4.jpg)

**Comment by Tensuko** [comment]
Dann ist das wohl eher ein Punkt für den Modder des Trailers und nicht für AD!

**Comment by WernerWusel** [comment]
Ich bin davon ausgegangen, durch einen Eintrag in den Release-Notes zu Ver. 2.0.0.6 "AutoLoad führte zu div. Problemen #437, #451, #453 & #539", dass ein Fehler sowohl am Mod liegen kann als auch an AD (der Modder ist im übrigen @Achimobil, sowohl für den Skript als auch für den Trailer), da alle anderen Trailer funktionieren, auch der Strautmann ohne AutoLoad.

**Comment by Achimobil** [comment]
![image](https://user-images.githubusercontent.com/65055783/183220134-2388c340-29e2-4802-9551-32358ad6c027.png)
Also ich habe das gerade in meinem SP getestet. Sowohl das zuweisen des Parkplatzes an den SEK sowie auch das abschließende Parken geht bei mir problemlos

**Comment by WernerWusel** [comment]
Ok, Danke. Dann mal selber suchen woran das liegt.
