### ISSUE TITLE
Zielpunkt im Client am Home-Server nicht zuweisbar.

### ISSUE THREAD

**Issue by WernerWusel** [Stephan-S/FS22_AutoDrive#649]
Die Überschrift stimmt nicht ganz. Wenn man einen Zielpunkt erstellt (im Client) erscheint dieser Zielpunkt zwar in der AD Liste im Ordner Standard, allerdings ist der Zielpunkt an einem Wegpunkt irgendwo auf der Karte und nicht da, wo er sein sollte.
Man kann den Zielpunkt auch am Home-Server erstellen. Man sieht ihn dann auch am richtigen Wegpunkt, allerdings NUR am Home-Server, im Client ist der Zielpunkt nicht sichtbar.
 
AD-Version 2.0.0.7

**Comment by Iwan1803** [comment]
Sorry, aber irgendwie verstehe ich dein Problem nicht so ganz bzw. was ist ein Home-Server?
Ich habe gestern noch auf einem Dedi-Server Strecken und Zielpunkte erstellt, welche direkt für meine Mitspieler nutzbar waren.

**Comment by WernerWusel** [comment]
Der Home-Server, dein unbekanntes Wesen ;)
Aus Client-Sicht (MP Spiel beitreten) gibt es keinen Unterschied zwischen Home- und Dedi-Server.
Der Name Home ist von mir gewählt, um den Unterschied zwischen den beiden Servertypen, die es im LS22 gibt, zu erkennen.
Der Home-Server ist ein PC in deinem Home, nicht irgendwo in einer Serverfarm, auf dem der LS22 läuft.  Man kann auf einem Home-Server auch spielen, muss es aber nicht. Mein I-Net Anschluss ist nur eine 16 MBit-Leitung, aber für den LS22 reicht das für 4 Spieler locker aus. 7 Screenshots zur Verdeutlichung.
![20220822132453_1](https://user-images.githubusercontent.com/102391757/185912423-0acd4311-b24f-42bd-9785-efd01206fa77.jpg)
![20220822132501_1](https://user-images.githubusercontent.com/102391757/185912448-0ce7a0cc-09ae-4d5b-93fe-a5be0d3529e7.jpg)
![20220822132519_1](https://user-images.githubusercontent.com/102391757/185912457-9193d809-04ed-4873-8936-c276eaeaeeea.jpg)
![20220822132532_1](https://user-images.githubusercontent.com/102391757/185912479-8dd03303-6da6-4816-a39b-ba9e3a644c72.jpg)
![20220822132536_1](https://user-images.githubusercontent.com/102391757/185912492-c5269968-0869-4735-9145-d238cb69ba32.jpg)
![20220822132713_1](https://user-images.githubusercontent.com/102391757/185912502-7859ad98-7fb4-4e29-8adc-f42c61524429.jpg)
![20220822132740_1](https://user-images.githubusercontent.com/102391757/185912507-350b7b26-d057-49cc-9518-657f6783cf65.jpg)

**Comment by Iwan1803** [comment]
Sorry, aber Dedi-Server und selber gehostetes SP-Spiel ("Home-Sever") macht schon einen gewissen Unterschied aus 😉
Dennoch ist es bei beiden so, das die AD-Config aus dem savegame an die Clients verteilt werden. Ich bin mir nur gerade nicht sicher, wie die Synch des AD-Netzes da abläuft. Theoretisch sollten deine Mitspieler aber Änderungen am Netz auch gleich sehen können.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
