### ISSUE TITLE
Automatic course generator on single lane roads

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS22_AutoDrive#65]
After the update to 2.0.0.1 the Problem still exists that on single lane roads the generator generates two overlapping green lanes in each direction, instead of one purple line.

![AD_Issue](https://user-images.githubusercontent.com/5852750/147147011-08386332-bd5f-4949-a3a7-c6e111611aef.jpg)

**Comment by Stephan-S** [comment]
Can you do me a quick favor and check if those spline start and end at exactly the same spots (reversed of course) or do the extend separated? Thanks

**Comment by Mike1977** [comment]
I am sorry, but i went to my family for a few days and so i could not react to your request. Thank you for fixing the problem anyways.
