### ISSUE TITLE
Rückwärts einparken bei Halle mit Rolltor

### ISSUE THREAD

**Issue by FarmerMario** [Stephan-S/FS22_AutoDrive#650]
Hallo,
Ich habe ein kleines Problem.Wenn ich in  eine Halle mit Rolltor einparken möchte,wird der Anhänger mit hochgezogen
und bleibt dann hängen.Bei manchen Geräten ist das kein Problem.
Liegt es  an der Kollisionserkennung vom Anhänger? Oder liegt es an die Geschwindigkeit des Rolltores.
![20220807121106_1](https://user-images.githubusercontent.com/98883983/183286501-3462c690-48b8-4657-9f17-d46c42a93473.jpg)
![20220807121125_1](https://user-images.githubusercontent.com/98883983/183286502-bb4e8383-24c1-465e-af25-0fd3a57b0928.jpg)
![20220807121144_1](https://user-images.githubusercontent.com/98883983/183286504-b45d7166-03cb-408c-b2d5-c6105fa8e1a8.jpg)

Ich benutze den Mod "FS22_AnimatedObjectExtend"

mfg FarmerMario

**Comment by Iwan1803** [comment]
Das Tor öffnet nicht schnell genug - so war es zumindest in LS19.
Dort habe ich für mich die Triggerzone für Rolltore vergrößert als auch die Geschwindigkeit erhöht.

**Comment by FarmerMario** [comment]
Hallo Iwan,
Danke für Deine Antwort.Den Verdacht hatte ich auch schon.
Ich wollte ja auch schon den Trigger vergrößern.Nur ladet de GE die Texturen nicht,gibt Errors aus.
So das das Gebäude nach dem speichern,Weiß ist.
Und wie bzw. wo, ich die Geschwindigkeit der Tore ändern kann,weiß ich leider nicht :(

mfg Farmer Mario

**Comment by Iwan1803** [comment]
Die Geschwindigkeit müsste man in der XML zur Halle finden.
Schau mal nach "animatedObject" und dort dann nach "animation duration".

**Comment by FarmerMario** [comment]
Hallo Iwan,
Super.... Danke für den Tip mit der Duration.
Ich habe diese verringert, nun sind sie schneller und es funktioniert mit AD.
Vielen Dank für den Tip.

Viele Grüße Farmer Mario

**Comment by Iwan1803** [comment]
Super... dann mach ich hier mal zu 😉
