### ISSUE TITLE
Fertilization

### ISSUE THREAD

**Issue by Vernyj** [Stephan-S/FS22_AutoDrive#651]
Any fertilization when switching from courseplay to autodrive will cause a total interruption of all ongoing work. For this reason, there are gaps in the fields or departures from the route. This problem does not occur only in a moment. when personally sitting in the designated machine that is currently being switched.

**Comment by wwalsh1240** [comment]
Had same problem, its the kamaz pack, uninstall and you'll be good

**Comment by Iwan1803** [comment]
Try with newest version as there were some improvents in the latest ones.
If problem comes up again screenshots maybe could be helpfull.
