### ISSUE TITLE
Mouse pointer/keyboard input handover issue

### ISSUE THREAD

**Issue by venquessa** [Stephan-S/FS22_AutoDrive#652]
I have recently found myself in the situation where I have 2 hours of game play unsaved and suddenly the only thing I can talk to is AutoDrive.  Mouse and keyboard are not received by FS22.  ESC does not produce the menu/map, but pressing the AD settings button does open it's menu.  In the end, all times this happens, I have had to just kill FS22 and lose gametime.

It seems to happen when you have the mouse point active, hit escape to open the menu and the map/menu opens, but the mouse pointer is invisible.  Most times when this happens, just hitting escape, and it returns to normal.  Occasionally when this happens, hitting ESC to return to the game results in the keyboard and mouse becoming disconnected from FS22 and only he AD GUI responding to clicks or key presses.

Hard to reproduce I know, but it's exceedingly annoying.  Is it possible to add a "SAVE GAME" button somewhere in the settings menu as a handle rescue option?

**Comment by Iwan1803** [comment]
Join our discord which is linked on the start page. There maybe someone can help.
As this is not an AD issue -> closed.
