### ISSUE TITLE
AD still will not drive under auger

### ISSUE THREAD

**Issue by GTA3Fan** [Stephan-S/FS22_AutoDrive#654]
NOTE: I saw the other thread and saw it was closed and wasn't sure if my reply there notified anyone.

Just got back to game after a few months and noticed tractor wouldn't drive under auger wagon chute. Searched and found this apparently has been fixed on 0.7.

I updated and it started to drive under auger but then stopped before chute. I readjusted driving points and now it won't even go near it. 

0.6
![20220808143713_1](https://user-images.githubusercontent.com/106483338/183496007-19cc1fc4-ce3b-4dc7-a598-4863dd4bd62d.jpg)

0.7
![20220808151212_1](https://user-images.githubusercontent.com/106483338/183496039-9f39efb2-dce5-4214-9c32-a68cfc4c5054.jpg)

**Comment by ninjatrig** [comment]
I have the same issue. Even with collision detection off it still won't drive under arms or conveyer belts. Silos pipes are fine and sometimes arms/belts will randomly be friendly but something's definitely wrong.

**Comment by FarmerMoe** [comment]
I have the same issue when I try to use the default Walkabout WMB 4000. In prior versions I was able to use the Walkabout and AD without any issues.

**Comment by Williwillswisse** [comment]
Try this:
- enter the vehicle with the auger wagon
- fold the pipe
- leave with "E"
- enter with "E"
- unfold the pipe
- leave with "E" and do not enter the vehicle again
- start your tractor and test

**Comment by ninjatrig** [comment]
> Try this:
> 
> * enter the vehicle with the auger wagon
> * fold the pipe
> * leave with "E"
> * enter with "E"
> * unfold the pipe
> * leave with "E" and do not enter the vehicle again
> * start your tractor and test

Can confirm this works after one try. Possibly unnecessary instructions to simplify the habit before fix:

1. Arrive at wait point and unfold pipe then fold it immediately after full unfold. Enter and exit tractor. Enter tractor again, unfold the pipe and exit tractor. (E to enter and exit tractor)

Will report back if this needs to be done after auger refills seeds lime or whatever.

**Comment by big-horn73** [comment]
I’m having this issue as well. Version 0.5 worked correctly.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
