### ISSUE TITLE
Abfahrer

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS22_AutoDrive#655]
Hallo, ich habe das Problem dass beim dreschen der Abfahrer neben her fährt und permanent abtankt. im Drescher sind nur 1% aber der Abfahrer bleibt bei 0% nicht stehen, sondern fährt wie beim häckseln ständig neben her...

Ist ja grundsätzlich egal, jedoch bei 2 Dreschern auf dem Feld wird dadurch der Abfahrer vom 2. Drescher gerufen, nur kommt der dann nur zum 2. Drescher, wenn der 1. mit der Reihe fertig ist.

Stell ich hier was falsches ein?

LG 
Eric

**Comment by Goofy78** [comment]
Moin 

Hast du das Aktive Abfahren im Drescher deatktiviert?

**Comment by eric4072** [comment]
hallo, nein ist aktiv....

hier mal ein Video dazu:
https://youtu.be/JXN_yrMVd9k

Das "Problem" betrifft alle Fahrzeuge, ganz egal welches Zugfahrzeug, egal welcher Anhänger...

noch ein Video von einem 2. Drescher inkl. meiner Einstellungen am Schluß:

https://youtu.be/DSXRVaK_1qk

bei dieser Länge des Feldes blockieren die beiden den ganzen Ablauf, der 2. Drescher steht da und muß warten bis der 2. Drescher das Wenden einleitet...

Hat das noch jemand? Der Modordner ist gut gefüllt, also will ich gar nicht ausschliessen, dass das Problem bei mir liegt. Aber so sehr ich mich auch zurück erinnere, ich habe das bei mir noch nie anders gesehen glaub ich...
Log ist fehlerfrei

Danke für Eure Hilfe
Eric

**Comment by Goofy78** [comment]
CP die Option " Beim Entladen stehen bleiben" aktiviert?

**Comment by eric4072** [comment]
gerade probiert, dann bleibt der Drescher stehen, bei diesen Längen nicht sinnvoll...

**Comment by TobiHH78** [comment]
Das ist gewollt, dass der Abfahrer bis zum Ende der Bahn abtankt. Würde er das nicht tun, wäre der Korntank des Dreschers am Ende der Bahn auf großen Feldern schon wieder recht voll, was auf der nächsten Bahn wenn das Rohr in der Frucht ist auch wieder zu Problemen führt.
Dann muss der Drescher erst eine Tasche ausdreschen und wird erst im Stand abgetankt.

So wie es jetzt ist, kann man in den allermeisten Fällen sehr flüssig und ohne Stillstand arbeiten.

**Comment by rohne83** [comment]
> Das ist gewollt, dass der Abfahrer bis zum Ende der Bahn abtankt. Würde er das nicht tun, wäre der Korntank des Dreschers am Ende der Bahn auf großen Feldern schon wieder recht voll, was auf der nächsten Bahn wenn das Rohr in der Frucht ist auch wieder zu Problemen führt. Dann muss der Drescher erst eine Tasche ausdreschen und wird erst im Stand abgetankt.

Deswegen fährt man beim Dreschen ja auch nicht Spur an Spur sondern so dass das Rohr nahezu jede Bahn außerhalb der Frucht bleibt ;)
Lösung des Problems hier wurde sogar schon angeschnitten nur noch nicht erkannt: aktives Abladen (in den AD-Drescher-Einstellungen) deaktivieren, dann wird nur solange abgetankt bis der Drescher leer ist, und danach steht der Abfahrer für die anderen Drescher zur Verfügung.

**Comment by TobiHH78** [comment]
Ich weiß was Beete sind. Die Betonung liegt auf "nahezu". Ganz ohne neue Anstiche bei denen das Rohr in der Frucht ist geht es nicht, und dafür ist es hilfreich, wenn bis zum Ende der vorherigen Bahn abgetankt wird.

**Comment by rohne83** [comment]
Müsste man dann aber jede Bahn wieder umstellen, handlich ist das nicht. Und bringt dir sowieso auch nix wenn in der letzten Bahn vor Neuanstich gar nicht erst abgetankt wird. Um solche Fälle wirklich sinnvoll handeln zu können, wäre es am besten wenn man per Button den Abfahrer/ULW auch unabhängig vom tatsächlichen Füllstand rufen könnte (war zB bei CP im 19er möglich, und wurde für genau diese Fälle auch sehr häufig genutzt von mir). Zumindest ULW-Mode soll ja irgendwann auch wieder bei CP integriert werden.
Aber jedenfalls, dieses aktive Abfahren ist die Ursache für das Problem eric4072s Problem, und lässt sich glücklicherweise deaktivieren (fände es sinnvoller wenn es defaultmäßig immer deaktiviert wäre, die Fälle wo es tatsächlich Sinn macht das aktiv zu haben sind ja doch eher selten).

**Comment by TobiHH78** [comment]
> Um solche Fälle wirklich sinnvoll handeln zu können, wäre es am besten wenn man per Button den Abfahrer/ULW auch unabhängig vom tatsächlichen Füllstand rufen könnte (war zB bei CP im 19er möglich, und wurde für genau diese Fälle auch sehr häufig genutzt von mir).

Das kann man....
Dafür kann man eine beliebige Taste in den AD-Keybindings belegen.
Setzt aber natürlich voraus, dass man den Drescher selbst fährt. Ich rufe die Abfahrer eigentlich immer manuell, wenn ich den Zeitpunkt als sinnvoll erachte.
Was sinnvoll ist oder nicht, hängt halt immer von vielen individuellen Faktoren ab.

**Comment by eric4072** [comment]
> > Das ist gewollt, dass der Abfahrer bis zum Ende der Bahn abtankt. Würde er das nicht tun, wäre der Korntank des Dreschers am Ende der Bahn auf großen Feldern schon wieder recht voll, was auf der nächsten Bahn wenn das Rohr in der Frucht ist auch wieder zu Problemen führt. Dann muss der Drescher erst eine Tasche ausdreschen und wird erst im Stand abgetankt.
> 
> Ne ist nicht gewollt, sondern kann eingestellt werden wie es beliebt. Um das von dir Beschriebene zu vermeiden fährt man beim Dreschen ja auch nicht Spur an Spur sondern so dass das Rohr nahezu jede Bahn außerhalb der Frucht bleibt ;) Lösung des Problems hier wurde sogar schon angeschnitten, nur noch nicht erkannt: aktives Abladen deaktivieren! Und zwar in den AD-Drescher-Einstellungen - nicht des Abfahrers sondern tatsächlich des Dreschers (da wo auch der Abfahrfüllstand und "rufe 2ten Abfahrer" eingestellt werden kann). Dann wird nur solange abgetankt bis der Drescher leer ist, und danach steht der Abfahrer für die anderen Drescher zur Verfügung - zumindest sofern die nicht schon 80 oder 90% voll sind (da gibts aber schon ein anderes Issue für).

Danke, werde ich gleich mal testen...

**Comment by eric4072** [comment]
Das umschalten von aktivem Abladen bei Drescher hat das gewünschte Ergebnis gebracht, danke nochmal :-)

**Comment by andreasthu** [comment]
aktives abladen macht man bei Feldhäckslern,
bei Dreschern (die einen Korntank haben)macht man das aus.
lg
andreas

**Comment by eric4072** [comment]
dann nennt den "Schalter" doch Drescher/Häcksler :-)

**Comment by s4t4n** [comment]
Hi, ich habe so ein ähnliches Problem beim hächseln.. ein abfahrer kommt und fährt mit, aber der 2. wartet am Feldrand und erst wenn der eine weg ist und vom Feld runter auf einer Straße oder so, setzt sich der 2. in bewegung. Im 19er kannte ich das so, daß der 2. schon direkt dahinter fährt.
Kann man das irgendwie hinbekommen/einstellen?
lg

**Comment by eric4072** [comment]
> Hi, ich habe so ein ähnliches Problem beim hächseln.. ein abfahrer kommt und fährt mit, aber der 2. wartet am Feldrand und erst wenn der eine weg ist und vom Feld runter auf einer Straße oder so, setzt sich der 2. in bewegung. Im 19er kannte ich das so, daß der 2. schon direkt dahinter fährt. Kann man das irgendwie hinbekommen/einstellen? lg

"rufe 2.Abfahrer" beim Häcksler einschalten (AD)

**Comment by s4t4n** [comment]
ah.. der Hächsler hat dann eine eigene Einstellung... nice, das wusste ich gar nicht. Danke.

**Comment by s4t4n** [comment]
okay, ich habe das jetzt mal ausprobiert, der 2. Abfahrer kommt zwar, aber wenn er an der Reihe wäre ab zu tanken,
bleibt er einfach stehen. Erst wenn der 1. sein Hächselgut weggebracht hat und zurück kommt, fährt der 2. weiter zum Hächsler.
Habe das jetzt mit "nur" 2 Abfahrern getestet.. vielleicht müssen es mehr sein?!

**Comment by eric4072** [comment]
> okay, ich habe das jetzt mal ausprobiert, der 2. Abfahrer kommt zwar, aber wenn er an der Reihe wäre ab zu tanken, bleibt er einfach stehen. Erst wenn der 1. sein Hächselgut weggebracht hat und zurück kommt, fährt der 2. weiter zum Hächsler. Habe das jetzt mit "nur" 2 Abfahrern getestet.. vielleicht müssen es mehr sein?!

ok, da solltest du mal screenshots oder videos zeigen. Ich habe z.Z. regelmäßig 30 Fahrzeuge am laufen, großteils ohne Probleme.

Meine Häckslerketten (3 Häckslerketten mit jeweils 4 Abfahrer) laufen, nach dem Vorgewende, ohne eingreifen zu müssen 20std. lang. Nun geht es mir wie beim LS19: ich stoße an die Grenze des Spiels. 15-20 Produktionen und die ca. 30 Fahrzeuge erzeugt das altbekannte ruckeln :-)

zu den Themen oben:
Ich habe jetzt einen Test gemacht. kaum zu glauben, NF ohne Gräben, Feld 50:
Zeitersparnis mit 3 statt 4 Abfahrer und 2 Drescher, CP Lands mit 6 Reihen, AD bei beiden Dreschern "aktives abfahren" auf aus: 20min Ersparnis 

LG 
Eric

**Comment by s4t4n** [comment]
hab noch mal etwas rum probiert.... mit 3 und 4 Abfahrer klappt das wunderbar... manchmal zwar etwas lustig an zu gucken, wenn die sich in die Quäre kommen und versuchen auszuweichen.. funktioniert dann aber doch. Mit 2 Abfahrer, 1 Drescher bzw. Hächsler... dann wollen die irgendwie nicht.

**Comment by rohne83** [comment]
aber für das eigentliche Problem des Issueerstellers wurde die Lösung doch gefunden, und der Issue kann damit zu, oder @Iwan1803 ?
