### ISSUE TITLE
Haltepunkt

### ISSUE THREAD

**Issue by acton59** [Stephan-S/FS22_AutoDrive#658]
Hallo,

erst mal Danke für die tolle Atbeit.
wäre es möglich im Editor einen Haltepunkt zu definieren, wie bei Courseplay LS19.

aldo

**Comment by Iwan1803** [comment]
Warum? Wofür? Welchen Zweck soll das haben?

**Comment by acton59** [comment]
Hallo
Man könnte eine Wiegung simulieren und die Fahrzeuge am Stoppschild anhalten lassen, Wer es möchte.

**Comment by Iwan1803** [comment]
Ja, aber warum sollte man das wollen? Welchen Sinn soll das machen?

**Comment by acton59** [comment]
Welchen Sinn ?
Schöner anzuschauen.
Aber war nur ne frage.

**Comment by Iwan1803** [comment]
Nur fürs "schöner anzuschauen" macht sowas keinen Sinn, sorry.
Daher mache ich hier mal zu...
