### ISSUE TITLE
Parking assignment disappearing 

### ISSUE THREAD

**Issue by Andrius9277** [Stephan-S/FS22_AutoDrive#659]
I am using the latest autodrive and had parking assignments for each vehicle.  After saving the game and loading back up all assignments are lost. Is there a way to fix this? Can find what is wrong.

**Comment by Misamangame** [comment]
Are you sure you assigned tractor and not for example trailer or some equipment? I have over 80 parking spaces assigned and all working without any issues

**Comment by Andrius9277** [comment]
I have tried both ways and it disappears after loading. I have checked every single attachment and tractor nothing assigned any more. I didn't have any issues before.

**Comment by Iwan1803** [comment]
Check your mods folder if the file for AD is named: FS22_AutoDrive.zip
If not, then delete alle AD-zips out of that folder and redownload AD from here:
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.7/FS22_AutoDrive.zip
If this doesn't help, please post the log.txt here.

**Comment by Andrius9277** [comment]
Thanks Iwan1803, it was folder name issue.

**Comment by lytyi** [comment]
что делать вообще не могу назначить парковку
