### ISSUE TITLE
ANZEIGE VOM FAHRZEUG

### ISSUE THREAD

**Issue by FARMER-4780** [Stephan-S/FS22_AutoDrive#661]
Hallo,
erst einmal ein Dankeschön für die tolle Arbeit die Ihr macht.
Könnte man das Fahrzeug, welches man selbst fährt auf der Karte in einer anderen Farbe anzeigen, damit man besser sieht, wo man auf einer großen Karte unterwegs ist. Im Moment sieht man manchmal vor lauter weißen Zeichen sein eigens Fahrzeug nicht gut.
Grüße aus Belgien

**Comment by Axel32019** [comment]
Danke für das Dankeschön, ist echt eine Ausnahme!
"welches man selbst fährt " - hierfür ist AD nicht "zuständig", vielleicht einen eigenen mod schreiben :-)
