### ISSUE TITLE
AD Und IT Runner 

### ISSUE THREAD

**Issue by hecke82** [Stephan-S/FS22_AutoDrive#662]
Hallo, wollte AD fahren lassen mit einem IT Runner hintendran aber wenn ich auf Start Kicke, fährt er den Hacken zurück (mit Container drauf) und will dann erst losfahren.

**Comment by Iwan1803** [comment]
AD-Einstellungen -> Experimentelle Features -> Fold Implements -> deaktivieren

**Comment by Axel32019** [comment]
Gleiches Verhalten wie mit Giants-Helfer "Freie Fahrt" zu Ziel -> Haaken ausklappen, dann losfahren.
Ist ein mod-Problem, kein AD-Bug.
Wer es für sich lösen will:
turnOnFoldDirection="-1" ersetzen durch turnOnFoldDirection="1"
@Iwan1803 @Williwillswisse @Stephan-S  Falls gefragt wird hierauf verweisen.

**Comment by MeRida2104** [comment]
> Gleiches Verhalten wie mit Giants-Helfer "Freie Fahrt" zu Ziel -> Haaken ausklappen, dann losfahren. Ist ein mod-Problem, kein AD-Bug. Wer es für sich lösen will: turnOnFoldDirection="-1" ersetzen durch turnOnFoldDirection="1" @Iwan1803 @Williwillswisse @Stephan-S Falls gefragt wird hierauf verweisen.

Bspw. beim Vanilla Güllefass Kotte Garant PQ 32.000 mit Schleppschlauch Bomech Multi 4XL: Wie kann man es hier lösen? Wo müsste man hier turnOnFoldDirection="1" setzen?
