### ISSUE TITLE
Abfahrer nach einander voll machen

### ISSUE THREAD

**Issue by IROKILLER** [Stephan-S/FS22_AutoDrive#663]
Hey entweder bin ich zu doof es zu finden oder es gibt es nicht.

Wenn ich mehr als 1 Abfaher auf Feld habe mit einem Mähdrecher sucht er sich immer den der am dichtesen dran ist, was dazu für das alle unterschiedlich voll gemacht werden. Wäre cool das erst einer voll ist der dan abhauen kann und der nächste dann voll gemacht wird.

**Comment by andreasthu** [comment]
wäre ideal,
manchmal hab ich auch zwei, drei abfahrer stehen, mit 70-80% voll, dann werden alle ziemlich gleich voll und hauen ab, der Drescher steht dann etwas länger bis der erste wieder da ist.
wenn ich drann denke, entlasse ich immer die, die am feldrand warten und stelle einen wieder ein, wenn der volle abhaut.
lg
andreas

**Comment by FarmerMario** [comment]
Hi,
Beim Drescher im Menü das "aktive Abfahren" deaktivieren und "rufe 2. Abfahrer" aktiviren.
Beim Drescher und oder Abfahrer,den Punkt "abfahren ab..." das Limit einstellen.
Ich gebe keine Garantie,aber bei mir klappt das meistens,daß der "leere" Abfahrer den beereits "gefüllten" Abfahrer folgt 
und dann eingreift,wenn der Erste voll ist.

mfg Farmer Mario

**Comment by rohne83** [comment]
> Hi, Beim Drescher im Menü das "aktive Abfahren" deaktivieren und "rufe 2. Abfahrer" aktiviren. Beim Drescher und oder Abfahrer,den Punkt "abfahren ab..." das Limit einstellen. Ich gebe keine Garantie,aber bei mir klappt das meistens,daß der "leere" Abfahrer den beereits "gefüllten" Abfahrer folgt und dann eingreift,wenn der Erste voll ist.
> 
> mfg Farmer Mario

Ne, darum gehts hier gar nicht. Hier gehts darum, dass AD derzeit (und das haben die AD-Devs aus für uns unbekannten Gründen aber laut Iwan definitiv bewusst so implementiert) immer den nahesten Abfahrer ruft, und nicht den mit dem höchsten Füllstand.
Idealerweise kann man das einfach selbst einstellen wie es auch bei CP möglich war (Abfahrer-Priorität hieß das glaub ich, konnte gewechselt werden zwischen Entfernung und Füllstand). Mapaufbau, Feldgröße und -layout und natürlich auch die Erntemaschinen und Logistik sind nunmal in derart unterschiedlichen Kombinationen möglich, dass es gar nicht möglich ist auszudiskutieren welche Einstellung die bessere ist, das kann immer nur der Spieler selbst jeweils am besten wissen.

**Comment by Iwan1803** [comment]
Es wird immer Situationen geben, in denen das eine oder andere mehr Sinn macht, aber wie Rohne schon schreibt, hängt das von vielen Faktoren ab.
Es wird immer Situationen geben, in denen es sinnvoller ist, den nächstgelegenen oder einen anderen Entlader zu rufen. AD ist ein Skript, keine KI. Eine Logik zu programmieren, würde vermutlich den Rahmen deutlich sprengen.

**Comment by Iwan1803** [comment]
Da kein weiteres Feedback -> geschlossen!
