### ISSUE TITLE
CP/AD - Unload bale at a point without trigger ?

### ISSUE THREAD

**Issue by Chico0008** [Stephan-S/FS22_AutoDrive#664]
Hi

I'm picking up a lot of bales right now
i now CP can pick them up, and AD deliver them
BUT, is there a way to tell AD a place to drop the bale, event if there is no trigger ? (like under a shed for example)

For now i do it manually, reverse unload under my shed, but if AD could do that for me it could've been great.

Is there a way to do that ? not for now ? never ?

**Comment by Iwan1803** [comment]
No, there is no possibillity at the moment. AD needs a trigger for it.

**Comment by m0box** [comment]
I found that is the reverse course was long enough for the trailer and tractor to be straight, the target waypoint was set at the end of the reverse course, and the look ahead distance (turn) variable was a default 5m then the Arcusin autoloading trailer would unload in the shed. Note the stack deposited needed to be cleared away so the next load can be dumped in the same place else bales everywhere LoL.

**Comment by Iwan1803** [comment]
Check newest version: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
