### ISSUE TITLE
Z Key 

### ISSUE THREAD

**Issue by HispanoModding** [Stephan-S/FS22_AutoDrive#665]
Hello. There are some mods that to open the cover or extend the tube (bourgaul seeder) you have to use the Z key, with autodrive it doesn't work.
Do I have to configure something in autodrive settings? or what can it be?
Greetings.

**Comment by Iwan1803** [comment]
Sounds like you are using mods and if they don't use default settings for it, AD can't handle them.

**Comment by HispanoModding** [comment]
They were two buggy mods, all fixed.
