### ISSUE TITLE
Strange issues 

### ISSUE THREAD

**Issue by GmanAtheist** [Stephan-S/FS22_AutoDrive#667]
Autodrive conflicts with create field and Courseplay . When I want to create field with plow that has create field , the button does not show up on the hud. Even when I change keybindings, the ability to create fields does not come up in hud. Also key “G” to change implement between Tractor and plow does not work. When I disable Autodrive all is fine. Love this mod, but need field creation and courseplay. Please fix this. Thanks for the hard work making this great mod.

**Comment by Iwan1803** [comment]
No Log? No info about AD and CP version used? How should we help?

**Comment by GmanAtheist** [comment]
AD - 2.0.0.7
CP - 7.1.0.3

**Comment by GmanAtheist** [comment]
Mods List
[DirPrnInfo2.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9479741/DirPrnInfo2.txt)

**Comment by Iwan1803** [comment]
A screenshot of the F1 menu could maybe helpfull. Also in AD and CP you can set options to not show it in the F1 menu.

**Comment by Axel32019** [comment]
no feedback -> closed
