### ISSUE TITLE
Lua Fehler beim anhängen vom großen Feldrandcontainer

### ISSUE THREAD

**Issue by timmi4026** [Stephan-S/FS22_AutoDrive#668]
Moin, wenn ich den großen Feldrandcontainer anhänge kommt dieser Lua Fehler in die Client Log und ich kann auch im AD keine Gülle auswählen zum nachkaufen . 

2022-08-29 11:36 Error: Running LUA method 'draw'.
C:/Users/Herbe/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Hud/PullDownList.lua:589: attempt to index a nil value
2022-08-29 11:36 Error: Running LUA method 'draw'.
C:/Users/Herbe/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Hud/PullDownList.lua:589: attempt to index a nil value

LG TImmi

**Comment by Axel32019** [comment]
#596
