### ISSUE TITLE
Traktor fährt nich auf Abgeerntete Wiese 

### ISSUE THREAD

**Issue by xerion8300** [Stephan-S/FS22_AutoDrive#669]
Hallo warum fährt der Traktor immer durch die Wiese und nicht auf der abgemähten Seite.
Gibt es da eine Einstellung, beim Maishäckseln funktioniert es, oder liegt es daran das es kein Feld ist.
![fsScreen_2022_08_30_20_10_22](https://user-images.githubusercontent.com/25564472/187512819-02c69c83-16ed-4b83-87c7-05935939ca55.png)

**Comment by rohne83** [comment]
M.W. wird In-Game immer noch nicht zwischen abgeerntetem und erntereifem Gras unterschieden, in der Form dass damit Fruchtumfahrung oder eben korrekte Auswahl der Rohrseite funktionieren würde. War schon im 19er so. Ist dann aber halt ein Giants-Problem.

**Comment by hermannbrauer** [comment]
Wiese ist immer noch Problem...

**Comment by Iwan1803** [comment]
Gras war schon im 19er ein Problem und ist es im 22er leider auch noch, da Gras keine Frucht für Giants ist.
Wir werden mal schauen, ob wir da noch was machen können...

**Comment by Axel32019** [comment]
fixed Release 2.0.1.2
