### ISSUE TITLE
autodrive drops connection

### ISSUE THREAD

**Issue by frabonk** [Stephan-S/FS22_AutoDrive#67]
when going on multiplayer my connection drops every time just as I load the game, with out the mod installed its fine, I know you are working hard to get it done so I thought ill point out this issue out thanks.

**Comment by Stephan-S** [comment]
Hey, please attach a log from you (the client) and if you have access, also from the server.

**Comment by frabonk** [comment]
sorry cant find it not good with pcs

**Comment by Beedog743** [comment]
@frabonk  it should be under Documents > My Games > Farming Simulator 22 > **Log.txt** start the game up and try to re create your issue and when it happens simply go to that text file and you can locate the issue in there. Look through all the lines and look for any **warnings** or **errors**. Once you find it then copy it in here so the dev can pinpoint it better

**Comment by frabonk** [comment]
cant find log files they are not showing on my pc sorry i am not good on a pc.

**Comment by Beedog743** [comment]
@frabonk  here is a video.

https://youtu.be/sGfebhIqgtA

**Comment by frabonk** [comment]
I  have seen video but that file must be hidden, so I am not sure can you take over my pc and take a look through any desk, sorry I am trying because I am retired and play with my friends online but am stuck on this part sorry frank.

**Comment by frabonk** [comment]
all I can se is log.txt

**Comment by frabonk** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7773556/log.txt)

**Comment by frabonk** [comment]
sorry this is the right one gets to 99 percent on multiplayer and holds there so i come out of game by pressing my window key hope this helps thank you very much.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7773614/log.txt)

**Comment by Stephan-S** [comment]
Hey, unfortunately, there is no error in this log and nothing that could point us to a likely issue.
You should update to the latest AD Release though and try creating a new AutoDrive config on the server.
To do so, either start a new savegame or start and save the game once without AD installed.

**Comment by Axel32019** [comment]
no update -> closed
