### ISSUE TITLE
Combine driving with stairs in work position

### ISSUE THREAD

**Issue by Misamangame** [Stephan-S/FS22_AutoDrive#679]
Hello,

as title said when AD driving combines from A to B they have stairs/ladder open into oncoming driving lane which in case of big combines is a lot of space. As soon as player enter combine driven by AD those stairs are folded into driving position (same when you driving it manually). Can that be solved by AD automatically ?

You can see on the picture I'm sitting in CH 10 there is no stairs/ladder even when AD still in command, but CASE IH in front have stairs on the left side open into oncoming lane.

![20220512125823_1](https://user-images.githubusercontent.com/33344465/189068272-8fff0742-cc1a-4a19-b972-38e79978f398.jpg)

**Comment by Axel32019** [comment]
Combine fold ladder separate if user enter or leave vehicle - G's logic...

**Comment by regs1980** [comment]
Das mit der Leiter klappt, nur hat der Drescher so eine Art Gedenkminute, bevor er zum Zielpunkt fährt.

**Comment by Axel32019** [comment]
@regs1980 Bitte mal prüfen ob es jetzt besser ist.

**Comment by regs1980** [comment]
@Axel32019 Das funktioniert sehr gut. Im aufgeklappten Zustand, klappt er die Leiter an, wartet bis er komplett zugeklappt ist und dann fährt er los. So kann man es lassen.
