### ISSUE TITLE
(BUG) Running Lua Method Draw 

### ISSUE THREAD

**Issue by iraydawg** [Stephan-S/FS22_AutoDrive#68]
After completing a new route into the network and attempting to send vehicle (worker) to another waypoint this error occured. 

D:/FarmSimMods/FS22/gamemods/FS22_AutoDrive/scripts/Utils/UtilFuncs.lua:382: attempt to perform arithmetic on local 'toY' (a nil value)
2021-12-23 02:13 Error: Running LUA method 'draw'.

In addition it wiped the autodrive xmls from the save game folder. 

See attached log
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7767450/log.txt).

**Comment by Stephan-S** [comment]
Hey, thanks for the report.
This means that we unfortunatley missed one root cause for that issue in the 2.0.0.1 release.
I already fixed this now and we will deploy a hotfix asap!

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
