### ISSUE TITLE
Produktion beliefern bzw. Produkt abholen

### ISSUE THREAD

**Issue by FarmerMario** [Stephan-S/FS22_AutoDrive#680]
Hallo,
Ich da eine Idee bzw. Frage.
Ist es möglich, eine Produktion zu beliefern und gleich nach der Lieferung, das fertige Produkt abzuholen.
Bsp. Mischfutterproduktion: 
Das Mischfutter(Produkt) abholen und in's Lager abladen. Aus dem Lager den Rohstoff gleich wieder aufladen und dann
in der Produktion wieder liefern,so das keine Leerfahrt entsteht.
z.Zt. geht ja "nur" liefern und abholen.
Also beliefern und dann für's Lager oder Verkauf abholen.

mfg Farmer Mario

P.S. Bitte fragen, wenn mann nicht versteht,was ich meine.

**Comment by hermannbrauer** [comment]
Dann hast du aber massive Standzeiten an den Produktionen. 
Was du versuchen könntest dir die jeweiligen Lade und entladen Punkte in entsprechende Order legen und Liefern wie auch Abholen auf Multiple stellen..

Wäre interessant ob das geht, kann ich gerade nicht testen.. evtl müssen die jeweiligen Lade- und Entladepunkte in der "richtigen" Reihenfolge sein... Dann sollte das in der Theorie klappen... 
Musst halt Ordner haben "Laden Mühle" mit den Punkten Hof-Silo und Mühle-Ausgabe und dann den Ordner "Entladen Mühle" mit Mühle-Anlieferung und Hof-Lager

**Comment by FarmerMario** [comment]
Ich hatte das so gemeint.Vorraussetzung die Produktion ist voll und im Hoflager sind die Rohstoffe.
Hofsilo laden --> Produktion abladen --> Produktion laden --> Hofsilo abladen --> Hofsilo laden --> Produktion abladen usw.
Aber wenn ich das so sehe, müsste das klappen, wenn ich die o.g. Punkte in einem Ordner packe.
Nur hatt das den Nachteil,daß ich jedesmal für die jeweilige Produktion einen Ordner erstellen muß und die lade-ablade Punkte
so umbenenen muß,danit sie in der richtigen Reihenfolge sind.
Das wollte ich ja vermeiden.

mfg

**Comment by Iwan1803** [comment]
Es gibt keine Task-/Aufgabenliste in AD, um sowas zu bewerkstelligen und nein, es wird auch nicht kommen.
