### ISSUE TITLE
Falsche Strecke angenommen

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#681]
Hallo, Ich wollte zum Feld 11 fahren, es wird ob aber angezeigt das der Weg zum Parkplatz gefunden wurde
![Schweinn](https://user-images.githubusercontent.com/47453761/189412909-bc6be5be-7dbe-4e8b-8a65-4cd943d9c95b.png)

**Comment by Iwan1803** [comment]
Sicher, das die Meldung von dem Traktor ist?
Man kann übrigens für AD-Fahrer einen Namen vergeben, wenn man in den LS22-Einstellungen eine Taste dafür belegt. Das ist sehr hilfreich, wenn man z.Bsp. den gleichen Trecker mehrfach hat.
