### ISSUE TITLE
Unload pipe Grimme Evo and Ropa harvester

### ISSUE THREAD

**Issue by haza737** [Stephan-S/FS22_AutoDrive#686]
Hello,

My unloader will not go under the trailed potato harvesters pipes, I have tried all default machines and mods. I have tried adjusting the collisions, pathfinding and offset. It will drive up to pipe, not go under and then state 'reversing from collision'. Anything else I could try? I have been trying for a week or so to fix this problem but now turning to you for help. 

Thank you for your work. 

![fsScreen_2022_09_14_12_23_23](https://user-images.githubusercontent.com/113521097/190144245-8390eb5a-ebdf-4386-b62f-35a5f9cbfed1.png)
 

![fsScreen_2022_09_14_12_19_47](https://user-images.githubusercontent.com/113521097/190144220-f736546d-c9a7-4759-832e-244102e08969.png)
![fsScreen_2022_09_14_12_19_49](https://user-images.githubusercontent.com/113521097/190144234-82871d1f-dcf4-4a90-89ca-4a6125ec4555.png)

**Comment by bigginhill** [comment]
I'm also encountering this, and am similarly flummoxed.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
