### ISSUE TITLE
Auto Load Error Bales Dedicated Server

### ISSUE THREAD

**Issue by PapaTim68** [Stephan-S/FS22_AutoDrive#687]
Moin,

playing on a dedicated Server and using a PWO 24 Autoload Trailer from the Autoload Stock Trailer Pack,
I encountered a problem while delivering Silage Bales. As soon as the Delivery Point is in side and the Driver starts "search for the trigger"
the Server is spammed with the following error.
```
2022-09-14 20:49 Error: Running LUA method 'update'.
D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: attempt to perform arithmetic on local 'fillFreeCapacity' (a nil value)
```

Stalling the hole server to a hold. I hope you can fix this, assuming this is a thing on your side and not Autoload.

Greetings,
PapaTim68

**Comment by Axel32019** [comment]
@PapaTim68 Is it still present with actual Autoload-Script? Not possible to reproduce it...
If so, please attach the complete log.

**Comment by PapaTim68** [comment]
Yes, the thing is still happening. I also tried it with the Strautmann which is supposed to be the reference implementation.
Here goes the Server Log:
[server_log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10096311/server_log.txt)

And here for reference the client log:
[client_log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10096312/client_log.txt)


I did activate all the debug options of AD. At 14:04 roughly, the Driver reaches the trigger and goes into search mode.

**Comment by Axel32019** [comment]
@PapaTim68 Please remove the mod FS22_FillLevelLimiter, this cause the error.

**Comment by PapaTim68** [comment]
Okay, thanks for the info. Will do so. Although it's sad using it from time to time... But can understand that this cant be on your side to fix.
