### ISSUE TITLE
Einstellung für Reparatur 

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Stephan-S/FS22_AutoDrive#689]
Wo kann man bei der automatischen Reparatur die Werte ändern? Also ab welchen bestimmten Wert das Fahrzeug zur Werkstatt fährt.

**Comment by Iwan1803** [comment]
Die Werte sind fest hinterlegt:
Tanken < 15%
Reparieren bei Schaden > 60%

**Comment by kurtlohnunternehmen** [comment]
Ok. Schade das man es als User nicht ändern kann. Persönlich finde ich die 60% für Schaden ziemlich niedrig. Wo sind denn diese Werte hinterlegt (lua oder xml)?

**Comment by Iwan1803** [comment]
Du kannst die automatische Reparatur ja ausschalten und dein Fahrzeug bei Bedarf mit einer Tastenkombi losschicken 😉
Und nein, ich kann dir leider nicht sagen, wo genau der Wert steht.
Es wird zu 99% auch keine Einstellmöglichkeit dazu kommen, denn es sind jetzt schon mehr Optionen verfügbar als man braucht.

**Comment by kurtlohnunternehmen** [comment]
Alles klar - nix für ungut. (:
