### ISSUE TITLE
Abholen & Abliefern mag nicht recht.

### ISSUE THREAD

**Issue by Th301** [Stephan-S/FS22_AutoDrive#69]
Moin zusammen,

zunächst natürlich 1000 Dank, dass ihr so schnell einen der essenziellsten Mods ins Spiel zurück gebracht habt!!
Die neuen Funktionen sind auch echt nice!

Ich habe aber irgendwie ein Problem. Eigentlich dachte ich, dass ich aus dem Ls19 beinahe "PowerUser" bin, allerdings klappt es im 22er noch nicht so gut :(

Auf dem Foto sieht man die Einstellung im HUD und auch einen Wegpunkt. Der Traktor steht direkt vor dem Wegpunkt und sagt, dass er keinen Pfad dahin finden konnte. Das passiert bei "Abholen und Abliefern".

Wähle ich einfach den Modus "Fahren" aus, so gibt es keine Probleme. Woran kann das liegen?
![fsScreen_2021_12_23_09_08_18](https://user-images.githubusercontent.com/25582092/147209617-f02f1c5b-1603-4589-9e27-d30e34abda44.png)

**Comment by Stephan-S** [comment]
Hi,
die Fehlermeldung ist leider irreführend (Muss ich dringend mal bearbeiten)
Er ist ja aktuell voll und würde in diesem Modus als nächstes das untere Ziel zum Abladen anfahren. Dahin kann er wohl keinen Weg berechnen. Die Meldung gibt leider das obere Ziel aus.
Falls du die automatisch genierierten Kurse nutzt, dann kann es gut sein, dass es dort noch Lücken im Kurs gibt und / oder sogar Wegpunkte übereinander liegen.
Falls möglich würde ich eine neue Config anlegen oder nutze auch gerne die von  Willi vorbereiteten Kurse:
https://discord.com/channels/640957956027973633/824619540016136202/921761865179222086

**Comment by Th301** [comment]
Moin Stephan,

danke für die schnelle Reaktion!! Aber normalerweise müsste er ja, wenn er voll ist den Punkt anfahren und dann auf den Abladepunkt springen. Das war ja im 19er auch so, evtl. musste man manuell auf "Weiterfahren" klicken.

Ich lade mir mal das Netz von Willi, danke!
Ivan hat in seinem Video auch gesagt, er würde sein Netz bereitstellen, allerdings hab ich das noch nicht gefunden ;)

Ich hätte noch einen Nachtrag.

Ich habe verschiedene Szenarien getestet.

1. (Vom initialen Post): Automatisch generiertes Streckennetz und Anbindung der Strecken über die Höfe mit der Neuen Kurvenfunktion. --> Strecke wird nicht gefahren.
2. Kein automatisch generiertes Streckennetz, der Kurs zwischen den beiden Silos wurde direkt eingefahren. --> Funktioniert wie es soll.
3. Automatische generiertes Streckennetz und Anbindung der Strecken über die Höfe ohne die Kurvenfunktion sondern direkte Punkt:Punkt Verbindung (manuell) --> Strecke wird nicht gefahren.

Habe vor jedem Test die Config gelöscht und neu erstellen lassen.

Es scheint also auf jeden Fall mit dem Automatisch generierten Streckennetz zu tun zu haben.

**Comment by Stephan-S** [comment]
Alles klar, danke fürs Feedback. Dann mache ich hier erstmal zu
