### ISSUE TITLE
Reverse Driving Tractors

### ISSUE THREAD

**Issue by HC1Gunner** [Stephan-S/FS22_AutoDrive#690]
Class and Valtra have had the purchase option of "reverse drive direction" for several versions of FS.

I bought a Valtra tractor with the reverse drive option, attached a Lacotec LH, and a kemper forage header. CP runs the vehicle just fine to chop corn, but my load vehicle running AD, lines up with the tractor, headed in the wrong direction, and has no idea the the vehicle is in reverse drive mode. I would have thought by now AD would have a settings option for this by now.

![FarmingSimulator2022Game_2022_09_16_16_29_22_167](https://user-images.githubusercontent.com/45585444/190727892-13b1d2bb-db57-45a0-a50d-c025ee14fce3.jpg)

**Comment by Axel32019** [comment]
Not related to reverse driving tractor - change the position of lacotec chopper to front and you see the same.
Mod issue: the mod is 180° rotated, which will not work with AD.
