### ISSUE TITLE
Idee für eine Parkplatzerweiterung

### ISSUE THREAD

**Issue by Obelixm** [Stephan-S/FS22_AutoDrive#691]
Hallo zusammen und vielen Dank für dieses GENIALE Programm.

Ich weis nicht ob sowas umsetzbar ist, ich wollte es einfach mal melden:

Sammelparkplatz, definieren eines Parkplatzbereiches (hintereinander)
z.B.
im AD definieren: P Drescher Start --> P Drescher Ende

Vorteil: Wenn man eine neue Karte anfängt muss man nicht für jedes Fahrzeug einzeln einen Parkplatz erstellen.
Bei vielen Maschinen (16-fach Karte), ein enormer Zeitvorteil.

Vielen Dank für´s lesen.

______________________
Google:

Hello everyone and thank you for this GENIUS program.

I don't know if something like this can be implemented, I just wanted to report it:

Collective parking lot, define a parking lot area (one after the other)
e.g.
define in AD: P Drescher start --> P Drescher end

Advantage: If you start a new map, you don't have to create a parking space for each vehicle individually.
With many machines (16x Map), an enormous time advantage.

Thank you for reading.

Obelixm

![Sammelparkplatz](https://user-images.githubusercontent.com/68119682/190846300-6afc3c19-8d3c-41d4-ac1f-0932516924af.JPG)

**Comment by hermannbrauer** [comment]
Das kannst du dich machen.

Lege eine Nebenstrecke an und setze dort den Punkt Drescherkette, dann weißt Du allen Fahrzeugen diesen Punkt als Parkplatz zu, jetzt wird die Drescherkette nach und nach von den Fahrzeugen gefüllt fertig. 

Dann sieht es aus wie auf dem Screenshot. Die Fahrzeuge sind dann aber nicht in der Lage die Strecke unabhängig von einander zu verlassen.

Somit macht es Sinn jedem Fahrzeug seinen expliziten Parkplatz zuzuweisen. Dann kann der Schlepper aus der Hechselkette den Kipper aus der Getreidekette nehmen und die Kartoffelkette unterstützen.

**Comment by Obelixm** [comment]
Danke für deine Antwort.

Genau soo habe ich es auch gemacht, deswegen kam ich auf die Idee. Der Nachteil bei dieser Art ist, das der Helfer immer noch aktiv ist, bis er den Punkt erreicht hat und somit 
a) Kosten verursacht 
und 
b) was schlimmer ist, auf die Performance geht, das ist grad bei grossen Karten und schwächeren PC´s nachteilig.

**Comment by Iwan1803** [comment]
Tja, so lange AD nicht den Zielpunkt erreicht, ist die Arbeit halt noch nicht beendet. Es wird dir nichts anderes übrig bleiben, als AD dann selbständig zu beenden.

**Comment by Obelixm** [comment]
Hi,
deswegen ja meine Frage, ob es möglich ist einen Parkbereich zu machen.
Also eine Strecke die komplett als Parkplatz angesehen wird (wie z.B. der Silobereich ist ja auch kein Punkt sondern ein Bereich).
Keine Ahnung ob das machbar ist, aber es wäre eine Idee.

Danke

Obelixm

**Comment by Iwan1803** [comment]
Wenn hunderte Spieler genau so spielen würden, könnte man darüber nachdenken. So ist es aber eher der Wunsch eines einzelnen.
Sorry, aber da lohnt sich der Aufwand im Vergleich zu Nutzen leider gar nicht.
