### ISSUE TITLE
When doing Counted Deliveries, Counts get's Reset to Start when Repair or Refuel is triggered.

### ISSUE THREAD

**Issue by allandata** [Stephan-S/FS22_AutoDrive#693]
If you are driving 6(or any number) of trips to the sellpoint to sell some crop, and after a Refuel or Repair is triggered while doing this delivery, the count is (re)set back to the original(6), hense moving too much material.

Have seen the same issue on versions 2.0.0.3 - 2.0.0.4 - 2.0.0.5 - 2.0.0.7

**Comment by Iwan1803** [comment]
Try the latest version: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
