### ISSUE TITLE
Probleme mit schrägen Ebenen -- AD-Fahrer bleiben einfach stehen 

### ISSUE THREAD

**Issue by redzacke** [Stephan-S/FS22_AutoDrive#694]
AD scheint mit Rampen und schrägen Flächen nicht klar zu kommen. AD-Fahrer bleiben bei Übergängen von horizontal -- ebenerdig zu schrägen Auffahrten/Rampen stehen. Auch andersherum, schräg zu ebenerdig,  passiert es genau so.

Ich nutze dabei das Streckennetz von [Willi Willswissen](https://hot-hq.de/index.php?user/16-willi-willswissen/)

FS22-Version 1.7.1.0
AD [Release 2.0.0.7] (https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.7)
Map: Haut Beyleron 
Aufgabe: Abtanken Feld 22 zu GCHB Getreidespeicher 

Hab ihr ne Idee, was das sein kann?

Beste Grüße
JayJo

**Comment by andreasthu** [comment]
das wird die "Kollisionshöhe über Grund" sein.
schau in deinen AD optionen, auf welcher Höhe die eingestellt ist, und stell sie dann schrittweise um 0,25m höher, solange bis es passt.
aber achtung, zu hoch sollte sie auch nicht sein, ansonsten erkennt AD den Strassenverkehr nicht.
lg
andreas

**Comment by redzacke** [comment]
Lieber Andreas, DU BIST MEIN HELD! Hab wie irre gestern Nacht noch alles mögliche ausprobiert und nix hat geholfen. 1,75 eingestellt und es läuft  :-D Vielen Dank!
