### ISSUE TITLE
Problem bei rotierend entladen

### ISSUE THREAD

**Issue by iljarogoff** [Stephan-S/FS22_AutoDrive#695]
Hallo,
ich habe ein Problem mit dem rotierenden Entladen. Manchmal geht es, meistens aber nicht. Zum Hintergrund: Fahrsilo (Standard Keilsilo) mit 2 Abladepunkten eingefahren, beide in einen Ordner gepackt. Das Sammeln/Abladen funktioniert soweit (Ladewagen sammelt per CP Grasschnitt und übergibt an AD wenn voll). Aber wenn ich "rotierend entladen" aktiviere, funktioniert der Wechsel zwischen den beiden Abladepunkten nur sehr selten. Ich würde gerne ein Log zur Verfügung stellen, aber welche Logchannels soll ich dafür aktivieren? Kann ich sonst noch Infos liefern? Screenshots, etc.?
Edit: noch so ne Idee: kann es was ausmachen, wenn man, während der Ablader unterwegs ist, mit einem anderen Traktor im Fahrsilo schon mal verdichtet?

**Comment by hermannbrauer** [comment]
nein, das Verdichten hat keinen Einfluss auf den Abladeprozess, außer natürlich du bleibst im Silo stehen wenn der Abfahrer kommt, dann scheppert es... 
problematisch ist es wenn du den Ablauf "störst" heißt du stoppst den AD zwischenzeitlich und startest dann wieder, das hat durchaus Einfluss

**Comment by iljarogoff** [comment]
Hab grad wieder eine Session am Laufen, Gras wird mit dem Ladewagen gesammelt und soll im Fahrsilo rückwärts abgeladen werden, einmal rechtsseitig, einmal linksseitig. Ich greife nicht ein, lass den Abfahrer einfach seinen Job machen. Und was tut er? Seit mittlerweile x-mal lädt er immer linksseitig ab. Es wird nicht rotiert. Aber was rede ich hier. Die Issues schaut sich doch eh keiner mehr an, an einer Fehlerdiagnose hat keiner ein Interesse. Schade, dass man die Hilfsbereitschaft der User ignoriert. Das Ross, auf dem man sitzt, ist wohl etwas zu hoch geworden.

**Comment by throsten** [comment]
> Hab grad wieder eine Session am Laufen, Gras wird mit dem Ladewagen gesammelt und soll im Fahrsilo rückwärts abgeladen werden, einmal rechtsseitig, einmal linksseitig. Ich greife nicht ein, lass den Abfahrer einfach seinen Job machen. Und was tut er? Seit mittlerweile x-mal lädt er immer linksseitig ab. Es wird nicht rotiert. 

Bei mir das Gleiche. Mal funktioniert der Wechsel, mal nicht. Eine Ursache konnte ich bisher noch nicht entdecken.

**Comment by Axel32019** [comment]
Bitte log mit Debug Pfadfindung anfügen.

**Comment by Axel32019** [comment]
"an einer Fehlerdiagnose hat keiner ein Interesse" -> closed
