### ISSUE TITLE
Running into a lot of "Can't calculate Path" all of a sudden.

### ISSUE THREAD

**Issue by TSO-Original** [Stephan-S/FS22_AutoDrive#696]
Running into a lot of "Can't calculate the path" when I'm maybe 100-200 feet from an autodrive network node. But if I drive to 20-30 feet away from the same node, and try autodrive again, it can calculate a path.

I am picking up grass with forage wagons, and it worked really well with straw, but I have 3 of 4 machines that quit when full and I have to drive closer to the network before they can sort out the route.

I thought the issue might be "Avoid Fruit", so I turned that off so they would drive over swaths, but that didn't change things at all.

**Comment by TSO-Original** [comment]
Tried reverting back to previous version of courseplay, no change.

**Comment by Tensuko** [comment]
And what does Courseplay have to do with AutoDrive Pathfinder?
You should provide a logfile with needed debugs for the guys of AutoDrive, else no one can help you...

**Comment by TSO-Original** [comment]
Which

> And what does Courseplay have to do with AutoDrive Pathfinder? You should provide a logfile with needed debugs for the guys of AutoDrive, else no one can help you...

Which logfile?

**Comment by Axel32019** [comment]
no update -> closed
