### ISSUE TITLE
Fehler mit Pumps N' Hoses DLC

### ISSUE THREAD

**Issue by Bone2510** [Stephan-S/FS22_AutoDrive#697]
Bei verwendung des Schouten HS 5100 und einem passenden Schlitzgerät wir der Arm des Geräteträgers übermäßig in die länge gezogen und beim Absenken des Gülleverteilers wird der Arm an dem der Schlauch befestigt ist nicht wieder zurück in die Arbeitsposition gebracht, sodass der Gülleverteiler auf dem Arm aufliegt.

Fehler 1
![soll](https://user-images.githubusercontent.com/67342543/192093739-e1a6eb88-71a2-4002-8939-d6974c30f47e.png)

Fehler 2
![fehler1](https://user-images.githubusercontent.com/67342543/192093740-e39f7983-ba12-4481-940c-37bdc864ceea.png)

So sollte es aussehen
![fehler2](https://user-images.githubusercontent.com/67342543/192093741-bcfe38be-8b44-45c0-9aaa-a1289dac1689.png)

**Comment by rohne83** [comment]
Was soll das denn mit AD zu tun haben? AD macht keine Feldarbeit

**Comment by Iwan1803** [comment]
Lt. Aussage von ProdaxCH gerade in seinem Stream wurde schon folgendes getestet:
- ist AD als Mod aktiviert (nicht AD aktiv für Feldarbeit), kommt es zu diesen Fehlern
- ist AD als Mod nicht aktiviert, ist alles ok

Da das DLC noch nicht released worden ist, können wir da auch nichts gegentesten.

**Comment by 97Lukas90** [comment]
![Farming Simulator 22 Screenshot 2022 09 27 - 13 33 59 92](https://user-images.githubusercontent.com/95321654/192514810-57c5e8b0-55c2-443c-bc11-5f6425dda512.png)

Kann den Fehler bestätigen. Ohne Autodrive läuft es, mit Autodrive treten die angesprochenen Fehler auf.

**Comment by RumsdeBums** [comment]
Heute das DLC gekauft und kann die Fehler die AD verursacht bestätigen.

![fsScreen_2022_09_29_13_23_29](https://user-images.githubusercontent.com/91734705/193124849-16d5e80f-68f8-4330-8c0b-1e4969398424.png)

Ist AD aus dem Modordner entfernt ist alles i.O.
Wurde auch im GIANTS Forum bestätigt.

**Comment by JCB2904** [comment]
Moin, bei mir ist das auch das Problem mit AD

**Comment by Iwan1803** [comment]
Erstens interessiert uns das Giants-Forum nicht und zweitens hilft es uns nicht, wenn jeder sagt, das er den Anzeigefehler hat aber keine weiteren Infos liefert. Eine Log wäre z.Bsp. mal interessant...

**Comment by RumsdeBums** [comment]
Die log.txt ist sauber. Der, der das bestätigt hat ist von VertexDezign. Das sollte Euch schon zu denken geben bzw. interessieren.

**Comment by rohne83** [comment]
> Die log.txt ist sauber. Der, der das bestätigt hat ist von VertexDezign. Das sollte Euch schon zu denken geben bzw. interessieren.

Nö, warum? Auch wegen VertexDezign wird man keine Ausnahme machen, sprich: Issues laufen über Github. Und nicht übers Forum oder Youtube-Kommentare oder Insta-Stories oder weiß der Geier was.
Fehler ist bekannt laut Aussage von Iwan vor 7 Tagen (siehe oben), aber außer "ich hab das Problem auch" hat bisher noch niemand was hier drunter geschrieben, das bei der Fehlersuche auch helfen könnte.

**Comment by RumsdeBums** [comment]
So, hier mal die log.txt
Damit das Team von AD sieht, das es keine Fehler gibt. Weder zu AD noch zum DLC.

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9690111/log.txt)

**Comment by Grisu118** [comment]
Ich hab das Problem lokalisiert, PR mit einem fix ist in Arbeit.

**Comment by Tensuko** [comment]
1) Kein Fehler in der log heist noch gar nichts
2) 

> Das sollte Euch schon zu denken geben bzw. interessieren.

Solche Aussagen würde ich mir sparen, wenn ich etwas erreichen möchte, nur mal als Hinweis.
Ein logfile ist IMMER gefordert, genauso wie erkenntnisse durch ausprobieren, dieses "hab auch das Problem" hilft niemanden.

**Comment by RumsdeBums** [comment]
Es wird eine log.txt gefordert. Dann kommt die log.txt und das ist auch wieder nicht RICHTIG.

Ich hatte oben auch geschrieben das, wenn AD aus dem Modordner ist läuft es!

Der einzige der  was positives schrieb, ist Grisu118.

> Solche Aussagen würde ich mir sparen, wenn ich etwas erreichen möchte, nur mal als Hinweis.

Nun ja, wir als die Com haben eh keine Ahnung und machen nur mimimi.

**Comment by FruchtigerZwerg** [comment]
Selber Fehler, mit AD, ohne AD alles ok.

**Comment by RumsdeBums** [comment]
Das Fix hat Grisu118 schon fertig.

https://github.com/Stephan-S/FS22_AutoDrive/pull/701

**Comment by FruchtigerZwerg** [comment]
ok, dann mal warten, solange mal am Hof weiter bauen, dankeschön und noch einen schönen Abend an alle.

**Comment by RumsdeBums** [comment]
> ok, dann mal warten, solange mal am Hof weiter bauen, dankeschön und noch einen schönen Abend an alle.

Kannst du dir schon laden.

**Comment by FruchtigerZwerg** [comment]
finde ich nicht, habe 2.0.0.7 aber funktioniert nicht

**Comment by RumsdeBums** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/pull/701

**Comment by RumsdeBums** [comment]
> finde ich nicht, habe 2.0.0.7 aber funktioniert nicht

[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/9690674/FS22_AutoDrive.zip)

**Comment by Iwan1803** [comment]
Kann jemand bestätigen, das der Fix auch wirklich zuverlässig funktioniert?

**Comment by JDFendtLS11** [comment]
Habe den Fix seit 7 Tagen laufen. Mit Pumps N' Hoses läuft seitdem alles wie es soll. Vielen Dank dafür.

**Comment by NeonRider1999** [comment]
Also ich habe mir gerade die Dev von Stephan geladen und bei mir existiert der Fehler immer noch

**Comment by Iwan1803** [comment]
@NeonRider1999 dann lad dir mal meine Dev runter. Dort ist der Fix für P'n'H enthalten.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
