### ISSUE TITLE
Auger Needs Engine on to empty

### ISSUE THREAD

**Issue by BrutalRIP** [Stephan-S/FS22_AutoDrive#70]
augers cannot be emptied at the side of the field in 2 stages as the engine is required to be on for the auger to work by the time the second trailer turns up the engine is off and won't unload the auger and the combine just sits there calling ad but ad is waiting for the auger to empty

An option to not turn off the engine when  waiting for unload in ad would solve this issue

Or an option to sense a vehicle on unloading zone to turn on engine.. If it was just with a vehicle in the vicinity, queueing stuff would cause all to keep running.

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
