### ISSUE TITLE
Repeating Error OldFunc

### ISSUE THREAD

**Issue by DieHardTony** [Stephan-S/FS22_AutoDrive#700]
Receive this error on "OldFunc" 
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9689417/log.txt)

2022-09-30 21:59   Error (C:/Users/dieha/Documents/My Games/FarmingSimulator2022/savegame10/vehicles.xml): Failed to validate xml path 'vehicles.vehicle(0).FS22_AutoDrive_2_0_0_7.AutoDrive#mode' for 'savegame_vehicles'. Path not registered.
2022-09-30 21:59 LUA call stack:
  dataS/scripts/xml/XMLFile.lua (384) : printCallstack
  dataS/scripts/xml/XMLFile.lua (275) : getValueType
  =E:/iDriveBackup/iDriveSync/IDrive-Sync/ModBackups/FS22Repo/FS22Mods/FS22_AutoDrive_2_0_0_7/scripts/Modules/StateModule.lua (158) : setValue
  =E:/iDriveBackup/iDriveSync/IDrive-Sync/ModBackups/FS22Repo/FS22Mods/FS22_AutoDrive_2_0_0_7/scripts/Specialization.lua (467) : saveToXMLFile
  dataS/scripts/vehicles/Vehicle.lua (1401) : saveToXMLFile
  dataS/scripts/utils/VehicleLoadingUtil.lua (640) : saveToXMLFile
  dataS/scripts/utils/VehicleLoadingUtil.lua (673) : saveVehiclesToSavegameXML
  dataS/scripts/FSCareerMissionInfo.lua (336) : save
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/missions/SavegameController.lua (450) : saveToXMLFile

This is a repeating error which fills the log then eventually shutsdown game.

**Comment by Axel32019** [comment]
Do never rename the zip  FS22_AutoDrive.zip , like you did: FS22_AutoDrive_2_0_0_7

**Comment by DieHardTony** [comment]
Thank you for the quick response
