### ISSUE TITLE
Question- Option to not let autodrive manipulate lights on vehicle? 

### ISSUE THREAD

**Issue by dozerjz** [Stephan-S/FS22_AutoDrive#703]
Is / could there be an option to not let auto drive manipulate the lights on the vehicles?  I would like to be able to set the hazards on the tractors when transporting from field to field, keep all the lights on when around the edges of the field, etc.  Is there something i could edit on my own to make this work?  Thank you for all you do!

**Comment by Iwan1803** [comment]
And why should there be such an option?

**Comment by TobiHH78** [comment]
Das schreibt er doch...
"I would like to be able to set the hazards on the tractors when transporting from field to field, keep all the lights on when around the edges of the field,"

Er möchte die Arbeitslichter auch außerhalb des Feldes aktiviert haben.

**Comment by Tensuko** [comment]
Jedes Licht in jeder Situation extra einstellen zu können und die Einstellungs Seite platzt aus allen Nähten.... (tut sie jetzt schon meiner Meinung nach).

**Comment by dozerjz** [comment]
> And why should there be such an option?
It is not just for the working lights, but when I am following a combine with a header from field to field, it would be cool to be able to have the hazards on, and when the tractor is in combine mode sometimes they run outside of the field, and the lights turn on and off- it is more for the roleplaying aspect

**Comment by dozerjz** [comment]
> Being able to adjust each light separately in each situation and the settings page is bursting at the seams... (I think it already is).

and to answer Tensuko, if there was an option to not have autodrive have to deal with it, wouldn't that help the situation? It is just a thought, and I am trying to learn how everything works- hopefully some day I can learn how .lua files work and be able to tweak things for personal use, until then I am at the mercy of the designer :)

**Comment by Iwan1803** [comment]
Makes for us no sense to let AD drive with work lights on streets.
