### ISSUE TITLE
"Gedenkminute" beim Lexion

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#704]
Hallo Leute, 
Hab die letzt version von dev_axel und da fällt mir auf, das der claas Lexion (original von giants) immer eine Gedenkminute braucht von "kurs starten" bis zum tatsächlichen losfahren.
Es ist egal ob der Zielpunkt 1km oder 10m entfernt liegt, ich drücke auf abfahrt und muss ne gute Minute warten bis der lexion anfährt. Auch wenn ich ihn stoppe und wieder weiterfahren lasse, dauerts eine minute bis anfahrt.
Bei allen anderen Traktoren, Dreschern oder LkW"s hab ich das nicht. Diese setzen sich unmittelbar in Bewegung.
Was kann da sein?
Lg
Andreas

**Comment by andreasthu** [comment]
Ach, ich seh gerade das es eine neue dev von axel gibt, werd mir das später mal ansehen, ob das da funktioniert 
Lg
Andress

**Comment by regs1980** [comment]
Hat er schon behoben #679

**Comment by andreasthu** [comment]
Danke, funktioniert nun.
Lg
Andreas
