### ISSUE TITLE
Traktor fährt einmal um die Map statt direkt

### ISSUE THREAD

**Issue by DerD3vil** [Stephan-S/FS22_AutoDrive#709]
![unknown](https://user-images.githubusercontent.com/34687401/194939052-90ea0dd5-ed77-453d-b6f7-dbdc6108a724.png)

Mein Abfahrer beginnt am start und fährt die Schwarz markierte route bis zum ladepunkt am Gelben Marker beim Wasser. Danach fährt er leider nach Süden auf die Hauptstrasse, anstatt er die Strecke zurück fährt zum Start wo er abladen soll.
Ich habe bei jeder Einfahrt zur Nebenstrecke die zu und abfahrten als Hauptstrassen gemacht und die Feldwege sind als beidseitig befahrbare Nebenstrecken drin.
Woran kann das liegen?

**Comment by manne70** [comment]
Es fehlt irgentwo eine Verbindung so das er nur die lsnge Strecke berechnen kann. Must du halt suchen wo sie fehlt.

**Comment by DerD3vil** [comment]
Es liegt nicht an den Verbindungen, diese sind allesamt verbunden. Ich habe den Maximalen Umweg von 100m auf 10m gesenkt. Jetzt fahren sie Teilweise kürzere wege. Begegnen sich aber auch gelegentlich auf den Doppelweg-Nebenstrassen
