### ISSUE TITLE
Abfahrer versenkt sich im See

### ISSUE THREAD

**Issue by Altbachfreak** [Stephan-S/FS22_AutoDrive#71]
Hallo, habe nun schon öfter das Problem gehabt, dass mein Abfahrer sich auf Haut-Beyloron im See versenkt hat.
Dies passiert immer beim Abfahren vom Häcksler auf den Feldern 30 und 33. Er holt dann ewig weit aus und weg ist er. Teilweise fährt er dann nach 5 min. einfach wieder los als wäre nie etwas gewesen.

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
