### ISSUE TITLE
Park when job finished

### ISSUE THREAD

**Issue by Misamangame** [Stephan-S/FS22_AutoDrive#711]
Hello guys,

I very much like Parking function after job is finished and I was thinking if there is some way to add function Refuel & park after job is finished. Meaning vehicle will go fill up (whatever amount of fuel is left in fuel tank) and then park automatically. Reason is I would like to have my vehicles tank full for next job and sometimes even when I  want to park after job I have to send them to refuel manually and then park. Yes I know it is just laziness but if something like that would be possible it will be great :)

**Comment by Iwan1803** [comment]
You can assign AD keys to drive vehicles to refuel, repair and park.
F.e. i used CTRL+ALT+T for refueling, CTRL+ALT-R for repairing and CTRL+ALT+P for parking.
If i press CTRL+ALT+T and directly after it CTRL+ALT+P, AD will drive refuelling if needed and after that it drives to the parking place.

**Comment by Misamangame** [comment]
I had set up keys for Parking but actually never used them easier was click on Icon in HUD :)  But ok I set up Refuel as well and it works perfectly even if you press it during the way to some other destination vehicle goes for refuel which is great. So now I only have to learn to use them automatically :).  Thx @Iwan1803

**Comment by Iwan1803** [comment]
You're welcome 😉
