### ISSUE TITLE
Driving trailer under Beet Harvest Pipe fails

### ISSUE THREAD

**Issue by Timmeey86** [Stephan-S/FS22_AutoDrive#712]
Issue:

The tractor which is supposed to drive under the pipe stops early (see screenshot) while still in state "Drive to combine pipe", then alternates between that state and "Searching clear area" endlessly.

Equipment used:

"Harvester":
Massey Fergtuson MF 6718S (Headleandmanagement, GPS, Narrow Tires if any of that matters)
Grimme FT 300 (Front Beet harvester)
Grimme Rootster 604 (Back Beet harvester with pipe)

Trailer Tractor:
Fetor Proxima HS 120 (with Front Loader)
Brantner Z 18051/2 XXL Power Flex (with Cover)

![grafik](https://user-images.githubusercontent.com/10223149/195206587-fcd7d371-8458-4e06-b714-166c031160f5.png)

The "harvester" will always drive a curve before unloading, not sure if that's the autodrive or the courseplay mod

The harvester won't always drive a curve, sometimes it'll stay and sometimes it'll drive backwards to the side at an angle, but straigthened out

**Comment by rohne83** [comment]
This "curve" by the harvester is CP. It is the pocket he creates when 95% full in first headland or if there's fruit under the pipe/conveyor, to allow unloading into trailer without having the unloader to drive into fruit or off field. Unfortunately for the machines you use this 95% setting is too late, for the pocket to be created completely. You can disable this behaviour by deactivating avoid fruit setting in harvester's CP settings.
Maybe this could also help with your unloader. Or you try the CP unloader mode.

**Comment by Timmeey86** [comment]
Alright thanks, I'll close the issue in that case
