### ISSUE TITLE
[Feature Request] Junction/Point presets

### ISSUE THREAD

**Issue by emwedk** [Stephan-S/FS22_AutoDrive#714]
Delete if not allowed to "request" features or ask if it might be done in the future

i have a couple rough blueprints of 4 way (21 point) and T junctions (~half) which focus on longer vehicles being able to turn without colliding with anything.

however it's fairly tedious to do 100-200 times for a map 

so if it could be possible to where you can select multiple points (maybe a button when you press it, it will save the ones u click on - clicking it again, if any's selected it will make you enter a name) Save it as a preset and then having a menu where you can spawn the preset.

(ofcourse a junction is never gonna be completely alike another but this removes the need for clicking to add lines and clicking to add points - but then you can move the premade ones around) 
it's probably been discussed before but i couldn't find anything about it here

( you could also use that same button (to select multiple points) to be able to move multiple points at the same time ) which i bet has also come up as a request?

//Emwe

**Comment by Iwan1803** [comment]
Copy&Paste of waypoint selections can be done by using the Java editor: https://github.com/KillBait/AutoDrive_Course_Editor
