### ISSUE TITLE
Güllefass mit optionalem Schleppschlauch

### ISSUE THREAD

**Issue by SAM24986** [Stephan-S/FS22_AutoDrive#719]
Moin Moin,
Ich benutze zum Gülleausbringen CP, die Fahrt zur Ladestelle und wieder zurück zum Feld erledigt AutoDrive. Das funktioniert in soweit auch sehr gut, mit der Ausnahme das der AD Fahrer mit eingeschaltetem Fass fährt. Dieser Zustand gilt aber nur für Güllewagen, bei denen man das Schleppschlauchgestänge extra montieren muss, alle anderen mit fest eingebautem Gestänge funktionieren einwandfrei, ebenso alle Selbstfahrer. Auch alle anderen optionale Geräte wie Schlitzgestänge oder Güllegrubber funktionieren tadellos. Das Fass ohne montiertes Gestänge geht übrigens auch tadellos, erst wenn das Gestänge angekuppelt wird ändert sich das. 
Meine Vermutung ist dass dieses Problem erst in der Kombi ausgelöst wird.
Das fängt auch erst mit der Version 2.0.0.6 an, davor war alles gut.
Vllt schaut ihr da ja mal drüber.

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9838777/log.txt)

**Comment by andreasthu** [comment]
kann ich so bestätigen:
![fsScreen_2022_10_25_17_30_36](https://user-images.githubusercontent.com/24860501/197817425-61ae08c6-8983-4305-b3f1-b1462e8d0c64.png)
lg
andreas

**Comment by Axel32019** [comment]
Verhalten wie #662
