### ISSUE TITLE
Sämaschine mit Dünger und Saatgut laden klappt nicht

### ISSUE THREAD

**Issue by SaschaLie** [Stephan-S/FS22_AutoDrive#72]
Hallo
Die Sämaschine mit Dünger und Saatgut laden klappt noch nicht. Einstellungen: Fahrt zum Feld xy mit Aufladen Dünger und Saatgut. Beide Silos stehen direkt hintereinander, erst Dünger, dann Saatgut. Eingestellt ist im AD Saatgut. Sämaschine (Pöttinger Terrasem C6F) lädt nur Dünger und will dann zum Feld. Zielpunkt ist weit genug auch für Saatgut. Abstand Silos auf 50m eingestellt. Sämaschine mit nur Saatgut klappt.
Foto 1 lädt sie gerade Dünger, Foto 2 ist sie umgesprungen auf das Feld und fährt ab
![Saat1](https://user-images.githubusercontent.com/96572157/147221981-0feea996-74f8-4561-899b-3bd81642365e.jpg)
![Saat2](https://user-images.githubusercontent.com/96572157/147221985-7f98f7cb-30f9-42e7-810f-90e1e6829504.jpg)

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
