### ISSUE TITLE
Missing function.

### ISSUE THREAD

**Issue by taarhn** [Stephan-S/FS22_AutoDrive#720]
Hello, 

I have a problem in the autodrive settings, I can no longer access the "setting debug " (bezel icon). 

The icon does not appear anymore. What is the problem?

Thanks for the mod.

**Comment by Iwan1803** [comment]
You need to activate the console for FS22 in the game.xml:
![image](https://user-images.githubusercontent.com/47528836/202989136-c10750c3-8413-479b-a9cd-e3d89adbfa5e.png)

**Comment by taarhn** [comment]
Hello,

Thank you for your reply.

Sincerely
