### ISSUE TITLE
Aktuelle Ziele speichern

### ISSUE THREAD

**Issue by Gerrar99** [Stephan-S/FS22_AutoDrive#721]
Hallo,

gibt es die Möglichkeit beim AD die aktuellen Ziele, z.B. beim "Drescher abfahren", zu speichern, so dass ich nicht jedes mal wenn ich das Spiel starte alles neu einstellen muss? Ist besonders beim Häckseln nervig bei 10+ Fahrzeugen.

Freue mich auf jede hilfreiche Antwort und bedanke mich dafür im Voraus :)

VG
Gerrit

**Comment by SAM24986** [comment]
Du kannst dafür Ordner verwenden. Du öffnest die Optionen, im Reiter mit der Weltkugel findest Du den Menüpunkt " Ordner verwenden" den stellst Du auf ja. Anwenden, das Menü wieder verlassen. Dann in den Editier-Modus gehen, den Ziele Reiter öffnen. Oben siehst Du dann ein grünes Plus, da klicken und Dir einen Ordner erstellen, Bsp Feld 1, bestätigen. Im Editier-Modus kannst Du dann alle Ziele, die mit z.B. Feld 1 zu tun haben, per Drag and Drop einfach in den Ordner ziehen. Das geht aber nur im Edit-Modus.

**Comment by Gerrar99** [comment]
Dass man Ordner erstellen kann weiß ich. Das habe ich auch. Nur ich will, dass die eingestellten Ziele beim Starten des Spiels eingestellt bleiben. So dass ich nur auf Starten klicken muss.
Gerade bei den Abfahrern ist es nervig, weil ich ja das Feld und die Abladestelle neu einstellen muss.

**Comment by SAM24986** [comment]
Hab das jetzt mal getestet, bei mir bleiben alle Einstellungen erhalten, so wie ich das Spiel beendet habe. Bei Dir ne' Mod drin die das verhindert?

**Comment by Gerrar99** [comment]
Nein, selbst wenn ich nur Autodrive habe, bleiben die Ziele nicht gespeichert. Dann geht das wohl nicht...

**Comment by MeRida2104** [comment]
Sowas würde mir ebenfalls sehr helfen. Wie du schon sagst: Beim Mais häckseln ist sehr nervig, wenn man bei x Abfahrern jedes Mal das gleiche einstellen muss. Speicherbare "Routen" wären hier sicherlich hilfreich. Sprich man stellt seine Start-Ziel Punkte ein und kann diese Konfig einfach speichern und mit einem Namen versehen. Beim nächsten Fahrzeug muss dann nur noch die gespeicherte Start-Ziel Konfig geladen werden.

**Comment by Iwan1803** [comment]
aus den Release Notes:
`Fahrzeugeinstellungen (z.Bsp. Abholne&Abliefern) sind nach einem Neustart verschwunden #609`
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
