### ISSUE TITLE
Tractor stops and does not unload Harvester.

### ISSUE THREAD

**Issue by Gibbanator** [Stephan-S/FS22_AutoDrive#723]
Please excuse if I am putting this in the wrong area I see no bug report area. Using CP 7.1.1.5 and Auto Drive 2.0.0.7  The Tractor stops and will not continue like there is a collision or something stopping it. It clearly has plenty of room to move forward. Here is a video on the problem. https://youtu.be/xpkfCA-EqlE I can repeat the action if needed so if you need me to do anything I can replicate it.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/9875667/log.txt)

**Comment by Misamangame** [comment]
Problems with unloading from auger wagons/sugar/potato harvesters hopefully will be solved with next release

**Comment by Axel32019** [comment]
Not reproducible, but:
- >2 maps in mod folder, i.e. Bergland, FS22_BackRoadsCounty, FS22_DondiegoMap
- many errors not related to AD, no error related to AD
Please clean up mod folder, use only AD and CP and try to reproduce.

**Comment by OldnRustyNoob** [comment]
Did exatly same thing to me today, worked perfectly first. Suddenly stopped unloading.

**Comment by OldnRustyNoob** [comment]
I found a solution for this (most likely read The faq and learn to use AD lmao.) Will drop a hinta here when i find it again. Something that Harvester (any type) has to Be unfolded,Pipe on before you start that AD carrier, so it can count The collision box from Harvester. Got IT going with vanilla grimme potatoharvester, allthought i hate to Harvest potatoes topped. Pain in The a#€ to try and Harvest them. Trying to get it going with other toys. 

AD made great work last night with a Combine, worked perfectly well Even with unloading when moving, exept My personal mistake, i accidentally hitted "fold table", and that caused him a huge headage, need to save, quit, start again and first fold The header, 

(in Finland straight translation for header IS "cutting table"sorry For that)

After reloading The game, i first un-/folded header completely, then setted carrier on his route. After that i harvested several Fields and IT worked absolutely like a greased lightning.

**Comment by OldnRustyNoob** [comment]
Solution so far (Works with Grimme 290 mod also, looks like The collision height with ropa potato Harvester causes The issue)

1. Set The "collision height over ground to highest, (found from "settings-autodrive") on both, Pipe offset to 0.7 and distance Combine to 1.0 Meter (found under "vehicle settings")
2. Make sure that The Harvester has The same field assigned. Keep The Harvester unfoded.
3. Set The carrier to The route and let it drive one pass around.
4. Unfold The Harvester and get it going !!WITH PIPE IN!! 
5. Enjoy 😉

**Comment by Iwan1803** [comment]
No further feedback -> closed.
