### ISSUE TITLE
Português Brasileiro - idioma

### ISSUE THREAD

**Issue by Wellison94** [Stephan-S/FS22_AutoDrive#724]
O jogo fica com o hud todo bugado quando troca o idioma para "brazilian" (Português Brasileiro). Atualmente jogo na versão 1.7.0 do jogo.
![Sem_titulo](https://user-images.githubusercontent.com/101759946/198346604-1f35df2b-4a60-45ab-8ddc-894595524c60.png)

**Comment by Iwan1803** [comment]
There is allready an brazilian language file inside AD (translation_br.xml):
https://github.com/Stephan-S/FS22_AutoDrive/tree/main/translations
Which AD version are you using exactly?

**Comment by Myiamoto86** [comment]
Dear,

Goodnight.

With this version translated by me, there is no problem. It has already been revised for the new version of autodrive.
[translation_br.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10150135/translation_br.txt)

**Comment by Axel32019** [comment]
see #646
