### ISSUE TITLE
Kollisionserkennung im Fahrsilo

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS22_AutoDrive#725]
Hallo,

ist es möglich dass ihr in Durchfahrsilos eine Zone einrichtet (+50m vorne und hinten) wo die Kollisionserkennung (bei trotzdem eingeschalteter Koll.erk.) nicht gilt?

LG
Eric

**Comment by Iwan1803** [comment]
Zur Lösung eines nicht bekannten Problems? Welchen Sinn soll das machen?

**Comment by eric4072** [comment]
Hallo, Problem würde ich nicht sagen, es ist eher ein Effekt der vor allem ab halb gefüllten Silos auftritt...

Da die Steigung beim einfahren und verlassen des Fahrsilos zu extrem wird, löst die Kollisionserkennung immer eine Bremsung aus. Das Fahrzeug bleibt dann mit 10% Füllstand am Ende des Silos stehen. Deaktiviert man in diesem Fall die Kollisionserkennung, fährt das Fahrzeug weiter. Auch beim einfahren in den Silo tritt das auf, vor allem wenn die Steigung zu groß wird.

Beim Betrieb von 2 oder mehr Häckslerketten muß man alle 3 min somit die Kollisionserkennung abschalten. Würde diese bei den Fahrzeugen automatisch im Silo deaktiviert werden, würde AD ganz normal stundenlang ohne Probleme laufen. ich habe die Kollisionshöhe auf 2,5m gestellt, eine weitere Erhöhung macht aber am Rest der Karte nicht wirklich Sinn, da die Fahrzeuge dann keine Zäune und Ähnliches mehr erkennen.

Gibts da nicht die Möglichkeit diese Funktion einzubauen?

Danke und LG

Eric

**Comment by Axel32019** [comment]
Mal schauen...

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
