### ISSUE TITLE
generelles Hud deaktivieren

### ISSUE THREAD

**Issue by Mc-Games** [Stephan-S/FS22_AutoDrive#726]
Hallo, steige ich in ein Fahrzeug, habe ich sofort das AD Hud. Kann man dies vermeiden und erst mit einer Taste aufrufen?
Danke für eine hilfreiche Antwort!

**Comment by cwattyeso** [comment]
Been asking 6 months for this to be changed/fixed and unfortunately Autodrive Devs don't see it as an Issue or a Bug that they in fact created, so it won't likely get fixed.

**Comment by Axel32019** [comment]
#765
