### ISSUE TITLE
Mittlere Maustastehält Bubble fest...

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#73]
Hi, 

wenn viele Punkte vorhanden sind (z.B. Kreuzung) und man klickt die MB und die Maus ist über einem Bubble dann wird dieser festgehalten. Wenn man dann fährt und woanders wieder die MB drückt haste dann auf einmal diesen Bubble mitgezogen.

LG

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
