### ISSUE TITLE
Kein Weg gefunden 

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#730]
Hallo
Wie man auf den Bild sehen kann ist rechts unten bei den Kursen das Feld als Abfahrpunkt eingestellt und der Getreidehandel als abkipppunkt eingestellt. Es steht aber oben kein Weg zum Parkplatz gefunden. Wo dran liegt das
![Findet den Weg nicht](https://user-images.githubusercontent.com/47453761/198897039-f2e48678-472e-484e-b8d5-e44f766b2e32.png)

**Comment by Iwan1803** [comment]
Du hast mehrere 7R und vielleicht möchte ein anderer gerade parken fahren.
Ich würde dir den Tip geben, den verschiedenen Fahrzeugen sprechende Namen zu geben
Hierzu muss man in den Tastenbelegungen eine für "AD: Vergebe Fahrer Namen" belegen.
