### ISSUE TITLE
Feature Suggestion: Thickness Setting ?

### ISSUE THREAD

**Issue by Rantory** [Stephan-S/FS22_AutoDrive#731]
Hello Together,

I like to alter my Lines in Edit-Mode when zoomed out a bit, however the Lines, Colors and Arrows can be hard to see, depending on the Ground underneath them.

So i ask if it would be Possible to add an adjustment Setting for the Thickness of the Lines between Points and the Arrows aswell.

Also Thanks for the Amazing Mod and Work on it :)

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
