### ISSUE TITLE
Tractor stops at intersection

### ISSUE THREAD

**Issue by DeereJ18** [Stephan-S/FS22_AutoDrive#732]
I have discovered an issue with my tractor stopping at this point in the course. 

https://youtu.be/cDCSAhxKh70

What I have tried:
-Redoing the point near the intersection
-Restarting game

Is there a way to determine the cause? This is the only point on the map so far that has had this issue

**Comment by DeereJ18** [comment]
I adjusted the points and it works now, but why?

https://youtu.be/Ozux7kBm7Fc

**Comment by fudoido** [comment]
maybe something with the "collision from ground" setting? i learned that some time ago and always put it to 2.0 now, it actually says 2.0 is the default, but for some reason when starting a new map, it actually starts autodrive with that setting on 1.3 value, not the "default" 2.0, and changing it has prevented me alot of the vehicles stopping on roads for no reason.....
