### ISSUE TITLE
Wild West Map Fehler

### ISSUE THREAD

**Issue by HANES65** [Stephan-S/FS22_AutoDrive#733]
Hallo,

Ich habe mein savegame geöffnet und Bei Dem Fenster "Streckennetz Generierung" Auf "Ja" gedrückt. Wenn ich jetzt im Menü auf die karte gehe verschwinden alle Icons Auf der karte und im Menü. Wenn ich das Menü verlasse Werden Das tacho, Etc. nicht mehr angezeigt.
<img width="1440" alt="Bildschirmfoto 2022-11-01 um 11 46 51" src="https://user-images.githubusercontent.com/117165603/199216658-19d511c7-3b89-4a4f-a128-a296216d8308.png">
<img width="1440" alt="Bildschirmfoto 2022-11-01 um 11 46 42" src="https://user-images.githubusercontent.com/117165603/199216688-a8061c4a-fc12-47a6-ae2e-a8acce3b9adc.png">

**Comment by Iwan1803** [comment]
Log?

**Comment by HANES65** [comment]
<img width="1440" alt="Bildschirmfoto 2022-11-07 um 06 17 05" src="https://user-images.githubusercontent.com/117165603/200232418-eacbc799-c585-4eb0-ae26-5bb77a87560c.png">

**Comment by f4mous96** [comment]
die gesamte log ist gemeint aus dem verzeichnis : \Documents\My Games\FarmingSimulator2022

**Comment by Axel32019** [comment]
no log -> closed
