### ISSUE TITLE
Display help not hidding keybinds

### ISSUE THREAD

**Issue by brown-star** [Stephan-S/FS22_AutoDrive#734]
I have display help set to no and have refreshed the save game, however I still get AD keybinds in the F1 menu.
![FarmingSimulator2022Game_otMXOSwZvS](https://user-images.githubusercontent.com/40640300/200057770-fdd11880-6b7a-4d8e-b6aa-5c0f13ea8657.png)

**Comment by Rantory** [comment]
Had the same issue at first, changed it to no -> accept the change ->back into the menue ->save as default ->switch vehicle
That solved it for me

**Comment by Tensuko** [comment]
Re enter vehicle after turn it off.

**Comment by HorkayZolee** [comment]
Edit the AutoDriveUsersData.xml in current savegame folder
showHelp="2" to showHelp="1"
