### ISSUE TITLE
Suggestion: Maximum trigger detection values

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS22_AutoDrive#735]
Hello team. Would it be possible to change the values of the maximum trigger detection by different increments, maybe by 10 unit increments instead of the way it is now?

Situation: Playing on Landownunda map, using a setup with a man truck + dolly + 2x Krampe SKS 30/150 trailers.
Due the length of the setup, i put trigger distance to 50m, 25M was too short to make a proper use of auger wagons with this setup. 50M has been working great for it, BUT not so good for other things. Using a bale loader trailer and sending it to sell bales, the tractor detects the trigger while it is still in the road and drops the bales in the road (doesn't even enter the area of sale, dumps them straight in the road some meters on the side), and then when using 25M trigger detection it works fine, but it will be a short value for the other setup, generating a big conflict in which values to use.....

By adding increments of 10 values, or maybe even 5, we could fine tune this setting and make it work along with more options. In my case, imagine the actual best value would be 35m, or 40m, a different value that would work for both situations..... would be exceptional if we could set it in smaller increments, or even maybe write it in a selection box?

Also, this option could be a vehicle only setting instead of a global setting, maybe that way each vehicle could have its own trigger detection distance and wouldn't conflict with other routes, and keep the current values for detection maybe, although i feel that 10m increments would be much better for us players.

Best regards and thanks for the attention, hope to get feedback soon.

**Comment by Misamangame** [comment]
Having same issue all the time. On the farm I planned the routes in the way that he will go straight for unloading even with 50m trigger but ofcourse it is not possible for many bale sales on different maps.  I don't mind to leave values as they are but moving it to vehicle settings instead of global with default 50m will be nice.  But maybe it is there for some reason...

**Comment by fudoido** [comment]
i think having the setting per vehicle instead of general would help very much, if creating different values is too much work.

**Comment by Axel32019** [comment]
implemented in #962
