### ISSUE TITLE
[Feature Request] Universal Autoload integration 

### ISSUE THREAD

**Issue by emwedk** [Stephan-S/FS22_AutoDrive#737]
Universal Autoload integration 

since unlike apalletautoload, it's 100x easier to set up a new trailer and every basegame trailer is already premade
and with "FS22_UniversalAutoloadModhubAddon" you got almost every modded trailer set up aswell

with apalletautoload, if u want a basegame trailer defined, u have to remake it into a new mod ...
with universal, u don't have to do anything since its premade, but IF it wasn't, u'd just have measure some numbers from GE and add a few lines of code

**Comment by regs1980** [comment]
has already made someone must only be taken over https://github.com/schwiti6190/FS22_AutoDrive/commit/300eb6a3cd43e178a3691f5bf87dfbe2c9de4b60 and https://github.com/loki79uk/FS22_UniversalAutoload/commit/9916bc6ea3b8e5203c4d410a7dc53fb3b3cb5818

**Comment by emwedk** [comment]
awesome ! thanks @regs1980

**Comment by Axel32019** [comment]
not taken over from schwiti
implementiert: https://github.com/Stephan-S/FS22_AutoDrive/commit/140a7d66dc59befc45b8bbb3e7a20d66019b74a5

**Comment by Axel32019** [comment]
fixed Release 2.0.1.2
