### ISSUE TITLE
AD mit Ladewagen fährt nach Abladen nicht weiter

### ISSUE THREAD

**Issue by VJH01** [Stephan-S/FS22_AutoDrive#74]
Hallo zusammen,
AD fährt nach dem Abladen mit dem Ladenwagen nicht weiter. Das Heu/Stroh/Silage/Häckselgut wird normal entladen, Klappe schließt sich und der Abfahrer fährt danach nicht weiter. Problem tritt nur auf, wenn der Siliermitteltank am Ladewagen noch befüllt ist. Wenn er von vorn herein leer ist gibt's keine Probleme. Vermutlich versucht er ihn auch zu entleeren und schafft es nicht, deshalb bleibt er stehen.
Grüße und frohe Festtage

**Comment by Stephan-S** [comment]
Hi, ist das eigentlich ein Mod mit dem Siliermittel oder gehört das ins Grundspiel?
Ich bin da noch nicht drüber gestolpert bisher

**Comment by VJH01** [comment]
Ist im 22er neu hinzugekommen und gehört zum Grundspiel. Du kannst im Shop jeden Ladewagen mit einem Siliermitteltank (+2000€) zusätzlich ausstatten. Das Zeug selber gibts im Shop unter Paletten und dann Bonsilage, soll wohl +5% bei Gras/Silage bringen. Kann übrigens auch in Maishäcksler gefüllt werden.

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
