### ISSUE TITLE
Autodrive verhindert das Öffnen und Schließen der Plane vom Anhänger

### ISSUE THREAD

**Issue by SchorschiBW** [Stephan-S/FS22_AutoDrive#740]
Wie es der Titel schon sagt, verhindert Autodrive das Öffnen und Schließen der Plane von dem/den Anhänger(n), wenn eine Zugmaschine mit Mulde und Plane involviert ist.

Beispiel: Ich nehme den kürzlich erschienenen Unimog von Modding Welt, konfiguriere diesen mit der großen Mulde mit Plane, hänge dort einen beliebigen Hänger mit Plane an, wie den Brantner Z 18051/2 XXL POWER FLEX.
Versuche ich nun mit N die Plane zu öffnen, geht nur die Plane am Unimog. Drücke ich Y, passiert gar nichts.

Nehme ich Autodrive aus dem Modordner, dann funktioniert alles, also Plane des Unimogs mit N und die Planen der Anhänger mit Y.

Ich habe einen weiteren Versuch mit einem anderen Mod ausgeführt,  in dem Fall war es ein Kamaz 5320, den ich bei FBM; gefunden habe. Dort das gleiche Spiel: Mit Autodrive gehen die Planen der Hänger nicht, weder mit N noch mit Y.
Autodrive raus, schon geht es.

Ich habe schon in den Einstellungen gesucht, aber leider nichts gefunden oder vielleicht doch übersehen

**Comment by rohne83** [comment]
Seit wann gehen denn Anhängerplanen mit Y? Persönliches Keybinding? Ich muss meine Planen für sämtliche Fahrzeuge mit N öffnen (mittels G halt vorher das korrekte Fahrzeug auswählen)

**Comment by SchorschiBW** [comment]
@rohne83: Grundsätzlich gehen die Planen mit N auf, so lange sie von einem Traktor gezogen werden. Wenn allerdings das Zugfahrzeug auch eine Plane hat, dann geht die Plane des Zugfahrzeugs mit N auf und die Anhänger mit Y. UND das steht dann sogar auch im Hilfemenü

Ich zitiere aus einem Forum:

"n der Beschreibung hier steht ziemlich unten folgendes: "Die Abdeckplane vom Unimog wird mit der Taste "N" geöffnet, die Planen der Anhänger mit der Taste "Y"." Hast Du das gelesen? Wenn Du dein F1-Hilfemü auf machst, stehen die Tasten dort ebenfalls drin (es sei denn, irgendein Skript hat dein F1-Hilfemenü vollgespamt). ^^

Es funktioniert anders als im LS 19, aber ich habe mir das nicht ausgedacht, die verschiedenen Tasten sind von Giants vorgegeben."

Quelle: https://forbidden-mods.de/filebase/file/38155-unimog-u1200-u1400-u1600/#comments/comment65058

Schau da in den Kommentaren, speziell auf die Antwort zu Knecht Rupplink

**Comment by Tensuko** [comment]
Das scheint dann aber ein spezielles Unimog Ding zu sein, also warum da auf AD schließen?

**Comment by SchorschiBW** [comment]
Weil 
1. ich das Problem ohne AD nicht habe. Ich habe es getestet mit neuem Spielstand und nur AD und den Unimog drin: Mit AD geht es nicht, ohne AD geht es
2.  Nicht nur mit dem Unimog existiert das Problem, sondern auch mit einem Kamaz (https://forbidden-mods.de/filebase/file/37633-kamaz-5320-trailer-gkb/)

**Comment by Axel32019** [comment]
Mit o.g. Unimog nicht reproduzierbar -> close

**Comment by SchorschiBW** [comment]
In welcher Konfiguration wurde es getestet?
