### ISSUE TITLE
[ERLEDIGT] Problem nach Update auf LS 1.8.1.0

### ISSUE THREAD

**Issue by Neo-x-Plan** [Stephan-S/FS22_AutoDrive#741]
Moin,
nachdem Steam mir gestern das Spiel upgedated hat macht AD ein Problem und lässt das Spiel "einschlafen" 
Außer dem Update fanden keinerlei Änderungen am Spiel/Mods statt, zuvor lief alles einwandfrei.
Das Problem stellt sich wenn ich ein Fahrzeug mit (teil)beladenem Anhänger auf die Reise schicke,

Ein Trecker alleine: kein Problem
Ein Trecker mit leerem Anhänger: kein Problem
Bei beidem auch keinerlei Meldungen im Log.

Ein Trecker mit beladenem Anhänger, unabhängig davon ob voll oder teilbeladen: das Fahrzeug fährt ein Stück und das Spiel friert ein, ohne Meldung "reagiert nicht". Ich kann dann noch Escape drücken und komme ins Menü aber die Karte lädt nicht und ich kann auch nicht speichern. Es spielt auch keine Rolle ob es sich um einen Paletten-, Ballen- oder Schüttgutanhänger handelt. 
Im Log ist dann mehrere hundert mal innerhalb einer Minute folgende Meldung:

2022-11-12 14:24 Error: Running LUA method 'update'.
H:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/TrailerUtil.lua:11: attempt to perform arithmetic on local 'fillFreeCapacity' (a nil value)

Mit freundlichen Grüßen
Neo aka Wolfgang

ERLEDIGT: Problem gefunden, kein AD-Problem

**Comment by rohne83** [comment]
Sondern? Vielleicht ganz interessant zu wissen für Andere falls bei denen das Problem ebenfalls auftritt

**Comment by Neo-x-Plan** [comment]
Oh shit, sorry!
Tante Edit hat mir den Absatz geklaut wo das drin stand... (alles auf Tante Edit schieben , der Depp vorm Keyboard ist schließlich NIE Schuld...)
AD und der FillLevelLimiter-Mod bekommen sich in die Wolle, den Limiter-Mod rausnehmen, alles wieder ok!
