### ISSUE TITLE
bug Running LUA method 'update'.

### ISSUE THREAD

**Issue by Eternel750** [Stephan-S/FS22_AutoDrive#747]
Hello I have a problem with my FS22
Here is the error:

2022-11-19 18:01 Error: Running LUA method 'update'.

**Comment by Tensuko** [comment]
This is not the Error itself.
A LUA Error is always 2 Lines.
Your msg is only the 1st the "method", the real Error is in the next Line and I suggest you to always post the complete logfile!

**Comment by Eternel750** [comment]
hello sorry for disturbing you

here is the Log.xml file :
https://mega.nz/file/64FTmKAI#tuHDs3lorKLTLlnRpEEL40Mod-6yhBMdqF-Q-U_FTxc

**Comment by Axel32019** [comment]
> 54000 errors, but no AutoDrive mod in use / involved ???????????????????????????
-> closed!
