### ISSUE TITLE
MP syncro problem 99%

### ISSUE THREAD

**Issue by Dragonfly1982** [Stephan-S/FS22_AutoDrive#748]
Wir haben bei uns auf dem Server ein Syncronisations Problem und haben immer wieder AD mit LUA Call Stacks in der Log stehen. Könnt ihr euch das mal bitte Anschauen und uns gegebenenfalls Rückmeldung geben.

IM Anhang sende ich euch die Server LOg und die Spieler LOg von mir mit.
[SpielerLog.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10049322/SpielerLog.txt)
[ServerLog.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10049323/ServerLog.txt)

Vielen Dank euch und macht weiter so eine gute Arbeit.

**Comment by Axel32019** [comment]
Wie #618

**Comment by Iwan1803** [comment]
Aktualisiert CoursePlay auf die aktuelle Version 7.1.2.3, denn das gleiche Problem mit ähnlicher Meldung hatten wir gestern auch und es lag nicht an AD.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
