### ISSUE TITLE
Feature: Gerät einklappen bevor losgefahren wird?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS22_AutoDrive#75]
Hallo,
Ich habe gerade auf einem Feld die Arbeit beendet und hatte vergessen, das Anbaugerät einzuklappen.
Könnte AD das Einklappen übernehmen, bevor die Fahrt startet, damit der Traktor nicht mit ausgeklappten Gerät über die Strassen brettert? 
Früher hatte bei Ende der Feldarbeit CP gelegentlich auch nicht immer eingeklappt, obwohl das so eingestellt war.
Wäre schon hilfreich, wenn man es doch mal vergessen sollte.

Es hat keine Prio, aber anfragen kostet ja nichts.
Daumen hoch für eure super Arbeit. 

Frohe Weihnachten, allen Beteiligten.

Gruss Micha

**Comment by Stephan-S** [comment]
Ist im nächsten Release als experimentelle Einstellung drinnen. Die musst du selber in den AD Einstellungen erst aktivieren

**Comment by Stephan-S** [comment]
Done / Erledigt :-)

**Comment by haamic** [comment]
soweit funktioniert das, eine Feldspritze braucht schon mal so 10-15s zum einklappen, AD fährt aber schon los.
Könnt ihr eine einstellbare Wartezeit im AD Menü Bereitstellen? Oder gibts eine Rückmeldung, wenn alles eingeklappt ist, das AD dann erst startet?

**Comment by IgshFirn** [comment]
Hallo!
Vielen Dank für die Mod! Funktioniert bei mir sehr gut! Habe aber eine Frage zum betanken von Gewächshäusern, vielleicht kann mir hier jmd. helfen. Der Schlepper mit angehängtem Wasserfass bewegt sich zum Stoppunkt und entleert wunschgemäß seinen Tank und füllt somit das Gewächshaus mit Wasser. Wenn im Tank vom Schlepper noch ein Rest enthalten ist springt der Triger von Autodrive nicht zum nächsten Zielpunkt und verbleibt dann am z.B. ersten Gewächshaus anstatt weiterzufahren und den Rest des Tankes am nächsten zu leeren. Ein kurzes Ein- und Ausschalten von Autodrive veranlasst den Schlepper dann nächsten Wasserfass zu fahren und wird dort entleert. Für einen Tipp wäre ich dankbar!
Gruß Gerd
