### ISSUE TITLE
Performance verbesserungs vorschlag bei übergabe von CP an AD

### ISSUE THREAD

**Issue by Ghost265** [Stephan-S/FS22_AutoDrive#750]
Mir ist aufgefallen bei CP im Ballensammelmodus, das wenn er fertig ist und an AD übergibt und der füllstand nicht erreicht ist AD dann zum Aufladepunkt fährt und an CP übergibt. CP aber gibt dann wieder an AD weil nichts mehr auf dem Feld ist. Das ganze wiederholt sich durchgehend und führt so zu massiven leggs.

Als lösung wäre dort möglich eventuell eine Abfrage einbauen die kontrolliert ob in kurzer Zeit der CP an AD übergibt und umgedreht. Wenn das den Wert x überschreitet, z.b. 3x in 5 sekunden, AD sich dann automatisch abschaltet um die leggs nicht zu verursachen.

**Comment by Tensuko** [comment]
Da gibt es bessere Lösungen für.

**Comment by Ghost265** [comment]
schon eine verbaut die nutzbar ist?

**Comment by Tensuko** [comment]
Nein.

**Comment by Iwan1803** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
