### ISSUE TITLE
LKWs können nicht rückwerts fahren

### ISSUE THREAD

**Issue by ArneM96** [Stephan-S/FS22_AutoDrive#752]
Die Anhänger der LKWs driften immer mehr weg.

**Comment by Iwan1803** [comment]
Und nun sollen wir raten, welche LKW auf welcher Map oder wie?
Ein bischen mehr Subtext könnte nicht schaden, da wir sonst nicht helfen können.

**Comment by ArneM96** [comment]
Ich spiele auf der Karte Landkreis Rostock
LKW: Mercedes Actros MP 4
Anhänger: Cargoline TST08 Pritsche (Autoloader Transport Paket)

Vorgehensweise:
Ich fahre einen Kurs ein wo ich Rückwärts (hellblaue Pfeile zum Zielpunkt) an eine Abladepunkt heranfahre und wenn Autodrive dann da was abliefern soll, fährt der LKW rückwärts als wenn er keinen Anhänger angekuppelt hat. Der angekupelte Anhänger driftet dann zu einer Seite weg, da der LKW nicht gegensteuert.

**Comment by Iwan1803** [comment]
Das mit den "Strecke aus hellblauen Pfeilen zum rückwärtsfahren" ist schon etwas angestaubt, aber egal.
Schickst du ihn rein zum Abladen hin oder im Abholen&Abliefern-Modus?
Im Ablaaden-Modus will AD danach den Zielpunkt erneut anfahren und maybe das ist das Problem bei dir.

**Comment by Axel32019** [comment]
mod Problem, siehe Achim's Discord -> closed
