### ISSUE TITLE
Punkte / Sackgassen außerhalb der Map

### ISSUE THREAD

**Issue by agestar69** [Stephan-S/FS22_AutoDrive#755]
Ich habe festgestellt, das außerhalb der Map ein paar Debug-Punkte sind. Die kann ich nicht anfahren und somit auch nicht löschen.
Ich sehe sie zwar über Debug, aber das war es auch schon.
Wie bekomme ich diese Punkte weg?

![fsScreen_2022_11_24_16_15_02](https://user-images.githubusercontent.com/82504853/203817595-960f63c9-babb-4322-9b68-0812f9563209.png)

**Comment by TobiHH78** [comment]
Damit geht es am einfachsten...

https://github.com/KillBait/AutoDrive_Course_Editor

**Comment by agestar69** [comment]
Danke hat funktioniert
