### ISSUE TITLE
When will we get the next Release of an Update for Autodrive?

### ISSUE THREAD

**Issue by cwattyeso** [Stephan-S/FS22_AutoDrive#756]
I come to this page every day hoping to find an update for this mod that fixes a lot of the issues myself and others have reported since the last release back in July. I'm just wondering if this mod is ever going to get an update or is it dead? Nearly 5 months now with no updates and fixes so is there going to be an update anytime soon?

**Comment by 60erjonny** [comment]
The mod is not dead, but patience is required here. The developers also have a private life and do this by the way.
I do not tend to a team, but what problems do you have? Maybe I can help, because for me the mod works perfectly ... :-)

**Comment by Iwan1803** [comment]
AD is not dead and we are working on the next release.
Due to private circumstances it simply takes much longer this time. In addition, Giants has laid a few beautiful eggs in our nest.
So, just keep cool, have a coffee or tea and relax 😉

**Comment by cwattyeso** [comment]
@60erjonny well issues I've been having with the current release are:

1. HUD always open on Vehicles when loading into a save or joining a multiplayer server, despite having gone round numerous times and closing it. Why does this happen? Why does the mod not keep the hud closed by default and only open/active when players want to use it?
2. Tractors/Trucks & Trailers that when emptying a Combine when they get full or called by another combine decide to drive forward and then turn right directly into the path of the combine they have just been emptying and cause a collision.
3. Tractors/Trucks that seem to take forever to react respond to a harvester calling them, to the point that by the time the Tractor/Truck has got anywhere near to unloading the harvester it's reached the end of it's row and is now going to turn around.
4. Tractors/Trucks that when attempting to unload a Combine that's reaching the end of it's current row, drive to the combine and then without unloading it decide to stop and randomly reverse instead.
5. Tractors/Trucks that when attempting to unload a Combine they make a turn towards the combine from close range that means they don't manage to correctly align with the pipe, thus they can't empty the combine, so drive forward and make the turn again with the same effect and basically end up doing a Circle of Death where they just keeping turning in a circle and never align themselves with the pipe of the harvester that's sitting stationary waiting to unload.
6. Unloading Multiple Harvesters with Multiple Autodrive Trailers on the same Field. There often seems to be no logic as to which harvester a trailer will unload first. Often time you'll witness a trailer right next to harvester drive to completely the opposite side of the field to empty a different harvester despite the one right next to it having it's pipe out and repeatedly hitting the call to unload button. There seems to be no way to specifiy in this situation that certain trailers should service Harvester A for example and other trailers service Harvester B only.

**Comment by 60erjonny** [comment]
Hallo
Sorry, can only speak for single players ...And my translation

1.:Sorry...no idea
2.:"Blue/ Brown Fan Line" around the field? Departers set at the nearest in the field exit?
3/4/5/6.: I always have the combine unloaded while standing, I have had the best experience.
7.: Increase the value when setting: "Look in front of a distance", it could help.
8.: Collision recognition is switched on? Reduce the value for collision height over the ground.

Also important, use standard vehicles or mods. Because mods can also be faulty and cannot be compatible with AD. And something else. This is a game, everything will never work automatically. A "intervention and help" is also necessary for my AD driver every now and then.

**Comment by Iwan1803** [comment]
for 1.: it's not an error/issue, but there is allready a request for it -> #726
if we change it: maybe or maybe not...

all other points: everything could happen as AD is also only a "stupid" script, but some of your problems sound like wrong configurations and/or misunderstanding of how AD works

**Comment by cwattyeso** [comment]
_This is a game, everything will never work automatically. A "intervention and help" is also necessary for my AD driver every now and then._

I can fully understand that but I have found as time has passed and the game have received updates and patches and with new mods coming out all the time that the amount of "Intervention and Help" I'm having to give to the "Autodrive" workers is increasing all the time to the point where the mod is much automatic anymore and needs almost as much hand holding and baby sitting as Giants own native AI. Also seems weird that with the lack of updates for Autodrive, the developers of Courseplay in recent updates have now added their own Trailer Unloading option so those of us that use Courseplay and Autodrive can now ditch Autotdrive and try the Courseplay version to handle combine unloading and delivering/selling of crops from the fields automatically. If they actually add back the ability to record our own custom courses like in the FS19 version, then I could probably drop Autodrive completely and just use Courseplay solely like I did in FS19. The one thing letting Courseplay down in FS22 has been the lack of Transport and Combine modes, but if they are coming back now, then maybe we just use that mod.

_but some of your problems sound like wrong configurations and/or misunderstanding of how AD works_

See I found that hard to accept as there are so few configuration and setting options. I certainly see nothing in the configuration or settings that would improve the issues I'm having with points 2-8. I've certainly played with all the options the mod has visible to me, and watched enough other youtubers and streamers who use the mod and see them having the exact same things in their gameplay too. I see no configuration options that stop trailers reversing at the end rows and instead keeps them unloading. Nor can I see any setting or options to speed up how quickly trailers respond to a combine unload request and take the best and most direct route to the harvester without driving all round the field or halfway round the map. (Yes I have avoid fruit disabled and yes field exit is set to nearest point on all vehicles to try and help some of my frustrations and issues above, but the AI doesn't seem to pay attention.)

For example when  grain harvesting or doing root crop harvesting if the combine's pipe/unloader is over the crop, the Autodrive Trailer will just drive right up the backside of the harvester sniffing it's butt instead of driving alongside and unloading it. I have the trailer option to Avoid Fruit turned off so it should ignore the fruit and just drive where it needs to drive, so there is no reason why the trailer shouldn't drive in the crop and just unload normally, but no it insists in driving right behind the harvest smelling it's butt the entire row. Even if I change the setting for "Follow Behind Harvester Distance" that makes no difference to the Autodrive guy in this case.

As for point 1. it is an issue as it never happened in earlier versions of Autodrive but was only introduced in version 2.0.0.6 and remained in 2.0.0.7

It's been mentioend in several posts #554 #579 #619 that I have seen and posted in, and it's still not been fixed. Many of those posts have just been closed without the issue being addressed. There's no reason for the Hud to be automatically open and open on every single vehicle each time you start the game, load or reload a save or log in to a multiplayer server. We have keybinds to open the hud as and when we want it and need to use and activate autodrive. Please make the hud closed by default as it was back when the mod was in earlier versions when FS22 first released.

**Comment by Misamangame** [comment]
"It's been mentioned in several posts 554, 579, 619 that I have seen and posted in, and it's still not been fixed"  And why they should be fixed? Authors are working on this mod when they have free time, they are not paid for it and they are not obliged to do anything for you or anyone else. If you are so clever just make your own mod no need to whine on forum about it. CP unloader might be better for not having so many collisions, but it often stops for no reason and just sitting there doing nothing, with AD sooner or later some unloader come even when from other side of the field but yes collisions are issue.  You should be glad that those mods even exist with errors as Giants will have something like this in FS 54 only. I would like to see AD "refined" and added more functions like unloading bunker or unloading bales on destined point but I can understand it might come or might not.  Until then you can either use it within its limits or like you mentioned just ditch it and be happy with FS helper :)

**Comment by TobiHH78** [comment]
> _This is a game, everything will never work automatically. A "intervention and help" is also necessary for my AD driver every now and then._
> 
> I can fully understand that but I have found as time has passed and the game have received updates and patches and with new mods coming out all the time that the amount of "Intervention and Help" I'm having to give to the "Autodrive" workers is increasing all the time to the point where the mod isn't much automatic anymore and needs almost as much hand holding and baby sitting as Giants own native AI. Also seems weird that with the lack of updates for Autodrive, the developers of Courseplay in recent updates have now added their own Trailer Unloading option so those of us that use Courseplay and Autodrive can now ditch Autotdrive and try the Courseplay version to handle combine unloading and delivering/selling of crops from the fields automatically. If they actually add back the ability to record our own custom courses like in the FS19 version, then I could probably drop Autodrive completely and just use Courseplay solely like I did in FS19. The one thing letting Courseplay down in FS22 has been the lack of Transport and Combine modes, but if they are coming back now, then maybe we just use that mod.


Not if you want to drive the combine by yourself. It works only, when the combine is driven by CP, and Tensuko mentioned that they will not implement this feature for player driven combines.

I don`t have most of the problems you describe. AD is definitively not perfect and there is always space for improvement. But I agree with Iwan that most of the problems you describe are wrong settings or user errors.
I`m playing on a 4x map and usually harvest with 1 combine and 2 unloaders, sometimes with 2 combines and 4 unloaders. 1 combine is always driven by myself. And I harvested several hundreds hectare without 1 single problem.

**Comment by bojanh66** [comment]
Maybe i will get help here, my problem is when i send harvester from point A to point B on a tighter road, so when harvester is making a turn in the corner, it will not follow 100% exactly the line, it will take a wider turn. I even tried to delete the turning waypoints and record it again slowly with harvester, but harvester will again take wider turn and stuck in the obstacles around the road (poles, bridge, barrier, tree or whatever). I have even reduced corner speed to 50%, but it didnt help much. Is this "issue" fixed in the next release, will harvester be able to follow AD lines in the corner more accurately ?

**Comment by Iwan1803** [comment]
Release is out: https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.0.9/FS22_AutoDrive.zip
So i'll close here...
