### ISSUE TITLE
Question about the technical component.

### ISSUE THREAD

**Issue by MANIAK10** [Stephan-S/FS22_AutoDrive#757]
Here I have such a problem that sometimes when unloading the combine, the tractor just drives past the pipe unloading 5 percent of it and then waits for the call again and it all repeats. Very often this happens when harvesting beets and potatoes. But even in ordinary cultures, this happens.

**Comment by Iwan1803** [comment]
How should we find the "problem" without any informations about the harvester and unloader and their settings?

**Comment by MANIAK10** [comment]
техника стандартная, настройки мода по умолчанию

**Comment by Iwan1803** [comment]
German or englisch, please!

**Comment by MANIAK10** [comment]
the technique is standard, the mod settings are by default
I don't remember exactly what technique it was a long time ago

**Comment by Axel32019** [comment]
Screenshots???

**Comment by Axel32019** [comment]
no feedback -> closed
