### ISSUE TITLE
Autodrive on New SilverRun Map

### ISSUE THREAD

**Issue by drich2211** [Stephan-S/FS22_AutoDrive#759]
AutoDrive not working on the downhill routes, just stops

**Comment by Roby1164** [comment]
No, I've used it without problems, even a friend of mine, who I passed it to, had no problems.

**Comment by drich2211** [comment]
Try it with any of the Trucks that pull trailers on the Silver Run Map, its fine uphill but not down hill, starts and stops continuousely until it starts uphill or levels out again

**Comment by geeooff** [comment]
I experienced the same issue, with 2 Volvo trucks. It barely go forward for a few meters, brake, then go forward again for a few meters, until it's finally uphill where it will drive normally.

**Comment by Roby1164** [comment]
That is a collision detection problem, increase the collision detection distance slightly, and the problem disappears, probably the Giants, have exaggerated the collision zone of the street lights or other objects in the area, the trees have their weight. PS: be careful to keep the traffic active, even that can create false detections.

**Comment by regs1980** [comment]
Colission height too low, 2 meters and more is better.

<img width="1157" alt="2022-12-04 16_44_28-FS22 AutoDrive - Issue #759 - YouTube – Mozilla Firefox" src="https://user-images.githubusercontent.com/13314443/205500466-569dfb7b-6496-4188-8068-a5790362a295.png">

**Comment by drich2211** [comment]
Thank you

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 4, 2022 at 10:47 AM, ***@***.***> wrote:   


Colission height too low, 2 meters and more is better.

**Comment by Iwan1803** [comment]
So problem is gone?
As written in the Release Notes Giants has insert new collision bits. Maybe you should set the collision to "FS22" in the global settings. Can't check this as i don't have the Platinum Extension.

**Comment by drich2211** [comment]
Yes it is now working great, thanks.  Will check out  global settings 

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 5, 2022 at 2:10 AM, ***@***.***> wrote:   


So problem is gone?
As written in the Release Notes Giants has insert new collision bits. Maybe you should set the collision to "FS22" in the global settings. Can't check this as i don't have the Platinum Extension.

**Comment by geeooff** [comment]
> Colission height too low, 2 meters and more is better.
> 
> <img alt="2022-12-04 16_44_28-FS22 AutoDrive - Issue #759 - YouTube – Mozilla Firefox" width="1157" src="https://user-images.githubusercontent.com/13314443/205500466-569dfb7b-6496-4188-8068-a5790362a295.png">

Thanks for catching that. I confirm that works with 2 meters.
