### ISSUE TITLE
Frage: auf dem Weg zur Werkstatt/Tanken die eigentliche eingestellte Aufgabe erfüllen

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS22_AutoDrive#76]
Hallo,
mein Szenario: Gespann soll zum Abladen fahren, der Abladepunkt liegt VOR einem Werkstatt-Trigger auf dem Hof..
Ich starte die Fahrt, AD meldet das es zur Werkstatt fährt. Auf dem Weg dahin überfährt es den eigentlichen Abladepunkt, repariert, dreht eine Ehrenrunde und lädt dann ab.
Wäre es möglich, das Abladen schon eher zu ermöglichen, bevor man den Werkstattpunkt erreicht, wenn das eigentliche Ziel zufällig auf der Strecke zur Werkstatt liegt?
Genauso wäre es beim Tanken, warum erst Tanken, wenn man bereits durch eigentliche Ziel oder am Ziel vorbei fährt.
Also, welches Ereignis eher eintrifft, wird gemacht. 

Es hat keine Prio, aber anfragen kostet ja nichts.
Daumen hoch für eure super Arbeit. 

Frohe Weihnachten, allen Beteiligten.

Gruss Micha

**Comment by Stephan-S** [comment]
Hey, an sich klingt das ja nach einem sinnvollen Vorschlag. Allerdings lässt sich das aktuell nicht wirklich leicht in AutoDrive abbilden.
Ein Fahrzeug hat immer genau einen aktuellen Job/Task. Daher kann es nicht auf dem Weg andere Punkte abhaken.
Das Tanken und Reparieren wird immer als Task dazwischen geschoben wenn es nötig ist.
