### ISSUE TITLE
[Feature Request] AutoDrive als Navi / Anzeige der Route in der Minimap

### ISSUE THREAD

**Issue by IMWeazel** [Stephan-S/FS22_AutoDrive#761]
Ich fände es sehr hilfreich, wenn AutoDrive eine "manuell fahren"-Funktion hat, in der es dann nur als Navi fungiert und die beste Route in der Minimap anzeigt.
Ich weiß, dass AutoDrive in erster Linie ein Tool ist, damit die Helfer fahren können und "manuell fahren" eigentlich genau das Gegenteil ist, allerdings denke ich, dass hier die Umsetzung "relativ" einfach wäre, da die Routenberechnung ja eh bereits Teil des Tools ist, auch wird die Strecke bereits in der großen Helfer-Map angezeigt. Letztendlich müsste ja nur diese berechnete Strecke in die Minimap übernommen werden, sobald ein Ziel eingestellt ist. Die Anzeige der Route würde ja auch nicht stören, wenn der Helfer fährt, bzw. es spräche ja auch nichts dagegen, dies in den Optionen ausstellen zu können.

**Comment by Iwan1803** [comment]
Wenn der Helfer fährt, kann man die Strecke auf der Helfer-Map sehen.
AD wird kein "Navi" werden, sorry.
