### ISSUE TITLE
Problem beim Abladen, wohl an gelehnt an #561

### ISSUE THREAD

**Issue by 60erjonny** [Stephan-S/FS22_AutoDrive#764]
Hallo
Mit der neuen Version 2.0.0.9 läd der Ladewagen nicht mehr ab, im Abholen und Abliefern Modus. Karte NFM und mit Standartladewagen getestet. Mir der alten 2.0.0.7. ging es noch oder wieder. 
Wenn ich noch was nachreichen soll gerne...:-)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10149191/log.txt)
![Screenshot (81)](https://user-images.githubusercontent.com/63659182/205508589-a0643ed1-7b59-498a-8824-2bb26243436c.png)
![Screenshot (82)](https://user-images.githubusercontent.com/63659182/205508600-fa49af3d-d1e0-41e3-90c4-3c40d7878f83.png)
![Screenshot (83)](https://user-images.githubusercontent.com/63659182/205508606-ed737b40-961d-4377-a819-cbfab2c6017d.png)
![Screenshot (84)](https://user-images.githubusercontent.com/63659182/205508609-1964ecfb-380d-432b-8734-208ad4c8fecb.png)
![Screenshot (85)](https://user-images.githubusercontent.com/63659182/205508616-e06b3b5b-af3e-4a71-939a-a6430e32b0ce.png)
![Screenshot (86)](https://user-images.githubusercontent.com/63659182/205508623-0cd6fc64-f0a3-4562-9aee-7f99e55e16cf.png)
![Screenshot (87)](https://user-images.githubusercontent.com/63659182/205508629-5f810c43-d3bc-4aa8-ae3a-1503b367cc45.png)
![Screenshot (88)](https://user-images.githubusercontent.com/63659182/205508634-f0a9c773-535d-4bb2-8e71-ccf0d5afcbec.png)

**Comment by Axel32019** [comment]
Hallo, Probier mal Kollisionserkennung FS 19.

**Comment by 60erjonny** [comment]
Hallo
Ok, er fährt jetzt schon bis zu dem Abladepunkt, es öffnet sich aber der Ladewagen nicht.
![Screenshot (89)](https://user-images.githubusercontent.com/63659182/205515335-ae69b9a3-d7bd-4998-a744-8501ce967424.png)
Nadem ich den Abfahrer entlassen habe, zeigt er mir schon an, das er entladen könnte. Der Abladepunkt müsste schon passen...
![Screenshot (90)](https://user-images.githubusercontent.com/63659182/205515408-ae1f978c-d7d5-48cf-ab23-6e713a073a26.png)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10149453/log.txt)

**Comment by Axel32019** [comment]
siehe #561, Zielpunkt muss ein paar Meter weiter.

**Comment by 60erjonny** [comment]
Hallo, das hat leider nicht geholfen...er fährt jetzt bis zum Abladepunkt, aber er öffnet sich zum entladen nicht.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10156548/log.txt)
![Screenshot (91)](https://user-images.githubusercontent.com/63659182/205705288-6d68496b-6fef-4d39-ac61-f815a170d339.png)

**Comment by 60erjonny** [comment]
Hallo

Was meinst du genau, mit 2. 25 m verwenden...?

**Comment by andreasthu** [comment]
sry, das ich mich da drannhänge.
seit v.2.0.0.9 bleibt mein Abfahrer auch vor manchen Abladepunkten stehen - mit FS22 Kollision.
mit FS19 Kollision funktioniert es - was ist da genau der unterschied?
lg
andreas

**Comment by Axel32019** [comment]
@andreasthu Siehe hier: https://gdn.giants-software.com/thread.php?categoryId=22&threadId=9694
Selbst BigG verteilt die bits nach Gutdünken - man schaue sich nur mal die originalen Ballentrigger in C:\Program Files (x86)\Farming Simulator 2022\data\placeables\mapFR\ -> sellingStationBales.i3d und sellingStationWool.i3d an. Seit wann sind das denn 12: "DYNAMIC_OBJECT: A dynamic object" ??? Als ob jemand den Ballenverkauf wegtragen/transportieren können sollte, den Wolleverkauf aber nicht???
Mit 12: "DYNAMIC_OBJECT: A dynamic object" sollen z.B. Paletten, Bigbags, Ballen etc. als Kollision erkannt werden, aber ist halt wieder mal so'n BigG-Ding....

**Comment by andreasthu** [comment]
Ah ja danke das macht sinn.
Konkret ist es beim mir der ballen/paletten trigger auf hobos hollow. Welcher eigentlich mit dem ballentrigger der Haute-Beyleron ident zu sein scheint. 
Hab mich eh schon gewundert warum diese verkaufsstelle 5 triggerboxen hat.
Lg
Andreas
