### ISSUE TITLE
[BUG] status for HUD open/closed not saved

### ISSUE THREAD

**Issue by cwattyeso** [Stephan-S/FS22_AutoDrive#765]
So downloaded and installed the new Autodrive Update and guess what? The HUD is still broken and is automatically open on every single vehicle everytime you start the game and load the save. Even going round closing the hud manually on every vehicle, saving the game and exiting does not fix this. Next time you load the game up the pissing hud is open again on every thing. I thought this was supposed to be fixed in this update? Isn't that why you've been going round closing all the posts that mention this problem?

Perhaps you shouldn't close reported issues until you've actually fixed them.

It's bad enough we have to keep reporting the same things over and over again to Giants on their Bug Tracker because they keep closing reports before they actually fix the issue. Don't be like Giants, Autodrive Devs, be better.

**Comment by Tensuko** [comment]
Won't even need a setting for this in the UI.
Just save the state HUD open or closed in the savegame for every vehicle.
Close HUD, save the game, next time you open the game it will be closed.
Ofc same for open. Default state closed is also simple to add.

**Comment by cwattyeso** [comment]
@Tensuko Yeah would be nice if they added that. Better still would be for them to reverse whatever they did between 2.0.0.5 and 2.0.0.6 which caused the HUD to always be open on game launch. I however feel the Dev's want to force the HUD on us all the time instead of giving us players the option of opening it when we want it and not until.

@Iwan1803 I'm not submitting a new suggestion or improvement. I'm submitting an issue repeatedly since July, as are other people like the poster in #726 who has noticed that when Autodrive first released for FS22 and in the first few updates afterwards the HUD was never defaulted to always being open on game launch, save load etc. The HUD only opened on a vehicle when the user pressed the button to open the HUD. You have decided to change something which has caused the HUD to always open now, on every vehicle every time the game has loaded. Several people have posted here asking for this to be changed back, not just me, and you keep ignoring us and closing comments related to this issue. Going back to a couple of updates to when Autodrive wouldn't save and remember users settings in HUD, people were commenting then about this issue. You quickly released an update that fixed the issue of the user settings not being saved, but forgot at the same time to fix the issue with the HUD always being open.

**Comment by cwattyeso** [comment]
For further information and just to put my own mind at peace I just downloaded version 2.0.0.3 of Autodrive @Iwan1803 and in that version of the mod the HUD does not automatically open on every vehicle each time the game is launched or a save is loaded/reloaded. That version of Autodrive much like @Tensuko comments seems to remember the players choice and saves that between game launches and loads. So yeah I'm definitely now leaning more towards this being an unfortunate BUG/ISSUE that has creapt in the mod and is not something that needs a request for a new feature or improvement.

**Comment by Iwan1803** [comment]
Please do not twist any words or sentences or write misinterpretations, because it makes no sense.
Besides, the sound makes the music and not who shouts the loudest is also served first.
Some people sometimes seem to forget that we are also only human and that we have a life outside of AD.

@Axel32019 please take a look at it.

**Comment by cwattyeso** [comment]
If you want to trade sayings here's a great English one for you, "The Squeaky Wheel gets the Grease."

You have a bug, people have pointed it out, you have ignored us and when we complain more loudly, you get defensive and offended. That's your problem. We're trying to help you make a better mod by pointing out problems and issues and providing feedback. We're all working as beta testers for you, we're all doing it for free and we all have life's outside of FS and AD.

**Comment by rohne83** [comment]
No, it's just your problem. You are the one who is requesting something from AD guys. But they decide which issues they take care about and which not. The unpolite way you argue I as developer would already ignore every issue opened by you. So you're lucky AD devs are more patient than me.

**Comment by Tensuko** [comment]
@Axel32019 

`<AutoDriveUsersData>
    <users>
        <user uniqueId="SinglePlayer" hudX="0.859896" hudY="0.270648" showMarkersOnMap="2" switchToMarkersOnMap="1" guiScale="1" iconSetToUse="1" lineHeight="1" wideHUD="1" EditorMode="1" playSounds="2" showHelp="1" addSettingsToHUD="1" showTooltips="2" notifications="3" showNextPath="2"/>
    </users>
</AutoDriveUsersData>`

Just save the current state there, that sould be enough.

**Comment by Tensuko** [comment]
Quick and dirty:
Remove the -- from that Line in XML.lua
It does exactly what I suggested but global for all vehicles.

```
setXMLBool(xmlFile, "AutoDrive.HudShow", AutoDrive.Hud.showHud)

**Comment by Mc-Games** [comment]
Hallo zusammen, ich beobachte jetzt schon eine ganze Weile die Posts zum Thema "HUD nur bei Bedarf aktivieren" und habe mal getestet ... die Vs 2.0.0.5 speichert noch das Ausblenden des HUDs. Ab Vs 2.0.0.6 bis 2.0.0.9 dann nicht mehr. 
Die Löschung der Zeile setXMLBool(xmlFile, "AutoDrive.HudShow", AutoDrive.Hud.showHud) aus der XML.lua. hat nichts gebracht. 
Ich zappe also weiterhin durch ca 20 Selbstfahrer, um bei einem Wechsel nicht immer das HUD vor mir zu haben.

![AutoDriveHUD](https://user-images.githubusercontent.com/29283879/207117299-3fda0a9d-16b7-4ea4-bc1b-da406257bed3.jpg)

Diese markierte Zeile ist raus!
Was kann man noch machen - und jetzt bitte nicht Kommentare wie "weniger Fahrzeuge haben"  ^^

**Comment by Iwan1803** [comment]
Die Quick&Dirty-Lösung von Tensuko war, nicht diese Zeile komplett zu löschen sondern lediglich die 2 Bindestriche am Anfang 😉

**Comment by Mc-Games** [comment]
Danke! Mein Fehler, die Gedankenstriche (so heissen diese) habe ich übersehen!

**Comment by cwattyeso** [comment]
Thank You @Tensuko for a very simple and straight forward solution to this issue. You sir are a star!

**Comment by BullFlag** [comment]
I too commend you @Tensuko for a simple solution,  you just don't quit when it looks tough.  and then a simple solution appears

**Comment by Mc-Games** [comment]
Pleased me and probably others! Thank you very much for your work!

**Comment by Axel32019** [comment]
Did someone tested this?
Means: Enable/Disable HUD in different vehicles -> save -> quit -> start game -> check?

**Comment by Tensuko** [comment]
The state is saved global in AD config.xml
Not the best position for it...
MP might be problem too.
You should save player based settings locally and not in the savegame on the server.

**Comment by cwattyeso** [comment]
Yeah tested in mutliplayer @Tensuko and it doesn't work to fix the issue there. Everytime you log in to the server all the huds are open again on all the vehicles. So your fix only works presently only for single player. Hopefully in time the Autodrive Devs implement a fix that works for local and multiplayer.

**Comment by Tensuko** [comment]
I guess the problem here is, whenever a HUD is set for open on a vehicle and the server does an autosave, it will write true....
But as said, this HUD on/off is something for offline setting per user, nothing for savegame.

**Comment by Axel32019** [comment]
What is now the great Advantage / Solution from "a nice catch by CP dev Team" by re-enabling 1 line of code to solve the issue?

**Comment by Tensuko** [comment]
That there is a simple quick workarround for the ppl with the problem....
What is the problem about this now ?
Ofc it would be better if there will be a final solution for this Issue.
Like I suggested, simple value that gets turned true or false but localy and not in savegame due to MP not working with this.

**Comment by Iwan1803** [comment]
As the setting for every user will be stored on the server, why should it be stored local? Sorry, but makes no sense...

**Comment by Tensuko** [comment]
So other Users will decide for your if the HUD is open or not ?
Well that doesn't make sence for me....
It will be much easier if you can decide for yourself, without any MP sync or other player action, if the HUD will be closed or open for your.... but thats up to you how you want to do it....

**Comment by Iwan1803** [comment]
The settings are saved for each user itself and not one setting for all...

**Comment by Tensuko** [comment]
But not the AutoDrive_config.xml where with the workarround the ShowHud is set right now.... thats all what I said....
And it was just a suggestion for offline settings....

**Comment by Iwan1803** [comment]
I don't understand what else you want now....
Your workaround is nice, but as you already correctly recognized: it is stored in the AutoDrive_config.xml, where it does not belong to. For user settings there is the AutoDriveUsersData.xml and there it must be stored. This then should also work on server and yes, the AutoDriveUsersData.xml is stored in the savegame folder on the server - not locally.
@Axel32019 can you please check this, thanks!
