### ISSUE TITLE
Autodrive mit IT Runner

### ISSUE THREAD

**Issue by SuperPlusx** [Stephan-S/FS22_AutoDrive#769]
Moin 

Ich habe folgendes Problem:
Ich möchte Autodrive mit nem IT Runner Abholen und Abliefern schicken, aber sobald ich auf Start drücke lädt er den Container ab und fährt mit abgelassenen Container los. Ist auch in Freier Fahrt Modus so. Seit dem neusten Update ist das so. Hab auch mehrere  IT Runner ausprobiert 

Danke schonmal im Vorraus für Antworten

**Comment by Iwan1803** [comment]
Experimental Features -> Fold Implements auf "nein" stellen

**Comment by SuperPlusx** [comment]
Super danke :)

**Comment by Axel32019** [comment]
#662
