### ISSUE TITLE
Frage: Aktive Helfer Menü, AD Ziele ÜBER/AUF den LS Symbolen anzeigen?

### ISSUE THREAD

**Issue by haamic** [Stephan-S/FS22_AutoDrive#77]
Hallo,
das AD nun auch im Helfermenü benutzbar ist, ist super.
Die blauen LS Symbole sind sehr gross und verdecken somit eventuelle AD Ziele. 
Könnt ihr die Ziele über/auf die LS Symbole legen? damit sie anklickbar sind? 
Auf dem Beispielbild ist eine spitze eines AD Zieles zu erkennen, 2 weiter sind aber noch unter den blauen Symbolen.

![Symbole](https://user-images.githubusercontent.com/28841989/147231387-3b901627-ef62-4112-b92e-e39d86b69660.png)

Es hat keine Prio, aber anfragen kostet ja nichts.
Daumen hoch für eure super Arbeit. 

Frohe Weihnachten, allen Beteiligten.

Gruss Micha

**Comment by Stephan-S** [comment]
Done / Erledigt :-)
