### ISSUE TITLE
Autodrive V09 not found by FS22

### ISSUE THREAD

**Issue by Trekkerle** [Stephan-S/FS22_AutoDrive#773]
First things first,
txs for this wonderfull mod!

I'm using FS22 from steam and it is on the latest patch level.
As I had some issues with Autodrive 05 I decided to update to the 09 version.
This update is reported as missing by FS22, althoug it's in the correct folder.

So I replaced it by the 07 version which works.

Is anybody else experiencing this issue?

Is, perhaps, the platinum DLC needed?

Kind Regards,

Trekkerle

**Comment by Tensuko** [comment]
Install the 2.0.0.9 and post a logfile after loading the game once.

**Comment by Iwan1803** [comment]
Without log helping is not possible.
If 2.0.0.7 is working and 2.0.0.9 not: is the game patched to latest version 1.8.2?

**Comment by Trekkerle** [comment]
Hi guys,
thanks for answering.
Iwan, my patch level is 1.8.1.0 as I'm running on steam. 1.8.2.0 seems not to be available on steam.
I started this time with the 2.0.0.9 version. Autodrive is just not recognized again :-(
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10200306/log.txt)

I made a backup of my savegame before experimenting. I'l remove all mods except Autodrave and then I'll send you the results of that test.

**Comment by Trekkerle** [comment]
OK, I started a new version of nomansland.
Patch level 1.8.1.0
Autodrive 2.0.0.9
Main error in log:
Available mod: (Hash: 7e968068e5457bb757bb3ec9ae8ab474) (Version: 2.0.0.9) FS22_AutoDrive
Error: Unsupported mod description version in mod FS22_AutoDrive
The mod description version is 72
I'm not a modder although I'm a Delphi programmer, but to me it looks like there is something incompatible.

Does anyone has the idea what?

Personally I'm affraid I need patch level 1.8.2.0 of LS22.

Thanks for helpning,

Trekkerle

**Comment by Trekkerle** [comment]
Thanks Iwan,

Steam doesn`t have this patch ready to distribute.
As I wasn't willing to wait, I changed the Version in 62, the same Autodrive 2.0.0.7 has.
his seems to work but I don't know the impact.

As soon as I receive the new patch I'll return to the original value.

Guys, thanks, I love LS22 WITH autodrive and courseplay.
