### ISSUE TITLE
Refueling not working on latest version

### ISSUE THREAD

**Issue by Testing123-svg** [Stephan-S/FS22_AutoDrive#775]
Even though valid fuel areas are defined whenever refueling is triggered a notification appears that says could not find refuel station

**Comment by Misamangame** [comment]
It works without problems for me...

**Comment by Iwan1803** [comment]
More informations are needed or we can't help.

**Comment by Testing123-svg** [comment]
What other information do you need?

**Comment by Iwan1803** [comment]
Which map, vehicle, refuel station?

**Comment by Testing123-svg** [comment]
Elm Creek, 
All vehicles
Fuel station on map, vanilla fuel tanks and modded ones

**Comment by Iwan1803** [comment]
FYI: there must be a target point in a range of 15m around a tank trigger so that AD drives to it.
Please try with latest version again and then post a feedback, including screenshots of the situation and a visible route network.

**Comment by Axel32019** [comment]
no feedback -> closed

**Comment by FamerV** [comment]
Hi, am steel waiting for a fix for this issue. 

Using assing key N for Refuel and M for Repair
or Automatic.

repair works good.
Fuel  Displays: Could not find refuel station.

**Comment by Iwan1803** [comment]
@FamerV please create a separate issue for your problem.
A little tip: there must be an AD target point within a radius of 15 m around a workshop or tank trigger.
