### ISSUE TITLE
Vehicles stopping before unloading trigger in new 2.0.0.9 version

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS22_AutoDrive#777]
Hi team.
i have a big route made (or edited at my taste) for landownunda map. it has been working great with a trigger distance of 50m, because i use a double trailer setup and 20m is not enough to trigger the last trailer. Today i updated the autodrive mod and went to play. noticed the new options and try to adjust as possible.
Initially the collision detection was set for fs22, but noticed it detects collisions too much, stopping vehicles when there is enough distance to drive, so i then changed to fs19 collisions, which prevented this situation.
However, i am noticing that now vehicles stop too much before the trigger, too far from the actual waypoint. When  reversing, the vehicle stops when trailer reaches the trigger detection, but keeps changing the loading action, i can see it in the F1 menu the R key being constantly triggered on and off, and vehicle doesnt move more, while on version 2.0.0.7 it was more backwards and fill up properly, leaving the waypoint when no more product was available, using the pickup and deliver mode, in 2 cases, 1 from milk collect trigger to dairy, one from slurry load to bga, both reversing routes, both act the same way.
the other "pickup and delivery" routes are acting like i mentioned above, vehicles stopping as soon trigger is detected, wich makes the vehicle behind the actual unload position and more far away from the waypoint.
Can this be something related to the trigger distance set in the options? or is something to do with the new collision options?
At the moment, autodrive is not being able to work for me, and i have to revert to 2.0.0.7

**Comment by SoftJunk** [comment]
I am also seeing issues. I am using Autodrive to unload combines and take the crop to sell points. Everything was set up and worked perfectly in 2.0.0.7, but on 2.0.0.9, the tractor approaches the sell point (grain pit), then stops BEFORE crossing the pit to reach the dump trigger.

I have the stop point set on the other side of the grain pit, so that when the tractor reaches it, the trailer is over the tip point and it dumps the crop. This worked perfectly up until this latest version, now the tractor will not drive across the pit to the stop point, it just stops when it reaches the pit, it won't drive over it to reach the stop point on the other side. 

If I revert back to 2.0.0.7, it works as expected.

**Comment by fudoido** [comment]
exactly what is happening to me, and my waypoint is quite far ahead from the trigger, as i have been using a double trailer setup and have the distance set to 50 meter detection, yet the vehicle stops before entering the discharge area, or the loading area if its loading from the silo or similar situation.

**Comment by Swinegel** [comment]
hier das gleiche, seit V2.0.0.9 stoppt der Trecker vor dem Zielentladepunkt. Unter V2,0,0,7 war das nicht der Fall.
![20221216031510_1](https://user-images.githubusercontent.com/59506866/208006733-fedff460-6f89-49be-8475-a424d968345c.jpg)

**Comment by bojanh66** [comment]
I have the same problem and i was thinking, am i crazy or what, because i didnt change anything in my road map, the only change was upgrading to 2.0.0.9 version.
but the weird thing is, some tractors will unload, while some will stop before unload point.
anyway, reverting back to previous AD version until this is fixed.

**Comment by fudoido** [comment]
talking with users in facebook and discord, it seems this issue is connected to the new collision detection system, but reverting to old one doesnt fix also, it has to turn off detection entirely for autodrive to go through the triggers.

**Comment by wackoamd1** [comment]
yup thats also the only thing fixing it for me , since setting it to fs19 only fixes it partially , turning of collision is the only way to fix it , but it is not only forward its also like OP backing into a unload trigger

**Comment by Axel32019** [comment]
These are issues with the collisions set in the Maps, Mods, Placeables etc. 
As Autodrive has no Eyes to see something it is not possible to handle this, AD can only react on the collisions it detects.

**Comment by SoftJunk** [comment]
> These are issues with the collisions set in the Maps, Mods, Placeables etc. As Autodrive has no Eyes to see something it is not possible to handle this, AD can only react on the collisions it detects.

Forgive my ignorance, but why has this behaviour only appeared in the latest version? I am using exactly the same map/mods as before, so the only thing that has changed is the AD version. The collisions on the map haven't changed, as it's the same map, so what causes this?

Thanks.

**Comment by fudoido** [comment]
sorry to say, but something has changed in this version for it to occur, cant be only due collisions set in the maps, since AD 2.0.0.7 had no issues with those same collisions. AD detection must be checked or converted to old version, because there is clearly an issue with the 2.0.0.9 update regarding collisions.....

**Comment by bojanh66** [comment]
I have to agree, i play on map FS22 Old Stream Farm that hasnt been changed for a long time, but with newest version of AD, my tractors will stop before unloading at sell points. I changed collision in settings and now they will work like before.
So something is definitely changed in newest AD.

**Comment by wackoamd1** [comment]
well thats one way to fix a problem ;-) 
blame everything else and label it wontfix XD

**Comment by fudoido** [comment]
it is disapointing considering that there is an issue with it, and not only 1 person mentioning the issue...... 
AD is a much valued tool for ingle players like myself, along with courseplay, but seems the updates and support is getting more and more scarse and limited, but being told an issue isnt being solved for whatever reason, when thre is an issue not present in previous ad version when using every other mod and map in the same version as before, seems like a "i dont care" kind of response really. start to think courseplay guys should have kept their course driving feature for fs22, if i knew ad would become such a "throne" to some people........ :(

**Comment by dozerjz** [comment]
I also agree with you fellas, something did change, I just wasn't sure if it was an update by giants or AD. I have semi's hitting each other now all the time, as before with 0.7 it worked....

**Comment by Axel32019** [comment]
See: https://github.com/Stephan-S/FS22_AutoDrive/wiki/Release-Notes-for-AutoDrive-english
extended usage of TrafficDetection with FS22 or FS19 collision (new collisions bits)

only for routes, not on fields
https://gdn.giants-software.com/thread.php?categoryId=22&threadId=9694
