### ISSUE TITLE
sell everything and sell everything container mods

### ISSUE THREAD

**Issue by Orsa1305** [Stephan-S/FS22_AutoDrive#778]
Both of these from the in game mod list stopping my tractor if collision is on, either FS22 or FS19.
i guess it is a problem with those mods, like AD sees them higher then they suppose to be.

if this is the case does anyone know another mod that I can use to sell everything (i use it mostly to sell Fertilizer)

Thanks.

**Comment by 60erjonny** [comment]
Hallo
Try this setting ...
![Screenshot (92)](https://user-images.githubusercontent.com/63659182/206894449-ab674532-6a2b-4536-8918-16c7c2e420d8.png)

**Comment by BattleHook** [comment]
Try this edit of the mod. It worked for me
[FS22_sellEverything_SCedit.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10229459/FS22_sellEverything_SCedit.zip)

**Comment by Axel32019** [comment]
mod issue - closed
