### ISSUE TITLE
Tastenbelegungspunkt fürs reparieren

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS22_AutoDrive#78]
Kann es sein das der Belegungspunkt für das reparieren in der Tastenbelegung verschwindet? Am Anfang ist er noch da irgendwann verschwindet er. Das war ja auch schon bei Iwan im release Video so, das der Punkt nicht mehr da war.

Beim Tanken funktioniert es wunderbar mit der Tastenbelegung.

**Comment by Stephan-S** [comment]
Es gab nie eine Belegung für das Reparieren. Aber da dies ja jetzt öfter mal angefragt wird, werde ich dort wohl mal was einbauen

**Comment by Onkel2000** [comment]
Ehm okay. Ist auch eine gute Lösung, danke dir.
