### ISSUE TITLE
Ampelanlage

### ISSUE THREAD

**Issue by KarlGutenberg** [Stephan-S/FS22_AutoDrive#780]
Habe mir die FS22_Ackendorf geladen
leider halten die von AutoDrive gesteuerten Fahrzeuge
an der Ampelanlage nicht an!
Der AI Verkehr funktioniert jedoch einwandfrei!

Danke

**Comment by RalfGorden** [comment]
ist ja  auch nicht für AD gedacht ,nur  AI Verkehr

**Comment by KarlGutenberg** [comment]
Wenn AI an der Ampel halten kann, warum nicht auch AD?

**Comment by regs1980** [comment]
> Wenn AI an der Ampel halten kann, warum nicht auch AD?

Weil der Modder der Map ein Hindernis einbauen muss, wenn es rot ist, so das AD da auch stoppt durch seine Sensoren, AD macht das auch bei Tore oder Schranken.

**Comment by Iwan1803** [comment]
Ich werde mir die Map mal anschauen, aber wie würde da wohl ein vollbeladener LKW reagieren, welcher da mit ~80 Sachen ankommt? Der würde doch vermutlich nicht mehr rechtzeitig zum stehen kommen.
Btw. sollte es doch ein leichtes sein, da ein passendes Kollisionsbit zu setzen, damit AD das auch ohne zusätzliche Programmierung erkennt.

**Comment by KarlGutenberg** [comment]
Das wehre eine super Sache!

**Comment by Iwan1803** [comment]
Wem nützt eine Ampel, wenn AD aufgrund hoher Geschwindigkeit und schwerer Ladung nicht mehr rechtzeitig bremsen und somit in die Kollision reinknallen würde?
Die Idee ist zwar gut, aber ausbauwürdig bevor man eine Umsetzung denken könnte. Vielleicht könnte Achimobil ja mal testweise eine Kolli einbauen, auf welche AD per Default eh schon reagiert, um dann zu sehen, was passiert.

**Comment by Axel32019** [comment]
Ruhig bleiben - ist schon WIP....

**Comment by KarlGutenberg** [comment]
Ich wundere mich nur, dass noch keiner, die "SUPER Ampelanlage" von Blacky konvertiert hat!
Denn Blacky macht doch nichts mehr für den LS!

**Comment by KarlGutenberg** [comment]
Axel32019, was sollen mir deine zwei Kommentare sagen?
Auch wenn ich LS22 oder LS19 einstelle, halten die Abfahrer nicht an der Ampel an!
Und wann ist WIP fertig? Sagst du mir Bescheid?
Danke für Deine Mühe.

**Comment by Iwan1803** [comment]
WIP = work in progress = es wird dran gearbeitet und es ist fertig, wenn es fertig ist 😉

**Comment by KarlGutenberg** [comment]
Sorry das ich schon 70 Jahre alt bin und hier dumme Fragen stelle!

**Comment by Iwan1803** [comment]
Ich habe keine dumme Frage gesehen.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0

**Comment by s4t4n** [comment]
Hi, eine frage dazu noch: Funktioniert das nun auch mit den Ampeln von Achimobil?
Lg

**Comment by Iwan1803** [comment]
Ja, funktioniert mit seinen Ampeln.

**Comment by KarlGutenberg** [comment]
Hallo Iwan1803!
Leider funktioniert das bei mir noch nicht!
Muss ich da was, im AutoDrive neu einstellen?

**Comment by Iwan1803** [comment]
Kollisionserkennung muss aktiviert sein, ob FS19 oder FS22 sollte eigentlich keinen Unterschied machen.
Da die Mapper und Modder aber noch nicht auf die LS22-Collision-Bits umgestellt haben, werde ich vorerst FS19 nehmen.

**Comment by KarlGutenberg** [comment]
Habe ich versucht FS19 sowie FS22 beide funktionierte nicht!
Frage: Kollisionserkennung? Gibt es da noch einen anderen Reiter?
Oder reicht auf FS19 einzustellen?
