### ISSUE TITLE
Zwei Tanks an Feldrandcontainer befüllen

### ISSUE THREAD

**Issue by Sinonplayz253** [Stephan-S/FS22_AutoDrive#781]
Hallo
Ich wollte vor kurzem eine Spritze mit Fronttank an einem Feldrandconainer mit AD befüllen lassen.
Jedoch wird nur der erste befüllt und der Helfer fährt beim zweiten einfach weiter und lässt ihn leer.
Das ist aber nur bei einen Objekt so (Palette, Feldrandcontainer, ...). Bei Beladetriggern, wie an einem Silo funkioniert es wunderbar.
Ich hatte nur AD im Modordner und es gibt keine Fehler.

**Comment by regs1980** [comment]
Screenshots sind immer hilfreich, für die Fehler Findung, natürlich im Kurseditor Modus so das man die Zielpunkte auch sieht.

**Comment by Sinonplayz253** [comment]
Na klar
![Screenshot_20221215_191052](https://user-images.githubusercontent.com/57094499/207935543-fdf516fb-8447-435f-a88e-1d9949be51cf.png)
![Screenshot_20221215_191100](https://user-images.githubusercontent.com/57094499/207935559-3e325925-b7f7-4322-93e6-963363fc8ffa.png)
![Screenshot_20221215_191121](https://user-images.githubusercontent.com/57094499/207935575-6d0c0c2e-af43-47c0-aaea-e4d70e3fe278.png)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10239595/log.txt)

**Comment by regs1980** [comment]
Das ist auch der falsche Modus, das 
<img width="247" alt="2022-12-15 20_25_21-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/207949263-aa9a6299-13a1-43b2-819a-70d8d2bce223.png">
wäre der richtige für die Arbeit.

**Comment by Sinonplayz253** [comment]
Ne leider nicht, ist immernoch das gleiche Problem

**Comment by regs1980** [comment]
Da war doch was, IBC Container kann er ja auch nicht beide Tanks laden, von daher, vielleicht kommt es ja irgendwann mal.
