### ISSUE TITLE
Field exit default/closest

### ISSUE THREAD

**Issue by Misamangame** [Stephan-S/FS22_AutoDrive#783]
Hello,
I would like to know if someone else can confirm but since new version 0.9 my vehicles which have settings park after job is finished leaving fields on closest AD route even when settings are on default.  Maybe it was a case before too but I did not noticed as it was not a problem on my previous map but now they are very often travelling through river :)

**Comment by Iwan1803** [comment]
The field exit strategy only works for the unloader - not for the others like drive to target X (same like drive parking).

**Comment by Misamangame** [comment]
> 

Ok then. Will make borders on my fields, no problem :)
