### ISSUE TITLE
AD Kurs Abholn abliefern

### ISSUE THREAD

**Issue by pulimatrix** [Stephan-S/FS22_AutoDrive#784]
Hey zusammen,

habe neuerdings das Problem das AD nicht mehr anhält bei Gülle zum BELADEN aber beim Entladen. Wenn was drinnen ist, hält er an! Auch beim Saatgut nachladen hält er nicht an, sondern fährt einfach weiter, :/ weiß nicht mehr welche Version. Ich hatte aber glaube bei Version 2.0.0.6/7 war es noch alles okay. Habe natürlich die Version noch mal probiert, aber half keine Änderungen. Wenn was Benötigt wird bitte mitteilen wird umgehend nachgereicht.

**Comment by Iwan1803** [comment]
Zielpunkte zu nah am Trigger? Einfach mal 5m weiterschieben und den Silabstand mal auf 25m stellen, falls er kleiner eingestellt sein sollte.

**Comment by pulimatrix** [comment]
Map ist die Hofbergamnn, hab auf 25 mter gestellt hab die Punkte auch weiter auseinander gestellt tut nicht was er soll :/

**Comment by Iwan1803** [comment]
Screenshot im Editormodus wäre vielleicht hilfreich. Modanhänger oder alles Vanilla?

**Comment by Axel32019** [comment]
Bitte folgende Dateien anfügen: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml

**Comment by Axel32019** [comment]
Keine Reaktion -> closed
