### ISSUE TITLE
IT Runner Pack Problem

### ISSUE THREAD

**Issue by Ghost265** [Stephan-S/FS22_AutoDrive#785]
Mahlzeit, mir ist aufgefallen beim nutzen mit dem It Runner Pack dass beim Starten des Ad Fahrers sich der IT Container erst absenkt und dann mit abgesenkten Container los fährt

**Comment by Iwan1803** [comment]
Schönen Gruß an die Modder vom Pack, welche da wohl eine Funktion an der falschen Stelle eingebaut haben.
Bis dahin: Experimentelle Features -> Fold Implement -> deaktivieren.

**Comment by Axel32019** [comment]
#662
