### ISSUE TITLE
Help entries not getting removed from F1 menue

### ISSUE THREAD

**Issue by rohne83** [Stephan-S/FS22_AutoDrive#786]
Even when help entries are switched off, there are still several AD entries in F1 menue, so that the really important shortcuts (i.e. for Precision Farming) aren't visible.

![fsScreen_2022_12_27_13_40_13](https://user-images.githubusercontent.com/71030138/209668416-fed81e6d-abd4-4174-8633-a26cf35a633f.png)

![fsScreen_2022_12_27_13_40_06](https://user-images.githubusercontent.com/71030138/209668440-b3e49f14-f23d-47f7-9c9b-10d990508a7e.png)

**Comment by Iwan1803** [comment]
Schalte die F1-Anzeige aus, steig aus dem Fahrzeug aus und wieder ein und schon ist das Problem erledigt.

**Comment by rohne83** [comment]
Ich weiß, dass das eigentlich hilft. Schon mehrfach gemacht, auch in andere Fahrzeuge gewechselt, etc. Aber diese Einträge wollen einfach nicht mehr verschwinden.

**Comment by Iwan1803** [comment]
Log?

**Comment by rohne83** [comment]
Seh da zwar nix, das irgendeinen Hinweis geben könnte, aber siehe Anhang. Die beiden errors sind vom fillLevelWarning, können ignoriert werden. Das Phänomen ist das selbe auch ohne dieses Skript.
Scheint irgendeine seltsame Wechselwirkung mit CP zu sein. So lange nur AD fährt oder man selbst, sind die AD-Hilfseinträge nicht im F1-Menü. Die erscheinen erst sobald CP das Kommando übernimmt. Gut, ist daher jetzt auch zumindest nicht game-braking, da man zum Ändern von Ausbringmenge etc eh CP entlassen muss, aber komisch ist es schon, und gewollt bestimmt auch nicht.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10365974/log.txt)

**Comment by Iwan1803** [comment]
Schmeiss FS22_Filllevelwarning raus, falls es kein Update gibt, da es eh nur Fehler schmeisst. Ob die ggfs. auch Auswirkungen auf was anderes haben, kann ich nicht sagen.
Wenn bei mir CP aktiv ist, habe ich dennoch keine AD-Einträge im F1-Menü. Mysterien im BigG-Wunderland...
