### ISSUE TITLE
FS22_AutoDrive/scripts/Hud/PullDownList.lua:437: bad argument #1 to 'insert' (table expected, got nil)

### ISSUE THREAD

**Issue by TrekkerPapa** [Stephan-S/FS22_AutoDrive#787]
Hallo zusammen,

habe gestern abend scheinbar mein autodrive geschrottet.
Habe versucht den Speicherpunkt Papa 14 zu laden. Kann mir bitte jemand Helfen wie ich dem Fehler auf die Spur komme?

Beim Savegame Neustart ist alles soweit in Ordnung. Keine Fehler im Log. 
Lade ich dann Papa 14 verschwindet das Autodrive HUD. Und die Meldung Error: Running LUA method 'draw'. schreibt mein Log voll.
Das Log habe ich angefügt. Wenn weitere dateien notwendig sind bitte melden.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10309611/log.txt)

Mit freundlichen Grüßen

Greger Christian 

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10309576/log.txt)

**Comment by Axel32019** [comment]
Hallo @TrekkerPapa , Bitte folgende Dateien anfügen: AutoDrive_config.xml, AutoDriveUsersData.xml

**Comment by TrekkerPapa** [comment]
Hallo Axel32019,

Auch das Update auf 2.0.0.9 konnte den fehler bei mir nicht beheben.
Danke für die Information. Files sind im Anhang.

[Autodrive Dateien.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10310261/Autodrive.Dateien.zip)

Mit freundlichen Grüßen

Greger Christian

**Comment by Axel32019** [comment]
Hallo @TrekkerPapa, Was meinst Du mit "Lade ich dann Papa 14 verschwindet das Autodrive HUD"?
Die config enthält kein Ziel mit diesem Namen.
Sind da min. 3 Karten im mod-Ordner? -> führt sehr häufig zu unerklärlichen Effekten / Fehlern!

**Comment by TrekkerPapa** [comment]
Hallo Axel32019,

ja habe mehrere Karten im Mod Ordner. 
Habe immer auf Papa 14 gespeichert im HUD ist die auch vorhanden. Siehe Bild. 
![fsScreen_2022_12_28_20_42_35](https://user-images.githubusercontent.com/121508397/209864705-6161a36f-23b9-488d-b3eb-cdbff0a0f449.png)
![Ordner 1 Dateipfad](https://user-images.githubusercontent.com/121508397/209864713-3271cd28-6b16-44f9-8bd3-8179d86b6176.JPG)
![Ordner 1](https://user-images.githubusercontent.com/121508397/209864729-ca598b4b-6543-4a57-977c-6c66346385ee.JPG)
![Ordner 2 Dateipfad](https://user-images.githubusercontent.com/121508397/209864908-15a7a7d2-b6c4-48b2-aa53-e38f77198570.JPG)
![Ordner 2](https://user-images.githubusercontent.com/121508397/209864914-21d58331-e9e0-4da8-a93c-5cdde6cbb39e.JPG)

**Comment by TrekkerPapa** [comment]
Servus Axel32019,

Jetzt ist alles weg. Im Hud wird nichts mehr angezeigt. :-( Siehe Bild im Anhang. 
Habe dann alle Dateien aus den Autodrive Ordnern gelöscht.
Habe Autodrive aus meinem Mod Ordner gelöscht und neu angefangen. 
Hab mir unter "BY Wald 1" einen neuen Speicherpunkt angelegt. 
Mehrere Ziele neu erstellt und abgespeichert. 
Habe dann versucht "BY Wald 1" zu laden das HUD war verschwunden. 
Habe das Spiel gespeichert und runtergefahren. 
In den AD Ordnern nach "BY Wald 1" gesucht dieses existierte nicht. 
Spiel gestartet und in ein Fahrzeug gesprungen. Im HUD ist die "BY Wald 1" nicht mehr vorhanden und alle meine Ziele sind nicht mehr vorhanden. 
Gibt es ein Problem mit den Ordnern im HUD ?
Als ich die Ziele unter Standard hatte konnte ich jederzeit "BY Wald 1" laden.
Als ich die Ziele in den Ordner Hof verschoben habe per Drag and Drop. Und dann auf Laden gedrückt habe war das HUD weg.
Und mein gespeicherter Spiel stand.

Gruß

Christian



![fsScreen_2022_12_31_00_29_51](https://user-images.githubusercontent.com/121508397/210118010-c62b3f9f-d322-46df-b880-b1edaaea247f.png)

**Comment by TrekkerPapa** [comment]
Servus Axel32019,

Willi aus dem HOT Team konnte mit Helfen. So wie es ausschaut hat aber das HUD einen Fehler oder ich mache beim Speichern was falsch. Denn so wie es ausschaut ist es so das wenn man eine "Route" laden will das Autodrive abstürzt.

Gruß

Trekkerpapa
Christian
