### ISSUE TITLE
From version 2.0.0.6 to version 2.0.09, user settings of every vechile can not saved.

### ISSUE THREAD

**Issue by shimq520** [Stephan-S/FS22_AutoDrive#789]
From version 2.0.0.6 to version 2.0.09, user settings of every vechile can not saved.

**Comment by shimq520** [comment]
Every time you restart the game, the task and land selection of each vechile will be lost, and you need to select again.

**Comment by Iwan1803** [comment]
The problem was allready solved in 2.0.0.9, see the release notes:
> vehicle settings (like pickup&deliver) disappeared after a restart #609

**Comment by shimq520** [comment]
Let me reconfirm. If the problem still exists, I will take another screenshot to feed back.

**Comment by shimq520** [comment]
I tested several times, but the problem still exists.

**Comment by shimq520** [comment]
before restarting the game:
![IMG_20230102_231645](https://user-images.githubusercontent.com/10345072/210250827-c4d5a117-76e8-4efb-8c4f-ea36913302ad.jpg)
After restarting the game:
![IMG_20230102_231819](https://user-images.githubusercontent.com/10345072/210250916-ca7d0ecc-4490-4f7f-b050-b6d93855d2c1.jpg)

**Comment by shimq520** [comment]
![IMG_20230102_231645](https://user-images.githubusercontent.com/10345072/210251608-b58d5ad4-40e7-474b-846c-76338c3d52ef.jpg)
![IMG_20230102_231819](https://user-images.githubusercontent.com/10345072/210251621-517a6dab-53bc-470a-9c92-ad97123a6d2e.jpg)

**Comment by Axel32019** [comment]
Please add these files: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by shimq520** [comment]
[ad files.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10336862/ad.files.zip)

**Comment by Axel32019** [comment]
You have 5 AutoDrive-Versions in mod-Folder, which will cause unexpected behaviour!
Error: Invalid mod name 'AutoDrive2.0.4'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Available mod: (Hash: abd7ea44d78ccc46329c83e94cba7de8) (Version: 2.0.0.5) FS22_AutoDrive
Available mod: (Hash: 6ab0e517bc5f43ca899c020256a8ee21) (Version: 2.0.0.6) FS22_AutoDrive206
Available mod: (Hash: 53d2bcc19b2c3fcbca739549017a899f) (Version: 2.0.0.9) FS22_AutoDrive_2009
Available mod: (Hash: b4275b50b8214b6987a4ca664cba2339) (Version: 2.0.0.7) FS22_AutoDrive_2_0_0_7
This cause vehicle settings not saved, see:
2023-01-02 23:14   Error (d:/Users/victor/Documents/My Games/FarmingSimulator2022/savegame2/vehicles.xml): Failed to validate xml path 'vehicles.vehicle(0).FS22_AutoDrive_2009.AutoDrive#mode' for 'savegame_vehicles'. Path not registered.

1. Do not rename the zip-file! It has to be "FS22_AutoDrive", nothing else!
2. Delete all other AutoDrive-Versions in mod-Folder! Only keep version 2.0.0.9 named FS22_AutoDrive!

**Comment by shimq520** [comment]
The first version I used was 2.0.0.7, but 207 had this problem. Then I downloaded 206, 205, 204. When 209 was released, I downloaded 209. It is found that 206 also has problems and 205 works normally. In addition, I only select one version when entering the game. Even if several versions are in the mods folder at the same time, version 205 works normally.

**Comment by shimq520** [comment]
I will try to put only 2.0.0.9 in the mods folder without changing its name to see if the problem still exists. thank you.

**Comment by Iwan1803** [comment]
There should be only version inside the mod folder and this one should not be renamed as this could cause several problems.

**Comment by shimq520** [comment]
As you said, I only put 2.0.0.9 in the mods folder without changing its name. It works normally. Thank you.
