### ISSUE TITLE
Frage zum angefügtem Bild - Fahrer fährt in die falsche Richtung

### ISSUE THREAD

**Issue by TheUsforcer** [Stephan-S/FS22_AutoDrive#79]
Hallo, wie man sieht, geht die Strecke in die andere Richtung, aber auf einmal fährt er in die andere Richtung und will ne Kehrtwende machen. Woran kann das liegen
Das Auto kam gerade erst, das war vorher nicht da :P
Liebe Grüße :)

![2021-12-23 13_59_06-Farming Simulator 22](https://user-images.githubusercontent.com/12585847/147244085-76c58dce-d42b-484d-9d9c-3a93d451996c.png)
?

**Comment by TheUsforcer** [comment]
![2021-12-23 14_10_36-Farming Simulator 22](https://user-images.githubusercontent.com/12585847/147245199-cd9195ab-d2b8-48f9-a1cd-c1872ea0b48d.png)

**Comment by Axel32019** [comment]
Bitte mit Release 2.0.0.3 testen und hier berichten.

**Comment by Axel32019** [comment]
Kein Update -> closed
