### ISSUE TITLE
Problem with 2.0.0.9 

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS22_AutoDrive#794]
I only realized today that there is a problem with 2.0.0.9 that I didn't have with the previous one.
As you can see in the photo, when it has to approach the triger of the silo, as it is near the point, it stops, I have activated debugging, and you can see that it turns red, as if there was an obstacle or something else, while in the second photo, I moved the tractor forward manually, in doing so, starting the auto drive, it positions itself and begins to load correctly. It's probably a problem with that mod silo, but I checked, and there are no collision zones there.
![Screenshot_2](https://user-images.githubusercontent.com/24955554/210432509-4438d4f3-d826-4a31-840d-9d84e038f395.jpg)
![Screenshot_13](https://user-images.githubusercontent.com/24955554/210432517-0399828e-7880-4e1f-b326-d4cc93db7d4d.jpg)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10339459/log.txt)

**Comment by Axel32019** [comment]
1x F5 key -> screenshot

**Comment by Roby1164** [comment]
> 1x F5 key -> screenshot

????

**Comment by Roby1164** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/24955554/210448942-4f4bcc1f-8d7d-426e-88b0-19bccf2c925b.jpg)
![Screenshot_16](https://user-images.githubusercontent.com/24955554/210448950-682f0c23-49db-4f96-8ba8-cead9a32e89e.jpg)

**Comment by Roby1164** [comment]
With 2.0.0.7 it worked and it works
![Screenshot_17](https://user-images.githubusercontent.com/24955554/210450457-c2d1fc27-7582-425b-b7be-16e6ab05f9e9.jpg)

**Comment by Axel32019** [comment]
Settings - AutoDrive -> Collision detection -> change from FS22 to FS19
see: https://github.com/Stephan-S/FS22_AutoDrive/releases
"extended usage of TrafficDetection with FS22 or FS19 collision (new collisions bits)"

**Comment by Roby1164** [comment]
Ok, solved, I didn't quite understand how that new setting worked, so in the presence of old mod buildings, it's better to set FS19, for the collision....
