### ISSUE TITLE
Anfrage Loop-Funktion für Fahrzeuge

### ISSUE THREAD

**Issue by Evildriver6** [Stephan-S/FS22_AutoDrive#796]
Hallo zusammen. Bin mir nicht sicher ob dieses Thema bereits angesprochen wurde. Wäre es vielleicht möglich eine Loop-Funktion für "andere" Fahrzeuge zu erstellen? Die Idee: Im Strßennetz jeder Map fahren nur Fahrzeuge die die Mapper eingebaut haben. Nicht jeder kann sich die Fahrzeuge auf der Map später nach eigenem Wunsch ändern. Es wäre richtig cool, wenn es eine Option gäbe Fahrzeuge wie Autos, LKW, Traktoren usw einfach im Loop um die Karte fahren zu lassen. Ohne Zele oder Trigger. Diese Fahrzeuge würden einfach ständig über die Map fahren und so für Abwechslung sorgen.  Diese Loop-Funktion könnte doch auf die Spline der Map zugreifen und je nach Bedarf ggf angepasst und/oder erweitert werden. Ich bin immer noch im LS19 unterwegs und nutze Zielpunkte auf der Karte. Nachteil ist, dass ich jedes mal die Fahrzeuge wieder starten muss. Also das wäre mein Vorschlag für eine weitere Funktion für Autodrive :) Noch ein großes Dankeschön für die Arbeit die Ihr leistet. Ich kann mir den LS nicht mehr ohne Autodrive vorstellen. Macht weiter so und viele Grüße Stefan

**Comment by Iwan1803** [comment]
Sorry, aber wir werden für LS19 nichts mehr machen.

**Comment by Evildriver6** [comment]
Moin, es war ja für LS22 gedacht :) wäre eine coole Funktion. Grüße

**Comment by Iwan1803** [comment]
Das Problem ist, das es dennoch Rechenpower benötigt, nur damit irgendwelche Fahrzeuge (unnötig) durch die Gegend fahren.

**Comment by Evildriver6** [comment]
OK verstehe. Trotzdem vielen lieben Dank für die Rückmeldung :⁠-⁠) viele
Grüße
