### ISSUE TITLE
No Man's Land - PickUp and deliver not working

### ISSUE THREAD

**Issue by IonutDanNica** [Stephan-S/FS22_AutoDrive#797]
I've got this strange issue here, where I've setup like 4-5 or 5 times the AutoDrive and a fermenting silo on no man's land.

I have a claas karat trailer and a small tractor from the vanilla game. I've also tried like 4 other trailers and a fendt vario and the results are the same.

I have this small video showing the issue:
https://youtu.be/XzfpKt4kT74

So i'm setting it up for pickup and deliver. I've loaded it up with grass, then I activate auto-drive and All I'm seeing is that it drives at the unload point and then it waits there, doesn't disengage the autodrive, no error that I can see nothing. I've fiddled around with multiple settings, but can't seem to get it to trigger the unload function of the trailer.

I loaded another map, Pacific North West (almost the same mods loaded) and there the same loop I made with AutoDrive PickUp and deliver works.

What information is required to further debug this?

Thanks

**Comment by GTA3Fan** [comment]
I'm Having this issue with mine on Elmcreek. I have 3 cow barns and a TMR Silo, it just goes in circles to each barn but never unloads. If I manually unload and start AD again it will got the silo and refill but then again never unload at any spots. 

It worked in .7 which I may revert back to, to see if this is the problem.

**Comment by GTA3Fan** [comment]
Just loaded in with .7.  Works perfect without fail.

**Comment by Axel32019** [comment]
Please enable debug trailer and pathfinding and provide the following files: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by GTA3Fan** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10559132/log.txt)

Can't upload .xml files, says github doesn't support file type. I have however uploaded to Drive for access. 
https://drive.google.com/drive/folders/1i7vKvSDMcX02iyqM1FQeHX7b8B8yO43e?usp=sharing

I also attached 2 videos, one for each version.

.7
[https://youtu.be/HAyKPZE2xsI](url)
.9
https://youtu.be/ATKTYjiXnHU

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10559132/log.txt)

**Comment by Axel32019** [comment]
@GTA3Fan Please try with version 2009, setting Maximum trigger distance to 25m.
You have set 10m. If 25m is working, you should move the destination backwards in drive direction.

**Comment by GTA3Fan** [comment]
@Axel32019 This worked for me, I left the destinations alone and left running for several trips. Everything seemed to work as intended now. Glad it was mostly user error/input and not the mod. 

Was there something that changed between the two versions that made it work at 10m on .7 and not on .9?

**Comment by Axel32019** [comment]
The reference for trigger detection changed from front vehicle only to all fill units to allow better detection.
