### ISSUE TITLE
Request for information on changing the Italian language file

### ISSUE THREAD

**Issue by Markus33-ITA** [Stephan-S/FS22_AutoDrive#8]
Hi guys. how can i make changes to the italian language file?
Tells me:
"You're making changes in a project you don't have write access to. We've created a fork of this project for you to commit your proposed changes to. Submitting a change will write it to a new branch in your fork, so you can send a pull request."

I created a pastebin by adding the missing translations and making some changes.
https://pastebin.com/VdeekzDv

Great for the work you do.

**Comment by Stephan-S** [comment]
Hey,
thank you for that.
Here are instructions in case you want to do the pull request:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

If not, I am happy to just copy the file and add it myself. Though that means that you will not be the official "creator" of those translations in Github and will not be listed as contributor :D 

Anyhow, if I don't see a pull request from you in the next days, I will put the translation in myself.

Best,
Stephan

**Comment by Markus33-ITA** [comment]
Hi Stephan-S.
Thanks a lot for the answer. I hope I haven't messed up. In theory I should have followed the guide well
