### ISSUE TITLE
Selecting fill type using the new helper HUD

### ISSUE THREAD

**Issue by Malfed** [Stephan-S/FS22_AutoDrive#80]
Hey,

Summary:
when you sit in a tractor with an attached trailer and select a second tractor with an attached tank (no trailer) using the helper HUD you cannot select the liquid fill types, but the trailer specific fill types only.

In Detail - how to reproduce:

You need two tractors (e.g. Fendt + Massey Ferguson) , one trailer and one luqid tank (Joskin Aquatrans 7300 S e.g.). Attach the trailer to the Fendt and the Joskin to the Massey Ferguson. Now select "Pickup and Deliver" in AutoDrive while using the Fendt. You are able to select all fill types for this trailer:

![image](https://user-images.githubusercontent.com/24369031/147256638-89f8383a-da92-4a06-aa8b-7832e294aaef.png)

Now switch to the helper HUD menü while still sitting in the Fendt. There you are able to select the same fill types for the Fendt. But now click on the Massey Ferguson to select it, switch AutoDrive to "Pickup and Deliver" and try to select a valid fill type for the Joskin. You are not able to select Water. Instead you see all fill types of the vehicle you are currently sitting in (the Fendt):

![image](https://user-images.githubusercontent.com/24369031/147256835-4066def1-65cb-4f8f-8b05-01596b4a0207.png)

Of course you can do this the other way round. Jump into the Massey Ferguson, open the helper HUD and click on the Fendt. Now, while the Fendt is selected, you are only able to select "Water" though having a trailer attached:

![image](https://user-images.githubusercontent.com/24369031/147256911-15989fdc-5d03-470a-adc6-fe3c0135ec14.png)

I think the drop down menu does not consider the vehicle clicked on but only uses the vehicle you are currently sitting in. I think this can be reproduced with any available vehicle.

**Comment by Malfed** [comment]
To be sure, I just tested it with version 2.0.0.2: the problem persists even with the latest version.

**Comment by Stephan-S** [comment]
Yeah, there is only so many issues I can close in one day :D
