### ISSUE TITLE
Loading and delivery (unload): Bale or Pallet

### ISSUE THREAD

**Issue by huseyinsayar** [Stephan-S/FS22_AutoDrive#802]
The "load and deliver" option for AD works fine for bulk products (wheat, straw etc.).
However, with arcusin, I was unable to deliver "hay bales" from field 1 to the biogas power plant, or to deliver palletized eggs from the chicken coop to the point of sale.
I tried archimobil scriptlide, I also tried universal autolad script.
Is there a video tutorial?
I write using translation. Sorry for typos.

**Comment by wackoamd1** [comment]
its not you , i have the same problem , u cant set it to bales , so it wont unl;oad.
when u have any kind of bale trailer ,  modded , autounload ( which also  doesnt work) or official bale trailers.
the dropdown to select the product just does not work the only thing in there is wheat as if u are driver a single tractor without a trailer. hope it gets fixed soon

**Comment by Iwan1803** [comment]
Since the Vanilla bale trailers can only load bales, there is no need to set "bales" as the load.
I can unload with both trailers so far without any problems. You have to make sure that the target point is not too close to the unloading trigger.

**Comment by Misamangame** [comment]
Lots of triggers on lots of maps simply not working for that. Same for many modded bale warehouses. Otherwise it works fine but like Iwan said point of unload must be set far away after trigger (vehicle with bales must go over that) in case of some it needs lots of testing.
