### ISSUE TITLE
multiple vehicle  leading off a combine

### ISSUE THREAD

**Issue by devilboy123** [Stephan-S/FS22_AutoDrive#803]
when iam leading crop of the field with multiple tractor and trailer if one get full and the other one is wait to get call by the combine they get stuck i wonder if there a way to stop that happening

**Comment by Iwan1803** [comment]
They get stuck? What exactly happens?

**Comment by devilboy123** [comment]
They get in each other way when one  coming to the field marker and the other wait for the combine to fill just wondering if u can a third Box on the combine  tab so u can have  the number of the field then where it going eg farm slio  then another  one  when they come back in field so there don't get in the way of each other

**Comment by Iwan1803** [comment]
Punctuation would make it easier to read and understand... 🙄
If the vehicles get in each other's way at the field destination, an incorrect field exit strategy is probably being used. It is recommended to use catch lines around the field and then use "Nearest" as the strategy.
