### ISSUE TITLE
Bunkersilo befüllen

### ISSUE THREAD

**Issue by Noggle70** [Stephan-S/FS22_AutoDrive#804]
Hallo, 

ich habe den Kurs zum Befüllen eines Bunkers aus dem Link von einem geschlossenen Thema hier abgeschaut

https://www.youtube.com/watch?v=h9HxOlC9hPQ

Funktioniert auch ein paar mal ganz gut, sagt er doch nach einer gewissen Zeit, er finde den Weg nicht mehr.. 
Was mache ich falsch ??

![AD 1](https://user-images.githubusercontent.com/86755520/213868093-afcd34b7-0a60-4619-88e5-b800a599ac4c.jpg)

**Comment by 60erjonny** [comment]
hi
Ich denke, nach etlichen abladen, bist du zu nah am Abfahrpunkt angelangt. Setze den weiter weg...

**Comment by Iwan1803** [comment]
Die Wegfahrlinie ist zu dicht vor dem Fahrzeug und daher findet AD keinen Weg mehr.

**Comment by Noggle70** [comment]
Habe es geändert und es funktioniert wieder wunderbar. 

Vielen Dank für die Hilfe und das tolle Video. 

Kann dann geschlossen werden..
