### ISSUE TITLE
Bunkersilo befüllen

### ISSUE THREAD

**Issue by funmusic73** [Stephan-S/FS22_AutoDrive#805]
Hallo zusammen!
Ich habe seit einigen Tagen das Problem, dass das Silo nicht mehr abgeladen wird. Ich habe zwei Silos nebeneinander beim ersten hat alles Problemlos funktioniert. Beim erstellen der Strecken, habe ich beide Silos miteinander eingerichtet. Nun beim zweiten fahren die Abfahrer alle Punkte auch an, nur laden sie nicht mehr ab. Der Abfahrer kommt, fährt aber mit dem vollen Wagen wieder weg. Die Einstellungen hab ich nicht verändert. Habe nun verschiedene Einstellungen probiert, auch das gesamte Silo leer gemacht, die Abfahrpunkte neu eingefahren, jedoch keine Änderung. Habe die Version von gestern mit dem Bunkersilofix drauf.
Welche Dateien braucht Ihr von mir noch?

**Comment by Iwan1803** [comment]
Screenshots und das Logfile wären schon mal hilfreich...

**Comment by funmusic73** [comment]
Hallo Iwan, danke für deine Nachricht. Weil in diesem Bereich nur AD Fahrer unterwegs sind. Mit dem neuen Update funktioniert das Abladen jetzt einwandfrei. Danke für eure Arbeit.
