### ISSUE TITLE
Fertilizer usually trailers not loading at bin

### ISSUE THREAD

**Issue by TSO-Original** [Stephan-S/FS22_AutoDrive#806]
Ran into an issue last night. Might be the first time loading fertilizer spreaders with lime at bins with 2.0.0.9.

Courseplay (7.2.0.0) and Autodrive linked. Spreaders are not filling. They drive up to the bin slowly. Pause at the Stop trigger, then autodrive turns off and courseplay drives away empty.

Tried adding a waypoint/trigger for tractors that would pause with the trailer just under the spout to see if that would help. Tried 2 different tractors, 2 different trailers, and tried 3 silo locations.

Run a lot of trucks hauling lime and other materials and they seem to be working as expected to load and unload.

**Comment by Iwan1803** [comment]
Screenshot of the route and situation could be helpfull.

**Comment by Axel32019** [comment]
no feedback -> closed
