### ISSUE TITLE
Frage zum "Laden- und Entlademodus"

### ISSUE THREAD

**Issue by Stagehand87** [Stephan-S/FS22_AutoDrive#807]
![Screenshot_20230120_161605](https://user-images.githubusercontent.com/123071938/214662773-87fa6990-bfcd-488e-88c0-0083045ccce9.png)

Haben die zwei Symbole vor den Lade- bzw. Entladestellenauswahllisten eine Funktion? Man kann sie unabhängig von einander von "Weiß" auf "Blau" stellen. 

Vielen Dank

**Comment by TobiHH78** [comment]
Ja, haben sie. Gibt es glaube ich schon seit Version 2.0

*Automatische Auswahl des Abladeziels (anhand des Verkaufspreises)
*Automatische Auswahl von Abholpunkten hinzugefügt (anhand des Einkaufspreises)

Bei blau sucht sich AD automatisch die günstigste Einkaufsstelle bzw. Verkaufsstelle mit dem höchsten Verkaufspreis. Das ist dann nicht zwingend der eingestellte Punkt. Bei weiß fährt er halt grundsätzlich zu dem eingestellten Punkt, unabhängig von Einkaufs-oder Verkaufspreis.
