### ISSUE TITLE
FS22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:672: attempt to index field 'attacherJoint' (a nil value)

### ISSUE THREAD

**Issue by zywang981** [Stephan-S/FS22_AutoDrive#808]
Hi all,

I have encountered a (possible) bug while using Autodrive and courseplay.

When this problem appears, the game just froze for a few seconds then it restores, after it backs to noraml, the vehicle with Courseplay leaves a blank of the working field, i.e., during the "frozen" time, the vehicles appears to keeo driving but not working (not sowing/harvesting).

I have attached the log file below.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10516385/log.txt)

Appreciate it in advance,

Dan

**Comment by Axel32019** [comment]
Hello @DanielMayerszyw, At lease one of your ~200 mods has an incomplete attacher definition.
Unfortunaly we are no able to check all your mods where this is missing.

**Comment by DanielMayerszyw** [comment]
Thank you for the reply Axel, would you explain a little bit what 'attacherJoint' means? Thank you again

**Comment by Axel32019** [comment]
In the XML of your mod vehicles look for:
```
    <attachable>
        <inputAttacherJoints>
            <inputAttacherJoint node="attacherJoint" jointType="trailer" attacherHeight="0.67"/>
        </inputAttacherJoints>
        <support animationName="moveSupport"/>
        <brakeForce force="0.8" maxForce="1.4" maxForceMass="14000"/>
    </attachable>

```
There must be something missing...
