### ISSUE TITLE
Fertilizer reload causing game crash

### ISSUE THREAD

**Issue by simonIOW** [Stephan-S/FS22_AutoDrive#809]
[logsnip.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10519908/logsnip.txt)

Doing a lime run on courseplay (7.2.0.0)  using a vanilla Bredal K165 and when empty it's set to do a refill at the limestation.

At the point the Bredal is empty it's reporting a formatting error which then loops repeatedly and crashes the game.  

Will try with other vehicles/trailers to see if I can repeat it.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
