### ISSUE TITLE
Drive function - vehicles keep starting and stopping

### ISSUE THREAD

**Issue by kellydigital** [Stephan-S/FS22_AutoDrive#810]
I just finished creating all the routes and points on my latest map.  But when I was finished I tried to test it.  I would pick a destination (eg. Home Silo) set it to drive and click the power button.  The tractor will drive a few points on the path.  then stop.  then drive a few more points and stop.   It eventually gets to the destination but it takes forever.

**Comment by Axel32019** [comment]
Please provide screenshots from the situation and the following files: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by kellydigital** [comment]
Here are the files you asked for:
[AutoDrive Log Files.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10528337/AutoDrive.Log.Files.zip)

**Comment by kellydigital** [comment]
This photo shows my vehicles just suddenly braking while they are following a route...

![2023-01-28_16-36-31](https://user-images.githubusercontent.com/123771705/215292262-67c9891c-a6ea-4309-8ba7-a77f7f972912.jpg)

**Comment by kellydigital** [comment]
In this image - my tractor is just sitting there even though it says driving to destination - its not moving anywhere.

![2023-01-28_16-37-41](https://user-images.githubusercontent.com/123771705/215292285-62c1093c-9a7e-4a82-86a5-1d1f8f364db4.jpg)

**Comment by kellydigital** [comment]
If I turn it off an on - nothing happens.  if I turn it off - then drive one more red dot and turn it on - it starts moving again.

**Comment by kellydigital** [comment]
Here is video of the issue:


https://user-images.githubusercontent.com/123771705/215292800-b2bb3580-7f43-4417-a084-f0eac7be4ce7.mp4

**Comment by Axel32019** [comment]
Two points:
1. Set collision height to 2m
2. Update Version to 2.0.0.9

**Comment by kellydigital** [comment]
Thanks @Axel32019  - it seems to be working better - out of curiosity - why isn't the 2.0.0.9 update showing up in the FS22 interface?  I had to manually update it, and second- what is the collision height setting used for?

**Comment by Axel32019** [comment]
It is not showing inside the game because it is not published in the Giants Modhub.
The collision height is the setting for the "box" in front / rear of the vehicle to prevent hitting other objects, vehicles etc.
You can see it if you enable Sensors in the debug settings.

**Comment by kellydigital** [comment]
> It is not showing inside the game because it is not published in the Giants Modhub. The collision height is the setting for the "box" in front / rear of the vehicle to prevent hitting other objects, vehicles etc. You can see it if you enable Sensors in the debug settings.

Thanks for the help!  This is my favorite mod hands down...  I tried using it on the new Ballyfields map recently but the lanes and gates are so narrow that every vehicle got stuck if it had a trailer...  I switched to a more wide open map -and now its perfect!
