### ISSUE TITLE
Fehler bei nutzen AD

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS22_AutoDrive#811]
Sobald wir fahren lassen mit ad bekommen wir fehler
Hoffe uns kann einer Helfen
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10526133/log.txt)
Danke schon mal

**Comment by Axel32019** [comment]
Kein Fehler von AD erkennbar, jedoch deutet dies eher auf ein mögliches Problem mit FS22_EasyDevControls hin:
2023-01-28 07:27   Info: Tweety mehr Kraft
2023-01-28 07:27 Error: Running LUA method 'packetReceived'.
dataS/scripts/network/Server.lua(468) : attempt to index local 'object' (a nil value)
2023-01-28 07:27 Error: Running LUA method 'update'.
dataS/scripts/player/Player.lua(3101) : attempt to perform arithmetic on local 'inputValue' (a nil value)

**Comment by Bandesss** [comment]
Ok danke
