### ISSUE TITLE
Probleme beim Entladen

### ISSUE THREAD

**Issue by Mc-Games** [Stephan-S/FS22_AutoDrive#813]
Hallo zusammen, ich beschreibe das Problem hier, weil ich (fast) alle sämtlichen Einstellungen im AD schon durchprobiert habe - ich setze meinen Zielpunkt so, dass der Hänger zum Abladen im Trigger steht. Nun das Fahrzeug fährt zum Silo und der Hänger kippt schon vor dem Zielpunkt ab dh nach Beendigung fährt er noch die paar Meter zum Zielpunkt und schaltet dann ab. Zudem stelle ich fest, wenn ich in den Einstellungen "hinten abladen" einstelle, dann kippt der Kipper trotzdem rechts ab, auch im Hud ist "hinten" eingestellt, das wechselt allerdings dann auf "rechts". Welche Einstellung regelt das ordnungsgemäß, so dass der Traktor wirklich bin zum Zielpunkt fährt? Abladesymbol ist richtig eingestellt!
Danke für hilfreiche Tipps!

**Comment by Iwan1803** [comment]
Wenn in AD "automatische Abladeseite" eingestellt ist, kannst du im F1-Menü einstellen was du willst = AD ignoriert es.
Für die anderen "Probleme" wären Screenshots hilfreich.

**Comment by Mc-Games** [comment]
Danke für die prompte Antwort, ich habe versucht die entspr Screens zu machen
![AbladePunkt](https://user-images.githubusercontent.com/29283879/215546720-271ba128-4c34-4e9a-9513-0673101897f6.jpg)
![FahrzeugEinstellung](https://user-images.githubusercontent.com/29283879/215546727-3671485d-8282-488b-ba8c-94ab02284b89.jpg)
![GlobalEinstellung](https://user-images.githubusercontent.com/29283879/215546733-8ec1044a-2681-4713-a609-0770aaff2c25.jpg)
![PersEinstellung](https://user-images.githubusercontent.com/29283879/215546736-691800d2-49c5-4f1a-b9e6-9dfe7e22ad06.jpg)

**Comment by Mc-Games** [comment]
Nun, ich dachte, wenn es auf "Nein" steht, dann lädt er überhaupt nicht ab.
Aber es dürfte jetzt funktionieren, muss die Option nur noch in die entspr Fahrzeuge eintragen!
Danke!

**Comment by Iwan1803** [comment]
Wenn du mit dem Mauszeiger über die Einträge gehst, kommt sogar ein Hilfetext 😉
Dann mach ich hier erstmal.
