### ISSUE TITLE
AD nach Serverneustart

### ISSUE THREAD

**Issue by Bandesss** [Stephan-S/FS22_AutoDrive#815]
Hallo um 7 Uhr wird der Server neu gestartet, als ich den Fahrer auf das Feld 16 los schickte kommte der Fehler
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10610361/log.txt)
Was habe ich falsch gemacht.

Ein Paar Minuten später
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10610369/log.txt)

Hoffe ihr seht es
Gruß

**Comment by Axel32019** [comment]
Hallo @Bandesss , Ihr habt immer noch FS22_aPalletAutoLoader Version: 1.8.7.1 aktiv, welches diese Fehler ohne weitere Meldung schmeisst. Mit Version: 1.8.7.2 wird das eindeutig zugeordnet, siehe:
- Unload lua Fehler umgangen und Log Einträge eingefügt. Beim Auftreten der Warnung soll die ganze Log in den Discord Kanal des Autoloaders geposted werden.

**Comment by Bandesss** [comment]
Oha entschuldigung, das wusste ich nicht
Danke
