### ISSUE TITLE
JD 1775 NT planter reversing issue

### ISSUE THREAD

**Issue by Misamangame** [Stephan-S/FS22_AutoDrive#817]
Hello guys,
I have problem with reversing JD 1775 planter into parking position.  The joint on this implement get fixed and therefore tractor moving whole equipment in bad direction even when he trying to get it into right position. Not sure if it caused by some Giants issue, but I did not experienced it with anything else (so far). Tested with mutiple tractors with same results. I know Kinze planters reveresing just fine.

https://youtu.be/qEEzuqQVxd4

**Comment by Axel32019** [comment]
same as #637
