### ISSUE TITLE
FS22 - Auger Wagon will not pipe out

### ISSUE THREAD

**Issue by MrKiel** [Stephan-S/FS22_AutoDrive#818]
Hi,

I'm attempting to harvest sugarcane using a pulled sugarcane harvester. 
I have a tractor, which pulls the sugarcane harvester, which in turn pulls an auger wagon. 

This setup allows the sugarcane to be stored in the auger wagon while being harvested, to unload into a trailer using autodrive. 

Unfortunately, I have not found a working configuration of autodrive that allows the auger to unload into a nearby trailer. 
An autodrive-powered unloading trailer will drive up to the auger wagon (working as expected), but the auger wagon will not start unloading. Everything but this step is working correctly - the positioning etc seems correct based on my manual testing, it's simply that the harvesting vehicle will not activate the auger wagon to unload into the nearby trailer. 

I'm not clear on where the problem lies, as the tractor-harvester-auger wagon combination is powered by courseplay. Could this perhaps be an issue with courseplay instead?

**Comment by Misamangame** [comment]
If you have tractor which towing harvester and then auger wagon, it will never work. And yes it will be CP problem, but it is not issue really it will simply not hadle two implements supposed to do different work. And then real fact that towed sugar cane harvester cannot provide any power into auger wagon for unloading as there is no PTO connection...

**Comment by MrKiel** [comment]
> If you have tractor which towing harvester and then auger wagon, it will never work. And yes it will be CP problem, but it is not issue really it will simply not hadle two implements supposed to do different work. And then real fact that towed sugar cane harvester cannot provide any power into auger wagon for unloading as there is no PTO connection...

Is there a configuration of sugarcane harvesting which _does_ work with Autodrive / Courseplay (i.e. am I just doing it wrong)?
