### ISSUE TITLE
If you exit a tall vehicle [harvester] get stuck

### ISSUE THREAD

**Issue by Shiney101** [Stephan-S/FS22_AutoDrive#819]
If you put a harvester [tried many] on a go to route you lose access to the mouse [pc] and if you try to leave the vehicle it gets more screwy, can't use the map etc.

**Comment by Misamangame** [comment]
It must be some of your mods because I'm using ton of harvesters sending them on routes all the time with no issue like that.

**Comment by Iwan1803** [comment]
Without further informations, screenshots or logs... how should we help?

**Comment by Axel32019** [comment]
no feedback -> closed
