### ISSUE TITLE
Running LUA mathod 'mouseEvent' Error

### ISSUE THREAD

**Issue by TheFLiP97** [Stephan-S/FS22_AutoDrive#82]
Erstmal die log Datei:
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7770253/log.txt)
Der Fehler ist im Release 2.0.0.1 aufgetreten
Ich habe neue Strecken erstellt und dann sind die FPS gedroppt und die Änderungen seit letzten Start des Savegames wurden nicht gespeichert. In der Log Datei sind noch andere Lua Fehler.

Vielleicht Lösung:
Den Fehler in "FS22_AutoDrive/scripts/Hud.lua:800: attempt to perform arithmetic on field 'y' (a nil value)" habe ich selber versucht zu lösen. Ich habe die Zeile 800: "local _, _, depth = project(node.x, node.y + AutoDrive.drawHeight + AutoDrive.getSetting("lineHeight"), node.z)" in die Überprüfung if node ~= nil and... hineingezogen. Seit dem habe ich diesen Fehler nicht mehr bekommen

**Comment by Iwan1803** [comment]
Bitte 2.0.0.2 runterladen und erneut probieren.

**Comment by TheFLiP97** [comment]
Ich habe jetzt bisschen mit der neuen Version getestet und ist nicht mehr vorgekommen. Wenn es nochmal vorkommt melde ich mich. Danke für den schnellen Support.
Ps.: sorry, dass ich nicht gleich gesehen habe das ein neuer Release da ist.
