### ISSUE TITLE
grain augers

### ISSUE THREAD

**Issue by runzik** [Stephan-S/FS22_AutoDrive#820]
there seems to be a problem with AD detecting the trigger for grain augers not matter what iv seem to do the truck always drive just past the trigger point just far enough where it hit the trigger just enough to stop but will not dump czu it went to far

**Comment by 60erjonny** [comment]
Hallo

Please more information about your problem. What speed does the downhill have ...?

**Comment by runzik** [comment]
im not sure what other info you may need the only that i have done any different then before was i need to keep the trigger distance at 100m or the truck fly's right past it and goes to the stop point 

and i side note im never used grain auger pipes with AD to load the bins before

**Comment by 60erjonny** [comment]
Hallo
Show us all ad settings in screenshot...Possibly test other vehicles ...

**Comment by Axel32019** [comment]
no update - closed
