### ISSUE TITLE
Re-open the game, the parking location records of all cars disappear

### ISSUE THREAD

**Issue by richarduncle** [Stephan-S/FS22_AutoDrive#821]
The device I am using is a 2021 MacBook Pro (M1 PRO), the operating system is macOS Ventura13.1, the game is installed on the steam platform, and the AutoDrive version is 2.0.0.9.
Re-open the game, the parking location records of all cars disappear.

**Comment by Sam-D03** [comment]
+1 on this issue

**Comment by Iwan1803** [comment]
Log?

**Comment by Axel32019** [comment]
Please add these files here: AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml.

**Comment by Iwan1803** [comment]
No Log, no support -> closed.
