### ISSUE TITLE
Verbesserungen bei Autodrive

### ISSUE THREAD

**Issue by goldorel** [Stephan-S/FS22_AutoDrive#822]
Hallo, ich habe zwei Vorschläge zur Verbesserung von Autodrive. Der erste Vorschlag, bitte machen Sie im Menü Autodrive, damit Sie nicht nur angeben können, wie viel Sie in Prozent hochladen möchten, sondern Sie können auch auswählen, wie viel Sie in Liter laden möchten, es ist sehr praktisch, wenn Sie eine bestimmte Menge in Liter mitnehmen müssen. Der zweite Satz, wenn Sie die Funktion Entladen und Liefern ändern auswählen, fährt Autodrive, wenn er Produkte von der Liste in Ordner zu allen Orten bringt, nicht zum Parkplatz zurück, sondern beginnt erneut, durch die Liste aus dem Ordner zu fahren. Bitte machen Sie es, damit Autodrive, wenn er durch diese Orte aus dem Ordner gefahren ist, wenn Sie die Funktion Download und Lieferung ändern auswählen, zum Parkplatz fährt, und nicht erneut in der Liste. Und bitte machen Sie die Anzahl der Flüge, wie oft er durch die Liste aus dem Ordner zu jedem Ortspunkt fahren muss? Vielen Dank im Voraus

**Comment by goldorel** [comment]
Vielen Dank für die Antwort.

**Comment by Iwan1803** [comment]
Die neue Version ist da: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
