### ISSUE TITLE
Frage FS22 UniversalAutoload 

### ISSUE THREAD

**Issue by Mannie313** [Stephan-S/FS22_AutoDrive#823]
Hallo AD Team. Wäre es möglich bei diesem mod FS22_UniversalAutoload genauso abzuladen wie bei FS22_aPalletAutoLoader.

Das wäre sehr hilfreich.

MFG Mannie313

**Comment by Axel32019** [comment]
Ist in Arbeit...

**Comment by Mannie313** [comment]
Danke für die info.

MFG Mannie313

**Comment by Axel32019** [comment]
implementiert: https://github.com/Stephan-S/FS22_AutoDrive/commit/140a7d66dc59befc45b8bbb3e7a20d66019b74a5
