### ISSUE TITLE
Bad functionality of Offset

### ISSUE THREAD

**Issue by S-eler** [Stephan-S/FS22_AutoDrive#824]
Hi! This is not a bug, this is a feature - I know. But it would be perfect if would be an option to "freeze" offset.

At this moment, if I set course 90 degree with offset -2,7m, on drive back (course 270 degree) offset will be 2,7m, on the opposite side of the vehicle. But when I'm using bale loader trailer (Anderson, from base game) I need minus offset in both directions.

Here you have correct 90 degree course:
![IMG_0465](https://user-images.githubusercontent.com/121870418/218450640-123cb535-db0e-4063-9e5b-2a4eca6ff1b5.jpeg)

and here what we receive after turning back:
![IMG_0466](https://user-images.githubusercontent.com/121870418/218450762-99504375-5ca5-4902-8b31-f61ae12b6ae5.jpeg)

Option for a checkbox for "freezing" offset would be magnificent - at this moment I need to manually shift track left/right after each turn :(. And I'm a lazy bastard.

Sorry for photos, but I suddenly discover that my keyboard (Logitech k780 didn't have prntscreen key O.o")

**Comment by Axel32019** [comment]
No AD topic -> closed
