### ISSUE TITLE
ENHANCEMENT: Pickup and Deliver to multiple destinations

### ISSUE THREAD

**Issue by TWProductions** [Stephan-S/FS22_AutoDrive#827]
A couple of useful additions could be
- the ability to pickup say TMR from a central point and delivery it to multiple Cow pens
- the ability to collect Slurry from multiple cow pens and deliver to a central point

**Comment by Axel32019** [comment]
Already available since years: https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-HUD-Button
