### ISSUE TITLE
Kreisverkehr

### ISSUE THREAD

**Issue by mulei2507** [Stephan-S/FS22_AutoDrive#83]
Also der Radius mit dem Mausrad ist echt toll. Aber ich fände es sinnvoller  wenn man es in beiden Richtung machen könnte dann kann man vielleicht sinnvolle Kreisverkehr machen.

**Comment by Iwan1803** [comment]
In beide Richtungen wäre interessant, vor allem wenn man grüne mit blauen Linien verbinden möchte, wo an der blauen eine grüne angebunden ist, welche in die andere Richtung geht.
Kreisverkehr geht mit Sicherheit jetzt schon, wenn man ein Achteck aufmalt und dann die Wegpunkte als Kurven verbindet.

**Comment by mulei2507** [comment]
Also ich hab das nicht hinbekommen weil um eine kurve zu machen erst ein grade line sein muß aber ich warte bis du dazu ein YT Vidio machst :)

**Comment by Iwan1803** [comment]
Meinen letzten Kreisverkehr habe ich selber eingefahren. Dazu habe ich mir dem Landschaftstool einen großen Kreis mit Wiese gemacht und drumher wurde dann der Kreisverkehr eingefahren.
Theoretisch braucht man "nur" ein eingefahrenes Quadrat und verbindet dann innendrin die Kurven:
![image](https://user-images.githubusercontent.com/47528836/147301184-08d2e9d7-2d4b-42bd-a3f5-57ca9ee0e09c.png)

**Comment by mulei2507** [comment]
Super mit dem Quadrat klappt auch gut :)
