### ISSUE TITLE
Ballen abladen

### ISSUE THREAD

**Issue by PhilippS1** [Stephan-S/FS22_AutoDrive#830]
Hallo zusammen,
habe das selbe Problem wie schon viele anderen auch, jedoch finde ich keine Lösung. Auf der Map Ostseeküste wurden zwei Ballen Trigger verbaut, einmal ein ganz normaler Ballenverkauf und der zweite für die BGA. Am Ballenverkaufstrigger läd AD ganz normal ab. Jedoch den BGA Trigger erkennt AD nur läd aber nicht ab, manuel kann ich dort aber abladen. Hab schon die Anfahrtsrichtung gedreht und den Wegpunkt etwar eine Fahrzeugslänge hinter das Trigger Ende gesetzt, leider ohne Erfolg.
Siloabstand habe ich auf 50 Meter eingestellt.

**Comment by rohne83** [comment]
Hat man auch auf der Landkreis Rostock, egal ob einem die BGAs gehören oder nicht. Frage ist halt ob das ein AD-Problem ist, wenn der normale Verkaufstrigger ja funktioniert, oder ob es nicht doch eher an den BGAs liegt.

**Comment by PhilippS1** [comment]
Das ist es ja, es kann an sovielem liegen. Habe gelesen das es selbst an einer falsch ausgerichteten AInode kommen kann

**Comment by regs1980** [comment]
Das einfachste was man machen kann ist, entlade Ballen an AD Punkt XY, ob da ein Trigger ist oder nicht, bietet somit auch die Option der Feldrandentladung. Da AD mit Autoload umgehen kann kann man diese dannn auch mit einem LKW Gespann zum passenden Trigger fahren, macht das ganze noch realistischer.
Das wichtigste ist, es hört auf mit dem spontanen selbst entladen auf der Straße, wenn man an einem Trigger Punkt vorbeifährt.
https://discord.com/channels/640957956027973633/690252595700302195/1050079732894548028

**Comment by PhilippS1** [comment]
Habe das selbe Problem jetzt mit einem Getreideanhänger an einem Verkaufstrigger. Der Trigger wird erkannt die Abdeckung geht auf, jeodoch der Annhänger wird nicht gekippt. Komischerweise passiert das nicht jedesmal und auch nicht mit jedem Anhänger.

**Comment by Iwan1803** [comment]
Das Thema Ballenwagen wurde in der neuesten Version überarbeitet: 
https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0
