### ISSUE TITLE
Ziele in aktiven Fahrzeugen ändern sich ungewollt

### ISSUE THREAD

**Issue by roland45** [Stephan-S/FS22_AutoDrive#831]
Verdacht auf eine Fehlfunktion des Menüpunktes  „Ziele anwählbar“.
Nach längerer Ursachenforschung glaube ich, den Fehler lokalisiert zu haben. Die Zieländerungen traten bei mir nach Aktivierung der AD Funktion „Ziele anwählbar“ auf, indem bei Anklicken eines Zieles in der Übersicht, dieses Ziel sich nicht nur ins gewollte Fahrzeug, sondern auch in mehrere andere aktiv arbeitende Fahrzeuge eintrug.
Log ist ohne Fehler und Warnungen, auch nach dem Fehlerauftritt keine Eintragungen. Map ist NF-Marsch o.G  und AD in Version V2.0.0.9

**Comment by Iwan1803** [comment]
Ich habe diese Option bei mir auf diversen Maps aktiv und kann dieses Problem nicht nachvollziehen. Nur in dem Fahrzeug, in welchem ich sitze, ändert sich das Ziel.
SP, MP oder Dedi? Bekommen wirklich alle Fahrzeuge dieses angeklickte Ziel oder wechseln sie auf irgendwas?
Bitte das ganze nach dem Start vom Spiel noch mal prüfen und im Anschluss das Log bitte dennoch mal hier hochladen.

**Comment by roland45** [comment]
Ich habe den damaligen Spielstand von einer Sicherung eingelesen und versucht die Situation nachzustellen. Damals hatte ich ung. 10-12 Fahrzeuge mit ihren Aufgaben auf der Karte „NF Marsch o.G“ ohne Fehler unterwegs als ich die Idee hatte einmal mit der Funktion „Ziele anwählbar“ über die Übersichtsmaske den weiteren Spielablauf zu steuern. Das Ergebnis war eine schleichende Verschlechterung der Abläufe (dachte zuerst an eigene falsche Eingaben) bis hin zu willkürlichen nicht nachvollziehbaren Abläufen bei vielen der Fahrzeuge.
Folgende Dokumentation beschränkt sich auf 3 Fahrzeuge, 1 Drescher mit 2 Abfahrern und ein Pritschenwagen für Paletten. Die Doku_230222.zip Datei enthält: AutoDrive_Config.xml, log.txt, vehicles.xml und Screenshots mit Dokumentation der Abläufe 
Aus meiner damaligen Situation war ersichtlich, daß mehrere verschiedene Fahrzeuge gleichzeitig betroffen waren.  Nach weglassen der Zieleingaben über die Übersichtsmaske und Verwendung des AD HUD für die Zieleingabe war die Situation, auch mit den gleichen Fahrzeugen und ohne Änderungen, wieder korrekt möglich.  (Datei zu groß, daher einzel)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10803769/log.txt)

**Comment by roland45** [comment]
[Screenshots1.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10803825/Screenshots1.zip)
[Screenshots2.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10803828/Screenshots2.zip)
[Screenshots3.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10803832/Screenshots3.zip)

**Comment by roland45** [comment]
[Dateien.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10803857/Dateien.zip)

**Comment by TangoMike1982** [comment]
Ich habe aktuell selbiges Problem. Drescher abfahren führt zu ungewollten Zielortänderungen, obwohl man sie nicht ändert. Statt "Feed and Grain South" wird auf einmal z.B. der "Gesteinsbrecher" oder irgendein anderer Verkaufsort angefahren.

**Comment by Axel32019** [comment]
Hallo @roland45 , Danke fürs Nachstellen. Leider kann ich das nicht nachvollziehen und würde Dich bitten folgende Version zu verwenden. Nach Auftreten der Änderung bitte Screenshot generieren und anschließend die log.txt mit hier anfügen.
[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10828362/FS22_AutoDrive.zip)

**Comment by roland45** [comment]
Hallo, anbei die log.txt, erstellt mit Deiner AD Datei und dazu die Screenhots. Hoffe es ist eine Erkenntnis aus der log zu erhalten, ich habe bis jetzt noch keine Logik aus den Abläufen erkennen können.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10830847/log.txt)
[Fotobeschreibung 20230225.docx](https://github.com/Stephan-S/FS22_AutoDrive/files/10830849/Fotobeschreibung.20230225.docx)
[Doku_230225_a.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10830850/Doku_230225_a.zip)
[Doku_230225_b.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10830853/Doku_230225_b.zip)
[Doku_230225_c.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10830854/Doku_230225_c.zip)

**Comment by Axel32019** [comment]
Hallo, egal was ich versuche ich bekomme das nicht nachgestellt!
Jetzt bleibt nur noch Ausschliessen der mods, dazu erstmal nur mit Karte, AD, CP anfangen...
Wichtig: mods nicht nur deaktivieren sondern in einen anderen Ordner verschieben.
Hierzu auch diese Version verwenden:
[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10831543/FS22_AutoDrive.zip)

**Comment by roland45** [comment]
Ist auch ziemlich unverständlich, was hier passiert. Außerdem zeigt die log ja keinerlei Fehler auf. Da ich die Funktion "Ziele anwählbar" **normalerweise ja sowieso nicht verwende** ist mir ehrlich gesagt das Auslagern von 106 Mods und dann schrittweise nachstellen und Testen schon alleine zeitlich nicht möglich, noch dazu kann ich ja ohne dieser Funktion einwandfrei und ohne Fehlfunktion  AD verwenden. Wenn gewünscht könnte ich auch die gesamte "FarmingSimulator2022" Datei an Euch überspielen. Sollte in Zukunft auch ohne "Ziele anwählbar" bei mir Zieländerungen auftreten müsste ich mich sowieso nochmals melden.
Besten Dank für Eure Mühe, AD ist ein Super Mod!!

**Comment by Iwan1803** [comment]
Da kein Testbereitschaft -> geschlossen!
