### ISSUE TITLE
Impossible to sell bales using Arcusin in game bale loader/transporter

### ISSUE THREAD

**Issue by k4talin** [Stephan-S/FS22_AutoDrive#833]
Please fix this issue. No way i could manage to make AD to sell bales at any sell point using the in game Arcusin 14 bales loader. I ried any way possible for like 6 hours. Forward , reverse anything. Why is Ad trying to detect triggers idk. Just make it force unload when it reached the point we set up. That would be easy fix. I believe there might be problems w triggers on some sell point from Giants side. Can u make Ad just force unload for Arcusin please? i do know arcusin need Y for unload but i presume AD knows that since he manage to unload bales randomly outside drop area few time durring my tryouts.

**Comment by Iwan1803** [comment]
Screenshot of the situation?

**Comment by k4talin** [comment]
Everyone knows this issue. AG will not unload at the sell point. I tried 12 hours over 2 days already. I managed to make it work at Animal dealer Elm creek with a weird short reverse towards one side which makes no sense. Other than that i would like to see a video that maybe u could make it work with the In game Arcusin bale loader . I do not use autoloaders. I play hard mode using in game vehicles.. I am saying this because it seems like for you this is fine working....... I even modified the map and moved ttriggers with no success is a AD problem definetely. I have noticed that Ad unloads sometimes if moving forward and being very close to drop point will intersect the reverse path. will unload at the exact point where forward intersect with reverse. I will try to get screen shot but clearely does not work. Many people know about this issue even on AD discord. No ideea why u ask for pictures.

**Comment by Axel32019** [comment]
https://www.youtube.com/watch?v=SnjHYmDEZJk

**Comment by Iwan1803** [comment]
We changed the unload of bale wagon: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0

**Comment by k4talin** [comment]
> https://www.youtube.com/watch?v=SnjHYmDEZJk
Thx for the video. Do you understand english? cause i don't understand german. The video is about different bale loader(so it does not help the case). I said Arcusin since i don't work with round bales and i will never do.

**Comment by k4talin** [comment]
> We changed the unload of bale wagon: https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0

Thx for the fix SIR. Works like a charm now.
