### ISSUE TITLE
Backup combine and stop dropping straw before pulling out of row for unloading

### ISSUE THREAD

**Issue by coatsy35** [Stephan-S/FS22_AutoDrive#834]
Hi,

When in combine mode. Would it be possible for the combine to back up straight before it moves across ready for unloading when it's not working in lands? as you get a row of straw between the two rows. making things messy for the baler when planning to use courseplay etc... Backing up until it finishes dropping straw would be better way of doing this before it turns.

**Comment by Axel32019** [comment]
Hi @coatsy35, Should this be adressed to CP?

**Comment by coatsy35** [comment]
> Hi @coatsy35, Should this be addressed to CP?

This is when autodrive is unloading the combine in forager/.combine mode. I don't think that has anything to do with courseplay at that moment does it? If I was using courseplays new combine unloader mode then perhaps. I'm not sure at which point courseplay and autodrive switch over.

**Comment by Axel32019** [comment]
AD is not controlling the combine drive, only unloaders.

**Comment by Tensuko** [comment]
Driving combine is CP part:
Might fit into this:
#2093

**Comment by coatsy35** [comment]
> Driving combine is CP part: Might fit into this: [#2093](https://github.com/Courseplay/Courseplay_FS22/issues/2093)

Yes it does. Hadn't spotted that, same scenario. Would appreciate it if you consider adding this in a future update if possible.
