### ISSUE TITLE
rotierendes Abladen

### ISSUE THREAD

**Issue by Noggle70** [Stephan-S/FS22_AutoDrive#836]
Hallo liebes Team, 

großes Kompliment für eure Arbeit, alles tadellos. 

Ich habe nur eine Frage, kein Problem.. 
Kann man bei dem rotierenden Abladen eine Reihenfolge festlegen, oder ist das immer zufällig ?

Liebe Grüße
Noggle

**Comment by Axel32019** [comment]
Hallo @Noggle70 , Das ist nicht zufällig. Die Reihenfolge ergibt sich aus der alphanumerischen Sortierung der Ziele im Ordner.
Der Name machts.

**Comment by Noggle70** [comment]
Wenn ich jetzt 3 Abfahrer habe, aber 4 Silos, wird also Silo 4 nie angefahren ?

**Comment by Axel32019** [comment]
Nein, die Ziele werden "gemanaged". Egal wieviele Abfahrer, derjenige der zu den Zielen fahren soll erhält das nächste aus dem Ordner.  Der Manager rotiert die Zuweisung bei jeder Anfrage durch.

**Comment by Noggle70** [comment]
Alles klar..
Hab vielen Dank für die schnelle Antwort..
