### ISSUE TITLE
Suggestion autogenerate path on field

### ISSUE THREAD

**Issue by k4r3l01** [Stephan-S/FS22_AutoDrive#839]
Hello please it will be possible to add this feature to automatic generate path on field headland?
Thanks in advance for any answer

**Comment by Iwan1803** [comment]
You mean the catch line along the edge of the field?
I use Courseplay for this, generating a course with 5m working width and smooth curves. Depending on how the field edge looks i go to 6m, for example if there are trees or rocks.
I start recording in AD, then let CP drive the first headland and I'm done.

**Comment by Axel32019** [comment]
no feedback -> closed
