### ISSUE TITLE
Ablade Option für Ballensammelwagen 

### ISSUE THREAD

**Issue by regs1980** [Stephan-S/FS22_AutoDrive#841]
@Axel32019 ich teste gerade deine Änderungen https://github.com/Stephan-S/FS22_AutoDrive/commit/e9266513f711813a2c2a142dd5c73a14daf91181 da ist mir was aufgefallen. Besteht die Möglichkeit dem Sammelwagen zu sagen, dass er abladen soll, bevor er an dem Ablade Punkt ist, wenn ein Hindernis ihm rückwärts den Weg versperrt.
Ich habe da mal ein Video gemacht, vielleicht kann man das noch beheben, dann wäre es möglich Ballenstapel an Feldränder, in Silos, in Hallen usw aufzustellen, sowohl Rund- als auch Quaderballen. 

https://www.dropbox.com/s/72hp7h8wp4ujcjm/2023-03-04_01-19-06_2.mp4?dl=0

**Comment by Axel32019** [comment]
@regs1980 Danke für's Testen!
Das ist nicht so einfach!
Die Sammelwagen verhalten sich alle unterschiedlich, nur für diesen hier wäre es ansatzweise denkbar.
Der Rundballenwagen lädt liegend ab, da würde der Stapel schnell sehr lang.
Die beiden anderen Wagen laden jetzt schon nur auf einem Trigger vernünftig ab, da auf freier Fläche die Ballen sofort wieder mitgeschliffen werden.
Generell ist der Funktionsumfang der Ballenwagen für Scripte sehr eingeschränkt und im MP funktioniert die Synchro besch...
Giants hat halt kein Interesse an sowas - schließlich funktioniert ja alles super von Hand!
Momentan hab ich keinen Bock mehr auf Ballenwagen, das MP-Thema hat mich schon fast 2 Wochen genervt und kein Erfolg.

**Comment by regs1980** [comment]
@Axel32019 
> Die Sammelwagen verhalten sich alle unterschiedlich, nur für diesen hier wäre es ansatzweise denkbar.
> Der Rundballenwagen lädt liegend ab, da würde der Stapel schnell sehr lang.

Es würde für beide funktionieren, einerseits kann man mit der Wiederholungszahl bestimmen, wie viel Ballenstapel auf dem Kurs abgelegt werden können und andererseits regelt das ganz dann auch noch die Länge.
Kann der Sammler nicht mehr auf den Kurs biegen und erkennt frontal ein Hindernis, bleibt er stehen und wartet bis das Hindernis entfernt ist oder man selber eingreift.

<img width="960" alt="2023-03-05 00_36_37-Greenshot" src="https://user-images.githubusercontent.com/13314443/222933606-6a54de2f-866b-4849-9f2e-d4228e84a347.png">

 
> Momentan hab ich keinen Bock mehr auf Ballenwagen, das MP-Thema hat mich schon fast 2 Wochen genervt und kein Erfolg.

Ich kann das auch verstehen aber bleiben wir bei den Fakten, die Nachfrage wird kommen und wenn man das jetzt gleich mit einfügt hast du Ruhe und brauchst nie wieder mit Ballensammelwagen irgendwas zu machen. Mehr ist mit Ballensammelwagen nicht zu machen, außer man baut Flügel dran und versucht zu fliegen.

**Comment by regs1980** [comment]
@Axel32019 Ich schließe das mal, da CP Feldabladung bald integrieren will, dann müsstest du eigentlich nur noch den Universal Autoload Mod unterstützen.

**Comment by Axel32019** [comment]
@regs1980 siehe: https://github.com/Stephan-S/FS22_AutoDrive/issues/878#issuecomment-1500924834
