### ISSUE TITLE
AutoDrive Partial Unloading Lode King 

### ISSUE THREAD

**Issue by James31283** [Stephan-S/FS22_AutoDrive#844]
AutoDrive is only unloading the rear bins from the Lode King Distinction Super double trailer.

Link to the video showing the issue: https://youtu.be/LC004JNltl8

**Comment by James31283** [comment]
Attempted to change the Autoload position setting, and no selection resolved the issue.

**Comment by Martin-L45** [comment]
Very strange. when i turn off automatic tip side it only unloads one bin. when i turn it on it unloads both.

**Comment by Axel32019** [comment]
works with Release 2.0.1.0
