### ISSUE TITLE
Einstellungen für Fold Implements werden weiterhin nicht gespeichert

### ISSUE THREAD

**Issue by Cassy-Blair** [Stephan-S/FS22_AutoDrive#850]
Ich habe festgestellt, daß im Multiplayer die Einstellung für Fold Implements noch immer nicht gespeichert wird.
Ich stelle sie auf "Nein", speichere das Spiel, beende das Spiel, betrete das Spiel neu und sie stehen wieder auf "Ja"

![fsScreen_2023_03_13_07_35_37](https://user-images.githubusercontent.com/87262647/224631042-4cdb5d99-4b55-4065-be7a-8380ab8f139f.png)
![fsScreen_2023_03_13_07_35_29](https://user-images.githubusercontent.com/87262647/224631071-0f95584b-ff32-404f-ae3b-046d3f9b2779.png)

**Comment by Cassy-Blair** [comment]
> 

Irgendwie kann ich hier keine XML hochladen. Github sagt ständig "We don't allow that file type.

**Comment by Cassy-Blair** [comment]
[Server.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/10984855/Server.zip)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/10984880/log.txt)

Habe die Server Dateien nun als Zip gepackt

**Comment by Axel32019** [comment]
Die Einstellungen werden korrekt gespeichert und korrekt geladen.
Problem ist das Menü (GUI): Hier werden immer die AD-Standard-Werte dargestellt, nicht die aktuellen.
Werden Einstellungen geändert, so werden diese auch korrekt angewendet, gespeichert und geladen.
