### ISSUE TITLE
AD Ignoriert die Ampeln

### ISSUE THREAD

**Issue by Peddig2** [Stephan-S/FS22_AutoDrive#855]
Hallo ich Spiele auf der Ollihausen und habe mir gestern die neue Version von AD Heruntergeladen.
Kollision habe ich sowohl auf LS19 als auch auf LS22 versucht aber AD fährt bei den Roten Ampeln ohne zu Bremsen weiter.

**Comment by Peddig2** [comment]
Ich benutze das Streckennetz von Iwan1803

**Comment by Peddig2** [comment]
Die KI Fahrzeuge halten an den Ampeln an.

**Comment by Iwan1803** [comment]
Ja, das machen sie auch, wenn eine veraltete Ampelversion in der Map noch drin ist.
Entweder auf den Mapper warten oder selber die passende Datei aktualisieren.
