### ISSUE TITLE
Maximler Siloabstand, bzw zum Zielpunkt

### ISSUE THREAD

**Issue by roehrich73** [Stephan-S/FS22_AutoDrive#858]
Hallo, ich hätte da einen Verbesserungsvorschlag. Wäre es möglich den Abstand zum Silo, bzw. Zielpunkt irgendwie fahrzeugbezogen zu emplimitieren? Ich finde es manchmal irgendwie störend, wenn die Zielpunkte elend weit vom eigentlichen Trigger entfernt sind.

Grüße Roehrich73

**Comment by Iwan1803** [comment]
Was nennst du "elend weit"? Nimm dein längstes Fahrzeuggespann, was du nutzt und stell es so hin, das das Ende kurz hinter der Mitte vom Trigger ist. Dann setzt du den Zielpunkt 2-3m vor das Fahrzeug und fertig.
Fahrzeugspezifisch halte für übertrieben, denn was soll das bitte bringen? Man spart höchstens ein paar Sekunden dadurch aber ärgert sich, wenn man plötzlich doch mal einen längeren Hänger nimmt und dann aber vergisst, den Abstand anzupassen.

**Comment by manne70** [comment]
Ich finde den Vorschlag nicht schlecht, ich brauche eigentlich nur den langen Siloabstand nur bei den Sähmaschinen alle anderen bremsen dann schon ewig lange vor dem Trigger auf Schleichfahrt ab. Trodzdem toller Mod macht bitte weiter so, Danke

**Comment by regs1980** [comment]
In den Fahrzeugeinstellungen wäre es besser aufgehoben, als in den Globalen. 
Zumal die Probleme mit längeren Fahrzeugen nicht hätte, so wie das.
https://github.com/Stephan-S/FS22_AutoDrive/issues/204

Auch so ein Problem wie das wäre dann hinfällig
https://drive.google.com/file/d/1ALoRMD9VGNBSsmG13yBlxlrDrkHMA4nh/view?usp=sharing
Ich muss da 50 m einstellen, sonst wird keine Dünger in meine Stadtmaschine geladen.

Man könnte auch per Voting die User im Discord entscheiden lassen, ob sie es in den globalen Einstellungen weiter haben wollen oder in den Fahrzeugeinstellungen separat, auf einen Eintrag mehr oder weniger kommt es nicht mehr an.
Weil die Anfrage ist im Discord schon oft aufgekommen.

**Comment by ThomasMatern** [comment]
@regs1980 ich mag die Idee in #962 - behalte die globale Einstellung und erlaube es in den Fahrzeugeinstellungen zu ueberschreiben. Ich kann mir das am Wochenende mal ansehen.

**Comment by regs1980** [comment]
Das hört sich gut, danke schön.

**Comment by regs1980** [comment]
@ThomasMatern funktioniert sehr gut. 
Top Arbeit.
 
<img width="1920" alt="2023-10-08 10_23_15-Greenshot" src="https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/be0cc415-0545-4275-9ca6-4afff222a90d">

**Comment by Axel32019** [comment]
fixed #1005
