### ISSUE TITLE
A writen is not clearly legible and overlaps the buttons

### ISSUE THREAD

**Issue by Markus33-ITA** [Stephan-S/FS22_AutoDrive#86]
Hi. is it possible to request an improvement for the code linked to this variable (gui_ad_noUnloaderAvailable)?
The text goes under the messages and if you could also change color. Thank you

[https://i.imgur.com/ziCbIay.png](https://i.imgur.com/ziCbIay.png)

I don't know if it's on the improvements list and if so, I apologize if I've opened a topic.

**Comment by Stephan-S** [comment]
Hey, for now I would suggest that we generate translations that fit into the line. I don't want to adjust the font size based on the language for now :-)
