### ISSUE TITLE
Bitte erhöhen Sie die Anzahl der Flüge, um die Lieferpunkte zu ändern.

### ISSUE THREAD

**Issue by goldorel** [Stephan-S/FS22_AutoDrive#860]
Hallo, mir hat die neue Funktion gefallen, die Anzahl der Flüge einzustellen, wenn Sie Lieferpunkte ändern auswählen, aber Sie könnten die Anzahl der Flüge nicht auf 100 erhöhen, weil manchmal 9 Flüge knapp sind, zum Beispiel wenn 15 Produktionsstellen jeweils 30.000 Liter benötigen und der Tank 6000 Liter transportieren soll, dann reichen 9 Flüge nicht aus, und wenn es bis zu 100 Flüge gibt, können Sie berechnen, wie viele Flüge Sie benötigen, und eine unendliche Anzahl ist nicht bequem, weil es unendlich fahren wird und es nicht bequem ist ? Die Anzahl der Liter habe ich ungefähr geschrieben, um die Situation zu erklären. Vielen Dank im Voraus für Ihr Verständnis und Ihre Hilfe und ich hoffe sehr, dass Sie mir bitte gefallen und die Anzahl der Flüge auf 100 einstellen werden.

**Comment by Iwan1803** [comment]
Sounds like you used a translator. It's better to translate to english and then post it here. "Flüge" sounds like flying but it should be rounds, right? 😉

**Comment by goldorel** [comment]
Hi, I liked the new function of selecting the number of flights to change delivery, but could you increase the cycles to 100 flights, because sometimes 9 flights are not enough, for example, if there are 15 local points in the folder for greenhouses that require 30,000 liters of water for each, and the transport for transportation is designed for 6000 liters of water, then 9 flights will not be enough. I have written approximate figures to explain to you why it is necessary to increase. I really ask you to please increase to 100 flights when choosing a delivery service. Thank you very much in advance.

**Comment by goldorel** [comment]
I just used an online translator, please excuse me if something was translated into German wrong.

**Comment by Iwan1803** [comment]
Duplicate to #862 - closed this one here.
