### ISSUE TITLE
Fehler nach Update auf neue Version bei Fahrsilo

### ISSUE THREAD

**Issue by Launebaer1981** [Stephan-S/FS22_AutoDrive#861]
Hallo zusammen, ich habe gestern auf die Version 2.0.1.0 aktualisiert. Gestern habe ich mit der vorherigen angefangen ein Fahrsilo zu befüllen und das ging bis dahin wie immer noch super, heute nach der Aktualisierung leider nicht mehr. Der fährt durch das Silo und läd wie gewohn ab, am Ende bleibt er aber nun nicht mehr stehen und lässt in ruhe den Schubboden zurückfahren, sondern fährt währenddessen einfach geradeaus weiter ohne auf die Fahrlinie zu achten. Erst wenn der Schubboden zurückgefahren ist, sucht er den nächsten Wegpunkt und fährt dann darauf weiter wenn er sich nicht woanders schon verfangen hat.

https://youtu.be/zdiw64e2AK0

**Comment by Axel32019** [comment]
Ist bekannt und gefixed, kommt im nächsten Release: https://github.com/Stephan-S/FS22_AutoDrive/commit/46c18b98304d34463cccf0a2cf0c59ad3d08f002

**Comment by Axel32019** [comment]
fixed Release 2.0.1.2
