### ISSUE TITLE
Please add 100 rounds for the change delivery function.

### ISSUE THREAD

**Issue by goldorel** [Stephan-S/FS22_AutoDrive#862]
Hi, I'm sorry that I created a new topic, it was just in German, and now I wrote in English, I'm sorry that the online translator did not translate correctly. I really liked the new function of selecting the number of flights to change delivery, but could you increase the cycles to 100 flights, because sometimes 9 flights are not enough, for example, if there are 15 local points in the folder for greenhouses that need 30,000 liters of water for each, and the transport for transportation is designed for 6000 liters of water, then 9 flights will not be enough. I have written approximate figures to explain to you why it is necessary to increase. And endless cycles can be very inconvenient, because he will ride endlessly until you stop him yourself. I really ask you to please increase the number of flights to 100 when choosing the change delivery function. Thank you very much in advance.

**Comment by hermannbrauer** [comment]
Einmal hier zum Verständnis, mit Flights sind Runden gemeint.

Der tread Ersteller möchte erreichen das die Rundenzahl von 1-9 bzw unendlich auf 1 - 100 bzw unendlich gesetzt wird.

Für den Fall das aus dem Text nicht klar genug heraus gestellt wird worum es geht.

**Comment by goldorel** [comment]
> Einmal hier zum Verständnis, mit Flights sind Runden gemeint.
> 
> Der tread Ersteller möchte erreichen das die Rundenzahl von 1-9 bzw unendlich auf 1 - 100 bzw unendlich gesetzt wird.
> 
> Für den Fall das aus dem Text nicht klar genug heraus gestellt wird worum es geht.

Yes, you got it right.

**Comment by goldorel** [comment]
Thank you so much for your help.

**Comment by Axel32019** [comment]
implemented with #1000
