### ISSUE TITLE
Abladestellen Erlengrat als Hindernis erkannt

### ISSUE THREAD

**Issue by LS22Farmer2022** [Stephan-S/FS22_AutoDrive#863]
Moin,
ich bin ein großer Fan von AutoDrive und benutze es (in Kombination mit Courseplay) auf der Erlengrat-Map.
Dabei ist mir aufgefallen, dass AD an einigen Verkaufsstellen, wie z.B. bei der Schreinerei die Holz-Abladestelle oder beim Viehhändler die Abladestelle für Silage, als Hindernis erkannt wird.
Das Phänomen konnte ich auch bei anderen Verkaufsstellen, z.B. Mods, reproduzieren. Ein Verändern der Kollisionshöhe, -erkennung oder das Wechseln des Fahrzeuges sowie ein anderes Heranfahren lösen das Problem nicht. Ebenso habe ich mit dem Object-Hider den kompletten Viehhändler ausgeblendet - AD bleibt aber trotzdem noch mit einer Kollision stehen.

![fsScreen_2023_03_19_11_46_42](https://user-images.githubusercontent.com/128291263/226170324-8f00be12-caf0-4b19-898c-57b655e9d48d.png)

Woran könnt das liegen?

Herzliche Grüße und vielen Dank für diesen super Mod :-)

**Comment by Axel32019** [comment]
Hallo,
Giants verteilt Kollisions-Bits in ihren eigenen Sachen ohne S... und V....!
Hier ist bit 11: "TREE: A tree" gesetzt, ich kann jedoch in dem Trigger keinen Baum erkennen.
Lass gerne ein Dankeschön bei Giants für diesen M..... - k... mich mittlerweile dermaßen an.
Da hilft nur auf FS19 Kollision umzuschalten: Einstellungen - Autodrive -> Kollisionserkennung -> FS19

**Comment by 112TEC-Chris** [comment]
das gleiche passiert auch auf der silverrun Forest. Und bezüglich den Bits 11: das wird gebraucht für die Transportmissionen von Holzstämmen. Da ist schon Sinn und Verstand. Ich lass Dir gerne ne Dankeschön da für das "wontfix"

**Comment by Axel32019** [comment]
@112TEC-Chris Hast Du ohne bit 11 getested oder worauf basiert Deine Erkenntnis?
