### ISSUE TITLE
AD stops front to the new trigger patch 1.9

### ISSUE THREAD

**Issue by Vanquish081** [Stephan-S/FS22_AutoDrive#864]
AD stops front to the new trigger created for new stores in patch 1.9, this new triggers use 12, 20 and 21 bits unlike loading/unloading triggers in silos that use bit 30.

![fsScreen_2023_03_19_12_11_32](https://user-images.githubusercontent.com/12070061/226174604-1099a294-389a-4be1-bba7-40847814b874.jpg)

![bits_triggers](https://user-images.githubusercontent.com/12070061/226174651-fc9aa306-75e6-41ef-8993-577cf182c0ed.png)

**Comment by Axel32019** [comment]
Greatings from Giants!!!
Do you see a DYNAMIC_OBJECT, i.e. bigbag, palett etc., there?
Remove the DYNAMIC_OBJECT bit and it will be no issue.

**Comment by Vanquish081** [comment]
> Greatings from Giants!!! Do you see a DYNAMIC_OBJECT, i.e. bigbag, palett etc., there? Remove the DYNAMIC_OBJECT bit and it will be no issue.

There is nothing... there is the trigger of an objectStorage
