### ISSUE TITLE
Input Action Conflict prevents toggle cover of Benalu Optiliner

### ISSUE THREAD

**Issue by tn4799** [Stephan-S/FS22_AutoDrive#867]
**Whats the Problem?**
When using AD and the Benalu Optiliner AD blocks the input action of the Trailer to toggle the cover. The keybinding of this trailer to toggle the cover is `InputAction.IMPLEMENT_EXTRA4` because the key for `InputAction.TOGGLE_COVER` is already blocked by the cylindered part for the lift axis. 

**Potential Cause**
I did some tests myself with a own script to log which code section in the source code of the farming simulator is executed. The conclusion of this observation is that the registration of the input action `IMPLEMENT_EXTRA4` is blocked by the input action `ADToggleHud`. I've attached a log file with my logging data to provide this data aswell. I've also uploaded my inputBindings.xml to prove that I didn't assign any conflicting keybindings myself.

**Why am I sure that AutoDrive causes the problem?**
The problem only occurs when AutoDrive is active. Once I deactivate AutoDrive the cover opens just as expected.

**Reproducability**
Always when AutoDrive and the Benalu Optiliner are both active with standard keybindings.

**Related Mods**
[Benalu Optiliner](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=227541&title=fs2022)
Autodrive (latest Release)

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11033064/log.txt)
[inputBinding.xml](https://drive.google.com/file/d/1DpfHhgf-Vc14vXsGU4JhE6DgqlGzJRQF/view?usp=sharing)

**Comment by Axel32019** [comment]
No issue from AD observed:
mod folder only with:
Available mod: (Hash: b4dc7fb5c54e9165b9aec02f268e5862) (Version: 2.0.1.0) FS22_AutoDrive
Available mod: (Hash: 3e57605241ce31ed92735af9191264d0) (Version: 1.0.0.0) FS22_BenaluOptiliner
deleted inputBinding.xml
start game
trailer cover working OK with key 'Y'
statement 'standard keybindings', see your inputBinding.xml ???

**Comment by tn4799** [comment]
> statement 'standard keybindings', see your inputBinding.xml ???

I refered to the key bindings of FrontLoaderArm, Implement Extra 4 and all AD keybindings.
Those where never changed.
And as you can see in my log the key binding conflict was related to AD. But I cannot explain why this happens. 
When I delete the inputBindings, the problem disappears as you mentioned. So yes, not a 100% AD issue. But maybe you have an Idea what could cause the behaviour described above. If you don't want to bother and close this issue, im also fine with it.

**Comment by Axel32019** [comment]
I could only guess what cause this log entry, might be a mod / script register an action with key binding ALT 0 as well.
Why the trailer need a frontloader to control?
2023-03-21 20:59 event collision
2023-03-21 20:59 colliding action: [AXIS_FRONTLOADER_ARM: categories= 3, axisType=FULL, isLocked=false]
2023-03-21 20:59 Vehicle: Optiliner 133
2023-03-21 20:59 state: false
2023-03-21 20:59 event collision
2023-03-21 20:59 colliding action: [ADToggleHud: categories= 3, axisType=HALF, isLocked=false]
2023-03-21 20:59 Vehicle: Optiliner 133
2023-03-21 20:59 state: false
Could be a hint...

**Comment by tn4799** [comment]
The log entry you mentioned is from a script ive written to insert some debug prints inside the code of giants. They have no influence on the behaviour.

The trailer uses the frontloader arm-axis to allow one wheel row to be lifted. This is done by frontloader arm, with also uses the n-key. Thats the reason for why the trailer uses y instead of n to toggle the cover.

**Comment by Axel32019** [comment]
Still I do not see an issue caused by AD.
