### ISSUE TITLE
Fehlermeldung in der Log

### ISSUE THREAD

**Issue by scorpion3010** [Stephan-S/FS22_AutoDrive#868]
Hallo,

C:/Users/xxxx/Documents/MyGames/FarmingSimulator2022/mods/FS22_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:714: attempt to index field 'attacherJoint' (a nil value)
2023-03-22 09:20 Error: Running LUA method 'update'.

Dieser Fehler steht am Ende meiner Log, und zwar in ständiger Wiederholung (ungefähr 3000! Mal in zwei Minuten).
Dadurch bleibt mir nur das Spiel zu beenden und neu zu starten.

Was kann ich machen?

LG
scorpion3010

**Comment by regs1980** [comment]
Erst mal das Lesen https://github.com/Stephan-S/FS22_AutoDrive/issues/1 und dann noch mal die fehlenden Sachen nachliefern.

**Comment by Axel32019** [comment]
wie #808
