### ISSUE TITLE
AutoDrive HUD settings not saved for host on local Multiplayer

### ISSUE THREAD

**Issue by mpupedis** [Stephan-S/FS22_AutoDrive#869]
This appears to be related to the fix implemented for #765 in 2.0.1.0.

As the host for a local multiplayer (not dedicated server), my AutoDrive HUD settings (open/closed, position, wide, etc) are not saved between sessions.  There are also other settings (corner speed, show next path, etc) that are not saved, and ignore the "Make Default" option.

The HUD visibility and settings are not affected for any client connecting to the session, just the host.

**Comment by Axel32019** [comment]
Add: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml

**Comment by mpupedis** [comment]
[log1.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11054638/log1.txt)
From the original start/setup of a new save

[log2.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11054642/log2.txt)
Relaunching the save after exiting

[AutoDrive_config.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11054668/AutoDrive_config.txt)

[AutoDriveUsersData.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11054666/AutoDriveUsersData.txt)

**Comment by Axel32019** [comment]
Please try this:
[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/11065935/FS22_AutoDrive.zip)

**Comment by mpupedis** [comment]
An entry was created in the UserData file, but the HUD settings were not loaded when I relaunched the game.  I noticed that the UniqueID stored in the UserData file is different from the one in the players.xml.

[log1.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11066671/log1.txt)
First launch with new version.

[log2.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11066673/log2.txt)
Second launch with new version.

[AutoDrive_config.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11066679/AutoDrive_config.txt)
[AutoDriveUsersData.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11066685/AutoDriveUsersData.txt)
[players.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11066686/players.txt)

**Comment by Axel32019** [comment]
The UniqueID is not yet available in time the user data is loaded, thats why it is SinglePlayer.
But I missed something to change, this one should work now (hopeful):
[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/11067052/FS22_AutoDrive.zip)

**Comment by mpupedis** [comment]
That one works.  Everything is saved and recalled as before.

Thank you for the quick turn around.
