### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS22_AutoDrive#87]
Hallo,

wollte mit einem Freund gerade einen Multiplayer starten, jedoch hängt sein Spiel beim laden bei 99%...

Irgendwelche Ideen was da schuld sein kann?

log von mir:
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7770947/log.txt)

log von ihm:
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/7770948/log.txt)

Danke
Eric

**Comment by Stephan-S** [comment]
Hi, falls du einen Kurs nutzt, der Auto generiert wurde von AD, dann probiere es bitte mal mit einer neuen AutoDrive Config.
Dort gab es einen Bug in der Generierung der leider zu Problemen im Kurs führt, die dann beim Syncen im MP erst auftauchen

**Comment by eric4072** [comment]
hat geklappt, danke 👍😁
