### ISSUE TITLE
[Suggestion] AD interact with PDA

### ISSUE THREAD

**Issue by k4r3l01** [Stephan-S/FS22_AutoDrive#871]
Hello please its will be possible to make AD work like ingame helper?
i mean i set point on map and AD drive to marked destination 
Thanks in advance for any answer

**Comment by k4r3l01** [comment]
thanks for your answer but i mean drive to destination where is no marker created by AD
i need this for creating courses on big maps

**Comment by Axel32019** [comment]
Do I understand correct? AD should drive to a point on a map where no AD-network exist?

**Comment by k4r3l01** [comment]
nope i mean set point on pda where driver go like helper in fs but on this location must exist AD network but without marker

**Comment by Axel32019** [comment]
From my perspective a huge effort for small problem which could be solved easy:
Just add more destinations while create a network and delete at end which are no longer needed.

**Comment by mpupedis** [comment]
The AutoDrive Course Editor (https://github.com/KillBait/AutoDrive_Course_Editor) can be used to modify the Route Manager config files, allowing extra destinations to be created and loaded into the game on the fly.  Modify the Route Manager config file in the AutoDrive Editor, then re-load the Route in game.  Presto!

**Comment by k4r3l01** [comment]
@mpupedis thanks but how to reload route manager config ingame or i must reload game when i make any change in Course editor?

**Comment by mpupedis** [comment]
@k4r3l01 

Using the "Disk" icon when in modify mode.
![image](https://user-images.githubusercontent.com/128707955/227948137-d8f54d79-b7aa-4013-871e-7777bcc091b7.png)

The Route Manager can load changes in real-time, without relaunching the game.
![image](https://user-images.githubusercontent.com/128707955/227948278-ee551048-0ad8-4b2e-a783-5fa1d9c7bc03.png)

In the AutoDrive Editor, just use the Routes menu.  I use Load Routes Manager Config to bring up a select list of the stored routes.  Once you make a change (add waypoints, destination labels, etc), you can save the Route in the editor, then Load the Route in game, and the changes will be present immediately.
![image](https://user-images.githubusercontent.com/128707955/227948393-c2ec5ac5-8e96-42db-8ddd-1378113d2f2e.png)

The changes will not be saved to the save file data until you save your game the next time, but they can always be reloaded through the Route Manager.  I have been using the process to build out my own AutoDrive routes.
