### ISSUE TITLE
Trecker Kippt in kurven um 

### ISSUE THREAD

**Issue by Panzerknacker1337** [Stephan-S/FS22_AutoDrive#875]
Moin Stephan, 
ich habe auf Meiner Map Bein Mais Häckseln Beobachtet Das wenn Ein Voll Beladener Abfahrer vom Feld Zur Werkstatt Oder tanke Fährt die kurven Geschwindigkeit deutlich über scheitet Meistens habe ich ihn gesehenen wie er zwischen 30-40 Km/h gefahren ist und wegen REA in der kurve um gekippt ist Ohne REA passiert dies nicht aber Normaler weise wird der Abfahrer vor einer kurve langsamer. Übrigens ich habe die Kurvengeschwindigkeit auf 50% Und wenn der Abfahrer Normal zwischen Feld und Haufen Pendelt Bremst er ja auch Währe cool Wenn du das Fixen kannst weil auf der Marsch sind die Felder groß und die Wege weit, Ach ja Dass passiert nur mit REA wenn er zur Werkstatt/Tanke Fährt also an REA liegts nicht.

**Comment by regs1980** [comment]
Passiert das mit dem REA22 Center Of Gravity https://www.farming-simulator.com/mod.php?lang=de&country=be&mod_id=227389&title=fs2022?

**Comment by Panzerknacker1337** [comment]
Weiß ich Jetzt Nicht aber, man merkt auf jeden fall das die Helfer vor einer kurve, wenn sie zu Werkstatt fahren nicht bremsen. Wen du willst komm ich Gerne in Deinen oder meinen DC und erläutere dir das Problem genauer  Danke Für Deine Antwort  Von: regs1980Gesendet: Samstag, 1. April 2023 00:14An: Stephan-S/FS22_AutoDriveCc: Panzerknacker1337; AuthorBetreff: Re: [Stephan-S/FS22_AutoDrive] Trecker Kippt in kurven um (Issue #875) Passiert das mit dem REA22 Center Of Gravity https://www.farming-simulator.com/mod.php?lang=de&country=be&mod_id=227389&title=fs2022?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by regs1980** [comment]
Die Antwort auf meine Frage ist doch sehr einfach, ja oder nein.

**Comment by Panzerknacker1337** [comment]
Ja  Gesendet von Mail für Windows Von: regs1980Gesendet: Samstag, 1. April 2023 13:38An: Stephan-S/FS22_AutoDriveCc: Panzerknacker1337; AuthorBetreff: Re: [Stephan-S/FS22_AutoDrive] Trecker Kippt in kurven um (Issue #875) Die Antwort auf meine Frage ist doch sehr einfach, ja oder nein.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by regs1980** [comment]
> Ohne REA passiert dies nicht aber Normaler weise wird der Abfahrer vor einer kurve langsamer.

Deine Kurven müssen eckiger werden, 
von dem 
<img width="310" alt="2023-04-02 22_49_50-Greenshot" src="https://user-images.githubusercontent.com/13314443/229378544-a567229a-1c7c-4bf9-9ace-9cff5d840259.png">
zu dem
<img width="608" alt="2023-04-02 22_51_00-Greenshot" src="https://user-images.githubusercontent.com/13314443/229378549-73bec40d-a9ba-4cae-bbf9-b5be19eb8a6d.png">
so das AD dieses Fahrzeug verlangsamt oder per HUD die Geschwindigkeit heruntersetzen.
Du schreibst ja selber ohne den REA22 Center Of Gravity Mod passiert es nicht, was soll deiner Meinung nach jetzt gefixt werden, Kurvengeschwindigkeit noch weiter heruntersetzen oder wie wäre dein Vorschlag.

**Comment by Axel32019** [comment]
Die Einstellung der Kuvengeschindigkeit wird bei allen Fahrten berücksichtigt, es spielt keine Rolle in welchem Modus was / wohin gefahren wird! Sehe hier keinen Bug in AD.
