### ISSUE TITLE
[suggestion] Home button

### ISSUE THREAD

**Issue by glowpipe** [Stephan-S/FS22_AutoDrive#876]
Been using Autodrive a lot lately, and while not needed, i think a home button on the main Autodrive window would be nice to have

So you set a "home" waypoint, and when you clicked this button it would drive to that waypoint, it would just be a quality of life change to have a easier way to get back to your farm rather than opening the drop down list with all the waypoints. Now obviously this is not super hard to do (choosing the waypoint that is), but there a few scenarios where i can see this to be a little helpful and just a bit quicker way to get home. I am currently playing with a route-system someone made and it got quite a few waypoints, so a "go home" function would make that a bit easier/quicker

I don't know if this is even possible however, as i know litteraly nothing about coding

**Comment by S-eler** [comment]
You know about "parking" option, and dedicated button to send current vehicle to assigned parking spot?
