### ISSUE TITLE
Spanngurte etwas zu schnell beim spannen

### ISSUE THREAD

**Issue by andreasthu** [Stephan-S/FS22_AutoDrive#878]
Hallo Leute
ich lade gerne verchiedene Paletten auf denselben Anhänger.
wenn diese Paletten unterschiedliche Höhe haben, kommt es manchmal vor, das die neuen Paletten dann etwas zu hochgeladen werden.
bevor sie jedoch auf den Boden fallen können schnappt sie der Spanngurt und hält sie schwebend:
![fsScreen_2023_04_06_13_11_03](https://user-images.githubusercontent.com/24860501/230390124-90fcafcc-6482-4a7b-904b-979fa1022d39.png)
![fsScreen_2023_04_06_13_10_56](https://user-images.githubusercontent.com/24860501/230390159-8e423fc4-833e-4765-927e-20f3a9618267.png)
![fsScreen_2023_04_06_13_11_12](https://user-images.githubusercontent.com/24860501/230390176-abdfdbbc-9e30-47c5-aef0-0f03510fd2b1.png)

könnte man den automatischen Spanngurt etwas verzögert aktivieren?
alternative ist entweder der manuelle Spanngurt, oder den automatischen Spanngurt wieder lösen und neu spannen.
lg
andreas

**Comment by regs1980** [comment]
> automatischen Spanngurt

Das wäre mir neu das AD automatisch Spanngute anlegt ohne den Paletten [Autoloader Spezialisierung Mod](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=228819&title=fs2022)

**Comment by Axel32019** [comment]
@regs1980 Die AD-Implementierung für UAL liegt Loki seit 4 Wochen vor - bitte bei ihm nachfragen!

**Comment by andreasthu** [comment]
OH
achja sorry.
hab das wohl ins falsche forum geschrieben.
autodrive ist ja nicht zuständig fürs verladen.
*verschämt im Boden versink*
lg
andreas

**Comment by Axel32019** [comment]
@andreasthu Darf geschlossen werden, oder?

**Comment by regs1980** [comment]
> @regs1980 Die AD-Implementierung für UAL liegt Loki seit 4 Wochen vor - bitte bei ihm nachfragen!

Er meint, er hat dir was geschickt und die Version ist raus .
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.1.8

**Comment by andreasthu** [comment]
Ja sorry, kann man schliessen
