### ISSUE TITLE
A way for an auger wagon to leave its unloading position without completely emptying?

### ISSUE THREAD

**Issue by evenmorestupiderhats** [Stephan-S/FS22_AutoDrive#881]
Harvesting is getting stalled when my auger wagon doesn't get to 0% empty.  It can cause a deadlock when a vehicle with multiple trailers/multiple bins in a single trailer receiving the grain from the auger wagon arrives after the auger wagon arrives at its unload position and only fills its first trailer and fails to move forward.

Could there be a way to set up a time limit for auger wagons to remain at their unload position if they are not at 100% full?  If they are at 100% full there should be no reason for the auger wagon to leave its unloading position.  If unloading stalls, the auger wagon could leave the unload position and return to the field position.  That should resolve the deadlock by allowing the auger wagon to approach the unload position again and fill all the trailers of the vehicle waiting to receive grain.

**Comment by rohne83** [comment]
Issue is the same as for #475 and #535 , just that you want it to be fixed by timelimit instead of more appropriate fill level

**Comment by Axel32019** [comment]
Same as mentioned before -> closed
