### ISSUE TITLE
Gülle Zubringer

### ISSUE THREAD

**Issue by Porter76** [Stephan-S/FS22_AutoDrive#882]
Hallo. Wie sieht es mit einer Erweiterung für den AD-Gülle-Zubringer aus? Wenn der Güllefahrer beim AD-Gülle-Zubringer aufgetankt hat ( jedoch weniger Volumen als der Zubringer besitzt) und weiter arbeitet, bleibt der AD-Gülle-Zubringer stehen weil er noch nicht leer ist. Es wäre sehr hilfreich wenn dieser dann direkt wieder los fährt um neue Gülle zu holen.

**Comment by rohne83** [comment]
Kann zu. Genau zu dem Thema gibts doch schon zwei Issues zu: #475 und #535
Ob ULW oder Güllezubringer oder was auch immer, das Verhalten ist immer das gleiche
