### ISSUE TITLE
Punkt für automatisches Tanken vorgeben

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS22_AutoDrive#883]
Hallo zusammen,

wie wäre es mit der Idee, wenn der  "automatisch tanken" Punkt aktiviert ist, in den Einstellungen einen fest vorgegebenen Tankpunkt eintragen zu können.

So dass die Maschine nicht an jeder beliebigen Stelle tankt, wo er mit den Anbaugeräten vielleicht auch gar nicht reinkommt.
Anfahrpunkt einer Hoftankstelle mit evtl. selbst hergestelltem Diesel ist da eine bessere Lösung.

Viele grüße

Marc

**Comment by 60erjonny** [comment]
...ich habe alle Punkte gelöscht, wo das tanken nicht so gut möglich ist und nur den "einen Punkt " zum tanken belassen und gut ist bei mir...klar wäre eine solche Möglichkeit zum einstellen wohl ergänzend gut, dann müssten die AD-Pnkte verschiedene Priortäten besitzen...aber ich bin nur AD-Benutzer...

**Comment by Kitekater** [comment]
Naja Priorität nicht wirklich. In den Einstellungen einen Punkt festlegen und gut. Ganz elegant wäre es natürlich wie beim Parken. Neben den P Symbol ein T Symbol, wo ich den Standpunkt hinterlege. Den nimmt er dann fürs automatische Tanken her.
Guter Nebeneffekt, man kann ihn mit dieser Taste auch zum manuell tanken schicken

**Comment by 60erjonny** [comment]
...nun ja der Nachteil, ich müsste für jedes Fahrzeug seinen Tankpunkt festlegen, was ich aber jetzt nicht muss...und für das tanken schicken kann man in den Tastatureinstellungen, eine Tastenkombi festlegen...

**Comment by Kitekater** [comment]
Ein globaler eingerichteter Punkt würde ja reichen.
Evtl pro Fahrzeug übeschreibbar falls auf Nebenhof geparkt mit eigener Tankstelle

**Comment by 60erjonny** [comment]
Zitat: Ein globaler eingerichteter Punkt würde ja reichen.
Nun ja, so in der Art, habe ich es ja auch gelöst...:-)
Aber egal warten wir ab, welche Antwort du von den "Machern" hier bekommst...trotzdem noch viel Spass mit AD...:-)

**Comment by S-eler** [comment]
I guess we approach the same problem, Finally, i solved my problem by editing rafinnery mod, to delete fueling point from it, becouse my harvester also was graviting into it, instead my normal underground fuel tank ;).

**Comment by 60erjonny** [comment]
@S-eler In principle, it always depends on how realistic you want to play ... and with every adaptation, If you deviate from it ...

**Comment by S-eler** [comment]
I really want to play realistic, but still there is no option for auto-refilling on field, and with really, really large fields, (like my sunflower field, 1/3 size of NML map ;)) i need to keep everything as smooth as possible - i even build underground tank, and create AD routes so combine with 12m header is able to auto-refuel, auto-repair, and park after job finished

**Comment by Axel32019** [comment]
Hallo zusammen,
Die Vergabe eines Punktes zum Tanken per Einstellung(en) würde die Handhabung von AD noch komplizierter machen.
Wie @60erjonny schon ausgeführt hat, kann man die Tank-Stellen per Zielpunkt vergeben oder eben auch nicht.
Momentan sehe ich daher keine Notwendigkeit daran etwas zu ändern.

**Comment by Axel32019** [comment]
> I really want to play realistic, but still there is no option for auto-refilling on field, and with really, really large fields, (like my sunflower field, 1/3 size of NML map ;)) i need to keep everything as smooth as possible - i even build underground tank, and create AD routes so combine with 12m header is able to auto-refuel, auto-repair, and park after job finished

"I really want to play realistic" - How realistic is it to drive a harvester with 12m header from field to fuel station and back?
At least for Europe I would state it is impossible. But you managed it for NML - fine.
