### ISSUE TITLE
Abfahrer stoppt und fährt zurück ab fliegendes Abbunkern

### ISSUE THREAD

**Issue by 0scarZulu** [Stephan-S/FS22_AutoDrive#885]
Hallo :) 

mir ist aufgefallen das wenn ich selber Drescher oder auch Cp und fliegend abgebunktert werden soll der AD Abfahrer an den Drescher heranfährt, 50m dahinter stehen bleibt, zurückfährt und dann wieder weiter fährt und unter Rohr. Also er hat quasi keine flüssige Anfahrt vom Rufen bis zum Abbunkern. Kann das Irgendwie geifxt werden? Es kommt schon vor das selbst wenn ich bei 70% das ROhr ausfahre der AD Abfahrer es seltens pünktlich schafft unters rohr zu fahren sodass man stehen bleiben muss.. 

Cheers

**Comment by Axel32019** [comment]
Hallo,
Bitte mal folgende Dateien log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml und ein paar Screenshots der Situation einfügen.
