### ISSUE TITLE
Bergmann RRW fährt nicht im beladenen Zustand

### ISSUE THREAD

**Issue by Lorsch1409** [Stephan-S/FS22_AutoDrive#886]
Moin,
ich möchte den Bergman RRW (den ÜLW für Zuckerrüben) im beladenen Zustand von A nach B senden. Ich kann weder "Fahre zum Zielpunkt" noch "Beladen/Abladen" nutzen. Ich bin nicht sicher, ob es ein generelles Thema der ÜLW ist oder erst seit dem die Geräte zwingend eingeklappt werden, bevor der Abfahrer losfährt.

Any Idea?

LG Jens

![image](https://user-images.githubusercontent.com/131489033/233723459-325dc878-70af-48f3-b474-19e9a65896cf.png)

**Comment by Axel32019** [comment]
Moin,
Bitte folgende Dateien einfügen: log.txt, AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml

**Comment by Lorsch1409** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11303382/log.txt)

Bei den XML Dateien sagt mir github: "We don't support that file type" Soll ich die zuvor in txt umwandeln?

**Comment by Lorsch1409** [comment]
[AutoDriveUsersData.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11303410/AutoDriveUsersData.txt)
[vehicles.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11303411/vehicles.txt)
[AutoDrive_config.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11303412/AutoDrive_config.txt)

Hab mal alle 3 Dateien als TXT gespeichert. Sollte es einen anderen (für euch einfacheren Weg geben, gerne Bescheid sagen.

**Comment by Lorsch1409** [comment]
Ich Depp. Ursache gefunden. Ich hatte "Fold Implements" auf Ja. Sorry, dass ich es nicht gleich gesehen habe. Es war tatsächlich erst ein Gedankenblitz nachdem ich die Dateien hochgeladen hatte.
