### ISSUE TITLE
Cycling through destinations

### ISSUE THREAD

**Issue by PaulNicholson62** [Stephan-S/FS22_AutoDrive#889]
After a trigger point, autodrive cycles through to a different destinations. The cycling option is set to 'none'. I'm using folders but no matter what settings I change, it still does it.
On a collection and delivery route, the vehicle does a drop, destination is set but after a few seconds it changes to something different. It  changes both fields.

**Comment by Iwan1803** [comment]
Is the trailer in front of the target blue? If yes, AD will drive to the best target for buying or selling something.
If you click on the trailer, you can change it back to white and the target will not be changed anymore.
