### ISSUE TITLE
Fahrzeug fährt zum Tanken oder zur Werkstatt Problem

### ISSUE THREAD

**Issue by 19Flow89** [Stephan-S/FS22_AutoDrive#890]
Huhu,

mir ist eben aufgefallen das Fahrzeuge die zur Werkstatt fahren oder zum Tanken fahren keine Doppelfahrspuren beachten oder von anderen beachtet werden. Der "normal" Fahrende stand dann frontal an einer Doppel befahrbaren vor dem "zum Tanken" oder "zur Werkstatt" fahrendem Fahrzeug. Was im normal Fahrbetrieb nicht passiert da warten sie anständig und der Fahrer der zum Tanken oder zur Werkstatt fährt hat einen ganz schönen Bleifuß und kennt gefühlt kaum eine Bremse.
Falls es das hier schon irgendwo gibt bitte Schließen ( Version die neuste von Axel ).

**Comment by Axel32019** [comment]
Moin, es gibt keinen Unterschied wie/was/wohin/wieso... gefahren wird. 
Bitte mit normalen Fahren zu Ziel prüfen ob das am Streckennetz liegt.
