### ISSUE TITLE
Ad Abfahrer bleibt kurz vor Ziel stehen

### ISSUE THREAD

**Issue by wisc85** [Stephan-S/FS22_AutoDrive#895]
Hallo,
Ich habe das Problem das mein Ad Fahrer neuerdings immer kurz vorm Abladepunkt (nur da wo sich Tore zum Gelände des Verkaufspunktes befinden) ein paar Meter vor dem Tor stehen bleibt und dann nicht weiter kommt. Das macht er bei allen Fahrten egal ob ich ein Fahrzeug nur zum Shop schicke oder ob es der Abfahrer ist der immer wieder zwischen Feld und Verkaufspunkt hin und her fährt. Bis vor ein paar Tagen hat das alles noch ohne Probleme funktioniert aber jetzt leider nicht mehr. Ich hab meines Wissens auch nix an den Einstellungen geändert.
Vllt kann mir hier ja geholfen werden?

Gruß Willi

**Comment by Axel32019** [comment]
Hallo @wisc85 , Kollisionserkennung auf FS19 eingestellt? Wenn nicht dies probieren.

**Comment by wisc85** [comment]
Hallo. Danke für die schnelle Antwort. Es scheint jetzt zu funktionieren. Komisch, es hat mit Kollisionserkennung auf FS22 eine ganze Weile geklappt und dann auf einmal nicht mehr...🤔
Naja, wie gesagt, jetzt scheint es zu funktionieren
