### ISSUE TITLE
Veröffentlichung Modhub

### ISSUE THREAD

**Issue by PhilippS1** [Stephan-S/FS22_AutoDrive#896]
Hallo zusammen,

aktuelle Spiele ich über NvidiaNow, hier kann ich mir alle meine Mods von Modhub holen. Leider halt kein Autodrive. Wäre es daher möglich Autodrive über Modhub zu veröffentlichen? 

Gruß

**Comment by Iwan1803** [comment]
Da Giants die Anforderungen für Veröffentlichungen im Ingame-modhub verschärft hat, werden wir neue Version nur noch hier auf github veröffentlichen.

**Comment by PhilippS1** [comment]
Das ist echt Schade, aber naja kann man nichts machen.
