### ISSUE TITLE
Stop an Ampelanlage

### ISSUE THREAD

**Issue by franky-bb** [Stephan-S/FS22_AutoDrive#899]
Hallo.
Besteht die Möglichkeit, beim nächsten Update, den Stop bei Rot an der Ampelanlage einzubauen. Das wäre richtig toll. Das bringt dann deutlich mehr Ordnung in den Straßenverkehr.

Hier der Link zur Ampelanlage:
[Ampelanlage](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=261657&title=fs2022)

**Comment by Iwan1803** [comment]
Aus den Release Notes zur letzten AD-Version 2.0.1.0:
- Ampelanlagen mit Kollision (AI_Blocking) werden erkannt

Sollte es bei dir nicht funktionieren, dann bitte die Kollisionserkennung auf "FS 19" einstellen. Wenn es dann immer noch nicht geht, hat der Mapper vielleicht eine veraltete Version von Achimobil seinem Ampelskript genutzt.

**Comment by franky-bb** [comment]
Danke für die Antwort. In den AD Einstellungen war auf 'keine Kollision' gestellt. Wenn ich das auf Ls19 ändere, fährt AD keinen Meter. Das selbe wenn ich auf Ls22 stelle. Nur wenn die Kollisionserkennung auf 'aus' stelle, fahren die Fahrzeuge. (AD v2.0.1.0)
Was mache ich falsch.

**Comment by Iwan1803** [comment]
Und nun sollen wir raten, auf welcher Map und mit welchen Fahrzeugen das passiert oder wie sollen wir dem Problem auf die Schliche kommen?

**Comment by franky-bb** [comment]
Es funktioniert. Ich habe die Einstellung im AD gefunden, die für den Stillstand verantwortlich war. Die Einstellung 'Kollisionshöhe über Grund' war bei mir auf 0,25m eingestellt. Standard ist 2m. Ab 0,75m funktioniert es. Egal ob die Kollisionserkennung auf FS19 oder FS22 steht.

**Comment by Iwan1803** [comment]
0,75 oder 1,25m ist Standard wenn ich mich recht erinnere, aber schön, wenn das Problem gelöst ist 😉
