### ISSUE TITLE
Autodrive über Helfermenü steuern.

### ISSUE THREAD

**Issue by TheDukeOne** [Stephan-S/FS22_AutoDrive#9]
Hallo liebes Autodrive Team.
Erstmal ein großes Dankeschön an euch, für die schnelle und tolle Arbeit an Autodrive für den ls22.
Jetzt meine Frage: ist es möglich dass man die Fahrzeuge mit Autodrive, über das ingame Helfermenü steuern kann? So dass man praktisch nicht mehr in die Fahrzeuge einsteigen müsste.

**Comment by Stephan-S** [comment]
Maybe ;-)

**Comment by Iwan1803** [comment]
Da umgesetzt -> geschlossen ;)
