### ISSUE TITLE
AD Kollision - Fahrzeug stoppt vor Gebäude/Trigger

### ISSUE THREAD

**Issue by Kalibu1980** [Stephan-S/FS22_AutoDrive#900]
Hi, ich suche seit Tagen nach einer Lösung, kann aber keine finden.
Da ich hier im Forum auch nichts gefunden habe schreibe ich nun hier mein Anliegen.

Anliegen:
Wenn ich bei Fahrzeugen in den AD Einstellung die Kollisionserkennung (FS22, FS19) aktiviere beleiben alle Fahrzeuge vor einem Abladepunkt/Trigger stehen.  Ist es nur ein Trigger am boden um etwas abzukippen kann ich die Einstellung "Kollision über Grund" anheben (max. 4 Meter) und das Fahrzeug fährt drauf und läd ab. Ist es z.b. ein Abladepunkt mit Silos an den Seiten oder Gebäuden usw. bleibt das Fahrzeug stehen und fährt nicht auf den Abladepunkt. Schalte ich die Kolission in der AD Einstellung aus, klappt es, aber dann fährt der in jeden Baum oder Gebäude. 

Wenn ich bei  den besagten Silos/Abladestellen die Kollision per GIANTS EDITOR ausschalte, kann man plötzlich nichts mehr abladen.

Hat jemand eine Idee?
Kann man vielleicht die 4 Meter "Kollision über Grund" in einer Datei mittels editor erhöhen?

Ich hoffe ich habe es so erklärt das man es versteht.

Grüße

**Comment by Iwan1803** [comment]
Wenn die Kolli schon 4m über dem Boden ist, kannst du sie auch gleich abschalten, weil es einfach keinen Sinn macht.
Leider fehlen hier ein paar Infos, wie z.Bsp. auf welcher Map und mit was für Fahrzeugen...

**Comment by Kalibu1980** [comment]
Hi Iwan1803, danke für deine Antwort und Infos.

Da du noch weitere Infos wolltest hatte ich gedacht das ich dafür ein paar Tests mache. (andere Map, andere Mods usw.)
Und siehe da, ich konnte ermitteln das, dass Problem an einem Silo-ModPack liegt. (Mod)
Das ist nur nicht aufgefallen weil auf meiner ganzen Map, dieselben Trigger und Boden-Gitter usw. aus diesem Silo-ModPack, bei allen Gebäuden verbaut sind. Habe den Mod ermittelt, aus den Mod ordner genommen und alle Trigger durch andere ersetzt und nun funktioniert es. Ich hatte so viele Tests gemacht, aber bin nicht dahinter gekommen weil ja quasi alle Trigger auf der Karte das Problem hatten, (weil identische Trigger) es aber nichts mit der Karte zu tun hatte.

Das besagte Silo-Modpack lautet:
FS22_grainquidStorage (Getreide Und Flüssigkeitslager) von MISSYB Version 1.3

Vielen dank Iwan1803 für deinen direkten Denkanstoß, der dann zur Lösung beigetragen hat.

**Comment by Iwan1803** [comment]
Dann haben die Trigger wohl falsche Kollisions-Bits erhalten und das sollte man vielleicht dem Modder mal mitteilen ;)

**Comment by TobiHH78** [comment]
Darf ich hier noch die Frage anschließen, welche Bits korrekt sind?
Ich habe auch das Problem, dass die AD-Fahrer vor einigen Triggern die auf verschiedenen Maps verbaut sind stehen bleiben.
Bin nicht so der Experte was den GE angeht, mit etwas Hilfe würde ich es aber evtl. hinbekommen.

Vielen Dank!

**Comment by Kalibu1980** [comment]
@TobiHH78 dem schließe ich mich auch an und wäre dankbar wenn das mit den Kollisions Bits mal jemand erklären könnte.
Im netz habe ich leider nichts dazu gefunden.
