### ISSUE TITLE
AD only unloading front half of the Wilson Pacesetter trailer

### ISSUE THREAD

**Issue by n4396t** [Stephan-S/FS22_AutoDrive#901]
Hi, I'm using the latest version of AD on the Green Valley Nebraska map but I have checked it on other maps and it is the same.  I setup the AD Course to drive from the field where the grain cart unloads into the truck to numerous sell points but when the truck gets there it only unloads the front half of the trailer, it always returns to the field with the back half still at one hundred percent.  I feel almost sure this is a setting that I don't have set right.  Can someone direct me to which setting it might be?
Thanks 
Mark

**Comment by Axel32019** [comment]
no update -> closed
