### ISSUE TITLE
Old tractors can't back up trailers.

### ISSUE THREAD

**Issue by tsbertalan** [Stephan-S/FS22_AutoDrive#903]
If I

1. attach a  Claas Carat 1140 TD to the back of an old (not sure how to check just how many "years", but a lot) but fully repaired Rigitrac SKE 50 Electric, with a Agco 650 weight on the front
2. make a perfectly-straight forward and then backward course about 5 trailer-lengths long (green arrows, then blue)
3. name the waypoint at the end of the blue
4. and then have the Rigitrac try to pull, then push, the Claas Carat 1140 TD from the beginning of the green to that named end point,

it will jackknife every time.

If I try the same with a newly-purchased Rigitrac (with the same Agco 650 weight on the front and Claas trailer on the back), it backs up successfully.

This is on FS22 and AD git commit f82dc79b21456bfc62ce227409e82a67e2c378bd

Is this intended behavior? If I want to cheat it away, should I just go into my savegame and edit the tractors new again, or is there a better way?

**Comment by Iwan1803** [comment]
Try to reset the tractor, no need for cheats.

**Comment by tsbertalan** [comment]
Thanks; I ended up using [this script](https://github.com/tsbertalan/FarmAutomation/blob/main/everything_old_is_new_again.py).
