### ISSUE TITLE
Anhänger können nicht geladen werden

### ISSUE THREAD

**Issue by Hellsdriver** [Stephan-S/FS22_AutoDrive#904]
Hi,

wenn ich manuell mit einem Anhänger oder befüllbarem Anbaugerät an etwas heranfahre (Silo, Palette, etc) dann kann ich nicht laden. Ich muss das gerät erst abkuppeln und wieder ankuppeln. Wenn ich später das Fahrzeug verlasse, und wieder einsteige oder das Anbaugerät wechsel geht das Spiel von vorne los und ich kann nicht laden ohne am Silo, Palette, etc. das Anbaugerät ab- und wieder anzukuppeln.

Ich habe nur Autodrive Mod aktiviert und es tritt bei den Giantskarten und den Modkarten auf. Wenn ich Autodrive nicht aktiviere und ohne Mods oder mit anderen Mods spiele tritt das Problem nicht auf.

Es ist seit 2.0.0.7 und bei 2.0.1.0 ist es auch. Ich habe die neueste Version vom LS22.

**Comment by Iwan1803** [comment]
Poste mal bitte dein Log, wenn das Problem das nächste mal auftritt.

**Comment by Hellsdriver** [comment]
Hi Schon den Fehler gefunden?

**Comment by Axel32019** [comment]
Hi, Der mods-Ordner ist noch voll mit mods, nur deaktivieren reicht nicht, daher bitte folgendes machen:
- mods Ordner sichern / umbenennen
- neuen mods Ordner nur mit AutoDrive erstellen
- inputBinding.xml sichern / umbenennen
- inputBinding.xml löschen
- Spiel starten und Fehler nachstellen

**Comment by Hellsdriver** [comment]
Ich habe den Fehler versucht nachzustellen, aber es klappt nicht. Der Fehler taucht nicht mehr auf.

Habe Euch die Log nochmal angehängt.

[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11616825/log.txt)
