### ISSUE TITLE
Kein Streckennetz sichtbar 

### ISSUE THREAD

**Issue by OstseeTimo** [Stephan-S/FS22_AutoDrive#905]
Hallo liebe Leute, 
Ich habe seit 2 Tagen das Problem bei Autodrive das ich kein Streckennetz mehr sehen kann. Wenn ich eine Aufnahme starte höre ich das Punkte erstellt werden und ich kann auch Ziele darauf erstellen und jemanden fahren lassen. Aber ich sehe eben nicht wie die strecke eingefahren ist um zum Beispiel Punkte zu verbinden. Ich habe auch bereits Autodrive mehrmals neu Heruntergeladen und an Mods kann es auch nicht liegen weil ich auch einen Start nur mit Autodrive probiert habe. 
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11471476/log.txt)
Danke schonmal im Voraus

Nachtrag: Im Helfer Menü sind die strecken sichtbar

**Comment by Iwan1803** [comment]
Stell mal deine Grafikeinstellungen auf eine Default zurück (z.Bsp. mittlere Qualität).

**Comment by OstseeTimo** [comment]
Sorry das ich nicht geantwortet habe, hatte eigentlich die Benachrichtigungen angestellt hier für, aber nichts bekommen.  Das hat leider nicht funktioniert, habe es Des öfteren Probiert, ich denke ich werde mal alle sachen vom Game saven und neu Installieren

**Comment by OstseeTimo** [comment]
Sorry das ich nicht geantwortet habe, hatte eigentlich die Benachrichtigungen angestellt hier für, aber nichts bekommen.  Das hat leider nicht funktioniert, habe es Des öfteren Probiert, ich denke ich werde mal alle sachen vom Game saven und neu Installieren
