### ISSUE TITLE
Infinite pathfinding unload combine

### ISSUE THREAD

**Issue by duck-kid** [Stephan-S/FS22_AutoDrive#912]
Autodrive unload combine when pathfinding to catch up the the combine, when from start, or in the field, pathfinds infinitely, fulfulling the 1-2 or the 1-4 and then going back to 1

**Comment by Iwan1803** [comment]
And now we're supposed to guess what the situation is with you? 🙄

**Comment by Axel32019** [comment]
no update -> closed
