### ISSUE TITLE
does autodrive work with trailed forage harvester 

### ISSUE THREAD

**Issue by Horpestad** [Stephan-S/FS22_AutoDrive#913]
hello, is it not possible to use trailed forager harvester with autodrive? like the jf 1060 fct mod or the other john deere class ones? mine will not find the harvester at all
![fsScreen_2023_05_28_00_37_23](https://github.com/Stephan-S/FS22_AutoDrive/assets/93999285/ecdc6374-6d67-4adc-9780-06263623036c)
![fsScreen_2023_05_28_00_37_15](https://github.com/Stephan-S/FS22_AutoDrive/assets/93999285/6984ac41-46f9-4d31-989c-88ccf4cc1d07)

**Comment by Axel32019** [comment]
Hello, As you see already in pic 2, this is not a harvester at all!
From modDesc:
```
	<vehicleTypes>
		<type name="JF1060" parent="forageWagon" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="pipe" />
		</type>
    </vehicleTypes>	
```
So it is a forageWagon, means no bug from AD!
