### ISSUE TITLE
Deliver container to sellpoint.

### ISSUE THREAD

**Issue by VikingStreaming** [Stephan-S/FS22_AutoDrive#914]
When using the pick up and deliver mode, is there at way to setup AD to drive to the container dropof / sellpoint, and then drive to the store to get a new container, and then back to the location.

**Comment by Axel32019** [comment]
AD could not buy something - if this is you intention: NO
If container is some kind of autoload object supported by Paletten Autoloader Spezialisierung by AchiMobil: Yes
