### ISSUE TITLE
Abfahrer hält nicht mehr beim Durchfahrtssilo

### ISSUE THREAD

**Issue by eric4072** [Stephan-S/FS22_AutoDrive#916]
Hi! wie immer großes Danke an das gesamte Team! 

Ich weiß ja nicht ob dieses Problem nur bei mir Auftritt (wahrscheinlich), aber bei mir halten die Abfahrer nach dem abladen beim Durchfahrtssilo nicht mehr an. Es scheint so als würde er in der Anhänger-Rücksetzung (auf Fahrzustand) hängen bleiben und konstant mit ein paar km/h vorwärtsfahren.  Wenn die Linie dabei eine Kurve macht vor dem Abkipppunkt hält er den Einschlag der Vorderräder bei.

https://youtu.be/GyqhtRNG2Vo 

weiß nicht ob es an der Galgenberg oder an den Mods liegt, in der log vom LS habe ich nichts gefunden.

benötigt ihr zur Fehlersuche noch was?

LG Eric

**Comment by Axel32019** [comment]
Hi, ist bekannt & gefixt #861
