### ISSUE TITLE
Hide AutoDrive UI in menu

### ISSUE THREAD

**Issue by tinyoverflow** [Stephan-S/FS22_AutoDrive#917]
Hello,

currently, when the AutoDrive HUD is enabled, it is also shown in the menu. The keybindings to hide it don't work in the menu. It would be really awesome if it could be automatically hidden when the menu is opened, like Courseplay does it, so it doesn't block any menu elements.

**Comment by Iwan1803** [comment]
In the AD settings you can set an option to not show the AD help in the F1 menu 😉

**Comment by tinyoverflow** [comment]
Hey Iwan,

thanks, but thats not what I meant. I mean the Escape menu where you can see the map and assign jobs. When opening that, the little AutoDrive window is still visible. Courseplay hides itself when the menu is open.

**Comment by Iwan1803** [comment]
Don't know what is causing this on your site, but on my PDA the AD HUD will not be shown.

**Comment by 60erjonny** [comment]
@Iwan1803 wenn man die PDA bei der Weltkugel anklickt ist das AD-HUD weg, was aber er meinte ist wohl die PDA, wenn man das Lenkrad anklickt und da bleidt das AD-HUD aktiv...
![fsScreen_2023_06_07_19_05_53](https://github.com/Stephan-S/FS22_AutoDrive/assets/63659182/5bbfdf76-4113-4205-8141-847002b9058b)
![fsScreen_2023_06_07_19_05_38](https://github.com/Stephan-S/FS22_AutoDrive/assets/63659182/df157798-d470-4a42-a79d-c54d30b4fcb3)

**Comment by Iwan1803** [comment]
Ah, the helper map. CP works different then AD and so they are hiding their HUD as you need to create the jobs in the helper menu.
Why should the AD-HUD be hidden in the helper menu? I don't really see the purpose.

**Comment by 60erjonny** [comment]
@Iwan1803 ...je nachdem wo das Hud im Spiel positioniert ist und man in die PDA zoomt, könnte es die Sicht stören. Um diesen Umstand zu minimieren, habe ich es so eingestellt und gelöst...sehe es als Luxusproblem an...

**Comment by Iwan1803** [comment]
I see it exactly the same way. Also this is the helper menu and why shouldn't AD be displayed there to control the vehicles?
Maybe @tinyoverflow has a really good reason for it but this is the very first request where someone has a problem with the HUD display. Therefore I will close here for now.
