### ISSUE TITLE
Motor stellt nicht ab, wenn Fahrzeug an "P" geschickt wird.

### ISSUE THREAD

**Issue by zilicopter** [Stephan-S/FS22_AutoDrive#92]
Wenn ein Fahrzeug auf einem Ziel ein "P" zugewiesen wird, stellt der Motor nach dem Einparken nicht mehr ab. In 19 war das noch so.

**Comment by Axel32019** [comment]
Hallo @zilicopter ,
Kann ich nicht nachvollziehen. Wenn Du im Fahrzeug bist wenn P erreicht wird, bleibt der Motor an, bist Du nicht drin, Motor aus.
Da hat sich nichts geändert.

**Comment by zilicopter** [comment]
Hallo Stefan 
Danke für deine Antwort, blieb immer sitzen🙈

Grüsse
Zilicopter
