### ISSUE TITLE
ITRunner unfold

### ISSUE THREAD

**Issue by Vanquish081** [Stephan-S/FS22_AutoDrive#921]
Hello, It didn't happen before, I guess it's because of the latest Giants' patches, but now it unfolds when you send an ITRunner somewhere.

**Comment by Axel32019** [comment]
Hello, duplicate to #662.
translate this: https://github.com/Stephan-S/FS22_AutoDrive/issues/662#issuecomment-1320854645

**Comment by Vanquish081** [comment]
Oh... sorry, I searchedITRunner, no IT Runner
