### ISSUE TITLE
speedlimt for harvester should go below 50% within curves

### ISSUE THREAD

**Issue by merlinfive** [Stephan-S/FS22_AutoDrive#922]
hello , 

first of all many thanks for your great works and effort .
as mentioned in the title a speed limit for harvester below 50% would be great because  on map "Nordfrisische Marsch" the harvester often "moves/jumpes" over the crash barriers and got stuck .

**Comment by rohne83** [comment]
remove some waypoints within the curves, so the angle gets narrower. This makes the vehicles automatically drive slower.
Problem solved

**Comment by Axel32019** [comment]
Hello, you may set the corner speed for harvesters to lower value.
