### ISSUE TITLE
translation_da

### ISSUE THREAD

**Issue by Michaelbjerg21978** [Stephan-S/FS22_AutoDrive#923]
Pull requests failed, so hope you will see this.
Translated it to danish.
[translation_da.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11773674/translation_da.txt)
Hope you can use it.
Best regards
Michael

**Comment by Axel32019** [comment]
@Michaelbjerg21978 Thanks for you contribution!
No idea why a PR is not working, so to get the input here is OK.
I did a short test and found there seems to be 1 or more characters could not be handled by the FS engine:
line 118 has chacters "​​ZWSP​​ZWSP" - could you please check this?

**Comment by Iwan1803** [comment]
No further feedback -> closed!
