### ISSUE TITLE
Füttern

### ISSUE THREAD

**Issue by Hendirk** [Stephan-S/FS22_AutoDrive#925]
Ich habe eine Strecke erstellt das der Abfahrer vom Lager das Futter zu den Ställen zum Fütterungsroboter fährt,
Jetzt das Problem: Er fährt im Stall rein und kippt das Futter am Trog ab und nicht am Abkipppunkt
![Stroh füttern](https://github.com/Stephan-S/FS22_AutoDrive/assets/47453761/bbfa6f3d-0835-4d83-b1d8-031b8234ad24)
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/11908440/log.txt)

**Comment by manne70** [comment]
Ist der Trigger für den Roboter nicht auserhalb vom Stall?

**Comment by Hendirk** [comment]
Hallo Ja richtig der ist außerhalb, dort habe ich die Abkipppunkte gesetzt --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 29.06.23, 19:13 schrieb manne70 ***@***.***>:

   
  Ist der Trigger für den Roboter nicht auserhalb vom Stall?

**Comment by Axel32019** [comment]
Somit kein Fehler.
