### ISSUE TITLE
Request Personal and Shared Waypoints

### ISSUE THREAD

**Issue by Beedog743** [Stephan-S/FS22_AutoDrive#93]
I'm playing on a dedicated server and I want to create a network to park all of my vehicles however with how setting a parking point works I have to create a waypoint in order for that vehicle to park there when I say to park. Being on a dedicated server with my friends I don't want to clog up the drop down menu's  with Parking #1, Parking #2 etc. I would like to see a feature implemented either to create private waypoints which are only visible to the individuals farm that created them and shared waypoints which are available to all farms on a server like the "shop" etc. Or at the least be able to select a node and assign a parking point to a specific node without having to create a waypoint.

**Comment by Iwan1803** [comment]
The problem is that this will make AD unnecessarily complicated and probably also slow, since then quite a few checks are required each time.
I would rather recommend that you simply create folders, where you then store your private destinations in it.

**Comment by Beedog743** [comment]
Cam creating folders be done in game?

**Comment by Iwan1803** [comment]
Yes, if you've activated the use of folders in the AD settings.

**Comment by Beedog743** [comment]
Alright so I enabled the use folders option and I had created a folder. How do I utilize it? I try to select the created folder but nothing happens, is there certain keybinds? Do I need to delete waypoints and re create them?

**Comment by Iwan1803** [comment]
Move the target points using drag'n'drop into the folder 😉
