### ISSUE TITLE
Oi, quando o funcionário esta trabalhando e acaba as sementes/fertilizantes o autodrive não envia o funcionário para reabastecer sementes/fertilizantes

### ISSUE THREAD

**Issue by DavidCriptoo** [Stephan-S/FS22_AutoDrive#930]
/Oi, quando o funcionário esta trabalhando e acaba as sementes/fertilizantes o autodrive não envia o funcionário para reabastecer sementes/fertilizantes

**Comment by Iwan1803** [comment]
Translated: "when the employee is working and runs out of seeds/fertilizers the autodrive does not send the employee to replenish seeds/fertilizers"
Who is the employee? LS helper or CoursePlay or who?

**Comment by DavidCriptoo** [comment]
CoursePlay

**Comment by Iwan1803** [comment]
This feature allready exists if you are using CP. You only need to setup the pickup&delivery mode and activate the CP button in the AD hud.

**Comment by DavidCriptoo** [comment]
Ah, entendi obrigado 
Abraço e sucesso

**Comment by Iwan1803** [comment]
Great, have fun 😉
