### ISSUE TITLE
Technology sensors.

### ISSUE THREAD

**Issue by Nikossdim** [Stephan-S/FS22_AutoDrive#933]
Hello. Help fix the car. When obstacle detection is enabled, the car is loaded with pallets and drives back to the unloading point, but cannot drive because the rear sensor is displaced. Help how to fix it?
![fsScreen_2023_05_15_18_31_18](https://github.com/Stephan-S/FS22_AutoDrive/assets/98506753/2074ebeb-4202-48f3-8f67-1fd2f50ec7d4)

**Comment by Axel32019** [comment]
Hello, Check the size of the vehicle in the .xml:
Look for
```
    <base>
        <size width="4.5" length="8.8" height="3.8" />

```
length seems to be too small -> increase until red box appear behind car.

**Comment by Nikossdim** [comment]
Hello. When changing the length of the car, as you advised, the frame did move back, but for some reason the front frame moved forward. If you know how to fix it please tell me.
![fsScreen_2023_07_19_06_12_12](https://github.com/Stephan-S/FS22_AutoDrive/assets/98506753/94b28fed-ec61-4440-bae4-83da5103d562)
![fsScreen_2023_07_19_06_16_19](https://github.com/Stephan-S/FS22_AutoDrive/assets/98506753/8c5702a8-36b8-4009-a6c3-4dd185a57dcf)
![fsScreen_2023_07_19_06_11_46](https://github.com/Stephan-S/FS22_AutoDrive/assets/98506753/6abcd01a-6dfa-4062-89b6-e26ff17b87ba)
