### ISSUE TITLE
Fehler beim endlos "Liefern und Entladen"

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS22_AutoDrive#938]
Hallo zusammen,

seit der neuen Version gibt es das Problem, dass beim Abholen und Entladen, nach dem Entladen das Fahrzeug stehen bleibt und nicht erneut zur Ladestelle fährt.
Erst nach deaktivieren und neuen Aktivieren geht die Runde von neuem los.

Viele Grüße

Marc

**Comment by blackscorpion80** [comment]
Ich habe das gleiche Problem erkannt aber bei mir sind es nur die LKW's die stehen bleiben die Traktoren fahren weiter wie üblich.

**Comment by JDTiger** [comment]
Ich hatte das Problem auch, stellte sich heraus, dass es scheinbar am verwendeten mod-LKW lag.

Versucht es mal mit einem Truck aus dem Basegame

**Comment by Kitekater** [comment]
Wir nutzen das [FS22_MAN_TGX_Semi_Pack]

**Comment by Huschti** [comment]
da ich das Problem auch habe habe ich verschiedne Mod-LKWs getestet bisher sind von dem Problem betroffen das [FS22_MAN_TGX_Semi_Pack] aus dem modhub 
[FS22_KronePack] download zb von Forbiddenmods 
[MAN TGX 2020] von bd-modding
[Mercedes MP4] von bd-modding
[DAF XG+] von bd-modding

**Comment by Axel32019** [comment]
Schaut man mal in den "[FS22_MAN_TGX_Semi_Pack] aus dem modhub":
Was hat die Konfiguration einer Sonnenblende mit fillUnitConfiguration zu tun?
Wofür benötigt eine Semi-Zugmaschine die Spezialisierung etwas entladen zu können `<specialization name="dischargeable" />` ?
Das wissen wohl nur die Fahrzeug-Modder die es erstellen und Giants die das in den modHub bringen...

**Comment by Axel32019** [comment]
Integrated in Release 2.0.1.4
