### ISSUE TITLE
Automatische Kurvenberechnung auch bei Dualen Strecken ermöglichen (180° verdrehter Start/Ziel)

### ISSUE THREAD

**Issue by Zugross** [Stephan-S/FS22_AutoDrive#94]
Ich hoffe der Betreff passt soweit. Da ich es nicht richtig beschreiben kann, hab ich kurz ein Video von gemacht: 
https://youtu.be/tjY8dymgY8Y

**Comment by haamic** [comment]
Das hab ich auch schon bemerkt. irgendwie hängt das mit der Richtung des Aufzeichnens zusammen, auch wenn die Linien blau sind. Will man entgegengesetzte Richtungen mit Kurven versehen, kommt das zustande ,was du im Video zeigst.
Daher färbe ich, wenn alles passt erst blau. Ansonsten hab ich mir auch so geholfen, indem ich bei solchen blauen Kreuzungen, ab den Kreuzungspunkten mittels Tastenkombi erstmal umfärbe auf grün und/oder die Richtungen wechsel, bis es mit dem Kurventool in die richtige Richtung funktioniert.  Weisst du was ich meine mit umfärben/richtung wechseln per Taste? siehe Bild.

![farbe-typ](https://user-images.githubusercontent.com/28841989/147322419-ce157a58-aae5-4b8d-80b8-0421e3100763.jpg)

Manchmal hatte es bei mir geklappt, wenn man versucht aus der anderen Richtung die Kurve zu erstellen, in deinem Fall klappte das aber auch nicht.  Es kann auch nicht eine schon vorhanden Kurve, die meinetwegen von links nach unten geht, von dem unteren Punkt nach rechts erzeugt werden, da die Richtungen die am unteren Punkt sind, in verschiedene Richtungen gehen. Denkt man sich einen Mittelpunkt einer Kreuzung, dann die Nord-Süd Richtungen zum Mittelpunkt, ost-West weg vom Mittelpunkt. so sollten Kurven erzeugbar sein vom unteren Punkt nach links und rechts. Das gleiche vom oberen Punkt. Es muss auch immer ein Punkt als Start und Ziel gewählt werden, der beidseitig angebunden ist, keine Sackgasse, da entsteht sonst nur eine gerade, auch wenn man am Mausrad dreht.

![k](https://user-images.githubusercontent.com/28841989/147330590-e39f5dd7-517a-423a-9c11-24f762730b74.jpg)

Das Kurventool ist schon eine super Sache, vielleicht gibts da noch Anpassungen. Es ist ja noch ziemlich neu.
Ich komm aber trotzdem klar damit.

Frohe Weihnachten

Gruss Micha

Hier andere Beispielbilder, wo es nicht geht, bzw. wie man es hinbekommt.

![kreuzung2](https://user-images.githubusercontent.com/28841989/147327593-069ed465-4ca9-4044-9a1f-971ea3540f74.jpg)

**Comment by regs1980** [comment]
@ThomasMatern Danke für die Verbesserung, erleichtert einem die Stecke zu bearbeiten. 

Alte Variante
https://drive.google.com/file/d/1x5yHZ3LYR6dcI3shxuvyuGwvlMyf9Py9/view?usp=sharing

Neue Variante
https://drive.google.com/file/d/1MPvJjbaArOxNpe9-7_369YoT2SmbNR9A/view?usp=sharing

Eine kleine Anmerkung habe ich, da es jetzt möglich ist, eine entgegengesetzte Fahrtrichtungskurve zu setzten, müsste man diesen Knotenpunkt, 

![2023-11-17 12_13_45-Greenshot](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/47ef0e77-e07f-47bc-8b10-f22aeaf650b0)

beim Streckennetz-Debugging mit anzeigen, unter Fehler 9_.

https://github.com/Stephan-S/FS22_AutoDrive/wiki/FAQ-english

**Comment by ThomasMatern** [comment]
@regs1980 vielen Dank das du dir das angesehen hast. Ich habe das Streckennetz-Debugging noch nie benutzt, aber es scheint als ob die 9_* Punkte nur an schlechten Abzweigungen und nicht an Einmuendungen erzeugt werden - darum ist der Punkt ganz rechts in deinem Bild auch nicht als problematisch markiert.
Mich stoert, dass man keine untergeordneten Verbindungen (braun) und/oder  Zwei-Wegeverbindungen (blau) erzeugen kann. Vielleicht sollten wir eine Kombination von Shift/Alt/Ctrl dafuer benutzen?

**Comment by regs1980** [comment]
@ThomasMatern 
> Mich stoert, dass man keine untergeordneten Verbindungen (braun) und/oder Zwei-Wegeverbindungen (blau) erzeugen kann. Vielleicht sollten wir eine Kombination von Shift/Alt/Ctrl dafuer benutzen?

Wenn es möglich ist, warum nicht, nur halt nicht allzu kompliziert machen, muss für User noch nachvollziehbar sein, das bedienen.  

In Sachen Streckennetz-Debugging keine Ahnung was da die Kriterien sind um einen 9_x Fehler anzuzeigen.
Weil 9_2 ist eine 90° Winkel, rechts wird ja nichts angezeigt und 9_3 ist entgegen der Fahrtrichtung.
@Axel32019 du kannst da bestimmt mehr zu sagen.

**Comment by Axel32019** [comment]
@regs1980 Sollte damit auch angezeigt werden.

**Comment by ThomasMatern** [comment]
@Axel32019 OK, ich schaue mir das 9_x Problem an (hat aber nichts mit #94 zu tun)

**Comment by Axel32019** [comment]
@ThomasMatern Hab ich schon erledigt.

**Comment by ThomasMatern** [comment]
@regs1980 @Axel32019 fixed.

**Comment by ThomasMatern** [comment]
@Axel32019 deine Loesung erzeugt einen Fehler an jedem Wegpunkt:
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/8754844/ced692e7-c803-47e5-8a3f-f12d7a35f031)

**Comment by ThomasMatern** [comment]
- wenn der Start- oder Endpunkt eine untergeordnete Prioritaet hat, bekommt die ganze Kurve eine untergeordnete Prioritaet. Das Verhalten existierte schon, wenn man zwei Punkte direkt (mit einer Geraden) verbindet
- wenn man die linke Ctrl-Taste drueckt, wird eine Kurve fuer beide Fahrtrichtungen erzeugt
- die Kurvenvorschau zeigt an welcher Strassentyp erzeugt wird

@Axel32019 ich habe 4 neue Eintrage in translation.xml erzeugt. Kopiert ihr die manuell fuer jede Sprache oder gibt es dafuer irgendein scipt?

**Comment by regs1980** [comment]
@ThomasMatern 

> wenn man die linke Ctrl-Taste drueckt, wird eine Kurve fuer beide Fahrtrichtungen erzeugt

Das musst du ändern, Ctrl-Taste ändert die Richtung der Strecke, wenn man den Scheitelpunkt markiert hat und den darauf folgenden anklickt.

https://github.com/Stephan-S/FS22_AutoDrive/wiki/Info:-Tastenkombinationen

Was noch frei ist LSTRG + LALT.

Ansonsten sieht das mit dem Streckennetz-Debugging sehr gut aus, mehr Hinweise, wo eventuelle Fehler sein können.
Dadurch kann man jetzt sowas schneller erkennen in Kurs die man Downloadet.

![2023-11-19 11_44_57-Greenshot](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/7a1ce6e6-8afb-447b-a69a-552061a5882a)
![2023-11-19 11_45_47-Greenshot](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/ec7e29b7-ac5f-4b0d-8e4e-75ee2e0847fa)

**Comment by Axel32019** [comment]
> @Axel32019 ich habe 4 neue Eintrage in translation.xml erzeugt. Kopiert ihr die manuell fuer jede Sprache oder gibt es dafuer irgendein scipt?
@ThomasMatern Kein script - wir kopieren die englischen Texte in alle Sprachen, außer Deutsch, das kriegen wir direkt hin.

**Comment by Axel32019** [comment]
> @Axel32019 deine Loesung erzeugt einen Fehler an jedem Wegpunkt: ![image](https://user-images.githubusercontent.com/8754844/284027227-ced692e7-c803-47e5-8a3f-f12d7a35f031.png)

Warum das bei mir erst funktioniert hat, dann nicht mehr und auch ein Unterschied zwischen Deiner Ausgabe und der von @regs1980  erschließt sich mir noch nicht. Hab das nochmal überarbeitet:

**Comment by regs1980** [comment]
@ThomasMatern die gute S-Kurve wird nicht erstellt.
![2023-11-24 21_16_29-Greenshot](https://github.com/Stephan-S/FS22_AutoDrive/assets/13314443/e988815a-fa5d-4468-89aa-22fce52c1ef1)
Alles andere ist Super.

**Comment by ThomasMatern** [comment]
@regs1980 das funktioniert mit dem neuen Algorithmus nicht mehr - es funktioniert nur noch fuer Wegsegmente die sich irgendwo schneiden wuerden. Ich habe mal versucht, dass mit AD darzustellen:
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/8754844/9020dad9-18d9-4417-8756-5322031ce733)
Angenommen wir haben einen Wegpunkt (links im Bild) der seinerseits drei Wegpunkte verbindet (links, nicht sichtbar), und die gleiche Situation mit einem zweiten Wegpunkt (unten im Bild). Der Algorithmus berechnet dann, wo sich diese 3x3 Wegpunktrichtungen schneiden wuerden (braune Linien und rote Kreuze) - und waehlt dann den dichtesten Schnittpunkt aus (unten links).
In deinem Fall sind die beiden Strecken fast parallel, sie schneiden sich also in grosser Entfernung. Der Schnittpunkt mit dem Wegpunkt links von deiner Kreuzung ist deutlich dichter und wird deshalb bevorzugt. 
Fuer die S-Kurve braeuchten wir eine voellig andere Herangehensweise. Ich denke mal darueber nach....

**Comment by ThomasMatern** [comment]
@regs1980 ich habe das mal ueberarbeitet und einen ganz anderen Ansatz gefunden. Das scheint besser zu funktionieren und auch deine S-Kurve funktioniert wieder.

**Comment by regs1980** [comment]
@ThomasMatern Ich bin beeindruckt, sogar die S-Kurve ist jetzt möglich per STRG+ALT gleich in eine 2-Wege Stecke zu erstellen.
