### ISSUE TITLE
On harvester mode or pickup and deliver mode allow the tractor to return closer to the harvester to wait

### ISSUE THREAD

**Issue by coatsy35** [Stephan-S/FS22_AutoDrive#941]
On very large fields like the Oaks or western Australia maps etc.... on harvester mode and the pickup and deliver mode you have to set a field location and the delivery point. The problem is if you have say 3 vehicles all unloading from the same harvester, they are all jammed up waiting on the field location node and they could be a very long distance form the harvester. 

Could a system be put in place so that the next unloader moves along the headland to nearer where the harvester is working? so that when it calls for unload it';s not miles away and doesn't get there before it needs unloading? even at 40% precall in a lot of fields the trailer doesn't get to the harvester on time, and then due to the AD bug of not restarting unload on the move, you waste so much time harvesting. 

If it's not possible to do that, perhaps you could have multiple field location pins perhaps? so if you had an outer field path, trailers could wait at different distances around the field and if the point was in use by another trailer there the vehicle would continue to the next point that wasn't in use and wait there.

**Comment by TobiHH78** [comment]
Use the pre-call 2nd unloader function in the combine settings.
If you activate that, the 2nd unloader approaches the combine much earlier, and if the first unloader gets full, the 2nd unloader is not far away from the combine.

I always use that function on big fields, and never had the issua that next unloader doesn`t reach combine in time to unload on the move.

**Comment by Axel32019** [comment]
As @TobiHH78 mentioned.
