### ISSUE TITLE
Not continuing after unloading to silo (unload combine mode).

### ISSUE THREAD

**Issue by Bullzdozer** [Stephan-S/FS22_AutoDrive#942]
Been playing with v 2.0.1.0 of autodrive untill to day since atleast a month back.

updated today to the 2.0.1.2 version 

it´s been working fine untill i updated and for some reason its not working for me unloading to silos in latest version.

[Unload combine mode]
unloads the combine fine (exept the normal random jank with pathfinding causing it to randomly crash in to stuff sometimes it has passe by like 1000 times before whitout crashing).

Runs up towards the unload target. 

Stops a bit early to the taget (did in 2.0.1.0 aswell so guess its the unload trigger stopping it early) unloads the trailer to the silo.

Then just slowly goes forward to the actual unload taget and then just stands there with auto drive enabled unlil i either restart autodrive or tells it to go to next target manualy. 
(this is my problem with 2.0.1.2 . in previous version when the trailer was empty it just continued to next target automagicly n didnt even stop at the actual target location before continuing to unload target)

tried moving the target closer/away from the silo . -no go.
tried removing one of the silos on the path (had 2 on the same unload target to rule out jank with multiple unload zones or something). -no go

was working fine in 2.0.1.0 so just downgraded to that version again and now its working as it used to.

**Comment by Huschti** [comment]
did you use a mod truck?

**Comment by DemsMani** [comment]
I have the exact same problem. Have not yet tested a non mod truck, but at least with the Mod truck, I had the exact same behavior

**Comment by Huschti** [comment]
in Issue #938 i posted [https://github.com/Stephan-S/FS22_AutoDrive/issues/938](url)

**Comment by Huschti** [comment]
in Issue #938 I posted a small list of mods i tested who have the problem and it looks like the standard trucks dont have this problem

**Comment by Bullzdozer** [comment]
> did you use a mod truck?

Both yes and no.

had same issue with both the john Deere 7030 premium (mod) Valtra Q305 (mod) and my john Deere 7R (non mod).



> in Issue #938 I posted a small list of mods i tested who have the problem and it looks like the standard trucks dont have this problem

**Comment by regs1980** [comment]
Vanilla mods work. 
Custom mods that do not work deviate from the Gaints default.

**Comment by Axel32019** [comment]
Integrated in Release 2.0.1.4
