### ISSUE TITLE
Autodrive Consumes fertilizer on road if  Seeder fertilizer or sprayer is equipped 

### ISSUE THREAD

**Issue by ole22143** [Stephan-S/FS22_AutoDrive#945]
Autodrive Consumes fertilizer on road if  Seeder fertilizer or sprayer is equipped.

**Comment by regs1980** [comment]
Is a Giants bug.
The same thing happens with the ingame helper.

**Comment by Iwan1803** [comment]
No bug by AD but by Giants.
