### ISSUE TITLE
Rückwärts Fahrproblem mit John Deere 7R in Verbindung mit dem Laforge EZ 1700 und einem angehängtem Gerät

### ISSUE THREAD

**Issue by regs1980** [Stephan-S/FS22_AutoDrive#948]
Verbinde ich das Laforge EZ 1700 Unterbodengewicht (Mod aus dem Basisspiel) mit einem John Deere 7R (Mod aus dem Basisspiel) und hänge dann ein Anbaugerät daran, was Achsen hat, kann AD das Gespann nicht durch selbst Justierung gerade nach hinten drücken.

https://drive.google.com/file/d/1gBFZZC5z8KV1l4LS13ykwPWjCTSnLPJm/view?usp=sharing

Hängt man das Anbaugerät erst an und dann das Unterbodengewicht, dann funktioniert es, nur hängt man das Anbaugerät ab und ein neues an, tritt wieder der Fehler auf, schön zusehen im Video.

**Comment by Axel32019** [comment]
Schönes Gewicht mit `spec_wheels`

**Comment by regs1980** [comment]
Funktioniert Perfekt, danke.

**Comment by regs1980** [comment]
Funktioniert Perfekt, danke.

**Comment by Axel32019** [comment]
Damit es für das Release nicht vergessen wird, mach ich mal wieder auf.
Danke @regs1980 für die Rückmeldung!
