### ISSUE TITLE
How to create a new translation

### ISSUE THREAD

**Issue by aini1123** [Stephan-S/FS22_AutoDrive#95]
I created a new Chinese translation file based on the French file and put it into the translation file, but this does not take effect。I'm not a programmer and can't write code. I'm sorry. Can you help me
[translation_cn.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7772102/translation_cn.zip)
！

**Comment by Bobster82** [comment]
Hey, I think I saw the problem, please check your file again for errors. I saw 2 quotations mark errors on line 251 and 355

**Comment by aini1123** [comment]
OK, thank you for your help! I'll try to check and modify the two error points you found

**Comment by aini1123** [comment]
There are new problems! How to switch language translation to check whether my translation file is effective

**Comment by Bobster82** [comment]
A quick google search will answer most questions ;)

Quit the game and go to Steam.
In Steam, go to Library and then to Farming Simulator 22.
While on the game, right-click on it and select Properties. Click on it.
In the Properties section, go to Language. In the language tab, select the language of your choice and then launch the game. You will have the same language set in the game.

**Comment by aini1123** [comment]
thank you! At present, the translated files have been successfully applied in the game! However, there is an error in naming the translation file. When it is named (translation CN), it cannot be displayed in the game! It can only be displayed normally by changing its name to (CS)
[translation_cn.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7773995/translation_cn.zip)
!

**Comment by Axel32019** [comment]
Hello @aini1123 ,
The game supports the following languages: Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr ea da fi no sv fc
So the file name should be "translation_" + 2 of above characters.
If cs is for chinese we have to change the file name to _cs.xml.
Is this OK?

**Comment by aini1123** [comment]
Hi. I have completed the Chinese translation of the latest version 2.0.0.3, but due to the relationship between the Chinese font library of the game, the translation may not be fully displayed in the game, but it does not hinder normal use. How do I upload it nex
[translation_cs.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/7921926/translation_cs.zip)
t
