### ISSUE TITLE
Vehicle stops when using the Workshop trigger mod

### ISSUE THREAD

**Issue by emegbert** [Stephan-S/FS22_AutoDrive#950]
When using the Workshop Trigger mod I have an Autodrive course that runs over the trigger.  The vehicles are supposed to drive through the trigger where they get repaired and washed automatically.  Starting with version 2.0 the vehicles will stop before reaching the Workshop trigger and not drive through the trigger.  Not sure what logs or screens prints you might want for this.

**Comment by Iwan1803** [comment]
Please check the collisions settings in AD. Try to set it to 2.0m and "FS 19".

**Comment by emegbert** [comment]
FS19 and 2.0m allows it to work.

**Comment by Iwan1803** [comment]
Great, so i'll close here 😀
