### ISSUE TITLE
Auto Drive Issue can't compete route loop 

### ISSUE THREAD

**Issue by mirrorcarp27** [Stephan-S/FS22_AutoDrive#952]
Need help With Auto Drive latest version  2.0.1.2 I'm on the new FS22  DLC Horsch Map & I have created a loop route from Field 9 to unload to the Agrovation Silo it will unload fine but it gets stuck won't compete the loop back to field 9 how do i fix could someone test this out for 
issues many thanks
NEW

Also i thinks this also happens when you create a loop to load up from the Agrovation Silo it will load fine but it gets stuck won't compete loop 

Ps Auto Drive doing the same task with previous version 2.0.1.0 working fine doing loops

**Comment by rohne83** [comment]
duplicate to #942 / #946 ?
