### ISSUE TITLE
Autodrive tipping in wrong place

### ISSUE THREAD

**Issue by prawler74** [Stephan-S/FS22_AutoDrive#955]
Hi

Autodrive is really an awesome mod. 
Recently with 2.0.1.0 and the latest 2.0.1.2 there is something wrong. We are playing on Tranquil Waters by Stevie, and when we tell the forage wagon to tip in the main silo, it passes over the sheep tip trigger and tips the grass to the sheeps and then continues to the main silo.....

What could be wrong?

Keep up the good work

Bjørn

**Comment by prawler74** [comment]
Hi.

I will check.......get back with an update soon

Bjørn

**Comment by Iwan1803** [comment]
AD checks in front of the select target if there is a trigger.

**Comment by prawler74** [comment]
Thanx for explaining. 10 is the lowest. Do you know if there wil be an option to set it to 5 or 1?

When the forage w drives over the farm silo it unloads there instead of driving to the set point.

But i have solved one problem.

Any idea on this one?


Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Iwan1803** [comment]
A tractor has a length of 3-5 meters + trail 3-7 meters... so lower than 10m doesn't make sense.

**Comment by prawler74** [comment]
Yeah.

You are probably right.
Se if there is a possibility to move the triggers.

Thanx for all youre help. Really appreciated. 🤘

Best regards
Bjørn



Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Iwan1803** [comment]
Don't move the trigger - move the target point 😉
As it was solved -> closed.
