### ISSUE TITLE
Lineheight in settings

### ISSUE THREAD

**Issue by DennisKgaming** [Stephan-S/FS22_AutoDrive#957]
When you change the lineheight in settings to "Above the tractor" and save the settings, next time you open the gamer it isn't above the tractor anymore. I have seen this by several people and would like to know if the setting can stay saved so you don't always have to go back to the settings.

Thanks in advance.
Gr DennisK

**Comment by Axel32019** [comment]
From "seen" this or that we cannot investigate!
Please add the following files, then we can have a look into this!
AutoDrive_config.xml, AutoDriveUsersData.xml, vehicles.xml, log.txt

**Comment by Axel32019** [comment]
no feedback -> closed.
