### ISSUE TITLE
AD berechnet Düngerkosten bei Fahrten von A nach B ?

### ISSUE THREAD

**Issue by Kobold11** [Stephan-S/FS22_AutoDrive#958]
Beispiel:
Mein Trecker steht auf seinem Parkrkplatz.Ich hänge einen Düngerstreuer an.Dann soll er "nur" vom Parkplatz zum Feld fahren.(also nur fahre von A nach B).Sobald ich AD starte zählt mein Kotostand runter so als würde er schon Düngen.(kein CP Kurs geladen oder sonst etwas)
Auch bei Fahrten z.b vom Hof 1 zu Hof2.
Dabei ist es egal ob es ein Anhänger ist,ein Anbau oder ein Selbstfahrer.
Alles was zum Düngen gedacht ist verursacht Kosten sobald AD gestartet wird.
Trecker sowie Dünger Geräte sind keine Mods.(hab es aber auch mit Mods getestet.Das gleiche Problem)
AD und CP sind Aktuell.

**Comment by Axel32019** [comment]
Giants Bug #945
