### ISSUE TITLE
[BUG] [ Version 2.0.1.2] Not continuing after unloading to silo

### ISSUE THREAD

**Issue by Rambo99** [Stephan-S/FS22_AutoDrive#960]
The situation completely repeats the situation in request #942 (https://github.com/Stephan-S/FS22_AutoDrive/issues/942). Except for what happened not with the storage of grain crops, but with the storage for liquids and exclusively for only one type of equipment, only for a specific storage and a specific model (brand) of equipment. when replacing one brand with another, the problem disappears. I will add that this bug is not displayed in the game log file in any way, there is a standard record about accepting and saving a given course and that's it. Moreover, the bug "walking" at each game load can "turn off" any technique at random. For example, I have a "buggy" in this way either mod MAN or default (standard, not mod) TATRA. Every time it's different.
 Addition. If you press the "go to the next point" button (double arrow, >>) on the autodrive panel, then the vehicle continues to move to the starting (next) point of the route without any problems.

**Comment by Rambo99** [comment]
The situation has worsened. Now this bug is not local, but spread over ALL available storages in the game (both from the game developers and created by mod creators). The only joy is that if a specific brand of car or tractor is "bugged", then this will not change. At least that's stability.

**Comment by Rambo99** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/12289117/log.txt)
Game Log file.

**Comment by regs1980** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/issues/946

**Comment by Rambo99** [comment]
Screenshots to better understand the problem.
![20230808130316_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/1098421/da442e28-31c3-497d-b496-7094c61da390)
![20230808125756_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/1098421/95b6fa49-97ed-48b9-b7bc-b39e3c129698)
![20230808125929_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/1098421/a8be0ab7-97ff-4902-a0e1-8f6ec3f41ccd)
![20230808125956_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/1098421/131431ac-9d86-4ebf-80a5-5729bebdb119)
![20230808130141_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/1098421/cec78232-a964-46be-a56a-2b70287b668f)

**Comment by Rambo99** [comment]
Thank you for the amazing mod you created.
