### ISSUE TITLE
[Feature] Maximum trigger distance per vehicle

### ISSUE THREAD

**Issue by JDTiger** [Stephan-S/FS22_AutoDrive#962]
Hey,

I am currently running a roadtrain, wich need the max trigger distance to be set at 100m to unload correctly.
I am also running graincarts with Autodrive, wich obviusly could do with a way shorter distance setting.

Would it be possible to have the global trigger distance setting be overwritten by a vehicle specific one?

**Comment by Axel32019** [comment]
@Iwan1803 fixed with #1005
