### ISSUE TITLE
Map Marker nicht sichtbar wenn Server beitritt

### ISSUE THREAD

**Issue by SirGarnet** [Stephan-S/FS22_AutoDrive#964]
Hi,

wenn ich dem Server beitrete, sind die Marker der aktiven AD-Fahrer auf der Karte nicht sichtbar. Leider kann man so die Fzg. auch nicht auf der Karte anwählen. Erst nachdem man in das Fahrzeug getabt ist und AD deaktiviert & aktiviert wird das entsprechende Fahrzeug wieder angezeigt.

Mittlerweile sind hier zehn Abfahrer unterwegs und einige Transport-Fzg. + div. Arbeitsbienen. Jedes mal durch den ganzen Fuhrpark zu springen ist etwas aufwändig.

Die Helfer von CP & Giants sind immer sichtbar.

Version: 2.0.1.2

**Comment by Iwan1803** [comment]
Schöne Grüße an Giants, denn das scheint ein Synchro-Problem zu sein. Ab und zu haben Mitspieler von mir ein ähnliches Problem, das sie aktive AD-Fahrzeuge nicht sehen. In der Regel dauert es dann ein paar Minuten, bis die Synchro der Map & Co. vollständig durch ist, bis sie diese wieder sehen oder sie verlassen den Server und joinen neu.
