### ISSUE TITLE
What would cause the delivery mode not to load?

### ISSUE THREAD

**Issue by coatsy35** [Stephan-S/FS22_AutoDrive#965]
Have used pickup and delivery mode in the past. However today the trailer pulls under my Silo (same as I've used before - weeks ago) and it doesn't' fill? the silo only has Canola in it and AD is set to collect Canola from my Silo and the deliver it. It delivers it fine but I have to press R each time to fill it up and select Canola from the Silo list. Is this broken in the latest release?

**Comment by Iwan1803** [comment]
If this feature has been broken a lot more AD user would report that problem. So this seems to be a personal issue but how should we help without further informations? A screenshot of the situation with unhidden AD lines could be helpful.

**Comment by Axel32019** [comment]
no feedback -> closed
