### ISSUE TITLE
Fahrzeug parkt nicht richtig ein

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS22_AutoDrive#967]
Hallo zusammen,

ich habe hier einen relativ komischen Fall.
Auf unserem Hof befinden sich mehrere Traktoren des gleichen Mods, die sich nur durch die Farbe unterscheiden, sämtliche sonstigen Konfigurationen sind gleich.
Einer von den Traktoren parkt die Anbaugeräte nicht ein,
Er fährt richtig in die Spur, nur sobald er rückwärts fahren soll, lenkt er voll ein und stellt sich quer vor den Parkplatz/Halle und beendet AD.
Ein anderer Traktor, selben Herstellers macht es ohne Probleme. Es ist auch egal, welches Anbaugerät geparkt werden soll.
Auch ist es egal, welcher Spieler den Parkvorgang startet (Multiplayer).
Was kann das sein?
Nutzen die v 2.0.1.0
Waren kurz auf der aktuellen Version, sind aber wegen der unterbrochenen Lieferkettenfahrten erstmal zurück auf die Vorgängerversion

VG
Marc

**Comment by rohne83** [comment]
Wäre wohl sehr hilfreich wenn du dazu schreiben würdest, welcher Traktor das denn ist, der Probleme macht. Screenshot von der Situation mit eingeblendetem Routennetz könnte auch hilfreich sein.

**Comment by Axel32019** [comment]
`Einer von den Traktoren parkt die Anbaugeräte nicht` ein Welcher / welches Gerät?

**Comment by Kitekater** [comment]
Es sind die 1050 von Alex Blue.
Problem hat sich aber erledigt. Habe den Traktor verkauft und den Gleichen neu gekauft, dann hat es wieder geklappt
