### ISSUE TITLE
Der Helfermodus und AD

### ISSUE THREAD

**Issue by BigBlackBahamut** [Stephan-S/FS22_AutoDrive#97]
Hallo zusammen, 

wenn ich im Menü Helfer gehen kann man da ja auch den AD benutzen, leider aber nur dann wenn man vorher in einem Fahrzeug die Maus aktiviert hat. Kann man vielleicht das so einstellen das im Helfermenü der AD immer benutzbar ist?

MP:

Wenn man einen Helfer mit AD einstellt dauert es bis er losfährt. Habt Ihr da Einfluss? 
Nachtrag: Im Moment möchte der Helfer nicht losfahren bis ich einmal eingestiegen bin. Das macht den AD im Helfermenü überflüssig.

Was auch nicht wirklich klappt (vielleicht bin ich zu blöd) ist das setzten von Zielen mit der Linken und der Rechten Maustaste im Helfermenü beim AD.

LG

**Comment by Iwan1803** [comment]
Das klingt für mich danach, als wenn du noch nicht 2.0.0.2 geladen hast, denn dort ist es nicht mehr notwendig, das man in einem Fahrzeug sitzen muss, um etwas im Helfermenü zu aktivieren.

**Comment by BigBlackBahamut** [comment]
Eigentlich müsste auf Server und in meinen LS das neuste drin sein. Ich schau später nochmal nach wegen der Version. Ich melde mich dann diesbezüglich noch einmal zurück. Schönes Weihnachtsfest.

**Comment by BigBlackBahamut** [comment]
So, ich habe mich noch einmal vergewissert. Versionen Aktuell und sobald ich ins Helfermenü gehe habe ich nur auf das AD Zugriff wenn ich in einem Gefährt sitze und AD mit der Maus steuern kann. Das ist bei SP und im MP so. Das der Helfer nach dem aktivieren des AD´s nicht losfährt außer ich setzte mich einmal hinein ist nur im MP so. Ich habe es gerade mal gestestet. Im SP funzelt es.

**Comment by BigBlackBahamut** [comment]
Leider muss ich wieder hinzufügen das AD auf dem MP nicht so läuft wie es sollte. Zu einem fuhr der Helfer beim ersten abfahren eine extra Runde über das Feld ohne mich abzutanken, erst beim zweiten Anlauf hat es funktioniert. Doch dann steht dieser im Feld anstatt wieder runter zu fahren bzw das Feld frei zu machen. Schalte ich die Kollision ein fährt der AD keine Feldauswege mehr raus wenn gegenüber ein Baum steht.

**Comment by Iwan1803** [comment]
Dann scheint bei dir/euch irgendwas nicht zu passen. Habt ihr Click2Switch drauf?
Sowohl im SP als auch auf unserem Dediserver habe ich 0 Probleme dieser Art.

Bzgl. Abfahrer: welche Einstellungen hat er denn?
Bzgl. Kollision: welche Höhe habt ihr denn eingestellt?

**Comment by BigBlackBahamut** [comment]
Nein, haben wir nicht. Auch habe ich die selben Mod in MP wie in SP. Daher wundert es mich ja. Bin auch heute nicht zu Hause, morgen erst. Was könnte den triggern?

**Comment by BigBlackBahamut** [comment]
![20211226121306_1](https://user-images.githubusercontent.com/59480223/147406296-d851f109-2f01-41fc-b762-17e991bafa95.jpg)
![20211226121310_1](https://user-images.githubusercontent.com/59480223/147406300-76f24e9e-e8c1-42f8-8d1a-0f162f330b4b.jpg)

Kollisionshöhe Original

**Comment by BigBlackBahamut** [comment]
Also, egal was ich versuche. Irgendwie bleibt der Abfahrer im Feld stehen. So macht es gerade keinen Sinn mit dem AD. Das nimmt mehr Zeit in Kauf als ohne AD.... Ideen wären wirklich hilfreich....

**Comment by Stephan-S** [comment]
Da das hier etwas vom Thema abkommt mache ich das mal zu

**Comment by BigBlackBahamut** [comment]
Eigentlich nicht da es um den Abfahrer ging, zuletzt weil er gar nicht mehr nach dem abtanken los fahren wollte.

Aber ja, es lag wirklich am Rohr. Das zu frühe einfahren des Rohres lässt den Abfahrer einfach stehen.
