### ISSUE TITLE
Sending to Repair/Refuel or Parking ignores Automatic Cover Setting

### ISSUE THREAD

**Issue by PapaTim68** [Stephan-S/FS22_AutoDrive#970]
Version: 2.0.1.2
Dedicated Server (assuming not relevant in this case)

Using hotkeys to send a Driver to repair, refuel, or to its park position ignores the vehicle's automatic cover setting and closes the covers of attached trailers. This can cause problems when the closed covers are not noticed the next time the trailer/vehicle is used.
While not strictly a bug, it's unexpected behaviour.

I hope this can be fixed.

Grüße,
PapaTim68

**Comment by Iwan1803** [comment]
So you deactivated the cover settings but this will be ignored?

**Comment by PapaTim68** [comment]
Exactly, the automatic cover usage is disabled and the cover shouldn't be operated by the helper.
I hope that cleared up the confusion.

**Comment by Axel32019** [comment]
@Iwan1803 Could you try it on dedi? Drive to a destination should be sufficient.

**Comment by Iwan1803** [comment]
Tested on Dedi with Strautmann Magnon and Bredal K165, cover stays allways open while driving to a target, sending manually to repair and also if AD drives automatically to a repair trigger.

**Comment by Axel32019** [comment]
no update -> closed
