### ISSUE TITLE
suggestion: change the download link in the readme

### ISSUE THREAD

**Issue by jeabakker** [Stephan-S/FS22_AutoDrive#971]
As I see it when you release a new version you also have to change the download link in the ReadMe.
https://github.com/Stephan-S/FS22_AutoDrive/blob/e9084e7392e492f0df08d0dc772de46d1ab18deb/README.md?plain=1#L7
If you change the download link to 
```
https://github.com/Stephan-S/FS22_AutoDrive/releases/latest/download/FS22_AutoDrive.zip
```
No need to do that every release ;)

**Comment by Iwan1803** [comment]
That's a good idea, thanks!
