### ISSUE TITLE
Spanngute von UniversalAutoload werden am Entlade-Wegpunkt nicht gelöst.

### ISSUE THREAD

**Issue by Flextt** [Stephan-S/FS22_AutoDrive#974]
Das Problem tritt bei mir auf Haut-Beyleron mit dem Anhänger Farmtech DPW 1800 beim Versuch auf, 220cm Quaderballen mit Silage am BGA zu entladen. Solange die Spanngurte nicht gelöst sind, kann der Anhänger nicht entladen werden und der Fahrer überfahrt erfolglos den Entlade-Wegpunkt.

Autodrive 2.0.1.2
UniversalAutoload 1.4.1.0

**Comment by Flextt** [comment]
No change for the better in AD2.0.1.4. Video and picture material from the creator of UAL and myself can be found [here](https://github.com/loki79uk/FS22_UniversalAutoload/issues/204).

**Comment by Axel32019** [comment]
handled in mentioned issue -> closed here
