### ISSUE TITLE
Goweil Stationary causes crash

### ISSUE THREAD

**Issue by pierrehicks** [Stephan-S/FS22_AutoDrive#976]
Is anyone else having a problem with the Goweil stationary balers? Every time I try to set a waypoint at the baler it crashes the game. I've tried it on multiple maps and both 2.0.1.0 and .4

**Comment by Iwan1803** [comment]
Screenshots? Log.txt?

**Comment by pierrehicks** [comment]
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/12509244/log.txt)
![Screenshot (17)](https://github.com/Stephan-S/FS22_AutoDrive/assets/61533783/fee36390-d8cf-47e2-8190-317ba7827980)
It also appears that when I reload the save it works fine for a little bit but at some point it has a fit and the next time I enter and leave a menu the game crashes especially if its an autodrive menu like the settings or adding/changing a waypoint.

**Comment by Axel32019** [comment]
Beside several errors, I do not see any AD related error.
Try whatever you want to do with detached Goeweil and report.

**Comment by pierrehicks** [comment]
It seems that with the goweil detached the issue doesn't appear. I was also able to use this setup for a long time today with the problem not happening until a few hours later while in the past it was very soon after trying to create the course or shortly after loading with the course already made. This time it didn't straight up crash but frames dropped to probably around 10-15. I'll do some more testing tomorrow as well.

**Comment by Axel32019** [comment]
no update -> closed
