### ISSUE TITLE
Turn off drive to refuel for harvesters setting option

### ISSUE THREAD

**Issue by coatsy35** [Stephan-S/FS22_AutoDrive#977]
Would it be possible to include a setting to turn off auto fuelling for harvesters? So combines do not try and leave the field and get stuck. I usually go to them with a fuel trailer to fill them up but sometimes I miss one and they usually get stuck in strange places. Would be nice to have a setting to turn harvesters off so they just stay where they are when they run out of fuel.

**Comment by judg393** [comment]
You can do this individually by turning off the setting. It's per vehicle unless you set it to default then it will copy the default settings for every vehicle you buy after setting default
