### ISSUE TITLE
"Show help in F1 Menu" setting is getting ignored.

### ISSUE THREAD

**Issue by Mike1977** [Stephan-S/FS22_AutoDrive#980]
I wonder if it's just me, because nobody has reported on this yet, but for some reasons the "show help" setting is getting ignored for me. Sometimes its reversed, so if i set "no" and it is still shown, i switch to "yes" and its off. Sometimes it doesnt matter what i set, it will always show the help in the F1 menu. It is different for different vehicles. 

While writing these lines i just noticed that the help entries for AD appear as soon as i activate a course in courseplay. When i stop the course, the AD Entrys in the Help menu dissapear. Strange. But maybe they just rearrange and are pushed out of sight that way. Im not sure since the amount of entrys shown in the menu are limited.

**Comment by andreasthu** [comment]
set this, it will take effect when you "tab" in a other vehicle.
turn "show help" on or of and you stay in the same vehicle it change nothing i nthe F1 menü - only when you tab in the next vehicle.
lg
andreas

**Comment by Mike1977** [comment]
Sorry, but no. I sit in a vehicle, hit settings in AD, switch "show help" to "no" get out of settings and tab to through the vehicles until im back at the one where i have the help lines in the F1 Menu. And its still there. This is pretty messed up right there.

**Comment by themadgunman** [comment]
Have exactly the same problem, i turned AD help off 2 days ago, its still showing in my F1 menu

**Comment by SirGarnet** [comment]
Help = YES
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/3258297/86f554e3-0f8d-405a-9831-1d5692805c8f)

Help = NO
![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/3258297/f241d936-f6bb-4405-849f-81dc53931cb6)

In between I tabbed back (CTRL + TAB) and forward (TAB) to get back to the current vehicle. It looks okay for me.

**Comment by Mike1977** [comment]
> Help = YES ![image](https://user-images.githubusercontent.com/3258297/269052701-86f554e3-0f8d-405a-9831-1d5692805c8f.png)
> 
> Help = NO ![image](https://user-images.githubusercontent.com/3258297/269052614-f241d936-f6bb-4405-849f-81dc53931cb6.png)
> 
> In between I tabbed back (CTRL + TAB) and forward (TAB) to get back to the current vehicle. It looks okay for me.

Can you do me a favor and try to comfirm the following:
Sit it the vehicle, generate a fieldcourse with courseplay, then with disabled help for AD, start the course on courseplay.
Because thats the moment when ad starts to ignore the setting for me. 
And please use this mod to make sure there are really no help entrys for AD: https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=275113

**Comment by SirGarnet** [comment]
Yes you are right, I had help turned off. After I created a course with CP and started the fieldwork, the help points of AD are shown and the option of AD it completely ignored. On/Off is the same, help is always shown also on vehicles that are only controlled by AD.

**Comment by Mike1977** [comment]
Thank you very much... So this seems to be an actual issue and is not just on my side.

**Comment by Tensuko** [comment]
Did anyone of you checked this:
Turn off the setting, get out of the vehicle and get back in. Help is gone.
It never came back for me.
And thats the question why got to leave the vehicle to have that setting actual take effect.

There is no touching AD settings in CP, rather a missing refresh or something on AD.

Also: only AD in folder:
3 tractors, sit in one, turn it off and tab through all and see where it is on and where its off.

**Comment by SirGarnet** [comment]
Link only works for 2 days...
[https://streamable.com/p9ax8w](https://streamable.com/p9ax8w)

Only Mods:
AD: 2.0.1.4
CP: 7.3.0.3

**Comment by Tensuko** [comment]
Without get into esc and ai map but directly jump into the generator by clicking on no course?

**Comment by SirGarnet** [comment]
> Without get into esc and ai map but directly jump into the generator by clicking on no course?

Like this: [https://streamable.com/ecdt1k](https://streamable.com/ecdt1k)

**Comment by Tensuko** [comment]
I will do the testing later. This leads nowhere. You got to start small and figure out from where.

**Comment by Tensuko** [comment]
Now tell me its CP Problem :)
https://drive.google.com/file/d/1OCi9tG1dS-Rb-GJ5mRvUPHCAjcLPmo7j/view?usp=sharing

With only AD and a complete reset inputBiding (so I have AD keybinds again) you can see I turn off the Help Menu (with only AD in mod folder!) and other AD input bindings come up.

The reason you see AD input bindings when you start CP (generate course doesn't matter at all) is that while CP is running, other keybinds disappear and the AD input bidnings you could not see because the list was too long now suddenly appears.

So here is the AD Problem that the F1 Help Menu setting does NOT affect all keybinds shown in F1 Menu.

@Axel32019 You may have a look there.

**Comment by Tensuko** [comment]
You may use this while experimenting to get more key binds shown. https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=275113&title=fs2022

**Comment by SirGarnet** [comment]
@Tensuko It' a CP problem :o)

**Comment by Iwan1803** [comment]
@Axel32019 please have a look at Tensuko his video. Looks like not all F1 menu will be hidden.

**Comment by SirGarnet** [comment]
> Now tell me its CP Problem :) https://drive.google.com/file/d/1OCi9tG1dS-Rb-GJ5mRvUPHCAjcLPmo7j/view?usp=sharing
> 
> With only AD and a complete reset inputBiding (so I have AD keybinds again) you can see I turn off the Help Menu (with only AD in mod folder!) and other AD input bindings come up.
> 
> The reason you see AD input bindings when you start CP (generate course doesn't matter at all) is that while CP is running, other keybinds disappear and the AD input bidnings you could not see because the list was too long now suddenly appears.
> 
> So here is the AD Problem that the F1 Help Menu setting does NOT affect all keybinds shown in F1 Menu.
> 
> @Axel32019 You may have a look there.

To be fair, it's not visible in your video. You turn of the bindings at 16 seconds and after exiting the tractor and jump back in there no AD help shown till the end of the video. Even if the list of F1-Menu is very short. Don't know if you uploaded the wrong video file. And I still wonder how you were able to open CP if you only hat AD in you mods.

Both of my videos shows the problem better even if my root reason was wrong.

**Comment by Tensuko** [comment]
Oh wait, maybe I posted the wrong Video....
https://drive.google.com/file/d/1zwr50mcKEg3XaYUUJ8DFok9s0Dx-MQD6/view?usp=sharing
