### ISSUE TITLE
Autodrive Übergabe an Curseplay

### ISSUE THREAD

**Issue by Selyria** [Stephan-S/FS22_AutoDrive#983]
Ich habe ein Problem, das, wenn ich Autodrive sage, fahr zu Feld .. und übergib dann an Curseplay fährt Curseplay zum letzten Wegpunkt. Ich habe kein plan welcher der beiden Mods da was falsch macht.

**Comment by rohne83** [comment]
Sehr dürftige Beschreibung für einen angeblichen Fehler, so ohne Log und Screenshots.
Höchstwahrscheinlich aber eh falsche Bedienung. Wie startest du das denn?
Damit AD genutzt wird, darfst du den Helfer auch nur im AD-Hud starten und nicht im CP-Hud oder Helfermenü, CP-Button im AD-Hud drücken und dann Feuer.

**Comment by 60erjonny** [comment]
@Selyria ...hatte ich neulich auch, den Kurs am Fahrzeug in CP rausnehmen und neu laden, dann ging es bei mir wieder. Also kein AD-Problem wie ich meine...

**Comment by Selyria** [comment]
@60erjonny alles klar werde ich mal versuchen.

Also ich starte autodrive und sage ihm fahr zu Feld .... und stelle dann autodrive so ein das er Übergabe an Curseplay machen soll das passiert auch aber irgendwie fährt Curseplay dann zum letzten punkt auf der route. Ich versuch die tage mal ein Video mit log hochzuladen.

**Comment by Selyria** [comment]
Okay wenn man wie @60erjonny es geschrieben hat den kurz neu Lädt klappt alles Problemlos Autodrive gibt an CP ab und danach passiert erst der Fehler wenn man nicht den kurz neu Lädt nach einem Server Restart. Eher ein CP Fehler als AD
