### ISSUE TITLE
[bug]  AD allways filling tools before job, make it option in settings?

### ISSUE THREAD

**Issue by aadje93** [Stephan-S/FS22_AutoDrive#985]
I have a lot of small fields next to each other on "The Valley the old farm" from Blacksheep modding. But when i use the load mode combined with courseplay field course its allways driving back to the set location of loading (middle option) before starting the job in the field. Would it be possible to just start the field course right away (top option) and then after tool is empty go for a load?

**Comment by rohne83** [comment]
In AD vehicle settings there's a setting like drive on at x %. Set this to a very low value (i.e. 0%) and it will go directly to the field instead of filling up before

**Comment by Axel32019** [comment]
One option as @rohne83 mentioned, second is to press continue after start AD
