### ISSUE TITLE
[Bug] console command "restartMySavegame" not working

### ISSUE THREAD

**Issue by Efratror** [Stephan-S/FS22_AutoDrive#986]
The console command "RestartMySavegame" added by this mod gives an warning when used. It complains about expecting a "Bool" and getting a "String". See below screenshot of the message.

![image](https://github.com/Stephan-S/FS22_AutoDrive/assets/19653269/6c7fe966-c24e-44be-af7b-f5ccb8b37da7)

This seems to be a remnant of FS19 as stated by [this](https://gdn.giants-software.com/thread.php?categoryId=3&threadId=9426) post on the giants forum under item 6. Swapping the bool and the string around in ["AutoDrive.lua"](https://github.com/Stephan-S/FS22_AutoDrive/blob/1eb6f653982328d850be3bec0718c3a48fadde13/scripts/AutoDrive.lua#L147-L161) should fix the issue.

A PR is on it's way

**Comment by Axel32019** [comment]
@Iwan1803 fixed with #987
