### ISSUE TITLE
Ingame Kursmanager speichert keine Kurse ab

### ISSUE THREAD

**Issue by LSMT-elMatador** [Stephan-S/FS22_AutoDrive#988]
Hallo,

wenn ich ingame über das Diskettensymbol einen kurs speichern möchte, und diesen dann wieder lade, bekomme ich eine leere Map!

**Comment by LSMT-elMatador** [comment]
Fehler gefunden. Wenn man den Kurs im Kursmanager nur "Start" nennt, wird nichts abgespeichert!

**Comment by Iwan1803** [comment]
@Axel32019 vielleicht kannst du ja mal einen Blick drauf werfen, warum der Name zum Problem führt.
Ansonsten mache ich hier erstmal zu.

**Comment by Axel32019** [comment]
@Iwan1803 @LSMT-elMatador Kann ich nicht nachvollziehen, auch mit "Start" nicht.
Falls weitere Untersuchung gewünscht folgendes nach Auftreten hier einfügen:
kompletten Ordner: modSettings\FS22_AutoDrive
log.txt, AutoDrive_config.xml, AutoDrive_config.xml, vehicles.xml
