### ISSUE TITLE
Unable to get AD course to operate

### ISSUE THREAD

**Issue by caracarn3** [Stephan-S/FS22_AutoDrive#99]
Been spending the last hour trying to trouble shoot why AD cannot get me from one point to another.   With the point I am connected to here I can find the spot.   If I move back one I get unable to find path.   These courses are the auto generated network.   It seems as if I delete the correct point and then replace it works but trying to avoid just building a new network myself as using your auto generated would be best.
![image](https://user-images.githubusercontent.com/24917927/147352107-f2184d76-62db-4490-b163-191509855e70.png)
![image](https://user-images.githubusercontent.com/24917927/147352306-a9c26c99-1c86-47fe-a89d-91ef30e6da78.png)

Then if I back up and try it again it works,  Then try to back up to previous point and it rebreaks the point that had just worked.   Not deleting the point just toggling the on and off again.   So it seems to have the course, then the course gets broken.

**Comment by rohne83** [comment]
Is this an automatically generated route network? With this it sometimes happens that several waypoints have the exact same position, and there's no connection between those waypoints (so a starting and and ending dead end on exact same position). That way it looks like your network is ok, and you don't even see the red X as all waypoints have at least one connection to any other point, but in fact you still have dead ends and your tractor cannot find a continuous path.
So you still have to rework those networks manually, check for those dead ends and remediate these yourself.

**Comment by caracarn3** [comment]
> Is this an automatically generated route network? With this it sometimes happens that several waypoints have the exact same position, and there's no connection between those waypoints (so a starting and and ending dead end on exact same position). That way it looks like your network is ok, and you don't even see the red X as all waypoints have at least one connection to any other point, but in fact you still have dead ends and your tractor cannot find a continuous path. So you still have to rework those networks manually, check for those dead ends and remediate these yourself.

Yes, I fully understand that.   My point is that even after remediating they cycle to broken again.   I used AD extensively for very complex operations in FS19 so certainly confident in my operation and troubleshooting.    The network toggles off working and not working.   If a video is needed can possibly provide that or may just go back to manually creating all parts of the network, and see if that solves it.   I spent an hour to "rework those networks manually" and only then did I post here.

**Comment by Bobster82** [comment]
Hi, Did you try to turn on the debug setting 'road network' and check the map? It shows you all the dead ends of the routes, easy finding not connecten points ;)

**Comment by rohne83** [comment]
Are you sure your remediations to the network got saved correctly? I experienced myself that I reworked the network, pressed save but when loading it was still the old network. Not figured out yet how to reproduce but it happens from time to time. So maybe your changes didn't get saved and you still have a "buggy" network. Only way to prevent this is to save really regularly and from time to time reloading the network, to check whether your last changes got saved indeed.

**Comment by Crinkly-the-grey** [comment]
Hi, First off, seasons greetings.
   I had exactly the same problem on the Haut-Beyeleron map. I spent so much time trying to find all the bad connections, that I restarted without loading the default routes, I then created them all in Autodrive 2.0.0.2
   I was spending more time fixing issues than farming initially.
   It took me about 6 hours, however I feel that it was well worth the effort, I spent time tweaking corners etc., running routes through fuel stations and lime stations. My vehicles no longer get stuck on lampposts etc. All I have to do now, is set my field loading positions as each field is ready for harvest.
   If you are like me and start new games fairly often you may want to consider this option.
   I have not played Elmcreek yet, but I will do the same when I do.
