### ISSUE TITLE
Multiselect Fruchttyp wird nicht aktualisiert

### ISSUE THREAD

**Issue by SirGarnet** [Stephan-S/FS22_AutoDrive#990]
Hallo,

ich bin folgend vorgegangen und habe ein kleines Problem gefunden:

1. Ich habe einen Traktor, der zuvor nur Kalk gefahren hat
2. Mit STRG + Klick Kalk abwählen und dann z.B. Weizen & Roggen anwählen
3. Zum verlassen des Drop-Down-Menüs, auf das AD-Hauptfenster klicken
4. Ziele setzen und los...

Das sieht dann so aus:
![Screenshot 2023-09-19 181556](https://github.com/Stephan-S/FS22_AutoDrive/assets/3258297/33041edf-bc6d-4366-8c84-493ce2474d13)

Wenn das Fahrzeug nun los geschickt wird, versucht es Kalk am Ladepunkt zu laden obwohl es nicht blau markiert ist, es aber immer noch im Drop-Down-Menü sichtbar ausgewählt ist.

![Screenshot 2023-09-19 181616](https://github.com/Stephan-S/FS22_AutoDrive/assets/3258297/ab974de5-b93c-4df3-b7f4-6ee145552ae5)

EDIT:
Version: 2.0.1.2

**Comment by Iwan1803** [comment]
Bist du sicher, das auch wirklich am Ladepunkt versucht wird, Kalk zu laden oder steht einfach nur "Kalk" unten noch drin?
Das Ladegut/Frucht wird nämlich erst am Ladepunkt gewechselt, wenn ich mich nicht ganz irre.
Ansonsten meine Empfehlung: erst von Kalk auf Weizen wechseln und danach erst den Multiselect vornehmen.

**Comment by SirGarnet** [comment]
Update ist schon drauf (seit gestern...) Ich teste es nachher nochmal und mache evtl. ein Video dazu und eine vollstänige Beschreibung wie es dazu gekommen ist.

**Comment by SirGarnet** [comment]
Hallo @Iwan1803,

hier das Video:
[https://drive.google.com/file/d/1FzKUFo4F5G3mdWKRfhdg5WPKSHrHnpSw/view?usp=sharing](https://drive.google.com/file/d/1FzKUFo4F5G3mdWKRfhdg5WPKSHrHnpSw/view?usp=sharing)

Was vorher geschah:
- Traktor hat nach Transport von _Kalk_ eingeparkt

Was im Video passiert:
- Traktor bekommt eine neue Aufgabe (Abholen & Liefern)
- Ladeziel und Entladeziel wird festgelegt
- Frucht wird gewählt, dabei wird die alte Frucht (_Kalk_) mit **STRG + KLICK** abgewählt, dann mit **STRG + KLICK** drei neue Fruchtsorten ausgewählt
- Es soll jeweils ein Anhänger transportiert werden, daher die drei gleichgroßen Ähren
- Traktor wird los geschickt
- Am Silo angekommen, ist zu sehen das am Ausgaberohr _Kalk_ animiert wird, jedoch keiner im Lager ist
- Die anderen Fruchttypen sind aber im Lager vorhanden

Habe es danach auch nochmals mit LoadByFilllevel getestet (zwei Ähren) jedoch mit dem gleichen Ergebnis. Da das Video aber so spannend war, habe ich hier nur den Screenshot vom Ergebnis für dich. Da sieht man den Kalk noch animiert...

![Farming Simulator 22 21 09 2023 18_13_46](https://github.com/Stephan-S/FS22_AutoDrive/assets/3258297/53193e56-48f9-4fb5-9e30-d28786aa9d6d)

**Comment by SirGarnet** [comment]
Er sagt aber auch, es sollte sich am Silo neu einstellen. Tut es in dem Fall aber nicht.

**Comment by regs1980** [comment]
Wie soll er das denn machen, wenn ein Ladegut noch im Fahrzeugspeicher drin ist, was es nicht in dem Silo mehr gibt.
Vielleicht sollte man bei der Beschreibung noch was dazu schreiben, dass man erst ein Ladegut wählt, was man laden will und dann die Multiselektion durchführt, um weiter Ladegüter auszuwählen. 
Das würden solche Fehler vermeiden oder man bearbeitet den Code noch mal.

**Comment by SirGarnet** [comment]
So kann immer noch das selbe Problem entstehen. Wenn die erste gewählte Frucht beim Multiselect wieder abgewählt wird.

**Comment by SirGarnet** [comment]
Oder es wird in der Software so angepasst, wie @Iwan1803 sagte, dass die Validierung des Ladeguts beim ankommen am Silo gemacht wird - was gerade wohl nicht immer der Fall ist. Damit sind dann auch viele der unnötig gestellten Tickets vermieden, sowie unnötige _Leerfahrten_. Für diese muss dann manuell wieder die Anzahl der Wiederholungen angepasst werden, da eine _Leerfahrt_ abgezogen wird.

**Comment by ThomasMatern** [comment]
@SirGarnet das Ladegut wird in der Tat erst am Silo validiert. Ich vermute die Ladegutauswahl ist etwas verwirrt, weil nach dem abwaehlen von Kalk "nichts" ausgewaehlt ist. Ich schaue mir das heute abend mal an.

**Comment by SirGarnet** [comment]
@ThomasMatern Dankeschön, kann ja nicht so kompliziert sein nehme ich an

@regs1980 Warum hast du denn deinen Kommentar gelöscht, sieht ja aus als ob ich hier Selbstgespräche führe.

**Comment by regs1980** [comment]
Weil es behoben wird und es funktioniert sehr gut.

**Comment by Axel32019** [comment]
@Iwan1803 fixed with #997
