### ISSUE TITLE
[Verbesserungsvorschlag] Textfarbe/Textfeldhintergrund

### ISSUE THREAD

**Issue by Onkel2000** [Stephan-S/FS22_AutoDrive#991]
Hallo, 

ist es irgendwie möglich die Textfarbe, oder das blaue Hintergrundfeld zu ändern? z.b. bei Ziel-Namen eingaben. Da  ich leider sehr Seheingeschränkt bin, ist es mir unmöglich zusehen was ich dort eingebe, da sich der Text nicht abhebt vom Kontrast / Hintergrund.

![20230921012234_1](https://github.com/Stephan-S/FS22_AutoDrive/assets/53871930/e4aa9e4c-07a0-49cc-aab8-269599659093)

**Comment by Axel32019** [comment]
Hallo @Onkel2000 , Diese ist leider fest von Giants vorgegeben und nicht von AD definiert.
Als "Hack" kann ich nur diese Auswahl anbieten: https://github.com/Stephan-S/FS19_AutoDrive/wiki/Release-Notes#new-color-assignment-for-users-with-different-color-perception
Deutsch ab ca. 12:00 https://www.youtube.com/watch?v=RP1USIKGxMc&list=PL5cOkXj5isconfMMPvBVCkAMh0AepBvey&index=23

**Comment by Onkel2000** [comment]
Habs mir schon fast gedacht. Leider ist das mit dem "Hack" keine lösung. Ich bin schon sehr Daankbar für die Linien-Skalierung, würde am liebsten sogar mehr als 1000% nehmen. Mit dem Wert ist es aber wirklich schon gut machbar. Da muss ich mir für mein Problem etwas einfallen lassen. 

Danke für deine Mühe :)

**Comment by Axel32019** [comment]
@Onkel2000 Was würde Dir denn helfen? Als Nicht-Betroffener ist das sehr schwer vorstellbar...
Die Linien-Skalierung lässt sich noch erhöhen - Kannste ja schon mal bisschen probieren:
In Settings.lua einfach erweitern:
```
AutoDrive.settings.scaleLines = {
    values = {0.5, 1, 2, 3, 4, 5, 6, 10},
    texts = {"50%", "100%", "200%", "300%", "400%", "500%", "600%", "1000%"},
```

**Comment by Onkel2000** [comment]
@Axel32019 Es ist schwer es sich vorzustellen, genauso es zu beschreiben. Mirwürde es helfen .mit einem Akustischem Feedback welche Taste gedrückt wurde. Dies ist aber mit Sicherheit denn aufwand nicht wert. Vielleicht gibt es eine möglichkeit über einen Mod das blau vom LS dunkel zubekommen, da kenne ich mich leider null aus.

Komischerweise kann ich im LS Menü die schrift lesen, mit Windows Lupe auf ca.700-1000% vergrößerung. Leider bei AD und CP keine Chance. Hab auch mit Bildscbirmeinstellungen, alles erdenklich ausprobiert. Es betrifft ja wirklich nur das Texteingabefeld.

Im AD Hud habe ich ,mir die obere blaue Headerleiste schwarz gemacht, dann hört es leider bei mir auch scghon auf. Ich kann im Hud mit der Windpwslupe alles gut einstellen. Klar je größer der Text, desto besser.

Dank AD und CP bin ich sehr gut in der Lage LS zu spielen. 1000 Dank dafür!

**Comment by Axel32019** [comment]
Hab das mal zusammengebaut:
Skalierung bis 10k und die Farbwahl ist Nummer 17. Probier's mal.
[FS22_AutoDrive.zip](https://github.com/Stephan-S/FS22_AutoDrive/files/12730938/FS22_AutoDrive.zip)

**Comment by Onkel2000** [comment]
@Axel32019 Das mit der Skalierung ist wirklich super, danke.
Was meinst du mit der Farbnummer?

**Comment by Axel32019** [comment]
@Onkel2000 Wie oben geschrieben - schau Dir das mal an:
Deutsch ab ca. 12:00 https://www.youtube.com/watch?v=RP1USIKGxMc&list=PL5cOkXj5isconfMMPvBVCkAMh0AepBvey&index=23
Damit kannst Du das hellblau in andere Farben selbst ändern.

**Comment by Onkel2000** [comment]
@Axel32019 Ultra dies Hilft mir enorm. Du/Ihr seid einfach Klasse. Leider ändert es nur für AD, aber ein riesen Problem weniger.

Kleine Frage noch: Wie realistisch ist es eine "Text to Speech" Option für die AD-Benachrichtigungsfenster einzubauen?

Wirklich tausend Dank für die Mühe!

**Comment by Axel32019** [comment]
@Onkel2000 TTS ist ein unglaulicher Aufwand, daher sehe ich dafür in absehbarer Zeit keine Möglichkeit dafür.
