### ISSUE TITLE
Abtankrohr von Überladewagen

### ISSUE THREAD

**Issue by JuniorKDK** [Stephan-S/FS22_AutoDrive#992]
Gibt es eine Möglichkeit, das Rohr von einem Überladewagen, der nur auf dem Feld unterwegs ist bei aktivierten AutoDrive ausgeklappt zu lassen? Die Funktion "Fold Implement" hat auf das Abtankrohr keinen Einfluss.

**Comment by Axel32019** [comment]
Nein.
