### ISSUE TITLE
Wiederholungen per Mausrad ändern

### ISSUE THREAD

**Issue by SirGarnet** [Stephan-S/FS22_AutoDrive#993]
Hallo,

derzeit ist es so, dass in der Standardeinstellung die Wiederholungen mit Link-/Rechtsklick geändert werden. Jedoch ist ja die rechte Maustaste im Standard bei CP hinterlegt.

Es wäre schön, wenn die Wiederholungen - wie die Geschwindigkeitsbegrenzung - mit dem Mausrad eingestellt werden könnten. Dann ist damit auch eine konsistente Interaktion im HUD und auf allen drei Schaltflächen (Wiederholungen / Straßengeschwindigkeit / Feldgeschwindigkeit) welche veränderbare Zahlen haben.

**Comment by SirGarnet** [comment]
In dem Zuge wäre es evtl. auch schick den Maxiamlwert (derzeit 9) zu erhöhen, da mit dem Mausrad geht es auch etwas flinker.

**Comment by regs1980** [comment]
https://github.com/Stephan-S/FS22_AutoDrive/pull/1000#issue-1920115022

**Comment by Axel32019** [comment]
@Iwan1803 fixed with #1000
