### ISSUE TITLE
Bale Unload Problem

### ISSUE THREAD

**Issue by batuorhungunduz** [Stephan-S/FS22_AutoDrive#994]
Hello everyone. I cannot get autodrive to automatically unload the bale trailers for some reason. I am doing this in the "american farmlands" map. I used both the small and large arcusins and the anderson loaders with no luck. Both the bale storage from "michigan shed pack" nor the bale sale point of the map seem to work. I tried doing similar things in other maps before but havent had any luck. What could be the issue? Thanks in advance.
![resim](https://github.com/Stephan-S/FS22_AutoDrive/assets/35929119/078d8259-1517-4ea0-8821-88559a10c857)
![resim](https://github.com/Stephan-S/FS22_AutoDrive/assets/35929119/01e37ff5-21fe-4cca-adaa-a22c6735100b)

**Comment by regs1980** [comment]
Update your AD version and CP as well.

**Comment by batuorhungunduz** [comment]
Works great, thanks. Also works with non-vanilla bale loaders as well. (AD 2.0.1.0)
