### ISSUE TITLE
Verteiltes Abladen bei Ausfahrtstrategie "Nächstgelegen" funktioniert nicht

### ISSUE THREAD

**Issue by RedGun1978** [Stephan-S/FS22_AutoDrive#998]
Wenn Feldausfahrt "nächstgelegen" eingestellt ist, werden bei verteilten Abfahren die Ziele im Ordner nicht durch gewechselt. In meinem Fall: Trecker mit Ladewagen. CP wird genutzt zum Aufladen. Feldausfahrt nächstgelegen. 2 Ziele im Ordner. Siehe Video.
[log.txt](https://github.com/Stephan-S/FS22_AutoDrive/files/12742139/log.txt)
https://workupload.com/file/BKQxkMAX9rR

**Comment by 60erjonny** [comment]
Passiert es denn im Umkehrschluß, wenn du es auf "Standart" stellts?

**Comment by RedGun1978** [comment]
Ja. es sind exact 2 Ziele im Ordner. Bahn Links und Bahn Rechts. Die Einstellungen sind im HUD ersichtlich. Nächstgelegen und verteiltes Abladen. Oder welche Einstellungen hättest du den gerne?  Bei Standard und hinterm Start funktionierts.

**Comment by 60erjonny** [comment]
Ging es denn, mit einer älteren Version?

**Comment by Axel32019** [comment]
@RedGun1978 Bitte mal die AutoDrive_config.xml gezippt einfügen.

**Comment by RedGun1978** [comment]
@Axel32019  ich werde dir die xml per PN im Discord schicken, da weder der Kurs noch die Map bisher öffentlich ist.

**Comment by KarlGutenberg** [comment]
Hallo und sorry wenn ich mich melde!
Aber wurde den auch Rotieren in die Einstellung gemacht?
